// ============================================================
// Group 1 Quiz Data: Months / Days / Time Units / Seasons
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 1 - Months / Days / Time Units / Seasons (月份/星期/時間單位/季節)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice ----
// sentence: English with {{BLANK}} marker where the word goes
// cn: full Chinese translation (target word NOT bracketed here; shown plainly as part of the sentence)
const VOCAB = [
  { word: "January", pos: "n.", cn_def: "一月", en_def: "the first month of the year",
    sentence: "My family always visits my grandparents in {{BLANK}} because we celebrate New Year together and eat a big dinner.",
    cn: "我家總是在一月拜訪我的祖父母，因為我們會一起慶祝新年並吃一頓豐盛的晚餐。" },
  { word: "February", pos: "n.", cn_def: "二月", en_def: "the second month of the year",
    sentence: "Valentine's Day falls in {{BLANK}}, so my brother always buys flowers for his girlfriend that month.",
    cn: "情人節在二月，所以我哥哥那個月總是會買花給他的女朋友。" },
  { word: "March", pos: "n.", cn_def: "三月", en_def: "the third month of the year",
    sentence: "The weather starts to get warmer in {{BLANK}}, so people begin to take off their heavy winter coats.",
    cn: "天氣在三月開始變暖，所以人們開始脫掉他們厚重的冬天大衣。" },
  { word: "April", pos: "n.", cn_def: "四月", en_def: "the fourth month of the year",
    sentence: "It often rains a lot in {{BLANK}}, so I always carry an umbrella with me when I leave home.",
    cn: "四月常常下很多雨，所以我離家時總是隨身帶著一把雨傘。" },
  { word: "May", pos: "n.", cn_def: "五月", en_def: "the fifth month of the year",
    sentence: "School trips are usually planned for {{BLANK}} because the weather is nice and not too hot yet.",
    cn: "校外教學通常安排在五月，因為天氣很好而且還不會太熱。" },
  { word: "June", pos: "n.", cn_def: "六月", en_def: "the sixth month of the year",
    sentence: "Most students in Taiwan finish their final exams in {{BLANK}} and then start their long summer vacation.",
    cn: "台灣大部分的學生在六月考完期末考，然後就開始放他們的長暑假。" },
  { word: "July", pos: "n.", cn_def: "七月", en_def: "the seventh month of the year",
    sentence: "My family usually goes to the beach in {{BLANK}} because the weather is hot and the water feels great.",
    cn: "我家通常在七月去海邊，因為天氣很熱，海水感覺很棒。" },
  { word: "August", pos: "n.", cn_def: "八月", en_def: "the eighth month of the year",
    sentence: "Many typhoons hit Taiwan in {{BLANK}}, so people often need to prepare food and water at home.",
    cn: "許多颱風在八月侵襲台灣，所以人們常常需要在家準備食物和水。" },
  { word: "September", pos: "n.", cn_def: "九月", en_def: "the ninth month of the year",
    sentence: "The new school year starts in {{BLANK}}, so students need to buy new books and uniforms.",
    cn: "新學年在九月開始，所以學生們需要買新的書和制服。" },
  { word: "October", pos: "n.", cn_def: "十月", en_def: "the tenth month of the year",
    sentence: "The weather becomes cool and comfortable in {{BLANK}}, which makes it a great time for outdoor activities.",
    cn: "天氣在十月變得涼爽又舒適，這讓它成為從事戶外活動的好時機。" },
  { word: "November", pos: "n.", cn_def: "十一月", en_def: "the eleventh month of the year",
    sentence: "My uncle's birthday is in {{BLANK}}, so we always plan a small party for him near the end of that month.",
    cn: "我叔叔的生日在十一月，所以我們總是在那個月底為他計劃一個小派對。" },
  { word: "December", pos: "n.", cn_def: "十二月", en_def: "the twelfth month of the year",
    sentence: "Many shops put up colorful lights and decorations in {{BLANK}} to celebrate Christmas with their customers.",
    cn: "許多商店在十二月掛上色彩鮮豔的燈飾和裝飾品，來和顧客一起慶祝聖誕節。" },
  { word: "Sunday", pos: "n.", cn_def: "星期日", en_def: "the first day of the week",
    sentence: "My whole family stays home and relaxes together on {{BLANK}} before a new busy week begins.",
    cn: "在新的忙碌一週開始之前，我全家人會在星期日待在家裡一起放鬆。" },
  { word: "Monday", pos: "n.", cn_def: "星期一", en_def: "the day after Sunday",
    sentence: "I always feel a little tired on {{BLANK}} because the weekend break is already over.",
    cn: "我在星期一總是覺得有點累，因為週末的假期已經結束了。" },
  { word: "Tuesday", pos: "n.", cn_def: "星期二", en_def: "the day after Monday",
    sentence: "Our English class meets every {{BLANK}} afternoon, so I need to bring my textbook on that day.",
    cn: "我們的英文課每星期二下午上課，所以我那天需要帶課本。" },
  { word: "Wednesday", pos: "n.", cn_def: "星期三", en_def: "the day after Tuesday",
    sentence: "The school cafeteria usually serves noodles on {{BLANK}}, which is one of my favorite lunches.",
    cn: "學校餐廳通常在星期三供應麵食，那是我最喜歡的午餐之一。" },
  { word: "Thursday", pos: "n.", cn_def: "星期四", en_def: "the day after Wednesday",
    sentence: "My basketball practice is held every {{BLANK}} evening, right after I finish my homework.",
    cn: "我的籃球練習在每星期四晚上舉行，就在我做完功課之後。" },
  { word: "Friday", pos: "n.", cn_def: "星期五", en_def: "the day after Thursday",
    sentence: "Everyone in my class feels excited on {{BLANK}} because the weekend is finally about to start.",
    cn: "我班上每個人在星期五都感到很興奮，因為週末終於要開始了。" },
  { word: "Saturday", pos: "n.", cn_def: "星期六", en_def: "the last day of the week",
    sentence: "My parents take me to visit my grandmother every {{BLANK}} morning before we eat lunch together.",
    cn: "我父母每星期六早上都會帶我去拜訪我的奶奶，然後我們再一起吃午餐。" },
  { word: "week", pos: "n.", cn_def: "星期；週", en_def: "a period of seven days",
    sentence: "We have an English test every {{BLANK}}, so I need to study a little bit every single day.",
    cn: "我們每星期都有一次英文考試，所以我每一天都需要稍微讀一點書。" },
  { word: "weekday", pos: "n.", cn_def: "平日；週間", en_def: "any day except Saturday and Sunday",
    sentence: "I usually wake up at six thirty on a {{BLANK}} because my first class starts very early.",
    cn: "我平日通常六點半起床，因為我的第一堂課開始得很早。" },
  { word: "weekend", pos: "n.", cn_def: "週末", en_def: "Saturday and Sunday",
    sentence: "My family often goes hiking together on the {{BLANK}} when the weather is sunny and clear.",
    cn: "我家人常常在天氣晴朗的週末一起去爬山。" },
  { word: "season", pos: "n.", cn_def: "季節", en_def: "one of the four parts of the year",
    sentence: "Summer is my favorite {{BLANK}} because I can go swimming and eat cold desserts every day.",
    cn: "夏天是我最喜歡的季節，因為我可以每天去游泳並吃冰涼的甜點。" },
  { word: "spring", pos: "n.", cn_def: "春天", en_def: "the season after winter, when plants grow",
    sentence: "Many beautiful flowers start to bloom in {{BLANK}}, which makes the whole park look colorful and lively.",
    cn: "許多美麗的花朵在春天開始綻放，這讓整個公園看起來色彩繽紛又生氣勃勃。" },
  { word: "summer", pos: "n.", cn_def: "夏天", en_def: "the warmest season of the year",
    sentence: "The weather gets extremely hot in {{BLANK}}, so most people turn on their air conditioners all day.",
    cn: "天氣在夏天變得非常炎熱，所以大部分的人整天都開著冷氣。" },
  { word: "autumn", pos: "n.", cn_def: "秋天", en_def: "the season after summer, before winter",
    sentence: "The leaves on the trees turn yellow and red in {{BLANK}} before they slowly fall to the ground.",
    cn: "樹上的葉子在秋天會變成黃色和紅色，然後才慢慢掉落到地上。" },
  { word: "winter", pos: "n.", cn_def: "冬天", en_def: "the coldest season of the year",
    sentence: "It gets very cold in {{BLANK}}, so we need to wear thick coats and warm gloves outside.",
    cn: "天氣在冬天變得非常冷，所以我們在外面需要穿厚重的大衣和溫暖的手套。" }
];

// ---- Part 2 data: 30 MCQs ----
const MCQS = [
  { q: "Look at this year's calendar carefully and find the very beginning of it. The very first month of the whole year, right after December ends, is called ______.",
    options: ["June", "October", "March", "January"], answer: 3 },
  { q: "Many people give flowers and chocolate to someone special they love every year on Valentine's Day. This romantic and special day always falls in ______.",
    options: ["May", "August", "February", "November"], answer: 2 },
  { q: "The cold winter weather is finally ending outside, and small green leaves are starting to appear again on the bare trees. This refreshing change usually happens in ______.",
    options: ["July", "March", "September", "December"], answer: 1 },
  { q: "It rained almost every single day last week, so my shoes never had a chance to dry completely. This kind of wet weather is common in ______.",
    options: ["January", "June", "April", "October"], answer: 2 },
  { q: "Our teacher told us that the class trip to the science museum is planned for next month. She said the weather should still be cool and pleasant in ______.",
    options: ["February", "May", "August", "November"], answer: 1 },
  { q: "Most junior high students in Taiwan finish their final exams around the same time every year. After that, their long summer break usually begins in ______.",
    options: ["June", "March", "September", "December"], answer: 0 },
  { q: "The sun was so strong that everyone wanted to jump straight into the cool ocean water. My family always goes to the beach during ______.",
    options: ["January", "April", "October", "July"], answer: 3 },
  { q: "Strong winds and very heavy rain often hit the whole island again and again around the exact same time every single year. Most dangerous typhoons arrive in Taiwan during ______.",
    options: ["February", "May", "November", "August"], answer: 3 },
  { q: "After a long summer vacation, students put on their clean uniforms again and walk back to school. The new school year always begins in ______.",
    options: ["March", "June", "December", "September"], answer: 3 },
  { q: "The hot and tiring summer days are finally over, and the air outside feels cool, fresh, and comfortable once again. Many families enjoy long hiking trips during ______.",
    options: ["January", "April", "October", "July"], answer: 2 },
  { q: "My uncle always invites our whole family over for a small birthday dinner near the end of the eleventh month. His birthday falls in ______.",
    options: ["November", "February", "May", "August"], answer: 0 },
  { q: "Shopping streets all around the city are decorated with colorful lights, and cheerful Christmas songs play everywhere you go. These cozy holiday decorations usually appear in ______.",
    options: ["March", "December", "June", "September"], answer: 1 },
  { q: "After a busy week of school and homework, my whole family likes to stay home and relax together. We usually do this on ______, right before the new week starts.",
    options: ["Tuesday", "Thursday", "Sunday", "Saturday"], answer: 2 },
  { q: "The relaxing weekend always feels far too short, and getting up early again for school is never an easy thing to do. That's exactly how I feel every ______ morning.",
    options: ["Wednesday", "Monday", "Friday", "Sunday"], answer: 1 },
  { q: "I always remember to pack my thick green textbook in my school bag the night before. That's because my English class meets every ______ afternoon.",
    options: ["Monday", "Thursday", "Saturday", "Tuesday"], answer: 3 },
  { q: "The smell of warm noodle soup fills the school cafeteria in the middle of almost every week. It's one of my favorite lunches, and it's always served on ______.",
    options: ["Wednesday", "Friday", "Sunday", "Tuesday"], answer: 0 },
  { q: "Right after I finish all of my homework, I quickly grab my basketball shoes and head to the gym. My basketball practice happens every ______ evening.",
    options: ["Monday", "Wednesday", "Saturday", "Thursday"], answer: 3 },
  { q: "Everyone in my classroom starts smiling and chatting excitedly during the last class of the day. That's because the weekend is finally about to start on ______.",
    options: ["Tuesday", "Thursday", "Friday", "Sunday"], answer: 2 },
  { q: "My parents and I usually visit my elderly grandmother's house together in the morning, and then we all eat a nice lunch together. This happens almost every single ______.",
    options: ["Monday", "Wednesday", "Friday", "Saturday"], answer: 3 },
  { q: "Our English teacher gives us a short vocabulary test on the very same day, again and again, without fail. This test happens once every ______.",
    options: ["weekday", "weekend", "week", "season"], answer: 2 },
  { q: "My alarm clock rings at six thirty every single morning except Saturday and Sunday, because my first class starts very early. That's true on every ______.",
    options: ["week", "weekday", "weekend", "season"], answer: 1 },
  { q: "My family often packs a picnic lunch and drives to the mountains when the sky is sunny and clear. We almost always choose to go on the ______.",
    options: ["week", "weekday", "weekend", "season"], answer: 2 },
  { q: "There are four very different parts of the year, and each one brings its own weather and special activities. Each of these four parts is called a ______.",
    options: ["week", "weekday", "weekend", "season"], answer: 3 },
  { q: "Colorful flowers begin to bloom all over the park, and the cold air slowly turns warm and gentle again. This pleasant change usually happens in ______.",
    options: ["spring", "summer", "autumn", "winter"], answer: 0 },
  { q: "The air conditioner runs all day long because the sun is so strong and the temperature keeps rising higher and higher. This kind of extreme heat is typical of ______.",
    options: ["spring", "summer", "autumn", "winter"], answer: 1 },
  { q: "The bright green leaves on the trees slowly turn yellow and red before falling gently onto the ground below. This colorful change usually happens in ______.",
    options: ["autumn", "spring", "summer", "winter"], answer: 0 },
  { q: "Thick warm coats, soft gloves, and hot drinks all become absolutely necessary again because the outdoor temperature suddenly drops so low. People need these warm things most during ______.",
    options: ["spring", "winter", "summer", "autumn"], answer: 1 },
  { q: "Fireworks light up the night sky, and families gather together to celebrate the very beginning of a brand new year. This exciting celebration takes place every ______.",
    options: ["January", "April", "July", "October"], answer: 0 },
  { q: "There is no school at all, so I can finally sleep in late and watch cartoons all morning without worrying about homework. I always look forward to ______.",
    options: ["Monday", "Wednesday", "Friday", "Saturday"], answer: 3 },
  { q: "Children jump happily into the cool swimming pool almost every afternoon because school is out and the days feel endless. This joyful season is called ______.",
    options: ["summer", "spring", "autumn", "winter"], answer: 0 }
];

// ---- Word lookup definitions (for the lookup popup in Part 2) ----
const LOOKUP = {};
VOCAB.forEach(v => {
  LOOKUP[v.word.toLowerCase()] = { en_def: v.en_def, cn_def: v.cn_def, pos: v.pos };
});
