// ============================================================
// Group 33 Quiz Data: Actions, Part 2
// Full word set (36 words) — the second portion of the
// "actions" theme (252-word flat verb list). Continues from
// Group 32 (Actions, Part 1). Split into 7 groups of 36 words
// each (Groups 32-38) per the person's request.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 33 - Actions, Part 2 (動作 二)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (36 words) ----
const VOCAB = [
  { word: "sit", pos: "v.", cn_def: "坐", en_def: "to rest your body with your weight on your bottom",
    sentence: "Please {{BLANK}} quietly until the teacher finishes explaining the lesson.",
    cn: "請安靜地坐著，直到老師講解完這個課程。" },
  { word: "stand", pos: "v.", cn_def: "站", en_def: "to be on your feet in an upright position",
    sentence: "Everyone had to {{BLANK}} for almost an hour during the crowded concert.",
    cn: "在那場擁擠的演唱會上，每個人都必須站將近一個小時。" },
  { word: "sleep", pos: "v.", cn_def: "睡", en_def: "to rest with your eyes closed and your mind unaware",
    sentence: "Most teenagers need at least eight hours of {{BLANK}} every night.",
    cn: "大多數青少年每晚至少需要八小時的睡眠。" },
  { word: "wake", pos: "v.", cn_def: "醒來", en_def: "to stop sleeping and become alert",
    sentence: "I usually {{BLANK}} up before sunrise to go jogging with my dad.",
    cn: "我通常在日出前就醒來，跟我爸爸一起去跑步。" },
  { word: "act", pos: "v.", cn_def: "主演", en_def: "to perform a role in a play, movie, or show",
    sentence: "She was chosen to {{BLANK}} the leading role in the school play.",
    cn: "她被選為在學校戲劇中主演主角。" },
  { word: "add", pos: "v.", cn_def: "添加", en_def: "to put something together with something else",
    sentence: "My mother always likes to {{BLANK}} a little extra sugar to her tea.",
    cn: "我媽媽總是喜歡在茶裡多加一點糖。" },
  { word: "advise", pos: "v.", cn_def: "建議", en_def: "to give someone helpful suggestions about what to do",
    sentence: "The doctor decided to {{BLANK}} him to rest at home for a few days.",
    cn: "醫生決定建議他在家休息幾天。" },
  { word: "affect", pos: "v.", cn_def: "影響", en_def: "to have an influence on something or someone",
    sentence: "Too much noise at night can seriously {{BLANK}} how well you sleep.",
    cn: "晚上太多噪音會嚴重影響你的睡眠品質。" },
  { word: "agree", pos: "v.", cn_def: "同意", en_def: "to have the same opinion as someone else",
    sentence: "After a long discussion, both sides finally began to {{BLANK}} on a fair price.",
    cn: "經過長時間討論後，雙方終於就一個公平的價格達成同意。" },
  { word: "aim", pos: "v.", cn_def: "瞄準", en_def: "to point something carefully at a target",
    sentence: "He took a deep breath and tried to {{BLANK}} the arrow at the center.",
    cn: "他深吸一口氣，試著把箭瞄準靶心。" },
  { word: "allow", pos: "v.", cn_def: "允許", en_def: "to let someone do something or let something happen",
    sentence: "My parents finally decided to {{BLANK}} me to join the weekend hiking club.",
    cn: "我父母終於決定允許我加入週末健行社。" },
  { word: "apologize", pos: "v.", cn_def: "道歉", en_def: "to say you are sorry for something you did",
    sentence: "He called his friend right away to {{BLANK}} for arriving so late.",
    cn: "他立刻打電話給朋友，為了遲到道歉。" },
  { word: "argue", pos: "v.", cn_def: "爭論", en_def: "to talk angrily with someone because you disagree",
    sentence: "The two brothers began to {{BLANK}} loudly over who would use the computer first.",
    cn: "兩兄弟開始大聲爭論誰先用電腦。" },
  { word: "arrange", pos: "v.", cn_def: "安排", en_def: "to plan or organize something carefully",
    sentence: "Our teacher helped us {{BLANK}} the desks into small groups for the activity.",
    cn: "我們的老師幫忙我們把桌子安排成小組，以便進行活動。" },
  { word: "ask", pos: "v.", cn_def: "問", en_def: "to put a question to someone",
    sentence: "Feel free to {{BLANK}} the librarian if you can't find the book you need.",
    cn: "如果你找不到需要的書，可以隨時問圖書館員。" },
  { word: "attack", pos: "v.", cn_def: "進攻", en_def: "to use violence or force against someone or something",
    sentence: "The small village was once forced to {{BLANK}} by bandits long ago.",
    cn: "這座小村莊很久以前曾被迫遭到強盜進攻。" },
  { word: "avoid", pos: "v.", cn_def: "避免", en_def: "to stay away from something or someone",
    sentence: "We left the house very early to {{BLANK}} the worst of the rush hour traffic.",
    cn: "我們很早就出門，以避免最糟糕的尖峰時段交通。" },
  { word: "bark", pos: "v.", cn_def: "吠", en_def: "to make the loud sound a dog makes",
    sentence: "Our neighbor's dog began to {{BLANK}} loudly the moment the mail carrier arrived.",
    cn: "郵差一到，我們鄰居的狗就開始大聲吠叫。" },
  { word: "base", pos: "v.", cn_def: "以…為基礎、根據", en_def: "to use something as the foundation for a decision or idea",
    sentence: "The director decided to {{BLANK}} the new film on a popular novel.",
    cn: "導演決定根據一本暢銷小說來拍攝這部新電影。" },
  { word: "become", pos: "v.", cn_def: "成為", en_def: "to start to be something different",
    sentence: "After years of training, she finally managed to {{BLANK}} a professional dancer.",
    cn: "經過多年訓練，她終於成為了一名專業舞者。" },
  { word: "behave", pos: "v.", cn_def: "表現", en_def: "to act in a particular way",
    sentence: "The children promised to {{BLANK}} themselves nicely during the long museum visit.",
    cn: "孩子們承諾在這場漫長的博物館參觀中表現良好。" },
  { word: "belong", pos: "v.", cn_def: "屬於", en_def: "to be the property of someone or part of a group",
    sentence: "This old leather suitcase used to {{BLANK}} to my great-grandfather.",
    cn: "這個舊皮箱以前屬於我的曾祖父。" },
  { word: "bite", pos: "v.", cn_def: "咬", en_def: "to use your teeth to cut or hold something",
    sentence: "Be careful, because that small dog might {{BLANK}} if you reach for its bone.",
    cn: "小心，因為那隻小狗如果你伸手去拿牠的骨頭可能會咬你。" },
  { word: "blame", pos: "v.", cn_def: "責備", en_def: "to say that someone is responsible for something bad",
    sentence: "The coach refused to {{BLANK}} any single player for the team's narrow loss.",
    cn: "教練拒絕為球隊的小幅失利而責怪任何一位球員。" },
  { word: "blow", pos: "v.", cn_def: "吹", en_def: "to push air out through your mouth",
    sentence: "She took a deep breath and tried to {{BLANK}} out all the birthday candles.",
    cn: "她深吸一口氣，試著吹熄所有的生日蠟燭。" },
  { word: "bother", pos: "v.", cn_def: "打擾", en_def: "to disturb or annoy someone",
    sentence: "Please don't {{BLANK}} your sister while she is busy studying for her exam.",
    cn: "請不要在你姊姊忙著準備考試時打擾她。" },
  { word: "bow", pos: "v.", cn_def: "鞠躬", en_def: "to bend your body forward as a sign of respect",
    sentence: "All the performers paused to {{BLANK}} politely after the curtain finally fell.",
    cn: "所有表演者在幕布終於落下後，都停下來禮貌地鞠躬。" },
  { word: "break", pos: "v.", cn_def: "弄壞", en_def: "to cause something to separate into pieces or stop working",
    sentence: "He was worried he might {{BLANK}} the fragile vase while moving it across the room.",
    cn: "他擔心搬動那個易碎花瓶穿過房間時可能會把它弄壞。" },
  { word: "bring", pos: "v.", cn_def: "帶來", en_def: "to carry something with you to a place",
    sentence: "Don't forget to {{BLANK}} your swimsuit when we visit the beach this weekend.",
    cn: "這個週末我們去海邊時，別忘了帶上你的泳衣。" },
  { word: "build", pos: "v.", cn_def: "蓋(房子)", en_def: "to make something by putting materials and parts together",
    sentence: "The workers plan to {{BLANK}} a new playground behind the elementary school.",
    cn: "工人們計畫在小學後面蓋一座新的操場。" },
  { word: "burn", pos: "v.", cn_def: "燃燒", en_def: "to be destroyed or damaged by fire",
    sentence: "We watched the dry autumn leaves slowly {{BLANK}} in the small backyard fire pit.",
    cn: "我們看著乾燥的秋葉在後院小火坑裡慢慢燃燒。" },
  { word: "burst", pos: "v.", cn_def: "爆裂", en_def: "to break open suddenly, often with force",
    sentence: "The colorful balloon began to {{BLANK}} the moment it touched the sharp branch.",
    cn: "那個彩色氣球一碰到尖銳的樹枝就爆裂了。" },
  { word: "calm", pos: "v.", cn_def: "使平靜", en_def: "to make someone or something quiet and relaxed",
    sentence: "The nurse spoke softly to {{BLANK}} the frightened little boy before his injection.",
    cn: "護士輕聲說話，安撫那個害怕的小男孩，讓他在打針前平靜下來。" },
  { word: "cancel", pos: "v.", cn_def: "取消", en_def: "to decide that a planned event will not happen",
    sentence: "The organizers had to {{BLANK}} the outdoor concert because of the sudden storm.",
    cn: "由於突如其來的暴風雨，主辦單位必須取消這場戶外演唱會。" },
  { word: "change", pos: "v.", cn_def: "改變", en_def: "to make or become different",
    sentence: "Living abroad for a year really helped {{BLANK}} the way she sees the world.",
    cn: "在國外生活一年確實幫助改變了她看世界的方式。" },
  { word: "chase", pos: "v.", cn_def: "追逐", en_def: "to run after someone or something to catch them",
    sentence: "Our excited puppy loves to {{BLANK}} the neighbor's cat around the backyard.",
    cn: "我們興奮的小狗喜歡在後院追逐鄰居的貓。" }
];

// ---- Part 2 data: 36 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~27-34 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// 4 options per question, answer letters balanced across A/B/C/D,
// no adjacent repeats. vocabIndex points to the exact VOCAB entry.
const MCQS = [
  { q: "Looking around at the restless classroom full of fidgety students, the teacher gently reminded everyone to settle down. Please ______ quietly until the teacher finishes explaining the lesson to the class.",
    options: ["sit", "stand", "sleep", "wake"], answer: 0, vocabIndex: 0 },
  { q: "Squeezed shoulder to shoulder in the packed arena with nowhere to rest, the excited fans never once sat down. Everyone had to ______ for almost an hour during the crowded concert that night.",
    options: ["sleep", "stand", "bow", "wake"], answer: 1, vocabIndex: 1 },
  { q: "Doctors often remind busy parents that growing bodies and tired young minds need plenty of rest to stay healthy. Most teenagers need at least eight hours of ______ every single night to feel rested.",
    options: ["act", "change", "sleep", "argue"], answer: 2, vocabIndex: 2 },
  { q: "Setting an early alarm beside his bed each evening, the determined runner never misses his favorite morning routine. I usually ______ up before sunrise to go jogging with my dad together.",
    options: ["stand", "sit", "blow", "wake"], answer: 3, vocabIndex: 3 },
  { q: "Auditioning in front of the whole drama club with shaking hands, she practiced her lines until they felt natural. She was chosen to ______ the leading role in the upcoming school play.",
    options: ["act", "argue", "bow", "build"], answer: 0, vocabIndex: 4 },
  { q: "Stirring her steaming cup slowly while glancing at the sugar bowl nearby, she reached for just a little more sweetness. My mother always likes to ______ a little extra sugar to her tea.",
    options: ["aim", "add", "blame", "burn"], answer: 1, vocabIndex: 5 },
  { q: "Listening carefully to his patient describe a sore throat and constant tiredness, the doctor scribbled a few notes. The doctor decided to ______ him to rest quietly at home for a few days.",
    options: ["allow", "agree", "advise", "ask"], answer: 2, vocabIndex: 6 },
  { q: "Living next to a busy nightclub with music blasting until dawn made falling asleep nearly impossible every single night. Too much noise at night can seriously ______ how well you sleep overall.",
    options: ["calm", "behave", "belong", "affect"], answer: 3, vocabIndex: 7 },
  { q: "Sitting across the negotiating table for nearly three hours, the buyer and seller slowly moved closer toward common ground. After a long discussion, both sides finally began to ______ on a fair price.",
    options: ["agree", "argue", "apologize", "avoid"], answer: 0, vocabIndex: 8 },
  { q: "Steadying his shaking hands and squinting one eye shut, the young archer focused completely on the painted target ahead. He took a deep breath and tried to ______ the arrow at the center.",
    options: ["throw", "aim", "blow", "catch"], answer: 1, vocabIndex: 9 },
  { q: "After weeks of careful pleading and several promises about safety gear, the teenager finally heard the answer she hoped for. My parents finally decided to ______ me to join the weekend hiking club.",
    options: ["advise", "affect", "allow", "arrange"], answer: 2, vocabIndex: 10 },
  { q: "Realizing how rude it was to keep his friend waiting outside in the cold for nearly an hour, he felt terrible. He called his friend right away to ______ for arriving so very late.",
    options: ["blame", "bother", "agree", "apologize"], answer: 3, vocabIndex: 11 },
  { q: "Raising their voices over the sound of the television, the two siblings each insisted they deserved the first turn. The two brothers began to ______ loudly over who would use the computer first.",
    options: ["argue", "behave", "bark", "bow"], answer: 0, vocabIndex: 12 },
  { q: "Pushing the heavy furniture into neat clusters before the craft activity began, the whole class pitched in together. Our teacher helped us ______ the desks into small groups for the upcoming activity.",
    options: ["build", "arrange", "add", "break"], answer: 1, vocabIndex: 13 },
  { q: "Standing quietly at the front desk while scanning the tall shelves for the right title, the student looked a bit lost. Feel free to ______ the librarian if you can't find your book.",
    options: ["advise", "blame", "ask", "chase"], answer: 2, vocabIndex: 14 },
  { q: "Records from long ago describe how raiders on horseback would suddenly appear at the edge of the unprotected farmland. The small village was once forced to ______ by bandits many years ago.",
    options: ["avoid", "calm", "cancel", "attack"], answer: 3, vocabIndex: 15 },
  { q: "Checking the clock and grabbing their bags before the usual departure time, the careful commuters planned around the busiest roads. We left the house early to ______ the worst of the rush hour traffic.",
    options: ["avoid", "affect", "allow", "argue"], answer: 0, vocabIndex: 16 },
  { q: "The moment footsteps approached the gate each afternoon, the small brown dog leapt up with its ears pointed forward. Our neighbor's dog began to ______ loudly the moment the mail carrier arrived nearby.",
    options: ["bite", "bark", "blow", "burst"], answer: 1, vocabIndex: 17 },
  { q: "Flipping through a worn paperback for inspiration, the filmmaker imagined how the characters might look on the big screen. The director decided to ______ the new film on a popular novel instead.",
    options: ["build", "change", "base", "become"], answer: 2, vocabIndex: 18 },
  { q: "Practicing for hours after school every single day since she was six years old finally paid off completely. After years of training, she finally managed to ______ a professional dancer at the academy.",
    options: ["belong", "behave", "agree", "become"], answer: 3, vocabIndex: 19 },
  { q: "Reminded gently by their teacher about quiet voices and careful hands before stepping through the museum's tall doors, the students nodded. The children promised to ______ themselves nicely during the long museum visit.",
    options: ["behave", "become", "bother", "bow"], answer: 0, vocabIndex: 20 },
  { q: "Tucked away in an attic for decades, the worn leather case still carried the faint scent of old travel adventures. This old leather suitcase used to ______ to my great-grandfather many years ago.",
    options: ["become", "belong", "base", "blame"], answer: 1, vocabIndex: 21 },
  { q: "Reaching slowly toward the small terrier's favorite chew toy without warning, the curious toddler ignored his mother's worried glance. Be careful, because that small dog might ______ if you reach for its bone.",
    options: ["bark", "burn", "bite", "burst"], answer: 2, vocabIndex: 22 },
  { q: "Reviewing the final scoreboard after a disappointing defeat, the team gathered quietly around their disappointed but fair-minded coach. The coach refused to ______ any single player for the team's narrow loss that evening.",
    options: ["calm", "chase", "cancel", "blame"], answer: 3, vocabIndex: 23 },
  { q: "Leaning over the glowing cake with cheeks puffed out and friends singing loudly around her, she made her wish quickly. She took a deep breath and tried to ______ out all the birthday candles.",
    options: ["blow", "bite", "burn", "bother"], answer: 0, vocabIndex: 24 },
  { q: "Tiptoeing past the closed bedroom door with textbooks balanced under one arm, the younger sibling tried to stay quiet. Please don't ______ your sister while she is busy studying hard for her exam.",
    options: ["blame", "bother", "avoid", "affect"], answer: 1, vocabIndex: 25 },
  { q: "As the heavy red curtain slowly descended after the final song, the exhausted but proud cast lined up together facing the crowd. All the performers paused to ______ politely after the curtain finally fell.",
    options: ["bite", "burst", "bow", "build"], answer: 2, vocabIndex: 26 },
  { q: "Lifting the delicate antique carefully with both hands while crossing the cluttered living room, he moved with extra caution. He was worried he might ______ the fragile vase while moving it across the room.",
    options: ["burn", "burst", "bow", "break"], answer: 3, vocabIndex: 27 },
  { q: "Packing towels, sunscreen, and snacks into a beach bag the night before, she double-checked her list one more time. Don't forget to ______ your swimsuit when we visit the beach this weekend together.",
    options: ["bring", "chase", "build", "change"], answer: 0, vocabIndex: 28 },
  { q: "Studying blueprints spread across a folding table near the empty lot, the construction crew discussed where to start digging first. The workers plan to ______ a new playground behind the elementary school soon.",
    options: ["bring", "build", "base", "bow"], answer: 1, vocabIndex: 29 },
  { q: "Raking piles of orange and red leaves into a metal bin behind the house, the family prepared for their evening tradition. We watched the dry autumn leaves slowly ______ in the backyard fire pit.",
    options: ["chase", "change", "burn", "agree"], answer: 2, vocabIndex: 30 },
  { q: "Drifting too close to the thorny rosebush while bouncing happily across the lawn, the bright object met a sudden end. The colorful balloon began to ______ the moment it touched the sharp branch nearby.",
    options: ["blow", "bark", "break", "burst"], answer: 3, vocabIndex: 31 },
  { q: "Crouching beside the trembling toddler who had just scraped his knee, the nurse kept her voice gentle and low. The nurse spoke softly to ______ the frightened little boy before his injection.",
    options: ["calm", "affect", "advise", "change"], answer: 0, vocabIndex: 32 },
  { q: "Watching dark clouds roll in fast and lightning flash across the distant hills, the worried staff made an unavoidable decision. The organizers had to ______ the outdoor concert because of the sudden storm.",
    options: ["arrange", "cancel", "agree", "add"], answer: 1, vocabIndex: 33 },
  { q: "Returning home after twelve unforgettable months overseas, she noticed she now thought about everyday problems quite differently than before. Living abroad for a year really helped ______ the way she sees the world.",
    options: ["base", "become", "change", "belong"], answer: 2, vocabIndex: 34 },
  { q: "Spotting the neighbor's lazy orange cat strolling boldly along the fence line, the energetic puppy could never resist the temptation. Our excited puppy loves to ______ the neighbor's cat around the backyard every afternoon.",
    options: ["bite", "bark", "attack", "chase"], answer: 3, vocabIndex: 35 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "abroad": { pos: "adv.", en_def: "in or to a foreign country", cn_def: "在海外；出國" },
  "academy": { pos: "n.", en_def: "a school, especially one for special training", cn_def: "學院；訓練學校" },
  "antique": { pos: "n.", en_def: "an old and often valuable object", cn_def: "古董" },
  "arena": { pos: "n.", en_def: "a large building used for sports or concerts", cn_def: "競技場；體育館" },
  "attic": { pos: "n.", en_def: "a space just below the roof of a house", cn_def: "閣樓" },
  "audition": { pos: "v.", en_def: "to perform in order to be judged for a role", cn_def: "試演；試鏡" },
  "bandits": { pos: "n.", en_def: "robbers, especially ones who attack travelers", cn_def: "強盜（複數）" },
  "blueprints": { pos: "n.", en_def: "detailed plans or drawings for building something", cn_def: "設計圖（複數）" },
  "buyer": { pos: "n.", en_def: "a person who buys something", cn_def: "買方" },
  "catch": { pos: "v.", en_def: "to take hold of something moving through the air", cn_def: "抓住" },
  "caution": { pos: "n.", en_def: "great care taken to avoid danger", cn_def: "謹慎；小心" },
  "cast": { pos: "n.", en_def: "all the actors in a play or movie", cn_def: "全體演員" },
  "cluttered": { pos: "adj.", en_def: "filled with too many things in a disorganized way", cn_def: "雜亂的" },
  "commuters": { pos: "n.", en_def: "people who travel regularly between home and work", cn_def: "通勤者（複數）" },
  "construction": { pos: "n.", en_def: "the process of building something", cn_def: "建築；施工" },
  "crouching": { pos: "v.", en_def: "bending the body close to the ground", cn_def: "蹲下（進行式）" },
  "curtain": { pos: "n.", en_def: "a piece of cloth that covers a stage or window", cn_def: "幕布；簾子" },
  "defeat": { pos: "n.", en_def: "a loss in a game or contest", cn_def: "失敗" },
  "departure": { pos: "n.", en_def: "the act of leaving a place", cn_def: "出發；離開" },
  "descended": { pos: "v.", en_def: "moved downward (past tense of descend)", cn_def: "下降（過去式）" },
  "disappointed": { pos: "adj.", en_def: "feeling sad because something did not happen as hoped", cn_def: "失望的" },
  "drama club": { pos: "n.", en_def: "a school group focused on acting and plays", cn_def: "戲劇社" },
  "energetic": { pos: "adj.", en_def: "full of energy; active", cn_def: "精力充沛的" },
  "filmmaker": { pos: "n.", en_def: "a person who makes movies", cn_def: "電影製作人" },
  "fragile": { pos: "adj.", en_def: "easily broken or damaged", cn_def: "易碎的" },
  "great-grandfather": { pos: "n.", en_def: "the father of your grandfather or grandmother", cn_def: "曾祖父" },
  "inspiration": { pos: "n.", en_def: "something that gives you ideas to create or do something", cn_def: "靈感" },
  "lawn": { pos: "n.", en_def: "an area of grass, usually near a house", cn_def: "草坪" },
  "lot": { pos: "n.", en_def: "a piece of land used for a specific purpose", cn_def: "地段；地塊" },
  "narrow": { pos: "adj.", en_def: "small in difference; not wide", cn_def: "差距小的；狹窄的" },
  "negotiating": { pos: "v.", en_def: "discussing something to reach an agreement", cn_def: "談判（進行式）" },
  "nightclub": { pos: "n.", en_def: "a place open at night for music and dancing", cn_def: "夜店" },
  "overseas": { pos: "adv.", en_def: "in or to a foreign country", cn_def: "在海外；到國外" },
  "paperback": { pos: "n.", en_def: "a book with a soft paper cover", cn_def: "平裝書" },
  "pitched in": { pos: "v.", en_def: "helped with a group effort", cn_def: "一起幫忙" },
  "puffed": { pos: "v.", en_def: "blew out air in a quick burst", cn_def: "鼓起；吹氣（過去式）" },
  "raiders": { pos: "n.", en_def: "people who attack a place suddenly to steal or harm", cn_def: "襲擊者（複數）" },
  "raking": { pos: "v.", en_def: "gathering leaves or dirt with a tool", cn_def: "用耙子耙（進行式）" },
  "rosebush": { pos: "n.", en_def: "a plant that grows roses", cn_def: "玫瑰花叢" },
  "scoreboard": { pos: "n.", en_def: "a board that shows the score of a game", cn_def: "計分板" },
  "scraped": { pos: "v.", en_def: "rubbed against something rough and hurt the skin", cn_def: "擦傷（過去式）" },
  "seller": { pos: "n.", en_def: "a person who sells something", cn_def: "賣方" },
  "siblings": { pos: "n.", en_def: "brothers or sisters", cn_def: "兄弟姊妹（複數）" },
  "sunscreen": { pos: "n.", en_def: "a cream that protects skin from the sun", cn_def: "防曬乳" },
  "temptation": { pos: "n.", en_def: "a strong desire to do something, even if unwise", cn_def: "誘惑" },
  "terrier": { pos: "n.", en_def: "a small, energetic breed of dog", cn_def: "（一種）小型犬" },
  "textbooks": { pos: "n.", en_def: "books used for studying a school subject", cn_def: "教科書（複數）" },
  "thorny": { pos: "adj.", en_def: "covered with sharp points, like some plants", cn_def: "多刺的" },
  "throw": { pos: "v.", en_def: "to send something through the air with your hand", cn_def: "投擲" },
  "tradition": { pos: "n.", en_def: "a custom passed down over time", cn_def: "傳統" },
  "trembling": { pos: "v.", en_def: "shaking slightly, often from fear or excitement", cn_def: "顫抖（進行式）" },
  "unavoidable": { pos: "adj.", en_def: "impossible to avoid or prevent", cn_def: "無法避免的" },
  "vase": { pos: "n.", en_def: "a container used to hold flowers", cn_def: "花瓶" },
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
