// ============================================================
// Group 20 Quiz Data: Body Parts
// Full word set (35 words) — parts of the human body from the
// "body / health / feelings / clothing / appearance" theme.
// Health/illness and senses/speech verbs will follow as the
// next group.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 20 - Body Parts (身體部位)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (35 words) ----
const VOCAB = [
  { word: "body", pos: "n.", cn_def: "身體", en_def: "the whole physical structure of a person or animal",
    sentence: "After the long swim, her whole {{BLANK}} felt tired and relaxed.",
    cn: "游了很久之後，她全身感到疲倦又放鬆。" },
  { word: "head", pos: "n.", cn_def: "頭", en_def: "the top part of the body that contains the brain, eyes, and mouth",
    sentence: "He bumped his {{BLANK}} on the low doorway as he walked into the room.",
    cn: "他走進房間時頭撞到了低矮的門框。" },
  { word: "face", pos: "n.", cn_def: "臉", en_def: "the front part of the head, from forehead to chin",
    sentence: "She washed her {{BLANK}} with cold water to feel more awake.",
    cn: "她用冷水洗臉，讓自己更清醒一點。" },
  { word: "eye", pos: "n.", cn_def: "眼睛", en_def: "the organ used for seeing",
    sentence: "He closed one {{BLANK}} to look carefully through the small telescope.",
    cn: "他閉上一隻眼睛，仔細地透過小型望遠鏡觀看。" },
  { word: "ear", pos: "n.", cn_def: "耳朵", en_def: "the organ used for hearing",
    sentence: "She put her {{BLANK}} against the door to listen for any noise inside.",
    cn: "她把耳朵貼在門上，聽聽裡面有沒有聲音。" },
  { word: "nose", pos: "n.", cn_def: "鼻子", en_def: "the organ used for smelling and breathing",
    sentence: "The smell of fresh bread filled his {{BLANK}} as he walked past the bakery.",
    cn: "他走過麵包店時，新鮮麵包的香味飄入了他的鼻子。" },
  { word: "lip", pos: "n.", cn_def: "嘴唇", en_def: "one of the two soft edges around the mouth",
    sentence: "Her {{BLANK}} was sunburned after spending the whole afternoon at the beach.",
    cn: "她在海邊待了整個下午後，嘴唇被曬傷了。" },
  { word: "mouth", pos: "n.", cn_def: "嘴巴", en_def: "the opening in the face used for eating and speaking",
    sentence: "He covered his {{BLANK}} politely whenever he started to yawn in class.",
    cn: "他在課堂上想打哈欠時都會有禮貌地遮住嘴巴。" },
  { word: "chin", pos: "n.", cn_def: "下巴", en_def: "the part of the face below the mouth",
    sentence: "The doctor gently lifted the boy's {{BLANK}} to check his throat.",
    cn: "醫生輕輕抬起男孩的下巴來檢查他的喉嚨。" },
  { word: "neck", pos: "n.", cn_def: "脖子", en_def: "the part of the body connecting the head to the shoulders",
    sentence: "She wrapped a warm scarf around her {{BLANK}} before stepping outside in the cold.",
    cn: "她在寒冷的天氣外出前，在脖子上圍了一條溫暖的圍巾。" },
  { word: "shoulder", pos: "n.", cn_def: "肩膀", en_def: "the part of the body where the arm joins the body",
    sentence: "He carried his little sister on his {{BLANK}} so she could see the parade.",
    cn: "他讓小妹妹坐在他的肩膀上，這樣她就能看到遊行。" },
  { word: "arm", pos: "n.", cn_def: "手臂", en_def: "the part of the body from the shoulder to the hand",
    sentence: "She broke her {{BLANK}} after falling off her bicycle last weekend.",
    cn: "她上週末從自行車上摔下來，摔斷了手臂。" },
  { word: "hand", pos: "n.", cn_def: "手", en_def: "the part of the body at the end of the arm, used for holding things",
    sentence: "He raised his {{BLANK}} quickly to answer the teacher's question.",
    cn: "他迅速舉手回答老師的問題。" },
  { word: "wrist", pos: "n.", cn_def: "手腕", en_def: "the joint connecting the hand to the arm",
    sentence: "She wears a silver bracelet on her {{BLANK}} every single day.",
    cn: "她每天都在手腕上戴著一個銀色手環。" },
  { word: "finger", pos: "n.", cn_def: "手指", en_def: "one of the five thin parts at the end of the hand",
    sentence: "He accidentally cut his {{BLANK}} while slicing vegetables for dinner.",
    cn: "他切晚餐用的蔬菜時不小心割到了手指。" },
  { word: "thumb", pos: "n.", cn_def: "拇指", en_def: "the short thick finger next to the first finger",
    sentence: "The baby happily sucked her {{BLANK}} while falling asleep in the car seat.",
    cn: "嬰兒在汽車安全座椅上快樂地吸著拇指入睡。" },
  { word: "back", pos: "n.", cn_def: "背部", en_def: "the part of the body from the neck to the bottom of the spine",
    sentence: "He hurt his {{BLANK}} while lifting the heavy box off the floor.",
    cn: "他從地上抬起那個沉重的箱子時傷到了背部。" },
  { word: "waist", pos: "n.", cn_def: "腰", en_def: "the narrow part of the body between the ribs and the hips",
    sentence: "She tied a thin belt around her {{BLANK}} to complete her outfit.",
    cn: "她在腰上繫了一條細皮帶來搭配她的穿著。" },
  { word: "hip", pos: "n.", cn_def: "臀部", en_def: "the part of the body where the leg joins the body at the side",
    sentence: "He placed his hands on his {{BLANK}} while waiting for the bus to arrive.",
    cn: "他等公車時雙手放在臀部上。" },
  { word: "leg", pos: "n.", cn_def: "腿", en_def: "one of the two long parts of the body used for walking",
    sentence: "Her {{BLANK}} felt sore after running five kilometers in the park this morning.",
    cn: "今天早上在公園跑了五公里後，她的腿感覺很痠痛。" },
  { word: "knee", pos: "n.", cn_def: "膝蓋", en_def: "the joint in the middle of the leg",
    sentence: "He scraped his {{BLANK}} when he fell while skateboarding near the park.",
    cn: "他在公園附近玩滑板時跌倒，擦傷了膝蓋。" },
  { word: "ankle", pos: "n.", cn_def: "腳踝", en_def: "the joint connecting the foot to the leg",
    sentence: "She twisted her {{BLANK}} while running on the uneven trail.",
    cn: "她在不平的小路上跑步時扭傷了腳踝。" },
  { word: "foot", pos: "n.", cn_def: "腳", en_def: "the part of the leg below the ankle",
    sentence: "He stepped on a sharp rock and hurt his bare {{BLANK}}.",
    cn: "他踩到一塊尖石頭，弄傷了光著的腳。" },
  { word: "toe", pos: "n.", cn_def: "腳趾", en_def: "one of the five parts at the end of the foot",
    sentence: "She accidentally stubbed her {{BLANK}} on the corner of the bed in the dark.",
    cn: "她在黑暗中不小心踢到床角，傷到了腳趾。" },
  { word: "beard", pos: "n.", cn_def: "落腮鬍", en_def: "the hair that grows on a man's chin and cheeks",
    sentence: "My grandfather has had a thick white {{BLANK}} for as long as I can remember.",
    cn: "在我有記憶以來，我爺爺一直留著一把濃密的白色落腮鬍。" },
  { word: "hair", pos: "n.", cn_def: "頭髮", en_def: "the thin strands that grow on the head and body",
    sentence: "She tied her long {{BLANK}} into a ponytail before starting her morning run.",
    cn: "她開始晨跑前把長髮綁成了馬尾。" },
  { word: "nail", pos: "n.", cn_def: "指甲", en_def: "the hard covering at the tip of a finger or toe",
    sentence: "She painted her {{BLANK}} a bright shade of pink before the party.",
    cn: "派對前她把指甲塗成了鮮豔的粉紅色。" },
  { word: "skin", pos: "n.", cn_def: "皮膚", en_def: "the outer covering of the body",
    sentence: "He always wears sunscreen to protect his {{BLANK}} at the beach.",
    cn: "他在海邊總是擦防曬乳來保護皮膚。" },
  { word: "blood", pos: "n.", cn_def: "血液", en_def: "the red liquid that flows through the body",
    sentence: "The nurse took a small sample of {{BLANK}} for the doctor to test.",
    cn: "護士抽取了一小份血液樣本供醫生檢驗。" },
  { word: "bone", pos: "n.", cn_def: "骨頭", en_def: "one of the hard parts that make up the body's skeleton",
    sentence: "The doctor took an X-ray to check if the {{BLANK}} in his arm was broken.",
    cn: "醫生照了X光來檢查他手臂的骨頭是否骨折。" },
  { word: "tooth", pos: "n.", cn_def: "牙齒", en_def: "one of the hard white parts in the mouth used for biting",
    sentence: "He felt a sharp pain in his {{BLANK}} after eating something very cold.",
    cn: "他吃了很冰的東西後牙齒感到一陣劇痛。" },
  { word: "heart", pos: "n.", cn_def: "心臟", en_def: "the organ in the chest that pumps blood through the body",
    sentence: "Her {{BLANK}} beat quickly with excitement just before the race began.",
    cn: "比賽開始前，她的心臟因興奮而跳得很快。" },
  { word: "tongue", pos: "n.", cn_def: "舌頭", en_def: "the soft movable part inside the mouth used for tasting and speaking",
    sentence: "He accidentally bit his {{BLANK}} while eating dinner too quickly.",
    cn: "他吃晚餐吃得太快，不小心咬到了自己的舌頭。" },
  { word: "throat", pos: "n.", cn_def: "喉嚨", en_def: "the passage at the back of the mouth leading to the stomach and lungs",
    sentence: "Her {{BLANK}} felt sore after cheering loudly at the basketball game.",
    cn: "她在籃球比賽中大聲歡呼後喉嚨感到痛。" },
  { word: "stomach", pos: "n.", cn_def: "胃", en_def: "the organ in the body where food is digested",
    sentence: "His {{BLANK}} growled loudly during class because he had skipped breakfast.",
    cn: "他因為沒吃早餐，上課時肚子餓得咕咕叫。" }
];

// ---- Part 2 data: 35 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (9/9/9/8), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "After swimming for almost an hour without stopping, she finally climbed out of the pool. Her whole ______ felt tired but pleasantly relaxed.",
    options: ["head","body","neck","back"], answer: 1, vocabIndex: 0 },
  { q: "Rushing into the room without looking up, he forgot about the low doorway frame above him. He bumped his ______ and yelped in surprise.",
    options: ["face","chin","shoulder","head"], answer: 3, vocabIndex: 1 },
  { q: "Still half-asleep after waking up, she walked to the bathroom sink to splash some cold water. Washing her ______ helped her feel awake again.",
    options: ["hand","face","hair","arm"], answer: 1, vocabIndex: 2 },
  { q: "Trying to focus the small telescope on a distant star, he found it easier with just one open. He closed one ______ to see more clearly.",
    options: ["ear","nose","eye","lip"], answer: 2, vocabIndex: 3 },
  { q: "Standing outside the locked door, she leaned in close trying to figure out if anyone was home. She pressed her ______ against the wood to listen.",
    options: ["ear","face","nose","hand"], answer: 0, vocabIndex: 4 },
  { q: "Walking past the small bakery on his way to work, something delicious drifted through the morning air. The smell of fresh bread filled his ______ completely.",
    options: ["mouth","nose","throat","head"], answer: 1, vocabIndex: 5 },
  { q: "After spending the whole afternoon at the beach without sunscreen, she noticed something uncomfortable later that evening. Her ______ had turned red and felt sunburned.",
    options: ["lip","skin","nose","ear"], answer: 0, vocabIndex: 6 },
  { q: "Feeling sleepy during the long afternoon lesson, he tried hard to stay polite in front of his classmates. He covered his ______ every time he started to yawn.",
    options: ["nose","mouth","eye","ear"], answer: 1, vocabIndex: 7 },
  { q: "During the checkup, the young boy looked nervous as the doctor leaned closer to examine him. She gently lifted his ______ to look at his throat.",
    options: ["face","head","neck","chin"], answer: 3, vocabIndex: 8 },
  { q: "Before stepping outside into the freezing winter wind, she reached for something warm hanging by the door. She wrapped a thick scarf around her ______.",
    options: ["head","waist","neck","wrist"], answer: 2, vocabIndex: 9 },
  { q: "During the holiday parade downtown, the little girl could not see anything past the tall crowd in front of her. Her older brother lifted her onto his ______ so she could watch.",
    options: ["back","shoulder","arm","hip"], answer: 1, vocabIndex: 10 },
  { q: "Riding her bicycle too fast around the corner last weekend, she lost her balance and fell hard onto the pavement. At the hospital, doctors confirmed she had broken her ______.",
    options: ["arm","leg","ankle","knee"], answer: 0, vocabIndex: 11 },
  { q: "During math class, the teacher asked a tricky question that nobody seemed to know right away. One eager student quickly raised his ______ before anyone else could.",
    options: ["finger","hand","arm","thumb"], answer: 1, vocabIndex: 12 },
  { q: "Showing off her new accessory at school, she rolled up her sleeve so her friends could see it clearly. A shiny silver bracelet circled her ______ neatly.",
    options: ["neck","waist","ankle","wrist"], answer: 3, vocabIndex: 13 },
  { q: "While preparing dinner in the kitchen, she was chopping vegetables quickly when the knife slipped suddenly. She accidentally cut her ______ and had to get a bandage.",
    options: ["hand","finger","thumb","wrist"], answer: 1, vocabIndex: 14 },
  { q: "Strapped safely into her car seat during the long drive home, the tired baby slowly drifted off to sleep. She happily sucked her ______ the whole way.",
    options: ["finger","lip","thumb","tongue"], answer: 2, vocabIndex: 15 },
  { q: "Lifting the heavy cardboard box off the garage floor without bending his knees properly, he felt a sudden sharp pain. He had clearly hurt his ______ doing it.",
    options: ["leg","neck","shoulder","back"], answer: 3, vocabIndex: 16 },
  { q: "Getting ready for the party, she chose a thin accessory to complete her outfit perfectly. She tied a narrow belt around her ______ before leaving.",
    options: ["waist","neck","wrist","ankle"], answer: 0, vocabIndex: 17 },
  { q: "Standing at the bus stop with nothing else to do, he leaned back casually and placed both hands somewhere comfortable. He rested them on his ______ while he waited.",
    options: ["back","shoulder","hip","knee"], answer: 2, vocabIndex: 18 },
  { q: "After jogging five kilometers around the park early this morning, she noticed an ache building up by the time she got home. Her ______ felt sore for the rest of the day.",
    options: ["arm","back","neck","leg"], answer: 3, vocabIndex: 19 },
  { q: "Trying a new trick on his skateboard near the park, he lost his balance and landed hard on the pavement. He scraped his ______ and had to clean the small wound.",
    options: ["knee","elbow","ankle","wrist"], answer: 0, vocabIndex: 20 },
  { q: "Running too quickly on the bumpy, uneven trail without watching her footing carefully, she suddenly felt a sharp twist in her step. She had twisted her ______ and needed to rest.",
    options: ["knee","foot","toe","ankle"], answer: 3, vocabIndex: 21 },
  { q: "Walking barefoot across the rocky path near the river without thinking, he stepped directly on something sharp. He winced in pain after hurting his bare ______.",
    options: ["leg","ankle","foot","toe"], answer: 2, vocabIndex: 22 },
  { q: "Moving quietly through the dark bedroom without turning on the light, she misjudged the distance to the furniture. She accidentally stubbed her ______ on the corner of the bed.",
    options: ["foot","toe","ankle","knee"], answer: 1, vocabIndex: 23 },
  { q: "Looking through old family photographs, the grandchildren noticed one feature that never seemed to change. Their grandfather has worn the same thick white ______ for as long as they can remember.",
    options: ["hair","face","beard","chin"], answer: 2, vocabIndex: 24 },
  { q: "Getting ready for her early morning run before the sun even came up, she wanted to keep things out of her face. She tied her long ______ into a neat ponytail.",
    options: ["hair","neck","face","ear"], answer: 0, vocabIndex: 25 },
  { q: "Getting ready for the big party that evening, she wanted her outfit to look perfectly put together. She painted her ______ a bright shade of pink to match her dress.",
    options: ["hand","finger","nail","skin"], answer: 2, vocabIndex: 26 },
  { q: "Spending the entire day relaxing under the hot sun at the beach, he was careful to bring along something protective. He always wears sunscreen to protect his ______ outdoors.",
    options: ["hair","face","eye","skin"], answer: 3, vocabIndex: 27 },
  { q: "During the routine checkup, the doctor wanted to run a few simple tests before giving any advice. The nurse took a small sample of ______ to send to the lab.",
    options: ["blood","skin","hair","nail"], answer: 0, vocabIndex: 28 },
  { q: "After falling awkwardly during practice and feeling a sharp pain in his arm, his coach suggested seeing a doctor. An X-ray later confirmed that a ______ in his arm was broken.",
    options: ["nail","bone","skin","blood"], answer: 1, vocabIndex: 29 },
  { q: "Biting into a popsicle too quickly on a hot summer afternoon, he immediately regretted his decision. He felt a sharp pain in his ______ from the sudden cold.",
    options: ["tooth","tongue","throat","lip"], answer: 0, vocabIndex: 30 },
  { q: "Standing nervously at the starting line just moments before the whistle blew, she could feel something pounding rapidly inside her chest. Her ______ beat quickly with excitement and nerves.",
    options: ["head","stomach","heart","throat"], answer: 2, vocabIndex: 31 },
  { q: "Eating his dinner far too quickly because he was running late for soccer practice, he made a small painful mistake. He accidentally bit his ______ while chewing fast.",
    options: ["lip","tooth","cheek","tongue"], answer: 3, vocabIndex: 32 },
  { q: "Cheering loudly for her team throughout the entire basketball game without taking a single break, she noticed discomfort afterward. Her ______ felt sore by the time the game ended.",
    options: ["throat","mouth","tongue","nose"], answer: 0, vocabIndex: 33 },
  { q: "Rushing out the door to catch the early school bus, he completely forgot to grab anything to eat. His ______ growled loudly in class because he had skipped breakfast.",
    options: ["mouth","throat","stomach","heart"], answer: 2, vocabIndex: 34 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "accidentally": { pos: "adv.", en_def: "without meaning to; by mistake", cn_def: "不小心地" },
  "awake": { pos: "adj.", en_def: "not asleep", cn_def: "清醒的" },
  "bakery": { pos: "n.", en_def: "a shop that makes and sells bread and cakes", cn_def: "麵包店" },
  "bare": { pos: "adj.", en_def: "without covering, especially shoes or clothes", cn_def: "光著的；裸露的" },
  "basketball": { pos: "n.", en_def: "a sport played with a round ball and a high hoop", cn_def: "籃球" },
  "beach": { pos: "n.", en_def: "the sandy or rocky area next to the ocean", cn_def: "海灘" },
  "bicycle": { pos: "n.", en_def: "a two-wheeled vehicle powered by pedaling", cn_def: "自行車" },
  "bracelet": { pos: "n.", en_def: "a piece of jewelry worn around the wrist", cn_def: "手環；手鐲" },
  "breakfast": { pos: "n.", en_def: "the first meal of the day", cn_def: "早餐" },
  "cheek": { pos: "n.", en_def: "the soft part of the face below the eye on each side", cn_def: "臉頰" },
  "cheering": { pos: "v.", en_def: "shouting happily to support someone", cn_def: "歡呼" },
  "doorway": { pos: "n.", en_def: "the opening where a door is, used to enter or leave a room", cn_def: "門口" },
  "elbow": { pos: "n.", en_def: "the joint where the arm bends", cn_def: "手肘" },
  "excitement": { pos: "n.", en_def: "a feeling of being very interested or happy about something", cn_def: "興奮" },
  "kilometers": { pos: "n.", en_def: "units of distance, each equal to 1000 meters", cn_def: "公里（複數）" },
  "parade": { pos: "n.", en_def: "a public event where people walk or ride through the streets", cn_def: "遊行" },
  "ponytail": { pos: "n.", en_def: "hair tied back so it hangs like a horse's tail", cn_def: "馬尾" },
  "race": { pos: "n.", en_def: "a competition to see who is fastest", cn_def: "比賽" },
  "sample": { pos: "n.", en_def: "a small amount of something used for testing", cn_def: "樣本" },
  "scarf": { pos: "n.", en_def: "a piece of cloth worn around the neck for warmth", cn_def: "圍巾" },
  "skateboarding": { pos: "n.", en_def: "the activity of riding a board with wheels", cn_def: "玩滑板" },
  "sunburned": { pos: "adj.", en_def: "having red, sore skin from too much sun", cn_def: "曬傷的" },
  "sunscreen": { pos: "n.", en_def: "a lotion used to protect the skin from the sun", cn_def: "防曬乳" },
  "telescope": { pos: "n.", en_def: "a tool used to see distant objects, like stars, more clearly", cn_def: "望遠鏡" },
  "trail": { pos: "n.", en_def: "a path through nature used for walking or running", cn_def: "小徑" },
  "uneven": { pos: "adj.", en_def: "not flat or smooth; having an irregular surface", cn_def: "不平的" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
