// ============================================================
// Group 23 Quiz Data: Accessories / Colors
// Full word set (35 words) — accessories and colors from the
// "body / health / feelings / clothing / appearance" theme.
// Continues from Group 22 (Clothing Items/Care & Fashion).
// Physical appearance, age, and beauty will follow as the
// next group.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 23 - Accessories / Colors (配件/顏色)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (35 words) ----
const VOCAB = [
  { word: "pocket", pos: "n.", cn_def: "口袋", en_def: "a small pouch sewn into clothing for carrying small items",
    sentence: "He kept his bus ticket safe in his jacket {{BLANK}} the whole way home.",
    cn: "他整路回家都把公車票安全地放在外套口袋裡。" },
  { word: "backpack", pos: "n.", cn_def: "後背包", en_def: "a bag carried on the back, held by straps over the shoulders",
    sentence: "She packed her textbooks neatly into her {{BLANK}} before leaving for school.",
    cn: "她出門上學前把課本整齊地裝進後背包裡。" },
  { word: "bag", pos: "n.", cn_def: "袋子", en_def: "a flexible container used for carrying things",
    sentence: "He carried his lunch in a small paper {{BLANK}} every day.",
    cn: "他每天都用一個小紙袋裝午餐。" },
  { word: "purse", pos: "n.", cn_def: "錢包", en_def: "a small bag, usually carried by women, for money and personal items",
    sentence: "She searched through her {{BLANK}} looking for her house keys.",
    cn: "她在錢包裡翻找家裡的鑰匙。" },
  { word: "wallet", pos: "n.", cn_def: "皮夾", en_def: "a small flat case for carrying money and cards",
    sentence: "He checked his back pocket twice to make sure his {{BLANK}} was still there.",
    cn: "他檢查了兩次後口袋，確認皮夾還在裡面。" },
  { word: "belt", pos: "n.", cn_def: "皮帶", en_def: "a strip of leather or cloth worn around the waist",
    sentence: "He tightened his {{BLANK}} after losing a little weight last month.",
    cn: "他上個月瘦了一點後把皮帶束緊了一些。" },
  { word: "button", pos: "n.", cn_def: "鈕扣", en_def: "a small round object used to fasten clothing",
    sentence: "One {{BLANK}} fell off his shirt while he was getting dressed this morning.",
    cn: "他今天早上穿衣服時，襯衫上的一顆鈕扣掉了。" },
  { word: "cap", pos: "n.", cn_def: "鴨舌帽", en_def: "a soft hat with a brim, often worn for sports",
    sentence: "He wore his favorite baseball {{BLANK}} backward while skateboarding at the park.",
    cn: "他在公園玩滑板時把他最喜歡的棒球帽反著戴。" },
  { word: "hat", pos: "n.", cn_def: "帽子", en_def: "a covering worn on the head",
    sentence: "She wore a wide straw {{BLANK}} to protect her face from the sun.",
    cn: "她戴了一頂寬邊草帽來保護臉部不被太陽曬到。" },
  { word: "glove", pos: "n.", cn_def: "手套", en_def: "a piece of clothing that covers the hand and fingers",
    sentence: "He put on a thick winter {{BLANK}} before building a snowman outside.",
    cn: "他出去堆雪人前先戴上一隻厚厚的冬季手套。" },
  { word: "scarf", pos: "n.", cn_def: "圍巾", en_def: "a piece of cloth worn around the neck for warmth or style",
    sentence: "She wrapped a soft wool {{BLANK}} around her neck before going outside.",
    cn: "她出門前在脖子上圍了一條柔軟的羊毛圍巾。" },
  { word: "tie", pos: "n.", cn_def: "領帶", en_def: "a narrow piece of cloth worn around the neck, usually by men",
    sentence: "He chose a blue {{BLANK}} to match his suit for the job interview.",
    cn: "他為了面試挑了一條藍色領帶來搭配他的西裝。" },
  { word: "glasses", pos: "n.", cn_def: "眼鏡", en_def: "a pair of lenses worn over the eyes to help with seeing",
    sentence: "She cannot read the whiteboard clearly without her {{BLANK}} on.",
    cn: "她沒戴眼鏡就看不清楚白板上的字。" },
  { word: "contact lens", pos: "n.", cn_def: "隱形眼鏡", en_def: "a thin curved piece of plastic worn directly on the eye to help vision",
    sentence: "She prefers wearing a {{BLANK}} instead of glasses when she plays sports.",
    cn: "她打球時比較喜歡戴隱形眼鏡而不是眼鏡。" },
  { word: "earrings", pos: "n.", cn_def: "耳環", en_def: "jewelry worn on the ears",
    sentence: "Her grandmother gave her a pair of pearl {{BLANK}} for her sixteenth birthday.",
    cn: "她奶奶在她十六歲生日時送了她一對珍珠耳環。" },
  { word: "necklace", pos: "n.", cn_def: "項鍊", en_def: "a piece of jewelry worn around the neck",
    sentence: "She wore a gold {{BLANK}} with a small heart-shaped pendant.",
    cn: "她戴了一條墜著小愛心吊飾的金色項鍊。" },
  { word: "ring", pos: "n.", cn_def: "戒指", en_def: "a piece of jewelry worn on a finger",
    sentence: "He proposed to her with a beautiful diamond {{BLANK}} at the beach.",
    cn: "他在海邊用一枚美麗的鑽石戒指向她求婚。" },
  { word: "watch", pos: "n.", cn_def: "手錶", en_def: "a small device worn on the wrist to tell time",
    sentence: "He checked his {{BLANK}} nervously while waiting for the train to arrive.",
    cn: "他緊張地看著手錶等待火車到來。" },
  { word: "handkerchief", pos: "n.", cn_def: "手帕", en_def: "a small square piece of cloth used for wiping the nose or face",
    sentence: "He offered his clean {{BLANK}} when she started crying at the sad movie.",
    cn: "當她在那部悲傷的電影裡哭起來時，他遞給她一條乾淨的手帕。" },
  { word: "mask", pos: "n.", cn_def: "口罩", en_def: "a covering worn over the face or mouth and nose",
    sentence: "He wore a {{BLANK}} while cleaning the dusty old attic.",
    cn: "他清理那個滿是灰塵的舊閣樓時戴著口罩。" },
  { word: "hanger", pos: "n.", cn_def: "衣架", en_def: "a curved piece of plastic or wood used to hang clothes",
    sentence: "She hung her new coat carefully on a wooden {{BLANK}} in the closet.",
    cn: "她把新買的大衣小心地掛在衣櫃裡的木製衣架上。" },
  { word: "color", pos: "n.", cn_def: "顏色", en_def: "the quality that makes something look red, blue, green, and so on",
    sentence: "She could not decide which {{BLANK}} to paint her bedroom walls.",
    cn: "她無法決定要把臥室的牆漆成什麼顏色。" },
  { word: "colorful", pos: "adj.", cn_def: "色彩鮮豔的", en_def: "full of bright colors",
    sentence: "The festival parade was full of {{BLANK}} costumes and decorations.",
    cn: "這場節日遊行充滿了色彩鮮豔的服裝和裝飾。" },
  { word: "black", pos: "adj.", cn_def: "黑色的", en_def: "having the darkest color, like the night sky",
    sentence: "He wore a {{BLANK}} suit to his grandfather's funeral.",
    cn: "他穿了一套黑色西裝去參加爺爺的喪禮。" },
  { word: "white", pos: "adj.", cn_def: "白色的", en_def: "having the color of snow or milk",
    sentence: "She painted the kitchen walls a bright {{BLANK}} to make the room feel larger.",
    cn: "她把廚房的牆漆成明亮的白色，讓房間感覺更大。" },
  { word: "gray", pos: "adj.", cn_def: "灰色的", en_def: "having a color between black and white",
    sentence: "The sky turned {{BLANK}} just before the heavy rain started.",
    cn: "天空在大雨開始前變成了灰色。" },
  { word: "red", pos: "adj.", cn_def: "紅色的", en_def: "having the color of blood or a ripe tomato",
    sentence: "She wore a bright {{BLANK}} dress to stand out at the party.",
    cn: "她穿了一件鮮紅色的洋裝，在派對上顯得格外亮眼。" },
  { word: "pink", pos: "adj.", cn_def: "粉紅色的", en_def: "having a light reddish color",
    sentence: "My little sister's room is decorated entirely in {{BLANK}}.",
    cn: "我妹妹的房間全部都用粉紅色裝飾。" },
  { word: "yellow", pos: "adj.", cn_def: "黃色的", en_def: "having the color of a lemon or the sun",
    sentence: "The school bus stopped at the corner, its bright {{BLANK}} paint easy to spot.",
    cn: "那輛校車在轉角停下，鮮黃色的車身很容易就能看到。" },
  { word: "green", pos: "adj.", cn_def: "綠色的", en_def: "having the color of grass or leaves",
    sentence: "The hills turned a deep {{BLANK}} after weeks of steady rain.",
    cn: "經過幾週的持續降雨，山丘變成了深綠色。" },
  { word: "blue", pos: "adj.", cn_def: "藍色的", en_def: "having the color of a clear sky",
    sentence: "The ocean looked perfectly {{BLANK}} under the bright morning sun.",
    cn: "在明亮的早晨陽光下，海洋看起來是完美的藍色。" },
  { word: "purple", pos: "adj.", cn_def: "紫色的", en_def: "having a color made by mixing red and blue",
    sentence: "She picked a {{BLANK}} ribbon to match her new dress.",
    cn: "她挑了一條紫色緞帶來搭配她的新洋裝。" },
  { word: "brown", pos: "adj.", cn_def: "棕色的", en_def: "having the color of wood, soil, or coffee",
    sentence: "He has short {{BLANK}} hair and bright brown eyes like his father.",
    cn: "他和他爸爸一樣留著棕色短髮和明亮的棕色眼睛。" },
  { word: "golden", pos: "adj.", cn_def: "金色的", en_def: "having a bright yellow color, like gold",
    sentence: "The sunset painted the sky a warm {{BLANK}} shade that evening.",
    cn: "那天晚上的日落把天空染成了溫暖的金色。" },
  { word: "silver", pos: "adj.", cn_def: "銀色的", en_def: "having a shiny gray color, like the metal silver",
    sentence: "She wore a {{BLANK}} bracelet that matched her earrings perfectly.",
    cn: "她戴了一條和耳環完美搭配的銀色手環。" }
];

// ---- Part 2 data: 35 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (9/9/9/8), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "Riding the bus home from school, he wanted to keep his ticket somewhere safe. He slid it into his jacket ______ for the whole ride.",
    options: ["wallet","purse","pocket","bag"], answer: 2, vocabIndex: 0 },
  { q: "Getting ready for school every morning, she always checks that her textbooks are organized neatly. She packs them carefully into her ______ before leaving.",
    options: ["wallet","backpack","purse","belt"], answer: 1, vocabIndex: 1 },
  { q: "Bringing lunch to school every single day, he never uses anything fancy to carry it. He simply puts it inside a small paper ______.",
    options: ["wallet","pocket","belt","bag"], answer: 3, vocabIndex: 2 },
  { q: "Standing outside her front door, she suddenly realized she could not find her house keys anywhere. She dug through her ______ searching everywhere.",
    options: ["wallet","backpack","purse","pocket"], answer: 2, vocabIndex: 3 },
  { q: "Reaching into his back pocket at the checkout counter, he felt a moment of panic. He checked twice to make sure his ______ was still there.",
    options: ["purse","wallet","bag","watch"], answer: 1, vocabIndex: 4 },
  { q: "After losing a little weight last month, his clothes started feeling slightly loose around his waist. He had to tighten his ______ a notch.",
    options: ["scarf","tie","belt","glove"], answer: 2, vocabIndex: 5 },
  { q: "Getting dressed in a hurry this morning, he noticed something small had come loose on his shirt. One ______ had fallen off completely.",
    options: ["button","belt","tie","ring"], answer: 0, vocabIndex: 6 },
  { q: "Skateboarding at the park after school, he liked to wear his favorite piece of headwear in a certain way. He turned his baseball ______ backward.",
    options: ["hat","cap","scarf","mask"], answer: 1, vocabIndex: 7 },
  { q: "Spending the afternoon at the beach under a bright sun, she wanted to protect her face from getting burned. She wore a wide straw ______.",
    options: ["cap","scarf","mask","hat"], answer: 3, vocabIndex: 8 },
  { q: "Building a snowman in the freezing cold backyard, he needed something to keep his hands warm. He pulled on a thick winter ______ first.",
    options: ["scarf","belt","glove","tie"], answer: 2, vocabIndex: 9 },
  { q: "Stepping outside into the chilly autumn wind, she wanted to keep her neck warm on the walk to school. She wrapped a soft wool ______ around it.",
    options: ["tie","glove","belt","scarf"], answer: 3, vocabIndex: 10 },
  { q: "Getting ready for his job interview, he wanted his outfit to look sharp and professional. He chose a blue ______ to match his suit.",
    options: ["tie","scarf","glove","cap"], answer: 0, vocabIndex: 11 },
  { q: "Sitting at the front of the classroom, she squinted at the whiteboard, unable to make out the small writing. She simply could not read it clearly without her ______.",
    options: ["watch","mask","glasses","ring"], answer: 2, vocabIndex: 12 },
  { q: "Playing competitive sports every weekend, she found regular glasses uncomfortable and inconvenient during games. She prefers wearing a ______ instead.",
    options: ["mask","contact lens","watch","scarf"], answer: 1, vocabIndex: 13 },
  { q: "Turning sixteen this year, she received a thoughtful gift from her grandmother for the special occasion. It was a pair of pearl ______.",
    options: ["necklace","ring","earrings","watch"], answer: 2, vocabIndex: 14 },
  { q: "Dressing up for a special evening out, she wanted something elegant around her neck. She chose a gold ______ with a tiny heart pendant.",
    options: ["earrings","ring","scarf","necklace"], answer: 3, vocabIndex: 15 },
  { q: "Standing together on the quiet beach at sunset, he reached into his pocket for something he had been carrying all day. He proposed with a beautiful diamond ______.",
    options: ["necklace","ring","watch","earrings"], answer: 1, vocabIndex: 16 },
  { q: "Waiting nervously at the train station for an important delivery, he kept glancing down at his wrist every few minutes. He checked his ______ again and again.",
    options: ["watch","ring","glasses","belt"], answer: 0, vocabIndex: 17 },
  { q: "Watching a sad movie together at the theater, she suddenly began crying during one particular scene. He quietly offered his clean ______ to help.",
    options: ["scarf","handkerchief","glove","tie"], answer: 1, vocabIndex: 18 },
  { q: "Cleaning out the dusty old attic on a hot afternoon, he worried about breathing in too much dust. He wore a ______ the entire time.",
    options: ["mask","hat","scarf","glove"], answer: 0, vocabIndex: 19 },
  { q: "Putting away her brand-new winter coat in the closet, she wanted to keep it from getting wrinkled. She hung it carefully on a wooden ______.",
    options: ["belt","button","pocket","hanger"], answer: 3, vocabIndex: 20 },
  { q: "Redecorating her bedroom for the new school year, she stood in the paint aisle feeling completely overwhelmed by the choices. She could not decide which ______ to choose for the walls.",
    options: ["color","size","style","shape"], answer: 0, vocabIndex: 21 },
  { q: "Walking down the main street during the annual festival, visitors stopped to admire the elaborate floats passing by. The whole parade was full of ______ costumes and decorations.",
    options: ["fashionable","colorful","expensive","traditional"], answer: 1, vocabIndex: 22 },
  { q: "Attending a quiet, somber ceremony at the cemetery last weekend, he wanted to dress respectfully for the occasion. He wore a ______ suit to his grandfather's funeral.",
    options: ["black","white","gray","brown"], answer: 0, vocabIndex: 23 },
  { q: "Trying to make her small kitchen feel more spacious, she chose a particular paint color for the walls. She painted them a bright ______ to open up the room.",
    options: ["black","white","gray","brown"], answer: 1, vocabIndex: 24 },
  { q: "Looking up at the sky just before the storm arrived, the clouds shifted to a noticeably different shade. The sky turned ______ right before the heavy rain started.",
    options: ["gray","yellow","green","pink"], answer: 0, vocabIndex: 25 },
  { q: "Arriving at the lively birthday party that evening, she wanted to be noticed in the crowded room. She wore a bright ______ dress to stand out.",
    options: ["white","gray","red","brown"], answer: 2, vocabIndex: 26 },
  { q: "Walking into her little sister's bedroom for the first time, she immediately noticed the theme of the entire room. It was decorated completely in ______.",
    options: ["gray","brown","black","pink"], answer: 3, vocabIndex: 27 },
  { q: "Standing at the busy intersection waiting to cross, students immediately recognized which vehicle belonged to their school. The bus had bright ______ paint that was easy to spot.",
    options: ["red","yellow","green","purple"], answer: 1, vocabIndex: 28 },
  { q: "Hiking through the countryside after weeks of steady rainfall, visitors noticed something striking about the landscape around them. The hills had turned a deep, rich ______.",
    options: ["yellow","brown","green","gray"], answer: 2, vocabIndex: 29 },
  { q: "Sailing across the calm water early one morning, passengers leaned over the railing to admire the scenery. The ocean looked perfectly ______ under the bright sun.",
    options: ["blue","green","purple","gray"], answer: 0, vocabIndex: 30 },
  { q: "Shopping for accessories to match her new dress before the dance, she searched through several ribbon colors at the store. She finally picked a ______ ribbon that matched perfectly.",
    options: ["yellow","red","green","purple"], answer: 3, vocabIndex: 31 },
  { q: "Looking closely at old family photographs from years ago, she noticed how much her brother resembled their father. He has short ______ hair just like him.",
    options: ["brown","black","gray","blonde"], answer: 0, vocabIndex: 32 },
  { q: "Watching the sun disappear slowly behind the distant mountains that evening, the whole sky transformed into something beautiful. It turned a warm ______ shade just before dark.",
    options: ["silver","gray","golden","purple"], answer: 2, vocabIndex: 33 },
  { q: "Getting dressed for the formal dinner party, she wanted her accessories to look coordinated and elegant together. She wore a ______ bracelet that matched her earrings perfectly.",
    options: ["golden","brown","pink","silver"], answer: 3, vocabIndex: 34 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "attic": { pos: "n.", en_def: "a space or room just below the roof of a house", cn_def: "閣樓" },
  "beach": { pos: "n.", en_def: "the sandy or rocky area next to the ocean", cn_def: "海灘" },
  "birthday": { pos: "n.", en_def: "the day of the year a person was born", cn_def: "生日" },
  "blonde": { pos: "adj.", en_def: "having pale yellow hair", cn_def: "金髮的" },
  "bracelet": { pos: "n.", en_def: "a piece of jewelry worn around the wrist", cn_def: "手環；手鐲" },
  "closet": { pos: "n.", en_def: "a small room or cabinet used for storing clothes", cn_def: "衣櫃；儲藏室" },
  "costumes": { pos: "n.", en_def: "special clothes worn for a performance or celebration", cn_def: "服裝（複數）" },
  "decorations": { pos: "n.", en_def: "things used to make a place look nicer", cn_def: "裝飾品" },
  "diamond": { pos: "n.", en_def: "a hard, clear, valuable precious stone", cn_def: "鑽石" },
  "expensive": { pos: "adj.", en_def: "costing a lot of money", cn_def: "昂貴的" },
  "fashionable": { pos: "adj.", en_def: "stylish; in keeping with current trends", cn_def: "時尚的" },
  "festival": { pos: "n.", en_def: "a special day or time of celebration", cn_def: "節日" },
  "funeral": { pos: "n.", en_def: "a ceremony held when someone has died", cn_def: "葬禮" },
  "interview": { pos: "n.", en_def: "a formal meeting where someone is asked questions about a job", cn_def: "面試" },
  "intersection": { pos: "n.", en_def: "a place where two or more roads meet", cn_def: "十字路口" },
  "ocean": { pos: "n.", en_def: "a very large area of salt water", cn_def: "海洋" },
  "paint": { pos: "n.", en_def: "a colored liquid used to add color to a surface", cn_def: "顏料；油漆" },
  "parade": { pos: "n.", en_def: "a public event where people walk or ride through the streets", cn_def: "遊行" },
  "pearl": { pos: "n.", en_def: "a small round white gem formed inside an oyster shell", cn_def: "珍珠" },
  "pendant": { pos: "n.", en_def: "a small decoration hanging from a necklace", cn_def: "吊飾" },
  "ribbon": { pos: "n.", en_def: "a thin strip of cloth used for tying or decoration", cn_def: "緞帶" },
  "shade": { pos: "n.", en_def: "a particular tone of a color", cn_def: "色調" },
  "shape": { pos: "n.", en_def: "the form or outline of something", cn_def: "形狀" },
  "size": { pos: "n.", en_def: "how big or small something is", cn_def: "尺寸" },
  "skateboarding": { pos: "n.", en_def: "the activity of riding a board with wheels", cn_def: "玩滑板" },
  "snowman": { pos: "n.", en_def: "a figure made of snow shaped like a person", cn_def: "雪人" },
  "straw": { pos: "n.", en_def: "dried plant stems used to make hats or other items", cn_def: "稻草；麥稈" },
  "style": { pos: "n.", en_def: "a particular way of doing or making something", cn_def: "風格；款式" },
  "traditional": { pos: "adj.", en_def: "following customs that have existed for a long time", cn_def: "傳統的" },
  "whiteboard": { pos: "n.", en_def: "a white board used for writing with markers", cn_def: "白板" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
