// ============================================================
// Group 15 Quiz Data: Personality Traits / Emotions
// Full word set (49 words) — personality and character
// adjectives plus emotion words/verbs from the "describing
// words" theme. Difficulty/quality, size/state/safety, and
// general adjectives will follow as later groups.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 15 - Personality Traits / Emotions (個性/情緒)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (49 words) ----
const VOCAB = [
  { word: "careful", pos: "adj.", cn_def: "仔細的", en_def: "paying close attention to avoid mistakes or danger",
    sentence: "Please be {{BLANK}} when you cross the busy street near the school.",
    cn: "在學校附近過那條繁忙的街道時，請小心一點。" },
  { word: "careless", pos: "adj.", cn_def: "粗心的", en_def: "not paying enough attention; making mistakes easily",
    sentence: "He made a {{BLANK}} mistake on the test by forgetting to check his answers.",
    cn: "他因為忘記檢查答案，在考試中犯了一個粗心的錯誤。" },
  { word: "childish", pos: "adj.", cn_def: "幼稚的", en_def: "behaving in a silly way that is not appropriate for an adult",
    sentence: "Everyone thought it was {{BLANK}} of him to cry over losing a board game.",
    cn: "大家都覺得他因為輸了一場桌遊就哭，這樣很幼稚。" },
  { word: "childlike", pos: "adj.", cn_def: "天真的", en_def: "having the innocent or simple qualities of a child",
    sentence: "My grandmother still has a {{BLANK}} sense of wonder whenever she sees the ocean.",
    cn: "我奶奶每次看到海洋時，仍然帶著一種天真的驚奇感。" },
  { word: "evil", pos: "adj.", cn_def: "邪惡的", en_def: "morally very bad or wrong",
    sentence: "In the story, the {{BLANK}} witch tried to trap the children in her cottage.",
    cn: "在這個故事裡，邪惡的女巫試圖把孩子們困在她的小屋裡。" },
  { word: "friendly", pos: "adj.", cn_def: "親切的", en_def: "kind and pleasant toward other people",
    sentence: "Our new neighbor is very {{BLANK}} and always says hello when we see her.",
    cn: "我們的新鄰居非常親切，每次見到我們都會打招呼。" },
  { word: "kind", pos: "adj.", cn_def: "親切的", en_def: "caring and gentle toward others",
    sentence: "It was {{BLANK}} of you to help that old man carry his heavy bags.",
    cn: "你幫那位老人提重重的袋子，這樣很親切。" },
  { word: "funny", pos: "adj.", cn_def: "好笑的", en_def: "causing laughter; amusing",
    sentence: "The comedian told such a {{BLANK}} joke that everyone in the room laughed out loud.",
    cn: "那位喜劇演員講了一個很好笑的笑話，讓全場的人都笑了出來。" },
  { word: "naughty", pos: "adj.", cn_def: "頑皮的", en_def: "behaving badly, often used for children",
    sentence: "The {{BLANK}} puppy chewed up my favorite shoes while I was at school.",
    cn: "那隻頑皮的小狗在我上學時把我最喜歡的鞋子咬爛了。" },
  { word: "generous", pos: "adj.", cn_def: "慷慨的", en_def: "willing to give freely to others",
    sentence: "My uncle is so {{BLANK}} that he always pays for the whole family's dinner.",
    cn: "我叔叔非常慷慨，總是幫全家人付晚餐的錢。" },
  { word: "stingy", pos: "adj.", cn_def: "小氣的", en_def: "unwilling to spend or share money",
    sentence: "He is too {{BLANK}} to buy a birthday gift, even for his own brother.",
    cn: "他太小氣了，連自己的弟弟生日都不肯買禮物。" },
  { word: "selfish", pos: "adj.", cn_def: "自私的", en_def: "caring only about yourself, not about others",
    sentence: "It seemed {{BLANK}} of him to eat the last slice of pizza without asking anyone.",
    cn: "他沒問任何人就吃掉了最後一片披薩，這樣顯得很自私。" },
  { word: "gentle", pos: "adj.", cn_def: "溫和的", en_def: "kind, calm, and not rough or harsh",
    sentence: "The nurse spoke in a {{BLANK}} voice to calm the crying child.",
    cn: "護士用溫和的聲音安慰那個哭泣的孩子。" },
  { word: "good", pos: "adj.", cn_def: "好的", en_def: "having positive or pleasant qualities",
    sentence: "She always gets {{BLANK}} grades because she studies hard every night.",
    cn: "她每天晚上都用功學習，所以總是得到好成績。" },
  { word: "bad", pos: "adj.", cn_def: "壞的", en_def: "having negative or unpleasant qualities",
    sentence: "Eating too much candy before bedtime is a {{BLANK}} habit for your teeth.",
    cn: "睡前吃太多糖果對牙齒是個壞習慣。" },
  { word: "diligent", pos: "adj.", cn_def: "勤勉的", en_def: "working hard and carefully on something",
    sentence: "The {{BLANK}} student reviewed her notes every single evening before the big exam.",
    cn: "那位勤勉的學生在大考前每天晚上都會複習筆記。" },
  { word: "hard-working", pos: "adj.", cn_def: "勤勉的", en_def: "putting a lot of effort into work or study",
    sentence: "My father is a {{BLANK}} farmer who wakes up before sunrise every single day.",
    cn: "我爸爸是一位勤勞的農夫，每天都在日出前起床。" },
  { word: "lazy", pos: "adj.", cn_def: "懶惰的", en_def: "not willing to work or make an effort",
    sentence: "My brother felt too {{BLANK}} to clean his room, so it stayed messy all weekend.",
    cn: "我哥哥太懶了不想打掃房間，所以整個週末房間都亂糟糟的。" },
  { word: "honest", pos: "adj.", cn_def: "誠實的", en_def: "telling the truth; not lying or cheating",
    sentence: "Even though it was difficult, she gave an {{BLANK}} answer about what happened.",
    cn: "雖然很困難，她還是誠實地說出了發生的事情。" },
  { word: "dishonest", pos: "adj.", cn_def: "不誠實的", en_def: "telling lies or trying to deceive someone",
    sentence: "The shopkeeper was caught being {{BLANK}} about the price of the broken toy.",
    cn: "那位店主被發現對那個壞掉的玩具的價格不誠實。" },
  { word: "sincere", pos: "adj.", cn_def: "真誠的", en_def: "genuine and honest in feelings or words",
    sentence: "He wrote a {{BLANK}} letter to thank his teacher for years of patient support.",
    cn: "他寫了一封真誠的信，感謝老師多年來的耐心支持。" },
  { word: "responsible", pos: "adj.", cn_def: "負責任的", en_def: "able to be trusted to do what is expected",
    sentence: "As the oldest child, she felt {{BLANK}} for taking care of her younger siblings.",
    cn: "作為最大的孩子，她覺得自己有責任照顧弟妹。" },
  { word: "humble", pos: "adj.", cn_def: "謙虛的", en_def: "not proud; modest about one's own abilities",
    sentence: "Even after winning the competition, the young singer remained surprisingly {{BLANK}}.",
    cn: "即使贏得了比賽，那位年輕歌手依然出乎意料地謙虛。" },
  { word: "proud", pos: "adj.", cn_def: "驕傲的", en_def: "feeling pleased about something you or others have achieved",
    sentence: "My parents looked so {{BLANK}} when I received my diploma on stage.",
    cn: "當我在台上領取畢業證書時，我父母看起來非常驕傲。" },
  { word: "humorous", pos: "adj.", cn_def: "幽默的", en_def: "funny and entertaining",
    sentence: "The teacher told a {{BLANK}} story that made the whole class smile.",
    cn: "老師講了一個幽默的故事，讓全班都露出了笑容。" },
  { word: "afraid", pos: "adj.", cn_def: "害怕的", en_def: "feeling fear about something",
    sentence: "My little sister is {{BLANK}} of thunderstorms and hides under her blanket.",
    cn: "我妹妹很怕打雷，每次都躲在毯子下面。" },
  { word: "angry", pos: "adj.", cn_def: "生氣的", en_def: "feeling strong displeasure",
    sentence: "My mother was {{BLANK}} when she found out I had broken her favorite vase.",
    cn: "我媽媽發現我打破了她最喜歡的花瓶時非常生氣。" },
  { word: "mad", pos: "adj.", cn_def: "生氣的", en_def: "very angry",
    sentence: "He got so {{BLANK}} when his little brother erased his homework by accident.",
    cn: "當他弟弟不小心擦掉他的作業時，他非常生氣。" },
  { word: "bored", pos: "adj.", cn_def: "感到厭煩的", en_def: "feeling tired and uninterested because there is nothing to do",
    sentence: "The students looked completely {{BLANK}} during the long, slow lecture.",
    cn: "在這場又長又無聊的課程中，學生們看起來非常厭煩。" },
  { word: "excited", pos: "adj.", cn_def: "感到興奮的", en_def: "feeling very happy and full of energy about something",
    sentence: "We were all so {{BLANK}} when we heard about the surprise trip to the zoo.",
    cn: "我們聽到要去動物園的驚喜旅行時都非常興奮。" },
  { word: "jealous", pos: "adj.", cn_def: "嫉妒的", en_def: "feeling unhappy because someone else has something you want",
    sentence: "She felt a little {{BLANK}} when her friend got a brand-new bicycle for her birthday.",
    cn: "當她朋友生日收到一台全新的自行車時，她有點嫉妒。" },
  { word: "lonely", pos: "adj.", cn_def: "寂寞的", en_def: "feeling sad because you are alone",
    sentence: "After moving to a new city, he felt {{BLANK}} until he made some new friends.",
    cn: "搬到新城市後，他在交到新朋友之前感到很寂寞。" },
  { word: "nervous", pos: "adj.", cn_def: "緊張的", en_def: "worried or afraid about what might happen",
    sentence: "I always feel {{BLANK}} right before giving a speech in front of the class.",
    cn: "每次在班上演講前我總是覺得很緊張。" },
  { word: "glad", pos: "adj.", cn_def: "高興的", en_def: "feeling pleased about something",
    sentence: "I was so {{BLANK}} to hear that my cousin had passed her driving test.",
    cn: "聽到我表姐通過了駕照考試，我感到非常高興。" },
  { word: "happy", pos: "adj.", cn_def: "快樂的", en_def: "feeling joy or pleasure",
    sentence: "The whole family looked {{BLANK}} as they opened their presents together on Christmas morning.",
    cn: "聖誕節早上全家人一起打開禮物時看起來都很快樂。" },
  { word: "pleased", pos: "adj.", cn_def: "滿意的", en_def: "feeling satisfied or happy about something",
    sentence: "The coach was very {{BLANK}} with how hard the team practiced this week.",
    cn: "教練對球隊這週的努力練習感到非常滿意。" },
  { word: "sad", pos: "adj.", cn_def: "悲傷的", en_def: "feeling unhappy, often because of a loss",
    sentence: "Everyone felt {{BLANK}} when the beloved old teacher retired at the end of the year.",
    cn: "當這位深受喜愛的老教師在年底退休時，大家都感到很悲傷。" },
  { word: "sorry", pos: "adj.", cn_def: "抱歉的", en_def: "feeling regret about something you did",
    sentence: "He said he was {{BLANK}} for accidentally stepping on his classmate's foot.",
    cn: "他說他很抱歉不小心踩到了同學的腳。" },
  { word: "unhappy", pos: "adj.", cn_def: "不快樂的", en_def: "not feeling pleased or satisfied",
    sentence: "The customer looked {{BLANK}} after waiting nearly an hour for his food.",
    cn: "那位顧客等了將近一小時才拿到食物，看起來很不開心。" },
  { word: "surprised", pos: "adj.", cn_def: "感到驚訝的", en_def: "feeling shock at something unexpected",
    sentence: "We were completely {{BLANK}} when all our relatives jumped out for the party.",
    cn: "當所有親戚都跳出來為派對驚喜時，我們都感到非常驚訝。" },
  { word: "feel", pos: "v.", cn_def: "感覺", en_def: "to experience an emotion or physical sensation",
    sentence: "After the long hike, my legs began to {{BLANK}} very tired and sore.",
    cn: "經過長時間的健行後，我的腿開始覺得非常疲倦和痠痛。" },
  { word: "admire", pos: "v.", cn_def: "欽佩", en_def: "to respect and approve of someone or something",
    sentence: "Many students {{BLANK}} their teacher's patience and kindness toward everyone.",
    cn: "許多學生都欽佩老師對每個人的耐心和親切。" },
  { word: "anger", pos: "v.", cn_def: "激怒", en_def: "to make someone feel angry",
    sentence: "It seemed to {{BLANK}} him whenever someone interrupted his story.",
    cn: "每次有人打斷他講故事時，似乎都會激怒他。" },
  { word: "envy", pos: "v.", cn_def: "羨慕", en_def: "to wish you had what someone else has",
    sentence: "I have to admit I {{BLANK}} my friend's ability to learn languages so quickly.",
    cn: "我必須承認我很羨慕我朋友能這麼快學會語言的能力。" },
  { word: "fear", pos: "v.", cn_def: "畏懼", en_def: "to feel afraid of something",
    sentence: "Many small children {{BLANK}} the dark and need a night light to sleep.",
    cn: "許多小孩都害怕黑暗，需要小夜燈才能睡覺。" },
  { word: "hate", pos: "v.", cn_def: "厭惡", en_def: "to dislike something or someone very strongly",
    sentence: "My little brother says he absolutely {{BLANK}} eating vegetables of any kind.",
    cn: "我弟弟說他非常厭惡吃任何種類的蔬菜。" },
  { word: "regret", pos: "v.", cn_def: "懊悔", en_def: "to feel sorry about something you did or did not do",
    sentence: "She will always {{BLANK}} not telling her grandfather how much she loved him.",
    cn: "她將永遠懊悔沒有告訴爺爺她有多愛他。" },
  { word: "respect", pos: "v.", cn_def: "尊敬", en_def: "to have a high opinion of someone",
    sentence: "Students should {{BLANK}} their teachers by listening quietly during class.",
    cn: "學生應該在課堂上安靜聆聽，以尊敬老師。" },
  { word: "worry", pos: "v.", cn_def: "擔心", en_def: "to feel anxious or troubled about something",
    sentence: "My mother always starts to {{BLANK}} if I come home later than expected.",
    cn: "如果我比預期的時間晚回家，我媽媽總是會開始擔心。" }
];

// ---- Part 2 data: 49 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (13/12/12/12), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "The street near the school is always busy with cars and bicycles. Please be ______ when you cross it after class.",
    options: ["careless","childish","careful","kind"], answer: 2, vocabIndex: 0 },
  { q: "On the test, he forgot to check his answers before turning in the paper. That ______ mistake cost him several points.",
    options: ["careless","careful","generous","selfish"], answer: 0, vocabIndex: 1 },
  { q: "He lost a simple board game and started crying loudly in front of everyone. Most classmates thought his reaction seemed quite ______.",
    options: ["childlike","humble","childish","sincere"], answer: 2, vocabIndex: 2 },
  { q: "Even at her age, my grandmother still gets excited every time she sees the ocean. She has such a ______ sense of wonder.",
    options: ["childish","childlike","evil","naughty"], answer: 1, vocabIndex: 3 },
  { q: "In the old fairy tale, a wicked witch wanted to lock the children inside her cottage forever. Everyone in the village feared the ______ witch.",
    options: ["gentle","kind","evil","humble"], answer: 2, vocabIndex: 4 },
  { q: "Our new neighbor always smiles and says hello whenever she sees us outside. Everyone agrees she seems incredibly ______.",
    options: ["friendly","selfish","stingy","evil"], answer: 0, vocabIndex: 5 },
  { q: "You stopped to help that elderly man carry his heavy shopping bags up the stairs. That was a very ______ thing to do.",
    options: ["selfish","lazy","stingy","kind"], answer: 3, vocabIndex: 6 },
  { q: "The comedian told a joke about his cat that made the entire audience burst into laughter. Everyone agreed it was incredibly ______.",
    options: ["funny","serious","sad","boring"], answer: 0, vocabIndex: 7 },
  { q: "While I was at school, the new puppy chewed up one of my favorite pairs of shoes. That ______ little dog needs more training.",
    options: ["gentle","diligent","honest","naughty"], answer: 3, vocabIndex: 8 },
  { q: "My uncle always insists on paying for everyone's dinner whenever the whole family goes out together. He is known for being incredibly ______.",
    options: ["stingy","generous","selfish","careless"], answer: 1, vocabIndex: 9 },
  { q: "Even though it was his own brother's birthday, he refused to spend any money on a gift. Everyone called him ______ behind his back.",
    options: ["generous","gentle","kind","stingy"], answer: 3, vocabIndex: 10 },
  { q: "He grabbed the last slice of pizza without asking if anyone else wanted some. His sister thought that was a very ______ thing to do.",
    options: ["generous","selfish","kind","humble"], answer: 1, vocabIndex: 11 },
  { q: "The nurse spoke in a soft, calm voice while trying to comfort the crying child. Her ______ manner helped the little boy relax quickly.",
    options: ["angry","proud","gentle","stingy"], answer: 2, vocabIndex: 12 },
  { q: "She studies hard every single night and rarely misses turning in an assignment. As a result, she usually gets ______ grades on her report card.",
    options: ["bad","lazy","evil","good"], answer: 3, vocabIndex: 13 },
  { q: "Eating too much candy right before going to sleep can quickly damage your teeth. Dentists agree it is a ______ habit for children.",
    options: ["good","bad","diligent","honest"], answer: 1, vocabIndex: 14 },
  { q: "She reviews her class notes every single evening, even when there is no test the next day. Her teachers describe her as remarkably ______.",
    options: ["diligent","lazy","selfish","naughty"], answer: 0, vocabIndex: 15 },
  { q: "My father wakes up before sunrise every single morning to take care of the farm animals. Everyone in the village calls him a truly ______ man.",
    options: ["lazy","hard-working","careless","stingy"], answer: 1, vocabIndex: 16 },
  { q: "My brother kept putting off cleaning his messy room all weekend long, finding excuses every time. His room stayed a mess because he felt too ______.",
    options: ["diligent","responsible","lazy","humble"], answer: 2, vocabIndex: 17 },
  { q: "Even though admitting the mistake was embarrassing, she told her teacher exactly what had happened. Her ______ answer surprised everyone in the room.",
    options: ["honest","dishonest","careless","selfish"], answer: 0, vocabIndex: 18 },
  { q: "The shopkeeper claimed the broken toy was brand new and tried to charge full price for it. Customers soon discovered how ______ he really was.",
    options: ["honest","dishonest","sincere","responsible"], answer: 1, vocabIndex: 19 },
  { q: "After years of patient lessons, the student finally wrote a heartfelt letter thanking her teacher. Everyone could tell how ______ her words were.",
    options: ["sincere","dishonest","selfish","evil"], answer: 0, vocabIndex: 20 },
  { q: "As the oldest child in the family, she often watched over her younger brothers and sisters. She took this ______ role very seriously.",
    options: ["lazy","selfish","responsible","childish"], answer: 2, vocabIndex: 21 },
  { q: "Even after winning the singing competition, the young performer did not brag or act superior to anyone. Fans admired how ______ she remained.",
    options: ["humble","proud","selfish","stingy"], answer: 0, vocabIndex: 22 },
  { q: "When my name was called on stage to receive the award, my parents stood up smiling brightly. They looked incredibly ______ of me.",
    options: ["sad","proud","humble","afraid"], answer: 1, vocabIndex: 23 },
  { q: "The teacher told a silly story about her cat falling off a chair, and the whole class burst out laughing. Everyone called it a ______ tale.",
    options: ["serious","sad","humorous","boring"], answer: 2, vocabIndex: 24 },
  { q: "Whenever thunder crashes loudly outside, my little sister immediately hides under her blanket. She has always been ______ of storms.",
    options: ["afraid","excited","proud","bored"], answer: 0, vocabIndex: 25 },
  { q: "When my mother discovered that I had accidentally broken her favorite vase, her face turned red with frustration. She was extremely ______ at me.",
    options: ["happy","glad","pleased","angry"], answer: 3, vocabIndex: 26 },
  { q: "His little brother accidentally erased his entire homework file on the computer without saving it first. He got so ______ he could barely speak.",
    options: ["glad","humble","mad","sincere"], answer: 2, vocabIndex: 27 },
  { q: "The long lecture droned on for nearly two hours without a single interesting moment. By the end, most students looked completely ______.",
    options: ["excited","nervous","jealous","bored"], answer: 3, vocabIndex: 28 },
  { q: "When the teacher announced a surprise field trip to the zoo, the entire class started cheering loudly. Everyone felt incredibly ______ about it.",
    options: ["bored","lonely","excited","sorry"], answer: 2, vocabIndex: 29 },
  { q: "Her best friend received a brand-new bicycle as a birthday gift from her parents. She tried not to show it, but she felt a little ______.",
    options: ["proud","humble","sincere","jealous"], answer: 3, vocabIndex: 30 },
  { q: "After moving to a completely new city where he knew nobody, he spent his evenings alone in his apartment. He felt deeply ______ for several months.",
    options: ["lonely","excited","jealous","happy"], answer: 0, vocabIndex: 31 },
  { q: "Right before standing up to give a speech in front of the entire class, my hands always start shaking slightly. I always feel ______ in that moment.",
    options: ["glad","nervous","proud","bored"], answer: 1, vocabIndex: 32 },
  { q: "My cousin called to share some wonderful news about finally passing her driving test on the third try. I was so ______ to hear it.",
    options: ["sad","angry","jealous","glad"], answer: 3, vocabIndex: 33 },
  { q: "On Christmas morning, the whole family gathered around the tree and opened their presents together with big smiles. Everyone looked genuinely ______.",
    options: ["happy","sad","bored","nervous"], answer: 0, vocabIndex: 34 },
  { q: "The basketball coach watched the team practice extra hard all week without a single complaint. He seemed very ______ with their effort and progress.",
    options: ["angry","jealous","sad","pleased"], answer: 3, vocabIndex: 35 },
  { q: "After thirty wonderful years of teaching, the beloved old teacher finally retired at the end of the school year. Many students felt quite ______ saying goodbye.",
    options: ["happy","excited","sad","glad"], answer: 2, vocabIndex: 36 },
  { q: "He accidentally stepped on his classmate's foot while rushing to grab a seat near the window. He quickly apologized and said he felt very ______.",
    options: ["proud","sorry","happy","excited"], answer: 1, vocabIndex: 37 },
  { q: "The customer waited almost a full hour for his food order to finally arrive at the table. By the time it came, he looked noticeably ______.",
    options: ["happy","pleased","unhappy","glad"], answer: 2, vocabIndex: 38 },
  { q: "When all of our relatives suddenly jumped out from behind the furniture shouting happy birthday, we froze for a second. We were completely ______.",
    options: ["bored","surprised","sad","lonely"], answer: 1, vocabIndex: 39 },
  { q: "After finishing the long, tiring hike up the mountain trail, his legs grew heavier with every step. He began to ______ extremely sore and exhausted.",
    options: ["feel","admire","envy","fear"], answer: 0, vocabIndex: 40 },
  { q: "Many students in the class often talk about how patient and kind their homeroom teacher always is. They genuinely ______ her dedication to every student.",
    options: ["fear","admire","hate","regret"], answer: 1, vocabIndex: 41 },
  { q: "Every time someone interrupted him in the middle of telling his favorite story, his face would turn slightly red. It seemed to truly ______ him.",
    options: ["respect","envy","worry","anger"], answer: 3, vocabIndex: 42 },
  { q: "My friend can pick up a new language within just a few months of practice, which honestly impresses me. I have to admit I sometimes ______ that talent.",
    options: ["fear","hate","envy","respect"], answer: 2, vocabIndex: 43 },
  { q: "Many young children become nervous when the lights go out at bedtime and refuse to sleep without a small lamp. They clearly ______ the dark.",
    options: ["admire","respect","regret","fear"], answer: 3, vocabIndex: 44 },
  { q: "My little brother insists that he cannot stand eating any kind of vegetable, no matter how it is cooked. He says he truly ______ them.",
    options: ["hate","admire","respect","envy"], answer: 0, vocabIndex: 45 },
  { q: "She never got the chance to tell her grandfather how much his support had meant to her before he passed away. She will always ______ that missed moment.",
    options: ["envy","regret","fear","admire"], answer: 1, vocabIndex: 46 },
  { q: "Good students usually listen quietly and pay close attention whenever their teacher is explaining something important. This shows that they truly ______ their teachers.",
    options: ["respect","fear","hate","envy"], answer: 0, vocabIndex: 47 },
  { q: "Whenever I come home later than the time I promised, my mother starts pacing near the front door. She always begins to ______ about my safety.",
    options: ["envy","admire","regret","worry"], answer: 3, vocabIndex: 48 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "ability": { pos: "n.", en_def: "the power or skill to do something", cn_def: "能力" },
  "absolutely": { pos: "adv.", en_def: "completely; totally", cn_def: "完全地；絕對地" },
  "accident": { pos: "n.", en_def: "an unexpected event that causes harm or damage", cn_def: "意外；事故" },
  "accidentally": { pos: "adv.", en_def: "without meaning to; by mistake", cn_def: "不小心地" },
  "admit": { pos: "v.", en_def: "to agree that something is true, even if unwillingly", cn_def: "承認" },
  "bedtime": { pos: "n.", en_def: "the time when a person usually goes to bed", cn_def: "睡覺時間" },
  "beloved": { pos: "adj.", en_def: "loved very much", cn_def: "深受愛戴的" },
  "bicycle": { pos: "n.", en_def: "a two-wheeled vehicle powered by pedaling", cn_def: "自行車" },
  "birthday": { pos: "n.", en_def: "the day of the year a person was born", cn_def: "生日" },
  "blanket": { pos: "n.", en_def: "a thick piece of cloth used for warmth", cn_def: "毯子" },
  "boring": { pos: "adj.", en_def: "not interesting; dull", cn_def: "無聊的" },
  "cottage": { pos: "n.", en_def: "a small house, especially in the countryside", cn_def: "小屋" },
  "diploma": { pos: "n.", en_def: "an official document showing a person finished a course of study", cn_def: "畢業證書" },
  "erased": { pos: "v.", en_def: "removed writing or data completely", cn_def: "擦掉；刪除（過去式）" },
  "habit": { pos: "n.", en_def: "something a person does often and regularly, sometimes without thinking", cn_def: "習慣" },
  "interrupted": { pos: "v.", en_def: "stopped someone while they were speaking or doing something", cn_def: "打斷（過去式）" },
  "kindness": { pos: "n.", en_def: "the quality of being kind and caring", cn_def: "親切；善意" },
  "lecture": { pos: "n.", en_def: "a long talk given to teach about a subject", cn_def: "講座；課程" },
  "passed": { pos: "v.", en_def: "succeeded in a test or exam", cn_def: "通過（過去式）" },
  "patience": { pos: "n.", en_def: "the ability to wait calmly without getting upset", cn_def: "耐心" },
  "puppy": { pos: "n.", en_def: "a baby dog", cn_def: "小狗" },
  "relatives": { pos: "n.", en_def: "people in your family, such as aunts or cousins", cn_def: "親戚（複數）" },
  "retired": { pos: "v.", en_def: "stopped working, usually because of age", cn_def: "退休（過去式）" },
  "reviewed": { pos: "v.", en_def: "looked at or studied something again", cn_def: "複習（過去式）" },
  "serious": { pos: "adj.", en_def: "not funny; thoughtful or grave", cn_def: "嚴肅的" },
  "shopkeeper": { pos: "n.", en_def: "a person who owns or manages a small shop", cn_def: "店主" },
  "siblings": { pos: "n.", en_def: "brothers and sisters", cn_def: "兄弟姊妹" },
  "stage": { pos: "n.", en_def: "a raised platform where performances happen", cn_def: "舞台" },
  "sunrise": { pos: "n.", en_def: "the time in the morning when the sun first appears", cn_def: "日出" },
  "support": { pos: "n.", en_def: "help or encouragement given to someone", cn_def: "支持" },
  "surprisingly": { pos: "adv.", en_def: "in a way that causes surprise", cn_def: "出乎意料地" },
  "thunderstorms": { pos: "n.", en_def: "storms with thunder, lightning, and rain", cn_def: "雷雨（複數）" },
  "trap": { pos: "v.", en_def: "to catch someone or something and prevent escape", cn_def: "困住；陷害" },
  "vase": { pos: "n.", en_def: "a container, often decorative, used to hold flowers", cn_def: "花瓶" },
  "vegetables": { pos: "n.", en_def: "plants or parts of plants eaten as food", cn_def: "蔬菜" },
  "witch": { pos: "n.", en_def: "a woman believed to have magical powers, often in stories", cn_def: "女巫" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
