// ============================================================
// Group 6 Quiz Data: Meals & Common Foods
// Full word set (49 words) — meals, meats, breads/carbs,
// and snacks/desserts from the "food and drinks" theme.
// Condiments moved to Group 7 to balance word counts.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 6 - Meals & Common Foods (三餐/肉類/麵包/點心甜點)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (49 words) ----
const VOCAB = [
  { word: "breakfast", pos: "n.", cn_def: "早餐", en_def: "the first meal of the day, usually eaten in the morning",
    sentence: "Every morning, my mother makes a warm {{BLANK}} for the whole family before school.",
    cn: "每天早上，我媽媽都會在上學前為全家人準備一份溫暖的早餐。" },
  { word: "brunch", pos: "n.", cn_def: "早午餐", en_def: "a meal eaten late in the morning that combines breakfast and lunch",
    sentence: "On Sunday, my sister and I went to a café downtown to enjoy a relaxing {{BLANK}}.",
    cn: "星期天，我和姐姐去市區的咖啡廳享用了一頓悠閒的早午餐。" },
  { word: "lunch", pos: "n.", cn_def: "午餐", en_def: "a meal eaten in the middle of the day",
    sentence: "At noon, all the students line up in the cafeteria to get their {{BLANK}}.",
    cn: "中午時，所有學生都會在餐廳排隊領取午餐。" },
  { word: "dinner", pos: "n.", cn_def: "晚餐", en_def: "the main meal of the day, usually eaten in the evening",
    sentence: "My whole family sits together at the table every night to eat {{BLANK}}.",
    cn: "我們全家人每天晚上都會一起坐在餐桌前吃晚餐。" },
  { word: "supper", pos: "n.", cn_def: "晚餐", en_def: "a light meal eaten in the evening",
    sentence: "After the late movie, we stopped by a small shop for a quick {{BLANK}}.",
    cn: "看完晚場電影後，我們到一家小店吃了簡單的晚餐。" },
  { word: "meal", pos: "n.", cn_def: "一餐", en_def: "the food eaten at one particular time, such as breakfast or dinner",
    sentence: "After the long hike, everyone was hungry and ready for a big {{BLANK}}.",
    cn: "健行了很久之後，大家都餓了，準備好要吃一頓大餐。" },
  { word: "buffet", pos: "n.", cn_def: "自助餐", en_def: "a meal where guests serve themselves from many dishes",
    sentence: "For her birthday, my aunt booked a hotel {{BLANK}} so everyone could choose their own food.",
    cn: "我阿姨為了她的生日訂了一間飯店自助餐，這樣大家都可以自己挑選食物。" },
  { word: "menu", pos: "n.", cn_def: "菜單", en_def: "a list of food and drinks you can order in a restaurant",
    sentence: "Before ordering, the waiter handed each of us a colorful {{BLANK}} to look at.",
    cn: "點餐前，服務生給了我們每個人一份色彩鮮豔的菜單。" },
  { word: "delicious", pos: "adj.", cn_def: "美味的", en_def: "having a very pleasant taste",
    sentence: "Everyone agreed that the soup my grandmother made was absolutely {{BLANK}}.",
    cn: "大家都同意我奶奶煮的湯非常美味。" },
  { word: "yummy", pos: "adj.", cn_def: "好吃的", en_def: "tasting very good, often used by children",
    sentence: "The little boy smiled and said the chocolate cake was so {{BLANK}}.",
    cn: "那個小男孩笑著說那塊巧克力蛋糕真的很好吃。" },
  { word: "diet", pos: "n.", cn_def: "飲食", en_def: "the usual food and drink a person eats",
    sentence: "The doctor told my father to follow a healthier {{BLANK}} after his checkup.",
    cn: "醫生在健康檢查後建議我爸爸要採取更健康的飲食。" },
  { word: "food", pos: "n.", cn_def: "食物", en_def: "anything that people or animals eat to stay alive",
    sentence: "After the typhoon, volunteers brought boxes of fresh {{BLANK}} to the families nearby.",
    cn: "颱風過後，志工們帶了好幾箱新鮮的食物給附近的家庭。" },
  { word: "meat", pos: "n.", cn_def: "肉", en_def: "the flesh of an animal eaten as food",
    sentence: "My uncle grills different kinds of {{BLANK}} every time we visit his backyard.",
    cn: "每次我們去拜訪我叔叔的後院，他都會烤各種不同的肉。" },
  { word: "barbecue", pos: "n.", cn_def: "烤肉", en_def: "meat or food cooked over an open fire outdoors",
    sentence: "Every Mid-Autumn Festival, our whole neighborhood gathers outside for a big {{BLANK}}.",
    cn: "每年中秋節，我們整個社區都會聚在外面舉辦一場大型烤肉活動。" },
  { word: "beef", pos: "n.", cn_def: "牛肉", en_def: "meat that comes from a cow",
    sentence: "My father ordered a bowl of {{BLANK}} noodle soup at the small shop near the station.",
    cn: "我爸爸在車站附近的小店點了一碗牛肉麵。" },
  { word: "steak", pos: "n.", cn_def: "牛排", en_def: "a thick flat piece of meat, often grilled or fried",
    sentence: "For his birthday dinner, my brother chose a juicy {{BLANK}} with mashed potatoes on the side.",
    cn: "為了他的生日晚餐，我哥哥選了一塊多汁的牛排配馬鈴薯泥。" },
  { word: "pork", pos: "n.", cn_def: "豬肉", en_def: "meat that comes from a pig",
    sentence: "The night market stall is famous for its crispy fried {{BLANK}} chops with sweet sauce.",
    cn: "那個夜市攤位以酥脆的炸豬排配甜醬聞名。" },
  { word: "ham", pos: "n.", cn_def: "火腿", en_def: "meat from a pig's leg, usually smoked or salted",
    sentence: "My mother always adds a few slices of {{BLANK}} to my sandwich before school.",
    cn: "我媽媽在上學前總會在我的三明治裡夾幾片火腿。" },
  { word: "hot dog", pos: "n.", cn_def: "熱狗", en_def: "a long sausage served inside a long soft bun",
    sentence: "At the baseball game, my father bought us each a {{BLANK}} with mustard on top.",
    cn: "在棒球比賽現場，我爸爸給我們每人買了一個塗上黃芥末的熱狗。" },
  { word: "dumpling", pos: "n.", cn_def: "餃子", en_def: "a small piece of dough filled with meat or vegetables, often boiled or steamed",
    sentence: "Every Chinese New Year, our whole family sits together folding {{BLANK}} for hours.",
    cn: "每年過年，我們全家人都會坐在一起包好幾個小時的餃子。" },
  { word: "seafood", pos: "n.", cn_def: "海鮮", en_def: "fish and other sea animals eaten as food",
    sentence: "The restaurant near the harbor serves the freshest {{BLANK}} in the whole city.",
    cn: "港口附近的那家餐廳供應全市最新鮮的海鮮。" },
  { word: "egg", pos: "n.", cn_def: "蛋", en_def: "an oval food laid by a hen, often eaten for breakfast",
    sentence: "My father cracked an {{BLANK}} into the hot pan and started making breakfast.",
    cn: "我爸爸打了一顆蛋進熱鍋裡，開始準備早餐。" },
  { word: "bread", pos: "n.", cn_def: "麵包", en_def: "a common food made from baked flour dough",
    sentence: "The smell of fresh {{BLANK}} from the bakery filled the whole street every morning.",
    cn: "每天早上，麵包店傳出的新鮮麵包香氣瀰漫了整條街。" },
  { word: "bun", pos: "n.", cn_def: "小圓麵包", en_def: "a small round piece of bread, often sweet or used for sandwiches",
    sentence: "The vendor placed a hot pork {{BLANK}} into a paper bag for the customer.",
    cn: "攤販把一個熱熱的豬肉小圓麵包裝進紙袋給顧客。" },
  { word: "sandwich", pos: "n.", cn_def: "三明治", en_def: "two slices of bread with food placed between them",
    sentence: "My mother packs a simple {{BLANK}} in my lunch box almost every single day.",
    cn: "我媽媽幾乎每天都會在我的便當盒裡放一個簡單的三明治。" },
  { word: "toast", pos: "n.", cn_def: "烤土司", en_def: "a slice of bread that has been heated until brown and crisp",
    sentence: "I always spread a thin layer of butter on my {{BLANK}} before eating it.",
    cn: "我吃烤土司前總會先抹上一層薄薄的奶油。" },
  { word: "burger", pos: "n.", cn_def: "漢堡", en_def: "a round bread roll filled with a meat patty and other toppings",
    sentence: "After the swim meet, our coach treated the whole team to a cheese {{BLANK}}.",
    cn: "游泳比賽結束後，教練請全隊吃了起司漢堡。" },
  { word: "hamburger", pos: "n.", cn_def: "漢堡", en_def: "a sandwich made with a round bun and a beef patty inside",
    sentence: "The new restaurant downtown is famous for serving the biggest {{BLANK}} in town.",
    cn: "市區那家新開的餐廳以供應全鎮最大的漢堡而聞名。" },
  { word: "French fries", pos: "n.", cn_def: "薯條", en_def: "thin strips of potato that are fried until crispy",
    sentence: "My little brother always asks for extra ketchup with his {{BLANK}}.",
    cn: "我弟弟吃薯條時總是會多要一些番茄醬。" },
  { word: "pizza", pos: "n.", cn_def: "披薩", en_def: "a flat round bread topped with cheese, sauce, and other toppings, then baked",
    sentence: "On Friday nights, our family usually orders a large {{BLANK}} and watches a movie.",
    cn: "每個星期五晚上，我們家通常會訂一個大披薩，然後一起看電影。" },
  { word: "spaghetti", pos: "n.", cn_def: "義大利麵", en_def: "long thin strings of pasta, usually served with sauce",
    sentence: "My mother spent the whole afternoon cooking a rich tomato sauce for the {{BLANK}}.",
    cn: "我媽媽花了整個下午煮一份濃郁的番茄醬汁來搭配義大利麵。" },
  { word: "noodle", pos: "n.", cn_def: "麵", en_def: "a long thin strip of food made from flour, often served in soup",
    sentence: "On cold winter nights, my grandmother always makes a hot bowl of {{BLANK}} soup.",
    cn: "在寒冷的冬夜，我奶奶總會煮一碗熱騰騰的湯麵。" },
  { word: "rice", pos: "n.", cn_def: "飯（米）", en_def: "small white grains that are cooked and eaten as a main food",
    sentence: "In many Asian countries, people eat {{BLANK}} with almost every meal of the day.",
    cn: "在許多亞洲國家，人們幾乎每一餐都會吃飯。" },
  { word: "soup", pos: "n.", cn_def: "湯", en_def: "a liquid food often made by cooking meat or vegetables in water",
    sentence: "When I have a cold, my mother always makes me a bowl of warm {{BLANK}}.",
    cn: "每次我感冒時，我媽媽總會煮一碗熱湯給我喝。" },
  { word: "salad", pos: "n.", cn_def: "沙拉", en_def: "a cold dish of mixed vegetables, often eaten with dressing",
    sentence: "Before the main course arrived, the waiter brought us a fresh green {{BLANK}}.",
    cn: "在主餐上桌之前，服務生先端來了一份新鮮的綠色沙拉。" },
  { word: "tofu", pos: "n.", cn_def: "豆腐", en_def: "a soft white food made from soybeans",
    sentence: "My grandmother adds soft cubes of {{BLANK}} to almost every soup she cooks.",
    cn: "我奶奶幾乎每次煮湯都會加入軟嫩的豆腐塊。" },
  { word: "pie", pos: "n.", cn_def: "派", en_def: "a baked dish with a pastry crust and a filling, often fruit",
    sentence: "Every Thanksgiving, my aunt bakes a delicious apple {{BLANK}} for the whole family.",
    cn: "每年感恩節，我阿姨都會烤一個美味的蘋果派給全家人吃。" },
  { word: "cake", pos: "n.", cn_def: "蛋糕", en_def: "a sweet baked food, often eaten on birthdays",
    sentence: "We all sang together as my little sister blew out the candles on her birthday {{BLANK}}.",
    cn: "當我妹妹吹熄生日蛋糕上的蠟燭時，我們大家一起唱歌。" },
  { word: "candy", pos: "n.", cn_def: "糖果", en_def: "a small sweet food made mostly of sugar",
    sentence: "On Halloween night, the children walked from house to house collecting {{BLANK}}.",
    cn: "在萬聖節的夜晚，孩子們挨家挨戶地去收集糖果。" },
  { word: "cereal", pos: "n.", cn_def: "麥片", en_def: "a breakfast food made from grain, often eaten with milk",
    sentence: "Most mornings, I am in a hurry, so I just eat a bowl of {{BLANK}}.",
    cn: "大多數早晨我都很趕時間，所以只吃一碗麥片。" },
  { word: "cheese", pos: "n.", cn_def: "乳酪", en_def: "a solid food made from milk, often pale yellow or white",
    sentence: "My favorite kind of pizza has extra melted {{BLANK}} on top.",
    cn: "我最喜歡的披薩上面有額外的融化乳酪。" },
  { word: "chocolate", pos: "n.", cn_def: "巧克力", en_def: "a sweet brown food made from cacao beans",
    sentence: "For Valentine's Day, my boyfriend gave me a small box of {{BLANK}}.",
    cn: "情人節那天，我男朋友送了我一小盒巧克力。" },
  { word: "cookie", pos: "n.", cn_def: "餅乾", en_def: "a small flat sweet baked food",
    sentence: "The kitchen smelled wonderful while my mother baked a fresh batch of {{BLANK}}.",
    cn: "我媽媽烤了一批新鮮餅乾時，整個廚房聞起來都很香。" },
  { word: "dessert", pos: "n.", cn_def: "甜點", en_def: "a sweet food eaten at the end of a meal",
    sentence: "After dinner, the waiter asked if we wanted to order any {{BLANK}}.",
    cn: "晚餐後，服務生問我們要不要點甜點。" },
  { word: "doughnut", pos: "n.", cn_def: "甜甜圈", en_def: "a small round sweet food with a hole in the middle",
    sentence: "On the way to school, my father always stops to buy a warm {{BLANK}} for me.",
    cn: "去上學的路上，我爸爸總會停下來幫我買一個溫熱的甜甜圈。" },
  { word: "ice cream", pos: "n.", cn_def: "冰淇淋", en_def: "a frozen sweet food made from cream and sugar",
    sentence: "On the hottest day of summer, we all walked to the shop for some cold {{BLANK}}.",
    cn: "在夏天最熱的那一天，我們都走去那家店買冰淇淋吃。" },
  { word: "popcorn", pos: "n.", cn_def: "爆米花", en_def: "a snack made from corn that pops open when heated",
    sentence: "Before the movie started, we bought a large bag of buttery {{BLANK}}.",
    cn: "電影開始前，我們買了一大袋塗有奶油的爆米花。" },
  { word: "nut", pos: "n.", cn_def: "堅果", en_def: "a hard-shelled seed that can be eaten",
    sentence: "My grandmother always keeps a small bowl of mixed {{BLANK}} on the coffee table.",
    cn: "我奶奶總是在咖啡桌上放一小碗混合堅果。" },
  { word: "snack", pos: "n.", cn_def: "點心", en_def: "a small amount of food eaten between meals",
    sentence: "After school, my little brother always wants a quick {{BLANK}} before doing his homework.",
    cn: "放學後，我弟弟總是想先吃一個小點心再做作業。" }
];

// ---- Part 2 data: 49 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (13/12/12/12), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "Every morning, my mother makes a warm ______ for the whole family. We always eat together before school.",
    options: ["dinner","snack","breakfast","soup"], answer: 2, vocabIndex: 0 },
  { q: "On Sunday, my sister and I went to a café downtown. We enjoyed a relaxing ______ together at noon.",
    options: ["dinner","supper","salad","brunch"], answer: 3, vocabIndex: 1 },
  { q: "At noon, all the students line up in the cafeteria. They wait to get their ______ before class starts again.",
    options: ["lunch","candy","cereal","cake"], answer: 0, vocabIndex: 2 },
  { q: "My whole family sits together at the table every night. We always eat ______ and talk about our day.",
    options: ["breakfast","snack","dessert","dinner"], answer: 3, vocabIndex: 3 },
  { q: "After the late movie, we were hungry. We stopped by a small shop for a quick ______ before going home.",
    options: ["menu","diet","supper","buffet"], answer: 2, vocabIndex: 4 },
  { q: "After the long hike, everyone felt very hungry. We were all ready for a big ______ at the restaurant.",
    options: ["snack","menu","cookie","meal"], answer: 3, vocabIndex: 5 },
  { q: "For her birthday, my aunt booked a hotel ______. Everyone could choose their own food from many tables.",
    options: ["sandwich","dessert","buffet","pie"], answer: 2, vocabIndex: 6 },
  { q: "Before ordering, the waiter handed each of us something colorful. We looked at the ______ to choose our food.",
    options: ["menu","diet","snack","egg"], answer: 0, vocabIndex: 7 },
  { q: "Everyone agreed that the soup my grandmother made tasted wonderful. They all said it was absolutely ______.",
    options: ["yummy","fresh","delicious","warm"], answer: 2, vocabIndex: 8 },
  { q: "The little boy smiled brightly and took another bite. He said the chocolate cake was so ______.",
    options: ["yummy","delicious","healthy","fresh"], answer: 0, vocabIndex: 9 },
  { q: "The doctor checked my father carefully during his visit. Then he told him to follow a healthier ______.",
    options: ["menu","snack","diet","meal"], answer: 2, vocabIndex: 10 },
  { q: "After the typhoon, many families lost their kitchens. Volunteers brought boxes of fresh ______ to help them.",
    options: ["candy","food","dessert","cake"], answer: 1, vocabIndex: 11 },
  { q: "My uncle owns a large backyard with a big grill. He cooks different kinds of ______ every time we visit.",
    options: ["bread","rice","cereal","meat"], answer: 3, vocabIndex: 12 },
  { q: "Every Mid-Autumn Festival, our whole neighborhood gathers outside together. We all enjoy a big ______ near the park.",
    options: ["dessert","barbecue","buffet","snack"], answer: 1, vocabIndex: 13 },
  { q: "My father ordered a bowl of something special at the small shop. The ______ noodle soup smelled wonderful.",
    options: ["rice","bread","beef","egg"], answer: 2, vocabIndex: 14 },
  { q: "For his birthday dinner, my brother wanted something special. He chose a juicy ______ with mashed potatoes on the side.",
    options: ["sandwich","salad","pie","steak"], answer: 3, vocabIndex: 15 },
  { q: "The night market stall always has a long line of customers. It is famous for its crispy fried ______ chops.",
    options: ["pork","beef","tofu","ham"], answer: 0, vocabIndex: 16 },
  { q: "My mother always prepares my lunch box carefully before school. She adds a few slices of ______ to my sandwich.",
    options: ["cheese","ham","candy","cookie"], answer: 1, vocabIndex: 17 },
  { q: "At the baseball game, everyone looked hungry during the break. My father bought us each a ______ with mustard.",
    options: ["hot dog","burger","pizza","toast"], answer: 0, vocabIndex: 18 },
  { q: "Every Chinese New Year, our whole family gathers in the kitchen. We sit together folding ______ for hours.",
    options: ["noodles","dumplings","sandwiches","cookies"], answer: 1, vocabIndex: 19 },
  { q: "The restaurant near the harbor is always crowded on weekends. It serves the freshest ______ in the whole city.",
    options: ["candy","bread","seafood","rice"], answer: 2, vocabIndex: 20 },
  { q: "My father stood by the hot pan early in the morning. He cracked an ______ and started making breakfast.",
    options: ["onion","egg","apple","nut"], answer: 1, vocabIndex: 21 },
  { q: "Every morning, a wonderful smell fills the whole street. Fresh ______ from the bakery makes everyone hungry.",
    options: ["rice","soup","candy","bread"], answer: 3, vocabIndex: 22 },
  { q: "The street vendor worked quickly during the busy evening. He placed a hot pork ______ into a paper bag.",
    options: ["bun","pie","cake","egg"], answer: 0, vocabIndex: 23 },
  { q: "My mother packs my lunch box every single morning before school. She usually makes a simple ______ with cheese inside.",
    options: ["soup","salad","cereal","sandwich"], answer: 3, vocabIndex: 24 },
  { q: "I always spread a thin layer of butter first. Then I eat my warm ______ slowly with a cup of milk.",
    options: ["rice","toast","noodle","cake"], answer: 1, vocabIndex: 25 },
  { q: "After the swim meet, everyone on the team felt hungry and tired. Our coach treated us all to a cheese ______.",
    options: ["sandwich","pizza","burger","salad"], answer: 2, vocabIndex: 26 },
  { q: "The new restaurant downtown opened just last month. It is already famous for serving the biggest ______ in town.",
    options: ["sandwich","noodle","dumpling","hamburger"], answer: 3, vocabIndex: 27 },
  { q: "My little brother loves ketchup more than anything else. He always asks for extra ketchup with his ______.",
    options: ["rice","French fries","soup","cereal"], answer: 1, vocabIndex: 28 },
  { q: "On Friday nights, our whole family relaxes together at home. We usually order a large ______ and watch a movie.",
    options: ["salad","cereal","soup","pizza"], answer: 3, vocabIndex: 29 },
  { q: "My mother spent the whole afternoon cooking something special in the kitchen. She made a rich tomato sauce for the ______.",
    options: ["rice","spaghetti","bread","cereal"], answer: 1, vocabIndex: 30 },
  { q: "On cold winter nights, the kitchen always smells warm and comforting. My grandmother makes a hot bowl of ______ soup.",
    options: ["noodle","candy","cookie","cake"], answer: 0, vocabIndex: 31 },
  { q: "In many Asian countries, families gather around the table daily. People eat ______ with almost every meal of the day.",
    options: ["bread","rice","cheese","candy"], answer: 1, vocabIndex: 32 },
  { q: "When I have a cold, I usually feel too tired to cook. My mother always makes me a bowl of warm ______.",
    options: ["soup","candy","popcorn","cookie"], answer: 0, vocabIndex: 33 },
  { q: "Before the main course arrived at our table, the waiter walked over. He brought us a fresh green ______ first.",
    options: ["dessert","pie","salad","cake"], answer: 2, vocabIndex: 34 },
  { q: "My grandmother cooks many traditional dishes every single week. She adds soft cubes of ______ to almost every soup.",
    options: ["tofu","cheese","ham","beef"], answer: 0, vocabIndex: 35 },
  { q: "Every Thanksgiving, the whole kitchen smells like cinnamon and apples. My aunt bakes a delicious apple ______ for everyone.",
    options: ["cookie","pie","bun","doughnut"], answer: 1, vocabIndex: 36 },
  { q: "We all sang happily around the table that evening. My little sister blew out the candles on her birthday ______.",
    options: ["pie","cookie","doughnut","cake"], answer: 3, vocabIndex: 37 },
  { q: "On Halloween night, the streets were full of excited children. They walked from house to house collecting ______.",
    options: ["candy","snacks","cookies","popcorn"], answer: 0, vocabIndex: 38 },
  { q: "Most mornings, I wake up late and have very little time. I usually just eat a quick bowl of ______.",
    options: ["soup","noodle","salad","cereal"], answer: 3, vocabIndex: 39 },
  { q: "My favorite kind of pizza always tastes a little better at this shop. It has extra melted ______ on top.",
    options: ["cheese","sauce","butter","cream"], answer: 0, vocabIndex: 40 },
  { q: "For Valentine's Day, my boyfriend surprised me with something sweet. He gave me a small box of ______.",
    options: ["candy","cookies","chocolate","cake"], answer: 2, vocabIndex: 41 },
  { q: "The kitchen smelled wonderful all afternoon while my mother worked. She baked a fresh batch of ______ for us.",
    options: ["bread","cookies","pie","toast"], answer: 1, vocabIndex: 42 },
  { q: "After we finished our dinner, the waiter returned to our table. He asked if we wanted to order any ______.",
    options: ["soup","salad","dessert","bread"], answer: 2, vocabIndex: 43 },
  { q: "On the way to school, my father always stops at the same small shop. He buys a warm ______ for me.",
    options: ["sandwich","salad","soup","doughnut"], answer: 3, vocabIndex: 44 },
  { q: "On the hottest day of summer, nobody wanted to stay inside. We all walked to the shop for some cold ______.",
    options: ["ice cream","soup","tea","bread"], answer: 0, vocabIndex: 45 },
  { q: "Before the movie started, the theater smelled buttery and warm. We bought a large bag of ______ to share.",
    options: ["candy","popcorn","cookies","chocolate"], answer: 1, vocabIndex: 46 },
  { q: "My grandmother enjoys snacking quietly in the living room every evening. She keeps a small bowl of mixed ______ nearby.",
    options: ["nuts","candy","cookies","cereal"], answer: 0, vocabIndex: 47 },
  { q: "After school, my little brother always feels hungry right away. He wants a quick ______ before doing his homework.",
    options: ["dinner","buffet","snack","menu"], answer: 2, vocabIndex: 48 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "absolutely": { pos: "adv.", en_def: "completely; totally", cn_def: "完全地；絕對地" },
  "agreed": { pos: "v.", en_def: "said yes to the same idea as someone else", cn_def: "同意" },
  "apple": { pos: "n.", en_def: "a round fruit, usually red or green", cn_def: "蘋果" },
  "arrived": { pos: "v.", en_def: "reached a place", cn_def: "到達" },
  "aunt": { pos: "n.", en_def: "the sister of your father or mother", cn_def: "阿姨；伯母" },
  "backyard": { pos: "n.", en_def: "the area of land behind a house", cn_def: "後院" },
  "bakery": { pos: "n.", en_def: "a shop that makes and sells bread and cakes", cn_def: "麵包店" },
  "bakes": { pos: "v.", en_def: "cooks food in an oven", cn_def: "烘烤" },
  "batch": { pos: "n.", en_def: "a group of things made at the same time", cn_def: "一批" },
  "birthday": { pos: "n.", en_def: "the day of the year a person was born", cn_def: "生日" },
  "blew": { pos: "v.", en_def: "pushed air out from the mouth (past tense of blow)", cn_def: "吹（過去式）" },
  "booked": { pos: "v.", en_def: "arranged to use something in advance", cn_def: "預訂" },
  "bowl": { pos: "n.", en_def: "a round deep dish used for food", cn_def: "碗" },
  "boyfriend": { pos: "n.", en_def: "a man someone is romantically dating", cn_def: "男朋友" },
  "brought": { pos: "v.", en_def: "carried something to a place (past tense of bring)", cn_def: "帶來（過去式）" },
  "butter": { pos: "n.", en_def: "a soft yellow food made from cream", cn_def: "奶油" },
  "buttery": { pos: "adj.", en_def: "having the taste or feel of butter", cn_def: "含奶油的" },
  "cafeteria": { pos: "n.", en_def: "a room where people buy and eat meals, often at school or work", cn_def: "自助餐廳" },
  "candles": { pos: "n.", en_def: "sticks of wax that are burned for light", cn_def: "蠟燭（複數）" },
  "checkup": { pos: "n.", en_def: "a visit to the doctor to check your health", cn_def: "健康檢查" },
  "cream": { pos: "n.", en_def: "the thick rich part of milk, used in cooking", cn_def: "鮮奶油" },
  "healthy": { pos: "adj.", en_def: "good for the body; not causing illness", cn_def: "健康的" },
  "chops": { pos: "n.", en_def: "thick slices of meat, often with a bone", cn_def: "排骨" },
  "chose": { pos: "v.", en_def: "picked one thing instead of another (past tense of choose)", cn_def: "選擇（過去式）" },
  "coach": { pos: "n.", en_def: "a person who trains a sports team", cn_def: "教練" },
  "colorful": { pos: "adj.", en_def: "having many bright colors", cn_def: "色彩鮮豔的" },
  "cracked": { pos: "v.", en_def: "broke something open slightly", cn_def: "敲開" },
  "crispy": { pos: "adj.", en_def: "hard and easy to break, in a pleasant way", cn_def: "脆的" },
  "cubes": { pos: "n.", en_def: "small blocks with six square sides", cn_def: "方塊" },
  "customer": { pos: "n.", en_def: "a person who buys something from a shop", cn_def: "顧客" },
  "doctor": { pos: "n.", en_def: "a person trained to treat sick people", cn_def: "醫生" },
  "downtown": { pos: "n.", en_def: "the central business area of a city", cn_def: "市中心" },
  "extra": { pos: "adj.", en_def: "more than the usual amount", cn_def: "額外的" },
  "families": { pos: "n.", en_def: "groups of people related to each other", cn_def: "家庭（複數）" },
  "famous": { pos: "adj.", en_def: "known by many people", cn_def: "有名的" },
  "festival": { pos: "n.", en_def: "a special day or time of celebration", cn_def: "節日" },
  "filled": { pos: "v.", en_def: "made something full", cn_def: "充滿" },
  "folding": { pos: "v.", en_def: "bending something over itself", cn_def: "摺；包（餃子）" },
  "follow": { pos: "v.", en_def: "to do what is suggested or told", cn_def: "遵循" },
  "fresh": { pos: "adj.", en_def: "newly made or grown, not old", cn_def: "新鮮的" },
  "freshest": { pos: "adj.", en_def: "the most fresh", cn_def: "最新鮮的" },
  "fried": { pos: "adj.", en_def: "cooked in hot oil", cn_def: "油炸的" },
  "gathers": { pos: "v.", en_def: "comes together in a group", cn_def: "聚集" },
  "grills": { pos: "v.", en_def: "cooks food over direct heat", cn_def: "燒烤" },
  "halloween": { pos: "n.", en_def: "a holiday on October 31st with costumes and candy", cn_def: "萬聖節" },
  "handed": { pos: "v.", en_def: "gave something to someone using the hand", cn_def: "遞給" },
  "harbor": { pos: "n.", en_def: "a sheltered area of water where boats can dock", cn_def: "港口" },
  "healthier": { pos: "adj.", en_def: "more healthy", cn_def: "更健康的" },
  "hike": { pos: "n.", en_def: "a long walk, usually in nature", cn_def: "健行" },
  "homework": { pos: "n.", en_def: "school work done at home", cn_def: "作業" },
  "hotel": { pos: "n.", en_def: "a building where travelers pay to stay overnight", cn_def: "飯店" },
  "hottest": { pos: "adj.", en_def: "the most hot", cn_def: "最熱的" },
  "hungry": { pos: "adj.", en_def: "feeling like you need to eat", cn_def: "飢餓的" },
  "hurry": { pos: "n.", en_def: "the need to move or act quickly", cn_def: "匆忙" },
  "juicy": { pos: "adj.", en_def: "full of liquid; not dry", cn_def: "多汁的" },
  "ketchup": { pos: "n.", en_def: "a thick red sauce made from tomatoes", cn_def: "番茄醬" },
  "kitchen": { pos: "n.", en_def: "the room in a house where food is cooked", cn_def: "廚房" },
  "layer": { pos: "n.", en_def: "a thin level of something spread over a surface", cn_def: "一層" },
  "market": { pos: "n.", en_def: "a place where food and goods are sold", cn_def: "市場" },
  "mashed": { pos: "adj.", en_def: "crushed into a soft mixture", cn_def: "搗碎的" },
  "meet": { pos: "n.", en_def: "a sports competition, such as for swimming", cn_def: "競賽" },
  "melted": { pos: "adj.", en_def: "changed from solid to liquid by heat", cn_def: "融化的" },
  "mustard": { pos: "n.", en_def: "a yellow sauce with a sharp taste, often used on hot dogs", cn_def: "黃芥末" },
  "neighborhood": { pos: "n.", en_def: "the area around where you live", cn_def: "社區；鄰里" },
  "noon": { pos: "n.", en_def: "twelve o'clock in the middle of the day", cn_def: "正午" },
  "onion": { pos: "n.", en_def: "a round vegetable with a strong smell and taste", cn_def: "洋蔥" },
  "packs": { pos: "v.", en_def: "puts things together to carry, such as in a bag", cn_def: "打包" },
  "pan": { pos: "n.", en_def: "a flat metal container used for cooking", cn_def: "平底鍋" },
  "potatoes": { pos: "n.", en_def: "round vegetables that grow underground", cn_def: "馬鈴薯（複數）" },
  "ready": { pos: "adj.", en_def: "prepared for something", cn_def: "準備好的" },
  "relaxing": { pos: "adj.", en_def: "calm and free from stress", cn_def: "輕鬆的" },
  "restaurant": { pos: "n.", en_def: "a place where people pay to eat meals", cn_def: "餐廳" },
  "rich": { pos: "adj.", en_def: "having a strong, full flavor", cn_def: "濃郁的" },
  "sauce": { pos: "n.", en_def: "a thick liquid served with food to add flavor", cn_def: "醬汁" },
  "serves": { pos: "v.", en_def: "gives food or drink to someone", cn_def: "供應" },
  "shop": { pos: "n.", en_def: "a small store that sells things", cn_def: "商店" },
  "simple": { pos: "adj.", en_def: "easy and plain; not complicated", cn_def: "簡單的" },
  "slices": { pos: "n.", en_def: "thin flat pieces cut from something larger", cn_def: "片" },
  "smelled": { pos: "v.", en_def: "noticed something with the nose (past tense of smell)", cn_def: "聞到（過去式）" },
  "spread": { pos: "v.", en_def: "covered a surface evenly with something", cn_def: "塗抹" },
  "stall": { pos: "n.", en_def: "a small open shop or table, often outdoors", cn_def: "攤位" },
  "station": { pos: "n.", en_def: "a place where trains or buses stop", cn_def: "車站" },
  "stops": { pos: "v.", en_def: "pauses an action or movement", cn_def: "停下" },
  "table": { pos: "n.", en_def: "a piece of furniture with a flat top, used for eating or working", cn_def: "桌子" },
  "tea": { pos: "n.", en_def: "a hot or cold drink made from tea leaves", cn_def: "茶" },
  "team": { pos: "n.", en_def: "a group of people playing or working together", cn_def: "隊伍" },
  "thanksgiving": { pos: "n.", en_def: "a holiday in November celebrated with a big family meal", cn_def: "感恩節" },
  "tomato": { pos: "n.", en_def: "a soft red fruit eaten as a vegetable", cn_def: "番茄" },
  "treated": { pos: "v.", en_def: "paid for something nice for someone else", cn_def: "招待" },
  "typhoon": { pos: "n.", en_def: "a very strong tropical storm", cn_def: "颱風" },
  "uncle": { pos: "n.", en_def: "the brother of your father or mother", cn_def: "叔叔；伯父" },
  "vendor": { pos: "n.", en_def: "a person who sells things, often outdoors", cn_def: "攤販" },
  "volunteers": { pos: "n.", en_def: "people who help without being paid", cn_def: "志工" },
  "waiter": { pos: "n.", en_def: "a person who serves food in a restaurant", cn_def: "服務生" },
  "warm": { pos: "adj.", en_def: "having a comfortable level of heat", cn_def: "溫暖的" },
  "wonderful": { pos: "adj.", en_def: "extremely good or pleasant", cn_def: "極好的" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});

// ---- Plural aliases so MCQ option lookups (e.g. "cookies", "dumplings") resolve correctly ----
const PLURAL_ALIASES = {
  "cookies": "cookie", "dumplings": "dumpling", "noodles": "noodle", "nuts": "nut",
  "sandwiches": "sandwich", "snacks": "snack", "candies": "candy", "buns": "bun",
  "eggs": "egg", "pies": "pie", "cakes": "cake", "burgers": "burger",
  "hamburgers": "hamburger", "pizzas": "pizza", "menus": "menu", "meals": "meal",
  "soups": "soup", "salads": "salad"
};
Object.keys(PLURAL_ALIASES).forEach(plural => {
  const singular = PLURAL_ALIASES[plural];
  if (!LOOKUP[plural] && LOOKUP[singular]) {
    LOOKUP[plural] = LOOKUP[singular];
  }
});
