// ============================================================
// Group 42 Quiz Data: Home / Household / Objects, Part 4
// Full word set (36 words) — reading materials, stationery,
// and miscellaneous household objects from the "home /
// household / objects" theme. Continues from Group 41 (Home &
// Household, Part 3). This is the fourth of 5 groups (39-43)
// covering this theme at ~36 words per group.
// Continues the simpler/shorter MCQ style introduced in
// Group 37 (~16-26 words, 2 sentences, one blank).
// Note: the spreadsheet's dictionary definition for "ruler" is
// the political sense (a person who rules), not the measuring
// tool; corrected here using the 尺 Chinese gloss as confirmation.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 42 - Home / Household, Part 4 (居家環境 四)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (36 words) ----
const VOCAB = [
  { word: "comic", pos: "n.", cn_def: "漫畫", en_def: "a magazine with stories told through drawings",
    sentence: "He spent his allowance on a new {{BLANK}} every Friday.",
    cn: "他每個星期五都把零用錢花在一本新漫畫上。" },
  { word: "diary", pos: "n.", cn_def: "日記", en_def: "a book where you write about your daily life",
    sentence: "She writes in her {{BLANK}} every night before bed.",
    cn: "她每天晚上睡前都會寫日記。" },
  { word: "dictionary", pos: "n.", cn_def: "字典", en_def: "a book that explains the meanings of words",
    sentence: "He looked up the new word in his {{BLANK}}.",
    cn: "他在字典裡查了這個新單字。" },
  { word: "magazine", pos: "n.", cn_def: "雜誌", en_def: "a publication with articles and pictures, printed regularly",
    sentence: "She bought a fashion {{BLANK}} to read on the train.",
    cn: "她買了一本時尚雜誌在火車上看。" },
  { word: "map", pos: "n.", cn_def: "地圖", en_def: "a drawing that shows the layout of a place",
    sentence: "He unfolded the {{BLANK}} to find the quickest route.",
    cn: "他打開地圖尋找最快的路線。" },
  { word: "newspaper", pos: "n.", cn_def: "報紙", en_def: "printed pages with news, published daily or weekly",
    sentence: "My grandfather reads the {{BLANK}} every morning with his tea.",
    cn: "我爺爺每天早上都會邊喝茶邊看報紙。" },
  { word: "note", pos: "n.", cn_def: "筆記", en_def: "a short piece of writing to remember something",
    sentence: "She left a quick {{BLANK}} for her roommate on the fridge.",
    cn: "她在冰箱上留了一張給室友的簡短筆記。" },
  { word: "novel", pos: "n.", cn_def: "小說", en_def: "a long written story about made-up characters",
    sentence: "He finished reading the entire {{BLANK}} in just two days.",
    cn: "他只花了兩天就讀完了整本小說。" },
  { word: "page", pos: "n.", cn_def: "頁", en_def: "one side of a sheet of paper in a book",
    sentence: "She marked her place with a bookmark on {{BLANK}} fifty.",
    cn: "她用書籤標記了第五十頁的位置。" },
  { word: "paper", pos: "n.", cn_def: "紙張", en_def: "thin material used for writing or printing",
    sentence: "He folded a piece of {{BLANK}} into a paper airplane.",
    cn: "他把一張紙折成紙飛機。" },
  { word: "postcard", pos: "n.", cn_def: "明信片", en_def: "a card sent through the mail without an envelope",
    sentence: "She sent a {{BLANK}} to her friend from her vacation.",
    cn: "她從度假地寄了一張明信片給朋友。" },
  { word: "sheet", pos: "n.", cn_def: "一張(紙)", en_def: "a single flat piece of paper",
    sentence: "He grabbed a clean {{BLANK}} of paper to start his essay.",
    cn: "他拿了一張乾淨的紙開始寫文章。" },
  { word: "stationery", pos: "n.", cn_def: "文具", en_def: "writing materials such as paper, pens, and envelopes",
    sentence: "She organized her {{BLANK}} neatly inside her desk drawer.",
    cn: "她把文具整齊地收進書桌的抽屜裡。" },
  { word: "pen", pos: "n.", cn_def: "筆", en_def: "a tool used for writing with ink",
    sentence: "He borrowed a blue {{BLANK}} to sign the form.",
    cn: "他借了一支藍色的筆來簽表格。" },
  { word: "pencil", pos: "n.", cn_def: "鉛筆", en_def: "a tool used for writing or drawing with graphite",
    sentence: "She sharpened her {{BLANK}} before starting the math test.",
    cn: "她在開始數學考試前削尖了鉛筆。" },
  { word: "eraser", pos: "n.", cn_def: "橡皮擦", en_def: "a tool used to remove pencil marks",
    sentence: "He used an {{BLANK}} to fix his mistake on the worksheet.",
    cn: "他用橡皮擦修正了練習卷上的錯誤。" },
  { word: "ruler", pos: "n.", cn_def: "尺", en_def: "a flat tool used for measuring or drawing straight lines",
    sentence: "She used a {{BLANK}} to draw a straight line in her notebook.",
    cn: "她用尺在筆記本上畫了一條直線。" },
  { word: "crayon", pos: "n.", cn_def: "蠟筆", en_def: "a colored wax stick used for drawing",
    sentence: "The little boy colored the picture with a red {{BLANK}}.",
    cn: "小男孩用紅色蠟筆畫這幅圖。" },
  { word: "marker", pos: "n.", cn_def: "麥克筆", en_def: "a pen with a thick tip used for writing or coloring",
    sentence: "She wrote her name in big letters with a black {{BLANK}}.",
    cn: "她用黑色麥克筆把自己的名字寫得很大。" },
  { word: "envelope", pos: "n.", cn_def: "信封", en_def: "a paper cover used to hold a letter",
    sentence: "He sealed the letter inside a plain white {{BLANK}}.",
    cn: "他把信封進一個普通的白色信封裡。" },
  { word: "glue", pos: "n.", cn_def: "膠水", en_def: "a sticky substance used to join things together",
    sentence: "She used {{BLANK}} to attach the photos to her poster.",
    cn: "她用膠水把照片貼在海報上。" },
  { word: "ink", pos: "n.", cn_def: "墨水", en_def: "a colored liquid used for writing or printing",
    sentence: "The pen ran out of {{BLANK}} halfway through the letter.",
    cn: "這支筆寫信寫到一半就沒墨水了。" },
  { word: "paste", pos: "n.", cn_def: "漿糊", en_def: "a soft, sticky substance used for sticking paper",
    sentence: "He used a bit of {{BLANK}} to stick the cutout onto the card.",
    cn: "他用了一點漿糊把剪下來的圖貼在卡片上。" },
  { word: "notebook", pos: "n.", cn_def: "筆記本", en_def: "a small book with blank or lined pages for writing",
    sentence: "She carries a small {{BLANK}} to jot down her ideas.",
    cn: "她隨身帶著一本小筆記本來記下她的想法。" },
  { word: "pin", pos: "n.", cn_def: "大頭針", en_def: "a small, thin, pointed piece of metal",
    sentence: "She used a {{BLANK}} to hold the papers together.",
    cn: "她用一根大頭針把文件固定在一起。" },
  { word: "stamp", pos: "n.", cn_def: "郵票", en_def: "a small piece of paper stuck on mail to pay for postage",
    sentence: "He licked the {{BLANK}} and stuck it on the envelope.",
    cn: "他舔了郵票後貼在信封上。" },
  { word: "thing", pos: "n.", cn_def: "東西", en_def: "an object whose exact name is not given",
    sentence: "She forgot to bring an important {{BLANK}} to school today.",
    cn: "她今天忘了帶一個重要的東西去學校。" },
  { word: "box", pos: "n.", cn_def: "盒子", en_def: "a container with stiff sides, usually square or rectangular",
    sentence: "He stored his old toys in a cardboard {{BLANK}}.",
    cn: "他把舊玩具收在一個紙箱裡。" },
  { word: "cage", pos: "n.", cn_def: "籠子", en_def: "a structure made of bars used to keep animals inside",
    sentence: "The pet shop kept the rabbits in a clean {{BLANK}}.",
    cn: "寵物店把兔子養在一個乾淨的籠子裡。" },
  { word: "cellphone", pos: "n.", cn_def: "手機", en_def: "a small wireless phone you can carry with you",
    sentence: "She accidentally left her {{BLANK}} at home this morning.",
    cn: "她今天早上不小心把手機忘在家裡了。" },
  { word: "chess", pos: "n.", cn_def: "西洋棋", en_def: "a board game played with pieces on a checkered board",
    sentence: "My grandfather taught me how to play {{BLANK}} last summer.",
    cn: "我爺爺去年夏天教我怎麼下西洋棋。" },
  { word: "diamond", pos: "n.", cn_def: "鑽石", en_def: "a hard, clear, valuable gemstone",
    sentence: "Her ring sparkled with a small {{BLANK}} in the sunlight.",
    cn: "她的戒指上鑲著一顆小鑽石，在陽光下閃閃發光。" },
  { word: "doll", pos: "n.", cn_def: "洋娃娃", en_def: "a toy made to look like a small person",
    sentence: "The little girl carried her favorite {{BLANK}} everywhere she went.",
    cn: "小女孩走到哪裡都帶著她最喜歡的洋娃娃。" },
  { word: "flag", pos: "n.", cn_def: "旗子", en_def: "a piece of cloth with a design, used as a symbol",
    sentence: "The students raised the school {{BLANK}} every Monday morning.",
    cn: "學生們每週一早上都會升起學校的旗子。" },
  { word: "flashlight", pos: "n.", cn_def: "手電筒", en_def: "a small light powered by batteries that you can carry",
    sentence: "He used a {{BLANK}} to find his way during the blackout.",
    cn: "停電時他用手電筒找路。" },
  { word: "gun", pos: "n.", cn_def: "槍", en_def: "a weapon that shoots bullets",
    sentence: "The museum displayed an old {{BLANK}} from a historical battle.",
    cn: "博物館展示了一把來自歷史戰役的舊槍。" }
];

// ---- Part 2 data: 36 MCQs ----
// Continuing the simpler/shorter MCQ style from Group 37:
// ~16-26 words, exactly 2 sentences, one blank, 4 options.
// Answer letters balanced across A/B/C/D, no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "He loves a certain superhero series and never misses an issue. He spent his allowance on a new ______ every Friday.",
    options: ["comic", "novel", "magazine", "newspaper"], answer: 0, vocabIndex: 0 },
  { q: "She likes recording her thoughts and feelings privately each day. She writes in her ______ every night before bed.",
    options: ["notebook", "diary", "novel", "note"], answer: 1, vocabIndex: 1 },
  { q: "He came across a word he had never seen before in his reading. He looked up the new word in his ______.",
    options: ["diary", "novel", "dictionary", "newspaper"], answer: 2, vocabIndex: 2 },
  { q: "She wanted something interesting to read during her commute. She bought a fashion ______ to read on the train.",
    options: ["newspaper", "novel", "dictionary", "magazine"], answer: 3, vocabIndex: 3 },
  { q: "He wasn't sure which roads to take to reach his destination. He unfolded the ______ to find the quickest route.",
    options: ["map", "page", "sheet", "paper"], answer: 0, vocabIndex: 4 },
  { q: "Reading about current events is part of his morning habit. My grandfather reads the ______ every morning with his tea.",
    options: ["magazine", "newspaper", "novel", "diary"], answer: 1, vocabIndex: 5 },
  { q: "She wanted to remind her roommate about something important. She left a quick ______ for her roommate on the fridge.",
    options: ["page", "stamp", "note", "stationery"], answer: 2, vocabIndex: 6 },
  { q: "He couldn't put the exciting story down once he started. He finished reading the entire ______ in just two days.",
    options: ["magazine", "newspaper", "comic", "novel"], answer: 3, vocabIndex: 7 },
  { q: "She wanted to remember exactly where she stopped reading. She marked her place with a bookmark on ______ fifty.",
    options: ["page", "sheet", "stamp", "note"], answer: 0, vocabIndex: 8 },
  { q: "He wanted to make something fun during class break. He folded a piece of ______ into a paper airplane.",
    options: ["stationery", "paper", "ink", "glue"], answer: 1, vocabIndex: 9 },
  { q: "She wanted to share a small piece of her trip with a friend back home. She sent a ______ to her friend from her vacation.",
    options: ["letter", "magazine", "postcard", "diary"], answer: 2, vocabIndex: 10 },
  { q: "He needed something to begin writing his school essay. He grabbed a clean ______ of paper to start it.",
    options: ["stamp", "page", "novel", "sheet"], answer: 3, vocabIndex: 11 },
  { q: "She likes keeping her desk supplies neat and organized. She organized her ______ neatly inside her desk drawer.",
    options: ["stationery", "stamp", "ink", "paste"], answer: 0, vocabIndex: 12 },
  { q: "He needed to sign an important form quickly. He borrowed a blue ______ to sign the form.",
    options: ["pencil", "pen", "marker", "crayon"], answer: 1, vocabIndex: 13 },
  { q: "She wanted to be ready before the math test began. She sharpened her ______ before starting the test.",
    options: ["pen", "marker", "pencil", "crayon"], answer: 2, vocabIndex: 14 },
  { q: "He made a small mistake while filling out his worksheet. He used an ______ to fix his mistake.",
    options: ["ruler", "stamp", "pin", "eraser"], answer: 3, vocabIndex: 15 },
  { q: "She wanted her line to be perfectly straight in her notebook. She used a ______ to draw the straight line.",
    options: ["ruler", "pencil", "marker", "crayon"], answer: 0, vocabIndex: 16 },
  { q: "The little boy was coloring a picture during art class. He colored the picture with a red ______.",
    options: ["pen", "crayon", "pencil", "ink"], answer: 1, vocabIndex: 17 },
  { q: "She wanted her name to stand out boldly on the poster. She wrote her name in big letters with a black ______.",
    options: ["pencil", "crayon", "marker", "pen"], answer: 2, vocabIndex: 18 },
  { q: "He was getting ready to mail an important letter. He sealed it inside a plain white ______.",
    options: ["box", "bag", "notebook", "envelope"], answer: 3, vocabIndex: 19 },
  { q: "She was working on a poster for her school project. She used ______ to attach the photos to it.",
    options: ["glue", "paste", "ink", "tape"], answer: 0, vocabIndex: 20 },
  { q: "He was writing a long letter when something unexpected happened. The pen ran out of ______ halfway through.",
    options: ["paper", "ink", "glue", "paste"], answer: 1, vocabIndex: 21 },
  { q: "He needed to attach a small paper cutout onto his card. He used a bit of ______ to stick it on.",
    options: ["glue", "ink", "paste", "tape"], answer: 2, vocabIndex: 22 },
  { q: "She always likes to write down ideas whenever they come to mind. She carries a small ______ to jot them down.",
    options: ["dictionary", "magazine", "newspaper", "notebook"], answer: 3, vocabIndex: 23 },
  { q: "He needed to keep several loose papers from getting separated. He used a ______ to hold them together.",
    options: ["pin", "stamp", "eraser", "ruler"], answer: 0, vocabIndex: 24 },
  { q: "She was getting her letter ready to send through the mail. He licked the ______ and stuck it on the envelope.",
    options: ["pin", "stamp", "sticker", "paste"], answer: 1, vocabIndex: 25 },
  { q: "She realized something was missing from her backpack on the way to class. She forgot to bring an important ______ to school.",
    options: ["page", "note", "thing", "sheet"], answer: 2, vocabIndex: 26 },
  { q: "He wanted to keep his childhood toys safe and organized. He stored them in a cardboard ______.",
    options: ["bag", "envelope", "drawer", "box"], answer: 3, vocabIndex: 27 },
  { q: "The store needed a safe place to keep the small animals. The pet shop kept the rabbits in a clean ______.",
    options: ["cage", "box", "bag", "basket"], answer: 0, vocabIndex: 28 },
  { q: "She realized her device was missing as she left the house this morning. She accidentally left her ______ at home.",
    options: ["radio", "cellphone", "diary", "novel"], answer: 1, vocabIndex: 29 },
  { q: "He enjoys a quiet game that requires careful thinking and strategy. My grandfather taught me how to play ______ last summer.",
    options: ["cards", "checkers", "chess", "puzzles"], answer: 2, vocabIndex: 30 },
  { q: "Her ring caught everyone's attention at the wedding that day. It sparkled with a small ______ in the sunlight.",
    options: ["pearl", "ruby", "stone", "diamond"], answer: 3, vocabIndex: 31 },
  { q: "The little girl never went anywhere without her favorite toy. She carried her favorite ______ everywhere she went.",
    options: ["doll", "kite", "ball", "book"], answer: 0, vocabIndex: 32 },
  { q: "It's a school tradition that happens at the start of every week. The students raised the school ______ every Monday morning.",
    options: ["sign", "flag", "banner", "poster"], answer: 1, vocabIndex: 33 },
  { q: "The power suddenly went out during the storm last night. He used a ______ to find his way in the dark.",
    options: ["candle", "lamp", "flashlight", "lantern"], answer: 2, vocabIndex: 34 },
  { q: "The exhibit showed weapons used many years ago in a famous conflict. The museum displayed an old ______ from a historical battle.",
    options: ["sword", "shield", "knife", "gun"], answer: 3, vocabIndex: 35 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "bag": { pos: "n.", en_def: "a container made of paper, plastic, or cloth", cn_def: "袋子" },
  "ball": { pos: "n.", en_def: "a round object used in games and sports", cn_def: "球" },
  "banner": { pos: "n.", en_def: "a long piece of cloth with words or a design, used as a sign", cn_def: "橫幅" },
  "basket": { pos: "n.", en_def: "a container made of woven material, often with handles", cn_def: "籃子" },
  "battle": { pos: "n.", en_def: "a fight between armed forces", cn_def: "戰役" },
  "blackout": { pos: "n.", en_def: "a period when the electricity stops working", cn_def: "停電" },
  "book": { pos: "n.", en_def: "a set of printed pages bound together", cn_def: "書本" },
  "candle": { pos: "n.", en_def: "a stick of wax with a wick, burned to give light", cn_def: "蠟燭" },
  "cards": { pos: "n.", en_def: "small pieces of stiff paper used for games", cn_def: "紙牌（複數）" },
  "checkers": { pos: "n.", en_def: "a board game played with round pieces", cn_def: "西洋跳棋" },
  "childhood": { pos: "n.", en_def: "the time when a person is a child", cn_def: "童年" },
  "commute": { pos: "n.", en_def: "the journey between home and work", cn_def: "通勤" },
  "conflict": { pos: "n.", en_def: "a serious disagreement, often involving fighting", cn_def: "衝突" },
  "destination": { pos: "n.", en_def: "the place someone is traveling to", cn_def: "目的地" },
  "drawer": { pos: "n.", en_def: "a sliding storage box built into furniture", cn_def: "抽屜" },
  "exhibit": { pos: "n.", en_def: "an object or display shown to the public", cn_def: "展覽品" },
  "historical": { pos: "adj.", en_def: "relating to history or the past", cn_def: "歷史性的" },
  "issue": { pos: "n.", en_def: "a single edition of a regularly published magazine or comic", cn_def: "（雜誌或漫畫的）期" },
  "kite": { pos: "n.", en_def: "a light toy flown in the wind on a string", cn_def: "風箏" },
  "knife": { pos: "n.", en_def: "a tool with a sharp blade used for cutting", cn_def: "刀子" },
  "lamp": { pos: "n.", en_def: "a light that sits on a desk or table", cn_def: "檯燈" },
  "lantern": { pos: "n.", en_def: "a light that can be carried or hung up", cn_def: "燈籠" },
  "letter": { pos: "n.", en_def: "a written message sent to someone", cn_def: "信" },
  "pearl": { pos: "n.", en_def: "a smooth, round, valuable object formed inside an oyster", cn_def: "珍珠" },
  "poster": { pos: "n.", en_def: "a large printed picture or notice displayed in public", cn_def: "海報" },
  "puzzles": { pos: "n.", en_def: "games or toys that test thinking skills", cn_def: "拼圖；謎題（複數）" },
  "radio": { pos: "n.", en_def: "a device used to listen to broadcast sound", cn_def: "收音機" },
  "ruby": { pos: "n.", en_def: "a red precious stone", cn_def: "紅寶石" },
  "shield": { pos: "n.", en_def: "a piece of armor held to block attacks", cn_def: "盾牌" },
  "sign": { pos: "n.", en_def: "a board or notice giving information", cn_def: "標誌；告示牌" },
  "sparkled": { pos: "v.", en_def: "shone with small flashes of light", cn_def: "閃爍（過去式）" },
  "sticker": { pos: "n.", en_def: "a small piece of paper with adhesive backing", cn_def: "貼紙" },
  "stone": { pos: "n.", en_def: "a small piece of rock", cn_def: "石頭" },
  "strategy": { pos: "n.", en_def: "a careful plan to achieve a goal", cn_def: "策略" },
  "sword": { pos: "n.", en_def: "a weapon with a long, sharp blade", cn_def: "劍" },
  "tape": { pos: "n.", en_def: "a sticky strip used to attach or repair things", cn_def: "膠帶" },
  "tradition": { pos: "n.", en_def: "a custom passed down over time", cn_def: "傳統" },
  "weapons": { pos: "n.", en_def: "objects used for fighting or attacking", cn_def: "武器（複數）" },
  "wedding": { pos: "n.", en_def: "a ceremony where two people get married", cn_def: "婚禮" },
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
