// ============================================================
// Group 2 Quiz Data: Weather & Climate
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 2 - Weather & Climate (天氣與氣候)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice ----
const VOCAB = [
  { word: "weather", pos: "n.", cn_def: "天氣", en_def: "the condition of the sky and temperature outside",
    sentence: "The {{BLANK}} has been changing a lot recently, so I always check my phone before leaving for school.",
    cn: "天氣最近變化很大，所以我出門上學前總是會看一下手機。" },
  { word: "climate", pos: "n.", cn_def: "氣候", en_def: "the usual weather pattern of a place over many years",
    sentence: "Taiwan has a warm, humid {{BLANK}}, which is why so many tropical fruits grow well here all year.",
    cn: "台灣擁有溫暖潮濕的氣候，這就是為什麼這裡整年都能種出許多熱帶水果。" },
  { word: "temperature", pos: "n.", cn_def: "溫度", en_def: "how hot or cold something is",
    sentence: "The {{BLANK}} dropped suddenly last night, so I had to find an extra blanket before going to sleep.",
    cn: "昨晚溫度突然下降，所以我睡前必須找一條額外的毯子。" },
  { word: "air", pos: "n.", cn_def: "空氣", en_def: "the mixture of gases we breathe",
    sentence: "The {{BLANK}} felt fresh and clean after the rain, so we decided to take a long walk outside.",
    cn: "雨後的空氣感覺清新乾淨，所以我們決定到外面散一段長長的步。" },
  { word: "typhoon", pos: "n.", cn_def: "颱風", en_def: "a very strong storm with heavy rain and wind",
    sentence: "A strong {{BLANK}} is expected to hit Taiwan this weekend, so schools may be closed on Monday.",
    cn: "一個強烈的颱風預計這個週末會侵襲台灣，所以星期一學校可能會停課。" },
  { word: "lightning", pos: "n.", cn_def: "閃電", en_def: "a sudden bright flash of light in a storm",
    sentence: "A sudden flash of {{BLANK}} lit up the dark sky, and then we heard loud thunder a few seconds later.",
    cn: "一道突然的閃電照亮了黑暗的天空，幾秒鐘後我們就聽到了巨大的雷聲。" },
  { word: "rainbow", pos: "n.", cn_def: "彩虹", en_def: "an arc of colors in the sky after rain",
    sentence: "After the rain finally stopped, a beautiful {{BLANK}} appeared in the sky, and everyone took out their phones to take photos.",
    cn: "雨終於停了之後，天空出現了一道美麗的彩虹，大家都拿出手機拍照。" },
  { word: "snowman", pos: "n.", cn_def: "雪人", en_def: "a figure made of snow shaped like a person",
    sentence: "The children worked together all afternoon to build a tall {{BLANK}} in the front yard before it melted.",
    cn: "孩子們整個下午一起合作，在前院蓋了一個高大的雪人，趁它還沒融化。" },
  { word: "cloud", pos: "n.", cn_def: "雲", en_def: "a white or gray shape floating in the sky",
    sentence: "There is not a single {{BLANK}} in the sky today, so it should be perfect weather for our picnic.",
    cn: "今天天空中沒有一片雲，所以應該是適合我們野餐的完美天氣。" },
  { word: "cloudy", pos: "adj.", cn_def: "多雲的", en_def: "covered with clouds",
    sentence: "The sky looked {{BLANK}} all morning, so we decided to bring an umbrella just in case it rained.",
    cn: "整個早上天空看起來多雲，所以我們決定帶把雨傘以防下雨。" },
  { word: "fog", pos: "n.", cn_def: "霧", en_def: "a thick cloud of tiny water drops near the ground",
    sentence: "Thick {{BLANK}} covered the whole mountain road this morning, so the bus driver had to slow down a lot.",
    cn: "今天早上濃霧覆蓋了整條山路，所以公車司機必須大幅減速。" },
  { word: "foggy", pos: "adj.", cn_def: "有濃霧的", en_def: "full of fog",
    sentence: "The morning was so {{BLANK}} that we could barely see the school gate from across the street.",
    cn: "早上的霧濃到我們幾乎看不到對街的校門，天氣非常多霧。" },
  { word: "rain", pos: "n.", cn_def: "雨水", en_def: "water that falls from clouds",
    sentence: "The {{BLANK}} outside sounded so heavy that we decided to stay inside and watch a movie instead.",
    cn: "外面的雨聲聽起來非常大，所以我們決定待在室內看電影。" },
  { word: "rain", pos: "v.", cn_def: "下雨", en_def: "when water falls from the clouds",
    sentence: "It started to {{BLANK}} heavily right after we left the house, so we had to run back for an umbrella.",
    cn: "我們離開家後不久就開始下大雨，所以我們必須跑回去拿一把雨傘。" },
  { word: "rainy", pos: "adj.", cn_def: "下雨的", en_def: "having a lot of rain",
    sentence: "On {{BLANK}} days, my little brother likes to stay home and build things with his colorful blocks.",
    cn: "在下雨的日子裡，我弟弟喜歡待在家裡用他色彩繽紛的積木蓋東西。" },
  { word: "snow", pos: "n.", cn_def: "雪", en_def: "soft white frozen water that falls in winter",
    sentence: "Soft white {{BLANK}} covered the entire mountain top, making it look like a beautiful winter painting.",
    cn: "柔軟的白雪覆蓋了整座山頂，讓它看起來像一幅美麗的冬天畫作。" },
  { word: "snowy", pos: "adj.", cn_def: "下雪的", en_def: "having a lot of snow",
    sentence: "We packed thick coats and warm boots because the mountain town is famous for its {{BLANK}} winters.",
    cn: "我們打包了厚重的大衣和保暖的靴子，因為那個山城以多雪的冬天著名。" },
  { word: "storm", pos: "v.", cn_def: "突襲", en_def: "to attack suddenly and with force",
    sentence: "Dark clouds began to {{BLANK}} the small fishing boats just as the fishermen were heading back to shore.",
    cn: "就在漁夫們正要返回岸邊時，烏雲開始突襲那些小漁船。" },
  { word: "storm", pos: "n.", cn_def: "暴風雨", en_def: "very bad weather with strong wind and rain",
    sentence: "A powerful {{BLANK}} knocked down several trees along our street, so the road was blocked for two days.",
    cn: "一場強烈的暴風雨擊倒了我們街上的好幾棵樹，所以道路被封閉了兩天。" },
  { word: "stormy", pos: "adj.", cn_def: "暴風雨的", en_def: "having storms, with strong wind and rain",
    sentence: "The captain decided not to sail because the ocean looked far too {{BLANK}} for a small boat.",
    cn: "船長決定不出海，因為海面看起來對一艘小船來說太暴風雨了。" },
  { word: "wind", pos: "n.", cn_def: "風", en_def: "air that moves quickly outside",
    sentence: "A strong {{BLANK}} blew all of the leaves off the trees in just one single afternoon.",
    cn: "一陣強風在短短一個下午就把樹上所有的葉子都吹落了。" },
  { word: "windy", pos: "adj.", cn_def: "有風的", en_def: "having a lot of wind",
    sentence: "It was so {{BLANK}} on the beach today that we couldn't keep our towels flat on the sand.",
    cn: "今天海灘上風很大，我們的毛巾根本沒辦法平鋪在沙子上。" },
  { word: "cold", pos: "adj.", cn_def: "冷的", en_def: "having a low temperature",
    sentence: "The water in the mountain stream felt incredibly {{BLANK}}, so none of us wanted to put our feet in.",
    cn: "山間溪流裡的水感覺非常冰冷，所以我們都不想把腳放進去。" },
  { word: "cool", pos: "adj.", cn_def: "涼爽的", en_def: "a little cold, in a pleasant way",
    sentence: "After the sun went down, the night air became pleasantly {{BLANK}}, so we finally turned off the fan.",
    cn: "太陽下山後，夜晚的空氣變得舒適涼爽，所以我們終於把電風扇關掉了。" },
  { word: "freezing", pos: "adj.", cn_def: "酷寒的", en_def: "extremely cold",
    sentence: "My hands felt completely {{BLANK}} after building a snowman outside without wearing any gloves at all.",
    cn: "在外面不戴手套蓋雪人之後，我的手感覺完全凍僵了。" },
  { word: "hot", pos: "adj.", cn_def: "熱的", en_def: "having a high temperature",
    sentence: "The metal playground slide gets so {{BLANK}} in summer that nobody can sit on it without getting burned.",
    cn: "夏天時遊樂場的金屬滑梯會變得非常熱，沒有人可以坐上去而不被燙到。" },
  { word: "humid", pos: "adj.", cn_def: "潮濕的", en_def: "having a lot of water in the air",
    sentence: "Summer afternoons in Taiwan can feel extremely {{BLANK}}, so most people carry a small towel to wipe off sweat.",
    cn: "台灣夏天的午後感覺非常潮濕，所以大部分人都會隨身帶一條小毛巾擦汗。" },
  { word: "sunny", pos: "adj.", cn_def: "晴朗的", en_def: "bright with sunshine",
    sentence: "It was such a {{BLANK}} day that everyone at the beach needed sunglasses and plenty of sunscreen.",
    cn: "那天天氣非常晴朗，海灘上每個人都需要太陽眼鏡和大量的防曬乳。" },
  { word: "warm", pos: "adj.", cn_def: "溫暖的", en_def: "having a comfortably high temperature",
    sentence: "The soup tasted wonderfully {{BLANK}} after we came inside from playing in the cold winter wind.",
    cn: "我們從外面寒冷的冬風中進來後，這碗湯喝起來感覺非常溫暖。" },
];

// ---- Part 2 data: 30 MCQs ----
// vocabIndex points to the exact VOCAB array entry being tested,
// which matters for words like "rain"/"storm" that appear twice
// with different parts of speech and different sentences.
const MCQS = [
  { q: "The sky looks dark and the wind feels strong this morning, so I should probably check the forecast. The news always tells us what the ______ will be like today.",
    options: ["climate", "temperature", "air", "weather"], answer: 3, vocabIndex: 0 },
  { q: "Unlike daily weather, which can change quickly from morning to night, this word describes the usual pattern of conditions in a place over many years. Scientists study Earth's ______ to understand long-term changes.",
    options: ["weather", "climate", "fog", "wind"], answer: 1, vocabIndex: 1 },
  { q: "The nurse used a small device on my forehead to check how hot or cold my body was. She told my mother that my ______ was a little too high.",
    options: ["climate", "air", "temperature", "cloud"], answer: 2, vocabIndex: 2 },
  { q: "After the old factory finally closed down for good, people living in the small town noticed that the ______ around their houses smelled fresher and felt much easier to breathe.",
    options: ["air", "lightning", "rainbow", "fog"], answer: 0, vocabIndex: 3 },
  { q: "The weather bureau has been tracking this huge, named tropical storm system for days, and it is expected to bring extremely strong winds to the coast this weekend. A powerful ______ is approaching the island.",
    options: ["rainbow", "typhoon", "snowman", "storm"], answer: 1, vocabIndex: 4 },
  { q: "During the thunderstorm, a bright flash suddenly lit up the whole bedroom for just one second before the room turned dark again. That bright flash is called ______.",
    options: ["lightning", "rainbow", "snow", "fog"], answer: 0, vocabIndex: 5 },
  { q: "Sunlight passed through the falling raindrops and created seven bright colors stretching across the sky just after the storm ended. Everyone ran outside to take a picture of the colorful ______.",
    options: ["lightning", "cloud", "rainbow", "fog"], answer: 2, vocabIndex: 6 },
  { q: "The children rolled three round balls of snow and stacked them on top of each other, then added a carrot for a nose. By lunchtime, their ______ stood proudly in the front yard.",
    options: ["rainbow", "cloud", "fog", "snowman"], answer: 3, vocabIndex: 7 },
  { q: "I looked up at the bright blue sky and noticed there wasn't a single white shape floating above us anywhere. Not one ______ appeared in the sky all afternoon.",
    options: ["typhoon", "cloud", "fog", "wind"], answer: 1, vocabIndex: 8 },
  { q: "Drivers on the mountain road this morning could barely see ten meters ahead because a thick gray mist covered everything around them. Thick ______ made the early commute extremely dangerous.",
    options: ["rainbow", "lightning", "fog", "cloud"], answer: 2, vocabIndex: 10 },
  { q: "We could hear heavy drops hitting the roof all night long, and by morning, puddles had formed across the entire schoolyard. The sound of falling ______ kept me awake until midnight.",
    options: ["snow", "rain", "wind", "storm"], answer: 1, vocabIndex: 12 },
  { q: "Soft white flakes drifted slowly down from the gray sky and quickly began covering the rooftops and parked cars below. Within an hour, thick ______ blanketed the entire neighborhood.",
    options: ["rain", "fog", "snow", "wind"], answer: 2, vocabIndex: 15 },
  { q: "Dark clouds gathered quickly, strong winds knocked over garbage cans, and heavy rain poured down for nearly two hours straight. The sudden, violent ______ caught everyone by surprise.",
    options: ["typhoon", "fog", "snowman", "storm"], answer: 3, vocabIndex: 18 },
  { q: "Even though the sky was clear and sunny, a strong invisible force kept pushing the kite higher and higher above the playground. A steady ______ made it the perfect day for flying kites.",
    options: ["rain", "snow", "wind", "fog"], answer: 2, vocabIndex: 20 },
  { q: "There were thick gray shapes covering most of the sky this afternoon, so we couldn't see the sun at all during our walk. It has been a ______ day since this morning.",
    options: ["foggy", "rainy", "sunny", "cloudy"], answer: 3, vocabIndex: 9 },
  { q: "Visibility was so poor along the coastal road that drivers had to turn on their headlights even though it was already daytime. The thick mist made the morning extremely ______.",
    options: ["foggy", "cloudy", "rainy", "windy"], answer: 0, vocabIndex: 11 },
  { q: "My umbrella never leaves my school bag during this part of the year because the sky opens up almost every single afternoon without warning. June in Taiwan is famous for being very ______.",
    options: ["cloudy", "rainy", "snowy", "stormy"], answer: 1, vocabIndex: 14 },
  { q: "The little village high in the mountains gets buried under thick white powder for almost five months every single year. Tourists love visiting during its long, ______ winters.",
    options: ["rainy", "foggy", "windy", "snowy"], answer: 3, vocabIndex: 16 },
  { q: "The captain canceled the boat trip after seeing huge waves crash against the rocks and dark clouds roll in quickly from the sea. The ocean looked far too ______ for any small boats today.",
    options: ["cloudy", "snowy", "stormy", "windy"], answer: 2, vocabIndex: 19 },
  { q: "My hat flew right off my head twice while I was walking along the beach this afternoon, and the waves were unusually rough too. It has been an extremely ______ day at the coast.",
    options: ["cloudy", "rainy", "foggy", "windy"], answer: 3, vocabIndex: 21 },
  { q: "The mountain stream felt like ice against my bare feet, and I had to pull them out again after only a few seconds. The water was simply too ______ to stand in for long.",
    options: ["cold", "cool", "hot", "warm"], answer: 0, vocabIndex: 22 },
  { q: "After the sun finally went down behind the hills, a pleasant breeze made sitting outside on the porch much more comfortable than during the afternoon heat. The evening air felt wonderfully ______.",
    options: ["cold", "freezing", "cool", "warm"], answer: 2, vocabIndex: 23 },
  { q: "My fingers had completely lost all feeling after building a snowman outside for twenty minutes without any gloves on at all. The winter wind made my hands feel absolutely ______.",
    options: ["freezing", "cool", "hot", "humid"], answer: 0, vocabIndex: 24 },
  { q: "The metal slide at the playground had been sitting under the strong summer sun for hours, so nobody dared to sit down on it. The metal surface had become dangerously ______.",
    options: ["cold", "hot", "sunny", "warm"], answer: 1, vocabIndex: 25 },
  { q: "My shirt felt damp and sticky within minutes of walking outside, even though it wasn't raining at all that afternoon. Summer in southern Taiwan can feel incredibly ______.",
    options: ["humid", "cool", "sunny", "warm"], answer: 0, vocabIndex: 26 },
  { q: "Not a single cloud appeared in the sky all day, and everyone at the beach needed sunglasses just to keep their eyes open. It was the brightest, most ______ day of the whole summer.",
    options: ["cold", "sunny", "humid", "windy"], answer: 1, vocabIndex: 27 },
  { q: "After coming inside from the cold winter wind, the bowl of soup felt absolutely perfect in my cold hands. Its comforting heat made me feel ______ again within minutes.",
    options: ["warm", "cold", "freezing", "humid"], answer: 0, vocabIndex: 28 },
  { q: "Dark heavy clouds had been building all afternoon, and right after we stepped outside, the sky finally opened up above us. It began to ______ so hard that we had to run for shelter.",
    options: ["snow", "shine", "storm", "rain"], answer: 3, vocabIndex: 13 },
  { q: "The pirates' ship moved quickly through the fog, and the crew prepared their weapons as they got closer to the unguarded harbor. They planned to ______ the small village before dawn.",
    options: ["rain", "snow", "storm", "shine"], answer: 2, vocabIndex: 17 },
  { q: "Schools and offices across the island closed early today after the weather bureau issued its most serious warning of the entire summer season. Everyone is preparing for the powerful ______ arriving tonight.",
    options: ["storm", "rainbow", "cloud", "typhoon"], answer: 3, vocabIndex: 4 },
];

// ---- Word lookup definitions (for the lookup popup) ----
// Some words (rain, storm) appear twice with different parts of speech.
// Merge those into one combined entry so lookup shows both senses instead
// of silently losing one to an object-key overwrite.
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});
// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "afternoon": { pos: "n.", en_def: "the part of the day between noon and evening", cn_def: "下午" },
  "afternoons": { pos: "n.", en_def: "more than one afternoon", cn_def: "下午（複數）" },
  "appeared": { pos: "v.", en_def: "came into sight (past tense of appear)", cn_def: "出現（appear的過去式）" },
  "barely": { pos: "adv.", en_def: "almost not; only just", cn_def: "幾乎不" },
  "beach": { pos: "n.", en_def: "an area of sand next to the sea", cn_def: "海灘" },
  "beautiful": { pos: "adj.", en_def: "very pretty or pleasing to look at", cn_def: "美麗的" },
  "became": { pos: "v.", en_def: "started to be something (past tense of become)", cn_def: "變成（become的過去式）" },
  "began": { pos: "v.", en_def: "started (past tense of begin)", cn_def: "開始（begin的過去式）" },
  "blanket": { pos: "n.", en_def: "a thick cloth used to stay warm in bed", cn_def: "毯子" },
  "blew": { pos: "v.", en_def: "moved air strongly (past tense of blow)", cn_def: "吹（blow的過去式）" },
  "blocked": { pos: "v.", en_def: "stopped something from passing through", cn_def: "阻塞；封閉" },
  "blocks": { pos: "n.", en_def: "solid pieces, often used for building toys", cn_def: "積木；方塊" },
  "boat": { pos: "n.", en_def: "a small vehicle for traveling on water", cn_def: "船" },
  "boats": { pos: "n.", en_def: "more than one boat", cn_def: "船（複數）" },
  "boots": { pos: "n.", en_def: "shoes that cover the foot and ankle", cn_def: "靴子" },
  "bring": { pos: "v.", en_def: "to carry something to a place", cn_def: "帶來" },
  "brother": { pos: "n.", en_def: "a boy or man with the same parents as you", cn_def: "兄弟" },
  "build": { pos: "v.", en_def: "to make something by putting parts together", cn_def: "建造" },
  "building": { pos: "v.", en_def: "making something (the -ing form of build)", cn_def: "建造（進行式）" },
  "burned": { pos: "v.", en_def: "was hurt by something very hot", cn_def: "燙傷；燒傷" },
  "bus": { pos: "n.", en_def: "a large vehicle that carries many passengers", cn_def: "公車" },
  "came": { pos: "v.", en_def: "moved toward a place (past tense of come)", cn_def: "來（come的過去式）" },
  "captain": { pos: "n.", en_def: "the person in charge of a ship or boat", cn_def: "船長" },
  "carry": { pos: "v.", en_def: "to hold something while moving it", cn_def: "攜帶" },
  "changing": { pos: "v.", en_def: "becoming different (the -ing form of change)", cn_def: "改變（進行式）" },
  "check": { pos: "v.", en_def: "to look at something to make sure it's right", cn_def: "檢查" },
  "children": { pos: "n.", en_def: "young people; the plural of child", cn_def: "孩子們" },
  "clean": { pos: "adj.", en_def: "not dirty", cn_def: "乾淨的" },
  "closed": { pos: "v.", en_def: "stopped being open", cn_def: "關閉" },
  "clouds": { pos: "n.", en_def: "white or gray shapes floating in the sky", cn_def: "雲（複數）" },
  "coats": { pos: "n.", en_def: "warm outer clothes", cn_def: "大衣（複數）" },
  "cold": { pos: "adj.", en_def: "having a low temperature", cn_def: "冷的" },
  "colorful": { pos: "adj.", en_def: "having many bright colors", cn_def: "色彩豐富的" },
  "completely": { pos: "adv.", en_def: "fully; entirely", cn_def: "完全地" },
  "covered": { pos: "v.", en_def: "put something over the top of another thing", cn_def: "覆蓋" },
  "dark": { pos: "adj.", en_def: "having little or no light", cn_def: "黑暗的" },
  "day": { pos: "n.", en_def: "a period of 24 hours", cn_def: "天；日" },
  "days": { pos: "n.", en_def: "more than one day", cn_def: "天（複數）" },
  "decided": { pos: "v.", en_def: "made a choice (past tense of decide)", cn_def: "決定（decide的過去式）" },
  "driver": { pos: "n.", en_def: "a person who drives a vehicle", cn_def: "駕駛" },
  "dropped": { pos: "v.", en_def: "fell or let something fall", cn_def: "下降；掉落" },
  "entire": { pos: "adj.", en_def: "whole; complete", cn_def: "整個的" },
  "everyone": { pos: "pron.", en_def: "every person", cn_def: "每個人" },
  "expected": { pos: "v.", en_def: "believed something would happen", cn_def: "預期" },
  "extra": { pos: "adj.", en_def: "more than what is usual", cn_def: "額外的" },
  "extremely": { pos: "adv.", en_def: "to a very high degree", cn_def: "極度地" },
  "famous": { pos: "adj.", en_def: "known by many people", cn_def: "著名的" },
  "fan": { pos: "n.", en_def: "a machine that moves air to cool a room", cn_def: "電扇" },
  "far": { pos: "adv.", en_def: "a long distance; very much", cn_def: "遠；非常" },
  "feel": { pos: "v.", en_def: "to experience a feeling or sensation", cn_def: "感覺" },
  "feet": { pos: "n.", en_def: "the plural of foot; the parts of the body we stand on", cn_def: "腳（複數）" },
  "felt": { pos: "v.", en_def: "experienced a feeling (past tense of feel)", cn_def: "感覺（feel的過去式）" },
  "few": { pos: "adj.", en_def: "a small number of", cn_def: "少數的" },
  "finally": { pos: "adv.", en_def: "after a long time; at last", cn_def: "終於" },
  "find": { pos: "v.", en_def: "to discover something you are looking for", cn_def: "找到" },
  "fishermen": { pos: "n.", en_def: "people whose job is to catch fish", cn_def: "漁夫（複數）" },
  "fishing": { pos: "adj.", en_def: "related to catching fish", cn_def: "捕魚的" },
  "flash": { pos: "n.", en_def: "a sudden bright light", cn_def: "閃光" },
  "flat": { pos: "adj.", en_def: "smooth and level, with no bumps", cn_def: "平坦的" },
  "fresh": { pos: "adj.", en_def: "new and clean, not stale", cn_def: "新鮮的" },
  "front": { pos: "n.", en_def: "the part facing forward; the area before something", cn_def: "前面" },
  "fruits": { pos: "n.", en_def: "sweet foods that grow on plants", cn_def: "水果（複數）" },
  "gate": { pos: "n.", en_def: "a door-like structure at an entrance", cn_def: "大門" },
  "gets": { pos: "v.", en_def: "becomes or receives", cn_def: "變得；得到" },
  "getting": { pos: "v.", en_def: "becoming (the -ing form of get)", cn_def: "變得（進行式）" },
  "gloves": { pos: "n.", en_def: "clothing worn on the hands", cn_def: "手套" },
  "going": { pos: "v.", en_def: "moving toward a place (the -ing form of go)", cn_def: "去（進行式）" },
  "grow": { pos: "v.", en_def: "to become bigger over time", cn_def: "生長" },
  "hands": { pos: "n.", en_def: "the parts of the body at the end of the arms", cn_def: "手（複數）" },
  "heading": { pos: "v.", en_def: "moving toward a direction", cn_def: "前往" },
  "heard": { pos: "v.", en_def: "noticed a sound (past tense of hear)", cn_def: "聽到（hear的過去式）" },
  "heavily": { pos: "adv.", en_def: "with great force or amount", cn_def: "大量地；猛烈地" },
  "heavy": { pos: "adj.", en_def: "having a lot of weight or force", cn_def: "重的；猛烈的" },
  "hit": { pos: "v.", en_def: "to strike something with force", cn_def: "侵襲；打" },
  "home": { pos: "n.", en_def: "the place where someone lives", cn_def: "家" },
  "house": { pos: "n.", en_def: "a building where people live", cn_def: "房子" },
  "humid": { pos: "adj.", en_def: "having a lot of water in the air", cn_def: "潮濕的" },
  "incredibly": { pos: "adv.", en_def: "extremely; to an amazing degree", cn_def: "難以置信地；非常" },
  "inside": { pos: "adv.", en_def: "in or into a building", cn_def: "在裡面" },
  "instead": { pos: "adv.", en_def: "in place of something else", cn_def: "取而代之" },
  "keep": { pos: "v.", en_def: "to continue having or doing something", cn_def: "保持" },
  "knocked": { pos: "v.", en_def: "hit something so it fell over", cn_def: "撞倒" },
  "leaves": { pos: "n.", en_def: "the flat green parts of a plant or tree", cn_def: "樹葉" },
  "leaving": { pos: "v.", en_def: "going away from a place", cn_def: "離開（進行式）" },
  "left": { pos: "v.", en_def: "went away from a place (past tense of leave)", cn_def: "離開（leave的過去式）" },
  "likes": { pos: "v.", en_def: "enjoys something", cn_def: "喜歡" },
  "lit": { pos: "v.", en_def: "made something bright with light (past tense of light)", cn_def: "照亮（light的過去式）" },
  "look": { pos: "v.", en_def: "to use your eyes to see something", cn_def: "看" },
  "looked": { pos: "v.", en_def: "appeared a certain way; used your eyes", cn_def: "看起來；看" },
  "lot": { pos: "n.", en_def: "a large amount", cn_def: "很多" },
  "loud": { pos: "adj.", en_def: "making a lot of noise", cn_def: "大聲的" },
  "making": { pos: "v.", en_def: "creating something (the -ing form of make)", cn_def: "製作（進行式）" },
  "melted": { pos: "v.", en_def: "changed from solid to liquid because of heat", cn_def: "融化" },
  "metal": { pos: "n.", en_def: "a hard, shiny material like iron or steel", cn_def: "金屬" },
  "monday": { pos: "n.", en_def: "the day after Sunday", cn_def: "星期一" },
  "morning": { pos: "n.", en_def: "the early part of the day", cn_def: "早上" },
  "mountain": { pos: "n.", en_def: "a very high hill", cn_def: "山" },
  "movie": { pos: "n.", en_def: "a film shown in a theater or at home", cn_def: "電影" },
  "needed": { pos: "v.", en_def: "required something (past tense of need)", cn_def: "需要（need的過去式）" },
  "night": { pos: "n.", en_def: "the dark part of the day", cn_def: "夜晚" },
  "nobody": { pos: "pron.", en_def: "no person; not anyone", cn_def: "沒有人" },
  "ocean": { pos: "n.", en_def: "a very large area of salt water", cn_def: "海洋" },
  "outside": { pos: "adv.", en_def: "not inside; in the open air", cn_def: "在外面" },
  "packed": { pos: "v.", en_def: "put things into a bag or box for a trip", cn_def: "打包" },
  "painting": { pos: "n.", en_def: "a picture made with paint", cn_def: "畫作" },
  "people": { pos: "n.", en_def: "more than one person", cn_def: "人們" },
  "perfect": { pos: "adj.", en_def: "having no faults; ideal", cn_def: "完美的" },
  "phone": { pos: "n.", en_def: "a device used to talk to people far away", cn_def: "電話" },
  "phones": { pos: "n.", en_def: "more than one phone", cn_def: "電話（複數）" },
  "photos": { pos: "n.", en_def: "pictures taken with a camera", cn_def: "照片" },
  "picnic": { pos: "n.", en_def: "a meal eaten outdoors, often in a park", cn_def: "野餐" },
  "playground": { pos: "n.", en_def: "an outdoor area with equipment for children to play on", cn_def: "遊樂場" },
  "playing": { pos: "v.", en_def: "doing an activity for fun", cn_def: "玩耍（進行式）" },
  "pleasantly": { pos: "adv.", en_def: "in an enjoyable way", cn_def: "令人愉快地" },
  "plenty": { pos: "n.", en_def: "a large or more than enough amount", cn_def: "大量；充足" },
  "powerful": { pos: "adj.", en_def: "having great strength or force", cn_def: "強大的；強烈的" },
  "put": { pos: "v.", en_def: "to move something into a place", cn_def: "放置" },
  "rained": { pos: "v.", en_def: "water fell from the sky (past tense of rain)", cn_def: "下雨（rain的過去式）" },
  "recently": { pos: "adv.", en_def: "not long ago", cn_def: "最近" },
  "road": { pos: "n.", en_def: "a path made for vehicles to travel on", cn_def: "道路" },
  "run": { pos: "v.", en_def: "to move quickly using your legs", cn_def: "跑" },
  "sail": { pos: "v.", en_def: "to travel on water in a boat or ship", cn_def: "航行" },
  "sand": { pos: "n.", en_def: "the tiny grains found on beaches", cn_def: "沙子" },
  "school": { pos: "n.", en_def: "a place where students go to learn", cn_def: "學校" },
  "schools": { pos: "n.", en_def: "more than one school", cn_def: "學校（複數）" },
  "seconds": { pos: "n.", en_def: "very short units of time", cn_def: "秒" },
  "see": { pos: "v.", en_def: "to notice something with your eyes", cn_def: "看見" },
  "several": { pos: "adj.", en_def: "more than two but not very many", cn_def: "幾個" },
  "shore": { pos: "n.", en_def: "the land along the edge of water", cn_def: "岸邊" },
  "single": { pos: "adj.", en_def: "only one", cn_def: "單一的" },
  "sit": { pos: "v.", en_def: "to rest your body on a chair or surface", cn_def: "坐" },
  "sky": { pos: "n.", en_def: "the space above the earth where clouds are", cn_def: "天空" },
  "sleep": { pos: "v.", en_def: "to rest with your eyes closed at night", cn_def: "睡覺" },
  "slide": { pos: "n.", en_def: "a playground structure children slide down", cn_def: "滑梯" },
  "slow": { pos: "v.", en_def: "to make something move at a lower speed", cn_def: "減速" },
  "small": { pos: "adj.", en_def: "not large in size", cn_def: "小的" },
  "snowman": { pos: "n.", en_def: "a figure made of snow shaped like a person", cn_def: "雪人" },
  "soft": { pos: "adj.", en_def: "not hard or rough to touch", cn_def: "柔軟的" },
  "sounded": { pos: "v.", en_def: "seemed a certain way based on noise", cn_def: "聽起來" },
  "soup": { pos: "n.", en_def: "a liquid food made by cooking ingredients in water", cn_def: "湯" },
  "started": { pos: "v.", en_def: "began (past tense of start)", cn_def: "開始（start的過去式）" },
  "stay": { pos: "v.", en_def: "to remain in a place", cn_def: "停留" },
  "stopped": { pos: "v.", en_def: "ended an action or movement", cn_def: "停止" },
  "stream": { pos: "n.", en_def: "a small narrow river", cn_def: "溪流" },
  "street": { pos: "n.", en_def: "a road in a town or city", cn_def: "街道" },
  "strong": { pos: "adj.", en_def: "having a lot of power or force", cn_def: "強壯的；強烈的" },
  "sudden": { pos: "adj.", en_def: "happening quickly, without warning", cn_def: "突然的" },
  "suddenly": { pos: "adv.", en_def: "quickly, without warning", cn_def: "突然地" },
  "summer": { pos: "n.", en_def: "the warmest season of the year", cn_def: "夏天" },
  "sun": { pos: "n.", en_def: "the star that gives Earth light and heat", cn_def: "太陽" },
  "sunglasses": { pos: "n.", en_def: "dark glasses worn to protect eyes from sunlight", cn_def: "太陽眼鏡" },
  "sunscreen": { pos: "n.", en_def: "a cream that protects skin from the sun", cn_def: "防曬乳" },
  "sweat": { pos: "n.", en_def: "liquid that comes from skin when hot", cn_def: "汗" },
  "taiwan": { pos: "n.", en_def: "an island country in East Asia", cn_def: "台灣" },
  "take": { pos: "v.", en_def: "to get hold of and carry something", cn_def: "拿；帶" },
  "tall": { pos: "adj.", en_def: "having a great height", cn_def: "高的" },
  "tasted": { pos: "v.", en_def: "had a certain flavor", cn_def: "嚐起來" },
  "thick": { pos: "adj.", en_def: "having a large distance between two sides", cn_def: "厚的；濃的" },
  "things": { pos: "n.", en_def: "objects; items", cn_def: "東西" },
  "thunder": { pos: "n.", en_def: "the loud sound that follows lightning", cn_def: "雷" },
  "together": { pos: "adv.", en_def: "with each other, in the same place", cn_def: "一起" },
  "took": { pos: "v.", en_def: "got hold of something (past tense of take)", cn_def: "拿（take的過去式）" },
  "top": { pos: "n.", en_def: "the highest part of something", cn_def: "頂部" },
  "towel": { pos: "n.", en_def: "a cloth used for drying", cn_def: "毛巾" },
  "towels": { pos: "n.", en_def: "more than one towel", cn_def: "毛巾（複數）" },
  "town": { pos: "n.", en_def: "a small city", cn_def: "城鎮" },
  "trees": { pos: "n.", en_def: "tall plants with a trunk and branches", cn_def: "樹（複數）" },
  "tropical": { pos: "adj.", en_def: "relating to hot regions near the equator", cn_def: "熱帶的" },
  "turned": { pos: "v.", en_def: "changed into a different state or color", cn_def: "變成" },
  "umbrella": { pos: "n.", en_def: "a tool to keep you dry in the rain", cn_def: "雨傘" },
  "walk": { pos: "v.", en_def: "to move on foot at a normal speed", cn_def: "走；散步" },
  "wanted": { pos: "v.", en_def: "had a desire for something (past tense of want)", cn_def: "想要（want的過去式）" },
  "warm": { pos: "adj.", en_def: "having a comfortably high temperature", cn_def: "溫暖的" },
  "watch": { pos: "v.", en_def: "to look at something for a period of time", cn_def: "觀看" },
  "water": { pos: "n.", en_def: "the clear liquid in rivers, lakes, and rain", cn_def: "水" },
  "wearing": { pos: "v.", en_def: "having clothes on your body", cn_def: "穿著（進行式）" },
  "weather": { pos: "n.", en_def: "the condition of the sky and temperature outside", cn_def: "天氣" },
  "weekend": { pos: "n.", en_def: "Saturday and Sunday", cn_def: "週末" },
  "went": { pos: "v.", en_def: "moved to a place (past tense of go)", cn_def: "去（go的過去式）" },
  "white": { pos: "adj.", en_def: "having the color of snow or milk", cn_def: "白色的" },
  "whole": { pos: "adj.", en_def: "complete; all of something", cn_def: "整個的" },
  "wind": { pos: "n.", en_def: "air that moves quickly outside", cn_def: "風" },
  "winter": { pos: "n.", en_def: "the coldest season of the year", cn_def: "冬天" },
  "winters": { pos: "n.", en_def: "more than one winter", cn_def: "冬天（複數）" },
  "wipe": { pos: "v.", en_def: "to clean or dry something by rubbing it", cn_def: "擦拭" },
  "wonderfully": { pos: "adv.", en_def: "in a very good or pleasing way", cn_def: "極好地" },
  "worked": { pos: "v.", en_def: "did a job or task", cn_def: "工作；做事" },
  "yard": { pos: "n.", en_def: "an outdoor area next to a house", cn_def: "院子" },
  "year": { pos: "n.", en_def: "a period of 12 months", cn_def: "年" },
};