// ============================================================
// Group 17 Quiz Data: Size / State / Safety / Comparison
// Full word set (49 words) — adjectives describing size, state,
// safety, direction, and comparison from the "describing words"
// theme. Continues from Group 16 (Difficulty/Quality/Judgment).
// General adjectives will follow as the final group for this theme.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 17 - Size / State / Safety / Comparison (大小/狀態/安全/比較)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (49 words) ----
const VOCAB = [
  { word: "large", pos: "adj.", cn_def: "巨大的", en_def: "big in size or amount",
    sentence: "We needed a {{BLANK}} table to fit all twelve guests at the dinner.",
    cn: "我們需要一張大桌子才能讓十二位客人都坐下吃晚餐。" },
  { word: "big", pos: "adj.", cn_def: "大的", en_def: "of considerable size; not small",
    sentence: "My little brother got a {{BLANK}} surprise when he opened his birthday present.",
    cn: "我弟弟打開生日禮物時得到了一個很大的驚喜。" },
  { word: "small", pos: "adj.", cn_def: "小的", en_def: "not large in size or amount",
    sentence: "She keeps her jewelry in a {{BLANK}} wooden box on her dresser.",
    cn: "她把她的珠寶放在梳妝台上的一個小木盒裡。" },
  { word: "least", pos: "adj.", cn_def: "最小的", en_def: "the smallest amount or degree",
    sentence: "Out of all the desserts, the chocolate cake received the {{BLANK}} attention from guests.",
    cn: "在所有甜點中，巧克力蛋糕得到客人最少的關注。" },
  { word: "little", pos: "adj.", cn_def: "一點點的", en_def: "small in size or amount",
    sentence: "There was only a {{BLANK}} bit of milk left in the carton this morning.",
    cn: "今天早上紙盒裡只剩下一點點牛奶了。" },
  { word: "primary", pos: "adj.", cn_def: "首要的", en_def: "main or most important",
    sentence: "The {{BLANK}} reason she joined the team was to make new friends.",
    cn: "她加入這個隊伍的主要原因是想交新朋友。" },
  { word: "secondary", pos: "adj.", cn_def: "次要的", en_def: "less important than the main thing",
    sentence: "Winning the trophy felt like a {{BLANK}} goal compared to having fun with her teammates.",
    cn: "對她來說，贏得獎杯似乎是次要的目標，比起和隊友玩得開心更不重要。" },
  { word: "alive", pos: "adj.", cn_def: "活著的", en_def: "living; not dead",
    sentence: "The little bird looked hurt at first, but it was still {{BLANK}} and breathing.",
    cn: "那隻小鳥起初看起來受傷了，但牠仍然活著並有呼吸。" },
  { word: "dead", pos: "adj.", cn_def: "死的", en_def: "no longer alive",
    sentence: "We found a {{BLANK}} insect on the windowsill while cleaning the classroom.",
    cn: "我們打掃教室時在窗台上發現了一隻死掉的昆蟲。" },
  { word: "bright", pos: "adj.", cn_def: "明亮的", en_def: "giving off a lot of light; easy to see",
    sentence: "The {{BLANK}} morning sun made it hard for him to see the road ahead.",
    cn: "明亮的早晨陽光讓他很難看清前方的路。" },
  { word: "dark", pos: "adj.", cn_def: "黑暗的", en_def: "having little or no light",
    sentence: "The basement was so {{BLANK}} that we needed a flashlight to find the boxes.",
    cn: "地下室太暗了，我們需要手電筒才能找到那些箱子。" },
  { word: "forward", pos: "adj.", cn_def: "向前的", en_def: "directed toward the front",
    sentence: "The coach told the players to keep moving in a {{BLANK}} direction toward the goal.",
    cn: "教練告訴球員要持續朝球門的方向往前移動。" },
  { word: "backward", pos: "adj.", cn_def: "向後的", en_def: "directed toward the back",
    sentence: "He took one {{BLANK}} step and accidentally bumped into the table behind him.",
    cn: "他向後退了一步，結果不小心撞到了身後的桌子。" },
  { word: "safe", pos: "adj.", cn_def: "安全的", en_def: "free from danger or risk",
    sentence: "My parents always remind me to wear a helmet to stay {{BLANK}} while biking.",
    cn: "我父母總是提醒我騎自行車時要戴安全帽以保持安全。" },
  { word: "dangerous", pos: "adj.", cn_def: "危險的", en_def: "likely to cause harm or injury",
    sentence: "Swimming alone in the deep ocean at night can be extremely {{BLANK}}.",
    cn: "晚上獨自在深海游泳可能非常危險。" },
  { word: "same", pos: "adj.", cn_def: "相同的", en_def: "exactly alike; not different",
    sentence: "My sister and I were born on the {{BLANK}} day, exactly one year apart.",
    cn: "我和姐姐在同一天出生，相差整整一年。" },
  { word: "different", pos: "adj.", cn_def: "不同的", en_def: "not the same; unlike each other",
    sentence: "Each student in the art class chose a completely {{BLANK}} color for their painting.",
    cn: "美術課上每位學生都為自己的畫選了完全不同的顏色。" },
  { word: "early", pos: "adj.", cn_def: "早的", en_def: "happening before the usual or expected time",
    sentence: "We caught an {{BLANK}} train to avoid the crowds at the station.",
    cn: "我們搭了一班早班車以避開車站的人群。" },
  { word: "late", pos: "adj.", cn_def: "遲到的", en_def: "happening after the usual or expected time",
    sentence: "He arrived {{BLANK}} to class because his bus broke down on the way.",
    cn: "他因為公車在路上故障而上課遲到了。" },
  { word: "fancy", pos: "adj.", cn_def: "花俏的", en_def: "decorated and elegant; not plain",
    sentence: "She wore a {{BLANK}} dress with sparkling beads to the wedding party.",
    cn: "她穿了一件鑲著閃亮珠子的華麗禮服去參加婚禮。" },
  { word: "plain", pos: "adj.", cn_def: "樸素的", en_def: "simple in style, without decoration",
    sentence: "He prefers a {{BLANK}} white t-shirt over one with loud patterns.",
    cn: "他比較喜歡樸素的白色T恤，而不是花樣花俏的。" },
  { word: "fast", pos: "adj.", cn_def: "快的", en_def: "moving or able to move quickly",
    sentence: "The {{BLANK}} runner finished the race almost a full minute before everyone else.",
    cn: "那位快速的跑者比其他人提早將近一分鐘完成比賽。" },
  { word: "quick", pos: "adj.", cn_def: "迅速的", en_def: "happening or done with speed",
    sentence: "She gave a {{BLANK}} answer to the question without even pausing to think.",
    cn: "她不假思索地給了一個迅速的答案。" },
  { word: "slow", pos: "adj.", cn_def: "慢的", en_def: "not moving or happening quickly",
    sentence: "The traffic was so {{BLANK}} that we arrived twenty minutes later than planned.",
    cn: "車流非常緩慢，我們比預計時間晚了二十分鐘才到。" },
  { word: "impossible", pos: "adj.", cn_def: "不可能的", en_def: "not able to happen or be done",
    sentence: "It seemed {{BLANK}} to finish all the homework in just one hour.",
    cn: "在一個小時內完成所有作業似乎是不可能的。" },
  { word: "possible", pos: "adj.", cn_def: "可能的", en_def: "able to happen or be done",
    sentence: "With a little extra practice, it is definitely {{BLANK}} to improve your grade.",
    cn: "只要多一點練習，提升成績絕對是有可能的。" },
  { word: "likely", pos: "adj.", cn_def: "有可能的", en_def: "probable; expected to happen",
    sentence: "According to the weather report, it is {{BLANK}} to rain later this afternoon.",
    cn: "根據氣象報告，今天下午稍後很有可能會下雨。" },
  { word: "distant", pos: "adj.", cn_def: "遙遠的", en_def: "far away in space or time",
    sentence: "From the hilltop, we could see a {{BLANK}} mountain covered in snow.",
    cn: "從山頂上，我們能看到一座覆蓋著雪的遙遠山峰。" },
  { word: "near", pos: "adj.", cn_def: "近的", en_def: "not far away in distance",
    sentence: "Our new apartment is {{BLANK}} enough to the school that I can walk there.",
    cn: "我們的新公寓離學校很近，近到我可以走路去上學。" },
  { word: "new", pos: "adj.", cn_def: "新的", en_def: "recently made, bought, or arrived",
    sentence: "Everyone wanted to try out the {{BLANK}} computers in the school's tech lab.",
    cn: "大家都想試用學校科技教室裡的新電腦。" },
  { word: "old", pos: "adj.", cn_def: "舊的；老的", en_def: "having existed for a long time; not new",
    sentence: "My grandfather still drives the same {{BLANK}} truck he bought thirty years ago.",
    cn: "我爺爺仍然開著他三十年前買的那台舊卡車。" },
  { word: "wrong", pos: "adj.", cn_def: "錯誤的", en_def: "not correct; incorrect",
    sentence: "He realized halfway through the test that he had written the {{BLANK}} answer.",
    cn: "他在考試進行到一半時意識到自己寫了錯誤的答案。" },
  { word: "right", pos: "adj.", cn_def: "右邊的；正確的", en_def: "correct, or located on the opposite side from left",
    sentence: "Turn {{BLANK}} at the next traffic light to reach the museum.",
    cn: "在下一個紅綠燈右轉就能到達博物館。" },
  { word: "left", pos: "adj.", cn_def: "左邊的", en_def: "located on the side opposite from right",
    sentence: "She broke her {{BLANK}} arm after falling off her bicycle last weekend.",
    cn: "她上週末從自行車上摔下來，摔斷了左手臂。" },
  { word: "major", pos: "adj.", cn_def: "主要的", en_def: "important or significant; large in scale",
    sentence: "Losing electricity for a whole week was a {{BLANK}} problem for the village.",
    cn: "整整一週沒有電對村莊來說是一個重大的問題。" },
  { word: "minor", pos: "adj.", cn_def: "次要的", en_def: "small or not very important",
    sentence: "Luckily, he only suffered a {{BLANK}} injury after the small bicycle accident.",
    cn: "幸運的是，他在這次小自行車事故後只受了輕微的傷。" },
  { word: "maximum", pos: "adj.", cn_def: "最大限度的", en_def: "the greatest amount or level possible",
    sentence: "The elevator has a {{BLANK}} weight limit of one thousand pounds.",
    cn: "這座電梯的最大重量限制是一千磅。" },
  { word: "medium", pos: "adj.", cn_def: "中等的", en_def: "average in size, amount, or degree",
    sentence: "I usually order a {{BLANK}} cup of coffee, not too big and not too small.",
    cn: "我通常會點一杯中杯咖啡，不會太大也不會太小。" },
  { word: "middle", pos: "adj.", cn_def: "中間的", en_def: "in the center; neither at the start nor the end",
    sentence: "Our family always sits in the {{BLANK}} row of seats at the movie theater.",
    cn: "我們家在電影院總是坐在中間那一排座位。" },
  { word: "negative", pos: "adj.", cn_def: "否定的", en_def: "expressing disagreement, doubt, or a lack of something",
    sentence: "Try not to use such {{BLANK}} words when talking about your own mistakes.",
    cn: "在談論自己的錯誤時，盡量不要使用這麼負面的詞語。" },
  { word: "positive", pos: "adj.", cn_def: "正面的", en_def: "expressing agreement, hope, or a good attitude",
    sentence: "Her coach always stays {{BLANK}} and encourages the team even after a loss.",
    cn: "她的教練即使在輸球後也總是保持正面，並鼓勵球隊。" },
  { word: "noisy", pos: "adj.", cn_def: "喧鬧的", en_def: "making a lot of loud, unpleasant sound",
    sentence: "The construction site next door has been incredibly {{BLANK}} since early this morning.",
    cn: "隔壁的工地從今天一大早就非常吵鬧。" },
  { word: "peaceful", pos: "adj.", cn_def: "寧靜的", en_def: "calm and quiet; free from disturbance",
    sentence: "Early mornings in the countryside feel so {{BLANK}} compared to the busy city.",
    cn: "鄉村的清晨比起繁忙的城市感覺寧靜許多。" },
  { word: "quiet", pos: "adj.", cn_def: "安靜的", en_def: "making little or no noise",
    sentence: "Please be {{BLANK}} in the library so other students can concentrate on studying.",
    cn: "請在圖書館保持安靜，讓其他學生能專心學習。" },
  { word: "silent", pos: "adj.", cn_def: "寂靜的", en_def: "completely quiet; making no sound at all",
    sentence: "The whole classroom stayed {{BLANK}} while the teacher read out the test results.",
    cn: "老師宣布考試結果時，整間教室都鴉雀無聲。" },
  { word: "rich", pos: "adj.", cn_def: "富有的", en_def: "having a lot of money or valuable things",
    sentence: "The {{BLANK}} businessman donated a huge sum of money to the local hospital.",
    cn: "那位富有的商人捐了一大筆錢給當地醫院。" },
  { word: "poor", pos: "adj.", cn_def: "貧困的", en_def: "having very little money",
    sentence: "The charity collects warm clothes every winter for {{BLANK}} families in the area.",
    cn: "這個慈善機構每年冬天都會為當地的貧困家庭收集保暖衣物。" },
  { word: "private", pos: "adj.", cn_def: "私人的", en_def: "belonging to a particular person, not shared with others",
    sentence: "She keeps a {{BLANK}} diary that she never shows to anyone else.",
    cn: "她寫了一本私人日記，從不讓任何人看。" },
  { word: "public", pos: "adj.", cn_def: "公共的", en_def: "open to or shared by everyone",
    sentence: "Our neighborhood built a new {{BLANK}} park where families can play and relax.",
    cn: "我們社區建了一座新的公共公園，供家庭遊玩和休息。" }
];

// ---- Part 2 data: 49 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (13/12/12/12), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "Twelve guests were coming for dinner, and every chair needed a spot at the table. We needed something ______ to fit them all.",
    options: ["large","small","least","little"], answer: 0, vocabIndex: 0 },
  { q: "When my little brother finally opened his birthday present, his eyes grew wide with joy. It turned out to be a really ______ surprise.",
    options: ["small","big","least","minor"], answer: 1, vocabIndex: 1 },
  { q: "She keeps her favorite rings and necklaces somewhere safe on top of her dresser. They all fit neatly inside a ______ wooden box.",
    options: ["large","big","small","major"], answer: 2, vocabIndex: 2 },
  { q: "At the dessert table, several cakes and pies were laid out for the guests to enjoy. Out of all of them, the chocolate cake got the ______ attention.",
    options: ["most","major","primary","least"], answer: 3, vocabIndex: 3 },
  { q: "This morning, the milk carton felt almost empty when I picked it up for breakfast. There was only a ______ bit left inside.",
    options: ["large","major","little","secondary"], answer: 2, vocabIndex: 4 },
  { q: "She joined the school basketball team mostly because her friends were already on it. The ______ reason was simply to make new friends.",
    options: ["secondary","minor","least","primary"], answer: 3, vocabIndex: 5 },
  { q: "Winning the trophy felt nice, but it was not what mattered most to her during the season. That goal felt more ______ compared to having fun with her team.",
    options: ["secondary","primary","major","maximum"], answer: 0, vocabIndex: 6 },
  { q: "The little bird lying near the fence looked hurt and still for a moment. To our relief, it was breathing and clearly still ______.",
    options: ["dead","safe","dangerous","alive"], answer: 3, vocabIndex: 7 },
  { q: "While cleaning the classroom windowsill, two students noticed something small and still lying there. It turned out to be a ______ insect.",
    options: ["dead","alive","tiny","fast"], answer: 0, vocabIndex: 8 },
  { q: "Driving toward the sunrise that morning, he had to squint and shield his eyes from the road ahead. The ______ light made it hard to see.",
    options: ["dark","dim","quiet","bright"], answer: 3, vocabIndex: 9 },
  { q: "We needed flashlights just to find the old boxes stored in the basement. It was simply too ______ down there to see anything clearly.",
    options: ["bright","dark","noisy","quiet"], answer: 1, vocabIndex: 10 },
  { q: "During practice, the coach kept shouting at the players to keep their attention on the goal ahead. He wanted them moving in a ______ direction at all times.",
    options: ["backward","left","forward","right"], answer: 2, vocabIndex: 11 },
  { q: "While trying to take a photo, he stepped without looking and bumped right into the table behind him. That single ______ step caused quite a mess.",
    options: ["forward","backward","left","right"], answer: 1, vocabIndex: 12 },
  { q: "Before letting me ride my bike to school, my parents always remind me to wear a helmet. They say it helps keep me ______ on the road.",
    options: ["safe","dangerous","noisy","fast"], answer: 0, vocabIndex: 13 },
  { q: "Lifeguards always warn visitors never to swim alone in the deep ocean once the sun goes down. Doing so at night can be extremely ______.",
    options: ["safe","dangerous","peaceful","quiet"], answer: 1, vocabIndex: 14 },
  { q: "My sister and I share an unusual fact about our birthdays that surprises most people. We were both born on the exact ______ day, one year apart.",
    options: ["same","different","early","late"], answer: 0, vocabIndex: 15 },
  { q: "Walking around the art classroom, you could see every student had picked something unique for their painting. Each one chose a completely ______ color from the others.",
    options: ["same","different","early","late"], answer: 1, vocabIndex: 16 },
  { q: "To avoid the busy crowds that gather at the station every morning, our family planned ahead carefully. We caught an ______ train instead.",
    options: ["late","fast","slow","early"], answer: 3, vocabIndex: 17 },
  { q: "His bus broke down halfway through the trip, leaving him stuck on the side of the road for almost an hour. By the time he reached school, he was clearly ______.",
    options: ["early","late","fast","quick"], answer: 1, vocabIndex: 18 },
  { q: "For the wedding party, she chose something special covered in sparkling beads and delicate lace. Her ______ dress caught everyone's attention as she walked in.",
    options: ["plain","dark","fancy","quiet"], answer: 2, vocabIndex: 19 },
  { q: "Instead of choosing a shirt covered in loud patterns and bright colors, he reached for something simpler. He always prefers a ______ white t-shirt.",
    options: ["plain","fancy","bright","noisy"], answer: 0, vocabIndex: 20 },
  { q: "At the school track meet, one runner pulled far ahead of everyone else almost from the very start. That ______ runner finished nearly a full minute before the rest.",
    options: ["slow","late","fast","early"], answer: 2, vocabIndex: 21 },
  { q: "When the teacher asked a tricky question, one student raised her hand and answered almost instantly. Her ______ response surprised the whole class.",
    options: ["quick","slow","late","early"], answer: 0, vocabIndex: 22 },
  { q: "Heavy traffic on the highway that afternoon made everyone in the car feel restless and impatient. Everything moved so ______ that we arrived twenty minutes late.",
    options: ["fast","quick","slow","early"], answer: 2, vocabIndex: 23 },
  { q: "Looking at the giant pile of homework on his desk, he sighed and shook his head in frustration. Finishing it all within one single hour seemed completely ______.",
    options: ["possible","impossible","likely","easy"], answer: 1, vocabIndex: 24 },
  { q: "Her teacher reminded her that with a bit more effort and some extra practice, her grade could still improve. Reaching a higher score was definitely ______.",
    options: ["impossible","distant","unlikely","possible"], answer: 3, vocabIndex: 25 },
  { q: "Looking out the window at the gray clouds rolling in, the weather forecaster made a quick prediction. Rain later in the afternoon seemed quite ______.",
    options: ["likely","impossible","distant","near"], answer: 0, vocabIndex: 26 },
  { q: "Standing on the hilltop, the hikers pointed toward something far away, barely visible through the haze. A snow-covered mountain looked tiny and ______ in the distance.",
    options: ["near","close","small","distant"], answer: 3, vocabIndex: 27 },
  { q: "Choosing where to live, my parents wanted somewhere within easy walking distance of my school. Our new apartment turned out to be ______ enough that I never need a ride.",
    options: ["distant","far","near","old"], answer: 2, vocabIndex: 28 },
  { q: "The school just finished installing fresh equipment in its technology lab over the summer break. Every student was excited to try the ______ computers.",
    options: ["old","new","fast","slow"], answer: 1, vocabIndex: 29 },
  { q: "Even after thirty years on the road, my grandfather refuses to give up his favorite vehicle. He still proudly drives that same ______ truck.",
    options: ["new","fast","old","fancy"], answer: 2, vocabIndex: 30 },
  { q: "Halfway through the math test, he glanced back over his work and felt a sudden wave of doubt. He realized he had written the ______ answer.",
    options: ["wrong","right","correct","same"], answer: 0, vocabIndex: 31 },
  { q: "Looking for directions to the museum, a stranger explained that the building was just past the next traffic light. You simply needed to turn ______ to get there.",
    options: ["left","forward","backward","right"], answer: 3, vocabIndex: 32 },
  { q: "After falling off her bicycle last weekend, she went straight to the hospital with a painful arm. The doctor confirmed she had broken her ______ arm.",
    options: ["right","small","left","old"], answer: 2, vocabIndex: 33 },
  { q: "For an entire week, the small village had no electricity at all, affecting every single household. It quickly became a ______ problem for everyone living there.",
    options: ["major","minor","medium","secondary"], answer: 0, vocabIndex: 34 },
  { q: "After a small bicycle accident on his way home from school, he visited the doctor just to be safe. Luckily, the doctor said it was only a ______ injury.",
    options: ["major","dangerous","minor","serious"], answer: 2, vocabIndex: 35 },
  { q: "Posted near the buttons, a small sign explained an important safety rule for everyone riding inside. The elevator could carry a ______ weight of one thousand pounds.",
    options: ["minimum","maximum","average","medium"], answer: 1, vocabIndex: 36 },
  { q: "Standing at the coffee counter, he looked at the three cup sizes and made his usual choice. He typically orders a ______ cup, never too big or too small.",
    options: ["maximum","minimum","medium","large"], answer: 2, vocabIndex: 37 },
  { q: "At the cinema, our family has a favorite spot they always try to choose before the movie starts. We always sit in the ______ row of seats.",
    options: ["front","back","side","middle"], answer: 3, vocabIndex: 38 },
  { q: "When talking about a mistake you made, it helps to avoid using harsh, discouraging language about yourself. Try not to use such ______ words.",
    options: ["positive","negative","kind","gentle"], answer: 1, vocabIndex: 39 },
  { q: "Even after the team lost an important match, the coach refused to let anyone feel discouraged. She always stays ______ and keeps encouraging the players.",
    options: ["negative","quiet","silent","positive"], answer: 3, vocabIndex: 40 },
  { q: "Ever since early this morning, the construction site next door has been impossible to ignore. The constant drilling and hammering sound incredibly ______.",
    options: ["noisy","quiet","peaceful","silent"], answer: 0, vocabIndex: 41 },
  { q: "After living in the busy city for years, she finally moved to a small house in the countryside. Mornings there now feel wonderfully ______ compared to before.",
    options: ["noisy","dangerous","fast","peaceful"], answer: 3, vocabIndex: 42 },
  { q: "A sign near the entrance asks every visitor to lower their voice and respect other people studying inside. Please stay ______ in the library at all times.",
    options: ["quiet","noisy","fast","bright"], answer: 0, vocabIndex: 43 },
  { q: "As the teacher slowly read each name and score from the test results, nobody in the room dared to speak. The whole classroom remained completely ______.",
    options: ["quiet","noisy","loud","silent"], answer: 3, vocabIndex: 44 },
  { q: "Known throughout town for his enormous house and expensive cars, one local businessman recently donated a huge sum to the hospital. Everyone described him as remarkably ______.",
    options: ["poor","generous","rich","kind"], answer: 2, vocabIndex: 45 },
  { q: "Every winter, a local charity gathers warm coats and blankets to give to families struggling to make ends meet. These donations go directly to ______ households in the area.",
    options: ["rich","poor","wealthy","lucky"], answer: 1, vocabIndex: 46 },
  { q: "She writes down her deepest thoughts and secrets every night in a notebook hidden under her bed. That ______ diary is something she never shows to anyone.",
    options: ["private","public","open","shared"], answer: 0, vocabIndex: 47 },
  { q: "Residents in the neighborhood worked together to raise money for a new outdoor space everyone could enjoy. The result was a beautiful new ______ park.",
    options: ["private","public","secret","personal"], answer: 1, vocabIndex: 48 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "accident": { pos: "n.", en_def: "an unexpected event that causes harm or damage", cn_def: "意外；事故" },
  "accidentally": { pos: "adv.", en_def: "without meaning to; by mistake", cn_def: "不小心地" },
  "average": { pos: "adj.", en_def: "typical; not especially large or small", cn_def: "一般的；平均的" },
  "back": { pos: "n.", en_def: "the rear part of something; the opposite of front", cn_def: "後面" },
  "basement": { pos: "n.", en_def: "a room below the ground level of a building", cn_def: "地下室" },
  "beads": { pos: "n.", en_def: "small decorative balls, often strung together", cn_def: "珠子" },
  "bicycle": { pos: "n.", en_def: "a two-wheeled vehicle powered by pedaling", cn_def: "自行車" },
  "birthday": { pos: "n.", en_def: "the day of the year a person was born", cn_def: "生日" },
  "businessman": { pos: "n.", en_def: "a man who works in business, often running a company", cn_def: "商人" },
  "charity": { pos: "n.", en_def: "an organization that helps people in need", cn_def: "慈善機構" },
  "close": { pos: "adj.", en_def: "near in distance or time", cn_def: "近的" },
  "concentrate": { pos: "v.", en_def: "to focus all of one's attention on something", cn_def: "專心" },
  "construction": { pos: "n.", en_def: "the work of building something", cn_def: "建築工程" },
  "correct": { pos: "adj.", en_def: "free from mistakes; accurate", cn_def: "正確的" },
  "countryside": { pos: "n.", en_def: "land outside of cities, with farms and fields", cn_def: "鄉村" },
  "dim": { pos: "adj.", en_def: "not bright; having little light", cn_def: "昏暗的" },
  "donated": { pos: "v.", en_def: "gave money or goods to help others", cn_def: "捐贈（過去式）" },
  "dresser": { pos: "n.", en_def: "a piece of furniture with drawers for storing clothes", cn_def: "梳妝台" },
  "easy": { pos: "adj.", en_def: "not difficult; simple to do", cn_def: "容易的" },
  "electricity": { pos: "n.", en_def: "a form of energy used to power lights and machines", cn_def: "電力" },
  "elevator": { pos: "n.", en_def: "a machine that carries people up and down between floors", cn_def: "電梯" },
  "encourages": { pos: "v.", en_def: "gives someone support or confidence to do something", cn_def: "鼓勵" },
  "far": { pos: "adj.", en_def: "a long distance away", cn_def: "遙遠的" },
  "flashlight": { pos: "n.", en_def: "a small portable light powered by batteries", cn_def: "手電筒" },
  "front": { pos: "n.", en_def: "the part facing forward; the opposite of back", cn_def: "前面" },
  "generous": { pos: "adj.", en_def: "willing to give freely to others", cn_def: "慷慨的" },
  "gentle": { pos: "adj.", en_def: "kind, calm, and not rough or harsh", cn_def: "溫和的" },
  "helmet": { pos: "n.", en_def: "a hard hat worn to protect the head", cn_def: "安全帽" },
  "hilltop": { pos: "n.", en_def: "the top of a hill", cn_def: "山頂" },
  "improve": { pos: "v.", en_def: "to make something better", cn_def: "改善" },
  "jewelry": { pos: "n.", en_def: "decorative items worn on the body, like rings and necklaces", cn_def: "珠寶" },
  "kind": { pos: "adj.", en_def: "caring and gentle toward others", cn_def: "親切的" },
  "lab": { pos: "n.", en_def: "a room used for scientific experiments, short for laboratory", cn_def: "實驗室" },
  "loud": { pos: "adj.", en_def: "making a lot of noise", cn_def: "大聲的" },
  "lucky": { pos: "adj.", en_def: "having good things happen by chance", cn_def: "幸運的" },
  "minimum": { pos: "adj.", en_def: "the smallest amount possible", cn_def: "最小限度的" },
  "most": { pos: "adj.", en_def: "the greatest amount or number", cn_def: "最多的" },
  "museum": { pos: "n.", en_def: "a building where interesting old or rare things are shown", cn_def: "博物館" },
  "open": { pos: "adj.", en_def: "not closed; available for everyone", cn_def: "開放的" },
  "patterns": { pos: "n.", en_def: "repeated designs or shapes", cn_def: "圖案" },
  "personal": { pos: "adj.", en_def: "belonging to or relating to a particular person", cn_def: "個人的" },
  "race": { pos: "n.", en_def: "a competition to see who is fastest", cn_def: "比賽" },
  "report": { pos: "n.", en_def: "information given about weather, news, or events", cn_def: "報告" },
  "secret": { pos: "adj.", en_def: "known only by a few people; not shared openly", cn_def: "秘密的" },
  "serious": { pos: "adj.", en_def: "not funny; thoughtful or grave; important and needing attention", cn_def: "嚴肅的；嚴重的" },
  "shared": { pos: "adj.", en_def: "used or owned by more than one person", cn_def: "共享的" },
  "side": { pos: "n.", en_def: "a position to the left or right, or a part of something", cn_def: "邊；側" },
  "sparkling": { pos: "adj.", en_def: "shining brightly with small points of light", cn_def: "閃爍的" },
  "suffered": { pos: "v.", en_def: "experienced something painful or unpleasant", cn_def: "遭受（過去式）" },
  "tiny": { pos: "adj.", en_def: "extremely small", cn_def: "微小的" },
  "trophy": { pos: "n.", en_def: "an award given for winning a competition", cn_def: "獎杯" },
  "unlikely": { pos: "adj.", en_def: "not probable; not expected to happen", cn_def: "不太可能的" },
  "village": { pos: "n.", en_def: "a small group of houses, smaller than a town", cn_def: "村莊" },
  "wealthy": { pos: "adj.", en_def: "having a lot of money", cn_def: "富有的" },
  "wedding": { pos: "n.", en_def: "a ceremony where two people get married", cn_def: "婚禮" },
  "windowsill": { pos: "n.", en_def: "the ledge at the bottom of a window", cn_def: "窗台" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
