// ============================================================
// Group 8 Quiz Data: Family / People / Age / Titles
// Full word set (42 words) — family members and people/age/
// title categories from the "people / family / jobs /
// personality" theme. Jobs and Roles/Personality will follow
// as separate groups.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 8 - Family / People / Age / Titles (家庭成員/人物/年齡/稱謂)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (42 words) ----
const VOCAB = [
  { word: "family", pos: "n.", cn_def: "家庭", en_def: "a group of people who are related, such as parents and children",
    sentence: "Every Sunday evening, my whole {{BLANK}} gathers together for a big dinner.",
    cn: "每個星期天晚上，我們全家人都會聚在一起吃一頓豐盛的晚餐。" },
  { word: "aunt", pos: "n.", cn_def: "阿姨", en_def: "the sister of your father or mother",
    sentence: "My {{BLANK}} always brings homemade cookies whenever she visits us.",
    cn: "我阿姨每次來看我們時，都會帶自己做的餅乾。" },
  { word: "uncle", pos: "n.", cn_def: "叔叔", en_def: "the brother of your father or mother",
    sentence: "My {{BLANK}} taught me how to ride a bicycle in the park.",
    cn: "我叔叔在公園裡教我怎麼騎自行車。" },
  { word: "brother", pos: "n.", cn_def: "兄弟", en_def: "a boy or man who has the same parents as you",
    sentence: "My older {{BLANK}} helps me with my math homework every night.",
    cn: "我哥哥每天晚上都會幫我做數學作業。" },
  { word: "sister", pos: "n.", cn_def: "姊妹", en_def: "a girl or woman who has the same parents as you",
    sentence: "My little {{BLANK}} always borrows my clothes without asking first.",
    cn: "我妹妹總是不問就借穿我的衣服。" },
  { word: "cousin", pos: "n.", cn_def: "表(堂)兄弟姊妹", en_def: "the child of your aunt or uncle",
    sentence: "During summer vacation, my {{BLANK}} from Taipei comes to stay with us.",
    cn: "暑假期間，我從台北來的表哥會來我們家住。" },
  { word: "daughter", pos: "n.", cn_def: "女兒", en_def: "a person's female child",
    sentence: "My neighbor's {{BLANK}} just started learning the piano this year.",
    cn: "我鄰居的女兒今年剛開始學鋼琴。" },
  { word: "son", pos: "n.", cn_def: "兒子", en_def: "a person's male child",
    sentence: "Their {{BLANK}} wants to become a doctor when he grows up.",
    cn: "他們的兒子長大後想當醫生。" },
  { word: "father", pos: "n.", cn_def: "爸爸", en_def: "a male parent",
    sentence: "My {{BLANK}} drives me to school every morning before work.",
    cn: "我爸爸每天早上上班前都會載我去上學。" },
  { word: "mother", pos: "n.", cn_def: "媽媽", en_def: "a female parent",
    sentence: "My {{BLANK}} always packs an extra snack in my school bag.",
    cn: "我媽媽總是會在我的書包裡多放一份點心。" },
  { word: "parent", pos: "n.", cn_def: "雙親", en_def: "a father or mother",
    sentence: "Each {{BLANK}} signed the school form before the trip on Friday.",
    cn: "每位家長都在星期五的旅行前簽好了學校的表格。" },
  { word: "granddaughter", pos: "n.", cn_def: "孫女", en_def: "the daughter of someone's son or daughter",
    sentence: "My grandmother proudly shows photos of her {{BLANK}} to all her friends.",
    cn: "我奶奶總是驕傲地把孫女的照片給所有朋友看。" },
  { word: "grandson", pos: "n.", cn_def: "孫子", en_def: "the son of someone's son or daughter",
    sentence: "Every Lunar New Year, my grandfather gives his {{BLANK}} a red envelope.",
    cn: "每年農曆新年，我爺爺都會給他的孫子一個紅包。" },
  { word: "grandfather", pos: "n.", cn_def: "祖父（外公）", en_def: "the father of your father or mother",
    sentence: "My {{BLANK}} tells the same funny story every time we visit him.",
    cn: "我爺爺每次我們去看他時都會講同一個有趣的故事。" },
  { word: "grandmother", pos: "n.", cn_def: "祖母（外婆）", en_def: "the mother of your father or mother",
    sentence: "My {{BLANK}} taught me how to make dumplings when I was little.",
    cn: "我奶奶在我小時候教我怎麼包餃子。" },
  { word: "husband", pos: "n.", cn_def: "丈夫", en_def: "a married man, in relation to his wife",
    sentence: "Her {{BLANK}} cooks dinner for the whole family every Wednesday night.",
    cn: "她的丈夫每個星期三晚上都會幫全家人做晚餐。" },
  { word: "wife", pos: "n.", cn_def: "妻子", en_def: "a married woman, in relation to her husband",
    sentence: "My uncle's {{BLANK}} runs a small flower shop near the train station.",
    cn: "我叔叔的妻子在火車站附近經營一家小花店。" },
  { word: "nephew", pos: "n.", cn_def: "侄子", en_def: "the son of your brother or sister",
    sentence: "My {{BLANK}} just turned five and loves playing with toy trains.",
    cn: "我的姪子剛滿五歲，很喜歡玩玩具火車。" },
  { word: "niece", pos: "n.", cn_def: "侄女", en_def: "the daughter of your brother or sister",
    sentence: "I gave my {{BLANK}} a storybook for her birthday last month.",
    cn: "上個月我送了我的姪女一本故事書當生日禮物。" },
  { word: "relative", pos: "n.", cn_def: "親戚", en_def: "a person in your family, such as an aunt or cousin",
    sentence: "Many of our {{BLANK}} traveled from other cities to attend the wedding.",
    cn: "我們的許多親戚都從其他城市來參加這場婚禮。" },
  { word: "human", pos: "adj.", cn_def: "人類的", en_def: "relating to people rather than animals or machines",
    sentence: "Scientists say that this kind of memory is a uniquely {{BLANK}} ability.",
    cn: "科學家說這種記憶力是人類獨有的能力。" },
  { word: "person", pos: "n.", cn_def: "個人", en_def: "a single human being",
    sentence: "Only one {{BLANK}} can sit in the front seat of the small car.",
    cn: "這輛小車的前座只能坐一個人。" },
  { word: "people", pos: "n.", cn_def: "人們", en_def: "more than one person",
    sentence: "Hundreds of {{BLANK}} lined up outside the store before it even opened.",
    cn: "商店還沒開門，外面就已經排了好幾百人。" },
  { word: "adult", pos: "n.", cn_def: "成人", en_def: "a fully grown person",
    sentence: "Children under twelve must be accompanied by an {{BLANK}} on this ride.",
    cn: "十二歲以下的兒童搭乘這項遊樂設施必須有成人陪同。" },
  { word: "baby", pos: "n.", cn_def: "嬰孩", en_def: "a very young child who cannot yet walk or talk",
    sentence: "The new {{BLANK}} next door cries loudly almost every single night.",
    cn: "隔壁那個新生的嬰兒幾乎每晚都會大聲哭鬧。" },
  { word: "child", pos: "n.", cn_def: "小孩子", en_def: "a young person, not yet an adult",
    sentence: "Every {{BLANK}} in the class received a small gift from the teacher.",
    cn: "班上的每個孩子都收到了老師送的小禮物。" },
  { word: "kid", pos: "n.", cn_def: "孩子", en_def: "a child, used in a casual way",
    sentence: "The {{BLANK}} next door always wants to play basketball after school.",
    cn: "隔壁那個孩子放學後總是想打籃球。" },
  { word: "teenager", pos: "n.", cn_def: "青少年", en_def: "a young person between thirteen and nineteen years old",
    sentence: "Most {{BLANK}} in my neighborhood spend their weekends at the shopping mall.",
    cn: "我家附近的大多數青少年週末都會去逛購物中心。" },
  { word: "boy", pos: "n.", cn_def: "男孩", en_def: "a young male person",
    sentence: "The {{BLANK}} sitting next to me forgot to bring his pencil case today.",
    cn: "坐在我旁邊的那個男孩今天忘了帶他的鉛筆盒。" },
  { word: "girl", pos: "n.", cn_def: "女孩", en_def: "a young female person",
    sentence: "A {{BLANK}} from my class won first prize in the singing contest.",
    cn: "我班上的一個女孩在歌唱比賽中得到了第一名。" },
  { word: "gentleman", pos: "n.", cn_def: "紳士", en_def: "a polite and well-mannered man",
    sentence: "The old {{BLANK}} kindly held the door open for everyone entering the building.",
    cn: "那位老紳士很有禮貌地幫每個進入大樓的人開門。" },
  { word: "lady", pos: "n.", cn_def: "淑女", en_def: "a polite way to refer to a woman",
    sentence: "An elderly {{BLANK}} asked the driver to stop near the post office.",
    cn: "一位年長的女士請司機在郵局附近停車。" },
  { word: "ma'am", pos: "n.", cn_def: "女士", en_def: "a polite way to address a woman",
    sentence: "Excuse me, {{BLANK}}, could you please tell me where the exit is?",
    cn: "不好意思，女士，可以請您告訴我出口在哪裡嗎？" },
  { word: "sir", pos: "n.", cn_def: "先生", en_def: "a polite way to address a man",
    sentence: "Excuse me, {{BLANK}}, you dropped your wallet near the entrance.",
    cn: "先生，不好意思，您的錢包掉在入口附近了。" },
  { word: "Miss", pos: "n.", cn_def: "小姐", en_def: "a polite title used before the name of a young woman",
    sentence: "{{BLANK}} Chen will be our new English teacher starting next week.",
    cn: "陳小姐下星期開始將成為我們新的英文老師。" },
  { word: "Mr.", pos: "n.", cn_def: "先生", en_def: "a polite title used before a man's name",
    sentence: "{{BLANK}} Wang welcomed every new student warmly on the first day.",
    cn: "王先生在開學第一天熱情地歡迎每位新生。" },
  { word: "Mrs.", pos: "n.", cn_def: "夫人", en_def: "a polite title used before a married woman's name",
    sentence: "{{BLANK}} Lin organized the entire school fair by herself this year.",
    cn: "林夫人今年獨自籌辦了整個學校的園遊會。" },
  { word: "Ms.", pos: "n.", cn_def: "女士", en_def: "a polite title used before a woman's name",
    sentence: "{{BLANK}} Huang answered every question patiently during the meeting.",
    cn: "黃女士在會議中耐心地回答了每個問題。" },
  { word: "man", pos: "n.", cn_def: "男人", en_def: "an adult male person",
    sentence: "A tall {{BLANK}} in a gray coat asked us for directions downtown.",
    cn: "一位穿著灰色外套的高個子男人向我們問市區的方向。" },
  { word: "woman", pos: "n.", cn_def: "女人", en_def: "an adult female person",
    sentence: "The {{BLANK}} sitting across from me on the bus was reading a thick novel.",
    cn: "坐在公車上我對面的那位女人正在讀一本厚厚的小說。" },
  { word: "female", pos: "adj.", cn_def: "女性的", en_def: "relating to women or girls",
    sentence: "This year, more {{BLANK}} students joined the school's robotics club than ever before.",
    cn: "今年比以往有更多女學生加入學校的機器人社團。" },
  { word: "male", pos: "adj.", cn_def: "男性的", en_def: "relating to men or boys",
    sentence: "The coach is looking for a few more {{BLANK}} players to join the soccer team.",
    cn: "教練正在尋找幾位男學生加入足球隊。" }
];

// ---- Part 2 data: 42 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (11/11/10/10), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "Every Sunday evening, my relatives all come to our house together. My whole ______ gathers for a big dinner.",
    options: ["school","team","class","family"], answer: 3, vocabIndex: 0 },
  { q: "My mother's sister visits us every month with something delicious. My ______ always brings homemade cookies for everyone.",
    options: ["cousin","niece","aunt","daughter"], answer: 2, vocabIndex: 1 },
  { q: "My father's brother is very patient and kind to children. My ______ taught me how to ride a bicycle.",
    options: ["nephew","uncle","son","grandson"], answer: 1, vocabIndex: 2 },
  { q: "I have a sibling who is older than me and very smart. My older ______ helps me with homework every night.",
    options: ["sister","cousin","brother","uncle"], answer: 2, vocabIndex: 3 },
  { q: "I have a sibling who is younger and shares my closet often. My little ______ always borrows my clothes without asking.",
    options: ["brother","sister","aunt","niece"], answer: 1, vocabIndex: 4 },
  { q: "During summer vacation, a family member from Taipei stays with us. My ______ always brings fun stories from the city.",
    options: ["cousin","father","uncle","grandfather"], answer: 0, vocabIndex: 5 },
  { q: "My neighbor's child started a new hobby this year. Their ______ just began learning the piano a few months ago.",
    options: ["wife","daughter","aunt","niece"], answer: 1, vocabIndex: 6 },
  { q: "My friend's family has big dreams for their child's future. Their ______ wants to become a doctor when he grows up.",
    options: ["son","husband","father","nephew"], answer: 0, vocabIndex: 7 },
  { q: "Every weekday, the same person drops me off before going to work. My ______ drives me to school every morning.",
    options: ["brother","uncle","father","grandfather"], answer: 2, vocabIndex: 8 },
  { q: "Someone always remembers to add a little extra to my school bag. My ______ always packs an extra snack for me.",
    options: ["sister","aunt","cousin","mother"], answer: 3, vocabIndex: 9 },
  { q: "Before the school trip on Friday, a form needed to be signed at home. Each ______ signed the form that morning.",
    options: ["parent","teacher","student","child"], answer: 0, vocabIndex: 10 },
  { q: "My grandmother loves showing pictures of her family to friends. She proudly shows photos of her ______ to everyone.",
    options: ["niece","daughter","aunt","granddaughter"], answer: 3, vocabIndex: 11 },
  { q: "Every Lunar New Year, my grandfather follows the same kind tradition. He gives his ______ a red envelope each year.",
    options: ["nephew","son","grandson","cousin"], answer: 2, vocabIndex: 12 },
  { q: "Every time we visit, the same older relative tells a story we all know. My ______ tells the same funny story.",
    options: ["uncle","father","brother","grandfather"], answer: 3, vocabIndex: 13 },
  { q: "When I was little, someone in my family taught me a useful skill in the kitchen. My ______ taught me to make dumplings.",
    options: ["mother","grandmother","sister","aunt"], answer: 1, vocabIndex: 14 },
  { q: "Every Wednesday night, someone in the family takes over the kitchen. Her ______ cooks dinner for everyone that night.",
    options: ["father","brother","son","husband"], answer: 3, vocabIndex: 15 },
  { q: "My uncle's family runs a small business near the train station. His ______ manages a little flower shop there.",
    options: ["wife","daughter","sister","mother"], answer: 0, vocabIndex: 16 },
  { q: "A young family member just had a birthday and loves toy trains. My ______ just turned five years old.",
    options: ["niece","nephew","cousin","son"], answer: 1, vocabIndex: 17 },
  { q: "Last month, I gave a gift to a younger family member for her birthday. I gave my ______ a storybook.",
    options: ["sister","daughter","aunt","niece"], answer: 3, vocabIndex: 18 },
  { q: "At the wedding, many family members traveled a long distance to attend. Our ______ came from several different cities.",
    options: ["relatives","friends","neighbors","teachers"], answer: 0, vocabIndex: 19 },
  { q: "Scientists studying memory found something interesting about people compared to animals. This ability seems to be uniquely ______.",
    options: ["animal","natural","modern","human"], answer: 3, vocabIndex: 20 },
  { q: "The small car only has room for one passenger up front. Only one ______ can sit in the front seat.",
    options: ["person","family","group","team"], answer: 0, vocabIndex: 21 },
  { q: "Before the store even opened, a huge crowd had already formed outside. Hundreds of ______ stood waiting in line.",
    options: ["person","family","relative","people"], answer: 3, vocabIndex: 22 },
  { q: "This amusement park ride has a safety rule for young visitors. Children under twelve must be with an ______.",
    options: ["adult","child","teenager","kid"], answer: 0, vocabIndex: 23 },
  { q: "The neighbors next door welcomed someone new into their home recently. The new ______ cries loudly almost every night.",
    options: ["teenager","baby","adult","guest"], answer: 1, vocabIndex: 24 },
  { q: "On the last day of school, the teacher gave out small presents. Every ______ in the class received a gift.",
    options: ["adult","parent","child","teacher"], answer: 2, vocabIndex: 25 },
  { q: "After school, someone from the house nearby always wants to play sports. The ______ next door loves basketball.",
    options: ["adult","kid","parent","teacher"], answer: 1, vocabIndex: 26 },
  { q: "On weekends, many young people in this area gather at the same place. Most ______ spend their time at the mall.",
    options: ["teenagers","adults","children","babies"], answer: 0, vocabIndex: 27 },
  { q: "During class today, a forgotten item caused a small problem. The ______ sitting next to me forgot his pencil case.",
    options: ["girl","teacher","adult","boy"], answer: 3, vocabIndex: 28 },
  { q: "At the singing contest, someone from my class did very well. A ______ from my class won first prize.",
    options: ["boy","teacher","girl","adult"], answer: 2, vocabIndex: 29 },
  { q: "At the entrance of the building, someone kindly helped everyone passing through. The old ______ held the door open politely.",
    options: ["lady","gentleman","boy","kid"], answer: 1, vocabIndex: 30 },
  { q: "Near the post office, an older passenger asked the bus driver for a favor. An elderly ______ asked him to stop there.",
    options: ["gentleman","girl","lady","child"], answer: 2, vocabIndex: 31 },
  { q: "At the train station, someone politely asked a stranger for directions. \"Excuse me, ______, could you tell me where the exit is?\"",
    options: ["sir","Miss","Mrs.","ma'am"], answer: 3, vocabIndex: 32 },
  { q: "Near the entrance, someone noticed an item had fallen from another person's pocket. \"Excuse me, ______, you dropped your wallet.\"",
    options: ["ma'am","Miss","sir","Mrs."], answer: 2, vocabIndex: 33 },
  { q: "Starting next week, our class will welcome a new young teacher. ______ Chen will be teaching us English.",
    options: ["Mr.","Miss","Mrs.","Sir"], answer: 1, vocabIndex: 34 },
  { q: "On the first day of school, a kind teacher welcomed every new student. ______ Wang greeted everyone warmly that morning.",
    options: ["Mrs.","Miss","Mr.","Ms."], answer: 2, vocabIndex: 35 },
  { q: "This year, the school fair was organized entirely by one busy parent. ______ Lin planned the whole event by herself.",
    options: ["Mrs.","Mr.","Miss","Sir"], answer: 0, vocabIndex: 36 },
  { q: "During the meeting, one calm staff member answered every difficult question. ______ Huang stayed patient the entire time.",
    options: ["Mr.","Mrs.","Ms.","Sir"], answer: 2, vocabIndex: 37 },
  { q: "Downtown, a stranger needed help finding his way around the busy streets. A tall ______ in a gray coat asked us for directions.",
    options: ["man","woman","boy","girl"], answer: 0, vocabIndex: 38 },
  { q: "On the bus, someone across from me was deeply focused on a thick book. The ______ was reading a long novel quietly.",
    options: ["man","woman","boy","kid"], answer: 1, vocabIndex: 39 },
  { q: "This year, the school's robotics club saw a change in who joined. More ______ students signed up than ever before.",
    options: ["female","male","young","new"], answer: 0, vocabIndex: 40 },
  { q: "The soccer coach is looking to expand the team before the next season. He wants a few more ______ players to join.",
    options: ["female","male","young","new"], answer: 1, vocabIndex: 41 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "ability": { pos: "n.", en_def: "the power or skill to do something", cn_def: "能力" },
  "accompanied": { pos: "v.", en_def: "went somewhere together with someone", cn_def: "陪伴（過去式）" },
  "animal": { pos: "n.", en_def: "a living creature, not a plant", cn_def: "動物" },
  "answered": { pos: "v.", en_def: "gave a reply", cn_def: "回答（過去式）" },
  "attend": { pos: "v.", en_def: "to go to an event", cn_def: "出席；參加" },
  "basketball": { pos: "n.", en_def: "a sport played with a round ball and a high hoop", cn_def: "籃球" },
  "bicycle": { pos: "n.", en_def: "a two-wheeled vehicle powered by pedaling", cn_def: "自行車" },
  "birthday": { pos: "n.", en_def: "the day of the year a person was born", cn_def: "生日" },
  "borrows": { pos: "v.", en_def: "takes something to use and give back later", cn_def: "借用" },
  "building": { pos: "n.", en_def: "a structure with walls and a roof, like a house or office", cn_def: "建築物" },
  "children": { pos: "n.", en_def: "young people; the plural of child", cn_def: "孩子們" },
  "class": { pos: "n.", en_def: "a group of students who study together", cn_def: "班級" },
  "club": { pos: "n.", en_def: "a group of people who share an interest", cn_def: "社團" },
  "coach": { pos: "n.", en_def: "a person who trains a sports team", cn_def: "教練" },
  "coat": { pos: "n.", en_def: "a piece of clothing worn over other clothes outdoors", cn_def: "外套" },
  "contest": { pos: "n.", en_def: "a competition to find the best person at something", cn_def: "比賽" },
  "cookies": { pos: "n.", en_def: "small flat sweet baked foods", cn_def: "餅乾（複數）" },
  "directions": { pos: "n.", en_def: "instructions for how to get to a place", cn_def: "方向；指引" },
  "doctor": { pos: "n.", en_def: "a person trained to treat sick people", cn_def: "醫生" },
  "dumplings": { pos: "n.", en_def: "small pieces of dough filled with meat or vegetables", cn_def: "餃子（複數）" },
  "elderly": { pos: "adj.", en_def: "old; getting older", cn_def: "年長的" },
  "english": { pos: "n.", en_def: "the language spoken in countries like the UK and the US", cn_def: "英文" },
  "entrance": { pos: "n.", en_def: "the way into a place", cn_def: "入口" },
  "envelope": { pos: "n.", en_def: "a paper covering used to hold a letter or money", cn_def: "信封" },
  "excuse": { pos: "v.", en_def: "used to politely get someone's attention", cn_def: "請問；不好意思" },
  "exit": { pos: "n.", en_def: "the way out of a place", cn_def: "出口" },
  "fair": { pos: "n.", en_def: "an event with games, food, and activities", cn_def: "園遊會；市集" },
  "flower": { pos: "n.", en_def: "the colorful part of a plant that often smells nice", cn_def: "花" },
  "forgot": { pos: "v.", en_def: "did not remember (past tense of forget)", cn_def: "忘記（過去式）" },
  "form": { pos: "n.", en_def: "a paper document with spaces to fill in information", cn_def: "表格" },
  "friends": { pos: "n.", en_def: "people you know well and like", cn_def: "朋友（複數）" },
  "funny": { pos: "adj.", en_def: "causing laughter; amusing", cn_def: "有趣的；好笑的" },
  "gathers": { pos: "v.", en_def: "comes together in a group", cn_def: "聚集" },
  "gift": { pos: "n.", en_def: "something given to someone, often for a special occasion", cn_def: "禮物" },
  "group": { pos: "n.", en_def: "a number of people or things together", cn_def: "團體；群組" },
  "guest": { pos: "n.", en_def: "a person who is invited to visit or stay", cn_def: "客人" },
  "homemade": { pos: "adj.", en_def: "made at home, not bought from a store", cn_def: "自製的" },
  "homework": { pos: "n.", en_def: "school work done at home", cn_def: "作業" },
  "kindly": { pos: "adv.", en_def: "in a kind, helpful way", cn_def: "親切地" },
  "lined": { pos: "v.", en_def: "stood in a row, one after another", cn_def: "排隊（過去式）" },
  "loudly": { pos: "adv.", en_def: "in a loud way; not quietly", cn_def: "大聲地" },
  "lunar": { pos: "adj.", en_def: "related to the moon, as in the Lunar calendar", cn_def: "農曆的" },
  "mall": { pos: "n.", en_def: "a large building with many shops inside", cn_def: "購物中心" },
  "math": { pos: "n.", en_def: "the subject of numbers and calculations", cn_def: "數學" },
  "meeting": { pos: "n.", en_def: "a gathering of people to discuss something", cn_def: "會議" },
  "memory": { pos: "n.", en_def: "the ability to remember things", cn_def: "記憶力" },
  "modern": { pos: "adj.", en_def: "relating to the present time, not the past", cn_def: "現代的" },
  "morning": { pos: "n.", en_def: "the early part of the day", cn_def: "早上" },
  "natural": { pos: "adj.", en_def: "existing in nature, not made by people", cn_def: "自然的" },
  "neighbor": { pos: "n.", en_def: "a person who lives near you", cn_def: "鄰居" },
  "neighborhood": { pos: "n.", en_def: "the area around where you live", cn_def: "社區；鄰里" },
  "neighbors": { pos: "n.", en_def: "people who live near you", cn_def: "鄰居（複數）" },
  "new": { pos: "adj.", en_def: "recently made, bought, or arrived", cn_def: "新的" },
  "novel": { pos: "n.", en_def: "a long written story, usually fiction", cn_def: "小說" },
  "office": { pos: "n.", en_def: "a room or building where people do business work", cn_def: "辦公室" },
  "older": { pos: "adj.", en_def: "having lived or existed for more years than another", cn_def: "較年長的" },
  "organized": { pos: "v.", en_def: "planned and arranged something", cn_def: "組織；籌辦（過去式）" },
  "patiently": { pos: "adv.", en_def: "in a calm way without getting upset, while waiting", cn_def: "耐心地" },
  "pencil": { pos: "n.", en_def: "a thin tool used for writing or drawing", cn_def: "鉛筆" },
  "photos": { pos: "n.", en_def: "pictures taken with a camera", cn_def: "照片（複數）" },
  "piano": { pos: "n.", en_def: "a large musical instrument with black and white keys", cn_def: "鋼琴" },
  "players": { pos: "n.", en_def: "people who take part in a game or sport", cn_def: "選手（複數）" },
  "post office": { pos: "n.", en_def: "a place where letters and packages are sent", cn_def: "郵局" },
  "prize": { pos: "n.", en_def: "something given to a winner", cn_def: "獎品" },
  "proudly": { pos: "adv.", en_def: "in a way that shows pride or satisfaction", cn_def: "驕傲地" },
  "question": { pos: "n.", en_def: "something asked in order to get information", cn_def: "問題" },
  "received": { pos: "v.", en_def: "got something that was given", cn_def: "收到（過去式）" },
  "ride": { pos: "n.", en_def: "a machine at an amusement park that people sit on for fun", cn_def: "遊樂設施" },
  "robotics": { pos: "n.", en_def: "the study or building of robots", cn_def: "機器人學" },
  "runs": { pos: "v.", en_def: "manages or operates something, like a business", cn_def: "經營" },
  "school": { pos: "n.", en_def: "a place where children go to learn", cn_def: "學校" },
  "scientists": { pos: "n.", en_def: "people who study science", cn_def: "科學家（複數）" },
  "seat": { pos: "n.", en_def: "a place to sit", cn_def: "座位" },
  "shop": { pos: "n.", en_def: "a small store that sells things", cn_def: "商店" },
  "shopping": { pos: "n.", en_def: "the activity of buying things", cn_def: "購物" },
  "signed": { pos: "v.", en_def: "wrote one's name on a document", cn_def: "簽名（過去式）" },
  "singing": { pos: "n.", en_def: "the activity of making music with the voice", cn_def: "唱歌" },
  "soccer": { pos: "n.", en_def: "a sport played by kicking a ball into a goal", cn_def: "足球" },
  "station": { pos: "n.", en_def: "a place where trains or buses stop", cn_def: "車站" },
  "storybook": { pos: "n.", en_def: "a book containing stories, usually for children", cn_def: "故事書" },
  "student": { pos: "n.", en_def: "a person who is studying at a school", cn_def: "學生" },
  "students": { pos: "n.", en_def: "people who study at a school", cn_def: "學生（複數）" },
  "taipei": { pos: "n.", en_def: "the capital city of Taiwan", cn_def: "台北" },
  "tall": { pos: "adj.", en_def: "having a greater than average height", cn_def: "高的" },
  "taught": { pos: "v.", en_def: "gave lessons to someone (past tense of teach)", cn_def: "教導（過去式）" },
  "teacher": { pos: "n.", en_def: "a person whose job is to teach", cn_def: "老師" },
  "teachers": { pos: "n.", en_def: "people whose job is to teach", cn_def: "老師（複數）" },
  "team": { pos: "n.", en_def: "a group of people playing or working together", cn_def: "隊伍" },
  "teenagers": { pos: "n.", en_def: "young people between thirteen and nineteen", cn_def: "青少年（複數）" },
  "toy": { pos: "n.", en_def: "an object that children play with", cn_def: "玩具" },
  "train": { pos: "n.", en_def: "a long vehicle that runs on tracks", cn_def: "火車" },
  "trains": { pos: "n.", en_def: "long vehicles that run on tracks", cn_def: "火車（複數）" },
  "traveled": { pos: "v.", en_def: "went from one place to another", cn_def: "旅行；前往（過去式）" },
  "trip": { pos: "n.", en_def: "a journey to a place", cn_def: "旅行" },
  "turned": { pos: "v.", en_def: "reached a certain age", cn_def: "滿（…歲）" },
  "twelve": { pos: "n.", en_def: "the number 12", cn_def: "十二" },
  "uniquely": { pos: "adv.", en_def: "in a way that is special to one thing only", cn_def: "獨特地" },
  "vacation": { pos: "n.", en_def: "a period of time away from school or work for rest", cn_def: "假期" },
  "wallet": { pos: "n.", en_def: "a small case used to carry money and cards", cn_def: "錢包" },
  "warmly": { pos: "adv.", en_def: "in a friendly and kind way", cn_def: "熱情地" },
  "wedding": { pos: "n.", en_def: "a ceremony where two people get married", cn_def: "婚禮" },
  "weekends": { pos: "n.", en_def: "the days of Saturday and Sunday", cn_def: "週末（複數）" },
  "welcomed": { pos: "v.", en_def: "greeted someone in a friendly way", cn_def: "歡迎（過去式）" },
  "won": { pos: "v.", en_def: "got first place in a contest (past tense of win)", cn_def: "獲勝（過去式）" },
  "young": { pos: "adj.", en_def: "having lived only a short time; not old", cn_def: "年輕的" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});

// ---- Plural aliases so MCQ option lookups (e.g. "adults", "children") resolve correctly ----
const PLURAL_ALIASES = {
  "adults": "adult", "babies": "baby", "relatives": "relative",
  "kids": "kid", "boys": "boy", "girls": "girl", "men": "man", "women": "woman",
  "sons": "son", "daughters": "daughter", "brothers": "brother", "sisters": "sister",
  "cousins": "cousin", "uncles": "uncle", "aunts": "aunt", "nephews": "nephew",
  "nieces": "niece", "parents": "parent"
};
Object.keys(PLURAL_ALIASES).forEach(plural => {
  const singular = PLURAL_ALIASES[plural];
  if (!LOOKUP[plural] && LOOKUP[singular]) {
    LOOKUP[plural] = LOOKUP[singular];
  }
});
