// ============================================================
// Group 11 Quiz Data: Jobs / Office / Technology / Communication
// Full word set (40 words) — more professions plus office and
// communication technology vocabulary from the "school / work /
// media / communication" theme. School life, Work/Business/
// Money, and Media/Time words will follow as later groups.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 11 - Jobs / Office / Technology / Communication (職業/辦公室/科技/通訊)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (40 words) ----
const VOCAB = [
  { word: "student", pos: "n.", cn_def: "學生", en_def: "a person who is studying at a school or college",
    sentence: "Every {{BLANK}} in the class received a new textbook on the first day.",
    cn: "班上的每個學生在開學第一天都收到了一本新的課本。" },
  { word: "police", pos: "n.", cn_def: "警察", en_def: "the official group of people who keep order and enforce laws",
    sentence: "When the alarm went off, someone immediately called the {{BLANK}} for help.",
    cn: "警報響起時，有人立刻打電話叫警察來幫忙。" },
  { word: "soldier", pos: "n.", cn_def: "士兵", en_def: "a person who serves in an army",
    sentence: "The young {{BLANK}} wrote a letter home to his family every single week.",
    cn: "那位年輕的士兵每個星期都會寫一封信給家人。" },
  { word: "driver", pos: "n.", cn_def: "司機", en_def: "a person who operates a vehicle, such as a car or bus",
    sentence: "The bus {{BLANK}} stopped at every corner to let passengers get on and off.",
    cn: "公車司機在每個轉角都停車，讓乘客上下車。" },
  { word: "captain", pos: "n.", cn_def: "隊長", en_def: "the leader of a team or a ship",
    sentence: "Our basketball team's {{BLANK}} called everyone together before the championship game.",
    cn: "我們籃球隊的隊長在冠軍賽前把大家叫到一起。" },
  { word: "cowboy", pos: "n.", cn_def: "牛仔", en_def: "a man who works with cattle on a ranch, often riding a horse",
    sentence: "In the old movie, a brave {{BLANK}} rode across the desert on his horse.",
    cn: "在那部老電影裡，一位勇敢的牛仔騎著馬穿越沙漠。" },
  { word: "farmer", pos: "n.", cn_def: "農夫", en_def: "a person who grows crops or raises animals for a living",
    sentence: "The {{BLANK}} woke up before sunrise to feed the animals on his farm.",
    cn: "那位農夫在日出前就起床去餵農場裡的動物。" },
  { word: "fisherman", pos: "n.", cn_def: "漁夫", en_def: "a person whose job is to catch fish",
    sentence: "The old {{BLANK}} sailed out to sea every morning before the sun rose.",
    cn: "那位老漁夫每天早上太陽升起前就出海了。" },
  { word: "barber", pos: "n.", cn_def: "理髮師", en_def: "a person whose job is to cut men's hair",
    sentence: "My father visits the same {{BLANK}} every month for a haircut.",
    cn: "我爸爸每個月都會去同一位理髮師那裡剪頭髮。" },
  { word: "hairdresser", pos: "n.", cn_def: "美髮師", en_def: "a person whose job is to cut and style hair",
    sentence: "The {{BLANK}} gave my sister a new haircut before her graduation ceremony.",
    cn: "那位美髮師在我姐姐的畢業典禮前幫她剪了新髮型。" },
  { word: "shopkeeper", pos: "n.", cn_def: "店主", en_def: "a person who owns or manages a small shop",
    sentence: "The friendly {{BLANK}} always remembers what each regular customer likes to buy.",
    cn: "那位友善的店主總是記得每位常客喜歡買什麼東西。" },
  { word: "vendor", pos: "n.", cn_def: "小販", en_def: "a person who sells things, often outdoors or on the street",
    sentence: "A street {{BLANK}} sold fresh fruit from a small cart near the school gate.",
    cn: "一位街頭小販在學校門口附近用小推車賣新鮮水果。" },
  { word: "salesman", pos: "n.", cn_def: "推銷員", en_def: "a man whose job is to sell products",
    sentence: "The {{BLANK}} explained every feature of the new phone patiently to the customer.",
    cn: "那位推銷員耐心地向顧客解釋了新手機的每個功能。" },
  { word: "waiter", pos: "n.", cn_def: "服務生", en_def: "a man who serves food in a restaurant",
    sentence: "The {{BLANK}} recommended the seafood pasta as the restaurant's most popular dish.",
    cn: "那位服務生推薦海鮮義大利麵，說那是這家餐廳最受歡迎的菜。" },
  { word: "waitress", pos: "n.", cn_def: "女服務生", en_def: "a woman who serves food in a restaurant",
    sentence: "The {{BLANK}} brought our drinks quickly and smiled warmly at every table.",
    cn: "那位女服務生很快就送來我們的飲料，並對每一桌都熱情微笑。" },
  { word: "mail carrier", pos: "n.", cn_def: "郵差", en_def: "a person whose job is to deliver letters and packages",
    sentence: "The {{BLANK}} delivers packages to our neighborhood every afternoon around three o'clock.",
    cn: "郵差每天下午大約三點都會把包裹送到我們的社區。" },
  { word: "mailman", pos: "n.", cn_def: "郵差", en_def: "a man whose job is to deliver letters and packages",
    sentence: "Our friendly {{BLANK}} always waves and says hello when he passes our house.",
    cn: "我們友善的郵差每次經過我們家時都會揮手打招呼。" },
  { word: "worker", pos: "n.", cn_def: "工人", en_def: "a person who works, especially at a job that involves physical effort",
    sentence: "A construction {{BLANK}} carefully carried the heavy bricks up the tall ladder.",
    cn: "一位建築工人小心地把沉重的磚塊搬上高高的梯子。" },
  { word: "mechanic", pos: "n.", cn_def: "技工", en_def: "a person whose job is to repair machines, especially cars",
    sentence: "The {{BLANK}} quickly found the problem and fixed our car's engine that afternoon.",
    cn: "那位技工很快就找到問題，並在那天下午修好了我們汽車的引擎。" },
  { word: "painter", pos: "n.", cn_def: "油漆工", en_def: "a person whose job is to paint walls, houses, or buildings",
    sentence: "The {{BLANK}} spent three days giving our entire house a fresh coat of white paint.",
    cn: "那位油漆工花了三天時間幫我們整個房子重新刷上白色油漆。" },
  { word: "baby sitter", pos: "n.", cn_def: "保母", en_def: "a person who is paid to take care of children for a short time",
    sentence: "My parents hired a {{BLANK}} so they could go out for dinner on Saturday night.",
    cn: "我父母請了一位保母，這樣他們星期六晚上就能出去吃晚餐。" },
  { word: "housewife", pos: "n.", cn_def: "家庭主婦", en_def: "a woman who manages the home and family instead of having an outside job",
    sentence: "As a busy {{BLANK}}, she cooks, cleans, and takes care of three young children every day.",
    cn: "作為一位忙碌的家庭主婦，她每天都要做飯、打掃，並照顧三個年幼的孩子。" },
  { word: "office", pos: "n.", cn_def: "辦公室", en_def: "a room or building where people do business work",
    sentence: "My mother works in a tall building with her {{BLANK}} on the twentieth floor.",
    cn: "我媽媽在一棟高樓裡工作，她的辦公室在二十樓。" },
  { word: "department", pos: "n.", cn_def: "部門", en_def: "a part of a large organization that handles a specific area of work",
    sentence: "My uncle works in the sales {{BLANK}} of a large electronics company.",
    cn: "我叔叔在一家大型電子公司的銷售部門工作。" },
  { word: "chart", pos: "n.", cn_def: "圖表", en_def: "a drawing that shows information using lines, bars, or shapes",
    sentence: "The teacher drew a colorful {{BLANK}} on the board to explain the weather patterns.",
    cn: "老師在黑板上畫了一張色彩鮮豔的圖表來解釋天氣的模式。" },
  { word: "form", pos: "n.", cn_def: "表格", en_def: "a document with blank spaces for writing in information",
    sentence: "Before the trip, every student had to fill out a permission {{BLANK}}.",
    cn: "在這次旅行之前，每位學生都必須填寫一份許可表格。" },
  { word: "list", pos: "n.", cn_def: "清單", en_def: "a set of names, numbers, or items written one after another",
    sentence: "My mother wrote a shopping {{BLANK}} before we went to the supermarket together.",
    cn: "我媽媽在我們一起去超市之前寫了一份購物清單。" },
  { word: "copy", pos: "n.", cn_def: "副本", en_def: "a version of something made to look exactly like the original",
    sentence: "The teacher gave each student a {{BLANK}} of the worksheet before the quiz.",
    cn: "老師在小考前給每位學生一份練習卷的副本。" },
  { word: "e-mail", pos: "n.", cn_def: "電子郵件", en_def: "a message sent electronically over the Internet",
    sentence: "My teacher sent an {{BLANK}} to remind everyone about tomorrow's field trip.",
    cn: "我老師發了一封電子郵件來提醒大家明天的校外教學。" },
  { word: "mail", pos: "n.", cn_def: "郵件", en_def: "letters and packages sent through the postal service",
    sentence: "We checked the {{BLANK}}box every afternoon, hoping for a letter from grandma.",
    cn: "我們每天下午都會檢查信箱，希望能收到奶奶寄來的信。" },
  { word: "letter", pos: "n.", cn_def: "信件", en_def: "a written message sent to a person, usually by mail",
    sentence: "She wrote a long {{BLANK}} to her best friend who had moved overseas.",
    cn: "她寫了一封長信給搬到國外的最好朋友。" },
  { word: "message", pos: "n.", cn_def: "口信", en_def: "a short piece of information sent to someone",
    sentence: "My mother left a {{BLANK}} on the kitchen table telling me dinner was in the fridge.",
    cn: "我媽媽在廚房餐桌上留了一張口信，告訴我晚餐在冰箱裡。" },
  { word: "file", pos: "n.", cn_def: "文件夾", en_def: "a folder or collection of documents kept together",
    sentence: "The secretary organized every important paper into a labeled {{BLANK}}.",
    cn: "秘書把每份重要文件都整理進有標籤的文件夾裡。" },
  { word: "information", pos: "n.", cn_def: "資訊", en_def: "facts or details that someone learns or is told",
    sentence: "The librarian helped me find useful {{BLANK}} for my history report.",
    cn: "圖書館員幫我找到了寫歷史報告所需的有用資訊。" },
  { word: "knowledge", pos: "n.", cn_def: "知識", en_def: "the things a person knows from learning or experience",
    sentence: "My grandfather has deep {{BLANK}} about plants from years of gardening.",
    cn: "我爺爺因為多年的園藝經驗，對植物有很深的知識。" },
  { word: "Internet", pos: "n.", cn_def: "網路", en_def: "a global system that connects computers so people can share information",
    sentence: "We searched the {{BLANK}} for information about ancient Egypt for our project.",
    cn: "我們在網路上搜尋了關於古埃及的資訊來做我們的專案。" },
  { word: "link", pos: "n.", cn_def: "連結", en_def: "something that connects one webpage or piece of information to another",
    sentence: "My teacher shared a {{BLANK}} to the online quiz in our class group chat.",
    cn: "我老師在我們的班級群組裡分享了線上小考的連結。" },
  { word: "computer", pos: "n.", cn_def: "電腦", en_def: "an electronic machine used to store and process information",
    sentence: "My brother uses his {{BLANK}} every night to finish his online homework.",
    cn: "我哥哥每天晚上都用他的電腦完成線上作業。" },
  { word: "screen", pos: "n.", cn_def: "螢幕", en_def: "the flat surface on a device where images and text appear",
    sentence: "The {{BLANK}} on my old laptop cracked after it fell off the desk.",
    cn: "我那台舊筆電的螢幕在掉下桌子後裂開了。" },
  { word: "printer", pos: "n.", cn_def: "印表機", en_def: "a machine that puts text or images from a computer onto paper",
    sentence: "The office {{BLANK}} ran out of ink right before the important meeting.",
    cn: "辦公室的印表機在重要會議前剛好沒墨水了。" }
];

// ---- Part 2 data: 40 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (10 each), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "On the first day of school, every learner received something new from the teacher. Each ______ got a brand-new textbook.",
    options: ["student","worker","driver","captain"], answer: 0, vocabIndex: 0 },
  { q: "When the alarm in the building suddenly went off, someone acted quickly for safety. A neighbor immediately called the ______ for help.",
    options: ["soldier","mechanic","vendor","police"], answer: 3, vocabIndex: 1 },
  { q: "Every week, a young person serving in the army wrote home with news. The ______ always mailed his letter on the same day.",
    options: ["soldier","worker","farmer","painter"], answer: 0, vocabIndex: 2 },
  { q: "At every corner, the same person stopped the bus to let people on and off. Our regular ______ knew everyone's stop by heart.",
    options: ["captain","mechanic","salesman","driver"], answer: 3, vocabIndex: 3 },
  { q: "Before the championship game, someone gathered the whole basketball team together for a talk. Our team ______ spoke confidently to everyone.",
    options: ["worker","driver","captain","farmer"], answer: 2, vocabIndex: 4 },
  { q: "In the old western movie, a brave figure rode his horse straight across the desert. The lone ______ never seemed afraid.",
    options: ["soldier","hunter","driver","cowboy"], answer: 3, vocabIndex: 5 },
  { q: "Every morning before sunrise, someone on the farm fed all the animals first. The hardworking ______ never slept in late.",
    options: ["worker","vendor","farmer","mechanic"], answer: 2, vocabIndex: 6 },
  { q: "Each morning before the sun rose, someone sailed far out into the ocean. The experienced ______ always returned home by evening.",
    options: ["sailor","captain","soldier","fisherman"], answer: 3, vocabIndex: 7 },
  { q: "Once a month, my father visits the exact same shop near our home. The friendly ______ always gives him the same haircut.",
    options: ["salesman","barber","shopkeeper","vendor"], answer: 1, vocabIndex: 8 },
  { q: "Before her big graduation ceremony, my sister wanted to look especially nice. The ______ gave her a stylish new haircut that morning.",
    options: ["barber","painter","hairdresser","salesman"], answer: 2, vocabIndex: 9 },
  { q: "At the small shop near our house, the same person always remembers every regular customer's order. The kind ______ greets everyone warmly.",
    options: ["vendor","shopkeeper","waiter","mechanic"], answer: 1, vocabIndex: 10 },
  { q: "Near the school gate, someone sold fresh fruit from a small cart every single morning. The cheerful ______ knew most of the students.",
    options: ["shopkeeper","farmer","vendor","salesman"], answer: 2, vocabIndex: 11 },
  { q: "At the electronics store, someone patiently explained every single feature of the newest phone. The helpful ______ never seemed in a rush.",
    options: ["salesman","shopkeeper","vendor","mechanic"], answer: 0, vocabIndex: 12 },
  { q: "At the busy restaurant, someone recommended the seafood pasta as the most popular dish that night. The friendly ______ smiled at every table.",
    options: ["chef","host","waiter","cook"], answer: 2, vocabIndex: 13 },
  { q: "She brought our drinks quickly and smiled warmly at every single table in the restaurant. That cheerful ______ made the evening pleasant.",
    options: ["host","waitress","guest","manager"], answer: 1, vocabIndex: 14 },
  { q: "Every afternoon around three o'clock, packages and letters arrive at every house in our neighborhood. The reliable ______ never misses a delivery.",
    options: ["salesman","vendor","mail carrier","driver"], answer: 2, vocabIndex: 15 },
  { q: "Our friendly neighborhood delivery worker always waves and says hello while passing our house. Everyone on the street knows the kind ______.",
    options: ["mailman","driver","vendor","farmer"], answer: 0, vocabIndex: 16 },
  { q: "At the busy construction site, someone carefully carried heavy bricks up a tall ladder all day. The strong ______ never stopped working.",
    options: ["farmer","soldier","worker","captain"], answer: 2, vocabIndex: 17 },
  { q: "Our car suddenly stopped working on the way home, so we called for professional help. The skilled ______ fixed the engine within an hour.",
    options: ["driver","worker","painter","mechanic"], answer: 3, vocabIndex: 18 },
  { q: "For three full days, someone gave our entire house a fresh, bright coat of paint. The hardworking ______ finished just before our guests arrived.",
    options: ["painter","worker","mechanic","farmer"], answer: 0, vocabIndex: 19 },
  { q: "On Saturday night, my parents wanted to go out for a quiet dinner together. They hired a trusted ______ to watch us at home.",
    options: ["nurse","guest","teacher","baby sitter"], answer: 3, vocabIndex: 20 },
  { q: "Every single day, someone at home cooks, cleans, and takes care of three young children. As a busy ______, she rarely gets to rest.",
    options: ["babysitter","manager","housewife","teacher"], answer: 2, vocabIndex: 21 },
  { q: "My mother works on the twentieth floor of a very tall building downtown. Her ______ has a beautiful view of the entire city.",
    options: ["school","department","store","office"], answer: 3, vocabIndex: 22 },
  { q: "My uncle has worked at the same large electronics company for many years now. He works in the sales ______ on the third floor.",
    options: ["office","department","company","factory"], answer: 1, vocabIndex: 23 },
  { q: "To explain the weather patterns clearly, the teacher used something visual on the whiteboard. The colorful ______ showed temperature changes all month.",
    options: ["list","form","copy","chart"], answer: 3, vocabIndex: 24 },
  { q: "Before the class trip could happen, every parent needed to provide written permission. Each student handed in a signed permission ______.",
    options: ["form","letter","list","file"], answer: 0, vocabIndex: 25 },
  { q: "Before heading to the supermarket, my mother always writes down everything we need to buy. That helpful shopping ______ saves us a lot of time.",
    options: ["form","chart","file","list"], answer: 3, vocabIndex: 26 },
  { q: "Right before the quiz began, the teacher handed something to every single student. Each ______ of the worksheet looked exactly the same.",
    options: ["form","copy","list","chart"], answer: 1, vocabIndex: 27 },
  { q: "To remind everyone about tomorrow's field trip, my teacher used a quick electronic message. The ______ arrived in everyone's inbox that evening.",
    options: ["letter","message","e-mail","file"], answer: 2, vocabIndex: 28 },
  { q: "Every afternoon, my family checks a small box outside our house hoping for good news. We were excited to see ______ from grandma finally.",
    options: ["e-mail","mail","message","file"], answer: 1, vocabIndex: 29 },
  { q: "After moving overseas, my best friend still wanted to stay in close touch with me. She wrote a long, heartfelt ______ describing her new life.",
    options: ["e-mail","message","letter","file"], answer: 2, vocabIndex: 30 },
  { q: "Before leaving for work, my mother left something short on the kitchen table for me. Her quick ______ explained where to find dinner.",
    options: ["letter","message","file","copy"], answer: 1, vocabIndex: 31 },
  { q: "The secretary carefully organized every important document into something labeled and easy to find. Each ______ had its own neat folder.",
    options: ["file","copy","list","form"], answer: 0, vocabIndex: 32 },
  { q: "While writing her history report, my sister needed certain useful facts and details. The librarian helped her find exactly the ______ she needed.",
    options: ["knowledge","information","message","file"], answer: 1, vocabIndex: 33 },
  { q: "After years spent gardening, my grandfather understands plants better than almost anyone I know. His deep ______ helps our garden grow beautifully.",
    options: ["knowledge","information","message","skill"], answer: 0, vocabIndex: 34 },
  { q: "For our class project about ancient Egypt, we needed to find a lot of facts quickly. We searched the ______ together after school.",
    options: ["library","textbook","dictionary","Internet"], answer: 3, vocabIndex: 35 },
  { q: "In our class group chat, my teacher shared something we could click to take a quiz. That helpful ______ led straight to the online test.",
    options: ["link","file","message","copy"], answer: 0, vocabIndex: 36 },
  { q: "Every night, my brother sits at his desk to finish his online homework. He could not study without his trusty ______.",
    options: ["printer","computer","screen","phone"], answer: 1, vocabIndex: 37 },
  { q: "After my old laptop fell off the desk, something important on it suddenly cracked. The flat glass ______ never worked properly again.",
    options: ["screen","printer","computer","keyboard"], answer: 0, vocabIndex: 38 },
  { q: "Right before the important meeting started, something in the office stopped working completely. The office ______ had simply run out of ink.",
    options: ["computer","printer","screen","phone"], answer: 1, vocabIndex: 39 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "alarm": { pos: "n.", en_def: "a device or sound that warns people of danger", cn_def: "警報" },
  "ancient": { pos: "adj.", en_def: "very old; from a long time ago", cn_def: "古代的" },
  "basketball": { pos: "n.", en_def: "a sport played with a round ball and a high hoop", cn_def: "籃球" },
  "board": { pos: "n.", en_def: "a flat surface used for writing, like a blackboard", cn_def: "板子；黑板" },
  "brave": { pos: "adj.", en_def: "showing no fear when facing danger", cn_def: "勇敢的" },
  "bricks": { pos: "n.", en_def: "small hard blocks used to build walls", cn_def: "磚塊" },
  "building": { pos: "n.", en_def: "a structure with walls and a roof", cn_def: "建築物" },
  "championship": { pos: "n.", en_def: "a competition to find the best team or player", cn_def: "冠軍賽" },
  "chef": { pos: "n.", en_def: "a professional cook, especially the head cook", cn_def: "主廚" },
  "ceremony": { pos: "n.", en_def: "a formal event held for a special occasion", cn_def: "典禮" },
  "company": { pos: "n.", en_def: "a business that makes or sells things", cn_def: "公司" },
  "construction": { pos: "n.", en_def: "the work of building something, like a house or road", cn_def: "建築工程" },
  "cook": { pos: "n.", en_def: "a person who prepares food, especially as a job", cn_def: "廚師" },
  "corner": { pos: "n.", en_def: "the point where two streets or walls meet", cn_def: "轉角" },
  "desert": { pos: "n.", en_def: "a dry area of land with little rain and few plants", cn_def: "沙漠" },
  "dictionary": { pos: "n.", en_def: "a book that explains the meaning of words", cn_def: "字典" },
  "egypt": { pos: "n.", en_def: "a country in northeastern Africa known for ancient pyramids", cn_def: "埃及" },
  "electronics": { pos: "n.", en_def: "devices that use electronic parts, like phones or computers", cn_def: "電子產品" },
  "engine": { pos: "n.", en_def: "the part of a vehicle that produces power to make it move", cn_def: "引擎" },
  "factory": { pos: "n.", en_def: "a building where goods are made in large numbers", cn_def: "工廠" },
  "fridge": { pos: "n.", en_def: "a machine that keeps food cold", cn_def: "冰箱" },
  "gate": { pos: "n.", en_def: "a movable barrier used to enter or leave an area", cn_def: "大門" },
  "gardening": { pos: "n.", en_def: "the activity of growing and taking care of plants", cn_def: "園藝" },
  "graduation": { pos: "n.", en_def: "the act of finishing school and receiving a diploma", cn_def: "畢業" },
  "guest": { pos: "n.", en_def: "a person who is invited to visit or stay somewhere", cn_def: "客人" },
  "haircut": { pos: "n.", en_def: "the act or style of cutting someone's hair", cn_def: "理髮；髮型" },
  "history": { pos: "n.", en_def: "the study of events that happened in the past", cn_def: "歷史" },
  "homework": { pos: "n.", en_def: "school work done at home", cn_def: "作業" },
  "horse": { pos: "n.", en_def: "a large strong animal that people can ride", cn_def: "馬" },
  "host": { pos: "n.", en_def: "a person who welcomes and takes care of guests", cn_def: "主人" },
  "hunter": { pos: "n.", en_def: "a person who hunts wild animals for food or sport", cn_def: "獵人" },
  "ink": { pos: "n.", en_def: "the colored liquid used for writing or printing", cn_def: "墨水" },
  "keyboard": { pos: "n.", en_def: "a set of keys used to type on a computer", cn_def: "鍵盤" },
  "kitchen": { pos: "n.", en_def: "the room in a house where food is cooked", cn_def: "廚房" },
  "ladder": { pos: "n.", en_def: "a structure with steps used to climb up or down", cn_def: "梯子" },
  "laptop": { pos: "n.", en_def: "a small portable computer", cn_def: "筆記型電腦" },
  "librarian": { pos: "n.", en_def: "a person who works in a library", cn_def: "圖書館員" },
  "library": { pos: "n.", en_def: "a building or room with books for reading or borrowing", cn_def: "圖書館" },
  "manager": { pos: "n.", en_def: "a person who is in charge of a department, store, or team", cn_def: "經理" },
  "meeting": { pos: "n.", en_def: "a gathering of people to discuss something", cn_def: "會議" },
  "neighborhood": { pos: "n.", en_def: "the area around where you live", cn_def: "社區；鄰里" },
  "nurse": { pos: "n.", en_def: "a person trained to care for sick or injured people", cn_def: "護士" },
  "overseas": { pos: "adv.", en_def: "in or to a foreign country, across the sea", cn_def: "在海外" },
  "packages": { pos: "n.", en_def: "boxes or wrapped items sent or delivered", cn_def: "包裹（複數）" },
  "passengers": { pos: "n.", en_def: "people traveling in a vehicle who are not driving", cn_def: "乘客（複數）" },
  "pasta": { pos: "n.", en_def: "an Italian food made from flour, often served with sauce", cn_def: "義大利麵" },
  "patiently": { pos: "adv.", en_def: "in a calm way without getting upset, while waiting", cn_def: "耐心地" },
  "permission": { pos: "n.", en_def: "official approval to do something", cn_def: "許可" },
  "phone": { pos: "n.", en_def: "a device used to talk to people far away", cn_def: "電話" },
  "popular": { pos: "adj.", en_def: "liked or enjoyed by many people", cn_def: "受歡迎的" },
  "project": { pos: "n.", en_def: "a planned piece of work, often for school", cn_def: "專案；作業" },
  "quiz": { pos: "n.", en_def: "a short test of knowledge", cn_def: "小考" },
  "regular": { pos: "adj.", en_def: "happening often, following a usual pattern", cn_def: "固定的；常規的" },
  "report": { pos: "n.", en_def: "a written or spoken account of facts or events", cn_def: "報告" },
  "sailor": { pos: "n.", en_def: "a person who works on a ship", cn_def: "水手" },
  "sales": { pos: "n.", en_def: "the activity of selling goods or services", cn_def: "銷售" },
  "school": { pos: "n.", en_def: "a place where children go to learn", cn_def: "學校" },
  "seafood": { pos: "n.", en_def: "fish and other sea animals eaten as food", cn_def: "海鮮" },
  "secretary": { pos: "n.", en_def: "a person who organizes schedules, letters, and other office tasks", cn_def: "秘書" },
  "skill": { pos: "n.", en_def: "the ability to do something well", cn_def: "技能" },
  "store": { pos: "n.", en_def: "a place where things are sold", cn_def: "商店" },
  "sunrise": { pos: "n.", en_def: "the time in the morning when the sun first appears", cn_def: "日出" },
  "supermarket": { pos: "n.", en_def: "a large store that sells food and household items", cn_def: "超市" },
  "teacher": { pos: "n.", en_def: "a person whose job is to help students learn", cn_def: "老師" },
  "textbook": { pos: "n.", en_def: "a book used for studying a school subject", cn_def: "教科書" },
  "trip": { pos: "n.", en_def: "a journey to a place", cn_def: "旅行" },
  "weather": { pos: "n.", en_def: "the condition of the sky and air, such as rain or sunshine", cn_def: "天氣" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});

// ---- Plural / variant aliases so MCQ option lookups resolve correctly ----
const PLURAL_ALIASES = {
  "babysitter": "baby sitter", "babysitters": "baby sitter", "students": "student",
  "drivers": "driver", "farmers": "farmer", "fishermen": "fisherman", "workers": "worker",
  "mechanics": "mechanic", "painters": "painter", "waiters": "waiter", "waitresses": "waitress",
  "vendors": "vendor", "salesmen": "salesman", "shopkeepers": "shopkeeper",
  "offices": "office", "departments": "department", "charts": "chart", "forms": "form",
  "lists": "list", "copies": "copy", "files": "file", "letters": "letter",
  "messages": "message", "computers": "computer", "screens": "screen", "printers": "printer",
  "links": "link"
};
Object.keys(PLURAL_ALIASES).forEach(plural => {
  const singular = PLURAL_ALIASES[plural];
  if (!LOOKUP[plural] && LOOKUP[singular]) {
    LOOKUP[plural] = LOOKUP[singular];
  }
});
