// ============================================================
// Group 18 Quiz Data: General Adjectives (Part 1)
// Word set (41 words, able-instant) — the first half of the
// "general adjectives" block from the "describing words" theme.
// Continues from Group 17 (Size/State/Safety/Comparison).
// Group 19 will complete the theme with the remaining adjectives.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 18 - General Adjectives Part 1 (一般形容詞 一)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (41 words) ----
const VOCAB = [
  { word: "able", pos: "adj.", cn_def: "有能力的", en_def: "having the skill or power to do something",
    sentence: "After months of practice, she finally felt {{BLANK}} to swim across the entire pool.",
    cn: "經過幾個月的練習，她終於覺得自己有能力游完整個泳池。" },
  { word: "absent", pos: "adj.", cn_def: "缺席的", en_def: "not present; missing from a place",
    sentence: "Three students were {{BLANK}} from class today because of the flu going around school.",
    cn: "今天有三位學生因為學校流行的感冒而缺席。" },
  { word: "active", pos: "adj.", cn_def: "活躍的", en_def: "doing things regularly; full of energy and movement",
    sentence: "My grandmother stays {{BLANK}} by gardening and walking every single morning.",
    cn: "我奶奶每天早上靠園藝和散步保持活躍。" },
  { word: "available", pos: "adj.", cn_def: "可用的", en_def: "able to be used or obtained",
    sentence: "The library checked, but no copies of that popular novel were {{BLANK}} right now.",
    cn: "圖書館查了一下，但那本熱門小說目前沒有任何一本可借。" },
  { word: "boring", pos: "adj.", cn_def: "令人乏味的", en_def: "not interesting; dull",
    sentence: "He thought the documentary about rocks would be {{BLANK}}, but it surprised him.",
    cn: "他原以為這部關於岩石的紀錄片會很無聊，但結果讓他很驚訝。" },
  { word: "born", pos: "adj.", cn_def: "出生的", en_def: "having come into life",
    sentence: "My little cousin was {{BLANK}} on the same day as my grandfather's birthday.",
    cn: "我的小表弟出生的那天正好是我爺爺的生日。" },
  { word: "brave", pos: "adj.", cn_def: "勇敢的", en_def: "showing no fear when facing danger",
    sentence: "The {{BLANK}} firefighter ran into the burning building to rescue the trapped family.",
    cn: "那位勇敢的消防員跑進燃燒的大樓裡救出受困的家庭。" },
  { word: "busy", pos: "adj.", cn_def: "忙碌的", en_def: "having a lot of things to do",
    sentence: "My mother has been so {{BLANK}} this week that she hasn't had time to cook.",
    cn: "我媽媽這週非常忙碌，沒有時間做飯。" },
  { word: "central", pos: "adj.", cn_def: "中心的", en_def: "in or near the middle of something; most important",
    sentence: "The new shopping mall is built in a {{BLANK}} location near the train station.",
    cn: "這座新購物中心建在靠近車站的中心位置。" },
  { word: "certain", pos: "adj.", cn_def: "確定的", en_def: "sure about something; without doubt",
    sentence: "I am {{BLANK}} that I left my umbrella on the bus this morning.",
    cn: "我很確定我今天早上把雨傘留在公車上了。" },
  { word: "classical", pos: "adj.", cn_def: "古典的", en_def: "relating to traditional styles of music, art, or literature",
    sentence: "My piano teacher wants me to learn a {{BLANK}} piece by a famous composer.",
    cn: "我的鋼琴老師要我學一首著名作曲家的古典樂曲。" },
  { word: "clear", pos: "adj.", cn_def: "清楚的", en_def: "easy to see, hear, or understand",
    sentence: "The teacher gave very {{BLANK}} instructions, so nobody had any questions afterward.",
    cn: "老師給的指示非常清楚，所以後來沒有人提問。" },
  { word: "comfortable", pos: "adj.", cn_def: "舒適的", en_def: "providing physical ease and relaxation",
    sentence: "We bought a new {{BLANK}} sofa for the living room last weekend.",
    cn: "我們上週末買了一張新的舒適沙發放在客廳。" },
  { word: "convenient", pos: "adj.", cn_def: "方便的", en_def: "easy or useful for a particular purpose",
    sentence: "Living near the subway station is very {{BLANK}} for getting to school quickly.",
    cn: "住在捷運站附近對快速到達學校來說非常方便。" },
  { word: "crazy", pos: "adj.", cn_def: "瘋狂的", en_def: "acting in a strange or wild way",
    sentence: "It sounds {{BLANK}}, but my uncle once swam across the entire lake before breakfast.",
    cn: "這聽起來很瘋狂，但我叔叔曾在早餐前游過整個湖。" },
  { word: "crowded", pos: "adj.", cn_def: "擁擠的", en_def: "full of people or things, with little space",
    sentence: "The night market gets so {{BLANK}} on weekends that we can barely move.",
    cn: "夜市在週末變得非常擁擠，我們幾乎無法移動。" },
  { word: "cruel", pos: "adj.", cn_def: "殘忍的", en_def: "causing pain or suffering to others on purpose",
    sentence: "It was {{BLANK}} of the older boys to laugh at him for falling down.",
    cn: "那些年長的男孩因為他跌倒而嘲笑他，這樣很殘忍。" },
  { word: "curious", pos: "adj.", cn_def: "好奇的", en_def: "eager to learn or know about something",
    sentence: "My little sister is always {{BLANK}} about how machines work inside.",
    cn: "我妹妹總是對機器內部如何運作感到好奇。" },
  { word: "dear", pos: "adj.", cn_def: "親愛的", en_def: "loved very much; precious to someone",
    sentence: "She begins every letter to her grandmother with the words, \"My {{BLANK}} Grandma.\"",
    cn: "她寫給奶奶的每封信都以「親愛的奶奶」開頭。" },
  { word: "deep", pos: "adj.", cn_def: "深的", en_def: "going far down from the top or surface",
    sentence: "The lifeguard warned swimmers that the water near the rocks was very {{BLANK}}.",
    cn: "救生員警告泳客，岩石附近的水非常深。" },
  { word: "double", pos: "adj.", cn_def: "雙重的", en_def: "twice as much or as many; having two parts",
    sentence: "Because he worked overtime, my father earned {{BLANK}} pay for the holiday shift.",
    cn: "因為加班，我爸爸這次假日班拿到了雙倍的薪水。" },
  { word: "electric", pos: "adj.", cn_def: "電的", en_def: "powered by or relating to electricity",
    sentence: "My family bought an {{BLANK}} car last year to help protect the environment.",
    cn: "我家去年買了一台電動車來幫助保護環境。" },
  { word: "energetic", pos: "adj.", cn_def: "精力充沛的", en_def: "full of energy and enthusiasm",
    sentence: "Even after a long school day, my little brother is still incredibly {{BLANK}}.",
    cn: "即使上了一整天的學，我弟弟依然精力充沛。" },
  { word: "enough", pos: "adj.", cn_def: "充足的", en_def: "as much as is needed",
    sentence: "We didn't have {{BLANK}} chairs for everyone, so two people had to stand.",
    cn: "我們沒有足夠的椅子給每個人坐，所以有兩個人必須站著。" },
  { word: "exciting", pos: "adj.", cn_def: "令人興奮的", en_def: "causing strong feelings of interest or eagerness",
    sentence: "The last few minutes of the soccer match were absolutely {{BLANK}}.",
    cn: "這場足球比賽的最後幾分鐘真是令人興奮。" },
  { word: "extra", pos: "adj.", cn_def: "額外的", en_def: "more than what is usual or expected",
    sentence: "My mother always packs an {{BLANK}} sandwich in case I get hungry later.",
    cn: "我媽媽總是多帶一個三明治，以防我之後餓了。" },
  { word: "fair", pos: "adj.", cn_def: "公平的", en_def: "treating people equally; not favoring one side",
    sentence: "The referee tried to be {{BLANK}} and gave both teams the same number of warnings.",
    cn: "裁判試圖保持公平，給兩隊相同次數的警告。" },
  { word: "famous", pos: "adj.", cn_def: "著名的", en_def: "known by many people",
    sentence: "Our town became {{BLANK}} after a movie was filmed at the old lighthouse.",
    cn: "自從一部電影在那座老燈塔拍攝後，我們的小鎮就變得有名了。" },
  { word: "favorite", pos: "adj.", cn_def: "最喜歡的", en_def: "liked more than any others",
    sentence: "Chocolate ice cream has always been my {{BLANK}} dessert since I was little.",
    cn: "從小到大，巧克力冰淇淋一直是我最喜歡的甜點。" },
  { word: "final", pos: "adj.", cn_def: "最終的", en_def: "happening at the end; last",
    sentence: "Everyone held their breath during the {{BLANK}} round of the spelling competition.",
    cn: "在拼字比賽的最後一輪，大家都緊張地不敢呼吸。" },
  { word: "formal", pos: "adj.", cn_def: "正式的", en_def: "following accepted rules and traditions; not casual",
    sentence: "Students were asked to wear {{BLANK}} clothes for the graduation ceremony photos.",
    cn: "畢業典禮拍照時，學生被要求穿正式服裝。" },
  { word: "former", pos: "adj.", cn_def: "前任的", en_def: "having been something in the past, but not now",
    sentence: "My {{BLANK}} teacher still sends me a card every year on my birthday.",
    cn: "我以前的老師每年生日都還會寄卡片給我。" },
  { word: "frank", pos: "adj.", cn_def: "坦白的", en_def: "honest and direct in what you say",
    sentence: "I appreciate how {{BLANK}} my coach is when giving feedback after every game.",
    cn: "我很欣賞我的教練在每場比賽後給予回饋時的坦白態度。" },
  { word: "fresh", pos: "adj.", cn_def: "新鮮的", en_def: "recently made, grown, or obtained; not old",
    sentence: "My grandmother always uses {{BLANK}} vegetables from her garden in her cooking.",
    cn: "我奶奶煮菜總是用她花園裡新鮮的蔬菜。" },
  { word: "full", pos: "adj.", cn_def: "充滿的", en_def: "containing as much as possible; not empty",
    sentence: "The water bottle was completely {{BLANK}} when I left it on the counter.",
    cn: "我把水壺放在櫥檯上時它是裝滿的。" },
  { word: "gold", pos: "adj.", cn_def: "金色的；金製的", en_def: "made of or colored like gold",
    sentence: "She received a {{BLANK}} medal for finishing first in the swimming race.",
    cn: "她因為在游泳比賽中拿到第一名而獲得了一枚金牌。" },
  { word: "greedy", pos: "adj.", cn_def: "貪婪的", en_def: "wanting more money, food, or things than you need",
    sentence: "The {{BLANK}} dog tried to eat all the treats before the other puppies could have any.",
    cn: "那隻貪心的狗想在其他小狗有機會吃之前把所有零食都吃掉。" },
  { word: "homesick", pos: "adj.", cn_def: "想家的", en_def: "feeling sad because you miss your home",
    sentence: "During her first week studying abroad, she felt very {{BLANK}} and called her parents daily.",
    cn: "她出國留學的第一週感到非常想家，每天都會打電話給父母。" },
  { word: "horrible", pos: "adj.", cn_def: "可怕的", en_def: "very bad or unpleasant",
    sentence: "The smell coming from the garbage can was absolutely {{BLANK}}.",
    cn: "從垃圾桶傳出的氣味實在很可怕。" },
  { word: "independent", pos: "adj.", cn_def: "獨立的", en_def: "able to do things by yourself without help",
    sentence: "After moving away for college, he became much more {{BLANK}} than before.",
    cn: "搬出去上大學後，他變得比以前更獨立了。" },
  { word: "instant", pos: "adj.", cn_def: "即時的", en_def: "happening immediately, without any delay",
    sentence: "She felt an {{BLANK}} connection with her new puppy the moment they met.",
    cn: "她和新養的小狗第一次見面就立刻產生了連結。" }
];

// ---- Part 2 data: 41 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (11/10/10/10), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "After months of swimming lessons every weekend, she gained confidence in the water. She finally felt ______ to swim across the entire pool.",
    options: ["absent","busy","certain","able"], answer: 3, vocabIndex: 0 },
  { q: "A bad flu had been spreading around school all week, keeping many students home in bed. Three classmates were ______ from class today.",
    options: ["active","available","absent","born"], answer: 2, vocabIndex: 1 },
  { q: "Even at her age, my grandmother refuses to sit still and rest all day. She stays ______ by gardening and walking every morning.",
    options: ["absent","active","boring","crowded"], answer: 1, vocabIndex: 2 },
  { q: "I went to the library hoping to borrow a popular new novel everyone was talking about. Unfortunately, no copies were ______ at the time.",
    options: ["available","absent","famous","extra"], answer: 0, vocabIndex: 3 },
  { q: "He expected the documentary about rocks to be a complete waste of time. To his surprise, it turned out to be the opposite of ______.",
    options: ["exciting","fresh","boring","fair"], answer: 2, vocabIndex: 4 },
  { q: "My cousin shares a special connection with our grandfather because of something about their birthdays. He was ______ on the exact same day as our grandfather.",
    options: ["active","born","able","certain"], answer: 1, vocabIndex: 5 },
  { q: "Without hesitating, the firefighter rushed straight into the burning building to save the trapped family inside. Everyone called him incredibly ______ afterward.",
    options: ["energetic","frank","fair","brave"], answer: 3, vocabIndex: 6 },
  { q: "This week, my mother has had back-to-back meetings, errands, and appointments with barely a free moment. She has been far too ______ to cook dinner.",
    options: ["absent","busy","boring","fresh"], answer: 1, vocabIndex: 7 },
  { q: "Builders chose to place the new shopping mall close to the train station for easy access. It sits in a very ______ location for shoppers from all directions.",
    options: ["famous","former","double","central"], answer: 3, vocabIndex: 8 },
  { q: "Searching the bus seat and her bag, she still could not find her umbrella anywhere. She felt completely ______ that she had left it on the bus.",
    options: ["certain","curious","formal","extra"], answer: 0, vocabIndex: 9 },
  { q: "For her next piano lesson, the teacher assigned something written long ago by a well-known composer. She now has to learn a ______ piece for the recital.",
    options: ["electric","classical","instant","gold"], answer: 1, vocabIndex: 10 },
  { q: "Before the test, the teacher repeated the instructions slowly and answered every single question in detail. Her directions were so ______ that nobody felt confused.",
    options: ["formal","frank","deep","clear"], answer: 3, vocabIndex: 11 },
  { q: "Tired of the old, lumpy couch, my family went shopping for something new to relax on. We picked a soft, ______ sofa for the living room.",
    options: ["crowded","comfortable","cruel","double"], answer: 1, vocabIndex: 12 },
  { q: "Choosing where to live, my parents thought about how close everything would be to school and work. Living near the subway station turned out to be very ______.",
    options: ["famous","formal","horrible","convenient"], answer: 3, vocabIndex: 13 },
  { q: "Nobody expected my uncle to do something so unusual before having breakfast one morning. It sounds ______, but he once swam across an entire lake that early.",
    options: ["crazy","fair","frank","deep"], answer: 0, vocabIndex: 14 },
  { q: "On weekend evenings, the local night market fills up with so many shoppers that walking becomes difficult. It gets incredibly ______, leaving almost no space to move.",
    options: ["famous","curious","extra","crowded"], answer: 3, vocabIndex: 15 },
  { q: "When the younger boy slipped and fell on the playground, a group of older boys laughed loudly instead of helping. Everyone agreed their behavior was unkind and ______.",
    options: ["cruel","frank","curious","fair"], answer: 0, vocabIndex: 16 },
  { q: "Whenever my little sister sees a new gadget, she immediately wants to take it apart and see how it works. She has always been extremely ______ about machines.",
    options: ["greedy","boring","curious","horrible"], answer: 2, vocabIndex: 17 },
  { q: "Every letter she writes to her grandmother starts the exact same warm way before any other words follow. She always begins with, \"My ______ Grandma.\"",
    options: ["dear","former","fair","frank"], answer: 0, vocabIndex: 18 },
  { q: "Near the sharp rocks along the shore, the water suddenly drops far below the surface without warning. The lifeguard warned everyone that the area was very ______.",
    options: ["full","deep","fresh","extra"], answer: 1, vocabIndex: 19 },
  { q: "Because he agreed to work extra hours on the holiday, my father's paycheck looked noticeably bigger than usual. He earned ______ pay for taking that shift.",
    options: ["double","extra","instant","gold"], answer: 0, vocabIndex: 20 },
  { q: "Hoping to reduce pollution and save money on fuel, my family chose a vehicle powered differently than most cars. We bought an ______ car last year.",
    options: ["extra","formal","famous","electric"], answer: 3, vocabIndex: 21 },
  { q: "Even after a full day of school followed by soccer practice, my little brother still bounces around the house. He remains incredibly ______ no matter how tired he should be.",
    options: ["energetic","homesick","absent","former"], answer: 0, vocabIndex: 22 },
  { q: "Counting the chairs in the room, we realized there were two more guests than seats available. We simply did not have ______ chairs for everyone.",
    options: ["extra","double","enough","full"], answer: 2, vocabIndex: 23 },
  { q: "During the final minutes of the soccer match, both teams scored quickly and the crowd jumped to their feet cheering. That part of the game felt absolutely ______.",
    options: ["exciting","boring","formal","fair"], answer: 0, vocabIndex: 24 },
  { q: "Worried I might get hungry later in the afternoon, my mother always slips one more item into my lunch box. She packs an ______ sandwich just in case.",
    options: ["instant","extra","former","central"], answer: 1, vocabIndex: 25 },
  { q: "Trying to avoid favoring either side, the referee gave both teams the exact same number of warnings during the match. Players said he had been completely ______.",
    options: ["frank","former","fair","greedy"], answer: 2, vocabIndex: 26 },
  { q: "After a popular movie was filmed at the old lighthouse just outside town, tourists from everywhere began visiting. Our small town suddenly became quite ______.",
    options: ["central","famous","formal","curious"], answer: 1, vocabIndex: 27 },
  { q: "Of all the desserts on the menu, one always catches her eye before anything else does. Chocolate ice cream has been her ______ treat since childhood.",
    options: ["fresh","extra","favorite","fair"], answer: 2, vocabIndex: 28 },
  { q: "As the spelling competition entered its very last stage, the room grew completely silent with tension. Everyone held their breath during the ______ round.",
    options: ["former","final","frank","fair"], answer: 1, vocabIndex: 29 },
  { q: "For graduation photos, the school asked every student to dress neatly instead of wearing casual clothes. Everyone showed up in ______ outfits that day.",
    options: ["former","frank","formal","fresh"], answer: 2, vocabIndex: 30 },
  { q: "Even though she changed schools years ago, a teacher from her old class still remembers her birthday every year. Her ______ teacher sends a card without fail.",
    options: ["formal","frank","fair","former"], answer: 3, vocabIndex: 31 },
  { q: "After every game, the coach gives clear, honest feedback without softening any criticism, which the players actually appreciate. Everyone respects how ______ he always is.",
    options: ["formal","former","frank","fair"], answer: 2, vocabIndex: 32 },
  { q: "My grandmother insists on cooking only with vegetables picked straight from her garden that same morning. She never uses anything except ______ ingredients.",
    options: ["extra","former","double","fresh"], answer: 3, vocabIndex: 33 },
  { q: "I placed the water bottle on the kitchen counter right after filling it to the very top before leaving for school. It was completely ______ when I left it there.",
    options: ["enough","extra","full","deep"], answer: 2, vocabIndex: 34 },
  { q: "After finishing first in the swimming competition, she stood proudly on the podium as the announcer called her name. She received a shiny ______ medal for her win.",
    options: ["gold","fresh","formal","famous"], answer: 0, vocabIndex: 35 },
  { q: "At feeding time, one dog always pushes past the others to grab more treats than its fair share. The other puppies barely get any food because of how ______ it is.",
    options: ["curious","greedy","cruel","fair"], answer: 1, vocabIndex: 36 },
  { q: "During her very first week studying in a new country far from home, she missed her family terribly. She felt extremely ______ and called her parents every day.",
    options: ["curious","energetic","active","homesick"], answer: 3, vocabIndex: 37 },
  { q: "Walking past the overflowing garbage cans behind the restaurant, everyone covered their noses immediately. The smell coming from that area was absolutely ______.",
    options: ["horrible","fresh","fair","famous"], answer: 0, vocabIndex: 38 },
  { q: "After moving away from home to attend college, he learned to cook, clean, and manage money entirely on his own. He quickly became far more ______ than before.",
    options: ["absent","active","independent","curious"], answer: 2, vocabIndex: 39 },
  { q: "The very moment she held her new puppy for the first time, something clicked between them right away. She felt an ______ connection with the little dog.",
    options: ["instant","extra","double","former"], answer: 0, vocabIndex: 40 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "abroad": { pos: "adv.", en_def: "in or to a foreign country", cn_def: "在海外；出國" },
  "absolutely": { pos: "adv.", en_def: "completely; totally", cn_def: "完全地；絕對地" },
  "appreciate": { pos: "v.", en_def: "to be grateful for something", cn_def: "感激；欣賞" },
  "birthday": { pos: "n.", en_def: "the day of the year a person was born", cn_def: "生日" },
  "bottle": { pos: "n.", en_def: "a container for holding liquid", cn_def: "瓶子" },
  "breath": { pos: "n.", en_def: "the air taken into and let out of the lungs", cn_def: "呼吸" },
  "burning": { pos: "adj.", en_def: "on fire", cn_def: "燃燒的" },
  "card": { pos: "n.", en_def: "a piece of stiff paper, often with a greeting or message", cn_def: "卡片" },
  "ceremony": { pos: "n.", en_def: "a formal event held for a special occasion", cn_def: "典禮" },
  "checked": { pos: "v.", en_def: "looked at something to make sure it was correct", cn_def: "查看（過去式）" },
  "college": { pos: "n.", en_def: "a school for higher education after high school", cn_def: "大學" },
  "competition": { pos: "n.", en_def: "an event where people try to win against each other", cn_def: "比賽" },
  "composer": { pos: "n.", en_def: "a person who writes music", cn_def: "作曲家" },
  "connection": { pos: "n.", en_def: "a link or bond between people or things", cn_def: "連結" },
  "documentary": { pos: "n.", en_def: "a film that shows real facts and events", cn_def: "紀錄片" },
  "earned": { pos: "v.", en_def: "got something as a result of work or effort", cn_def: "獲得；賺得（過去式）" },
  "environment": { pos: "n.", en_def: "the natural world, including air, water, and land", cn_def: "環境" },
  "feedback": { pos: "n.", en_def: "comments or advice about how something can be improved", cn_def: "回饋" },
  "filmed": { pos: "v.", en_def: "recorded something using a camera", cn_def: "拍攝（過去式）" },
  "garbage": { pos: "n.", en_def: "waste material that is thrown away", cn_def: "垃圾" },
  "gardening": { pos: "n.", en_def: "the activity of growing and taking care of plants", cn_def: "園藝" },
  "graduation": { pos: "n.", en_def: "the act of finishing school and receiving a diploma", cn_def: "畢業" },
  "ingredients": { pos: "n.", en_def: "items used to make a food or dish", cn_def: "食材" },
  "instructions": { pos: "n.", en_def: "directions on how to do something", cn_def: "指示" },
  "lake": { pos: "n.", en_def: "a large area of water surrounded by land", cn_def: "湖" },
  "lifeguard": { pos: "n.", en_def: "a person who watches swimmers and keeps them safe", cn_def: "救生員" },
  "lighthouse": { pos: "n.", en_def: "a tower with a bright light that guides ships", cn_def: "燈塔" },
  "location": { pos: "n.", en_def: "a particular place or position", cn_def: "位置" },
  "mall": { pos: "n.", en_def: "a large building with many shops inside", cn_def: "購物中心" },
  "market": { pos: "n.", en_def: "a place where food and goods are sold", cn_def: "市場" },
  "match": { pos: "n.", en_def: "a sports game between two players or teams", cn_def: "比賽" },
  "medal": { pos: "n.", en_def: "a small disk given as an award for achievement", cn_def: "獎牌" },
  "outfits": { pos: "n.", en_def: "sets of clothes worn together", cn_def: "服裝" },
  "overtime": { pos: "n.", en_def: "extra time worked beyond the normal schedule", cn_def: "加班時間" },
  "podium": { pos: "n.", en_def: "a small raised platform for a speaker or winner", cn_def: "頒獎台" },
  "puppy": { pos: "n.", en_def: "a baby dog", cn_def: "小狗" },
  "race": { pos: "n.", en_def: "a competition to see who is fastest", cn_def: "比賽" },
  "referee": { pos: "n.", en_def: "a person who makes sure a sports game follows the rules", cn_def: "裁判" },
  "rescue": { pos: "v.", en_def: "to save someone from danger", cn_def: "救援" },
  "shift": { pos: "n.", en_def: "a scheduled period of work", cn_def: "（工作）班次" },
  "sofa": { pos: "n.", en_def: "a long soft seat for more than one person", cn_def: "沙發" },
  "spelling": { pos: "n.", en_def: "the way letters are arranged to form a word", cn_def: "拼字" },
  "subway": { pos: "n.", en_def: "an underground train system in a city", cn_def: "地鐵" },
  "umbrella": { pos: "n.", en_def: "a folding device used to keep dry in the rain", cn_def: "雨傘" },
  "warnings": { pos: "n.", en_def: "statements telling someone of a possible problem or danger", cn_def: "警告" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
