// ============================================================
// Group 32 Quiz Data: Actions, Part 1
// Full word set (36 words) — the first portion of the "actions"
// theme, a 252-word flat list of common verbs that was not yet
// covered by earlier groups. Split into 7 groups of 36 words
// each (Groups 32-38) per the person's request.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 32 - Actions, Part 1 (動作 一)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (36 words) ----
const VOCAB = [
  { word: "eat", pos: "v.", cn_def: "吃", en_def: "to put food in your mouth and swallow it",
    sentence: "We always {{BLANK}} dinner together as a family at seven o'clock.",
    cn: "我們全家總是在七點一起吃晚餐。" },
  { word: "accept", pos: "v.", cn_def: "接受", en_def: "to agree to take or receive something offered",
    sentence: "She happily decided to {{BLANK}} the invitation to her cousin's wedding.",
    cn: "她很高興地決定接受去表姊婚禮的邀請。" },
  { word: "refuse", pos: "v.", cn_def: "拒絕", en_def: "to say no to something offered or requested",
    sentence: "He chose to {{BLANK}} the extra dessert because he was already full.",
    cn: "他選擇拒絕額外的甜點，因為他已經吃飽了。" },
  { word: "reject", pos: "v.", cn_def: "拒絕", en_def: "to refuse to accept, believe, or agree with something",
    sentence: "The committee decided to {{BLANK}} the plan after reviewing it carefully.",
    cn: "委員會在仔細審核後決定拒絕這個計畫。" },
  { word: "appear", pos: "v.", cn_def: "出現", en_def: "to become visible or come into sight",
    sentence: "A bright rainbow began to {{BLANK}} in the sky after the rain stopped.",
    cn: "雨停後，天空開始出現一道明亮的彩虹。" },
  { word: "disappear", pos: "v.", cn_def: "消失", en_def: "to stop being visible; to vanish",
    sentence: "The magician made the coin {{BLANK}} right in front of our eyes.",
    cn: "魔術師讓硬幣就在我們眼前消失了。" },
  { word: "arrive", pos: "v.", cn_def: "到達", en_def: "to reach a place after a journey",
    sentence: "Our flight is scheduled to {{BLANK}} at the airport around midnight.",
    cn: "我們的班機預計在午夜左右抵達機場。" },
  { word: "leave", pos: "v.", cn_def: "離開", en_def: "to go away from a place",
    sentence: "We need to {{BLANK}} the house early to avoid the morning traffic.",
    cn: "我們需要早點離開家，以避免早上的交通堵塞。" },
  { word: "stay", pos: "v.", cn_def: "停留", en_def: "to remain in the same place",
    sentence: "My grandparents always {{BLANK}} with us for the entire summer holiday.",
    cn: "我祖父母總是整個暑假都跟我們住在一起。" },
  { word: "borrow", pos: "v.", cn_def: "借（入）", en_def: "to take something with a promise to return it",
    sentence: "Could I {{BLANK}} your pencil for a moment during the exam?",
    cn: "考試時我可以借用一下你的鉛筆嗎？" },
  { word: "lend", pos: "v.", cn_def: "借（出）", en_def: "to give something to someone for a while",
    sentence: "My brother agreed to {{BLANK}} me his bicycle for the weekend.",
    cn: "我哥哥同意把他的自行車借給我用一個週末。" },
  { word: "carry", pos: "v.", cn_def: "運載", en_def: "to hold and move something from one place to another",
    sentence: "She had to {{BLANK}} three heavy bags up the narrow staircase.",
    cn: "她必須把三個沉重的袋子提上那狹窄的樓梯。" },
  { word: "catch", pos: "v.", cn_def: "抓住", en_def: "to take hold of something moving through the air",
    sentence: "The outfielder ran quickly to {{BLANK}} the ball before it hit the ground.",
    cn: "外野手快速跑去接住那顆球，免得它落地。" },
  { word: "throw", pos: "v.", cn_def: "投擲", en_def: "to send something through the air with your hand",
    sentence: "He used all his strength to {{BLANK}} the ball across the field.",
    cn: "他用盡全力把球扔過整個球場。" },
  { word: "open", pos: "v.", cn_def: "打開", en_def: "to move something so it is no longer closed",
    sentence: "Please {{BLANK}} the window a little so we can let in some fresh air.",
    cn: "請把窗戶打開一點，讓新鮮空氣進來。" },
  { word: "close", pos: "v.", cn_def: "關上", en_def: "to move something so it is no longer open",
    sentence: "Remember to {{BLANK}} the door quietly so you don't wake the baby.",
    cn: "記得輕輕地關門，以免吵醒寶寶。" },
  { word: "go", pos: "v.", cn_def: "去", en_def: "to move or travel from one place to another",
    sentence: "We usually {{BLANK}} to the night market every Friday evening together.",
    cn: "我們通常每週五晚上一起去夜市。" },
  { word: "come", pos: "v.", cn_def: "來", en_def: "to move toward the person speaking",
    sentence: "Please {{BLANK}} to my birthday party this Saturday afternoon if you're free.",
    cn: "如果你有空，請來參加我這週六下午的生日派對。" },
  { word: "damage", pos: "n.", cn_def: "損害", en_def: "harm that reduces the value or quality of something",
    sentence: "The strong typhoon caused serious {{BLANK}} to several old buildings downtown.",
    cn: "強烈的颱風對市區幾棟舊建築造成嚴重損害。" },
  { word: "repair", pos: "v.", cn_def: "修理", en_def: "to fix something that is broken or damaged",
    sentence: "My father spent the whole weekend trying to {{BLANK}} the old bicycle.",
    cn: "我爸爸花了整個週末試圖修理那台舊自行車。" },
  { word: "decrease", pos: "v.", cn_def: "減少", en_def: "to become smaller in size, amount, or number",
    sentence: "The number of students in this small village school continues to {{BLANK}} each year.",
    cn: "這所小村莊學校的學生人數每年持續減少。" },
  { word: "increase", pos: "v.", cn_def: "增加", en_def: "to become larger in size, amount, or number",
    sentence: "Ticket prices for the popular concert are expected to {{BLANK}} next month.",
    cn: "這場熱門演唱會的票價預期下個月會增加。" },
  { word: "upload", pos: "v.", cn_def: "上傳", en_def: "to send data or files from a device to the internet",
    sentence: "She plans to {{BLANK}} the vacation photos to her social media tonight.",
    cn: "她打算今晚把假期照片上傳到她的社群媒體。" },
  { word: "download", pos: "v.", cn_def: "下載", en_def: "to copy data or files from the internet to a device",
    sentence: "It only took a few seconds to {{BLANK}} the new app onto my phone.",
    cn: "把這個新應用程式下載到我手機上只花了幾秒鐘。" },
  { word: "succeed", pos: "v.", cn_def: "成功", en_def: "to achieve a goal or do something successfully",
    sentence: "With years of hard work, she finally managed to {{BLANK}} in her own business.",
    cn: "經過多年的努力，她終於在自己的事業上成功了。" },
  { word: "fail", pos: "v.", cn_def: "失敗", en_def: "to not succeed in doing something",
    sentence: "He was disappointed when he learned he would {{BLANK}} the math test.",
    cn: "他得知自己數學考試會不及格時感到很失望。" },
  { word: "remember", pos: "v.", cn_def: "記得", en_def: "to keep information in your mind or recall it",
    sentence: "I still {{BLANK}} the exact moment we first met at summer camp.",
    cn: "我仍然記得我們在夏令營第一次見面的確切時刻。" },
  { word: "forget", pos: "v.", cn_def: "忘記", en_def: "to fail to remember something",
    sentence: "Please don't {{BLANK}} to bring your umbrella since it might rain later.",
    cn: "請別忘了帶傘，因為晚點可能會下雨。" },
  { word: "gain", pos: "v.", cn_def: "獲得", en_def: "to get or obtain something, often gradually",
    sentence: "Through daily practice, she began to {{BLANK}} more confidence on stage.",
    cn: "透過每天練習，她開始在台上獲得更多自信。" },
  { word: "lose", pos: "v.", cn_def: "失去", en_def: "to no longer have something; to fail to win",
    sentence: "If our team plays carelessly tonight, we might {{BLANK}} the championship game.",
    cn: "如果我們隊今晚打得不夠謹慎，可能會輸掉冠軍賽。" },
  { word: "pull", pos: "v.", cn_def: "拉回", en_def: "to use force to move something toward you",
    sentence: "The children worked together to {{BLANK}} the heavy wagon up the hill.",
    cn: "孩子們一起合作把那輛沉重的小推車拉上山。" },
  { word: "push", pos: "v.", cn_def: "推", en_def: "to use force to move something away from you",
    sentence: "We had to {{BLANK}} the stalled car off the busy road together.",
    cn: "我們必須一起把那輛拋錨的車推離繁忙的道路。" },
  { word: "send", pos: "v.", cn_def: "發送", en_def: "to cause something to go or be delivered somewhere",
    sentence: "I forgot to {{BLANK}} the email before leaving the office yesterday.",
    cn: "我昨天離開辦公室前忘了發送那封電子郵件。" },
  { word: "receive", pos: "v.", cn_def: "收到", en_def: "to get or be given something",
    sentence: "She was thrilled to {{BLANK}} a handwritten letter from her old friend.",
    cn: "她很興奮收到老朋友寄來的一封親筆信。" },
  { word: "turn", pos: "v.", cn_def: "轉動", en_def: "to move around a central point; to change direction",
    sentence: "Please {{BLANK}} left at the next traffic light to reach the museum.",
    cn: "請在下一個紅綠燈左轉以抵達博物館。" },
  { word: "shut", pos: "v.", cn_def: "關閉", en_def: "to close something firmly",
    sentence: "The shopkeeper began to {{BLANK}} the store right at nine o'clock every night.",
    cn: "店主每晚九點整就開始關店。" }
];

// ---- Part 2 data: 36 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~27-34 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// 4 options per question, answer letters balanced across A/B/C/D,
// no adjacent repeats. vocabIndex points to the exact VOCAB entry.
const MCQS = [
  { q: "Gathered around the kitchen table at the exact same time every single evening, this family treats the meal as a daily ritual. We always ______ dinner together as a family at seven o'clock.",
    options: ["eat", "cook", "wash", "serve"], answer: 0, vocabIndex: 0 },
  { q: "Reading the kind invitation card twice with a smile, she felt nothing but excitement about the upcoming celebration. She happily decided to ______ the invitation to her cousin's wedding that weekend.",
    options: ["reject", "accept", "refuse", "forget"], answer: 1, vocabIndex: 1 },
  { q: "Patting his stomach and shaking his head politely, he explained that he simply had no room left. He chose to ______ the extra dessert because he was already completely full.",
    options: ["accept", "receive", "refuse", "gain"], answer: 2, vocabIndex: 2 },
  { q: "After several long meetings spent studying every detail of the proposal, the group reached a final, unanimous decision. The committee decided to ______ the plan after reviewing it very carefully.",
    options: ["repair", "accept", "send", "reject"], answer: 3, vocabIndex: 3 },
  { q: "Colors stretched gracefully across the gray sky just minutes after the storm clouds finally rolled away. A bright rainbow began to ______ in the sky shortly after the rain stopped completely.",
    options: ["appear", "disappear", "increase", "arrive"], answer: 0, vocabIndex: 4 },
  { q: "With a wave of his hand and a confident smile, the performer made the small object vanish instantly. The magician made the coin ______ right in front of our amazed eyes.",
    options: ["appear", "disappear", "increase", "gain"], answer: 1, vocabIndex: 5 },
  { q: "Checking the screen nervously for updates, the tired travelers hoped their long overnight journey would soon be finished. Our flight is scheduled to ______ at the airport around midnight tonight.",
    options: ["leave", "stay", "arrive", "lose"], answer: 2, vocabIndex: 6 },
  { q: "Packing breakfast bags quickly and grabbing coats by the door, the family hurried to avoid the usual morning rush. We need to ______ the house early to avoid the heavy morning traffic.",
    options: ["receive", "catch", "close", "leave"], answer: 3, vocabIndex: 7 },
  { q: "Bringing extra suitcases each July and settling comfortably into the guest room, these visitors clearly enjoy the long break. My grandparents always ______ with us for the entire summer holiday.",
    options: ["stay", "arrive", "leave", "send"], answer: 0, vocabIndex: 8 },
  { q: "Whispering quietly during the quiet exam, a nervous student leaned slightly toward his neighbor's desk for help. Could I ______ your pencil for just a moment during the exam today?",
    options: ["lend", "borrow", "carry", "throw"], answer: 1, vocabIndex: 9 },
  { q: "Wanting his younger sibling to enjoy the trail too, the considerate older brother offered up his own ride for two days. My brother agreed to ______ me his bicycle for the weekend.",
    options: ["borrow", "catch", "lend", "push"], answer: 2, vocabIndex: 10 },
  { q: "Struggling with the awkward weight in both arms, she climbed the narrow stairs one careful step at a time. She had to ______ three heavy bags up the narrow staircase by herself.",
    options: ["throw", "pull", "open", "carry"], answer: 3, vocabIndex: 11 },
  { q: "Sprinting backward across the grass with his glove raised high, the young player kept his eyes locked on the falling ball. The outfielder ran quickly to ______ the ball before it hit the ground.",
    options: ["catch", "throw", "kick", "push"], answer: 0, vocabIndex: 12 },
  { q: "Winding up with both arms before releasing with full force, the determined pitcher sent the ball soaring across the wide field. He used all his strength to ______ the ball across the field.",
    options: ["catch", "throw", "carry", "pull"], answer: 1, vocabIndex: 13 },
  { q: "Feeling the stuffy classroom growing warmer by the minute, several students begged the teacher to let in some fresh air. Please ______ the window a little so we can cool the room down.",
    options: ["close", "shut", "open", "lock"], answer: 2, vocabIndex: 14 },
  { q: "Tiptoeing carefully across the dark nursery floor, the new parents tried hard not to disturb their sleeping infant. Remember to ______ the door quietly so you don't wake the baby up.",
    options: ["open", "throw", "send", "close"], answer: 3, vocabIndex: 15 },
  { q: "Excited for the colorful stalls, sizzling snacks, and bright lanterns, the same group of friends meets at the same spot weekly. We usually ______ to the night market every Friday evening together.",
    options: ["go", "stay", "leave", "arrive"], answer: 0, vocabIndex: 16 },
  { q: "Printed invitations sat ready on the kitchen counter, each one hoping for a cheerful yes from a close friend. Please ______ to my birthday party this Saturday afternoon if you happen to be free.",
    options: ["leave", "come", "go", "send"], answer: 1, vocabIndex: 17 },
  { q: "Roof tiles scattered across the street and broken windows lined the block after the powerful storm finally passed. The strong typhoon caused serious ______ to several old buildings located downtown.",
    options: ["comment", "lack", "damage", "increase"], answer: 2, vocabIndex: 18 },
  { q: "Covered in grease with tools spread across the garage floor, he refused to give up on the stubborn old machine. My father spent the whole weekend trying to ______ the old bicycle.",
    options: ["damage", "waste", "ruin", "repair"], answer: 3, vocabIndex: 19 },
  { q: "Fewer young families choose to remain in the remote countryside each passing year, leaving classrooms emptier than before. The number of students in this small village school continues to ______ every year.",
    options: ["decrease", "increase", "gain", "succeed"], answer: 0, vocabIndex: 20 },
  { q: "Eager fans rushed to buy seats early, knowing that demand for the popular show always drives costs upward. Ticket prices for the popular concert are expected to ______ again next month.",
    options: ["decrease", "increase", "lose", "fail"], answer: 1, vocabIndex: 21 },
  { q: "Scrolling happily through dozens of beach photos from the trip, she picked her favorites to share with everyone online. She plans to ______ the vacation photos to her social media account tonight.",
    options: ["download", "delete", "upload", "send"], answer: 2, vocabIndex: 22 },
  { q: "Tapping the glowing screen just once, the entire program installed itself onto her phone within moments. It only took a few seconds to ______ the new app onto my phone this morning.",
    options: ["upload", "repair", "open", "download"], answer: 3, vocabIndex: 23 },
  { q: "After countless sleepless nights and several failed attempts, her small handmade business finally began to turn a steady profit. With years of hard work, she finally managed to ______ in her own business.",
    options: ["succeed", "fail", "lose", "decrease"], answer: 0, vocabIndex: 24 },
  { q: "Staring blankly at the test paper covered in numbers he barely recognized, his stomach sank with growing dread. He was disappointed when he learned he would ______ the difficult math test.",
    options: ["succeed", "fail", "gain", "win"], answer: 1, vocabIndex: 25 },
  { q: "Closing her eyes for just a second, she could picture the bright campfire and laughter from that summer night perfectly. I still ______ the exact moment we first met at summer camp.",
    options: ["forget", "lose", "remember", "miss"], answer: 2, vocabIndex: 26 },
  { q: "Checking the cloudy sky nervously before leaving, the worried mother called out one last reminder to her son at the door. Please don't ______ to bring your umbrella since it might rain later.",
    options: ["remember", "carry", "lose", "forget"], answer: 3, vocabIndex: 27 },
  { q: "Performing the same piece on stage week after week, the shy young violinist slowly stopped shaking before each show. Through daily practice, she began to ______ more confidence on stage over time.",
    options: ["gain", "lose", "lend", "decrease"], answer: 0, vocabIndex: 28 },
  { q: "One careless mistake during the final minutes of the match could easily cost the exhausted team everything they had worked for. If our team plays carelessly tonight, we might ______ the championship game.",
    options: ["win", "lose", "gain", "succeed"], answer: 1, vocabIndex: 29 },
  { q: "Gripping the rope tightly with both hands, the laughing children leaned backward and dug their heels into the grass. The children worked together to ______ the heavy wagon up the steep hill.",
    options: ["push", "throw", "pull", "carry"], answer: 2, vocabIndex: 30 },
  { q: "Stuck right in the middle of the busy intersection with engines honking impatiently behind them, the drivers needed extra hands fast. We had to ______ the stalled car off the busy road together.",
    options: ["pull", "carry", "lend", "push"], answer: 3, vocabIndex: 31 },
  { q: "Rushing out the door with her coat half on and her bag already over her shoulder, she suddenly remembered the unfinished message. I forgot to ______ the email before leaving the office yesterday.",
    options: ["send", "receive", "open", "close"], answer: 0, vocabIndex: 32 },
  { q: "Recognizing the familiar handwriting on the envelope the moment it arrived, she tore it open with trembling, eager hands. She was thrilled to ______ a handwritten letter from her old friend abroad.",
    options: ["send", "receive", "lend", "borrow"], answer: 1, vocabIndex: 33 },
  { q: "Following the small paper map closely while walking through unfamiliar streets, the tourists searched for the next landmark ahead. Please ______ left at the next traffic light to reach the museum entrance.",
    options: ["stay", "leave", "turn", "shut"], answer: 2, vocabIndex: 34 },
  { q: "Flipping the sign in the window and locking the heavy front door, the tired shopkeeper finally ended another long workday. The shopkeeper began to ______ the store right at nine o'clock every night.",
    options: ["open", "repair", "send", "shut"], answer: 3, vocabIndex: 35 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "abroad": { pos: "adv.", en_def: "in or to a foreign country", cn_def: "在海外；出國" },
  "amazed": { pos: "adj.", en_def: "filled with great surprise or wonder", cn_def: "驚訝的" },
  "awkward": { pos: "adj.", en_def: "difficult to handle or deal with", cn_def: "笨拙的；難處理的" },
  "campfire": { pos: "n.", en_def: "an outdoor fire used for warmth or cooking", cn_def: "營火" },
  "carelessly": { pos: "adv.", en_def: "without paying enough attention", cn_def: "粗心地" },
  "championship": { pos: "n.", en_def: "a competition to find the best team or player", cn_def: "冠軍賽" },
  "cheerful": { pos: "adj.", en_def: "happy and positive", cn_def: "愉快的" },
  "classrooms": { pos: "n.", en_def: "rooms in a school used for teaching", cn_def: "教室（複數）" },
  "coat": { pos: "n.", en_def: "a piece of clothing worn over other clothes for warmth", cn_def: "外套" },
  "comment": { pos: "v.", en_def: "to give an opinion about something", cn_def: "評論" },
  "committee": { pos: "n.", en_def: "a group of people chosen to make decisions", cn_def: "委員會" },
  "confident": { pos: "adj.", en_def: "feeling sure of yourself", cn_def: "有自信的" },
  "considerate": { pos: "adj.", en_def: "thinking about the needs and feelings of others", cn_def: "體貼的" },
  "cook": { pos: "v.", en_def: "to prepare food using heat", cn_def: "烹煮" },
  "costs": { pos: "n.", en_def: "amounts of money needed to buy something", cn_def: "費用（複數）" },
  "countryside": { pos: "n.", en_def: "land outside of cities and towns", cn_def: "鄉村" },
  "delete": { pos: "v.", en_def: "to remove text or data from a device", cn_def: "刪除" },
  "dread": { pos: "n.", en_def: "a strong feeling of fear about something bad happening", cn_def: "恐懼；憂慮" },
  "drivers": { pos: "n.", en_def: "people who operate vehicles", cn_def: "駕駛者（複數）" },
  "envelope": { pos: "n.", en_def: "a paper cover used to hold a letter", cn_def: "信封" },
  "exhausted": { pos: "adj.", en_def: "extremely tired", cn_def: "疲憊不堪的" },
  "garage": { pos: "n.", en_def: "a building where cars are kept or repaired", cn_def: "車庫" },
  "grease": { pos: "n.", en_def: "a thick, oily substance", cn_def: "油污" },
  "guest room": { pos: "n.", en_def: "a bedroom kept for visitors", cn_def: "客房" },
  "handmade": { pos: "adj.", en_def: "made by hand rather than by machine", cn_def: "手工製作的" },
  "handwriting": { pos: "n.", en_def: "writing done by hand, especially someone's personal style", cn_def: "筆跡" },
  "heels": { pos: "n.", en_def: "the back parts of the feet", cn_def: "腳跟（複數）" },
  "honking": { pos: "v.", en_def: "making a loud sound with a car horn", cn_def: "按喇叭（進行式）" },
  "infant": { pos: "n.", en_def: "a very young baby", cn_def: "嬰兒" },
  "installed": { pos: "v.", en_def: "set up software or equipment so it is ready to use", cn_def: "安裝（過去式）" },
  "intersection": { pos: "n.", en_def: "a place where two or more roads meet", cn_def: "十字路口" },
  "kick": { pos: "v.", en_def: "to hit something with the foot", cn_def: "踢" },
  "lack": { pos: "n.", en_def: "the state of not having enough of something", cn_def: "缺乏" },
  "lanterns": { pos: "n.", en_def: "lights that can be carried or hung up", cn_def: "燈籠（複數）" },
  "landmark": { pos: "n.", en_def: "an easily recognized building or feature used to find your way", cn_def: "地標" },
  "lock": { pos: "v.", en_def: "to fasten something with a lock so it cannot be opened", cn_def: "鎖上" },
  "miss": { pos: "v.", en_def: "to fail to hit, catch, or reach something", cn_def: "錯過；未擊中" },
  "neighbor": { pos: "n.", en_def: "a person who lives or sits near you", cn_def: "鄰居" },
  "outfielder": { pos: "n.", en_def: "a baseball player who plays in the outer part of the field", cn_def: "外野手" },
  "performer": { pos: "n.", en_def: "a person who entertains an audience", cn_def: "表演者" },
  "pitcher": { pos: "n.", en_def: "the baseball player who throws the ball to the batter", cn_def: "投手" },
  "profit": { pos: "n.", en_def: "money gained from selling goods or services", cn_def: "利潤" },
  "rainbow": { pos: "n.", en_def: "an arc of colors that appears in the sky after rain", cn_def: "彩虹" },
  "remote": { pos: "adj.", en_def: "far away from cities or other places", cn_def: "偏遠的" },
  "residents": { pos: "n.", en_def: "people who live in a particular place", cn_def: "居民（複數）" },
  "roof": { pos: "n.", en_def: "the covering on top of a building", cn_def: "屋頂" },
  "ruin": { pos: "v.", en_def: "to damage or destroy something completely", cn_def: "毀壞" },
  "sank": { pos: "v.", en_def: "moved downward, as if dropping (past tense of sink)", cn_def: "下沉（過去式）" },
  "serve": { pos: "v.", en_def: "to give food or drink to someone", cn_def: "供應；端上" },
  "shopkeeper": { pos: "n.", en_def: "a person who owns or runs a small store", cn_def: "店主" },
  "soaring": { pos: "v.", en_def: "flying or moving quickly through the air", cn_def: "高飛（進行式）" },
  "sprinting": { pos: "v.", en_def: "running as fast as possible for a short distance", cn_def: "衝刺（進行式）" },
  "stalled": { pos: "adj.", en_def: "stopped working, especially a vehicle's engine", cn_def: "熄火的；故障的" },
  "stomach": { pos: "n.", en_def: "the part of the body where food is digested", cn_def: "胃；肚子" },
  "stubborn": { pos: "adj.", en_def: "refusing to change or work properly", cn_def: "頑固的；難搞的" },
  "stuffy": { pos: "adj.", en_def: "lacking fresh air", cn_def: "悶熱不通風的" },
  "suitcases": { pos: "n.", en_def: "cases used for carrying clothes when traveling", cn_def: "行李箱（複數）" },
  "tiles": { pos: "n.", en_def: "flat pieces used to cover roofs or floors", cn_def: "瓦片；磚（複數）" },
  "tiptoeing": { pos: "v.", en_def: "walking quietly on the toes", cn_def: "踮腳走路（進行式）" },
  "trembling": { pos: "v.", en_def: "shaking slightly, often from fear or excitement", cn_def: "顫抖（進行式）" },
  "typhoon": { pos: "n.", en_def: "a very large, powerful storm with strong winds and rain", cn_def: "颱風" },
  "unanimous": { pos: "adj.", en_def: "agreed on by everyone", cn_def: "一致同意的" },
  "violinist": { pos: "n.", en_def: "a person who plays the violin", cn_def: "小提琴手" },
  "wagon": { pos: "n.", en_def: "a four-wheeled cart used for carrying things", cn_def: "馬車；手推車" },
  "waste": { pos: "v.", en_def: "to use something carelessly without a good result", cn_def: "浪費" },
  "wash": { pos: "v.", en_def: "to clean something with water", cn_def: "洗" },
  "win": { pos: "v.", en_def: "to succeed in a game, contest, or competition", cn_def: "獲勝" },
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
