// ============================================================
// Group 21 Quiz Data: Health / Illness / Senses / Speech
// Full word set (45 words) — health, illness, and senses/speech
// verbs from the "body / health / feelings / clothing /
// appearance" theme. Continues from Group 20 (Body Parts).
// Clothing items will follow as the next group.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 21 - Health / Illness / Senses / Speech (健康/疾病/感官/說話)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (45 words) ----
const VOCAB = [
  { word: "health", pos: "n.", cn_def: "健康", en_def: "the condition of a person's body or mind",
    sentence: "Eating plenty of vegetables every day is good for your overall {{BLANK}}.",
    cn: "每天多吃蔬菜對整體健康有益。" },
  { word: "cancer", pos: "n.", cn_def: "癌症", en_def: "a serious disease in which cells grow out of control",
    sentence: "Doctors caught the {{BLANK}} early, so the treatment worked very well.",
    cn: "醫生早期就發現了癌症，所以治療效果非常好。" },
  { word: "flu", pos: "n.", cn_def: "流感", en_def: "a common illness that causes fever, coughing, and body aches",
    sentence: "Half the class stayed home with the {{BLANK}} during the cold winter week.",
    cn: "在那個寒冷的冬週裡，班上有一半的學生因為流感請假在家。" },
  { word: "cough", pos: "n.", cn_def: "咳嗽", en_def: "a sudden noisy push of air out of the lungs, often from being sick",
    sentence: "His {{BLANK}} kept him awake most of the night.",
    cn: "他的咳嗽讓他幾乎整夜都無法入睡。" },
  { word: "fever", pos: "n.", cn_def: "發燒", en_def: "a body temperature that is higher than normal, often from illness",
    sentence: "The doctor said her {{BLANK}} should go down within a day or two.",
    cn: "醫生說她的發燒應該在一兩天內就會退。" },
  { word: "wound", pos: "n.", cn_def: "傷口", en_def: "an injury to the body, especially a cut",
    sentence: "The nurse carefully cleaned the {{BLANK}} on his knee before wrapping it.",
    cn: "護士在包紮之前小心地清理了他膝蓋上的傷口。" },
  { word: "headache", pos: "n.", cn_def: "頭痛", en_def: "a pain felt inside the head",
    sentence: "Staring at the computer screen all day gave her a terrible {{BLANK}}.",
    cn: "整天盯著電腦螢幕讓她頭痛得很厲害。" },
  { word: "stomachache", pos: "n.", cn_def: "胃痛", en_def: "a pain felt in the stomach",
    sentence: "He got a {{BLANK}} after eating three bowls of ice cream too fast.",
    cn: "他太快吃了三碗冰淇淋後就胃痛了。" },
  { word: "toothache", pos: "n.", cn_def: "牙痛", en_def: "a pain felt in or around a tooth",
    sentence: "A bad {{BLANK}} kept her up all night until she finally saw the dentist.",
    cn: "嚴重的牙痛讓她整夜無法入睡，直到她終於去看了牙醫。" },
  { word: "pain", pos: "n.", cn_def: "疼痛", en_def: "an unpleasant feeling caused by injury or illness",
    sentence: "He felt a sharp {{BLANK}} in his leg after twisting his ankle.",
    cn: "他扭傷腳踝後，腿上感到一陣劇痛。" },
  { word: "dizzy", pos: "adj.", cn_def: "暈眩的", en_def: "feeling like everything is spinning around you",
    sentence: "She felt {{BLANK}} after standing up too quickly from the chair.",
    cn: "她從椅子上太快站起來後感到暈眩。" },
  { word: "healthy", pos: "adj.", cn_def: "健康的", en_def: "having or showing good health",
    sentence: "Regular exercise and good sleep help keep your body {{BLANK}}.",
    cn: "規律運動和充足睡眠有助於保持身體健康。" },
  { word: "well", pos: "adj.", cn_def: "健康的", en_def: "in good health; not sick",
    sentence: "After a week of rest, she finally felt {{BLANK}} enough to return to school.",
    cn: "休息一週後，她終於感覺好到可以回學校了。" },
  { word: "ill", pos: "adj.", cn_def: "生病的", en_def: "not feeling well; sick",
    sentence: "He looked so {{BLANK}} this morning that his mother kept him home from school.",
    cn: "他今天早上看起來很不舒服，所以媽媽讓他留在家裡沒去上學。" },
  { word: "sick", pos: "adj.", cn_def: "生病的", en_def: "feeling unwell or having an illness",
    sentence: "My little brother felt too {{BLANK}} to eat dinner last night.",
    cn: "我弟弟昨晚生病到吃不下晚餐。" },
  { word: "painful", pos: "adj.", cn_def: "疼痛的", en_def: "causing pain or hurting",
    sentence: "Walking on the broken ankle was extremely {{BLANK}} for the young athlete.",
    cn: "對這位年輕運動員來說，用骨折的腳踝走路非常疼痛。" },
  { word: "sore", pos: "adj.", cn_def: "痠痛的", en_def: "painful, especially from being used too much",
    sentence: "Her legs were {{BLANK}} for days after running her very first marathon.",
    cn: "她跑完第一次馬拉松後，雙腿痠痛了好幾天。" },
  { word: "strong", pos: "adj.", cn_def: "強壯的", en_def: "having a lot of physical power",
    sentence: "Years of swimming every morning made him incredibly {{BLANK}}.",
    cn: "多年每天早上游泳讓他變得非常強壯。" },
  { word: "weak", pos: "adj.", cn_def: "虛弱的", en_def: "lacking physical strength or power",
    sentence: "After being sick for a whole week, his legs felt {{BLANK}} when he finally stood up.",
    cn: "生病一整週後，他終於站起來時雙腿感覺虛弱。" },
  { word: "cure", pos: "v.", cn_def: "治癒", en_def: "to make a sick person well again",
    sentence: "Scientists are working hard to {{BLANK}} many diseases that once had no treatment.",
    cn: "科學家正努力研發方法來治癒許多以前無法治療的疾病。" },
  { word: "hurt", pos: "v.", cn_def: "傷害；疼痛", en_def: "to cause pain or injury",
    sentence: "She {{BLANK}} her wrist while trying to catch the falling vase.",
    cn: "她想接住掉落的花瓶時傷到了手腕。" },
  { word: "jam", pos: "v.", cn_def: "擠；卡住", en_def: "to press or squeeze tightly into a space",
    sentence: "Hundreds of people tried to {{BLANK}} into the small subway car during rush hour.",
    cn: "上班尖峰時間，數百人想擠進那輛小小的地鐵車廂裡。" },
  { word: "treat", pos: "v.", cn_def: "治療", en_def: "to try to cure or care for someone who is sick",
    sentence: "The doctor used a new medicine to {{BLANK}} the unusual skin condition.",
    cn: "醫生用一種新藥來治療這個罕見的皮膚狀況。" },
  { word: "operation", pos: "n.", cn_def: "手術", en_def: "a medical procedure to fix or remove something in the body",
    sentence: "The surgeon explained that the {{BLANK}} would take about three hours to complete.",
    cn: "外科醫生解釋這場手術大約需要三個小時才能完成。" },
  { word: "sense", pos: "n.", cn_def: "感官", en_def: "one of the ways the body experiences the world, like sight or hearing",
    sentence: "Dogs have a much stronger {{BLANK}} of smell than humans do.",
    cn: "狗的嗅覺比人類強得多。" },
  { word: "sight", pos: "n.", cn_def: "視力", en_def: "the ability to see",
    sentence: "Her grandmother's {{BLANK}} has gotten weaker over the past few years.",
    cn: "她奶奶的視力在過去幾年裡變弱了。" },
  { word: "voice", pos: "n.", cn_def: "聲音", en_def: "the sound a person makes when speaking or singing",
    sentence: "He recognized his best friend's {{BLANK}} immediately, even over the noisy phone line.",
    cn: "即使在嘈雜的電話線上，他也立刻認出了他最好朋友的聲音。" },
  { word: "blind", pos: "adj.", cn_def: "看不見的", en_def: "unable to see",
    sentence: "The {{BLANK}} man used his cane to carefully find his way down the busy sidewalk.",
    cn: "那位看不見的男士用他的拐杖小心地在繁忙的人行道上找路。" },
  { word: "deaf", pos: "adj.", cn_def: "聽不見的", en_def: "unable to hear",
    sentence: "Since he is {{BLANK}}, he learned to communicate using sign language.",
    cn: "因為他聽不見，所以他學會了用手語溝通。" },
  { word: "dumb", pos: "adj.", cn_def: "不能說話的", en_def: "unable to speak",
    sentence: "The character in the play pretended to be {{BLANK}} so nobody would ask him questions.",
    cn: "劇中的角色假裝不能說話，這樣就沒人會問他問題了。" },
  { word: "hear", pos: "v.", cn_def: "聽見", en_def: "to notice sound using your ears",
    sentence: "Can you {{BLANK}} the birds singing outside the window this morning?",
    cn: "你今天早上能聽到窗外鳥兒唱歌的聲音嗎？" },
  { word: "listen", pos: "v.", cn_def: "聆聽", en_def: "to pay attention to sound on purpose",
    sentence: "Please {{BLANK}} carefully to the instructions before starting the test.",
    cn: "請在開始測驗前仔細聆聽指示。" },
  { word: "see", pos: "v.", cn_def: "看見", en_def: "to notice something using your eyes",
    sentence: "From the top of the tower, we could {{BLANK}} the entire city below.",
    cn: "從塔頂上，我們能看到整座城市。" },
  { word: "look", pos: "v.", cn_def: "看", en_def: "to turn your eyes toward something on purpose",
    sentence: "Please {{BLANK}} both ways carefully before crossing the busy street.",
    cn: "過繁忙的街道前，請小心地向左右看。" },
  { word: "speak", pos: "v.", cn_def: "說話", en_def: "to say words out loud",
    sentence: "She felt nervous the first time she had to {{BLANK}} in front of the whole class.",
    cn: "她第一次必須在全班面前說話時感到很緊張。" },
  { word: "say", pos: "v.", cn_def: "說", en_def: "to express something in words",
    sentence: "He didn't know what to {{BLANK}} when his friend started crying suddenly.",
    cn: "當他的朋友突然哭起來時，他不知道該說什麼。" },
  { word: "talk", pos: "v.", cn_def: "說話", en_def: "to speak with someone; to have a conversation",
    sentence: "My parents like to {{BLANK}} about their day together over dinner every evening.",
    cn: "我父母每天晚餐時都喜歡一起聊聊他們這一天的事。" },
  { word: "tell", pos: "v.", cn_def: "告訴", en_def: "to give information to someone using words",
    sentence: "Could you {{BLANK}} me what time the movie starts tonight?",
    cn: "你可以告訴我今晚電影幾點開始嗎？" },
  { word: "smell", pos: "v.", cn_def: "聞", en_def: "to notice something using your nose",
    sentence: "I could {{BLANK}} fresh cookies baking from all the way down the hallway.",
    cn: "我在走廊另一端就能聞到新鮮餅乾正在烘烤的味道。" },
  { word: "taste", pos: "v.", cn_def: "嚐", en_def: "to notice the flavor of food using your tongue",
    sentence: "She wanted to {{BLANK}} the soup before adding any more salt to it.",
    cn: "她想先嚐嚐湯的味道，再決定要不要加更多鹽。" },
  { word: "bitter", pos: "adj.", cn_def: "苦的", en_def: "having a sharp, unpleasant taste, like black coffee",
    sentence: "The medicine tasted so {{BLANK}} that she needed water right after swallowing it.",
    cn: "那藥嚐起來非常苦，她吞下去後馬上需要喝水。" },
  { word: "sour", pos: "adj.", cn_def: "酸的", en_def: "having a sharp taste, like a lemon",
    sentence: "The green apple was much more {{BLANK}} than he expected.",
    cn: "這顆青蘋果比他預期的酸多了。" },
  { word: "sweet", pos: "adj.", cn_def: "甜的", en_def: "having the taste of sugar",
    sentence: "The cake was so {{BLANK}} that she could only finish half a slice.",
    cn: "這個蛋糕太甜了，她只能吃完半片。" },
  { word: "hungry", pos: "adj.", cn_def: "飢餓的", en_def: "feeling like you need to eat",
    sentence: "By the time dinner was ready, the children were extremely {{BLANK}}.",
    cn: "晚餐準備好的時候，孩子們已經非常飢餓了。" },
  { word: "thirsty", pos: "adj.", cn_def: "口渴的", en_def: "feeling like you need to drink something",
    sentence: "After running in the hot sun for an hour, he felt incredibly {{BLANK}}.",
    cn: "在炎熱的陽光下跑了一個小時後，他感到非常口渴。" }
];

// ---- Part 2 data: 45 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (12/11/11/11), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "Every day, my grandmother reminds me to eat plenty of vegetables and get enough sleep. She says these habits are good for my overall ______.",
    options: ["fever","wound","pain","health"], answer: 3, vocabIndex: 0 },
  { q: "Because doctors discovered the disease in its earliest stage, treatment began right away. Catching the ______ that early made a huge difference for her recovery.",
    options: ["cancer","flu","cough","fever"], answer: 0, vocabIndex: 1 },
  { q: "During the coldest week of winter, half the students stayed home feeling weak and feverish. Most of them had caught the same seasonal ______.",
    options: ["cancer","wound","headache","flu"], answer: 3, vocabIndex: 2 },
  { q: "All through the night, he kept waking up because something in his chest would not stop bothering him. His loud ______ made it impossible to sleep.",
    options: ["fever","wound","cough","pain"], answer: 2, vocabIndex: 3 },
  { q: "Feeling unusually warm all over, she asked her mother to check her temperature with the thermometer. Sure enough, she had a slight ______.",
    options: ["fever","cough","wound","headache"], answer: 0, vocabIndex: 4 },
  { q: "After he scraped his knee badly while skateboarding, the nurse brought out bandages and antiseptic. She carefully cleaned the ______ before covering it up.",
    options: ["fever","cough","wound","pain"], answer: 2, vocabIndex: 5 },
  { q: "After staring at her computer screen for hours without a break, she felt a sharp pain right behind her eyes. That terrible ______ would not go away.",
    options: ["headache","stomachache","toothache","fever"], answer: 0, vocabIndex: 6 },
  { q: "He ate three bowls of ice cream far too quickly at the birthday party. Not long after, an uncomfortable ______ made him regret his choice.",
    options: ["headache","toothache","stomachache","fever"], answer: 2, vocabIndex: 7 },
  { q: "All night long, she could not fall asleep because of a sharp pain near one of her back teeth. The next morning, she finally went to see the dentist about her ______.",
    options: ["headache","toothache","stomachache","wound"], answer: 1, vocabIndex: 8 },
  { q: "After twisting his ankle badly during the soccer game, he immediately felt something unpleasant shoot through his leg. That sharp ______ made it hard to walk.",
    options: ["fever","cough","wound","pain"], answer: 3, vocabIndex: 9 },
  { q: "Standing up too fast from the couch after a long nap, she suddenly felt the room spinning around her. She had to sit back down because she felt so ______.",
    options: ["sore","weak","dizzy","sick"], answer: 2, vocabIndex: 10 },
  { q: "Thanks to regular exercise, good meals, and plenty of sleep every night, his body stayed strong all year. His doctor said he was remarkably ______ for his age.",
    options: ["dizzy","weak","sore","healthy"], answer: 3, vocabIndex: 11 },
  { q: "After staying home from school with a bad cold for an entire week, she finally started feeling like herself again. She told her mother she felt ______ enough to return.",
    options: ["ill","well","sick","weak"], answer: 1, vocabIndex: 12 },
  { q: "This morning, he looked pale and tired, and he barely touched his breakfast before heading back to bed. His mother decided he was too ______ to go to school today.",
    options: ["well","strong","ill","healthy"], answer: 2, vocabIndex: 13 },
  { q: "Last night, my little brother had a stomachache and a slight fever that worried our parents. He felt so ______ that he could not finish his dinner.",
    options: ["healthy","strong","well","sick"], answer: 3, vocabIndex: 14 },
  { q: "The young athlete tried to keep playing despite her broken ankle, but every step made things worse. Walking on it turned out to be incredibly ______ for her.",
    options: ["healthy","strong","painful","well"], answer: 2, vocabIndex: 15 },
  { q: "After finishing her very first marathon, she could barely climb the stairs to her apartment that evening. Her legs stayed ______ for several days afterward.",
    options: ["strong","healthy","well","sore"], answer: 3, vocabIndex: 16 },
  { q: "Every single morning before school, he swims fifty laps in the community pool without fail. Years of this routine have made his whole body incredibly ______.",
    options: ["strong","weak","sore","ill"], answer: 0, vocabIndex: 17 },
  { q: "After spending an entire week sick in bed with barely any food, he finally tried to stand up on his own. His legs felt surprisingly ______ beneath him.",
    options: ["strong","weak","healthy","sore"], answer: 1, vocabIndex: 18 },
  { q: "Researchers around the world spend years studying diseases that once had no known treatment. Their goal is always to find a way to completely ______ these illnesses.",
    options: ["cure","hurt","jam","treat"], answer: 0, vocabIndex: 19 },
  { q: "While reaching quickly to catch a vase that was about to fall off the shelf, she twisted her wrist in an awkward way. She ended up ______ herself slightly in the process.",
    options: ["jamming","curing","hurting","treating"], answer: 2, vocabIndex: 20 },
  { q: "During rush hour at the busy subway station, hundreds of commuters tried to squeeze through the same narrow doorway at once. Everyone seemed determined to ______ themselves inside before the doors closed.",
    options: ["cure","jam","hurt","treat"], answer: 1, vocabIndex: 21 },
  { q: "After examining the strange red spots on her arm carefully, the doctor decided to try a brand-new medicine. She hoped this approach would finally ______ the unusual skin condition successfully.",
    options: ["jam","hurt","treat","cure"], answer: 2, vocabIndex: 22 },
  { q: "Before the surgery began, the surgeon sat down with the worried family to explain exactly what would happen. She said the entire ______ would take roughly three hours.",
    options: ["operation","sense","sight","voice"], answer: 0, vocabIndex: 23 },
  { q: "Scientists have long been amazed at how dogs can detect things humans completely miss using their noses alone. Their incredible ______ of smell is far stronger than that of any person.",
    options: ["sight","sense","voice","operation"], answer: 1, vocabIndex: 24 },
  { q: "Over the past several years, reading small text on menus and signs has become noticeably harder for my grandmother. Her ______ simply is not as sharp as it used to be.",
    options: ["sight","sense","voice","operation"], answer: 0, vocabIndex: 25 },
  { q: "Even though the phone connection was crackling and unclear, he recognized exactly who was calling within just a few seconds. His best friend's familiar ______ was unmistakable, even through the static.",
    options: ["sight","sense","operation","voice"], answer: 3, vocabIndex: 26 },
  { q: "Walking the crowded sidewalk every morning, the man relies on his cane and his sense of touch to guide him. Having been ______ since childhood, he navigates the city with skill.",
    options: ["blind","deaf","dumb","weak"], answer: 0, vocabIndex: 27 },
  { q: "Born unable to hear any sound at all, he grew up learning a different way to communicate with others. Because he is ______, sign language has always been his first language.",
    options: ["blind","deaf","dumb","sick"], answer: 1, vocabIndex: 28 },
  { q: "In the school play, one character avoided every uncomfortable question by acting as though he could not speak at all. He pretended to be ______ so nobody would ask him anything.",
    options: ["blind","deaf","weak","dumb"], answer: 3, vocabIndex: 29 },
  { q: "Lying quietly in bed early one morning, she noticed something pleasant coming through the open window before she even opened her eyes. She could clearly ______ birds singing cheerfully outside.",
    options: ["see","hear","look","smell"], answer: 1, vocabIndex: 30 },
  { q: "Right before the exam began, the teacher asked everyone to put down their pencils and pay close attention. She wanted students to ______ carefully to the instructions first.",
    options: ["listen","hear","see","look"], answer: 0, vocabIndex: 31 },
  { q: "Climbing slowly up the narrow staircase of the old tower, visitors finally reached the very top after several minutes. From up there, they could ______ the whole city spread out below.",
    options: ["hear","listen","smell","see"], answer: 3, vocabIndex: 32 },
  { q: "Before stepping off the sidewalk onto the busy road, every child at the crossing guard's station is taught the same important safety habit. They always ______ both ways carefully first.",
    options: ["see","hear","look","listen"], answer: 2, vocabIndex: 33 },
  { q: "Called to the front of class for her first oral presentation, she felt her hands shaking nervously. It was the first time she had needed to ______ in front of classmates.",
    options: ["talk","tell","say","speak"], answer: 3, vocabIndex: 34 },
  { q: "When his close friend unexpectedly burst into tears at lunch, he froze for a moment, unsure how to react. He genuinely did not know what to ______ in that awkward situation.",
    options: ["tell","say","speak","talk"], answer: 1, vocabIndex: 35 },
  { q: "Every evening after the dishes are cleared away, my parents stay seated at the table a little longer than usual. They enjoy that quiet time to ______ about their day.",
    options: ["say","tell","talk","speak"], answer: 2, vocabIndex: 36 },
  { q: "Curious about their plans for movie night, she texted her older sister to check the schedule before leaving the house. \"Could you ______ me what time the show starts,\" she asked.",
    options: ["talk","tell","speak","say"], answer: 1, vocabIndex: 37 },
  { q: "Walking down the long school hallway on her way to class, something wonderful drifted toward her from the cafeteria kitchen nearby. She could ______ fresh cookies baking from far away.",
    options: ["smell","taste","see","hear"], answer: 0, vocabIndex: 38 },
  { q: "Standing over the pot on the stove, she lifted the spoon carefully to check her cooking before serving it to guests. She wanted to ______ the soup first to check the seasoning.",
    options: ["smell","taste","see","hear"], answer: 1, vocabIndex: 39 },
  { q: "After her little brother insisted on trying the strange black coffee left on the counter, his face twisted up immediately. He had never imagined anything could taste quite so ______.",
    options: ["bitter","sweet","sour","salty"], answer: 0, vocabIndex: 40 },
  { q: "Biting into the green apple she had just picked from the tree, she regretted not waiting a few more days. It was far more ______ than the riper ones nearby.",
    options: ["sweet","bitter","salty","sour"], answer: 3, vocabIndex: 41 },
  { q: "Taking her first bite of the rich chocolate cake at the celebration, she had to slow down halfway through. The dessert was honestly so ______ that she could not finish it all.",
    options: ["sweet","sour","bitter","salty"], answer: 0, vocabIndex: 42 },
  { q: "By the time their mother called everyone in for dinner, all three children had been playing outside for hours without a snack. Each one rushed to the table, clearly very ______.",
    options: ["thirsty","hungry","tired","sleepy"], answer: 1, vocabIndex: 43 },
  { q: "After jogging beneath the midday sun for almost an hour without stopping for water, he ran straight to the nearest fountain when he finished. He had never felt quite so ______.",
    options: ["hungry","tired","thirsty","sleepy"], answer: 2, vocabIndex: 44 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "athlete": { pos: "n.", en_def: "a person who is good at sports", cn_def: "運動員" },
  "ankle": { pos: "n.", en_def: "the joint connecting the foot to the leg", cn_def: "腳踝" },
  "awake": { pos: "adj.", en_def: "not asleep", cn_def: "清醒的" },
  "body": { pos: "n.", en_def: "the whole physical structure of a person or animal", cn_def: "身體" },
  "cane": { pos: "n.", en_def: "a stick used to help with walking", cn_def: "拐杖" },
  "character": { pos: "n.", en_def: "a person in a story, movie, or play", cn_def: "角色" },
  "communicate": { pos: "v.", en_def: "to share information or feelings with someone", cn_def: "溝通" },
  "condition": { pos: "n.", en_def: "the state of a person's health", cn_def: "狀況" },
  "crossing": { pos: "n.", en_def: "a place where people can cross a street safely", cn_def: "穿越道；路口" },
  "dentist": { pos: "n.", en_def: "a person trained to treat teeth and gums", cn_def: "牙醫" },
  "diseases": { pos: "n.", en_def: "illnesses that affect the body", cn_def: "疾病（複數）" },
  "exercise": { pos: "n.", en_def: "physical activity done to stay healthy", cn_def: "運動" },
  "explained": { pos: "v.", en_def: "made something clear or easy to understand", cn_def: "解釋（過去式）" },
  "instructions": { pos: "n.", en_def: "directions on how to do something", cn_def: "指示" },
  "knee": { pos: "n.", en_def: "the joint in the middle of the leg", cn_def: "膝蓋" },
  "language": { pos: "n.", en_def: "a system of words used by people to communicate", cn_def: "語言" },
  "leg": { pos: "n.", en_def: "one of the two long parts of the body used for walking", cn_def: "腿" },
  "marathon": { pos: "n.", en_def: "a long running race, usually over 42 kilometers", cn_def: "馬拉松" },
  "medicine": { pos: "n.", en_def: "a substance used to treat illness", cn_def: "藥" },
  "nurse": { pos: "n.", en_def: "a person trained to care for sick or injured people", cn_def: "護士" },
  "phone": { pos: "n.", en_def: "a device used to talk to people far away", cn_def: "電話" },
  "recognized": { pos: "v.", en_def: "identified someone or something already known", cn_def: "認出（過去式）" },
  "regular": { pos: "adj.", en_def: "happening often, following a usual pattern", cn_def: "規律的" },
  "salt": { pos: "n.", en_def: "a white substance used to add flavor to food", cn_def: "鹽" },
  "salty": { pos: "adj.", en_def: "having the taste of salt", cn_def: "鹹的" },
  "scientists": { pos: "n.", en_def: "people who study science", cn_def: "科學家（複數）" },
  "screen": { pos: "n.", en_def: "the flat surface on a device where images and text appear", cn_def: "螢幕" },
  "signlanguage": { pos: "n.", en_def: "a language using hand movements instead of speech", cn_def: "手語" },
  "skin": { pos: "n.", en_def: "the outer covering of the body", cn_def: "皮膚" },
  "sleepy": { pos: "adj.", en_def: "feeling like you need to sleep", cn_def: "想睡的" },
  "subway": { pos: "n.", en_def: "an underground train system in a city", cn_def: "地鐵" },
  "surgeon": { pos: "n.", en_def: "a doctor who performs operations", cn_def: "外科醫生" },
  "test": { pos: "n.", en_def: "a set of questions used to check knowledge or ability", cn_def: "測驗" },
  "tired": { pos: "adj.", en_def: "feeling like you need rest or sleep", cn_def: "疲倦的" },
  "tower": { pos: "n.", en_def: "a tall narrow building or structure", cn_def: "塔" },
  "treatment": { pos: "n.", en_def: "medical care given to treat an illness or injury", cn_def: "治療" },
  "vase": { pos: "n.", en_def: "a container, often decorative, used to hold flowers", cn_def: "花瓶" },
  "vegetables": { pos: "n.", en_def: "plants or parts of plants eaten as food", cn_def: "蔬菜" },
  "window": { pos: "n.", en_def: "an opening in a wall, usually with glass", cn_def: "窗戶" },
  "wrist": { pos: "n.", en_def: "the joint connecting the hand to the arm", cn_def: "手腕" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});

// ---- Verb-form aliases so MCQ option lookups resolve correctly ----
const VERB_FORM_ALIASES = {
  "hurting": "hurt", "jamming": "jam", "curing": "cure", "treating": "treat"
};
Object.keys(VERB_FORM_ALIASES).forEach(form => {
  const base = VERB_FORM_ALIASES[form];
  if (!LOOKUP[form] && LOOKUP[base]) {
    LOOKUP[form] = LOOKUP[base];
  }
});
