// ============================================================
// Group 38 Quiz Data: Actions, Part 7 (FINAL)
// Full word set (36 words) — the seventh and final portion of
// the "actions" theme (252-word flat verb list). Continues
// from Group 37 (Actions, Part 6). This completes all 252
// words across Groups 32-38.
// Per the person's request, Part 2 MCQ questions use the
// simpler/shorter style introduced in Group 37 (~16-26 words,
// 2 sentences, one blank, clear context clue).
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 38 - Actions, Part 7 (動作 七)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (36 words) ----
const VOCAB = [
  { word: "shake", pos: "v.", cn_def: "握(手)", en_def: "to move quickly up and down or side to side",
    sentence: "The two leaders stopped to {{BLANK}} hands before the meeting began.",
    cn: "兩位領導人在會議開始前停下來握手。" },
  { word: "share", pos: "v.", cn_def: "分擔", en_def: "to have or use something together with others",
    sentence: "She decided to {{BLANK}} her lunch with her hungry classmate.",
    cn: "她決定和飢餓的同學分擔她的午餐。" },
  { word: "shoot", pos: "v.", cn_def: "注射", en_def: "to give an injection using a needle",
    sentence: "The nurse had to {{BLANK}} the patient with a small dose of medicine.",
    cn: "護士必須給病人注射一小劑藥物。" },
  { word: "solve", pos: "v.", cn_def: "解決", en_def: "to find the answer to a problem",
    sentence: "It took the class an hour to {{BLANK}} the tricky math puzzle.",
    cn: "全班花了一個小時才解決這道棘手的數學謎題。" },
  { word: "spell", pos: "v.", cn_def: "拼寫", en_def: "to say or write the letters of a word in order",
    sentence: "Can you {{BLANK}} your last name for the school records?",
    cn: "你可以為了學校紀錄拼寫一下你的姓嗎？" },
  { word: "spot", pos: "v.", cn_def: "看到", en_def: "to suddenly see or notice something",
    sentence: "She was the first to {{BLANK}} the rare bird in the tree.",
    cn: "她是第一個看到樹上那隻稀有鳥的人。" },
  { word: "spread", pos: "v.", cn_def: "蔓延", en_def: "to become larger or move over a wider area",
    sentence: "The wildfire began to {{BLANK}} quickly across the dry hillside.",
    cn: "野火開始迅速地蔓延到乾燥的山坡上。" },
  { word: "state", pos: "v.", cn_def: "陳述", en_def: "to say something clearly and formally",
    sentence: "The judge asked him to {{BLANK}} his name for the court record.",
    cn: "法官要求他陳述自己的姓名供法庭紀錄。" },
  { word: "steal", pos: "v.", cn_def: "偷竊", en_def: "to take something that belongs to someone else",
    sentence: "Someone tried to {{BLANK}} a bike from outside the library.",
    cn: "有人試圖偷竊圖書館外面的一台自行車。" },
  { word: "strike", pos: "v.", cn_def: "打擊", en_def: "to hit someone or something forcefully",
    sentence: "Lightning can {{BLANK}} tall trees during a powerful summer storm.",
    cn: "閃電在強烈的夏季暴風雨中可能打擊高大的樹木。" },
  { word: "suggest", pos: "v.", cn_def: "建議", en_def: "to offer an idea or plan for someone to consider",
    sentence: "My friend decided to {{BLANK}} a new restaurant for dinner tonight.",
    cn: "我朋友決定建議今晚去一家新餐廳吃晚餐。" },
  { word: "support", pos: "v.", cn_def: "支持", en_def: "to help or encourage someone",
    sentence: "Her whole family came to {{BLANK}} her during the big race.",
    cn: "她全家人都來支持她參加這場重要的比賽。" },
  { word: "surprise", pos: "v.", cn_def: "令…驚訝", en_def: "to cause someone to feel sudden wonder",
    sentence: "Her classmates planned to {{BLANK}} her with a small birthday cake.",
    cn: "她的同學計畫用一個小蛋糕讓她驚訝。" },
  { word: "survive", pos: "v.", cn_def: "倖存", en_def: "to continue to live after a difficult or dangerous event",
    sentence: "The small plant managed to {{BLANK}} the long, cold winter.",
    cn: "這株小植物挺過了漫長寒冷的冬天而倖存下來。" },
  { word: "take", pos: "v.", cn_def: "拿取", en_def: "to carry or move something from one place to another",
    sentence: "Please {{BLANK}} your umbrella with you because it might rain.",
    cn: "請帶上你的雨傘，因為可能會下雨。" },
  { word: "teach", pos: "v.", cn_def: "教", en_def: "to help someone learn a skill or subject",
    sentence: "My older sister offered to {{BLANK}} me how to ride a bike.",
    cn: "我姊姊主動提議教我如何騎自行車。" },
  { word: "tear", pos: "v.", cn_def: "撕裂", en_def: "to pull something apart so it rips",
    sentence: "Be careful not to {{BLANK}} the thin wrapping paper.",
    cn: "請小心別撕破這張薄薄的包裝紙。" },
  { word: "think", pos: "v.", cn_def: "認為", en_def: "to have an opinion or belief about something",
    sentence: "Most students {{BLANK}} the new gym schedule is much better.",
    cn: "大多數學生認為新的體育館時間表好多了。" },
  { word: "trace", pos: "v.", cn_def: "追蹤", en_def: "to follow or find the origin of something",
    sentence: "Detectives worked hard to {{BLANK}} the missing package's exact route.",
    cn: "警探努力追蹤這個遺失包裹的確切路線。" },
  { word: "trap", pos: "v.", cn_def: "設陷阱", en_def: "to catch an animal or person using a device or trick",
    sentence: "The hunter set a wire cage to {{BLANK}} the wild rabbit.",
    cn: "獵人設置了一個鐵絲籠來捕捉野兔。" },
  { word: "travel", pos: "n.", cn_def: "旅行", en_def: "the act of going from one place to another",
    sentence: "Her job requires a lot of {{BLANK}} between different countries.",
    cn: "她的工作需要在不同國家之間頻繁旅行。" },
  { word: "treasure", pos: "v.", cn_def: "珍愛", en_def: "to value something very highly",
    sentence: "She will always {{BLANK}} the old photo of her grandmother.",
    cn: "她會永遠珍愛這張祖母的舊照片。" },
  { word: "underline", pos: "v.", cn_def: "在…畫底線", en_def: "to draw a line under a word or sentence",
    sentence: "Please {{BLANK}} every new vocabulary word in your textbook.",
    cn: "請在課本裡的每個新單字下方畫底線。" },
  { word: "use", pos: "v.", cn_def: "使用", en_def: "to do something with a tool or object for a purpose",
    sentence: "You may {{BLANK}} my pencil if you forgot to bring one.",
    cn: "如果你忘了帶筆，可以使用我的鉛筆。" },
  { word: "visit", pos: "v.", cn_def: "拜訪", en_def: "to go and see a person or place",
    sentence: "We plan to {{BLANK}} our grandparents during the winter holiday.",
    cn: "我們計畫在寒假期間拜訪祖父母。" },
  { word: "wait", pos: "v.", cn_def: "等待", en_def: "to stay somewhere until something happens",
    sentence: "We had to {{BLANK}} almost an hour for the next bus.",
    cn: "我們必須等待將近一小時才能搭上下一班公車。" },
  { word: "want", pos: "v.", cn_def: "想要", en_def: "to have a desire for something",
    sentence: "Most kids {{BLANK}} a puppy at some point during childhood.",
    cn: "大多數孩子在童年時期都曾想要一隻小狗。" },
  { word: "wash", pos: "v.", cn_def: "洗", en_def: "to clean something using water",
    sentence: "Please remember to {{BLANK}} your hands before dinner tonight.",
    cn: "請記得在今晚晚餐前洗手。" },
  { word: "waste", pos: "v.", cn_def: "浪費", en_def: "to use something carelessly without a good result",
    sentence: "Try not to {{BLANK}} too much paper while printing your essay.",
    cn: "印你的文章時，盡量別浪費太多紙張。" },
  { word: "water", pos: "v.", cn_def: "澆水", en_def: "to give water to plants so they can grow",
    sentence: "She goes outside every morning to {{BLANK}} the small garden.",
    cn: "她每天早上都會出去幫小花園澆水。" },
  { word: "wave", pos: "v.", cn_def: "揮舞", en_def: "to move your hand side to side as a greeting",
    sentence: "The children began to {{BLANK}} happily at the passing train.",
    cn: "孩子們開心地對經過的火車揮手。" },
  { word: "win", pos: "v.", cn_def: "獲勝", en_def: "to be the best or first in a competition",
    sentence: "Our class hopes to {{BLANK}} the sports day relay this year.",
    cn: "我們班希望今年能在運動會接力賽中獲勝。" },
  { word: "write", pos: "v.", cn_def: "寫", en_def: "to put words on paper or a screen",
    sentence: "She likes to {{BLANK}} a short note in her diary every night.",
    cn: "她喜歡每天晚上在日記裡寫一段短短的文字。" },
  { word: "try", pos: "v.", cn_def: "嘗試", en_def: "to make an effort to do something",
    sentence: "He decided to {{BLANK}} the new recipe his mother suggested.",
    cn: "他決定嘗試他媽媽建議的新食譜。" },
  { word: "were", pos: "v.", cn_def: "是", en_def: "the past tense of \"are,\" used with plural subjects",
    sentence: "All the students {{BLANK}} excited about the upcoming field trip.",
    cn: "所有學生對即將到來的校外教學都感到興奮。" },
  { word: "actually", pos: "adv.", cn_def: "事實上", en_def: "used to say what is really true",
    sentence: "He looked nervous, but he was {{BLANK}} quite calm inside.",
    cn: "他看起來很緊張，但事實上內心相當平靜。" }
];

// ---- Part 2 data: 36 MCQs ----
// Continuing the simpler/shorter MCQ style from Group 37:
// ~16-26 words, exactly 2 sentences, one blank, 4 options.
// Answer letters balanced across A/B/C/D, no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "The two company leaders met for the first time today. They stopped to ______ hands before sitting down.",
    options: ["shake", "share", "shoot", "solve"], answer: 0, vocabIndex: 0 },
  { q: "Her friend forgot to bring lunch to school today. She decided to ______ her own sandwich with him.",
    options: ["shoot", "share", "spot", "spread"], answer: 1, vocabIndex: 1 },
  { q: "The patient needed a small dose of medicine right away. The nurse had to ______ him carefully with a needle.",
    options: ["shake", "solve", "shoot", "state"], answer: 2, vocabIndex: 2 },
  { q: "The math puzzle on the board looked very tricky at first. It took the whole class an hour to ______ it.",
    options: ["spell", "spot", "steal", "solve"], answer: 3, vocabIndex: 3 },
  { q: "The new student's last name was hard to write down. Can you ______ it for the school records, please?",
    options: ["spell", "state", "strike", "suggest"], answer: 0, vocabIndex: 4 },
  { q: "A rare bird landed quietly in the tall tree outside. She was the first one to ______ it there.",
    options: ["share", "spot", "support", "surprise"], answer: 1, vocabIndex: 5 },
  { q: "The dry hillside caught fire late one summer afternoon. The flames began to ______ very quickly across the grass.",
    options: ["steal", "strike", "spread", "survive"], answer: 2, vocabIndex: 6 },
  { q: "The judge needed his full name for the official record. He asked the man to ______ it clearly.",
    options: ["spell", "suggest", "support", "state"], answer: 3, vocabIndex: 7 },
  { q: "A bike was left unlocked outside the library all afternoon. Someone tried to ______ it before closing time.",
    options: ["steal", "strike", "survive", "trace"], answer: 0, vocabIndex: 8 },
  { q: "A sudden storm rolled in during the hot summer evening. Lightning began to ______ the tallest trees nearby.",
    options: ["steal", "strike", "spread", "spot"], answer: 1, vocabIndex: 9 },
  { q: "Nobody could decide where to eat dinner that night. My friend offered to ______ a new restaurant downtown.",
    options: ["state", "support", "suggest", "surprise"], answer: 2, vocabIndex: 10 },
  { q: "She felt nervous before the big race started this morning. Her whole family came to ______ her at the finish line.",
    options: ["suggest", "survive", "surprise", "support"], answer: 3, vocabIndex: 11 },
  { q: "Her friends planned something special for her birthday this year. They wanted to ______ her with a small cake.",
    options: ["surprise", "support", "state", "spread"], answer: 0, vocabIndex: 12 },
  { q: "Winter was long and cold for the tiny plant outside. Somehow, it managed to ______ until spring arrived.",
    options: ["suggest", "survive", "strike", "steal"], answer: 1, vocabIndex: 13 },
  { q: "The sky looked cloudy as she left for school this morning. Please ______ your umbrella just in case it rains.",
    options: ["teach", "tear", "take", "think"], answer: 2, vocabIndex: 14 },
  { q: "Her little brother wanted to learn how to ride a bike. She offered to ______ him after school today.",
    options: ["take", "trace", "trap", "teach"], answer: 3, vocabIndex: 15 },
  { q: "The wrapping paper on the gift was thin and delicate. Be careful not to ______ it while opening the box.",
    options: ["tear", "teach", "trace", "trap"], answer: 0, vocabIndex: 16 },
  { q: "The school changed the gym class schedule this semester. Most students ______ the new schedule is much better.",
    options: ["trap", "think", "travel", "treasure"], answer: 1, vocabIndex: 17 },
  { q: "A package never arrived at the customer's front door. Detectives worked hard to ______ where it had gone missing.",
    options: ["teach", "treasure", "trace", "underline"], answer: 2, vocabIndex: 18 },
  { q: "A wild rabbit kept eating vegetables from the farmer's garden. He set a small wire cage to ______ it.",
    options: ["trace", "travel", "treasure", "trap"], answer: 3, vocabIndex: 19 },
  { q: "Her job often takes her to many different countries each year. It requires a lot of ______ between cities.",
    options: ["travel", "trap", "trace", "treasure"], answer: 0, vocabIndex: 20 },
  { q: "She found an old photo of her grandmother in a drawer. She knows she will always ______ it deeply.",
    options: ["trap", "treasure", "trace", "travel"], answer: 1, vocabIndex: 21 },
  { q: "Learning new vocabulary words is part of every reading lesson. Please ______ each new word in your textbook.",
    options: ["trace", "trap", "underline", "use"], answer: 2, vocabIndex: 22 },
  { q: "He forgot to bring a pencil to class again today. You may ______ mine if you need one.",
    options: ["underline", "visit", "wait", "use"], answer: 3, vocabIndex: 23 },
  { q: "Winter break is coming up in just a few more weeks. We plan to ______ our grandparents during the holiday.",
    options: ["visit", "use", "wait", "want"], answer: 0, vocabIndex: 24 },
  { q: "The bus stop was crowded and the next bus was late. We had to ______ almost an hour in the cold.",
    options: ["visit", "wait", "want", "wash"], answer: 1, vocabIndex: 25 },
  { q: "Many children dream about having a pet of their own someday. Most kids ______ a puppy at some point.",
    options: ["wait", "wash", "want", "waste"], answer: 2, vocabIndex: 26 },
  { q: "Dinner is almost ready and the table is nearly set. Please remember to ______ your hands first tonight.",
    options: ["want", "waste", "water", "wash"], answer: 3, vocabIndex: 27 },
  { q: "Printing a long essay can use a surprising amount of paper. Try not to ______ too much while printing yours.",
    options: ["waste", "wash", "water", "wave"], answer: 0, vocabIndex: 28 },
  { q: "Her small vegetable garden needs daily care to stay healthy. She goes outside every morning to ______ it.",
    options: ["waste", "water", "wave", "win"], answer: 1, vocabIndex: 29 },
  { q: "A long train passed slowly by the schoolyard fence today. The children began to ______ at it happily.",
    options: ["water", "win", "wave", "write"], answer: 2, vocabIndex: 30 },
  { q: "The relay race is the most exciting event of sports day. Our class really hopes to ______ it this year.",
    options: ["wave", "write", "try", "win"], answer: 3, vocabIndex: 31 },
  { q: "Every night before bed, she opens her small notebook. She likes to ______ just a short note each time.",
    options: ["write", "win", "try", "were"], answer: 0, vocabIndex: 32 },
  { q: "His mother suggested a new recipe for dinner last night. He decided to ______ cooking it himself today.",
    options: ["write", "try", "win", "wait"], answer: 1, vocabIndex: 33 },
  { q: "Everyone in class buzzed with excitement about the school trip. All the students ______ thrilled about the news.",
    options: ["try", "wave", "were", "win"], answer: 2, vocabIndex: 34 },
  { q: "He looked nervous standing in front of the class today. Inside, though, he was ______ feeling quite calm.",
    options: ["were", "try", "wave", "actually"], answer: 3, vocabIndex: 35 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "calm": { pos: "adj.", en_def: "not nervous or excited; relaxed", cn_def: "平靜的" },
  "childhood": { pos: "n.", en_def: "the time when a person is a child", cn_def: "童年" },
  "customer": { pos: "n.", en_def: "a person who buys goods or services", cn_def: "顧客" },
  "detectives": { pos: "n.", en_def: "people who investigate crimes", cn_def: "警探（複數）" },
  "dose": { pos: "n.", en_def: "an amount of medicine taken at one time", cn_def: "（藥的）一劑" },
  "drawer": { pos: "n.", en_def: "a sliding storage box in furniture", cn_def: "抽屜" },
  "finish line": { pos: "n.", en_def: "the line marking the end of a race", cn_def: "終點線" },
  "flames": { pos: "n.", en_def: "the visible parts of a fire", cn_def: "火焰（複數）" },
  "hillside": { pos: "n.", en_def: "the sloping side of a hill", cn_def: "山坡" },
  "injection": { pos: "n.", en_def: "medicine given to the body using a needle", cn_def: "注射" },
  "judge": { pos: "n.", en_def: "a person who decides cases in a court of law", cn_def: "法官" },
  "lightning": { pos: "n.", en_def: "a bright flash of light during a storm", cn_def: "閃電" },
  "needle": { pos: "n.", en_def: "a thin, sharp instrument used for injections", cn_def: "針" },
  "notebook": { pos: "n.", en_def: "a small book for writing notes", cn_def: "筆記本" },
  "official": { pos: "adj.", en_def: "approved by an authority; formal", cn_def: "正式的；官方的" },
  "patient": { pos: "n.", en_def: "a person receiving medical treatment", cn_def: "病人" },
  "puppy": { pos: "n.", en_def: "a young dog", cn_def: "小狗" },
  "record": { pos: "n.", en_def: "official information kept about something", cn_def: "紀錄" },
  "relay race": { pos: "n.", en_def: "a race in which team members take turns running", cn_def: "接力賽" },
  "schoolyard": { pos: "n.", en_def: "the outdoor area of a school used for play", cn_def: "校園；操場" },
  "semester": { pos: "n.", en_def: "half of a school year", cn_def: "學期" },
  "wildfire": { pos: "n.", en_def: "a large, fast-spreading fire outdoors", cn_def: "野火" },
  "wire": { pos: "n.", en_def: "a thin piece of metal used for various purposes", cn_def: "鐵絲；金屬線" },
  "wrapping paper": { pos: "n.", en_def: "decorative paper used to wrap gifts", cn_def: "包裝紙" },
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
