// ============================================================
// Group 13 Quiz Data: Work / Business / Money
// Full word set (42 words) — workplace tasks, business actions,
// and money vocabulary from the "school / work / media /
// communication" theme. Continues from Group 12 (School Life).
// Media/Entertainment and Time/Era words will follow as Group 14.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 13 - Work / Business / Money (工作/商業/金錢)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (42 words) ----
const VOCAB = [
  { word: "work", pos: "n.", cn_def: "工作", en_def: "activity done to earn money or achieve a result",
    sentence: "My father always finishes his {{BLANK}} before he comes home for dinner.",
    cn: "我爸爸總是在回家吃晚餐前完成他的工作。" },
  { word: "interview", pos: "n.", cn_def: "面試", en_def: "a formal meeting where someone is asked questions about a job",
    sentence: "She wore her best suit to the job {{BLANK}} on Monday morning.",
    cn: "她星期一早上穿著最好的套裝去參加工作面試。" },
  { word: "project", pos: "n.", cn_def: "專案", en_def: "a planned piece of work with a specific goal",
    sentence: "Our team spent three weeks finishing the new website {{BLANK}} on time.",
    cn: "我們的團隊花了三個星期準時完成了新的網站專案。" },
  { word: "matter", pos: "n.", cn_def: "事情", en_def: "a subject or situation that needs attention or discussion",
    sentence: "The manager said it was an urgent {{BLANK}} that needed to be solved today.",
    cn: "經理說這是一件緊急的事情，今天必須解決。" },
  { word: "problem", pos: "n.", cn_def: "問題", en_def: "a difficult situation that needs to be solved",
    sentence: "The engineer found the {{BLANK}} with the machine after checking it carefully.",
    cn: "工程師仔細檢查後找到了機器的問題所在。" },
  { word: "method", pos: "n.", cn_def: "方法", en_def: "a particular way of doing something",
    sentence: "The teacher tried a new {{BLANK}} to help students remember new vocabulary.",
    cn: "老師嘗試了一種新方法來幫助學生記住新單字。" },
  { word: "plan", pos: "n.", cn_def: "計畫", en_def: "a set of steps decided in advance to achieve something",
    sentence: "We made a {{BLANK}} to finish all our chores before the weekend.",
    cn: "我們訂了一個計畫，要在週末前完成所有的家事。" },
  { word: "meeting", pos: "n.", cn_def: "會議", en_def: "a gathering of people to discuss something",
    sentence: "The {{BLANK}} started late because two managers were stuck in traffic.",
    cn: "因為兩位經理被困在車流中，這場會議晚了才開始。" },
  { word: "report", pos: "n.", cn_def: "報告", en_def: "a written or spoken account of facts or findings",
    sentence: "My sister stayed up late finishing her science {{BLANK}} for tomorrow's class.",
    cn: "我姐姐熬夜完成了明天上課要用的科學報告。" },
  { word: "member", pos: "n.", cn_def: "成員", en_def: "a person who belongs to a group or organization",
    sentence: "Each new {{BLANK}} of the club received a free t-shirt and a name tag.",
    cn: "社團的每位新成員都收到了一件免費的T恤和名牌。" },
  { word: "team", pos: "n.", cn_def: "團隊", en_def: "a group of people who work together toward a common goal",
    sentence: "Our sales {{BLANK}} celebrated together after reaching this year's biggest goal.",
    cn: "我們的銷售團隊在達成今年最大的目標後一起慶祝。" },
  { word: "call", pos: "v.", cn_def: "打電話", en_def: "to telephone someone",
    sentence: "Please {{BLANK}} me as soon as you arrive at the airport tonight.",
    cn: "請你今晚一到機場就打電話給我。" },
  { word: "dial", pos: "v.", cn_def: "撥號", en_def: "to press buttons on a phone to make a call",
    sentence: "She tried to {{BLANK}} the customer service number three times before someone answered.",
    cn: "她撥了三次客服電話才有人接聽。" },
  { word: "employ", pos: "v.", cn_def: "僱用", en_def: "to give someone a paid job",
    sentence: "The new restaurant plans to {{BLANK}} ten more workers before it opens next month.",
    cn: "這家新餐廳計畫在下個月開幕前再僱用十名員工。" },
  { word: "hire", pos: "v.", cn_def: "僱用", en_def: "to give someone a job after an interview",
    sentence: "After three interviews, the company decided to {{BLANK}} the friendly young graduate.",
    cn: "經過三次面試後，公司決定僱用那位友善的年輕畢業生。" },
  { word: "quit", pos: "v.", cn_def: "辭職", en_def: "to stop doing a job or activity",
    sentence: "He decided to {{BLANK}} his job and travel around the world for a year.",
    cn: "他決定辭職並花一年時間環遊世界。" },
  { word: "interrupt", pos: "v.", cn_def: "打斷", en_def: "to stop someone while they are speaking or doing something",
    sentence: "It is impolite to {{BLANK}} someone while they are still talking.",
    cn: "在別人說話時打斷他們是不禮貌的。" },
  { word: "business", pos: "n.", cn_def: "生意", en_def: "the activity of buying and selling goods or services",
    sentence: "My aunt started a small {{BLANK}} selling handmade candles online last year.",
    cn: "我阿姨去年開始在網路上經營一家賣手工蠟燭的小生意。" },
  { word: "trade", pos: "n.", cn_def: "貿易", en_def: "the buying and selling of goods between people or countries",
    sentence: "The two countries signed a new {{BLANK}} agreement to lower import taxes.",
    cn: "這兩個國家簽署了一份新的貿易協定，降低進口稅。" },
  { word: "contract", pos: "n.", cn_def: "合約", en_def: "a written agreement between two or more people that is legally binding",
    sentence: "Before starting the job, every employee must sign an official {{BLANK}}.",
    cn: "在開始工作之前，每位員工都必須簽署一份正式合約。" },
  { word: "duty", pos: "n.", cn_def: "義務", en_def: "something a person is required to do because of their job or position",
    sentence: "It is the lifeguard's {{BLANK}} to watch every swimmer carefully at all times.",
    cn: "救生員的義務就是隨時仔細看顧每位泳客。" },
  { word: "income", pos: "n.", cn_def: "收入", en_def: "the money a person earns from work or other sources",
    sentence: "After getting the promotion, her monthly {{BLANK}} increased by a noticeable amount.",
    cn: "升職後，她每月的收入明顯增加了。" },
  { word: "rent", pos: "v.", cn_def: "出租；租用", en_def: "to pay money regularly to use something that belongs to someone else",
    sentence: "We decided to {{BLANK}} a small apartment near the university for the school year.",
    cn: "我們決定在這個學年租一間靠近大學的小公寓。" },
  { word: "bill", pos: "n.", cn_def: "帳單", en_def: "a piece of paper showing how much money is owed for something",
    sentence: "My mother pays the electricity {{BLANK}} online at the start of every month.",
    cn: "我媽媽每個月初都會在網上付電費帳單。" },
  { word: "fee", pos: "n.", cn_def: "費用", en_def: "an amount of money paid for a particular service",
    sentence: "There is a small entrance {{BLANK}} to visit the museum on weekends.",
    cn: "週末參觀這座博物館需要支付一筆小額的入場費用。" },
  { word: "price", pos: "n.", cn_def: "價格", en_def: "the amount of money needed to buy something",
    sentence: "The {{BLANK}} of the toy dropped a lot during the holiday sale.",
    cn: "這個玩具的價格在假期特賣期間降了很多。" },
  { word: "credit card", pos: "n.", cn_def: "信用卡", en_def: "a small plastic card used to pay for things and pay back the money later",
    sentence: "He paid for the new laptop using his {{BLANK}} instead of cash.",
    cn: "他用信用卡付了新筆電的錢，而不是用現金。" },
  { word: "cash", pos: "n.", cn_def: "現金", en_def: "money in the form of coins or paper bills",
    sentence: "The small food stall near the school only accepts {{BLANK}}, not cards.",
    cn: "學校附近那家小吃攤只收現金，不收卡。" },
  { word: "coin", pos: "n.", cn_def: "硬幣", en_def: "a small round piece of metal used as money",
    sentence: "My little brother collects old {{BLANK}} from different countries in a special box.",
    cn: "我弟弟用一個特別的盒子收集來自不同國家的舊硬幣。" },
  { word: "money", pos: "n.", cn_def: "錢", en_def: "coins and paper bills used to buy things",
    sentence: "She has been saving her {{BLANK}} to buy a new bicycle for months.",
    cn: "她已經存了好幾個月的錢，想買一台新的自行車。" },
  { word: "cent", pos: "n.", cn_def: "一分錢", en_def: "a small unit of money, one hundredth of a dollar",
    sentence: "The candy at the old shop only cost fifty {{BLANK}} when I was young.",
    cn: "我小時候那家老店的糖果只要五十分錢。" },
  { word: "dollar", pos: "n.", cn_def: "元", en_def: "the basic unit of money used in the United States and other countries",
    sentence: "He found a five {{BLANK}} bill on the sidewalk near the park.",
    cn: "他在公園附近的人行道上發現了一張五元的紙鈔。" },
  { word: "pound", pos: "n.", cn_def: "英鎊", en_def: "the basic unit of money used in the United Kingdom",
    sentence: "She exchanged her dollars for British {{BLANK}} before flying to London.",
    cn: "她在飛往倫敦前把美元換成了英鎊。" },
  { word: "sell", pos: "v.", cn_def: "出售", en_def: "to give something to someone in exchange for money",
    sentence: "Every weekend, my neighbor likes to {{BLANK}} fresh vegetables at the local market.",
    cn: "我的鄰居每個週末都喜歡在當地市場出售新鮮蔬菜。" },
  { word: "buy", pos: "v.", cn_def: "購買", en_def: "to get something by paying money for it",
    sentence: "We plan to {{BLANK}} a birthday present for grandma this weekend.",
    cn: "我們這個週末打算買一份生日禮物給奶奶。" },
  { word: "pay", pos: "v.", cn_def: "支付", en_def: "to give money to someone for goods or services",
    sentence: "Could you please {{BLANK}} for the bus tickets while I find our seats?",
    cn: "你能幫忙付公車票錢嗎？我先去找我們的座位。" },
  { word: "charge", pos: "v.", cn_def: "收費", en_def: "to ask someone to pay a certain amount of money",
    sentence: "The parking garage will {{BLANK}} an extra fee if you stay past midnight.",
    cn: "如果你停留超過午夜，這個停車場會額外收費。" },
  { word: "cost", pos: "v.", cn_def: "花費", en_def: "to have a particular price",
    sentence: "The new smartphone will {{BLANK}} much more than the older model.",
    cn: "這款新智慧型手機的價格會比舊款貴很多。" },
  { word: "spend", pos: "v.", cn_def: "花（錢、時間）", en_def: "to use money to pay for something",
    sentence: "My brother tends to {{BLANK}} too much money on video games every month.",
    cn: "我哥哥每個月都會在電玩遊戲上花太多錢。" },
  { word: "cheap", pos: "adj.", cn_def: "便宜的", en_def: "low in price; not expensive",
    sentence: "The clothes at that small shop are {{BLANK}} but still good quality.",
    cn: "那家小店的衣服很便宜，但品質還是很好。" },
  { word: "expensive", pos: "adj.", cn_def: "昂貴的", en_def: "costing a lot of money",
    sentence: "The hotel near the beach was too {{BLANK}} for our small budget.",
    cn: "海邊那家飯店對我們有限的預算來說太貴了。" },
  { word: "free", pos: "adj.", cn_def: "免費的", en_def: "costing no money",
    sentence: "Admission to the city park is completely {{BLANK}} for all visitors.",
    cn: "進入這座市立公園對所有遊客來說都是完全免費的。" }
];

// ---- Part 2 data: 42 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (11/11/10/10), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "My father always finishes everything on his desk before leaving the office. He never brings unfinished ______ home with him.",
    options: ["report","meeting","plan","work"], answer: 3, vocabIndex: 0 },
  { q: "She wore her best suit and arrived fifteen minutes early on Monday morning. Her job ______ lasted almost an hour.",
    options: ["meeting","report","interview","project"], answer: 2, vocabIndex: 1 },
  { q: "Our team worked together for three whole weeks to finish something important on time. The new website ______ launched successfully.",
    options: ["method","duty","business","project"], answer: 3, vocabIndex: 2 },
  { q: "The manager looked worried and said something needed to be fixed before lunch. It was an urgent ______ that could not wait.",
    options: ["plan","matter","method","team"], answer: 1, vocabIndex: 3 },
  { q: "After checking the machine carefully for almost an hour, the engineer finally understood why it had stopped working. She found the exact ______.",
    options: ["plan","contract","fee","problem"], answer: 3, vocabIndex: 4 },
  { q: "The teacher tried something completely different this semester to help students remember new words. This new ______ worked better than expected.",
    options: ["method","plan","report","duty"], answer: 0, vocabIndex: 5 },
  { q: "Before the weekend arrived, our whole family decided exactly how we would finish all our chores. We followed our ______ step by step.",
    options: ["problem","report","plan","income"], answer: 2, vocabIndex: 6 },
  { q: "Two managers got stuck in heavy traffic on their way to the office that morning. As a result, the important ______ started late.",
    options: ["interview","meeting","project","duty"], answer: 1, vocabIndex: 7 },
  { q: "My sister stayed up very late finishing something for her science class the next day. Her detailed ______ included many charts and graphs.",
    options: ["report","contract","bill","fee"], answer: 0, vocabIndex: 8 },
  { q: "Everyone who joins this club for the first time receives a free t-shirt and a name tag. Each new ______ feels instantly welcomed.",
    options: ["worker","leader","member","guest"], answer: 2, vocabIndex: 9 },
  { q: "After working hard all year, our sales group finally reached its biggest goal ever. The whole ______ celebrated together that evening.",
    options: ["club","team","company","business"], answer: 1, vocabIndex: 10 },
  { q: "As soon as you land at the airport tonight, please use your phone right away. ______ me so I know you arrived safely.",
    options: ["Dial","Hire","Call","Employ"], answer: 2, vocabIndex: 11 },
  { q: "She tried three separate times before finally getting through to customer service. Each time, she had to carefully ______ the same long number.",
    options: ["call","dial","rent","charge"], answer: 1, vocabIndex: 12 },
  { q: "Before opening next month, the new restaurant needs more people working in the kitchen and at the tables. They plan to ______ ten more workers.",
    options: ["fire","quit","interrupt","employ"], answer: 3, vocabIndex: 13 },
  { q: "After three rounds of careful interviews, the company finally made its decision about the open position. They chose to ______ the friendly young graduate.",
    options: ["hire","fire","quit","rent"], answer: 0, vocabIndex: 14 },
  { q: "After years of working in the same office, he wanted something completely different in his life. He decided to ______ his job and travel.",
    options: ["hire","quit","employ","charge"], answer: 1, vocabIndex: 15 },
  { q: "During the important meeting, one coworker kept speaking over everyone else without waiting his turn. Everyone agreed it was rude to ______ like that.",
    options: ["interview","call","interrupt","dial"], answer: 2, vocabIndex: 16 },
  { q: "Last year, my aunt started something small using only her kitchen and a few simple tools. Her handmade candle ______ grew quickly online.",
    options: ["business","project","contract","method"], answer: 0, vocabIndex: 17 },
  { q: "Two neighboring countries recently signed a document that would lower taxes on imported goods. This new ______ agreement pleased both governments.",
    options: ["business","contract","trade","duty"], answer: 2, vocabIndex: 18 },
  { q: "Before starting any new job at this company, every worker must read and sign an official document. This important ______ explains all the rules.",
    options: ["bill","fee","income","contract"], answer: 3, vocabIndex: 19 },
  { q: "At the pool, one worker is always responsible for watching every single swimmer carefully. This important ______ never changes, rain or shine.",
    options: ["duty","fee","bill","plan"], answer: 0, vocabIndex: 20 },
  { q: "After receiving a surprising promotion at work, she noticed her paycheck looked noticeably larger each month. Her monthly ______ had clearly increased.",
    options: ["bill","income","fee","price"], answer: 1, vocabIndex: 21 },
  { q: "For the upcoming school year, my older brother needed somewhere close to campus to live. He decided to ______ a small apartment nearby.",
    options: ["rent","buy","sell","charge"], answer: 0, vocabIndex: 22 },
  { q: "At the start of every month, my mother sits at her computer to handle household payments. She always pays the electricity ______ online.",
    options: ["fee","price","income","bill"], answer: 3, vocabIndex: 23 },
  { q: "On weekends, visitors must pay a small amount before walking through the museum's front doors. This entrance ______ helps support the building.",
    options: ["bill","fee","income","cost"], answer: 1, vocabIndex: 24 },
  { q: "During the holiday sale last week, shoppers noticed something exciting about a popular toy on every shelf. Its ______ had dropped significantly.",
    options: ["fee","bill","income","price"], answer: 3, vocabIndex: 25 },
  { q: "Instead of carrying paper money to the electronics store, he chose a more convenient way to pay for his new laptop. He used his ______ instead.",
    options: ["credit card","coin","cent","dollar"], answer: 0, vocabIndex: 26 },
  { q: "The small food stall right outside the school gate has a strict rule about how customers must pay. It only accepts ______, never cards.",
    options: ["coins","credit card","cash","checks"], answer: 2, vocabIndex: 27 },
  { q: "My little brother keeps a special wooden box filled with round metal pieces from many different countries. He loves collecting old ______.",
    options: ["coins","bills","dollars","cents"], answer: 0, vocabIndex: 28 },
  { q: "For several months, my sister has carefully set aside a little bit from her allowance each week. She has been saving her ______ for a new bicycle.",
    options: ["coin","cent","income","money"], answer: 3, vocabIndex: 29 },
  { q: "Years ago, the candy at the corner shop near my childhood home was almost unbelievably cheap. It only cost fifty ______ back then.",
    options: ["cents","dollars","pounds","coins"], answer: 0, vocabIndex: 30 },
  { q: "Walking through the park one afternoon, he noticed something green lying flat on the pavement ahead. He picked up a five ______ bill.",
    options: ["cent","pound","dollar","coin"], answer: 2, vocabIndex: 31 },
  { q: "Before her flight to London, she stopped at the currency exchange counter inside the airport. She traded her American dollars for British ______.",
    options: ["cents","pounds","coins","dollars"], answer: 1, vocabIndex: 32 },
  { q: "Every Saturday morning, my neighbor sets up a small stand at the corner of our street. She loves to ______ fresh vegetables there.",
    options: ["buy","rent","charge","sell"], answer: 3, vocabIndex: 33 },
  { q: "This weekend, my whole family is heading to the mall with grandma's birthday in mind. We plan to ______ her a thoughtful present.",
    options: ["buy","sell","rent","cost"], answer: 0, vocabIndex: 34 },
  { q: "At the crowded bus station, my friend rushed ahead to find us two good seats on the bus. Could you please ______ for both tickets?",
    options: ["sell","buy","pay","spend"], answer: 2, vocabIndex: 35 },
  { q: "Some parking garages have a strict rule about cars left overnight in their building. They will ______ drivers extra if they stay past midnight.",
    options: ["pay","charge","cost","spend"], answer: 1, vocabIndex: 36 },
  { q: "Compared to the older version sitting on the store shelf, the brand-new smartphone model carries a much higher number on its tag. It will ______ significantly more.",
    options: ["cost","pay","charge","spend"], answer: 0, vocabIndex: 37 },
  { q: "Every single month without fail, my brother seems unable to control himself around his favorite video games. He tends to ______ far too much on them.",
    options: ["cost","spend","charge","pay"], answer: 1, vocabIndex: 38 },
  { q: "Even though the small shop downtown looks plain and simple from the outside, customers always leave satisfied with their purchases. The clothes there are surprisingly ______.",
    options: ["expensive","free","rich","cheap"], answer: 3, vocabIndex: 39 },
  { q: "Right next to the beach, one particular hotel charges far more per night than anywhere else nearby. It was simply too ______ for our limited budget.",
    options: ["cheap","expensive","free","rich"], answer: 1, vocabIndex: 40 },
  { q: "Unlike most attractions in the busy downtown area, this particular city park never asks visitors for a single coin at the gate. Entry has always stayed completely ______.",
    options: ["cheap","expensive","free","rich"], answer: 2, vocabIndex: 41 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "accepts": { pos: "v.", en_def: "agrees to take or receive something", cn_def: "接受" },
  "admission": { pos: "n.", en_def: "the right or fee to enter a place", cn_def: "入場（費）" },
  "agreement": { pos: "n.", en_def: "a formal arrangement between people or groups", cn_def: "協議" },
  "airport": { pos: "n.", en_def: "a place where airplanes take off and land", cn_def: "機場" },
  "amount": { pos: "n.", en_def: "a quantity of something", cn_def: "數量" },
  "apartment": { pos: "n.", en_def: "a set of rooms for living in, usually in a larger building", cn_def: "公寓" },
  "aunt": { pos: "n.", en_def: "the sister of your father or mother", cn_def: "阿姨；伯母" },
  "beach": { pos: "n.", en_def: "the sandy or rocky area next to the ocean", cn_def: "海灘" },
  "bicycle": { pos: "n.", en_def: "a two-wheeled vehicle powered by pedaling", cn_def: "自行車" },
  "bills": { pos: "n.", en_def: "pieces of paper showing money owed, or paper money", cn_def: "帳單；紙鈔（複數）" },
  "birthday": { pos: "n.", en_def: "the day of the year a person was born", cn_def: "生日" },
  "British": { pos: "adj.", en_def: "relating to the United Kingdom", cn_def: "英國的" },
  "budget": { pos: "n.", en_def: "a plan for how much money can be spent", cn_def: "預算" },
  "candles": { pos: "n.", en_def: "sticks of wax that are burned for light", cn_def: "蠟燭（複數）" },
  "cards": { pos: "n.", en_def: "small flat pieces of plastic or paper, such as credit cards", cn_def: "卡片（複數）" },
  "celebrated": { pos: "v.", en_def: "did something special to mark a happy event", cn_def: "慶祝（過去式）" },
  "cents": { pos: "n.", en_def: "small units of money, one hundredth of a dollar", cn_def: "分（複數）" },
  "checks": { pos: "n.", en_def: "pieces of paper used to pay money from a bank account", cn_def: "支票（複數）" },
  "chores": { pos: "n.", en_def: "small jobs done regularly, especially at home", cn_def: "家事（複數）" },
  "club": { pos: "n.", en_def: "a group of people who meet because they share an interest", cn_def: "社團" },
  "collects": { pos: "v.", en_def: "gathers and keeps things as a hobby", cn_def: "收集" },
  "company": { pos: "n.", en_def: "a business that makes or sells things", cn_def: "公司" },
  "customer": { pos: "n.", en_def: "a person who buys goods or services from a shop or business", cn_def: "顧客" },
  "electricity": { pos: "n.", en_def: "a form of energy used to power lights, machines, and devices", cn_def: "電力" },
  "employee": { pos: "n.", en_def: "a person who works for a company or organization", cn_def: "員工" },
  "engineer": { pos: "n.", en_def: "a person who designs or builds machines, structures, or systems", cn_def: "工程師" },
  "entrance": { pos: "n.", en_def: "the way into a place", cn_def: "入口" },
  "exchanged": { pos: "v.", en_def: "gave one thing and received another in return", cn_def: "交換（過去式）" },
  "fire": { pos: "v.", en_def: "to end someone's job", cn_def: "解僱" },
  "garage": { pos: "n.", en_def: "a building where a car is kept, or a place that fixes cars", cn_def: "車庫；修車廠" },
  "goal": { pos: "n.", en_def: "something a person aims to achieve", cn_def: "目標" },
  "graduate": { pos: "n.", en_def: "a person who has completed a course of study", cn_def: "畢業生" },
  "guest": { pos: "n.", en_def: "a person who is invited to visit or stay somewhere", cn_def: "客人" },
  "handmade": { pos: "adj.", en_def: "made by hand, not by machine", cn_def: "手工製作的" },
  "holiday": { pos: "n.", en_def: "a special day or period of celebration or rest", cn_def: "假期；節日" },
  "import": { pos: "v.", en_def: "to bring goods into a country from abroad", cn_def: "進口" },
  "impolite": { pos: "adj.", en_def: "not having good manners; rude", cn_def: "沒禮貌的" },
  "increased": { pos: "v.", en_def: "became larger in amount", cn_def: "增加（過去式）" },
  "interviews": { pos: "n.", en_def: "formal meetings where someone is asked questions about a job", cn_def: "面試（複數）" },
  "laptop": { pos: "n.", en_def: "a small portable computer", cn_def: "筆記型電腦" },
  "leader": { pos: "n.", en_def: "a person who guides or is in charge of a group", cn_def: "領導者" },
  "lifeguard": { pos: "n.", en_def: "a person who watches swimmers and keeps them safe", cn_def: "救生員" },
  "London": { pos: "n.", en_def: "the capital city of the United Kingdom", cn_def: "倫敦" },
  "lower": { pos: "v.", en_def: "to make something smaller or less", cn_def: "降低" },
  "machine": { pos: "n.", en_def: "a device built to do a particular job", cn_def: "機器" },
  "manager": { pos: "n.", en_def: "a person who is in charge of a department, store, or team", cn_def: "經理" },
  "managers": { pos: "n.", en_def: "people who are in charge of a department, store, or team", cn_def: "經理（複數）" },
  "market": { pos: "n.", en_def: "a place where food and goods are sold", cn_def: "市場" },
  "midnight": { pos: "n.", en_def: "twelve o'clock at night", cn_def: "午夜" },
  "museum": { pos: "n.", en_def: "a building where interesting old or rare things are shown", cn_def: "博物館" },
  "noticeable": { pos: "adj.", en_def: "easy to see or notice", cn_def: "明顯的" },
  "official": { pos: "adj.", en_def: "approved by an authority; formal", cn_def: "正式的" },
  "parking": { pos: "n.", en_def: "the act of leaving a vehicle in a particular place", cn_def: "停車" },
  "pounds": { pos: "n.", en_def: "the basic units of money used in the United Kingdom", cn_def: "英鎊（複數）" },
  "promotion": { pos: "n.", en_def: "a move to a higher position at work", cn_def: "升職" },
  "quality": { pos: "n.", en_def: "how good or bad something is", cn_def: "品質" },
  "rich": { pos: "adj.", en_def: "having a lot of money", cn_def: "富有的" },
  "service": { pos: "n.", en_def: "help or work provided to someone", cn_def: "服務" },
  "shirt": { pos: "n.", en_def: "a piece of clothing worn on the upper body", cn_def: "襯衫" },
  "sidewalk": { pos: "n.", en_def: "a paved path for walking beside a street", cn_def: "人行道" },
  "stall": { pos: "n.", en_def: "a small open shop or table, often outdoors", cn_def: "攤位" },
  "suit": { pos: "n.", en_def: "a formal set of matching clothes, usually a jacket and pants or skirt", cn_def: "套裝" },
  "swimmer": { pos: "n.", en_def: "a person who is swimming", cn_def: "游泳的人" },
  "tag": { pos: "n.", en_def: "a small label attached to something", cn_def: "標籤" },
  "taxes": { pos: "n.", en_def: "money paid to the government based on income or goods", cn_def: "稅（複數）" },
  "tickets": { pos: "n.", en_def: "small pieces of paper that allow entry to an event or travel", cn_def: "票（複數）" },
  "traffic": { pos: "n.", en_def: "vehicles moving along a road", cn_def: "交通" },
  "university": { pos: "n.", en_def: "a school for higher education after high school", cn_def: "大學" },
  "urgent": { pos: "adj.", en_def: "needing immediate attention", cn_def: "緊急的" },
  "vegetables": { pos: "n.", en_def: "plants or parts of plants eaten as food", cn_def: "蔬菜" },
  "website": { pos: "n.", en_def: "a set of pages on the Internet", cn_def: "網站" },
  "worker": { pos: "n.", en_def: "a person who works, especially at a job that involves physical effort", cn_def: "工人" },
  "workers": { pos: "n.", en_def: "people who work, especially at jobs involving physical effort", cn_def: "工人（複數）" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});

// ---- Plural aliases so MCQ option lookups resolve correctly ----
const PLURAL_ALIASES = {
  "coins": "coin", "dollars": "dollar", "members": "member", "teams": "team",
  "contracts": "contract", "fees": "fee", "prices": "price", "incomes": "income",
  "businesses": "business", "trades": "trade", "duties": "duty", "methods": "method",
  "plans": "plan", "problems": "problem", "reports": "report", "meetings": "meeting",
  "projects": "project"
};
Object.keys(PLURAL_ALIASES).forEach(plural => {
  const singular = PLURAL_ALIASES[plural];
  if (!LOOKUP[plural] && LOOKUP[singular]) {
    LOOKUP[plural] = LOOKUP[singular];
  }
});
