// ============================================================
// Group 34 Quiz Data: Actions, Part 3
// Full word set (36 words) — the third portion of the
// "actions" theme (252-word flat verb list). Continues from
// Group 33 (Actions, Part 2). Split into 7 groups of 36 words
// each (Groups 32-38) per the person's request.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 34 - Actions, Part 3 (動作 三)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (36 words) ----
const VOCAB = [
  { word: "cheat", pos: "v.", cn_def: "詐欺", en_def: "to act dishonestly in order to gain an advantage",
    sentence: "The teacher caught two students trying to {{BLANK}} during the final exam.",
    cn: "老師抓到兩名學生在期末考試中作弊。" },
  { word: "check", pos: "v.", cn_def: "檢查", en_def: "to examine something to make sure it is correct or safe",
    sentence: "My father always likes to {{BLANK}} the tires before a long road trip.",
    cn: "我爸爸在長途旅行前總喜歡檢查輪胎。" },
  { word: "climb", pos: "v.", cn_def: "攀登", en_def: "to move upward, often using your hands and feet",
    sentence: "It took the hikers nearly six hours to {{BLANK}} to the top of the hill.",
    cn: "登山客花了將近六小時才攀登到山頂。" },
  { word: "comment", pos: "n.", cn_def: "評論", en_def: "a remark expressing an opinion or reaction",
    sentence: "She left a kind {{BLANK}} under her friend's painting on social media.",
    cn: "她在朋友的畫作下方的社群媒體留下了一則友善的評論。" },
  { word: "compare", pos: "v.", cn_def: "比較", en_def: "to examine two or more things to see how they are similar or different",
    sentence: "The students were asked to {{BLANK}} the two short stories for homework.",
    cn: "學生被要求比較這兩篇短篇故事作為作業。" },
  { word: "complain", pos: "v.", cn_def: "抱怨", en_def: "to say that you are unhappy or dissatisfied about something",
    sentence: "Several customers began to {{BLANK}} loudly about the slow service at the restaurant.",
    cn: "幾位顧客開始大聲抱怨餐廳的服務太慢。" },
  { word: "complete", pos: "v.", cn_def: "完成", en_def: "to finish doing or making something",
    sentence: "She worked late into the night to {{BLANK}} her science project on time.",
    cn: "她工作到深夜才把科學作業如期完成。" },
  { word: "continue", pos: "v.", cn_def: "繼續", en_def: "to keep doing something without stopping",
    sentence: "Despite the heavy rain, the players decided to {{BLANK}} the soccer match.",
    cn: "儘管下著大雨，球員們還是決定繼續進行足球比賽。" },
  { word: "control", pos: "v.", cn_def: "控制", en_def: "to have power over something and direct how it works",
    sentence: "It took the new pilot several lessons to learn how to {{BLANK}} the small plane.",
    cn: "這位新飛行員花了好幾堂課才學會如何控制這架小飛機。" },
  { word: "cover", pos: "v.", cn_def: "覆蓋", en_def: "to put something over or on top of another thing",
    sentence: "She used a soft blanket to {{BLANK}} her little brother while he slept.",
    cn: "她用一條柔軟的毯子蓋住正在睡覺的弟弟。" },
  { word: "create", pos: "v.", cn_def: "創造", en_def: "to make something new that did not exist before",
    sentence: "The young artist wanted to {{BLANK}} a colorful mural for the school hallway.",
    cn: "這位年輕藝術家想要為學校走廊創造一幅色彩繽紛的壁畫。" },
  { word: "cross", pos: "v.", cn_def: "過(河、街)", en_def: "to go from one side of something to the other",
    sentence: "Always look both ways carefully before you {{BLANK}} the busy street.",
    cn: "在過繁忙的街道前，務必仔細看清楚兩邊。" },
  { word: "pass", pos: "v.", cn_def: "通過", en_def: "to go past or through something",
    sentence: "We watched the parade {{BLANK}} slowly in front of our favorite bakery.",
    cn: "我們看著遊行隊伍慢慢地經過我們最喜歡的麵包店前。" },
  { word: "cry", pos: "v.", cn_def: "哭泣", en_def: "to produce tears, usually because of sadness or pain",
    sentence: "The little girl began to {{BLANK}} after she dropped her favorite ice cream.",
    cn: "小女孩在掉了她最喜歡的冰淇淋後開始哭泣。" },
  { word: "cut", pos: "v.", cn_def: "切割", en_def: "to use a sharp tool to divide something into pieces",
    sentence: "Could you please {{BLANK}} the birthday cake into eight equal slices?",
    cn: "你可以幫忙把生日蛋糕切成八等份嗎？" },
  { word: "deal", pos: "v.", cn_def: "處理", en_def: "to handle or take care of a problem or situation",
    sentence: "The manager had to {{BLANK}} with several angry customers all afternoon.",
    cn: "經理整個下午都得處理好幾位生氣的顧客。" },
  { word: "debate", pos: "v.", cn_def: "辯論", en_def: "to discuss a topic by giving different opinions",
    sentence: "The two teams will {{BLANK}} about climate change in front of the whole school.",
    cn: "這兩個隊伍將在全校面前就氣候變遷進行辯論。" },
  { word: "decide", pos: "v.", cn_def: "決定", en_def: "to choose something after thinking carefully",
    sentence: "After visiting three different shops, she finally managed to {{BLANK}} on a birthday gift.",
    cn: "在逛了三家不同的店之後，她終於決定好了一份生日禮物。" },
  { word: "define", pos: "v.", cn_def: "定義", en_def: "to explain the exact meaning of a word or idea",
    sentence: "The teacher asked the class to {{BLANK}} the word \"democracy\" in their own words.",
    cn: "老師要求全班用自己的話來定義「民主」這個詞。" },
  { word: "deliver", pos: "v.", cn_def: "遞送", en_def: "to take something to a place or person",
    sentence: "The driver promised to {{BLANK}} the package before noon on Friday.",
    cn: "送貨員承諾在星期五正午前把包裹遞送過來。" },
  { word: "depend", pos: "v.", cn_def: "依賴", en_def: "to rely on someone or something for help or support",
    sentence: "Whether the picnic happens this weekend will {{BLANK}} entirely on the weather.",
    cn: "這個週末野餐是否舉行完全取決於天氣。" },
  { word: "detect", pos: "v.", cn_def: "察覺", en_def: "to notice or discover something that is not obvious",
    sentence: "A trained dog can easily {{BLANK}} the smell of certain foods hidden in luggage.",
    cn: "訓練有素的狗能輕易察覺隱藏在行李裡的特定食物氣味。" },
  { word: "develop", pos: "v.", cn_def: "發展", en_def: "to grow or change into something more advanced",
    sentence: "The small startup hopes to {{BLANK}} a useful new app for students.",
    cn: "這家小型新創公司希望為學生開發一款實用的新應用程式。" },
  { word: "die", pos: "v.", cn_def: "死", en_def: "to stop living",
    sentence: "Without enough water and sunlight, the small plant will eventually {{BLANK}}.",
    cn: "如果沒有足夠的水分和陽光，這株小植物最終會死掉。" },
  { word: "dig", pos: "v.", cn_def: "掘(土)", en_def: "to make a hole in the ground using a tool or your hands",
    sentence: "The children used small plastic shovels to {{BLANK}} a hole in the sand.",
    cn: "孩子們用小塑膠鏟在沙地上挖了一個洞。" },
  { word: "direct", pos: "v.", cn_def: "指揮", en_def: "to control or guide something, such as a movie or traffic",
    sentence: "She has always dreamed of getting the chance to {{BLANK}} her own short film.",
    cn: "她一直夢想著有機會能執導自己的短片。" },
  { word: "discover", pos: "v.", cn_def: "發現", en_def: "to find or learn something for the first time",
    sentence: "Scientists were thrilled to {{BLANK}} a new species of frog deep in the rainforest.",
    cn: "科學家們很興奮在雨林深處發現了一種新的青蛙物種。" },
  { word: "discuss", pos: "v.", cn_def: "討論", en_def: "to talk about something with another person or group",
    sentence: "The committee gathered after school to {{BLANK}} plans for the spring festival.",
    cn: "委員會在放學後聚集討論春季園遊會的計畫。" },
  { word: "doubt", pos: "v.", cn_def: "懷疑", en_def: "to feel unsure or not believe something",
    sentence: "Even with all the evidence presented, the jury continued to {{BLANK}} his story.",
    cn: "即使提出了所有證據，陪審團仍然懷疑他的說法。" },
  { word: "dream", pos: "v.", cn_def: "作夢", en_def: "to have thoughts and images in your mind while sleeping",
    sentence: "Last night I had a strange {{BLANK}} about flying over my hometown.",
    cn: "昨晚我夢到自己飛越家鄉的奇怪夢境。" },
  { word: "dry", pos: "v.", cn_def: "曬乾", en_def: "to remove water or moisture from something",
    sentence: "We hung the wet towels outside on the line to {{BLANK}} in the sun.",
    cn: "我們把濕毛巾掛在外面的繩子上曬乾。" },
  { word: "earn", pos: "v.", cn_def: "賺到", en_def: "to receive money or rewards for work you have done",
    sentence: "She works two part-time jobs each summer to {{BLANK}} extra money for college.",
    cn: "她每年夏天打兩份兼職工作，賺取額外的大學學費。" },
  { word: "ease", pos: "v.", cn_def: "使放鬆(舒緩)", en_def: "to make a feeling or problem less severe or painful",
    sentence: "A warm cup of tea can sometimes {{BLANK}} a sore throat before bed.",
    cn: "睡前喝一杯熱茶有時能舒緩喉嚨痛。" },
  { word: "embarrass", pos: "v.", cn_def: "使困窘", en_def: "to make someone feel ashamed or uncomfortable in front of others",
    sentence: "Tripping over his own shoelaces in front of the whole class began to {{BLANK}} him.",
    cn: "在全班面前被自己的鞋帶絆倒讓他開始感到困窘。" },
  { word: "emphasize", pos: "v.", cn_def: "強調", en_def: "to give special importance to something",
    sentence: "The coach likes to {{BLANK}} teamwork over individual scoring during practice.",
    cn: "教練在訓練時喜歡強調團隊合作而非個人得分。" },
  { word: "enjoy", pos: "v.", cn_def: "喜愛", en_def: "to take pleasure in something",
    sentence: "Most of the students seemed to {{BLANK}} the field trip to the science museum.",
    cn: "大多數學生似乎都很喜愛這次去科學博物館的校外教學。" }
];

// ---- Part 2 data: 36 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~27-34 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// 4 options per question, answer letters balanced across A/B/C/D,
// no adjacent repeats. vocabIndex points to the exact VOCAB entry.
const MCQS = [
  { q: "Glancing nervously at a neighbor's paper while the proctor walked the rows during the silent test, two students made a poor choice. The teacher caught two students trying to ______ during the final exam.",
    options: ["cheat", "check", "compare", "complete"], answer: 0, vocabIndex: 0 },
  { q: "Walking slowly around the loaded vehicle with a flashlight before sunrise, he made sure nothing would go wrong on the highway. My father always likes to ______ the tires before a long road trip.",
    options: ["create", "check", "cover", "cut"], answer: 1, vocabIndex: 1 },
  { q: "Sweating under the midday sun with heavy packs and trekking poles, the determined group pushed onward toward the summit. It took the hikers nearly six hours to ______ to the top of the hill.",
    options: ["cross", "dig", "climb", "develop"], answer: 2, vocabIndex: 2 },
  { q: "Scrolling through her phone late at night, she noticed a beautiful sunset photo posted by someone in her art class. She left a kind ______ under her friend's painting on social media that evening.",
    options: ["debate", "control", "deal", "comment"], answer: 3, vocabIndex: 3 },
  { q: "Sitting at the kitchen table with two open books and a notebook full of notes, the students worked through their assignment together. The students were asked to ______ the two short stories for homework.",
    options: ["compare", "create", "dry", "cheat"], answer: 0, vocabIndex: 4 },
  { q: "Tapping their feet impatiently while watching empty tables sit untouched for nearly an hour, several diners grew increasingly frustrated. Several customers began to ______ loudly about the slow service at the restaurant.",
    options: ["discover", "complain", "depend", "doubt"], answer: 1, vocabIndex: 5 },
  { q: "Surrounded by poster boards, glue, and research notes well past midnight, she refused to stop until every detail was finished. She worked late into the night to ______ her science project on time.",
    options: ["discuss", "earn", "complete", "dream"], answer: 2, vocabIndex: 6 },
  { q: "Soaked from head to toe but unwilling to give up the close match, both teams kept their eyes on the field. Despite the heavy rain, the players decided to ______ the soccer match anyway.",
    options: ["cover", "cheat", "cry", "continue"], answer: 3, vocabIndex: 7 },
  { q: "Gripping the small wheel tightly while the instructor explained each switch inside the cockpit, the nervous trainee listened closely. It took the new pilot several lessons to learn how to ______ the small plane.",
    options: ["control", "compare", "complain", "cut"], answer: 0, vocabIndex: 8 },
  { q: "Noticing her younger brother had finally drifted off on the couch during the quiet afternoon movie, she tiptoed over carefully. She used a soft blanket to ______ her little brother while he slept peacefully.",
    options: ["create", "cover", "climb", "deal"], answer: 1, vocabIndex: 9 },
  { q: "Staring at the blank wall near the cafeteria with paints and brushes at her feet, she imagined something colorful. The young artist wanted to ______ a colorful mural for the school hallway.",
    options: ["discover", "define", "create", "ease"], answer: 2, vocabIndex: 10 },
  { q: "Standing at the curb with cars whizzing past in both directions, the cautious pedestrian waited patiently for the signal to change. Always look both ways carefully before you ______ the busy street near school.",
    options: ["pass", "depend", "direct", "cross"], answer: 3, vocabIndex: 11 },
  { q: "Lining the sidewalk with cameras raised high and children waving small flags, the cheerful crowd waited eagerly near the bakery window. We watched the parade ______ slowly in front of our favorite bakery downtown.",
    options: ["pass", "cross", "discuss", "dig"], answer: 0, vocabIndex: 12 },
  { q: "Watching her favorite scoop tumble off the cone onto the warm sidewalk, the disappointed toddler's lower lip began to tremble. The little girl began to ______ after she dropped her favorite ice cream.",
    options: ["debate", "cry", "deliver", "detect"], answer: 1, vocabIndex: 13 },
  { q: "Standing over the colorful dessert with a sharp knife and eight excited guests gathered around the table, she prepared to serve everyone fairly. Could you please ______ the birthday cake into eight equal slices?",
    options: ["dig", "cover", "cut", "create"], answer: 2, vocabIndex: 14 },
  { q: "Fielding one frustrated phone call after another from the front office all afternoon, the store manager rarely had a moment to rest. The manager had to ______ with several angry customers all afternoon long.",
    options: ["decide", "doubt", "develop", "deal"], answer: 3, vocabIndex: 15 },
  { q: "Preparing index cards filled with statistics and counterarguments, the two student teams rehearsed their strongest points before the big assembly. The two teams will ______ about climate change in front of the whole school.",
    options: ["debate", "dream", "embarrass", "emphasize"], answer: 0, vocabIndex: 16 },
  { q: "Walking slowly past shelf after shelf of scarves and jewelry boxes, she compared prices and styles for nearly an hour. After visiting three different shops, she finally managed to ______ on a birthday gift.",
    options: ["define", "decide", "deliver", "depend"], answer: 1, vocabIndex: 17 },
  { q: "Pausing the lesson to write a single tricky word on the whiteboard, the teacher wanted everyone to think carefully about its meaning. The teacher asked the class to ______ the word \"democracy\" carefully.",
    options: ["discover", "detect", "define", "discuss"], answer: 2, vocabIndex: 18 },
  { q: "Loading boxes carefully into the back of his van early in the morning, the courier double-checked the delivery schedule on his clipboard. The driver promised to ______ the package before noon on Friday.",
    options: ["create", "cover", "cut", "deliver"], answer: 3, vocabIndex: 19 },
  { q: "Checking the forecast nervously every hour leading up to Saturday, the family kept their fingers crossed for clear blue skies. Whether the picnic happens this weekend will ______ entirely on the weather forecast.",
    options: ["depend", "doubt", "discuss", "dream"], answer: 0, vocabIndex: 20 },
  { q: "Sniffing carefully along the rows of suitcases with a focused expression, the trained animal moved steadily down the line. A trained dog can easily ______ the smell of food hidden in luggage.",
    options: ["deal", "detect", "decide", "define"], answer: 1, vocabIndex: 21 },
  { q: "Gathered around laptops scattered with sketches and code late into the evening, the small team brainstormed features students might actually enjoy using. The small startup hopes to ______ a useful new app for students.",
    options: ["dig", "dry", "develop", "earn"], answer: 2, vocabIndex: 22 },
  { q: "Wilting a little more each day on the windowsill despite regular watering attempts, the neglected seedling looked increasingly fragile and pale. Without enough water and sunlight, the small plant will eventually ______ completely.",
    options: ["dig", "doubt", "dream", "die"], answer: 3, vocabIndex: 23 },
  { q: "Armed with colorful buckets and tiny plastic tools near the water's edge, the excited children got straight to work building. The children used small plastic shovels to ______ a hole in the sand.",
    options: ["dig", "climb", "cross", "create"], answer: 0, vocabIndex: 24 },
  { q: "Watching countless movies and studying camera angles for years, the film student finally had a project of her own. She has always dreamed of getting the chance to ______ her own short film.",
    options: ["discuss", "direct", "deliver", "depend"], answer: 1, vocabIndex: 25 },
  { q: "Wading carefully through dense vegetation with notebooks ready, the research team paused suddenly at an unfamiliar call from the canopy above. Scientists were thrilled to ______ a new species of frog in the rainforest.",
    options: ["develop", "define", "discover", "detect"], answer: 2, vocabIndex: 26 },
  { q: "Pulling chairs into a circle in the empty classroom after the final bell rang, several teachers and student leaders settled in together. The committee gathered after school to ______ plans for the spring festival.",
    options: ["doubt", "deliver", "die", "discuss"], answer: 3, vocabIndex: 27 },
  { q: "Listening to witness after witness describe a confusing chain of events, several jury members exchanged uncertain glances throughout the long trial. Even with all the evidence presented, the jury continued to ______ his story.",
    options: ["doubt", "dream", "discuss", "develop"], answer: 0, vocabIndex: 28 },
  { q: "Waking up suddenly just before sunrise with vivid images still fresh in her mind, she tried to remember every strange detail. Last night I had a strange ______ about flying over my hometown rooftops.",
    options: ["comment", "dream", "doubt", "debate"], answer: 1, vocabIndex: 29 },
  { q: "Pinning damp laundry carefully to a long rope stretched between two trees, she hoped the warm breeze would help quickly. We hung the wet towels outside on the line to ______ in the sun.",
    options: ["cover", "cut", "dry", "cross"], answer: 2, vocabIndex: 30 },
  { q: "Balancing schoolwork with two different part-time shifts every single week, she carefully set aside a portion of every paycheck. She works two part-time jobs each summer to ______ extra money for college tuition.",
    options: ["ease", "embarrass", "emphasize", "earn"], answer: 3, vocabIndex: 31 },
  { q: "Wrapped snugly under a blanket on the couch with a steaming mug cradled in both hands, she finally felt some relief. A warm cup of tea can sometimes ______ a sore throat before bed.",
    options: ["ease", "emphasize", "earn", "enjoy"], answer: 0, vocabIndex: 32 },
  { q: "Stumbling clumsily in front of every classmate while reaching for his backpack during announcements, he felt his face turn red. Tripping over his own shoelaces in front of the class began to ______ him.",
    options: ["ease", "embarrass", "enjoy", "earn"], answer: 1, vocabIndex: 33 },
  { q: "Pausing the drill to gather every player close, the patient coach pointed again and again at how well the group worked together. The coach likes to ______ teamwork over individual scoring during every practice.",
    options: ["enjoy", "embarrass", "emphasize", "earn"], answer: 2, vocabIndex: 34 },
  { q: "Wandering happily between glowing exhibits and hands-on experiments for nearly three hours, the noisy group barely noticed the time passing. Most of the students seemed to ______ the field trip to the science museum.",
    options: ["emphasize", "ease", "embarrass", "enjoy"], answer: 3, vocabIndex: 35 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "assembly": { pos: "n.", en_def: "a gathering of people, often at a school", cn_def: "全校集會" },
  "brainstormed": { pos: "v.", en_def: "thought of many ideas together as a group", cn_def: "腦力激盪（過去式）" },
  "buckets": { pos: "n.", en_def: "round containers with handles, used for carrying things", cn_def: "水桶（複數）" },
  "cameras": { pos: "n.", en_def: "devices used to take photographs or videos", cn_def: "相機（複數）" },
  "canopy": { pos: "n.", en_def: "the upper layer of leaves and branches in a forest", cn_def: "（森林）樹冠層" },
  "cautious": { pos: "adj.", en_def: "careful to avoid danger or mistakes", cn_def: "謹慎的" },
  "clipboard": { pos: "n.", en_def: "a flat board with a clip for holding papers", cn_def: "文件夾板" },
  "cockpit": { pos: "n.", en_def: "the area where the pilot sits in an airplane", cn_def: "駕駛艙" },
  "counterarguments": { pos: "n.", en_def: "arguments made to oppose another argument", cn_def: "反論點（複數）" },
  "courier": { pos: "n.", en_def: "a person who delivers packages or messages", cn_def: "快遞員" },
  "curb": { pos: "n.", en_def: "the edge of a sidewalk next to a street", cn_def: "路緣" },
  "diners": { pos: "n.", en_def: "people eating a meal at a restaurant", cn_def: "用餐者（複數）" },
  "drill": { pos: "n.", en_def: "a repeated exercise used for practice or training", cn_def: "訓練演練" },
  "exhibits": { pos: "n.", en_def: "objects or displays shown in a museum", cn_def: "展覽品（複數）" },
  "fortress": { pos: "n.", en_def: "a strong building built for defense", cn_def: "堡壘" },
  "frustrated": { pos: "adj.", en_def: "feeling annoyed because of being unable to do something", cn_def: "感到沮喪的" },
  "hometown": { pos: "n.", en_def: "the town or city where you were born or grew up", cn_def: "家鄉" },
  "index cards": { pos: "n.", en_def: "small cards used for notes or organizing information", cn_def: "索引卡" },
  "instructor": { pos: "n.", en_def: "a person who teaches a skill", cn_def: "教練；指導員" },
  "jewelry": { pos: "n.", en_def: "decorative items worn on the body, like rings and necklaces", cn_def: "珠寶；飾品" },
  "jury": { pos: "n.", en_def: "a group of people who decide if someone is guilty in a trial", cn_def: "陪審團" },
  "lever": { pos: "n.", en_def: "a bar used to operate or control a machine", cn_def: "操縱桿" },
  "luggage": { pos: "n.", en_def: "bags and suitcases used for traveling", cn_def: "行李" },
  "mug": { pos: "n.", en_def: "a large cup, usually with a handle", cn_def: "馬克杯" },
  "mural": { pos: "n.", en_def: "a large painting done directly on a wall", cn_def: "壁畫" },
  "neglected": { pos: "adj.", en_def: "not given enough care or attention", cn_def: "被忽略的；疏於照顧的" },
  "paycheck": { pos: "n.", en_def: "a check or payment given for work done", cn_def: "薪水支票" },
  "pedestrian": { pos: "n.", en_def: "a person walking, especially on a street", cn_def: "行人" },
  "poster boards": { pos: "n.", en_def: "large sheets of stiff paper used for displays", cn_def: "海報板" },
  "proctor": { pos: "n.", en_def: "a person who supervises an exam", cn_def: "監考官" },
  "rehearsed": { pos: "v.", en_def: "practiced something before performing it for real", cn_def: "排練（過去式）" },
  "rooftops": { pos: "n.", en_def: "the tops of the roofs of buildings", cn_def: "屋頂（複數）" },
  "scarves": { pos: "n.", en_def: "long pieces of cloth worn around the neck", cn_def: "圍巾（複數）" },
  "scoop": { pos: "n.", en_def: "a single round portion, especially of ice cream", cn_def: "（冰淇淋）一球" },
  "sketches": { pos: "n.", en_def: "rough or quick drawings", cn_def: "草圖（複數）" },
  "snugly": { pos: "adv.", en_def: "in a warm, comfortable, close-fitting way", cn_def: "暖和舒適地" },
  "splatter": { pos: "v.", en_def: "to scatter messily after hitting something", cn_def: "潑濺" },
  "startup": { pos: "n.", en_def: "a newly established business", cn_def: "新創公司" },
  "statistics": { pos: "n.", en_def: "numerical facts collected for analysis", cn_def: "統計數據" },
  "summit": { pos: "n.", en_def: "the highest point of a mountain or hill", cn_def: "山頂" },
  "tiptoed": { pos: "v.", en_def: "walked quietly on the toes (past tense of tiptoe)", cn_def: "踮腳走路（過去式）" },
  "trainee": { pos: "n.", en_def: "a person being trained for a job or skill", cn_def: "受訓者" },
  "trekking poles": { pos: "n.", en_def: "poles used for support while hiking", cn_def: "登山杖" },
  "tuition": { pos: "n.", en_def: "money paid for education", cn_def: "學費" },
  "vegetation": { pos: "n.", en_def: "plants in a particular area", cn_def: "植被" },
  "wading": { pos: "v.", en_def: "walking through water or a difficult area", cn_def: "涉水而行（進行式）" },
  "whizzing": { pos: "v.", en_def: "moving very fast, often with a buzzing sound", cn_def: "快速移動（進行式）" },
  "wilting": { pos: "v.", en_def: "becoming weak and drooping, especially a plant", cn_def: "枯萎（進行式）" },
  "witness": { pos: "n.", en_def: "a person who saw something happen, especially in a trial", cn_def: "證人" },
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
