// ============================================================
// Group 4 Quiz Data: Plants / Birds / Farm & Pet Animals
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 4 - Plants / Birds / Farm & Pet Animals (植物/鳥類/農場與寵物動物)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice ----
const VOCAB = [
  { word: "plant", pos: "n.", cn_def: "植物", en_def: "a living thing that grows in soil, like a flower or tree",
    sentence: "My mother waters every {{BLANK}} on our balcony each morning before she leaves for work.",
    cn: "我媽媽每天早上出門上班前，都會幫陽台上的每一株植物澆水。" },
  { word: "plant", pos: "v.", cn_def: "栽種", en_def: "to put a seed in the ground so it can grow",
    sentence: "We worked together in the garden to {{BLANK}} tomato seeds along the back fence last weekend.",
    cn: "上週末我們一起在花園裡合作，沿著後面的籬笆栽種番茄種子。" },
  { word: "grass", pos: "n.", cn_def: "青草", en_def: "short green plants that cover the ground",
    sentence: "The soft green {{BLANK}} in the park felt cool under our bare feet during the summer afternoon.",
    cn: "公園裡柔軟的青草在夏日午後讓我們的赤腳感覺很涼爽。" },
  { word: "flower", pos: "n.", cn_def: "花", en_def: "the colorful part of a plant that often smells nice",
    sentence: "My grandmother grows a different colorful {{BLANK}} in every corner of her small front garden.",
    cn: "我奶奶在她小小的前院花園的每個角落都種了不同顏色的花。" },
  { word: "cotton", pos: "n.", cn_def: "棉花", en_def: "a soft white material from a plant, used to make cloth",
    sentence: "This soft white shirt is made entirely of {{BLANK}}, so it feels gentle against your skin.",
    cn: "這件柔軟的白色襯衫完全是用棉花製成的，所以穿在身上感覺很舒服。" },
  { word: "rose", pos: "n.", cn_def: "玫瑰花", en_def: "a flower with a sweet smell, often red or pink",
    sentence: "He picked a single red {{BLANK}} from the garden to give to his mother on her birthday.",
    cn: "他從花園裡摘了一朵紅玫瑰花，要在媽媽生日那天送給她。" },
  { word: "tree", pos: "n.", cn_def: "樹", en_def: "a tall plant with a trunk and branches",
    sentence: "We planted a small {{BLANK}} in our backyard last spring, and it has already grown much taller.",
    cn: "我們去年春天在後院種了一棵小樹，它現在已經長高了很多。" },
  { word: "leaf", pos: "n.", cn_def: "樹葉", en_def: "a flat green part of a plant or tree",
    sentence: "A single yellow {{BLANK}} slowly fell from the branch and landed quietly on the wet ground.",
    cn: "一片黃色的樹葉緩緩地從樹枝上落下，靜靜地落在潮濕的地面上。" },
  { word: "seed", pos: "n.", cn_def: "種子", en_def: "a small hard part of a plant that grows into a new plant",
    sentence: "My little brother planted a tiny {{BLANK}} in a paper cup and watched it grow every single day.",
    cn: "我弟弟在紙杯裡種了一顆小小的種子，每天都看著它生長。" },
  { word: "root", pos: "n.", cn_def: "根", en_def: "the part of a plant that grows underground",
    sentence: "The old tree's thick {{BLANK}} had grown so deep that it cracked the sidewalk near our school.",
    cn: "那棵老樹粗壯的根長得很深，把我們學校附近的人行道弄裂了。" },
  { word: "woods", pos: "n.", cn_def: "樹林", en_def: "a large area covered with many trees",
    sentence: "We followed a narrow trail deep into the {{BLANK}} until we finally found the hidden campsite.",
    cn: "我們沿著一條狹窄的步道深入樹林，終於找到了那個隱藏的營地。" },
  { word: "grow", pos: "v.", cn_def: "成長；種植", en_def: "to become bigger over time",
    sentence: "My father says tomatoes {{BLANK}} best when they get plenty of sunlight and water every day.",
    cn: "我爸爸說番茄在每天得到充足的陽光和水分時長得最好，生長得最好。" },
  { word: "bird", pos: "n.", cn_def: "鳥", en_def: "an animal with feathers and wings that can fly",
    sentence: "Every morning, a small {{BLANK}} sings cheerfully outside my bedroom window before my alarm even rings.",
    cn: "每天早上，在我的鬧鐘響起之前，一隻小鳥總會在我臥室窗外開心地唱歌。" },
  { word: "duck", pos: "n.", cn_def: "鴨子", en_def: "a water bird with webbed feet and a flat beak",
    sentence: "A mother {{BLANK}} led her five fluffy babies across the pond behind our elementary school.",
    cn: "一隻鴨子媽媽帶著她五隻毛茸茸的寶寶穿過我們小學後面的池塘。" },
  { word: "goose", pos: "n.", cn_def: "鵝", en_def: "a large water bird, bigger than a duck",
    sentence: "A loud, angry {{BLANK}} chased us across the farmyard when we got too close to her nest.",
    cn: "當我們靠近牠的窩太近時，一隻憤怒又大聲的鵝把我們追著趕出了農場。" },
  { word: "chicken", pos: "n.", cn_def: "小雞；雞肉", en_def: "a common farm bird raised for its eggs and meat",
    sentence: "My grandmother feeds her {{BLANK}} fresh corn every morning before collecting eggs from the small wooden coop.",
    cn: "我奶奶每天早上餵她的雞吃新鮮玉米，然後再從那個小木雞舍裡收集雞蛋。" },
  { word: "hen", pos: "n.", cn_def: "母雞", en_def: "an adult female chicken",
    sentence: "The brown {{BLANK}} sat quietly on her nest, waiting patiently for her eggs to finally hatch.",
    cn: "那隻棕色的母雞安靜地坐在窩裡，耐心地等待她的蛋終於孵化。" },
  { word: "turkey", pos: "n.", cn_def: "火雞", en_def: "a large farm bird often eaten at holiday dinners",
    sentence: "My family always cooks a large {{BLANK}} together every year for our special holiday dinner.",
    cn: "我家每年都會一起烹煮一隻大火雞，作為我們特別節日晚餐的菜色。" },
  { word: "eagle", pos: "n.", cn_def: "老鷹", en_def: "a large, powerful bird that hunts other animals",
    sentence: "A powerful {{BLANK}} circled high above the mountains, searching the valley below for its next meal.",
    cn: "一隻強壯的老鷹在山上高空盤旋，搜尋著下方山谷裡的下一頓食物。" },
  { word: "parrot", pos: "n.", cn_def: "鸚鵡", en_def: "a colorful bird that can copy human speech",
    sentence: "My uncle's colorful pet {{BLANK}} can repeat almost every single word that he says to it.",
    cn: "我叔叔的彩色寵物鸚鵡幾乎能重複他對牠說的每一句話。" },
  { word: "pigeon", pos: "n.", cn_def: "鴿子", en_def: "a common gray city bird",
    sentence: "A gray {{BLANK}} landed on the windowsill and pecked curiously at the bread crumbs we left there.",
    cn: "一隻灰色的鴿子停在窗台上，好奇地啄食我們留在那裡的麵包屑。" },
  { word: "swallow", pos: "v.", cn_def: "吞嚥", en_def: "to make food or drink go down your throat",
    sentence: "My little sister had to {{BLANK}} her medicine quickly because she didn't like its bitter taste at all.",
    cn: "我妹妹必須很快地吞下她的藥，因為她一點都不喜歡那苦苦的味道。" },
  { word: "swallow", pos: "n.", cn_def: "燕子", en_def: "a small bird with pointed wings and a forked tail",
    sentence: "Every spring, a pair of small {{BLANK}} build their nest under the roof of our front porch.",
    cn: "每年春天，一對小燕子都會在我們前門廊的屋頂下築巢。" },
  { word: "swan", pos: "n.", cn_def: "天鵝", en_def: "a large graceful white water bird with a long neck",
    sentence: "A graceful white {{BLANK}} glided silently across the calm lake as visitors watched from the shore.",
    cn: "一隻優雅的白天鵝靜靜地滑過平靜的湖面，遊客們在岸邊觀看著。" },
  { word: "pet", pos: "n.", cn_def: "寵物", en_def: "an animal kept at home for company",
    sentence: "My family adopted a small {{BLANK}} from the animal shelter last month, and we love her already.",
    cn: "我家上個月從動物收容所領養了一隻小寵物，我們已經非常愛她了。" },
  { word: "bat", pos: "n.", cn_def: "蝙蝠", en_def: "a small flying mammal that is active at night",
    sentence: "Every evening at sunset, dozens of small {{BLANK}} fly out from the dark cave near our village.",
    cn: "每天傍晚太陽下山時，數十隻小蝙蝠會從我們村莊附近的黑暗洞穴飛出來。" },
  { word: "bear", pos: "n.", cn_def: "熊", en_def: "a large, strong wild animal with thick fur",
    sentence: "Campers are warned to store their food carefully so a hungry {{BLANK}} won't wander into the campsite.",
    cn: "露營者被警告要小心保存食物，這樣飢餓的熊就不會閒逛進入營地。" },
  { word: "koala", pos: "n.", cn_def: "無尾熊", en_def: "a furry Australian animal that lives in trees",
    sentence: "This sleepy {{BLANK}} spends most of the day resting quietly among the branches of tall eucalyptus trees.",
    cn: "這隻愛睡覺的無尾熊大部分時間都安靜地待在高大的尤加利樹枝間休息。" },
  { word: "panda", pos: "n.", cn_def: "貓熊", en_def: "a large black-and-white bear from China that eats bamboo",
    sentence: "The zoo's newest baby {{BLANK}} spends almost the entire day eating fresh bamboo leaves and napping.",
    cn: "動物園最新的貓熊寶寶幾乎整天都在吃新鮮的竹葉和打瞌睡。" },
  { word: "cow", pos: "n.", cn_def: "母牛；奶牛", en_def: "a large farm animal kept for milk or meat",
    sentence: "Every morning before sunrise, the farmer walks out to milk his {{BLANK}} in the old wooden barn.",
    cn: "每天日出之前，農夫都會走到那間老舊的木造穀倉去擠他的母牛的奶。" },
  { word: "ox", pos: "n.", cn_def: "公牛", en_def: "a large male farm animal used for pulling heavy loads",
    sentence: "In the old painting, a strong {{BLANK}} pulled a heavy wooden cart slowly along the muddy village road.",
    cn: "在那幅古老的畫作中，一頭強壯的公牛緩緩地拉著一台沉重的木製推車走在泥濘的村莊道路上。" },
  { word: "cat", pos: "n.", cn_def: "貓", en_def: "a small furry animal often kept as a pet",
    sentence: "Our gray {{BLANK}} sleeps on the warmest windowsill in the house almost every single afternoon.",
    cn: "我們家的灰貓幾乎每天下午都睡在家裡最溫暖的窗台上。" },
  { word: "kitten", pos: "n.", cn_def: "小貓", en_def: "a baby cat",
    sentence: "The tiny {{BLANK}} could barely climb out of the cardboard box without falling over completely.",
    cn: "那隻小貓幾乎沒辦法從紙箱裡爬出來而不完全摔倒。" },
  { word: "deer", pos: "n.", cn_def: "鹿", en_def: "a graceful wild animal with thin legs, often with antlers",
    sentence: "A young {{BLANK}} stepped quietly out of the forest and stared at us before running away quickly.",
    cn: "一隻年輕的鹿靜靜地從森林裡走出來，盯著我們看了一會兒後就很快地跑走了。" },
];

// ---- Part 2 data: 34 MCQs ----
// vocabIndex points to the exact VOCAB array entry being tested, which matters
// for words like plant/swallow that appear twice with different parts of speech.
const MCQS = [
  { q: "My grandmother spends every single weekend morning carefully watering the green plants that sit along her sunny kitchen windowsill. She talks to each ______ as if it could actually hear her.",
    options: ["plant", "flower", "tree", "root"], answer: 0, vocabIndex: 0 },
  { q: "Every spring, our whole class gathers in the school garden wearing gloves and carrying small shovels for an outdoor activity. Our teacher shows us exactly how to ______ vegetable seeds in neat, straight rows.",
    options: ["shine", "travel", "grow", "plant"], answer: 3, vocabIndex: 1 },
  { q: "After a long rainy week, the sun finally came out and dried up the muddy park completely by Saturday afternoon. Children immediately ran barefoot across the soft green ______, laughing and chasing each other happily.",
    options: ["grass", "leaf", "root", "seed"], answer: 0, vocabIndex: 2 },
  { q: "Every single year on her birthday, without ever forgetting, my father walks to the small shop near our house. He always picks out one beautiful, colorful ______ to surprise my mother with that morning.",
    options: ["leaf", "seed", "flower", "cotton"], answer: 2, vocabIndex: 3 },
  { q: "This soft, lightweight summer shirt feels incredibly gentle and comfortable against my skin, even after a full sweaty day outside. That's because it's made entirely from natural ______ grown on farms far away.",
    options: ["woods", "cotton", "rose", "grass"], answer: 1, vocabIndex: 4 },
  { q: "On Valentine's Day every February, my older brother always walks nervously into the same small flower shop downtown. He carefully picks out a single red ______ to give to his girlfriend that evening.",
    options: ["rose", "leaf", "seed", "flower"], answer: 0, vocabIndex: 5 },
  { q: "Last summer, my father hung a wooden swing from one of the thickest, sturdiest branches he could safely reach. That particular ______ has been growing steadily in our backyard for almost fifty years now.",
    options: ["leaf", "root", "tree", "woods"], answer: 2, vocabIndex: 6 },
  { q: "One quiet afternoon in late October, a sudden gust of cold wind blew through the nearly empty park near our school. A single bright yellow ______ spun slowly through the air before landing softly below.",
    options: ["grass", "leaf", "seed", "root"], answer: 1, vocabIndex: 7 },
  { q: "My curious little nephew planted something tiny inside a paper cup filled with dark soil almost three weeks ago. Now, to his great excitement, that single ______ has finally grown into a small green sprout.",
    options: ["seed", "leaf", "root", "cotton"], answer: 0, vocabIndex: 8 },
  { q: "City workers were confused for weeks about why the sidewalk near our school gate kept cracking more and more. Eventually they discovered that the old oak tree's enormous underground ______ was slowly pushing it upward.",
    options: ["leaf", "root", "woods", "grass"], answer: 1, vocabIndex: 9 },
  { q: "During our weekend camping trip, we decided to follow a narrow dirt trail just to see where it might lead. Deep inside the quiet ______, we were surprised to discover an old abandoned wooden cabin.",
    options: ["tree", "grass", "root", "woods"], answer: 3, vocabIndex: 10 },
  { q: "Local farmers in this particular region often say that timing matters more than almost anything else for a good harvest. Their rice always seems to ______ best after several weeks of steady, gentle warm rain.",
    options: ["shine", "travel", "grow", "plant"], answer: 2, vocabIndex: 11 },
  { q: "Even before my alarm clock has a chance to ring, something outside my window always wakes me up gently first. Every single morning, a cheerful little ______ perches there and sings a bright, happy song.",
    options: ["duck", "eagle", "pigeon", "bird"], answer: 3, vocabIndex: 12 },
  { q: "Walking past the calm pond behind our elementary school one afternoon, several students stopped to watch something adorable happening nearby. A proud mother ______ was carefully guiding her five fluffy yellow babies across the water.",
    options: ["goose", "swan", "duck", "hen"], answer: 2, vocabIndex: 13 },
  { q: "While visiting my uncle's farm last summer, my cousins and I wandered too close to a hidden nest in the grass. A surprisingly loud, aggressive ______ immediately chased all of us across the farmyard.",
    options: ["duck", "goose", "swan", "turkey"], answer: 1, vocabIndex: 14 },
  { q: "Every single morning before leaving for school, I watch my grandmother walk out to her wooden coop behind the house. She scatters fresh corn for her ______ and then collects warm eggs to bring inside.",
    options: ["hen", "turkey", "duck", "chicken"], answer: 3, vocabIndex: 15 },
  { q: "For almost three weeks, something unusual was happening quietly inside the wooden coop at the back of the farm. The speckled brown ______ sat patiently on her nest, waiting for her eggs to finally hatch.",
    options: ["hen", "chicken", "duck", "goose"], answer: 0, vocabIndex: 16 },
  { q: "Every single November, without fail, my entire extended family gathers together in our busy kitchen for an entire afternoon of cooking. Everyone helps prepare a large, roasted ______ for our special holiday dinner that evening.",
    options: ["chicken", "goose", "turkey", "duck"], answer: 2, vocabIndex: 17 },
  { q: "High above the steep, rocky cliffs near our campsite, something large and powerful circled slowly through the bright afternoon sky. That impressive ______ was clearly searching the quiet valley below for its very next meal.",
    options: ["pigeon", "swallow", "parrot", "eagle"], answer: 3, vocabIndex: 18 },
  { q: "My uncle keeps an unusually intelligent, brightly colored bird as a pet inside a large cage in his living room. That clever ______ has learned to repeat almost every single phrase he says to it.",
    options: ["parrot", "pigeon", "eagle", "swan"], answer: 0, vocabIndex: 19 },
  { q: "While sitting outside a busy café in the city center, we noticed something gray and plain land gently on our table. The curious little ______ pecked carefully at a few crumbs of bread we dropped.",
    options: ["eagle", "parrot", "swallow", "pigeon"], answer: 3, vocabIndex: 20 },
  { q: "The little boy made a terrible face and held his nose tightly shut before finally taking the disgusting cough medicine. He had to ______ it quickly because he absolutely hated its bitter, unpleasant taste.",
    options: ["swallow", "eat", "drink", "grow"], answer: 0, vocabIndex: 21 },
  { q: "Every single spring without fail, the same small, dark-winged bird returns to the exact same spot above our front porch. That graceful ______ rebuilds its nest there year after year, raising new chicks each time.",
    options: ["pigeon", "eagle", "swallow", "swan"], answer: 2, vocabIndex: 22 },
  { q: "Tourists gathered quietly along the edge of the still, peaceful lake to admire something elegant gliding silently across the water. That graceful white ______ seemed completely unaware of the small crowd watching from the shore.",
    options: ["duck", "swan", "goose", "pigeon"], answer: 1, vocabIndex: 23 },
  { q: "Last month, after weeks of careful discussion, my entire family finally visited the local animal shelter together on a Saturday morning. We adopted a small, gentle ______ that we have already grown to love deeply.",
    options: ["bear", "deer", "koala", "pet"], answer: 3, vocabIndex: 24 },
  { q: "Just after the sun sets behind the mountains near our village, something strange and wonderful happens above the dark cave entrance. Dozens of small ______ suddenly fly out together into the cooling evening sky.",
    options: ["bear", "bat", "panda", "koala"], answer: 1, vocabIndex: 25 },
  { q: "Park rangers always remind every camper to lock their food away safely inside special metal containers before going to sleep at night. This simple rule prevents a hungry wild ______ from wandering curiously into camp.",
    options: ["deer", "ox", "bear", "cow"], answer: 2, vocabIndex: 26 },
  { q: "This famously sleepy Australian animal almost never seems to do much during the day except rest quietly among tall tree branches. Scientists say this particular ______ spends nearly twenty hours every single day sleeping.",
    options: ["panda", "koala", "bear", "deer"], answer: 1, vocabIndex: 27 },
  { q: "Visitors at the zoo gather every single day just outside one particular enclosure to watch a newborn animal eating quietly. The zoo's newest baby ______ spends almost the entire day munching fresh bamboo leaves happily.",
    options: ["panda", "koala", "bear", "bat"], answer: 0, vocabIndex: 28 },
  { q: "Every single morning before the sun has fully risen, the tired farmer walks slowly to the old wooden barn nearby. There, he carefully milks his patient ______ before starting the rest of his busy day.",
    options: ["ox", "cow", "deer", "kitten"], answer: 1, vocabIndex: 29 },
  { q: "In the faded old painting hanging in our village museum, an enormous, powerfully strong animal pulls a heavy wooden cart slowly. That tireless ______ trudges steadily along the muddy road toward the distant market town.",
    options: ["ox", "cow", "bear", "deer"], answer: 0, vocabIndex: 30 },
  { q: "Almost every single afternoon, without anyone needing to call her, our lazy gray house animal finds the sunniest, warmest spot available. That comfortable ______ stretches out happily on the living room windowsill for hours.",
    options: ["kitten", "cat", "deer", "pet"], answer: 1, vocabIndex: 31 },
  { q: "We watched with amusement as something tiny and clumsy kept tumbling backward while desperately trying to escape from a cardboard box. That adorable little ______ eventually gave up and simply fell asleep inside instead.",
    options: ["cat", "pet", "deer", "kitten"], answer: 3, vocabIndex: 32 },
  { q: "While hiking quietly through the forest early one misty morning, something graceful and nervous stepped out from between two tall trees. That young ______ stared directly at us for a moment before darting away.",
    options: ["bear", "ox", "deer", "cow"], answer: 2, vocabIndex: 33 },
];

// ---- Word lookup definitions (for the lookup popup) ----
// Some words (plant, swallow) appear twice with different parts of speech.
// Merge those into one combined entry so lookup shows both senses instead
// of silently losing one to an object-key overwrite.
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});
// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "adopted": { pos: "v.", en_def: "took an animal or child into your family to care for it", cn_def: "領養" },
  "afternoon": { pos: "n.", en_def: "the part of the day between noon and evening", cn_def: "下午" },
  "alarm": { pos: "n.", en_def: "a device that makes a sound to wake you up", cn_def: "鬧鐘" },
  "angry": { pos: "adj.", en_def: "feeling strong displeasure", cn_def: "生氣的" },
  "animal": { pos: "n.", en_def: "a living creature, not a plant", cn_def: "動物" },
  "babies": { pos: "n.", en_def: "very young children or young animals", cn_def: "寶寶（複數）" },
  "baby": { pos: "n.", en_def: "a very young child or young animal", cn_def: "寶寶" },
  "backyard": { pos: "n.", en_def: "the area of land behind a house", cn_def: "後院" },
  "balcony": { pos: "n.", en_def: "a platform outside an upper window of a building", cn_def: "陽台" },
  "bamboo": { pos: "n.", en_def: "a tall plant with hollow stems, eaten by pandas", cn_def: "竹子" },
  "bare": { pos: "adj.", en_def: "not covered by clothing or shoes", cn_def: "赤裸的" },
  "barely": { pos: "adv.", en_def: "almost not; only just", cn_def: "幾乎不" },
  "barn": { pos: "n.", en_def: "a large farm building for animals or storage", cn_def: "穀倉" },
  "bedroom": { pos: "n.", en_def: "a room used for sleeping", cn_def: "臥室" },
  "best": { pos: "adj.", en_def: "of the highest quality", cn_def: "最好的" },
  "birthday": { pos: "n.", en_def: "the day of the year someone was born", cn_def: "生日" },
  "bitter": { pos: "adj.", en_def: "having a sharp, unpleasant taste", cn_def: "苦的" },
  "box": { pos: "n.", en_def: "a container with stiff sides", cn_def: "盒子" },
  "branch": { pos: "n.", en_def: "a part of a tree that grows out from the trunk", cn_def: "樹枝" },
  "branches": { pos: "n.", en_def: "more than one branch", cn_def: "樹枝（複數）" },
  "bread": { pos: "n.", en_def: "food made from baked flour and water", cn_def: "麵包" },
  "brother": { pos: "n.", en_def: "a boy or man with the same parents as you", cn_def: "兄弟" },
  "brown": { pos: "adj.", en_def: "having a color like soil or wood", cn_def: "棕色的" },
  "build": { pos: "v.", en_def: "to make something by putting parts together", cn_def: "建造；築（巢）" },
  "calm": { pos: "adj.", en_def: "quiet and peaceful, without much movement", cn_def: "平靜的" },
  "campers": { pos: "n.", en_def: "people who stay outdoors in tents", cn_def: "露營者（複數）" },
  "campsite": { pos: "n.", en_def: "a place where people camp", cn_def: "營地" },
  "cardboard": { pos: "n.", en_def: "a stiff, thick kind of paper used for boxes", cn_def: "紙板" },
  "carefully": { pos: "adv.", en_def: "in a careful way, paying close attention", cn_def: "小心地" },
  "cart": { pos: "n.", en_def: "a vehicle with wheels, pulled by an animal or person", cn_def: "手推車" },
  "cave": { pos: "n.", en_def: "a large natural hole in the side of a hill or underground", cn_def: "洞穴" },
  "chased": { pos: "v.", en_def: "ran after someone or something to catch them", cn_def: "追趕" },
  "cheerfully": { pos: "adv.", en_def: "in a happy, positive way", cn_def: "愉快地" },
  "circled": { pos: "v.", en_def: "moved around in a circle", cn_def: "盤旋" },
  "climb": { pos: "v.", en_def: "to go up something using your hands and feet", cn_def: "攀爬" },
  "collecting": { pos: "v.", en_def: "gathering things together", cn_def: "收集（進行式）" },
  "colorful": { pos: "adj.", en_def: "having many bright colors", cn_def: "色彩豐富的" },
  "completely": { pos: "adv.", en_def: "fully; entirely", cn_def: "完全地" },
  "cooks": { pos: "v.", en_def: "prepares food using heat", cn_def: "烹煮" },
  "cool": { pos: "adj.", en_def: "a little cold, in a pleasant way", cn_def: "涼爽的" },
  "coop": { pos: "n.", en_def: "a small cage or building for keeping chickens", cn_def: "雞舍" },
  "corn": { pos: "n.", en_def: "a tall plant with yellow seeds eaten as food", cn_def: "玉米" },
  "corner": { pos: "n.", en_def: "the point where two sides or edges meet", cn_def: "角落" },
  "cracked": { pos: "v.", en_def: "broke without separating completely", cn_def: "裂開" },
  "crumbs": { pos: "n.", en_def: "tiny pieces of bread or cake", cn_def: "碎屑（複數）" },
  "cup": { pos: "n.", en_def: "a small container used for drinking", cn_def: "杯子" },
  "curiously": { pos: "adv.", en_def: "in a way that shows interest in learning about something", cn_def: "好奇地" },
  "dark": { pos: "adj.", en_def: "having little or no light", cn_def: "黑暗的" },
  "day": { pos: "n.", en_def: "a period of 24 hours", cn_def: "天；日" },
  "deep": { pos: "adj.", en_def: "extending far down or in", cn_def: "深的" },
  "different": { pos: "adj.", en_def: "not the same; unlike something else", cn_def: "不同的" },
  "dinner": { pos: "n.", en_def: "the main meal of the day", cn_def: "晚餐" },
  "dozens": { pos: "n.", en_def: "many groups of twelve; a large number", cn_def: "數十；許多" },
  "eating": { pos: "v.", en_def: "putting food in the mouth and swallowing it", cn_def: "吃（進行式）" },
  "eggs": { pos: "n.", en_def: "round objects laid by birds, often eaten as food", cn_def: "蛋（複數）" },
  "elementary": { pos: "adj.", en_def: "basic; relating to the first years of school", cn_def: "初級的；小學的" },
  "entire": { pos: "adj.", en_def: "whole; complete", cn_def: "整個的" },
  "entirely": { pos: "adv.", en_def: "completely; fully", cn_def: "完全地" },
  "eucalyptus": { pos: "n.", en_def: "a tall tree with leaves that koalas eat", cn_def: "尤加利樹" },
  "evening": { pos: "n.", en_def: "the time at the end of the day", cn_def: "晚上" },
  "every": { pos: "adj.", en_def: "each one, with none left out", cn_def: "每一個" },
  "falling": { pos: "v.", en_def: "dropping down (the -ing form of fall)", cn_def: "落下（進行式）" },
  "family": { pos: "n.", en_def: "a group of parents and children", cn_def: "家庭" },
  "farmer": { pos: "n.", en_def: "a person who works on a farm", cn_def: "農夫" },
  "farmyard": { pos: "n.", en_def: "the area around farm buildings", cn_def: "農場院子" },
  "father": { pos: "n.", en_def: "a male parent", cn_def: "父親" },
  "feeds": { pos: "v.", en_def: "gives food to a person or animal", cn_def: "餵食" },
  "feels": { pos: "v.", en_def: "experiences a sensation or emotion", cn_def: "感覺" },
  "feet": { pos: "n.", en_def: "the parts of the body at the end of the legs", cn_def: "腳（複數）" },
  "fell": { pos: "v.", en_def: "dropped down (past tense of fall)", cn_def: "落下（fall的過去式）" },
  "felt": { pos: "v.", en_def: "experienced a feeling (past tense of feel)", cn_def: "感覺（feel的過去式）" },
  "fence": { pos: "n.", en_def: "a barrier made of wood or metal around an area", cn_def: "籬笆；圍欄" },
  "finally": { pos: "adv.", en_def: "after a long time; at last", cn_def: "終於" },
  "five": { pos: "n.", en_def: "the number 5", cn_def: "五" },
  "fluffy": { pos: "adj.", en_def: "soft and light, like fur or feathers", cn_def: "毛茸茸的" },
  "fly": { pos: "v.", en_def: "to move through the air", cn_def: "飛" },
  "followed": { pos: "v.", en_def: "went after or behind something", cn_def: "跟隨（過去式）" },
  "food": { pos: "n.", en_def: "things that people and animals eat", cn_def: "食物" },
  "forest": { pos: "n.", en_def: "a large area covered with trees", cn_def: "森林" },
  "found": { pos: "v.", en_def: "discovered something (past tense of find)", cn_def: "找到（find的過去式）" },
  "fresh": { pos: "adj.", en_def: "recently made or obtained; not old", cn_def: "新鮮的" },
  "front": { pos: "n.", en_def: "the part facing forward", cn_def: "前面" },
  "garden": { pos: "n.", en_def: "an area of land for growing plants", cn_def: "花園" },
  "gentle": { pos: "adj.", en_def: "kind and calm; not rough", cn_def: "溫和的" },
  "get": { pos: "v.", en_def: "to receive or obtain something", cn_def: "得到" },
  "give": { pos: "v.", en_def: "to hand something to someone", cn_def: "給" },
  "glided": { pos: "v.", en_def: "moved smoothly and quietly", cn_def: "滑行（過去式）" },
  "graceful": { pos: "adj.", en_def: "moving in a smooth, beautiful way", cn_def: "優雅的" },
  "grandmother": { pos: "n.", en_def: "the mother of your mother or father", cn_def: "祖母；奶奶" },
  "gray": { pos: "adj.", en_def: "having the color between black and white", cn_def: "灰色的" },
  "green": { pos: "adj.", en_def: "having the color of grass or leaves", cn_def: "綠色的" },
  "ground": { pos: "n.", en_def: "the solid surface of the earth", cn_def: "地面" },
  "grown": { pos: "v.", en_def: "become bigger (past participle of grow)", cn_def: "成長（grow的過去分詞）" },
  "grows": { pos: "v.", en_def: "becomes bigger over time", cn_def: "生長" },
  "hatch": { pos: "v.", en_def: "to break out of an egg", cn_def: "孵化" },
  "heavy": { pos: "adj.", en_def: "having a lot of weight", cn_def: "重的" },
  "hidden": { pos: "adj.", en_def: "kept out of sight; not easy to find", cn_def: "隱藏的" },
  "holiday": { pos: "n.", en_def: "a special day when people don't usually work", cn_def: "節日；假日" },
  "house": { pos: "n.", en_def: "a building where people live", cn_def: "房子" },
  "hungry": { pos: "adj.", en_def: "feeling a need or desire for food", cn_def: "飢餓的" },
  "lake": { pos: "n.", en_def: "a large area of fresh water surrounded by land", cn_def: "湖" },
  "landed": { pos: "v.", en_def: "came down to rest on a surface", cn_def: "降落（過去式）" },
  "large": { pos: "adj.", en_def: "big in size or amount", cn_def: "大的" },
  "leaves": { pos: "n.", en_def: "the flat green parts of a plant or tree", cn_def: "葉子（複數）" },
  "led": { pos: "v.", en_def: "guided someone (past tense of lead)", cn_def: "帶領（lead的過去式）" },
  "loud": { pos: "adj.", en_def: "making a lot of noise", cn_def: "大聲的" },
  "love": { pos: "v.", en_def: "to feel deep affection for someone or something", cn_def: "愛" },
  "meal": { pos: "n.", en_def: "the food eaten at one time, like breakfast or dinner", cn_def: "一餐" },
  "medicine": { pos: "n.", en_def: "something taken to treat an illness", cn_def: "藥" },
  "milk": { pos: "v.", en_def: "to take milk from a cow or other animal", cn_def: "擠奶" },
  "month": { pos: "n.", en_def: "one of the twelve parts of a year", cn_def: "月" },
  "morning": { pos: "n.", en_def: "the early part of the day", cn_def: "早上" },
  "mother": { pos: "n.", en_def: "a female parent", cn_def: "母親" },
  "mountains": { pos: "n.", en_def: "very high areas of land", cn_def: "山（複數）" },
  "muddy": { pos: "adj.", en_def: "covered with soft wet earth", cn_def: "泥濘的" },
  "napping": { pos: "v.", en_def: "sleeping for a short time", cn_def: "打瞌睡（進行式）" },
  "narrow": { pos: "adj.", en_def: "not wide", cn_def: "狹窄的" },
  "nest": { pos: "n.", en_def: "a place built by a bird to lay eggs", cn_def: "巢" },
  "newest": { pos: "adj.", en_def: "most recently made or arrived", cn_def: "最新的" },
  "old": { pos: "adj.", en_def: "having existed for a long time", cn_def: "老的；舊的" },
  "painting": { pos: "n.", en_def: "a picture made with paint", cn_def: "畫作" },
  "pair": { pos: "n.", en_def: "two things that go together", cn_def: "一對" },
  "paper": { pos: "n.", en_def: "thin material used for writing or wrapping", cn_def: "紙" },
  "park": { pos: "n.", en_def: "a public area with grass and trees for relaxing", cn_def: "公園" },
  "patiently": { pos: "adv.", en_def: "in a way that shows calm waiting", cn_def: "耐心地" },
  "pecked": { pos: "v.", en_def: "hit or bit something quickly with a beak", cn_def: "啄食（過去式）" },
  "picked": { pos: "v.", en_def: "chose or gathered something (past tense of pick)", cn_def: "挑選；摘（pick的過去式）" },
  "planted": { pos: "v.", en_def: "put a seed in the ground (past tense of plant)", cn_def: "栽種（plant的過去式）" },
  "plenty": { pos: "n.", en_def: "a large amount; more than enough", cn_def: "大量；充足" },
  "pond": { pos: "n.", en_def: "a small area of still water", cn_def: "池塘" },
  "porch": { pos: "n.", en_def: "a covered area at the entrance of a house", cn_def: "門廊" },
  "powerful": { pos: "adj.", en_def: "having great strength or force", cn_def: "強大的" },
  "pulled": { pos: "v.", en_def: "moved something toward you by force", cn_def: "拉（過去式）" },
  "red": { pos: "adj.", en_def: "having the color of blood", cn_def: "紅色的" },
  "repeat": { pos: "v.", en_def: "to say or do something again", cn_def: "重複" },
  "resting": { pos: "v.", en_def: "relaxing or sleeping (the -ing form of rest)", cn_def: "休息（進行式）" },
  "rings": { pos: "v.", en_def: "makes a clear ringing sound", cn_def: "響起" },
  "road": { pos: "n.", en_def: "a path made for vehicles to travel on", cn_def: "道路" },
  "roof": { pos: "n.", en_def: "the covering on top of a building", cn_def: "屋頂" },
  "running": { pos: "v.", en_def: "moving quickly on foot (the -ing form of run)", cn_def: "跑步（進行式）" },
  "sat": { pos: "v.", en_def: "rested on a seat (past tense of sit)", cn_def: "坐（sit的過去式）" },
  "says": { pos: "v.", en_def: "speaks words", cn_def: "說" },
  "school": { pos: "n.", en_def: "a place where students go to learn", cn_def: "學校" },
  "searching": { pos: "v.", en_def: "looking carefully for something", cn_def: "搜尋（進行式）" },
  "seeds": { pos: "n.", en_def: "small hard parts of a plant that grow into new plants", cn_def: "種子（複數）" },
  "shelter": { pos: "n.", en_def: "a place that gives protection, often for animals without homes", cn_def: "收容所；避難處" },
  "shirt": { pos: "n.", en_def: "a piece of clothing worn on the upper body", cn_def: "襯衫" },
  "shore": { pos: "n.", en_def: "the land along the edge of water", cn_def: "岸邊" },
  "sidewalk": { pos: "n.", en_def: "a paved path for walking beside a road", cn_def: "人行道" },
  "sings": { pos: "v.", en_def: "makes musical sounds with the voice", cn_def: "唱歌" },
  "sister": { pos: "n.", en_def: "a girl or woman with the same parents as you", cn_def: "姊妹" },
  "skin": { pos: "n.", en_def: "the outer covering of the body", cn_def: "皮膚" },
  "sleeps": { pos: "v.", en_def: "rests with eyes closed", cn_def: "睡覺" },
  "sleepy": { pos: "adj.", en_def: "feeling tired and ready to sleep", cn_def: "愛睡的；睏的" },
  "small": { pos: "adj.", en_def: "not large in size", cn_def: "小的" },
  "soft": { pos: "adj.", en_def: "not hard or rough to touch", cn_def: "柔軟的" },
  "special": { pos: "adj.", en_def: "not ordinary; different in a good way", cn_def: "特別的" },
  "spends": { pos: "v.", en_def: "uses time on something", cn_def: "度過" },
  "spring": { pos: "n.", en_def: "the season after winter, when plants grow", cn_def: "春天" },
  "stared": { pos: "v.", en_def: "looked for a long time without moving the eyes", cn_def: "凝視（過去式）" },
  "stepped": { pos: "v.", en_def: "moved by lifting and placing the foot", cn_def: "踏；走（過去式）" },
  "store": { pos: "v.", en_def: "to keep something safe for later use", cn_def: "儲存" },
  "strong": { pos: "adj.", en_def: "having a lot of physical power", cn_def: "強壯的" },
  "summer": { pos: "n.", en_def: "the warmest season of the year", cn_def: "夏天" },
  "sunlight": { pos: "n.", en_def: "light from the sun", cn_def: "陽光" },
  "sunrise": { pos: "n.", en_def: "the time when the sun comes up", cn_def: "日出" },
  "sunset": { pos: "n.", en_def: "the time when the sun goes down", cn_def: "日落" },
  "tall": { pos: "adj.", en_def: "having a great height", cn_def: "高的" },
  "taller": { pos: "adj.", en_def: "having more height than something else", cn_def: "更高的" },
  "taste": { pos: "n.", en_def: "the flavor of food in the mouth", cn_def: "味道" },
  "thick": { pos: "adj.", en_def: "having a large distance between two sides", cn_def: "厚的；粗的" },
  "tiny": { pos: "adj.", en_def: "very small", cn_def: "微小的" },
  "tomato": { pos: "n.", en_def: "a soft red fruit eaten as a vegetable", cn_def: "番茄" },
  "tomatoes": { pos: "n.", en_def: "more than one tomato", cn_def: "番茄（複數）" },
  "trail": { pos: "n.", en_def: "a path through nature", cn_def: "步道" },
  "tree's": { pos: "n.", en_def: "belonging to a tree", cn_def: "樹的" },
  "trees": { pos: "n.", en_def: "more than one tree", cn_def: "樹（複數）" },
  "uncle's": { pos: "n.", en_def: "belonging to your uncle", cn_def: "叔叔的" },
  "valley": { pos: "n.", en_def: "a low area of land between hills or mountains", cn_def: "山谷" },
  "village": { pos: "n.", en_def: "a small group of houses in the countryside", cn_def: "村莊" },
  "visitors": { pos: "n.", en_def: "people who visit a place", cn_def: "遊客（複數）" },
  "waiting": { pos: "v.", en_def: "staying in a place until something happens", cn_def: "等待（進行式）" },
  "walks": { pos: "v.", en_def: "moves on foot", cn_def: "走路" },
  "wander": { pos: "v.", en_def: "to move around without a clear direction", cn_def: "閒逛；漫步" },
  "warmest": { pos: "adj.", en_def: "having the most heat", cn_def: "最溫暖的" },
  "warned": { pos: "v.", en_def: "told someone about a possible danger", cn_def: "警告（過去式）" },
  "watched": { pos: "v.", en_def: "looked at something for a period of time", cn_def: "觀看（過去式）" },
  "water": { pos: "n.", en_def: "the clear liquid in rivers, lakes, and rain", cn_def: "水" },
  "waters": { pos: "v.", en_def: "gives water to plants", cn_def: "澆水" },
  "weekend": { pos: "n.", en_def: "Saturday and Sunday", cn_def: "週末" },
  "wet": { pos: "adj.", en_def: "covered or soaked with water", cn_def: "濕的" },
  "white": { pos: "adj.", en_def: "having the color of snow or milk", cn_def: "白色的" },
  "window": { pos: "n.", en_def: "an opening in a wall covered with glass", cn_def: "窗戶" },
  "windowsill": { pos: "n.", en_def: "the ledge at the bottom of a window", cn_def: "窗台" },
  "wooden": { pos: "adj.", en_def: "made of wood", cn_def: "木製的" },
  "word": { pos: "n.", en_def: "a unit of language with meaning", cn_def: "字；詞" },
  "work": { pos: "n.", en_def: "activity done to earn money or achieve something", cn_def: "工作" },
  "worked": { pos: "v.", en_def: "did a job or task", cn_def: "工作（過去式）" },
  "year": { pos: "n.", en_def: "a period of 12 months", cn_def: "年" },
  "yellow": { pos: "adj.", en_def: "having the color of a lemon or the sun", cn_def: "黃色的" },
  "young": { pos: "adj.", en_def: "not old; in an early stage of life", cn_def: "年輕的" },
  "zoo's": { pos: "n.", en_def: "belonging to a zoo", cn_def: "動物園的" },
};