// ============================================================
// Group 43 Quiz Data: Home / Household / Objects, Part 5 (FINAL)
// Full word set (34 words) — miscellaneous objects, festivals
// and celebrations, and education levels, completing the
// "home / household / objects" theme (178 words total).
// Continues from Group 42 (Home & Household, Part 4). This is
// the fifth and final of 5 groups (39-43) covering this theme.
// Continues the simpler/shorter MCQ style introduced in
// Group 37 (~16-26 words, 2 sentences, one blank).
// Note: the spreadsheet has "bitrhday" as a misspelling of
// "birthday" (confirmed by the 生日 Chinese gloss); corrected
// here with the proper spelling and definition.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 43 - Home / Household, Part 5 (居家環境 五)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (34 words) ----
const VOCAB = [
  { word: "key", pos: "n.", cn_def: "鑰匙", en_def: "a metal tool used to lock or unlock something",
    sentence: "He searched his pockets for the {{BLANK}} to the front door.",
    cn: "他在口袋裡找前門的鑰匙。" },
  { word: "kite", pos: "n.", cn_def: "風箏", en_def: "a light toy flown in the wind on a string",
    sentence: "The children ran across the field flying a colorful {{BLANK}}.",
    cn: "孩子們在田野間奔跑放著一個色彩鮮豔的風箏。" },
  { word: "lantern", pos: "n.", cn_def: "燈籠", en_def: "a light that can be carried or hung up",
    sentence: "They hung a glowing paper {{BLANK}} outside the front door.",
    cn: "他們在門外掛了一個發亮的紙燈籠。" },
  { word: "mat", pos: "n.", cn_def: "草蓆", en_def: "a thick flat covering placed on a floor",
    sentence: "She wiped her shoes on the {{BLANK}} before entering the house.",
    cn: "她在進屋前先在草蓆上擦了擦鞋子。" },
  { word: "needle", pos: "n.", cn_def: "針", en_def: "a thin, sharp tool used for sewing",
    sentence: "She threaded the {{BLANK}} carefully to fix the torn shirt.",
    cn: "她小心地把線穿過針來修補破掉的襯衫。" },
  { word: "net", pos: "n.", cn_def: "網子", en_def: "a material with open spaces, used to catch things",
    sentence: "He used a small {{BLANK}} to scoop the goldfish from the tank.",
    cn: "他用一個小網子把金魚從魚缸裡撈出來。" },
  { word: "package", pos: "n.", cn_def: "包裹", en_def: "a wrapped or boxed item sent through the mail",
    sentence: "She was excited to receive a {{BLANK}} from her grandmother.",
    cn: "她很興奮收到奶奶寄來的一個包裹。" },
  { word: "pipe", pos: "n.", cn_def: "管子", en_def: "a long, hollow tube used to carry liquid or gas",
    sentence: "Water dripped from a small crack in the old {{BLANK}}.",
    cn: "水從這條老舊管子的一個小裂縫滴落。" },
  { word: "raincoat", pos: "n.", cn_def: "雨衣", en_def: "a coat worn to stay dry in the rain",
    sentence: "She put on her yellow {{BLANK}} before walking to school.",
    cn: "她在走去學校前穿上了她的黃色雨衣。" },
  { word: "rope", pos: "n.", cn_def: "繩索", en_def: "a strong, thick cord used for tying or pulling",
    sentence: "The sailors used a thick {{BLANK}} to tie the boat to the dock.",
    cn: "水手們用一條粗繩把船綁在碼頭上。" },
  { word: "ticket", pos: "n.", cn_def: "票券", en_def: "a piece of paper that allows you to enter or travel",
    sentence: "He showed his {{BLANK}} to the guard before entering the stadium.",
    cn: "他在進入體育場前向警衛出示了他的票券。" },
  { word: "toy", pos: "n.", cn_def: "玩具", en_def: "an object made for children to play with",
    sentence: "The little boy hugged his favorite {{BLANK}} before falling asleep.",
    cn: "小男孩抱著他最喜歡的玩具就睡著了。" },
  { word: "tube", pos: "n.", cn_def: "管子", en_def: "a long, hollow cylinder used to hold or carry things",
    sentence: "She squeezed the last bit of toothpaste from the {{BLANK}}.",
    cn: "她把牙膏管裡最後一點牙膏擠了出來。" },
  { word: "umbrella", pos: "n.", cn_def: "雨傘", en_def: "a device used to protect yourself from rain",
    sentence: "He opened his {{BLANK}} as soon as the rain started to fall.",
    cn: "雨一開始下他就打開了雨傘。" },
  { word: "wheel", pos: "n.", cn_def: "輪胎", en_def: "a round object that turns to allow a vehicle to move",
    sentence: "He checked the air in every {{BLANK}} before the long drive.",
    cn: "他在長途開車前檢查了每個輪胎的氣壓。" },
  { word: "festival", pos: "n.", cn_def: "節日", en_def: "a special day or time of celebration",
    sentence: "The whole town gathers for the lantern {{BLANK}} every year.",
    cn: "全鎮的人每年都會聚集參加燈籠節。" },
  { word: "Easter", pos: "n.", cn_def: "復活節", en_def: "a spring holiday celebrated by Christians",
    sentence: "The children searched the garden for colorful {{BLANK}} eggs.",
    cn: "孩子們在花園裡尋找色彩鮮豔的復活節彩蛋。" },
  { word: "Halloween", pos: "n.", cn_def: "萬聖節", en_def: "a holiday in October when people wear costumes",
    sentence: "She dressed up as a witch for the {{BLANK}} party.",
    cn: "她在萬聖節派對上裝扮成女巫。" },
  { word: "birthday", pos: "n.", cn_def: "生日", en_def: "the day of the year when a person was born",
    sentence: "We baked a chocolate cake for her {{BLANK}} this weekend.",
    cn: "我們這個週末為她的生日烤了一個巧克力蛋糕。" },
  { word: "balloon", pos: "n.", cn_def: "汽球", en_def: "a colorful bag filled with air, used for decoration",
    sentence: "She tied a bright red {{BLANK}} to the back of her chair.",
    cn: "她把一個鮮紅色的氣球綁在她椅子的後面。" },
  { word: "candle", pos: "n.", cn_def: "蠟燭", en_def: "a stick of wax with a wick, burned to give light",
    sentence: "She blew out every {{BLANK}} on her birthday cake.",
    cn: "她吹熄了生日蛋糕上的每一根蠟燭。" },
  { word: "card", pos: "n.", cn_def: "卡片", en_def: "a small piece of stiff paper with a message or picture",
    sentence: "He wrote a kind {{BLANK}} for his teacher's retirement.",
    cn: "他為老師的退休寫了一張溫馨的卡片。" },
  { word: "gift", pos: "n.", cn_def: "禮物", en_def: "something given to someone without payment",
    sentence: "She wrapped the {{BLANK}} carefully in shiny paper.",
    cn: "她小心地用閃亮的紙包好禮物。" },
  { word: "party", pos: "n.", cn_def: "派對", en_def: "a social event where people gather to celebrate",
    sentence: "They decorated the whole room for the surprise {{BLANK}}.",
    cn: "他們把整個房間都裝飾好來辦這場驚喜派對。" },
  { word: "bless", pos: "v.", cn_def: "祝福", en_def: "to wish someone well or ask for divine favor",
    sentence: "The grandmother stopped to {{BLANK}} her grandchildren before they left.",
    cn: "奶奶在孫子們離開前停下來祝福他們。" },
  { word: "celebrate", pos: "v.", cn_def: "慶祝", en_def: "to do something special to mark an important event",
    sentence: "Our whole family gathered to {{BLANK}} my grandfather's birthday.",
    cn: "我們全家聚在一起慶祝爺爺的生日。" },
  { word: "cheer", pos: "v.", cn_def: "為…歡呼、鼓舞", en_def: "to shout with joy or encouragement",
    sentence: "The crowd began to {{BLANK}} loudly when the team scored.",
    cn: "球隊得分時，觀眾開始大聲歡呼。" },
  { word: "education", pos: "n.", cn_def: "教育", en_def: "the process of teaching and learning",
    sentence: "She believes a good {{BLANK}} can change a person's future.",
    cn: "她相信良好的教育能改變一個人的未來。" },
  { word: "university", pos: "n.", cn_def: "大學", en_def: "a school for higher learning after high school",
    sentence: "He hopes to study engineering at a top {{BLANK}}.",
    cn: "他希望能在一所頂尖的大學學習工程學。" },
  { word: "college", pos: "n.", cn_def: "學院", en_def: "a school for education beyond high school",
    sentence: "She is excited to start {{BLANK}} this coming fall.",
    cn: "她很期待今年秋天開始上大學。" },
  { word: "senior high school", pos: "n.", cn_def: "高中", en_def: "a school for students in grades ten through twelve",
    sentence: "My older brother just started his first year of {{BLANK}}.",
    cn: "我哥哥剛開始讀高中一年級。" },
  { word: "junior high school", pos: "n.", cn_def: "國中", en_def: "a school for students in grades seven through nine",
    sentence: "All the students in {{BLANK}} take the same basic subjects.",
    cn: "所有國中學生都修讀相同的基礎科目。" },
  { word: "elementary school", pos: "n.", cn_def: "小學", en_def: "a school for young children, usually grades one through six",
    sentence: "She still remembers her favorite teacher from {{BLANK}}.",
    cn: "她仍然記得小學時最喜歡的老師。" },
  { word: "kindergarten", pos: "n.", cn_def: "幼稚園", en_def: "a school for very young children before elementary school",
    sentence: "He cried on his very first day of {{BLANK}}.",
    cn: "他幼稚園的第一天哭了。" }
];

// ---- Part 2 data: 34 MCQs ----
// Continuing the simpler/shorter MCQ style from Group 37:
// ~16-26 words, exactly 2 sentences, one blank, 4 options.
// Answer letters balanced across A/B/C/D, no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "He was locked out and couldn't get inside the house. He searched his pockets for the ______ to the door.",
    options: ["key", "rope", "needle", "net"], answer: 0, vocabIndex: 0 },
  { q: "It was a windy afternoon at the open park. The children ran across the field flying a colorful ______.",
    options: ["balloon", "kite", "flag", "umbrella"], answer: 1, vocabIndex: 1 },
  { q: "It was getting dark outside their front entrance. They hung a glowing paper ______ outside the door.",
    options: ["candle", "flag", "lantern", "flashlight"], answer: 2, vocabIndex: 2 },
  { q: "The ground outside was muddy after the rain. She wiped her shoes on the ______ before entering the house.",
    options: ["towel", "rope", "net", "mat"], answer: 3, vocabIndex: 3 },
  { q: "A small tear appeared in her brother's favorite shirt. She threaded the ______ carefully to fix it.",
    options: ["needle", "rope", "pipe", "key"], answer: 0, vocabIndex: 4 },
  { q: "He wanted to catch the fish swimming around in the tank. He used a small ______ to scoop it out.",
    options: ["rope", "net", "tube", "pipe"], answer: 1, vocabIndex: 5 },
  { q: "A mail truck stopped outside her house that afternoon. She was excited to receive a ______ from her grandmother.",
    options: ["card", "letter", "package", "gift"], answer: 2, vocabIndex: 6 },
  { q: "Something old in the wall needed repair. Water dripped from a small crack in the old ______.",
    options: ["tube", "rope", "net", "pipe"], answer: 3, vocabIndex: 7 },
  { q: "The sky looked cloudy as she got ready for school. She put on her yellow ______ before leaving.",
    options: ["raincoat", "umbrella", "jacket", "mat"], answer: 0, vocabIndex: 8 },
  { q: "The fishing boat needed to stay secured at the dock. The sailors used a thick ______ to tie it down.",
    options: ["net", "rope", "pipe", "tube"], answer: 1, vocabIndex: 9 },
  { q: "Security checked everyone entering the stadium that day. He showed his ______ to the guard before going in.",
    options: ["card", "key", "ticket", "stamp"], answer: 2, vocabIndex: 10 },
  { q: "Bedtime was always the same for the little boy each night. He hugged his favorite ______ before falling asleep.",
    options: ["pillow", "blanket", "book", "toy"], answer: 3, vocabIndex: 11 },
  { q: "She noticed there wasn't much toothpaste left this morning. She squeezed the last bit out of the ______.",
    options: ["tube", "pipe", "bottle", "can"], answer: 0, vocabIndex: 12 },
  { q: "Dark clouds appeared just as he stepped outside. He opened his ______ as soon as it started raining.",
    options: ["raincoat", "umbrella", "hat", "jacket"], answer: 1, vocabIndex: 13 },
  { q: "He was getting the car ready for a long road trip. He checked the air in every ______ first.",
    options: ["pipe", "tire", "wheel", "tube"], answer: 2, vocabIndex: 14 },
  { q: "Every year, colorful lanterns fill the town square in spring. The whole town gathers for the lantern ______.",
    options: ["party", "celebration", "holiday", "festival"], answer: 3, vocabIndex: 15 },
  { q: "Spring had finally arrived, and the garden was full of surprises. The children searched it for colorful ______ eggs.",
    options: ["Easter", "holiday", "spring", "festival"], answer: 0, vocabIndex: 16 },
  { q: "She wanted a spooky look for the school costume contest. She dressed up as a witch for the ______ party.",
    options: ["Easter", "Halloween", "birthday", "festival"], answer: 1, vocabIndex: 17 },
  { q: "It was a special day worth celebrating with something sweet. We baked a chocolate cake for her ______ this weekend.",
    options: ["festival", "party", "birthday", "holiday"], answer: 2, vocabIndex: 18 },
  { q: "She wanted to decorate her seat for the celebration. She tied a bright red ______ to the back of her chair.",
    options: ["flag", "ribbon", "card", "balloon"], answer: 3, vocabIndex: 19 },
  { q: "Everyone gathered around the table singing happily that evening. She blew out every ______ on her birthday cake.",
    options: ["candle", "lantern", "light", "flame"], answer: 0, vocabIndex: 20 },
  { q: "Her teacher was leaving the school after many years of service. He wrote a kind ______ for the occasion.",
    options: ["letter", "card", "note", "page"], answer: 1, vocabIndex: 21 },
  { q: "She wanted her present to look special before giving it. She wrapped the ______ carefully in shiny paper.",
    options: ["box", "card", "gift", "package"], answer: 2, vocabIndex: 22 },
  { q: "It was someone's special day, and the room needed to look exciting. They decorated it for the surprise ______.",
    options: ["festival", "celebration", "holiday", "party"], answer: 3, vocabIndex: 23 },
  { q: "Before her grandchildren left for their trip, she had something kind to say. She stopped to ______ them.",
    options: ["bless", "thank", "greet", "praise"], answer: 0, vocabIndex: 24 },
  { q: "It was an important date on the family calendar that year. Our whole family gathered to ______ my grandfather's birthday.",
    options: ["plan", "celebrate", "remember", "discuss"], answer: 1, vocabIndex: 25 },
  { q: "The stadium grew loud the moment the ball went in. The crowd began to ______ loudly when the team scored.",
    options: ["cry", "clap", "cheer", "shout"], answer: 2, vocabIndex: 26 },
  { q: "She has always believed strongly in the power of learning. She believes a good ______ can change a person's future.",
    options: ["job", "career", "skill", "education"], answer: 3, vocabIndex: 27 },
  { q: "He has always dreamed of designing bridges and buildings. He hopes to study engineering at a top ______.",
    options: ["university", "college", "kindergarten", "academy"], answer: 0, vocabIndex: 28 },
  { q: "She just finished high school and is excited for what's next. She is excited to start ______ this coming fall.",
    options: ["kindergarten", "college", "elementary school", "preschool"], answer: 1, vocabIndex: 29 },
  { q: "He just moved up a level in his schooling this year. My older brother just started his first year of ______.",
    options: ["college", "kindergarten", "senior high school", "university"], answer: 2, vocabIndex: 30 },
  { q: "Every student in this age group studies similar core subjects. All the students in ______ take the same basic subjects.",
    options: ["college", "kindergarten", "university", "junior high school"], answer: 3, vocabIndex: 31 },
  { q: "She often thinks fondly about her younger school years. She still remembers her favorite teacher from ______.",
    options: ["elementary school", "kindergarten", "college", "university"], answer: 0, vocabIndex: 32 },
  { q: "Leaving his parents for the first time felt scary for the little boy. He cried on his very first day of ______.",
    options: ["elementary school", "kindergarten", "college", "university"], answer: 1, vocabIndex: 33 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "academy": { pos: "n.", en_def: "a school, especially one for special training", cn_def: "學院；訓練學校" },
  "blanket": { pos: "n.", en_def: "a covering used to keep warm in bed", cn_def: "毯子" },
  "book": { pos: "n.", en_def: "a set of printed pages bound together", cn_def: "書本" },
  "bottle": { pos: "n.", en_def: "a container used for holding liquids", cn_def: "瓶子" },
  "box": { pos: "n.", en_def: "a square or rectangular container", cn_def: "盒子" },
  "calendar": { pos: "n.", en_def: "a chart showing the days, weeks, and months of a year", cn_def: "日(月)曆" },
  "can": { pos: "n.", en_def: "a sealed metal container for food or drink", cn_def: "罐頭" },
  "career": { pos: "n.", en_def: "a person's long-term job or profession", cn_def: "職業生涯" },
  "celebration": { pos: "n.", en_def: "an event held to celebrate something", cn_def: "慶祝活動" },
  "clap": { pos: "v.", en_def: "to hit your hands together to show approval", cn_def: "拍手" },
  "costume": { pos: "n.", en_def: "clothing worn to look like a different character", cn_def: "服裝；裝扮" },
  "crack": { pos: "n.", en_def: "a thin line where something has broken", cn_def: "裂縫" },
  "cry": { pos: "v.", en_def: "to produce tears, usually because of sadness or pain", cn_def: "哭泣" },
  "discuss": { pos: "v.", en_def: "to talk about something with another person or group", cn_def: "討論" },
  "dock": { pos: "n.", en_def: "a platform where boats are tied up", cn_def: "碼頭" },
  "engineering": { pos: "n.", en_def: "the study of designing and building structures and machines", cn_def: "工程學" },
  "entrance": { pos: "n.", en_def: "the way into a place", cn_def: "入口" },
  "flag": { pos: "n.", en_def: "a piece of cloth with a design, used as a symbol", cn_def: "旗子" },
  "flame": { pos: "n.", en_def: "the bright, hot part of a fire", cn_def: "火焰" },
  "flashlight": { pos: "n.", en_def: "a small light powered by batteries that you can carry", cn_def: "手電筒" },
  "greet": { pos: "v.", en_def: "to say hello or welcome someone", cn_def: "問候" },
  "guard": { pos: "n.", en_def: "a person who protects a place or watches over it", cn_def: "警衛" },
  "hat": { pos: "n.", en_def: "a covering worn on the head", cn_def: "帽子" },
  "holiday": { pos: "n.", en_def: "a day of celebration or rest from work or school", cn_def: "假日" },
  "jacket": { pos: "n.", en_def: "a short coat", cn_def: "夾克" },
  "job": { pos: "n.", en_def: "the work a person does for pay", cn_def: "工作" },
  "letter": { pos: "n.", en_def: "a written message sent to someone", cn_def: "信" },
  "light": { pos: "n.", en_def: "a source of brightness", cn_def: "燈；光" },
  "note": { pos: "n.", en_def: "a short piece of writing to remember something", cn_def: "筆記" },
  "occasion": { pos: "n.", en_def: "a special event or time", cn_def: "場合；時機" },
  "page": { pos: "n.", en_def: "one side of a sheet of paper in a book", cn_def: "頁" },
  "pillow": { pos: "n.", en_def: "a soft cushion used to support your head while sleeping", cn_def: "枕頭" },
  "plan": { pos: "v.", en_def: "to decide in advance what to do", cn_def: "計畫" },
  "praise": { pos: "v.", en_def: "to say good things about someone's work or behavior", cn_def: "讚美" },
  "preschool": { pos: "n.", en_def: "a school for very young children before kindergarten", cn_def: "學前班" },
  "remember": { pos: "v.", en_def: "to keep information in your mind or recall it", cn_def: "記得" },
  "retirement": { pos: "n.", en_def: "the act of stopping work, usually due to age", cn_def: "退休" },
  "ribbon": { pos: "n.", en_def: "a long, thin strip of material used for decoration", cn_def: "緞帶" },
  "sailors": { pos: "n.", en_def: "people who work on a ship", cn_def: "水手（複數）" },
  "secured": { pos: "v.", en_def: "made something safe or firmly fixed in place", cn_def: "固定；確保安全（過去式）" },
  "service": { pos: "n.", en_def: "years of work done for an employer", cn_def: "服務（年資）" },
  "shout": { pos: "v.", en_def: "to say something very loudly", cn_def: "大喊" },
  "skill": { pos: "n.", en_def: "the ability to do something well", cn_def: "技能" },
  "spooky": { pos: "adj.", en_def: "causing fear; eerie", cn_def: "陰森的；嚇人的" },
  "spring": { pos: "n.", en_def: "the season after winter and before summer", cn_def: "春天" },
  "stadium": { pos: "n.", en_def: "a large structure used for sports events", cn_def: "體育場" },
  "stamp": { pos: "n.", en_def: "a small piece of paper stuck on mail to pay for postage", cn_def: "郵票" },
  "tear": { pos: "n.", en_def: "a hole made by ripping", cn_def: "破洞" },
  "thank": { pos: "v.", en_def: "to express gratitude to someone", cn_def: "感謝" },
  "tire": { pos: "n.", en_def: "a rubber covering on a wheel", cn_def: "輪胎（外胎）" },
  "torn": { pos: "adj.", en_def: "ripped or damaged by pulling apart", cn_def: "破損的" },
  "towel": { pos: "n.", en_def: "a piece of cloth used to dry yourself", cn_def: "毛巾" },
  "town square": { pos: "n.", en_def: "an open public area in the center of a town", cn_def: "市鎮廣場" },
  "witch": { pos: "n.", en_def: "a woman believed to have magical powers, often in stories", cn_def: "女巫" },
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
