// ============================================================
// Group 35 Quiz Data: Actions, Part 4
// Full word set (36 words) — the fourth portion of the
// "actions" theme (252-word flat verb list). Continues from
// Group 34 (Actions, Part 3). Split into 7 groups of 36 words
// each (Groups 32-38) per the person's request.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 35 - Actions, Part 4 (動作 四)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (36 words) ----
const VOCAB = [
  { word: "enter", pos: "v.", cn_def: "進入", en_def: "to come or go into a place",
    sentence: "Please remember to {{BLANK}} the building through the main front door.",
    cn: "請記得從主要的前門進入這棟建築物。" },
  { word: "equal", pos: "v.", cn_def: "等於", en_def: "to be exactly the same in amount or value",
    sentence: "Two plus two will always {{BLANK}} four no matter how you count it.",
    cn: "無論怎麼算，二加二永遠等於四。" },
  { word: "excite", pos: "v.", cn_def: "使興奮", en_def: "to make someone feel very happy or eager",
    sentence: "The thought of the upcoming trip began to {{BLANK}} the whole family.",
    cn: "想到即將到來的旅行讓全家人都感到興奮。" },
  { word: "exist", pos: "v.", cn_def: "存在", en_def: "to be real or actually happen",
    sentence: "Many people doubt that such a friendly giant creature could really {{BLANK}}.",
    cn: "許多人懷疑這麼友善的巨大生物是否真的存在。" },
  { word: "fall", pos: "v.", cn_def: "落下", en_def: "to drop down from a higher place",
    sentence: "Bright orange leaves began to {{BLANK}} from the trees every October morning.",
    cn: "每年十月的早晨，橙色的葉子開始從樹上落下。" },
  { word: "feed", pos: "v.", cn_def: "餵食", en_def: "to give food to a person or animal",
    sentence: "My little sister loves to {{BLANK}} the ducks at the park on Sundays.",
    cn: "我妹妹很喜歡星期天在公園餵鴨子。" },
  { word: "fight", pos: "v.", cn_def: "打架", en_def: "to use physical force against someone in a struggle",
    sentence: "The two boys started to {{BLANK}} over who would get the last seat.",
    cn: "兩個男孩為了搶最後一個座位而開始打架。" },
  { word: "fill", pos: "v.", cn_def: "充滿", en_def: "to make something full by putting things into it",
    sentence: "She asked her son to {{BLANK}} the watering can before tending the garden.",
    cn: "她要兒子在照顧花園前先把灑水壺裝滿水。" },
  { word: "finish", pos: "v.", cn_def: "結束", en_def: "to come to the end of doing something",
    sentence: "We need to {{BLANK}} our homework before dinner is ready tonight.",
    cn: "我們需要在今晚晚餐準備好之前完成作業。" },
  { word: "fix", pos: "v.", cn_def: "固定", en_def: "to repair something that is broken",
    sentence: "My uncle promised to {{BLANK}} the leaking faucet sometime this weekend.",
    cn: "我叔叔答應這個週末會修理那個漏水的水龍頭。" },
  { word: "fly", pos: "v.", cn_def: "飛", en_def: "to move through the air, especially with wings",
    sentence: "Hundreds of geese {{BLANK}} south together every year before winter arrives.",
    cn: "每年冬天來臨前，數百隻雁會一起向南飛。" },
  { word: "focus", pos: "v.", cn_def: "專注", en_def: "to give all your attention to one thing",
    sentence: "It's hard to {{BLANK}} on homework when the television is so loud nearby.",
    cn: "當電視聲音這麼大時，很難專注在作業上。" },
  { word: "follow", pos: "v.", cn_def: "遵守", en_def: "to obey or act according to a rule or instruction",
    sentence: "All visitors to the museum must {{BLANK}} the posted safety rules.",
    cn: "所有參觀博物館的訪客都必須遵守公告的安全規則。" },
  { word: "frighten", pos: "v.", cn_def: "使害怕", en_def: "to make someone feel afraid",
    sentence: "A sudden loud thunderclap began to {{BLANK}} the sleeping puppy outside.",
    cn: "突然一聲響亮的雷聲讓外面睡覺的小狗感到害怕。" },
  { word: "get", pos: "v.", cn_def: "得到", en_def: "to receive or obtain something",
    sentence: "She was thrilled to {{BLANK}} a new bicycle for her birthday this year.",
    cn: "她很高興今年生日得到了一台新的自行車。" },
  { word: "give", pos: "v.", cn_def: "送給", en_def: "to hand something to someone or provide it to them",
    sentence: "Every winter, our class likes to {{BLANK}} warm blankets to the local shelter.",
    cn: "每年冬天，我們班都喜歡送溫暖的毛毯給當地的收容所。" },
  { word: "greet", pos: "v.", cn_def: "問候", en_def: "to say hello or welcome someone",
    sentence: "The shopkeeper always stops to {{BLANK}} every customer with a warm smile.",
    cn: "店主總是會停下來用溫暖的笑容問候每位顧客。" },
  { word: "guide", pos: "v.", cn_def: "引導", en_def: "to show someone the way or help direct them",
    sentence: "A friendly local offered to {{BLANK}} the lost tourists back to their hotel.",
    cn: "一位友善的當地人主動引導迷路的遊客回到他們的旅館。" },
  { word: "hammer", pos: "v.", cn_def: "敲打", en_def: "to hit something repeatedly with a heavy tool",
    sentence: "The carpenter began to {{BLANK}} the nails carefully into the wooden frame.",
    cn: "木匠開始小心地把釘子敲進木製框架裡。" },
  { word: "handle", pos: "v.", cn_def: "處理", en_def: "to deal with or manage a situation or task",
    sentence: "The new manager seemed calm and ready to {{BLANK}} any sudden problem.",
    cn: "這位新經理看起來很冷靜，準備好處理任何突發問題。" },
  { word: "hang", pos: "v.", cn_def: "把…掛起", en_def: "to attach something so it stays above the ground",
    sentence: "We decided to {{BLANK}} the new painting right above the living room sofa.",
    cn: "我們決定把新畫掛在客廳沙發上方。" },
  { word: "happen", pos: "v.", cn_def: "發生", en_def: "to take place; to occur",
    sentence: "Nobody really knows what will {{BLANK}} at tomorrow's surprise school assembly.",
    cn: "沒有人真正知道明天的驚喜全校集會會發生什麼事。" },
  { word: "have", pos: "v.", cn_def: "有", en_def: "to own, possess, or hold something",
    sentence: "Most students in this class {{BLANK}} at least one pet at home.",
    cn: "這個班上大多數學生家裡都有至少一隻寵物。" },
  { word: "help", pos: "v.", cn_def: "幫助", en_def: "to make it easier for someone to do something",
    sentence: "My older brother always offers to {{BLANK}} me with my math homework.",
    cn: "我哥哥總是主動幫我做數學作業。" },
  { word: "hide", pos: "v.", cn_def: "把…藏起來", en_def: "to put something where it cannot be seen",
    sentence: "The children loved to {{BLANK}} behind the curtains during the noisy game.",
    cn: "孩子們在這個吵鬧的遊戲中喜歡躲在窗簾後面。" },
  { word: "hold", pos: "v.", cn_def: "舉行", en_def: "to organize and carry out an event",
    sentence: "Our school plans to {{BLANK}} the annual sports day next Friday afternoon.",
    cn: "我們學校計畫下星期五下午舉行年度運動會。" },
  { word: "hug", pos: "v.", cn_def: "擁抱", en_def: "to put your arms around someone closely",
    sentence: "She ran across the airport to {{BLANK}} her grandmother tightly after the long flight.",
    cn: "她跑過機場，緊緊擁抱她那長途飛行後抵達的祖母。" },
  { word: "hunt", pos: "v.", cn_def: "狩獵", en_def: "to chase and try to catch an animal for food",
    sentence: "Wild foxes often {{BLANK}} small rabbits near the edge of the forest.",
    cn: "野生狐狸經常在森林邊緣狩獵小兔子。" },
  { word: "hurry", pos: "v.", cn_def: "急忙", en_def: "to move or act quickly",
    sentence: "We had to {{BLANK}} to the station to catch the last train home.",
    cn: "我們必須急忙趕到車站才能搭上最後一班回家的火車。" },
  { word: "ignore", pos: "v.", cn_def: "忽視", en_def: "to deliberately not pay attention to something",
    sentence: "It's never a good idea to {{BLANK}} a strange noise coming from your car.",
    cn: "忽視車子發出的奇怪聲音絕對不是個好主意。" },
  { word: "imagine", pos: "v.", cn_def: "想像", en_def: "to form a picture or idea in your mind",
    sentence: "Close your eyes and try to {{BLANK}} a quiet beach at sunset.",
    cn: "閉上眼睛，試著想像一個日落時寧靜的海灘。" },
  { word: "improve", pos: "v.", cn_def: "改善", en_def: "to make something better than before",
    sentence: "Daily practice has really helped {{BLANK}} her confidence speaking in front of the class.",
    cn: "每天練習確實幫助改善了她在全班面前說話的自信。" },
  { word: "include", pos: "v.", cn_def: "包含", en_def: "to have something as a part of a whole",
    sentence: "Our weekend trip package will {{BLANK}} two nights at a cozy mountain cabin.",
    cn: "我們的週末旅遊套餐將包含兩晚舒適的山中小屋住宿。" },
  { word: "indicate", pos: "v.", cn_def: "指出", en_def: "to point out or show information about something",
    sentence: "The flashing red light began to {{BLANK}} a serious problem with the engine.",
    cn: "閃爍的紅燈開始指出引擎有嚴重問題。" },
  { word: "show", pos: "v.", cn_def: "顯示", en_def: "to let someone see something",
    sentence: "Could you please {{BLANK}} me how to fold this paper crane correctly?",
    cn: "你可以教我（顯示給我看）如何正確地折這隻紙鶴嗎？" },
  { word: "insist", pos: "v.", cn_def: "堅持", en_def: "to demand something firmly and refuse to change your mind",
    sentence: "Despite her tiredness, she continued to {{BLANK}} on finishing the race herself.",
    cn: "儘管她很疲憊，她仍堅持要自己完成這場比賽。" }
];

// ---- Part 2 data: 36 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~27-32 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// 4 options per question, answer letters balanced across A/B/C/D,
// no adjacent repeats. vocabIndex points to the exact VOCAB entry.
const MCQS = [
  { q: "Arriving at the school gate just as the morning bell rang, the rushing students pushed gently toward the open entryway. Please remember to ______ the building through the main front door each morning.",
    options: ["enter", "exist", "excite", "equal"], answer: 0, vocabIndex: 0 },
  { q: "Checking her math homework with a calculator beside her notebook, the careful student double-checked every single answer twice. Two plus two will always ______ four no matter how you count it.",
    options: ["fall", "equal", "fill", "fix"], answer: 1, vocabIndex: 1 },
  { q: "Talking nonstop about packing lists and plane tickets at dinner every night for a week, everyone could hardly sit still. The thought of the upcoming trip began to ______ the whole family completely.",
    options: ["frighten", "ignore", "excite", "handle"], answer: 2, vocabIndex: 2 },
  { q: "Reading old legends passed down through generations about a gentle giant living deep in the misty mountains, skeptics shake their heads. Many people doubt that such a friendly giant creature could really ______.",
    options: ["equal", "excite", "improve", "exist"], answer: 3, vocabIndex: 3 },
  { q: "Walking beneath rows of tall maple trees lining the quiet street, the children noticed the colorful canopy slowly thinning each week. Bright orange leaves began to ______ from the trees every October morning.",
    options: ["fall", "fly", "fight", "fix"], answer: 0, vocabIndex: 4 },
  { q: "Carrying a small bag of bread crumbs to the pond every weekend, the cheerful girl never missed her favorite Sunday routine. My little sister loves to ______ the ducks at the park on Sundays.",
    options: ["guide", "feed", "hammer", "hunt"], answer: 1, vocabIndex: 5 },
  { q: "Pushing and shoving near the last empty chair in the crowded classroom, tempers quickly rose between the two restless classmates. The two boys started to ______ over who would get the last seat.",
    options: ["follow", "focus", "fight", "finish"], answer: 2, vocabIndex: 6 },
  { q: "Standing beside the dry flowerbeds with an empty container in hand, she reminded her son about an important first step. She asked her son to ______ the watering can before tending the garden.",
    options: ["fix", "fly", "feed", "fill"], answer: 3, vocabIndex: 7 },
  { q: "Glancing at the clock above the stove while pencils scratched quickly across half-finished worksheets, the siblings raced against time. We need to ______ our homework before dinner is ready tonight.",
    options: ["finish", "fill", "follow", "fall"], answer: 0, vocabIndex: 8 },
  { q: "Hearing the steady drip echo through the quiet kitchen for nearly a week, the patient homeowner finally called for help. My uncle promised to ______ the leaking faucet sometime this weekend.",
    options: ["hide", "fix", "hold", "hang"], answer: 1, vocabIndex: 9 },
  { q: "Forming a perfect V shape high above the cold fields as autumn winds picked up speed, the noisy flock pressed onward. Hundreds of geese ______ south together every year before winter arrives.",
    options: ["fall", "fight", "fly", "follow"], answer: 2, vocabIndex: 10 },
  { q: "Sitting cross-legged on his bedroom floor with the volume turned up far too high in the next room, he sighed loudly. It's hard to ______ on homework when the television is so loud nearby.",
    options: ["follow", "fix", "finish", "focus"], answer: 3, vocabIndex: 11 },
  { q: "Walking past large signs posted near every exhibit warning against touching the fragile ancient artifacts, the guide repeated the same reminder. All visitors to the museum must ______ the posted safety rules carefully.",
    options: ["follow", "guide", "greet", "hammer"], answer: 0, vocabIndex: 12 },
  { q: "Crashing suddenly through the quiet night sky right above the backyard fence, the unexpected noise sent the small animal scurrying. A sudden loud thunderclap began to ______ the sleeping puppy outside immediately.",
    options: ["excite", "frighten", "improve", "indicate"], answer: 1, vocabIndex: 13 },
  { q: "Unwrapping the shiny paper slowly with her family gathered closely around the kitchen table, she gasped at the surprise inside. She was thrilled to ______ a new bicycle for her birthday this year.",
    options: ["give", "guide", "get", "greet"], answer: 2, vocabIndex: 14 },
  { q: "Folding soft fabric into neat piles before loading them into boxes destined for the community center downtown, the students worked happily. Every winter, our class likes to ______ warm blankets to the local shelter.",
    options: ["have", "get", "hold", "give"], answer: 3, vocabIndex: 15 },
  { q: "Standing behind the wooden counter from morning until closing time, the cheerful man never once forgot a familiar face. The shopkeeper always stops to ______ every customer with a warm smile.",
    options: ["greet", "guide", "hug", "help"], answer: 0, vocabIndex: 16 },
  { q: "Noticing two confused travelers staring at a crumpled paper map near the busy train station, a kind stranger stepped forward immediately. A friendly local offered to ______ the lost tourists back to their hotel.",
    options: ["follow", "guide", "frighten", "fight"], answer: 1, vocabIndex: 17 },
  { q: "Kneeling beside the half-built wooden bench in his garage with a small toolbox open beside him, he steadied each piece carefully. The carpenter began to ______ the nails carefully into the wooden frame.",
    options: ["hunt", "hide", "hammer", "hang"], answer: 2, vocabIndex: 18 },
  { q: "Reviewing the store's emergency procedures during her very first week on the job, the confident new hire took careful notes. The new manager seemed calm and ready to ______ any sudden problem quickly.",
    options: ["hurry", "hug", "hunt", "handle"], answer: 3, vocabIndex: 19 },
  { q: "Measuring twice and checking the level against the wall before driving in a single nail, the couple worked together. We decided to ______ the new painting right above the living room sofa.",
    options: ["hang", "hold", "hide", "have"], answer: 0, vocabIndex: 20 },
  { q: "Whispering excitedly in the hallway between classes about a mysterious announcement posted on the bulletin board that morning, students buzzed with curiosity. Nobody really knows what will ______ at tomorrow's surprise school assembly.",
    options: ["hurry", "happen", "hug", "hunt"], answer: 1, vocabIndex: 21 },
  { q: "Looking around the room during a classroom survey about hobbies and home life, the teacher noticed an interesting pattern emerge. Most students in this class ______ at least one pet at home.",
    options: ["help", "hold", "have", "hide"], answer: 2, vocabIndex: 22 },
  { q: "Spreading out worksheets covered in fractions and long division across the kitchen table every evening after dinner, the patient sibling never complained. My older brother always offers to ______ me with my math homework.",
    options: ["hurry", "hunt", "hang", "help"], answer: 3, vocabIndex: 23 },
  { q: "Giggling quietly behind the heavy fabric while counting slowly to twenty in the next room, the excited players waited to be found. The children loved to ______ behind the curtains during the noisy game.",
    options: ["hide", "hammer", "hold", "have"], answer: 0, vocabIndex: 24 },
  { q: "Posting colorful flyers around the gymnasium and ordering ribbons for every event weeks in advance, the committee prepared for a big day. Our school plans to ______ the annual sports day next Friday afternoon.",
    options: ["hide", "hold", "hang", "hurry"], answer: 1, vocabIndex: 25 },
  { q: "Spotting a familiar suitcase rolling through the busy arrival gate after months apart, she dropped everything and rushed forward instantly. She ran across the airport to ______ her grandmother tightly after the long flight.",
    options: ["guide", "greet", "hug", "help"], answer: 2, vocabIndex: 26 },
  { q: "Moving quietly through the underbrush at dawn with sharp eyes scanning the open meadow nearby, the patient predator waited for its chance. Wild foxes often ______ small rabbits near the edge of the forest.",
    options: ["feed", "follow", "fight", "hunt"], answer: 3, vocabIndex: 27 },
  { q: "Checking the clock while grabbing coats and bags near the door with only minutes left before departure, the family rushed about. We had to ______ to the station to catch the last train home.",
    options: ["hurry", "hammer", "hide", "hang"], answer: 0, vocabIndex: 28 },
  { q: "Hearing a strange rattling sound coming from beneath the hood during the morning commute, a careless driver kept driving anyway. It's never a good idea to ______ a strange noise from your car.",
    options: ["improve", "ignore", "include", "indicate"], answer: 1, vocabIndex: 29 },
  { q: "Sitting quietly with eyes closed during the calm breathing exercise at the end of yoga class, the instructor guided everyone gently. Close your eyes and try to ______ a quiet beach at sunset peacefully.",
    options: ["ignore", "indicate", "imagine", "insist"], answer: 2, vocabIndex: 30 },
  { q: "Standing in front of the mirror rehearsing her lines every evening for weeks before the big presentation, she felt steadily stronger. Daily practice has really helped ______ her confidence speaking in front of class.",
    options: ["ignore", "indicate", "exist", "improve"], answer: 3, vocabIndex: 31 },
  { q: "Reading the brochure carefully while comparing prices for several different vacation options online late one evening, she circled her favorite choice. Our weekend trip package will ______ two nights at a cozy mountain cabin.",
    options: ["include", "improve", "indicate", "insist"], answer: 0, vocabIndex: 32 },
  { q: "Glancing nervously at the strange flashing dashboard symbol while driving home from work along the quiet highway, she pulled over carefully. The flashing red light began to ______ a serious problem with the engine.",
    options: ["include", "indicate", "improve", "imagine"], answer: 1, vocabIndex: 33 },
  { q: "Sitting cross-legged on the classroom floor surrounded by colorful paper squares during the weekly art lesson, the curious student raised her hand. Could you please ______ me how to fold this paper crane correctly?",
    options: ["guide", "follow", "show", "give"], answer: 2, vocabIndex: 34 },
  { q: "Limping slightly across the final stretch of the muddy track with her coach shouting from the sidelines, she refused every offer to stop. Despite her tiredness, she continued to ______ on finishing the race.",
    options: ["improve", "indicate", "ignore", "insist"], answer: 3, vocabIndex: 35 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "artifacts": { pos: "n.", en_def: "objects made by people in the past, often historical", cn_def: "古物；文物（複數）" },
  "arrival gate": { pos: "n.", en_def: "the area at an airport where arriving passengers exit", cn_def: "入境閘口" },
  "bulletin board": { pos: "n.", en_def: "a board for posting public notices", cn_def: "公告欄" },
  "cabin": { pos: "n.", en_def: "a small, simple house, often in the countryside", cn_def: "小木屋" },
  "calculator": { pos: "n.", en_def: "a device used for doing math", cn_def: "計算機" },
  "canopy": { pos: "n.", en_def: "the upper layer of leaves and branches in a forest", cn_def: "（樹林的）樹冠層" },
  "carpenter": { pos: "n.", en_def: "a person who builds and repairs things made of wood", cn_def: "木匠" },
  "classmates": { pos: "n.", en_def: "students who are in the same class as you", cn_def: "同班同學（複數）" },
  "committee": { pos: "n.", en_def: "a group of people chosen to make decisions", cn_def: "委員會" },
  "community center": { pos: "n.", en_def: "a public building used for local activities and services", cn_def: "社區中心" },
  "confident": { pos: "adj.", en_def: "feeling sure of yourself", cn_def: "有自信的" },
  "crumpled": { pos: "adj.", en_def: "pressed into creases or wrinkles", cn_def: "皺成一團的" },
  "curiosity": { pos: "n.", en_def: "a strong desire to know or learn something", cn_def: "好奇心" },
  "dashboard": { pos: "n.", en_def: "the panel in a car with controls and displays", cn_def: "（車輛）儀表板" },
  "departure": { pos: "n.", en_def: "the act of leaving a place", cn_def: "出發；離開" },
  "drip": { pos: "n.", en_def: "a small amount of liquid falling slowly", cn_def: "（水）滴" },
  "encouragement": { pos: "n.", en_def: "words or actions that give someone confidence or hope", cn_def: "鼓勵" },
  "engine": { pos: "n.", en_def: "the part of a vehicle that makes it move", cn_def: "引擎" },
  "exhibit": { pos: "n.", en_def: "an object or display shown to the public", cn_def: "展覽品" },
  "faucet": { pos: "n.", en_def: "a device for controlling the flow of water from a pipe", cn_def: "水龍頭" },
  "flock": { pos: "n.", en_def: "a group of birds or sheep", cn_def: "（鳥、羊等的）群" },
  "flowerbeds": { pos: "n.", en_def: "areas of soil where flowers are grown", cn_def: "花圃（複數）" },
  "flyers": { pos: "n.", en_def: "printed sheets used to advertise or announce something", cn_def: "傳單（複數）" },
  "fractions": { pos: "n.", en_def: "numbers that represent parts of a whole", cn_def: "分數（複數）" },
  "frustration": { pos: "n.", en_def: "a feeling of being upset because of being unable to do something", cn_def: "挫折感" },
  "garage": { pos: "n.", en_def: "a building where cars are kept or repaired", cn_def: "車庫" },
  "gasped": { pos: "v.", en_def: "took a quick breath, often from surprise", cn_def: "喘氣；倒抽一口氣（過去式）" },
  "gymnasium": { pos: "n.", en_def: "a large room used for sports and exercise", cn_def: "體育館" },
  "homeowner": { pos: "n.", en_def: "a person who owns the home they live in", cn_def: "房屋主人" },
  "legends": { pos: "n.", en_def: "old stories, often based on history but not fully true", cn_def: "傳說（複數）" },
  "limping": { pos: "v.", en_def: "walking with difficulty because of an injured leg or foot", cn_def: "跛行（進行式）" },
  "maple": { pos: "n.", en_def: "a type of tree with leaves that turn red or orange", cn_def: "楓樹" },
  "meadow": { pos: "n.", en_def: "a field covered in grass or flowers", cn_def: "草地；牧草地" },
  "misty": { pos: "adj.", en_def: "covered in a light fog", cn_def: "薄霧籠罩的" },
  "newhire": { pos: "n.", en_def: "a person recently hired for a job", cn_def: "新進員工" },
  "predator": { pos: "n.", en_def: "an animal that hunts other animals for food", cn_def: "捕食者；掠食動物" },
  "presentation": { pos: "n.", en_def: "a talk given to an audience to explain or show something", cn_def: "報告；展示" },
  "procedures": { pos: "n.", en_def: "official ways of doing something", cn_def: "程序（複數）" },
  "rattling": { pos: "v.", en_def: "making a series of short, sharp sounds", cn_def: "發出咯咯聲（進行式）" },
  "ribbons": { pos: "n.", en_def: "long, thin strips of material used for decoration or prizes", cn_def: "緞帶；彩帶（複數）" },
  "scurrying": { pos: "v.", en_def: "running with short, quick steps", cn_def: "急忙奔跑（進行式）" },
  "shelter": { pos: "n.", en_def: "a place that provides protection or temporary housing", cn_def: "收容所；避難處" },
  "siblings": { pos: "n.", en_def: "brothers or sisters", cn_def: "兄弟姊妹（複數）" },
  "skeptics": { pos: "n.", en_def: "people who doubt that something is true", cn_def: "懷疑論者（複數）" },
  "stranger": { pos: "n.", en_def: "a person you do not know", cn_def: "陌生人" },
  "thunderclap": { pos: "n.", en_def: "a sudden loud sound of thunder", cn_def: "雷聲；雷響" },
  "toolbox": { pos: "n.", en_def: "a box used to hold and carry tools", cn_def: "工具箱" },
  "underbrush": { pos: "n.", en_def: "small plants and bushes growing under trees", cn_def: "林下灌木叢" },
  "yoga": { pos: "n.", en_def: "a system of exercises for physical and mental wellbeing", cn_def: "瑜珈" },
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
