// ============================================================
// Group 56 Quiz Data: Descriptive Adjectives, Part 9 (FINAL)
// Full word set (29 words) — the ninth and final portion of
// the "function words / common nouns" theme (269-word list).
// Continues from Group 55 (Common Nouns, Part 6 + early
// adjectives). All 29 words in this final group are
// adjectives, completing the full theme.
// Continues the simpler/shorter MCQ style introduced in
// Group 37 (~16-26 words, 2 sentences, one blank).
//
// Definition note: the spreadsheet's dictionary definition for
// "rare" is "not widely known," but the Chinese gloss 稀有的
// points to the "uncommon / scarce" sense (e.g. a rare animal,
// a rare opportunity). Corrected here to match the gloss.
// Several other entries used overly advanced dictionary-style
// definitions (e.g. "usual": "occurring or...in accordance with
// regular practice"); these have been simplified to A2-level
// wording while preserving the original meaning and gloss.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 56 - Descriptive Adjectives, Part 9 FINAL (形容詞 九，完結)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (29 words) ----
const VOCAB = [
  { word: "other", pos: "adj.", cn_def: "其他的", en_def: "not the one already mentioned",
    sentence: "I only have one pen left; can I borrow your {{BLANK}} one?",
    cn: "我只剩一支筆了，可以借用你另一支嗎？" },
  { word: "excellent", pos: "adj.", cn_def: "傑出的", en_def: "extremely good",
    sentence: "The chef cooked an {{BLANK}} meal that everyone at the table enjoyed.",
    cn: "主廚做了一頓非常出色的餐點，餐桌上的每個人都很喜歡。" },
  { word: "marvelous", pos: "adj.", cn_def: "了不起的", en_def: "amazing and wonderful",
    sentence: "We had a {{BLANK}} time at the beach during our summer vacation.",
    cn: "我們在暑假去海邊玩得非常開心。" },
  { word: "important", pos: "adj.", cn_def: "重要的", en_def: "having great value or meaning",
    sentence: "Getting enough sleep before the exam is just as {{BLANK}} as studying.",
    cn: "考試前睡眠充足跟讀書一樣重要。" },
  { word: "main", pos: "adj.", cn_def: "主要的", en_def: "the most important one",
    sentence: "The {{BLANK}} reason she joined the club was to make new friends.",
    cn: "她加入這個社團的主要原因是想交新朋友。" },
  { word: "necessary", pos: "adj.", cn_def: "必要的", en_def: "needed in order to do something",
    sentence: "A passport is {{BLANK}} if you want to travel to another country.",
    cn: "如果你想去其他國家旅行，護照是必要的。" },
  { word: "interested", pos: "adj.", cn_def: "感興趣的", en_def: "wanting to know more about something",
    sentence: "My brother is very {{BLANK}} in space and reads about planets every night.",
    cn: "我弟弟對太空非常感興趣，每天晚上都會讀關於行星的書。" },
  { word: "interesting", pos: "adj.", cn_def: "有趣的", en_def: "making you want to pay attention",
    sentence: "The museum guide told us an {{BLANK}} story about an ancient queen.",
    cn: "博物館的導覽員跟我們講了一個關於古代皇后的有趣故事。" },
  { word: "pop", pos: "adj.", cn_def: "流行的", en_def: "popular, especially in music",
    sentence: "She listens to {{BLANK}} music on the bus every morning before school.",
    cn: "她每天早上上學前在公車上都聽流行音樂。" },
  { word: "popular", pos: "adj.", cn_def: "受歡迎的", en_def: "liked by a lot of people",
    sentence: "That new bubble tea shop near our school is incredibly {{BLANK}} right now.",
    cn: "我們學校附近那家新的珍珠奶茶店現在非常受歡迎。" },
  { word: "asleep", pos: "adj.", cn_def: "睡著的", en_def: "in a state of sleeping",
    sentence: "The baby finally fell {{BLANK}} after her mother sang a soft song.",
    cn: "媽媽唱了一首輕柔的歌之後，寶寶終於睡著了。" },
  { word: "sleepy", pos: "adj.", cn_def: "想睡的", en_def: "feeling like you want to sleep",
    sentence: "He felt too {{BLANK}} to finish his homework after the long soccer practice.",
    cn: "經過漫長的足球練習後，他覺得太想睡了，無法完成作業。" },
  { word: "tired", pos: "adj.", cn_def: "疲倦的", en_def: "needing rest because you used a lot of energy",
    sentence: "After climbing all those stairs, my legs felt completely {{BLANK}} and weak.",
    cn: "爬完那些樓梯之後，我的腿感覺非常疲倦無力。" },
  { word: "total", pos: "adj.", cn_def: "全部的", en_def: "complete; including everything",
    sentence: "The {{BLANK}} cost of the class trip was higher than the teacher expected.",
    cn: "班遊的全部費用比老師預期的還高。" },
  { word: "whole", pos: "adj.", cn_def: "完整的", en_def: "complete; with no part missing",
    sentence: "My little sister ate the {{BLANK}} cake before anyone else even got a slice.",
    cn: "我妹妹在其他人吃到一片之前就把整個蛋糕吃光了。" },
  { word: "helpful", pos: "adj.", cn_def: "有幫助的", en_def: "willing or able to help",
    sentence: "Our new classmate is always {{BLANK}} when someone forgets their textbook.",
    cn: "我們的新同學在有人忘記帶課本時總是很樂於幫忙。" },
  { word: "useful", pos: "adj.", cn_def: "有用的", en_def: "able to be used for something good",
    sentence: "This dictionary app is really {{BLANK}} when I don't know a word's meaning.",
    cn: "當我不知道一個單字的意思時，這個字典應用程式真的很有用。" },
  { word: "broad", pos: "adj.", cn_def: "寬闊的", en_def: "wide from one side to the other",
    sentence: "The hiking trail crossed a {{BLANK}} river with a small wooden bridge.",
    cn: "登山步道經過一條寬闊的河流，上面有一座小木橋。" },
  { word: "wide", pos: "adj.", cn_def: "寬的", en_def: "having a large distance between two sides",
    sentence: "The new highway has a much {{BLANK}} road than the old one.",
    cn: "新的高速公路比舊的那條路寬得多。" },
  { word: "narrow", pos: "adj.", cn_def: "窄的", en_def: "not wide",
    sentence: "Our car barely fit through the {{BLANK}} street near the old market.",
    cn: "我們的車勉強才能通過舊市場附近那條窄窄的街道。" },
  { word: "basic", pos: "adj.", cn_def: "基本的", en_def: "simple and forming the starting point",
    sentence: "Before learning grammar, students should master some {{BLANK}} vocabulary first.",
    cn: "在學習文法之前，學生應該先掌握一些基本的單字。" },
  { word: "common", pos: "adj.", cn_def: "普通的", en_def: "happening often; not unusual",
    sentence: "Forgetting an umbrella on a rainy day is a {{BLANK}} mistake here.",
    cn: "在這裡，下雨天忘記帶雨傘是一個常見的錯誤。" },
  { word: "usual", pos: "adj.", cn_def: "通常的", en_def: "happening most of the time; normal",
    sentence: "He took his {{BLANK}} seat by the window before the bus left.",
    cn: "公車出發前，他坐到了他平常坐的窗邊座位。" },
  { word: "general", pos: "adj.", cn_def: "一般的", en_def: "true for most people or things, not specific",
    sentence: "The teacher gave a {{BLANK}} introduction before explaining each topic in detail.",
    cn: "老師在詳細解釋每個主題之前先做了一個大致的介紹。" },
  { word: "ordinary", pos: "adj.", cn_def: "平常的", en_def: "not special; normal",
    sentence: "It seemed like an {{BLANK}} Monday until our teacher announced a surprise trip.",
    cn: "原本看起來是個平凡的星期一，直到老師宣布了一個驚喜旅行。" },
  { word: "regular", pos: "adj.", cn_def: "定期的", en_def: "happening again and again at fixed times",
    sentence: "My doctor said {{BLANK}} exercise would help me feel healthier and stronger.",
    cn: "我的醫生說定期運動會讓我感覺更健康、更強壯。" },
  { word: "rare", pos: "adj.", cn_def: "稀有的", en_def: "not common; not often found",
    sentence: "Snow is extremely {{BLANK}} in our city, so everyone got excited last winter.",
    cn: "雪在我們城市非常罕見，所以去年冬天大家都很興奮。" },
  { word: "special", pos: "adj.", cn_def: "特別的", en_def: "different from what is normal, in a good way",
    sentence: "Grandma always bakes something {{BLANK}} for us on the first day of school.",
    cn: "奶奶總是在開學第一天為我們烤一些特別的點心。" },
  { word: "unique", pos: "adj.", cn_def: "獨特的", en_def: "the only one of its kind",
    sentence: "Every snowflake has a {{BLANK}} shape that no other snowflake shares exactly.",
    cn: "每片雪花都有一個獨特的形狀，沒有其他雪花會完全一樣。" }
];

// ---- Part 2 data: MCQs (29 questions) ----
const MCQS = [
  { q: "I forgot to bring my umbrella again today. Could I please borrow your _____ one for the walk home?",
    options: ["other","main","total","whole"], answer: 0, vocabIndex: 0 },
  { q: "The students gave an _____ performance at the concert. The whole crowd stood up at once to clap.",
    options: ["interesting","excellent","useful","common"], answer: 1, vocabIndex: 1 },
  { q: "A group of dolphins swam right beside our small boat. It was honestly a truly _____ experience for everyone.",
    options: ["narrow","basic","marvelous","regular"], answer: 2, vocabIndex: 2 },
  { q: "Biking on busy city roads can be quite dangerous. Wearing a helmet is _____ if you want to stay safe.",
    options: ["asleep","pop","rare","important"], answer: 3, vocabIndex: 3 },
  { q: "This old story has a very clear message for readers. The _____ idea is that kindness beats raw strength.",
    options: ["main","sleepy","broad","popular"], answer: 0, vocabIndex: 4 },
  { q: "The mountain trail is steep and the weather is very hot. Bringing extra water along is absolutely _____.",
    options: ["tired","necessary","wide","ordinary"], answer: 1, vocabIndex: 5 },
  { q: "She paints for an hour every day. She is clearly _____ in becoming a real artist.",
    options: ["helpful","unique","interested","general"], answer: 2, vocabIndex: 6 },
  { q: "The film showed strange creatures from the deep sea. It was so _____ that nobody checked their phones.",
    options: ["useful","special","basic","interesting"], answer: 3, vocabIndex: 7 },
  { q: "Her new song just came out last week. It's already a _____ hit on every radio station.",
    options: ["pop","narrow","regular","rare"], answer: 0, vocabIndex: 8 },
  { q: "We had to wait two hours just to get inside. That amusement park is incredibly _____ this year.",
    options: ["other","popular","asleep","total"], answer: 1, vocabIndex: 9 },
  { q: "His alarm rang three separate times this morning. He was still half _____ when he finally got up.",
    options: ["common","whole","asleep","broad"], answer: 2, vocabIndex: 10 },
  { q: "He kept yawning all through math class. It was obvious that he felt very _____ and needed rest.",
    options: ["wide","main","unique","sleepy"], answer: 3, vocabIndex: 11 },
  { q: "Swim practice lasted almost two hours today. By the end, her arms felt heavy and completely _____.",
    options: ["tired","necessary","general","ordinary"], answer: 0, vocabIndex: 12 },
  { q: "Don't forget to add the shipping fee. The _____ price ends up higher than most people expect.",
    options: ["interested","total","regular","rare"], answer: 1, vocabIndex: 13 },
  { q: "There were not enough plates for everyone. So he decided to just roast the _____ chicken at once.",
    options: ["interesting","special","whole","pop"], answer: 2, vocabIndex: 14 },
  { q: "New students often get lost on their first day. Luckily, our librarian is always _____ and shows them around.",
    options: ["popular","asleep","narrow","helpful"], answer: 3, vocabIndex: 15 },
  { q: "The lights went out suddenly during the storm. A flashlight became incredibly _____ for finding our way around.",
    options: ["useful","sleepy","tired","total"], answer: 0, vocabIndex: 16 },
  { q: "We stood at the very top of the cliff. Below us spread a _____ valley covered in green farmland.",
    options: ["whole","broad","common","unique"], answer: 1, vocabIndex: 17 },
  { q: "Traffic used to back up for miles on that old road. The new highway has a much _____ lane.",
    options: ["necessary","general","wide","rare"], answer: 2, vocabIndex: 18 },
  { q: "Two students cannot pass each other there at the same time. The hallway is simply too _____ near the stairs.",
    options: ["interested","ordinary","special","narrow"], answer: 3, vocabIndex: 19 },
  { q: "Before trying any deep dives, beginners need real practice first. Coaches always start with some _____ kicking drills.",
    options: ["basic","popular","main","broad"], answer: 0, vocabIndex: 20 },
  { q: "Almost every student loses a charger cable eventually. It's such a _____ problem that the shop keeps extras nearby.",
    options: ["asleep","common","unique","total"], answer: 1, vocabIndex: 21 },
  { q: "Most mornings follow the exact same routine for him. On a _____ school day, breakfast comes first, then the bus.",
    options: ["rare","wide","usual","interesting"], answer: 2, vocabIndex: 22 },
  { q: "The coach skipped most of the small details today. He only gave a _____ summary of the season's plan.",
    options: ["sleepy","narrow","helpful","general"], answer: 3, vocabIndex: 23 },
  { q: "The hotel lobby downstairs looked huge and fancy. Our small _____ room upstairs felt much simpler by comparison.",
    options: ["ordinary","excellent","necessary","total"], answer: 0, vocabIndex: 24 },
  { q: "She never misses a Monday or Thursday session. Her swim practice runs on a strict, _____ schedule every week.",
    options: ["rare","regular","marvelous","whole"], answer: 1, vocabIndex: 25 },
  { q: "Most lobsters caught near here are a dull reddish brown. A blue one is so _____ that staff got excited.",
    options: ["common","useful","rare","broad"], answer: 2, vocabIndex: 26 },
  { q: "My brother just started his very first job. Mom planned a _____ dinner to celebrate the occasion.",
    options: ["narrow","general","asleep","special"], answer: 3, vocabIndex: 27 },
  { q: "No two people share the exact same fingerprint pattern. Each one is completely _____ to that single person.",
    options: ["unique","popular","basic","tired"], answer: 0, vocabIndex: 28 },
];

// ---- LOOKUP: this group's own target words (Tier 1 dictionary) ----
const LOOKUP = {
  "other": { pos: "adj.", en_def: "not the one already mentioned", cn_def: "其他的" },
  "excellent": { pos: "adj.", en_def: "extremely good", cn_def: "傑出的" },
  "marvelous": { pos: "adj.", en_def: "amazing and wonderful", cn_def: "了不起的" },
  "important": { pos: "adj.", en_def: "having great value or meaning", cn_def: "重要的" },
  "main": { pos: "adj.", en_def: "the most important one", cn_def: "主要的" },
  "necessary": { pos: "adj.", en_def: "needed in order to do something", cn_def: "必要的" },
  "interested": { pos: "adj.", en_def: "wanting to know more about something", cn_def: "感興趣的" },
  "interesting": { pos: "adj.", en_def: "making you want to pay attention", cn_def: "有趣的" },
  "pop": { pos: "adj.", en_def: "popular, especially in music", cn_def: "流行的" },
  "popular": { pos: "adj.", en_def: "liked by a lot of people", cn_def: "受歡迎的" },
  "asleep": { pos: "adj.", en_def: "in a state of sleeping", cn_def: "睡著的" },
  "sleepy": { pos: "adj.", en_def: "feeling like you want to sleep", cn_def: "想睡的" },
  "tired": { pos: "adj.", en_def: "needing rest because you used a lot of energy", cn_def: "疲倦的" },
  "total": { pos: "adj.", en_def: "complete; including everything", cn_def: "全部的" },
  "whole": { pos: "adj.", en_def: "complete; with no part missing", cn_def: "完整的" },
  "helpful": { pos: "adj.", en_def: "willing or able to help", cn_def: "有幫助的" },
  "useful": { pos: "adj.", en_def: "able to be used for something good", cn_def: "有用的" },
  "broad": { pos: "adj.", en_def: "wide from one side to the other", cn_def: "寬闊的" },
  "wide": { pos: "adj.", en_def: "having a large distance between two sides", cn_def: "寬的" },
  "narrow": { pos: "adj.", en_def: "not wide", cn_def: "窄的" },
  "basic": { pos: "adj.", en_def: "simple and forming the starting point", cn_def: "基本的" },
  "common": { pos: "adj.", en_def: "happening often; not unusual", cn_def: "普通的" },
  "usual": { pos: "adj.", en_def: "happening most of the time; normal", cn_def: "通常的" },
  "general": { pos: "adj.", en_def: "true for most people or things, not specific", cn_def: "一般的" },
  "ordinary": { pos: "adj.", en_def: "not special; normal", cn_def: "平常的" },
  "regular": { pos: "adj.", en_def: "happening again and again at fixed times", cn_def: "定期的" },
  "rare": { pos: "adj.", en_def: "not common; not often found", cn_def: "稀有的" },
  "special": { pos: "adj.", en_def: "different from what is normal, in a good way", cn_def: "特別的" },
  "unique": { pos: "adj.", en_def: "the only one of its kind", cn_def: "獨特的" }
};

// ---- EXTRA_GLOSSES: other words used in this group's sentences (Tier 2) ----
const EXTRA_GLOSSES = {
  "borrowed": { pos: "v.", en_def: "took something to use and planned to return it", cn_def: "借（過去式）" },
  "umbrella": { pos: "n.", en_def: "a device used to stay dry in the rain", cn_def: "雨傘" },
  "walk": { pos: "n.", en_def: "a trip made by moving on foot", cn_def: "步行" },
  "performance": { pos: "n.", en_def: "a show put on for an audience", cn_def: "表演" },
  "crowd": { pos: "n.", en_def: "a large group of people gathered together", cn_def: "人群" },
  "clap": { pos: "v.", en_def: "to hit your hands together to show approval", cn_def: "拍手" },
  "dolphins": { pos: "n.", en_def: "smart sea animals that often swim in groups", cn_def: "海豚（複數）" },
  "boat": { pos: "n.", en_def: "a small vehicle for traveling on water", cn_def: "船" },
  "experience": { pos: "n.", en_def: "something that happens to you that you remember", cn_def: "經歷" },
  "helmet": { pos: "n.", en_def: "a hard hat worn to protect the head", cn_def: "安全帽" },
  "strength": { pos: "n.", en_def: "physical power or force", cn_def: "力量" },
  "kindness": { pos: "n.", en_def: "the quality of being gentle and caring", cn_def: "善良" },
  "powerful": { pos: "adj.", en_def: "having great strength or force", cn_def: "強大的" },
  "hiking": { pos: "v.", en_def: "walking for a long distance, often in nature", cn_def: "健行" },
  "painting": { pos: "v./n.", en_def: "the activity of making pictures with paint", cn_def: "繪畫" },
  "practices": { pos: "v.", en_def: "does an activity repeatedly to improve a skill", cn_def: "練習" },
  "documentary": { pos: "n.", en_def: "a film that gives facts about a real topic", cn_def: "紀錄片" },
  "creatures": { pos: "n.", en_def: "living things, especially animals", cn_def: "生物（複數）" },
  "touched": { pos: "v.", en_def: "made contact with something using the hand", cn_def: "觸碰（過去式）" },
  "radio": { pos: "n.", en_def: "a device that plays broadcast sound", cn_def: "收音機" },
  "station": { pos: "n.", en_def: "a place that sends out broadcasts, like radio shows", cn_def: "電台" },
  "amusement": { pos: "n.", en_def: "entertainment or fun activities", cn_def: "娛樂" },
  "tickets": { pos: "n.", en_def: "pieces of paper that allow entry to an event", cn_def: "票（複數）" },
  "alarm": { pos: "n.", en_def: "a device that makes a sound to wake someone up", cn_def: "鬧鐘" },
  "snooze": { pos: "v.", en_def: "to delay an alarm so it rings again later", cn_def: "按掉鬧鐘再睡" },
  "yawning": { pos: "v.", en_def: "opening the mouth wide because you are tired", cn_def: "打哈欠（進行式）" },
  "rest": { pos: "n.", en_def: "a period of relaxing or sleeping", cn_def: "休息" },
  "swim": { pos: "n./v.", en_def: "to move through water using your arms and legs", cn_def: "游泳" },
  "heavy": { pos: "adj.", en_def: "having a lot of weight", cn_def: "重的" },
  "shipping": { pos: "n.", en_def: "the act of sending goods to a location", cn_def: "運送" },
  "fee": { pos: "n.", en_def: "an amount of money paid for a service", cn_def: "費用" },
  "expected": { pos: "v.", en_def: "thought something would happen", cn_def: "預期（過去式）" },
  "slices": { pos: "n.", en_def: "thin flat pieces cut from something larger", cn_def: "片（複數）" },
  "roast": { pos: "v.", en_def: "to cook food using dry heat, often in an oven", cn_def: "烤" },
  "librarian": { pos: "n.", en_def: "a person who works in or manages a library", cn_def: "圖書館員" },
  "flashlight": { pos: "n.", en_def: "a small portable light powered by batteries", cn_def: "手電筒" },
  "electricity": { pos: "n.", en_def: "the power used to run lights and machines", cn_def: "電力" },
  "cliff": { pos: "n.", en_def: "a high, steep area of rock or land", cn_def: "懸崖" },
  "valley": { pos: "n.", en_def: "a low area of land between hills or mountains", cn_def: "山谷" },
  "stretching": { pos: "v.", en_def: "extending over a distance", cn_def: "延伸（進行式）" },
  "lane": { pos: "n.", en_def: "a marked section of a road for one line of traffic", cn_def: "車道" },
  "traffic": { pos: "n.", en_def: "the vehicles moving on a road", cn_def: "交通" },
  "hallway": { pos: "n.", en_def: "a passage inside a building that connects rooms", cn_def: "走廊" },
  "fits": { pos: "v.", en_def: "is the right size or shape for a space", cn_def: "符合；容納" },
  "diving": { pos: "v.", en_def: "jumping or swimming underwater headfirst", cn_def: "潛水" },
  "swimmers": { pos: "n.", en_def: "people who swim", cn_def: "游泳者（複數）" },
  "master": { pos: "v.", en_def: "to become very skilled at something", cn_def: "精通" },
  "kicking": { pos: "n./v.", en_def: "the action of hitting something with the foot", cn_def: "踢；划水動作" },
  "breathing": { pos: "n./v.", en_def: "the act of taking air in and out", cn_def: "呼吸" },
  "charger": { pos: "n.", en_def: "a device used to add power to a battery", cn_def: "充電器" },
  "cable": { pos: "n.", en_def: "a wire used to connect or carry power", cn_def: "電線" },
  "extras": { pos: "n.", en_def: "additional items kept in case they are needed", cn_def: "額外的東西" },
  "counter": { pos: "n.", en_def: "a long flat surface in a shop where customers pay", cn_def: "櫃台" },
  "breakfast": { pos: "n.", en_def: "the first meal eaten in the morning", cn_def: "早餐" },
  "leaves": { pos: "v.", en_def: "goes away from a place", cn_def: "離開" },
  "details": { pos: "n.", en_def: "small specific pieces of information", cn_def: "細節（複數）" },
  "summary": { pos: "n.", en_def: "a short statement of the main points", cn_def: "摘要" },
  "season": { pos: "n.", en_def: "a period of the year, or a period in sports", cn_def: "季節；球季" },
  "fancy": { pos: "adj.", en_def: "expensive-looking and elegant", cn_def: "華麗的" },
  "lobby": { pos: "n.", en_def: "the entrance area of a building", cn_def: "大廳" },
  "cozy": { pos: "adj.", en_def: "warm and comfortable", cn_def: "舒適溫暖的" },
  "schedule": { pos: "n.", en_def: "a plan that shows when things will happen", cn_def: "時間表" },
  "lobster": { pos: "n.", en_def: "a sea animal with a hard shell and large claws", cn_def: "龍蝦" },
  "aquarium": { pos: "n.", en_def: "a building where people can see fish and sea animals", cn_def: "水族館" },
  "staff": { pos: "n.", en_def: "the group of people who work at a place", cn_def: "員工" },
  "thrilled": { pos: "adj.", en_def: "extremely excited and happy", cn_def: "非常興奮的" },
  "celebrate": { pos: "v.", en_def: "to do something special to mark an event", cn_def: "慶祝" },
  "fingerprints": { pos: "n.", en_def: "the unique marks left by the tips of fingers", cn_def: "指紋（複數）" },
  "pattern": { pos: "n.", en_def: "a repeated design or arrangement", cn_def: "圖案；模式" },
  "trail": { pos: "n.", en_def: "a path through nature or mountains", cn_def: "步道" },
  "steep": { pos: "adj.", en_def: "rising or falling at a sharp angle", cn_def: "陡峭的" },
  "film": { pos: "n.", en_def: "a movie", cn_def: "電影" },
  "fingerprint": { pos: "n.", en_def: "the unique mark left by the tip of a finger", cn_def: "指紋" },
  "lobsters": { pos: "n.", en_def: "sea animals with a hard shell and large claws", cn_def: "龍蝦（複數）" },
  "dictionary": { pos: "n.", en_def: "a book or app that explains word meanings", cn_def: "字典" },
  "drills": { pos: "n.", en_def: "practice exercises done repeatedly to build a skill", cn_def: "練習；訓練" },
  "beginners": { pos: "n.", en_def: "people who are just starting to learn something", cn_def: "初學者（複數）" },
  "coaches": { pos: "n.", en_def: "people who train athletes or teams", cn_def: "教練（複數）" },
  "classmate": { pos: "n.", en_def: "a student in the same class as you", cn_def: "同班同學" },
  "museum": { pos: "n.", en_def: "a building where interesting objects are displayed", cn_def: "博物館" },
  "queen": { pos: "n.", en_def: "a female ruler of a country", cn_def: "皇后；女王" },
  "planets": { pos: "n.", en_def: "large round objects in space that orbit a star", cn_def: "行星（複數）" },
  "snowflake": { pos: "n.", en_def: "a single small piece of snow", cn_def: "雪花" },
  "vocabulary": { pos: "n.", en_def: "the words a person knows or uses", cn_def: "字彙" },
  "grammar": { pos: "n.", en_def: "the rules for forming sentences in a language", cn_def: "文法" },
  "exam": { pos: "n.", en_def: "a formal test of knowledge", cn_def: "考試" },
  "studying": { pos: "v.", en_def: "spending time learning about a subject", cn_def: "學習（進行式）" },
  "doctor": { pos: "n.", en_def: "a person trained to treat sick people", cn_def: "醫生" },
  "exercise": { pos: "n.", en_def: "physical activity done to stay healthy", cn_def: "運動" },
  "healthier": { pos: "adj.", en_def: "more healthy", cn_def: "更健康的" },
  "stronger": { pos: "adj.", en_def: "having more strength", cn_def: "更強壯的" },
  "routine": { pos: "n.", en_def: "a regular set of actions done in the same order", cn_def: "日常作息" },
  "occasion": { pos: "n.", en_def: "a special event or time", cn_def: "場合；時機" },
  "comparison": { pos: "n.", en_def: "the act of comparing two or more things", cn_def: "比較" },
  "simpler": { pos: "adj.", en_def: "more simple; easier", cn_def: "更簡單的" },
  "downstairs": { pos: "adv./adj.", en_def: "on or to a lower floor of a building", cn_def: "樓下" },
  "dull": { pos: "adj.", en_def: "not bright or interesting in color", cn_def: "暗淡的" },
  "reddish": { pos: "adj.", en_def: "somewhat red in color", cn_def: "帶紅色的" },
  "farmland": { pos: "n.", en_def: "land used for growing crops or raising animals", cn_def: "農地" },
  "mountain": { pos: "n.", en_def: "a very high area of land", cn_def: "山" },
  "river": { pos: "n.", en_def: "a large natural flow of water", cn_def: "河流" },
  "market": { pos: "n.", en_def: "a place where goods are bought and sold", cn_def: "市場" },
  "passport": { pos: "n.", en_def: "an official document needed to travel to other countries", cn_def: "護照" },
  "country": { pos: "n.", en_def: "a nation with its own government and land", cn_def: "國家" },
  "travel": { pos: "v.", en_def: "to go from one place to another", cn_def: "旅行" },
  "dangerous": { pos: "adj.", en_def: "likely to cause harm or injury", cn_def: "危險的" },
  "message": { pos: "n.", en_def: "an important idea or piece of information", cn_def: "訊息；寓意" },
  "raw": { pos: "adj.", en_def: "in a natural, unprocessed state", cn_def: "原始的；天然的" },
  "artist": { pos: "n.", en_def: "a person who creates art, like painting or music", cn_def: "藝術家" },
  "becoming": { pos: "v.", en_def: "starting to be something", cn_def: "成為（進行式）" },
  "deep": { pos: "adj.", en_def: "going far down from the top or surface", cn_def: "深的" },
  "sea": { pos: "n.", en_def: "a large body of salt water", cn_def: "海" },
  "phones": { pos: "n.", en_def: "devices used to call or text people", cn_def: "電話（複數）" },
  "song": { pos: "n.", en_def: "a piece of music with words that can be sung", cn_def: "歌曲" },
  "hit": { pos: "n.", en_def: "a very successful and popular song or movie", cn_def: "熱門作品" },
  "rang": { pos: "v.", en_def: "made a ringing sound (past tense of ring)", cn_def: "響起（過去式）" },
  "separate": { pos: "adj.", en_def: "not joined or connected to something else", cn_def: "分開的；個別的" },
  "session": { pos: "n.", en_def: "a period of time spent doing one activity", cn_def: "一段練習或活動時間" },
  "half": { pos: "adj./n.", en_def: "one of two equal parts of something", cn_def: "一半" },
  "math": { pos: "n.", en_def: "the study of numbers, shapes, and patterns", cn_def: "數學" },
  "class": { pos: "n.", en_def: "a group of students who study together", cn_def: "班級；課程" },
  "arms": { pos: "n.", en_def: "the body parts from the shoulder to the hand", cn_def: "手臂（複數）" },
  "expect": { pos: "v.", en_def: "to think something will happen", cn_def: "預期" },
  "plates": { pos: "n.", en_def: "flat dishes used for serving food", cn_def: "盤子（複數）" },
  "shows": { pos: "v.", en_def: "lets someone see something; guides", cn_def: "展示；帶領" },
  "lights": { pos: "n.", en_def: "devices or sources that produce brightness", cn_def: "燈（複數）" },
  "storm": { pos: "n.", en_def: "very bad weather with strong wind and rain", cn_def: "風暴" },
  "finding": { pos: "v.", en_def: "discovering the location of something", cn_def: "找到（進行式）" },
  "highway": { pos: "n.", en_def: "a large main road for fast travel between places", cn_def: "高速公路" },
  "stairs": { pos: "n.", en_def: "a set of steps that go from one floor to another", cn_def: "樓梯" },
  "dives": { pos: "n.", en_def: "jumps headfirst into water", cn_def: "跳水動作（複數）" },
  "kicking": { pos: "n./v.", en_def: "the action of hitting something with the foot", cn_def: "踢；划水動作" },
  "charger": { pos: "n.", en_def: "a device used to add power to a battery", cn_def: "充電器" },
  "extras": { pos: "n.", en_def: "additional items kept in case they are needed", cn_def: "額外的東西" },
  "shop": { pos: "n.", en_def: "a small store that sells goods", cn_def: "商店" },
  "nearby": { pos: "adv./adj.", en_def: "not far away; close to a place", cn_def: "附近" },
  "bus": { pos: "n.", en_def: "a large vehicle that carries many passengers", cn_def: "公車" },
  "hotel": { pos: "n.", en_def: "a building where travelers pay to stay overnight", cn_def: "飯店" },
  "upstairs": { pos: "adv./adj.", en_def: "on or to a higher floor of a building", cn_def: "樓上" },
  "strict": { pos: "adj.", en_def: "demanding that rules be followed exactly", cn_def: "嚴格的" },
  "blue": { pos: "adj.", en_def: "having the color of a clear sky", cn_def: "藍色的" },
  "brown": { pos: "adj.", en_def: "having the color of soil or coffee", cn_def: "棕色的" },
  "excited": { pos: "adj.", en_def: "feeling very enthusiastic and happy", cn_def: "興奮的" },
  "single": { pos: "adj.", en_def: "only one; not more than one", cn_def: "單一的" }
};
