// ============================================================
// Group 12 Quiz Data: School Life
// Full word set (35 words) — school facilities, classroom
// objects, learning activities, and school subjects from the
// "school / work / media / communication" theme. Continues
// from Group 11 (Jobs / Office / Technology / Communication).
// Work/Business/Money and Media/Time words will follow as
// later groups.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 12 - School Life (學校生活)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (35 words) ----
const VOCAB = [
  { word: "school", pos: "n.", cn_def: "學校", en_def: "a place where children go to learn",
    sentence: "Every morning, my little brother walks to {{BLANK}} with his best friend from next door.",
    cn: "每天早上，我弟弟都和隔壁的好朋友一起走去學校。" },
  { word: "campus", pos: "n.", cn_def: "校園", en_def: "the land and buildings of a school or university",
    sentence: "On the first day, new students took a tour around the whole {{BLANK}}.",
    cn: "開學第一天，新生們在整個校園裡參觀了一圈。" },
  { word: "semester", pos: "n.", cn_def: "學期", en_def: "one of the two main periods that a school year is divided into",
    sentence: "Our final exams are usually held during the last week of the {{BLANK}}.",
    cn: "我們的期末考通常在這個學期的最後一週舉行。" },
  { word: "grade", pos: "n.", cn_def: "成績", en_def: "a score or mark given for schoolwork showing how well a student did",
    sentence: "She studied hard all week and finally earned a perfect {{BLANK}} on her math test.",
    cn: "她整週用功學習，終於在數學考試中得到了滿分的成績。" },
  { word: "course", pos: "n.", cn_def: "課程", en_def: "a series of lessons on a particular subject",
    sentence: "My sister signed up for an art {{BLANK}} at the community center this summer.",
    cn: "我姐姐這個暑假在社區中心報名了一門美術課程。" },
  { word: "lesson", pos: "n.", cn_def: "功課", en_def: "a period of time spent learning or teaching one subject",
    sentence: "Today's {{BLANK}} was about how plants grow from tiny seeds into tall trees.",
    cn: "今天的課程是關於植物如何從小小的種子長成高大的樹木。" },
  { word: "exam", pos: "n.", cn_def: "考試", en_def: "a formal test of knowledge or skill",
    sentence: "All the students felt nervous while waiting outside for the big {{BLANK}} to begin.",
    cn: "所有學生在外面等待這場重要考試開始時都感到很緊張。" },
  { word: "quiz", pos: "n.", cn_def: "測驗", en_def: "a short, informal test on a small amount of material",
    sentence: "Our teacher gives a short vocabulary {{BLANK}} at the start of every Friday class.",
    cn: "我們老師每週五上課一開始都會出一個簡短的單字測驗。" },
  { word: "test", pos: "n.", cn_def: "測試", en_def: "a set of questions used to check knowledge or ability",
    sentence: "He forgot his pencil case on the morning of the important science {{BLANK}}.",
    cn: "他在重要的科學測試那天早上忘記帶他的鉛筆盒了。" },
  { word: "homework", pos: "n.", cn_def: "功課", en_def: "school work that students do at home",
    sentence: "I always finish my {{BLANK}} before dinner so I can relax in the evening.",
    cn: "我總是在晚餐前完成功課，這樣晚上就能放鬆休息。" },
  { word: "degree", pos: "n.", cn_def: "學位", en_def: "a qualification given by a university after completing a course of study",
    sentence: "My older cousin worked for six years to earn her {{BLANK}} in engineering.",
    cn: "我的表姐花了六年時間才取得她的工程學位。" },
  { word: "beginner", pos: "n.", cn_def: "初學者", en_def: "a person who is just starting to learn or do something",
    sentence: "Even though he was a complete {{BLANK}}, he learned to swim within just two weeks.",
    cn: "雖然他是個完全的初學者，但他在短短兩週內就學會了游泳。" },
  { word: "group", pos: "n.", cn_def: "小組", en_def: "a number of people who work or are gathered together",
    sentence: "For the science project, our teacher divided the whole class into small {{BLANK}}.",
    cn: "為了這個科學作業，我們老師把全班分成了好幾個小組。" },
  { word: "club", pos: "n.", cn_def: "社團", en_def: "a group of people who meet because they share an interest",
    sentence: "My older brother joined the robotics {{BLANK}} after school every Tuesday and Thursday.",
    cn: "我哥哥每週二和週四放學後都會參加機器人社團。" },
  { word: "bell", pos: "n.", cn_def: "鈴", en_def: "a metal object that makes a ringing sound",
    sentence: "As soon as the {{BLANK}} rang, every student rushed out to the playground.",
    cn: "鈴聲一響，每個學生都立刻衝到操場上。" },
  { word: "blackboard", pos: "n.", cn_def: "黑板", en_def: "a dark board that teachers write on with chalk",
    sentence: "The teacher wrote today's homework assignment neatly on the {{BLANK}}.",
    cn: "老師把今天的作業整整齊齊地寫在黑板上。" },
  { word: "chair", pos: "n.", cn_def: "椅子", en_def: "a piece of furniture for one person to sit on",
    sentence: "My desk and {{BLANK}} are right next to the classroom window.",
    cn: "我的桌子和椅子就在教室窗邊。" },
  { word: "chalk", pos: "n.", cn_def: "粉筆", en_def: "a soft white or colored stick used for writing on a blackboard",
    sentence: "The art teacher handed out colored {{BLANK}} for our outdoor drawing activity.",
    cn: "美術老師發給我們彩色粉筆來進行戶外繪畫活動。" },
  { word: "textbook", pos: "n.", cn_def: "教科書", en_def: "a book that contains information about a school subject",
    sentence: "Please open your history {{BLANK}} to page forty and read the chapter quietly.",
    cn: "請翻開你的歷史教科書到第四十頁，並安靜地閱讀這一章。" },
  { word: "workbook", pos: "n.", cn_def: "作業簿", en_def: "a book with exercises and spaces for students to write answers",
    sentence: "We finish two pages of our math {{BLANK}} for homework every single night.",
    cn: "我們每天晚上都會完成兩頁的數學作業簿當作功課。" },
  { word: "learn", pos: "v.", cn_def: "學習", en_def: "to get knowledge or a skill through study or experience",
    sentence: "My grandmother decided to {{BLANK}} how to use a smartphone last year.",
    cn: "我奶奶去年決定要學習如何使用智慧型手機。" },
  { word: "study", pos: "v.", cn_def: "學習；研究", en_def: "to spend time learning about a subject",
    sentence: "My brother likes to {{BLANK}} quietly in the library after school every day.",
    cn: "我哥哥每天放學後都喜歡在圖書館安靜地學習。" },
  { word: "review", pos: "v.", cn_def: "複習", en_def: "to look at or study something again carefully",
    sentence: "Before the final exam, we spent an entire weekend reviewing the lessons together.",
    cn: "在期末考前，我們花了整個週末一起複習這些課程內容。" },
  { word: "subject", pos: "n.", cn_def: "科目", en_def: "an area of knowledge studied in school, such as math or science",
    sentence: "Out of all my classes, science is by far my favorite {{BLANK}} this year.",
    cn: "在我所有的課程中，科學是我今年最喜歡的科目。" },
  { word: "art", pos: "n.", cn_def: "美術", en_def: "the subject in which students learn to draw, paint, or create things",
    sentence: "In {{BLANK}} class today, we painted colorful pictures of our favorite animals.",
    cn: "今天的美術課上，我們畫了色彩鮮豔的動物圖畫。" },
  { word: "biology", pos: "n.", cn_def: "生物學", en_def: "the science that studies living things, such as plants and animals",
    sentence: "In {{BLANK}} class, we learned how a caterpillar slowly changes into a butterfly.",
    cn: "在生物學課上，我們學到了毛毛蟲如何慢慢變成蝴蝶。" },
  { word: "chemistry", pos: "n.", cn_def: "化學", en_def: "the science that studies what things are made of and how they react",
    sentence: "During the {{BLANK}} experiment, the clear liquid suddenly turned a bright shade of blue.",
    cn: "在這次化學實驗中，透明的液體突然變成了鮮藍色。" },
  { word: "Chinese", pos: "n.", cn_def: "中文", en_def: "the language spoken in China and Taiwan",
    sentence: "In {{BLANK}} class, we practiced writing new characters in our notebooks.",
    cn: "在中文課上，我們在筆記本上練習寫新的字。" },
  { word: "English", pos: "n.", cn_def: "英文", en_def: "the language originally from England, now spoken in many countries",
    sentence: "Our {{BLANK}} teacher always plays fun games to help us remember new words.",
    cn: "我們的英文老師總是用有趣的遊戲幫我們記住新單字。" },
  { word: "geography", pos: "n.", cn_def: "地理學", en_def: "the study of countries, rivers, mountains, and other features of the earth",
    sentence: "Our {{BLANK}} teacher showed us a large map of the world's oceans and continents.",
    cn: "我們的地理老師給我們看了一張世界海洋和大陸的大地圖。" },
  { word: "history", pos: "n.", cn_def: "歷史", en_def: "the study of events that happened in the past",
    sentence: "We are studying the {{BLANK}} of ancient Egypt and its famous pyramids this month.",
    cn: "這個月我們在研究古埃及的歷史及其著名的金字塔。" },
  { word: "mathematics", pos: "n.", cn_def: "數學", en_def: "the study of numbers, shapes, and quantities, often shortened to math",
    sentence: "Solving difficult {{BLANK}} problems gets much easier with a little daily practice.",
    cn: "只要每天稍微練習，解決困難的數學問題就會變得容易許多。" },
  { word: "physical", pos: "adj.", cn_def: "體育的", en_def: "relating to exercise and sport, often shortened to PE in school",
    sentence: "Everyone loves {{BLANK}} education class because we get to play basketball outside.",
    cn: "大家都很喜歡體育課，因為我們可以到外面打籃球。" },
  { word: "physics", pos: "n.", cn_def: "物理學", en_def: "the science that studies matter, energy, and how things move",
    sentence: "In {{BLANK}} class, we used a small ball to learn about gravity and motion.",
    cn: "在物理課上，我們用一個小球來學習重力和運動。" },
  { word: "science", pos: "n.", cn_def: "科學", en_def: "the study of the natural world through observation and experiments",
    sentence: "Our {{BLANK}} teacher brought a real telescope to class for our astronomy lesson.",
    cn: "我們的科學老師帶了一個真正的望遠鏡來上天文學的課。" }
];

// ---- Part 2 data: 35 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (9/9/9/8), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "Every morning, a young boy walks with his best friend from next door. They always go to ______ together.",
    options: ["campus","office","club","school"], answer: 3, vocabIndex: 0 },
  { q: "On the first day, new students explored every building and field at their new school. They toured the whole ______ together.",
    options: ["course","campus","subject","degree"], answer: 1, vocabIndex: 1 },
  { q: "Final exams usually happen during the very last week of school before a long break. They mark the end of the ______.",
    options: ["semester","lesson","course","quiz"], answer: 0, vocabIndex: 2 },
  { q: "She studied hard all week before her math test and felt confident walking in. Afterward, she earned a perfect ______ on it.",
    options: ["degree","subject","course","grade"], answer: 3, vocabIndex: 3 },
  { q: "This summer, my sister wanted to try something creative at the community center. She signed up for an art ______ there.",
    options: ["club","lesson","course","group"], answer: 2, vocabIndex: 4 },
  { q: "In science class today, the topic was how tiny seeds grow into something much bigger. Today's ______ was about plant growth.",
    options: ["lesson","course","subject","exam"], answer: 0, vocabIndex: 5 },
  { q: "Outside the classroom, every student waited quietly and nervously before the big test began. The important ______ was about to start.",
    options: ["lesson","quiz","exam","homework"], answer: 2, vocabIndex: 6 },
  { q: "At the start of every Friday class, our teacher hands out something short and simple. The vocabulary ______ only takes a few minutes.",
    options: ["quiz","exam","test","course"], answer: 0, vocabIndex: 7 },
  { q: "He forgot his pencil case on a very important morning at school. It happened to be the day of the big science ______.",
    options: ["lesson","quiz","subject","test"], answer: 3, vocabIndex: 8 },
  { q: "I always finish my school assignments before dinner every single evening. Doing my ______ early lets me relax later at night.",
    options: ["exam","lesson","homework","course"], answer: 2, vocabIndex: 9 },
  { q: "For six long years, my cousin studied hard at university to reach her goal. She finally earned her ______ in engineering.",
    options: ["grade","course","subject","degree"], answer: 3, vocabIndex: 10 },
  { q: "Even though he had never swum before, he learned the basics surprisingly fast. As a total ______, he could swim within two weeks.",
    options: ["student","member","beginner","leader"], answer: 2, vocabIndex: 11 },
  { q: "For the science project, the teacher split the entire class into smaller teams. Each small ______ worked on a different experiment.",
    options: ["club","course","team","group"], answer: 3, vocabIndex: 12 },
  { q: "Every Tuesday and Thursday afternoon, my brother stays after school for an activity he enjoys. He joined the robotics ______ this year.",
    options: ["club","group","course","team"], answer: 0, vocabIndex: 13 },
  { q: "As soon as a certain sound rang through the hallway, every student rushed outside. That loud ______ meant recess had finally started.",
    options: ["clock","alarm","horn","bell"], answer: 3, vocabIndex: 14 },
  { q: "The teacher wanted everyone to see the homework assignment clearly before leaving. She wrote it neatly on the ______ at the front.",
    options: ["blackboard","textbook","workbook","screen"], answer: 0, vocabIndex: 15 },
  { q: "My desk sits right next to the classroom window, with a clear view outside. My ______ is right beside it, facing the board.",
    options: ["table","chair","shelf","locker"], answer: 1, vocabIndex: 16 },
  { q: "For our outdoor drawing activity, the art teacher gave each student something colorful to use. We drew pictures on the sidewalk using ______.",
    options: ["chalk","paint","crayons","markers"], answer: 0, vocabIndex: 17 },
  { q: "Before reading the next chapter, our history teacher asked us to open a certain book. We turned our ______ to page forty.",
    options: ["notebook","textbook","workbook","dictionary"], answer: 1, vocabIndex: 18 },
  { q: "Every night, two pages of math problems wait for us to solve at home. We complete our math ______ as part of our homework.",
    options: ["textbook","notebook","folder","workbook"], answer: 3, vocabIndex: 19 },
  { q: "Last year, my grandmother decided she wanted to try something completely new for her. She chose to ______ how to use a smartphone.",
    options: ["teach","learn","review","test"], answer: 1, vocabIndex: 20 },
  { q: "After school every day, my brother heads straight to a quiet place full of books. He likes to ______ there until dinner time.",
    options: ["study","learn","teach","review"], answer: 0, vocabIndex: 21 },
  { q: "Before the final exam arrived, our whole class spent a weekend going back over old material. We spent hours ______ together as a group.",
    options: ["learning","reviewing","studying","teaching"], answer: 1, vocabIndex: 22 },
  { q: "Out of every class on my schedule this year, one stands out as my clear favorite. Science is by far my favorite ______.",
    options: ["lesson","course","subject","exam"], answer: 2, vocabIndex: 23 },
  { q: "Today's lesson involved brushes, paper, and many bright colors spread across the tables. In ______ class, we painted pictures of our favorite animals.",
    options: ["art","music","science","history"], answer: 0, vocabIndex: 24 },
  { q: "This week, our teacher explained how a small caterpillar eventually transforms into a colorful butterfly. We learned this in ______ class.",
    options: ["chemistry","physics","biology","geography"], answer: 2, vocabIndex: 25 },
  { q: "During an experiment in the lab today, something unexpected and colorful happened right before our eyes. The clear liquid suddenly turned blue during ______ class.",
    options: ["biology","physics","science","chemistry"], answer: 3, vocabIndex: 26 },
  { q: "In one of our language classes, we spent the whole hour practicing new characters carefully. We wrote them down during ______ class.",
    options: ["English","history","Chinese","art"], answer: 2, vocabIndex: 27 },
  { q: "Our language teacher always finds fun ways to help students remember new vocabulary words. Games make our ______ class much more enjoyable.",
    options: ["Chinese","English","history","science"], answer: 1, vocabIndex: 28 },
  { q: "Today, our teacher unrolled a huge map showing oceans, rivers, and continents around the world. This was part of our ______ lesson.",
    options: ["geography","history","science","math"], answer: 0, vocabIndex: 29 },
  { q: "This month, our class is learning about ancient Egypt and its famous, mysterious pyramids. It is part of our ______ lesson.",
    options: ["geography","history","science","art"], answer: 1, vocabIndex: 30 },
  { q: "Solving number problems used to feel impossible, but daily practice has made it much easier. ______ homework no longer feels so scary.",
    options: ["Science","History","Mathematics","Geography"], answer: 2, vocabIndex: 31 },
  { q: "Everyone looks forward to one particular class because it means playing basketball outside. ______ education is the most popular class of the week.",
    options: ["Art","Physical","Music","Science"], answer: 1, vocabIndex: 32 },
  { q: "In class today, we rolled a small ball across the floor to observe how it moved. This experiment was part of our ______ lesson.",
    options: ["chemistry","biology","physics","geography"], answer: 2, vocabIndex: 33 },
  { q: "Our teacher brought something special into class for our lesson about stars and planets. We used a real telescope during ______ class.",
    options: ["math","science","art","history"], answer: 1, vocabIndex: 34 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "activity": { pos: "n.", en_def: "something done for enjoyment or as part of a plan", cn_def: "活動" },
  "alarm": { pos: "n.", en_def: "a device or sound that warns people of danger", cn_def: "警報" },
  "ancient": { pos: "adj.", en_def: "very old; from a long time ago", cn_def: "古代的" },
  "assignment": { pos: "n.", en_def: "a task or piece of work given to someone", cn_def: "作業；任務" },
  "astronomy": { pos: "n.", en_def: "the scientific study of stars, planets, and space", cn_def: "天文學" },
  "basketball": { pos: "n.", en_def: "a sport played with a round ball and a high hoop", cn_def: "籃球" },
  "butterfly": { pos: "n.", en_def: "a colorful insect with large wings that flies among flowers", cn_def: "蝴蝶" },
  "caterpillar": { pos: "n.", en_def: "a small long creature that later turns into a butterfly or moth", cn_def: "毛毛蟲" },
  "chapter": { pos: "n.", en_def: "a main section of a book", cn_def: "章節" },
  "characters": { pos: "n.", en_def: "written symbols used in a language, like Chinese characters", cn_def: "字；文字" },
  "classroom": { pos: "n.", en_def: "a room where students have lessons", cn_def: "教室" },
  "clock": { pos: "n.", en_def: "a device that shows the time", cn_def: "時鐘" },
  "community": { pos: "n.", en_def: "a group of people living in the same area", cn_def: "社區" },
  "continents": { pos: "n.", en_def: "very large areas of land, like Asia or Africa", cn_def: "大陸（複數）" },
  "crayons": { pos: "n.", en_def: "sticks of colored wax used for drawing", cn_def: "蠟筆" },
  "desk": { pos: "n.", en_def: "a piece of furniture used for writing or working", cn_def: "書桌" },
  "dictionary": { pos: "n.", en_def: "a book that explains the meaning of words", cn_def: "字典" },
  "divided": { pos: "v.", en_def: "split something into smaller parts", cn_def: "分割（過去式）" },
  "drawing": { pos: "n.", en_def: "a picture made with a pencil or pen", cn_def: "繪畫" },
  "earn": { pos: "v.", en_def: "to get something as a result of work or effort", cn_def: "獲得；賺得" },
  "earned": { pos: "v.", en_def: "got something as a result of work or effort", cn_def: "獲得（過去式）" },
  "education": { pos: "n.", en_def: "the process of teaching and learning", cn_def: "教育" },
  "egypt": { pos: "n.", en_def: "a country in northeastern Africa known for ancient pyramids", cn_def: "埃及" },
  "engineering": { pos: "n.", en_def: "the field of designing and building machines or structures", cn_def: "工程學" },
  "experiment": { pos: "n.", en_def: "a scientific test to learn something", cn_def: "實驗" },
  "folder": { pos: "n.", en_def: "a thin case used to hold loose papers", cn_def: "文件夾" },
  "games": { pos: "n.", en_def: "activities played for fun, often with rules", cn_def: "遊戲（複數）" },
  "gravity": { pos: "n.", en_def: "the force that pulls objects toward the earth", cn_def: "重力" },
  "horn": { pos: "n.", en_def: "a device that makes a loud warning sound", cn_def: "喇叭；號角" },
  "leader": { pos: "n.", en_def: "a person who guides or is in charge of a group", cn_def: "領導者" },
  "library": { pos: "n.", en_def: "a building or room with books for reading or borrowing", cn_def: "圖書館" },
  "liquid": { pos: "n.", en_def: "a substance that flows freely, like water", cn_def: "液體" },
  "locker": { pos: "n.", en_def: "a small storage cabinet, often used at school", cn_def: "置物櫃" },
  "map": { pos: "n.", en_def: "a drawing that shows the features of an area, like countries or roads", cn_def: "地圖" },
  "markers": { pos: "n.", en_def: "pens with thick colored tips used for drawing or writing", cn_def: "馬克筆" },
  "math": { pos: "n.", en_def: "the study of numbers, shapes, and quantities", cn_def: "數學" },
  "member": { pos: "n.", en_def: "a person who belongs to a group or club", cn_def: "成員" },
  "month": { pos: "n.", en_def: "one of the twelve parts of a year", cn_def: "月份" },
  "motion": { pos: "n.", en_def: "the act of moving", cn_def: "運動；移動" },
  "music": { pos: "n.", en_def: "sounds arranged in a pleasing way, often with rhythm and melody", cn_def: "音樂" },
  "nervous": { pos: "adj.", en_def: "worried or afraid about what might happen", cn_def: "緊張的" },
  "notebook": { pos: "n.", en_def: "a book with blank pages used for writing notes", cn_def: "筆記本" },
  "notebooks": { pos: "n.", en_def: "books with blank pages used for writing notes", cn_def: "筆記本（複數）" },
  "oceans": { pos: "n.", en_def: "very large areas of salt water", cn_def: "海洋（複數）" },
  "office": { pos: "n.", en_def: "a room or building where people do business work", cn_def: "辦公室" },
  "outdoor": { pos: "adj.", en_def: "happening or used outside, not indoors", cn_def: "戶外的" },
  "paint": { pos: "n.", en_def: "a colored liquid used to add color to a surface or picture", cn_def: "顏料" },
  "painted": { pos: "v.", en_def: "used paint to create a picture or color something", cn_def: "繪畫（過去式）" },
  "pencil": { pos: "n.", en_def: "a thin tool used for writing or drawing", cn_def: "鉛筆" },
  "perfect": { pos: "adj.", en_def: "having no mistakes; completely correct", cn_def: "完美的" },
  "playground": { pos: "n.", en_def: "an outdoor area with equipment for children to play on", cn_def: "操場；遊樂場" },
  "practice": { pos: "v.", en_def: "to do something repeatedly to improve a skill", cn_def: "練習" },
  "practiced": { pos: "v.", en_def: "did something repeatedly to improve a skill", cn_def: "練習（過去式）" },
  "problems": { pos: "n.", en_def: "questions or situations that need to be solved", cn_def: "問題（複數）" },
  "project": { pos: "n.", en_def: "a planned piece of work, often for school", cn_def: "專案；作業" },
  "pyramids": { pos: "n.", en_def: "large stone structures with a square base and triangular sides, found in Egypt", cn_def: "金字塔（複數）" },
  "rang": { pos: "v.", en_def: "made a ringing sound (past tense of ring)", cn_def: "響起（過去式）" },
  "robotics": { pos: "n.", en_def: "the study or building of robots", cn_def: "機器人學" },
  "rushed": { pos: "v.", en_def: "moved quickly and suddenly", cn_def: "衝；急忙（過去式）" },
  "screen": { pos: "n.", en_def: "the flat surface on a device where images and text appear", cn_def: "螢幕" },
  "seeds": { pos: "n.", en_def: "small parts of a plant from which a new plant grows", cn_def: "種子（複數）" },
  "shade": { pos: "n.", en_def: "a particular tone of a color", cn_def: "色調" },
  "shelf": { pos: "n.", en_def: "a flat board used for storing or displaying things", cn_def: "架子" },
  "signed": { pos: "v.", en_def: "registered or wrote one's name", cn_def: "報名；簽名（過去式）" },
  "smartphone": { pos: "n.", en_def: "a mobile phone that can connect to the Internet and run apps", cn_def: "智慧型手機" },
  "solving": { pos: "v.", en_def: "finding the answer to a problem", cn_def: "解決" },
  "student": { pos: "n.", en_def: "a person who is studying at a school", cn_def: "學生" },
  "table": { pos: "n.", en_def: "a piece of furniture with a flat top", cn_def: "桌子" },
  "teach": { pos: "v.", en_def: "to help someone learn something", cn_def: "教導" },
  "team": { pos: "n.", en_def: "a group of people playing or working together", cn_def: "隊伍" },
  "telescope": { pos: "n.", en_def: "a tool used to see distant objects, like stars, more clearly", cn_def: "望遠鏡" },
  "tour": { pos: "n.", en_def: "a trip around a place to see different parts of it", cn_def: "參觀；遊覽" },
  "vocabulary": { pos: "n.", en_def: "the words used in a language", cn_def: "詞彙" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});

// ---- Verb-form / plural aliases so MCQ option lookups resolve correctly ----
const PLURAL_ALIASES = {
  "learning": "learn", "studying": "study", "reviewing": "review", "teaching": "teach",
  "schools": "school", "exams": "exam", "quizzes": "quiz", "tests": "test",
  "lessons": "lesson", "courses": "course", "subjects": "subject", "groups": "group",
  "clubs": "club", "chairs": "chair", "textbooks": "textbook", "workbooks": "workbook",
  "degrees": "degree", "beginners": "beginner", "grades": "grade"
};
Object.keys(PLURAL_ALIASES).forEach(plural => {
  const singular = PLURAL_ALIASES[plural];
  if (!LOOKUP[plural] && LOOKUP[singular]) {
    LOOKUP[plural] = LOOKUP[singular];
  }
});
