// ============================================================
// Group 10 Quiz Data: Roles / Characters / Personality
// Full word set (45 words) — roles, characters, and personality
// traits from the "people / family / jobs / personality" theme.
// This completes the theme started in Group 8 (Family/People/
// Age/Titles) and continued in Group 9 (Jobs/Professions).
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 10 - Roles / Characters / Personality (角色/人物/個性)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (45 words) ----
const VOCAB = [
  { word: "character", pos: "n.", cn_def: "角色", en_def: "a person in a story, movie, or play",
    sentence: "My favorite {{BLANK}} in the movie was the brave young girl who saved her village.",
    cn: "我在這部電影裡最喜歡的角色是那位拯救村莊的勇敢女孩。" },
  { word: "role", pos: "n.", cn_def: "角色", en_def: "the part a person plays in a movie, play, or situation",
    sentence: "She practiced for weeks before finally winning the lead {{BLANK}} in the school play.",
    cn: "她練習了好幾個星期，終於在學校的話劇中贏得了主角這個角色。" },
  { word: "angel", pos: "n.", cn_def: "天使", en_def: "a spiritual being often shown with wings, believed to help people",
    sentence: "In the old painting, a small {{BLANK}} floats gently above the sleeping baby.",
    cn: "在這幅古老的畫作中，一個小天使輕輕地飄浮在熟睡的嬰兒上方。" },
  { word: "dragon", pos: "n.", cn_def: "龍", en_def: "a large imaginary creature that can fly and breathe fire",
    sentence: "In the story, a brave knight finally defeated the fierce {{BLANK}} guarding the castle.",
    cn: "在這個故事裡，一位勇敢的騎士終於打敗了守護城堡的兇猛巨龍。" },
  { word: "ghost", pos: "n.", cn_def: "鬼", en_def: "the spirit of a dead person, believed to appear to the living",
    sentence: "My little brother was too scared to watch the {{BLANK}} movie alone at night.",
    cn: "我弟弟太害怕了，晚上不敢獨自看那部鬼片。" },
  { word: "god", pos: "n.", cn_def: "神", en_def: "a powerful being worshipped in a religion",
    sentence: "In ancient Greek stories, every {{BLANK}} controlled a different part of nature.",
    cn: "在古希臘的故事裡，每位神都掌控著自然界的不同部分。" },
  { word: "monster", pos: "n.", cn_def: "怪物", en_def: "a large, frightening imaginary creature",
    sentence: "The little boy hid under his blanket, afraid a {{BLANK}} was hiding in his closet.",
    cn: "那個小男孩躲在被子下面，害怕衣櫃裡藏著怪物。" },
  { word: "customer", pos: "n.", cn_def: "顧客", en_def: "a person who buys goods or services from a shop or business",
    sentence: "The shop owner greeted every {{BLANK}} with a warm smile at the door.",
    cn: "店主在門口用溫暖的笑容迎接每一位顧客。" },
  { word: "guest", pos: "n.", cn_def: "客人", en_def: "a person who is invited to visit or stay somewhere",
    sentence: "My mother prepared extra food because we were expecting several {{BLANK}} for dinner.",
    cn: "我媽媽多準備了一些食物，因為我們晚餐預計會有好幾位客人。" },
  { word: "passenger", pos: "n.", cn_def: "乘客", en_def: "a person traveling in a vehicle who is not driving it",
    sentence: "Every {{BLANK}} on the plane was asked to fasten their seatbelt before landing.",
    cn: "飛機上的每位乘客在降落前都被要求繫好安全帶。" },
  { word: "enemy", pos: "n.", cn_def: "敵人", en_def: "a person who is against you or wants to harm you",
    sentence: "In the video game, players must defeat every {{BLANK}} to reach the final level.",
    cn: "在這款電玩遊戲中，玩家必須打敗每一個敵人才能進入最後一關。" },
  { word: "neighbor", pos: "n.", cn_def: "鄰居", en_def: "a person who lives near you",
    sentence: "Our friendly {{BLANK}} always waters our plants whenever we go on vacation.",
    cn: "我們友善的鄰居每次我們去旅行時都會幫忙澆花。" },
  { word: "friend", pos: "n.", cn_def: "朋友", en_def: "a person you know well and like",
    sentence: "My best {{BLANK}} and I have known each other since elementary school.",
    cn: "我最好的朋友和我從小學就認識了。" },
  { word: "partner", pos: "n.", cn_def: "夥伴", en_def: "a person who works together with you on something",
    sentence: "For the science project, my {{BLANK}} and I built a small model volcano.",
    cn: "為了這個科學作業，我的夥伴和我做了一個小型的火山模型。" },
  { word: "stranger", pos: "n.", cn_def: "陌生人", en_def: "a person you do not know",
    sentence: "My parents always tell me never to get into a car with a {{BLANK}}.",
    cn: "我父母總是告訴我絕對不要上陌生人的車。" },
  { word: "visitor", pos: "n.", cn_def: "訪客", en_def: "a person who comes to see a place or person",
    sentence: "Every {{BLANK}} must sign in at the front desk before entering the building.",
    cn: "每位訪客在進入大樓前都必須在櫃台登記。" },
  { word: "fool", pos: "n.", cn_def: "傻瓜", en_def: "a person who does something silly or unwise",
    sentence: "He felt like a complete {{BLANK}} after forgetting his own birthday party.",
    cn: "他忘了自己的生日派對，覺得自己像個十足的傻瓜。" },
  { word: "genius", pos: "n.", cn_def: "天才", en_def: "a person with extremely high intelligence or talent",
    sentence: "Everyone in class called her a {{BLANK}} after she solved the hardest math problem instantly.",
    cn: "她瞬間解出了最難的數學題，全班都稱她為天才。" },
  { word: "giant", pos: "n.", cn_def: "巨人", en_def: "an imaginary very large person in stories",
    sentence: "In the old fairy tale, a friendly {{BLANK}} helped the small village build a new bridge.",
    cn: "在這個古老的童話故事裡，一位友善的巨人幫助小村莊建造了一座新橋。" },
  { word: "hero", pos: "n.", cn_def: "英雄", en_def: "a person admired for great courage or brave actions",
    sentence: "The firefighter became a local {{BLANK}} after rescuing the family from the burning building.",
    cn: "那位消防員救出燃燒大樓裡的家庭後，成為了當地的英雄。" },
  { word: "hunter", pos: "n.", cn_def: "獵人", en_def: "a person who hunts wild animals for food or sport",
    sentence: "The experienced {{BLANK}} moved silently through the forest, following the deer's tracks.",
    cn: "那位經驗豐富的獵人在森林中悄悄前行，跟著鹿的足跡。" },
  { word: "host", pos: "n.", cn_def: "主人", en_def: "a person who welcomes and takes care of guests",
    sentence: "As the {{BLANK}} of the party, my aunt made sure everyone had enough food.",
    cn: "作為派對的主人，我阿姨確保每個人都有足夠的食物。" },
  { word: "leader", pos: "n.", cn_def: "領導者", en_def: "a person who guides or is in charge of a group",
    sentence: "Our class chose a new {{BLANK}} to organize the trip to the science museum.",
    cn: "我們班選出了一位新的領導者來籌辦去科學博物館的旅行。" },
  { word: "player", pos: "n.", cn_def: "選手", en_def: "a person who takes part in a game or sport",
    sentence: "The youngest {{BLANK}} on the team scored the winning goal in the last minute.",
    cn: "隊上最年輕的選手在最後一分鐘踢進了致勝的一球。" },
  { word: "thief", pos: "n.", cn_def: "小偷", en_def: "a person who steals things from others",
    sentence: "The {{BLANK}} ran quickly down the alley after grabbing the woman's purse.",
    cn: "那個小偷搶走那位女士的錢包後迅速沿著巷子跑走了。" },
  { word: "king", pos: "n.", cn_def: "國王", en_def: "a male ruler of a country, usually inheriting the position",
    sentence: "In the old story, the {{BLANK}} ruled the kingdom wisely for over forty years.",
    cn: "在這個古老的故事中，國王明智地統治王國長達四十多年。" },
  { word: "queen", pos: "n.", cn_def: "皇后", en_def: "a female ruler of a country, or the wife of a king",
    sentence: "The {{BLANK}} wore a beautiful golden crown during the entire ceremony.",
    cn: "皇后在整個典禮中都戴著一頂美麗的金色皇冠。" },
  { word: "prince", pos: "n.", cn_def: "王子", en_def: "the son of a king or queen",
    sentence: "The young {{BLANK}} learned how to ride a horse before his tenth birthday.",
    cn: "那位年輕的王子在十歲生日前學會了騎馬。" },
  { word: "princess", pos: "n.", cn_def: "公主", en_def: "the daughter of a king or queen",
    sentence: "In the fairy tale, the {{BLANK}} escaped from the tall tower using a long rope.",
    cn: "在這個童話故事裡，公主用一條長繩子從高塔逃了出來。" },
  { word: "servant", pos: "n.", cn_def: "僕人", en_def: "a person who works in someone's home, helping with daily tasks",
    sentence: "In the old castle, a loyal {{BLANK}} brought food to the king every evening.",
    cn: "在這座古老的城堡裡，一位忠誠的僕人每天晚上都會為國王送上食物。" },
  { word: "polite", pos: "adj.", cn_def: "有禮貌的", en_def: "having good manners; respectful toward others",
    sentence: "The new student was so {{BLANK}} that all the teachers liked him immediately.",
    cn: "那位新學生非常有禮貌，所有老師都立刻喜歡上他。" },
  { word: "impolite", pos: "adj.", cn_def: "沒禮貌的", en_def: "not having good manners; rude",
    sentence: "It is considered {{BLANK}} to talk loudly on your phone during a quiet meal.",
    cn: "在安靜的用餐時間大聲講電話被認為是沒禮貌的行為。" },
  { word: "rude", pos: "adj.", cn_def: "無禮的", en_def: "not polite; showing no respect for others",
    sentence: "Everyone was shocked when the customer spoke in such a {{BLANK}} way to the waiter.",
    cn: "當那位顧客對服務生說話如此無禮時，大家都感到很驚訝。" },
  { word: "intelligent", pos: "adj.", cn_def: "明智的", en_def: "able to think, learn, and understand things well",
    sentence: "Even as a young child, she was clearly very {{BLANK}} and curious about everything.",
    cn: "即使在小時候，她也明顯非常明智且對一切都充滿好奇心。" },
  { word: "clever", pos: "adj.", cn_def: "聰明的", en_def: "able to think quickly and find smart solutions",
    sentence: "The {{BLANK}} fox found a clever way to escape from the trap.",
    cn: "那隻聰明的狐狸找到了一個巧妙的方法逃出陷阱。" },
  { word: "smart", pos: "adj.", cn_def: "聰明的", en_def: "intelligent; quick to learn or understand",
    sentence: "My older sister is very {{BLANK}} and always finishes her homework in record time.",
    cn: "我姐姐非常聰明，總是能以最快的速度完成作業。" },
  { word: "wise", pos: "adj.", cn_def: "有智慧的", en_def: "having good judgment based on knowledge and experience",
    sentence: "The {{BLANK}} old teacher always gave us thoughtful advice when we were confused.",
    cn: "那位有智慧的老老師總是在我們困惑時給予我們深思熟慮的建議。" },
  { word: "foolish", pos: "adj.", cn_def: "愚蠢的", en_def: "lacking good sense; unwise",
    sentence: "It was {{BLANK}} of him to leave his bike unlocked outside the busy station.",
    cn: "他把自行車沒鎖就放在繁忙的車站外面，這樣做真是愚蠢。" },
  { word: "silly", pos: "adj.", cn_def: "傻的", en_def: "behaving in a way that is not serious or sensible",
    sentence: "We all laughed at his {{BLANK}} joke about the talking banana.",
    cn: "我們都被他那個關於會說話的香蕉的傻笑話逗笑了。" },
  { word: "stupid", pos: "adj.", cn_def: "愚笨的", en_def: "showing a lack of good judgment or intelligence",
    sentence: "Forgetting my umbrella on the rainiest day of the year felt like a {{BLANK}} mistake.",
    cn: "在這一年最多雨的日子忘記帶傘，這真是個愚笨的錯誤。" },
  { word: "shy", pos: "adj.", cn_def: "害羞的", en_def: "nervous or uncomfortable around other people",
    sentence: "My little cousin is too {{BLANK}} to speak in front of the whole class.",
    cn: "我的表弟太害羞了，不敢在全班面前說話。" },
  { word: "talkative", pos: "adj.", cn_def: "愛說話的", en_def: "liking to talk a lot",
    sentence: "My uncle is so {{BLANK}} that family dinners never have a single quiet moment.",
    cn: "我叔叔非常愛說話，家庭聚餐時從來沒有一刻是安靜的。" },
  { word: "goodness", pos: "n.", cn_def: "善良", en_def: "the quality of being kind and morally good",
    sentence: "The old man's {{BLANK}} was clear to everyone who watched him help the stray dog.",
    cn: "看到那位老人幫助流浪狗的人都能感受到他的善良。" },
  { word: "honesty", pos: "n.", cn_def: "誠實", en_def: "the quality of telling the truth and being sincere",
    sentence: "My parents always remind me that {{BLANK}} is more important than getting a perfect score.",
    cn: "我父母總是提醒我，誠實比得到滿分更重要。" },
  { word: "humor", pos: "n.", cn_def: "幽默", en_def: "the quality of being funny or amusing",
    sentence: "Even during the stressful exam week, my friend's {{BLANK}} always made us laugh.",
    cn: "即使在壓力很大的考試週，我朋友的幽默感總是能讓我們笑出來。" }
];

// ---- Part 2 data: 45 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (12/11/11/11), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "In the movie, one person stood out more than anyone else for me. My favorite ______ was the brave young girl.",
    options: ["actor","writer","host","character"], answer: 3, vocabIndex: 0 },
  { q: "After weeks of practice, someone finally got the most important part in the play. She won the lead ______ in the show.",
    options: ["role","job","team","prize"], answer: 0, vocabIndex: 1 },
  { q: "In the old painting, a small winged figure floats above a sleeping baby. The peaceful ______ seems to be watching over the child.",
    options: ["ghost","angel","monster","giant"], answer: 1, vocabIndex: 2 },
  { q: "In the story, a brave knight faced a fierce fire-breathing creature near the castle. The knight finally defeated the dangerous ______.",
    options: ["monster","thief","dragon","enemy"], answer: 2, vocabIndex: 3 },
  { q: "My little brother refused to watch a certain kind of scary movie alone at night. He was too afraid of the ______ in it.",
    options: ["hero","ghost","stranger","hunter"], answer: 1, vocabIndex: 4 },
  { q: "In ancient Greek stories, many powerful beings each controlled a different part of nature. Every ______ had its own special power.",
    options: ["god","king","leader","giant"], answer: 0, vocabIndex: 5 },
  { q: "The little boy hid under his blanket, feeling nervous about something in his closet. He was afraid a ______ was hiding there.",
    options: ["thief","monster","stranger","ghost"], answer: 1, vocabIndex: 6 },
  { q: "At the small shop, the owner always welcomed visitors with a warm, friendly smile. Every ______ felt comfortable shopping there.",
    options: ["guest","visitor","customer","partner"], answer: 2, vocabIndex: 7 },
  { q: "My mother cooked extra food because several people were coming for dinner that evening. She wanted every ______ to feel welcome.",
    options: ["guest","customer","stranger","neighbor"], answer: 0, vocabIndex: 8 },
  { q: "Before the plane landed, the flight crew checked that everyone was safely buckled in. Every ______ followed the safety instructions.",
    options: ["visitor","passenger","host","player"], answer: 1, vocabIndex: 9 },
  { q: "In the video game, players need to defeat every opponent to reach the final level. Each ______ becomes harder to beat.",
    options: ["friend","partner","enemy","hero"], answer: 2, vocabIndex: 10 },
  { q: "Whenever we travel, someone next door always kindly takes care of our garden for us. Our friendly ______ waters all the plants.",
    options: ["neighbor","host","guest","stranger"], answer: 0, vocabIndex: 11 },
  { q: "I have known one particular classmate since elementary school, and we are still very close. My best ______ always understands me.",
    options: ["partner","neighbor","friend","host"], answer: 2, vocabIndex: 12 },
  { q: "For the science project, two students worked together and built a small model volcano. My ______ and I shared every task equally.",
    options: ["friend","partner","neighbor","leader"], answer: 1, vocabIndex: 13 },
  { q: "My parents always remind me to be careful around people I have never met before. They warn me never to trust a ______.",
    options: ["guest","visitor","thief","stranger"], answer: 3, vocabIndex: 14 },
  { q: "Before entering the office building, everyone is asked to write down their name at the front desk. Each ______ must sign in first.",
    options: ["customer","visitor","passenger","guest"], answer: 1, vocabIndex: 15 },
  { q: "He completely forgot about his own birthday party and felt embarrassed afterward. He said he felt like a complete ______.",
    options: ["stranger","thief","hero","fool"], answer: 3, vocabIndex: 16 },
  { q: "After solving the hardest math problem in just a few seconds, everyone was amazed. The whole class called her a true ______.",
    options: ["leader","hero","genius","player"], answer: 2, vocabIndex: 17 },
  { q: "In the old fairy tale, an unusually large and kind figure helped the village build something important. The friendly ______ built a new bridge.",
    options: ["king","hero","god","giant"], answer: 3, vocabIndex: 18 },
  { q: "The firefighter bravely ran into a burning building to save a trapped family. After that day, everyone called him a true ______.",
    options: ["hero","leader","host","king"], answer: 0, vocabIndex: 19 },
  { q: "Deep in the quiet forest, someone moved carefully while following the tracks of a deer. The skilled ______ made almost no sound.",
    options: ["thief","hunter","enemy","stranger"], answer: 1, vocabIndex: 20 },
  { q: "At the busy party, my aunt made sure every guest had enough food and a comfortable seat. As the ______, she worked all evening.",
    options: ["guest","visitor","host","partner"], answer: 2, vocabIndex: 21 },
  { q: "Before the class trip, students needed someone to plan and organize the whole day. They chose a new ______ for the job.",
    options: ["host","leader","hero","king"], answer: 1, vocabIndex: 22 },
  { q: "In the final minute of the game, someone on the team scored the winning goal. The youngest ______ became the hero of the match.",
    options: ["leader","host","hunter","player"], answer: 3, vocabIndex: 23 },
  { q: "Someone grabbed the woman's purse and ran quickly down the narrow alley. Police were soon searching for the missing ______.",
    options: ["stranger","hunter","thief","enemy"], answer: 2, vocabIndex: 24 },
  { q: "In the old story, one ruler governed the kingdom carefully for more than forty years. The wise ______ was loved by everyone.",
    options: ["leader","host","hero","king"], answer: 3, vocabIndex: 25 },
  { q: "During the long royal ceremony, one important woman wore a beautiful golden crown the whole time. The ______ smiled warmly at the crowd.",
    options: ["princess","host","queen","guest"], answer: 2, vocabIndex: 26 },
  { q: "Before turning ten, a young boy from the royal family learned an important new skill. The ______ practiced riding his horse every day.",
    options: ["king","hero","leader","prince"], answer: 3, vocabIndex: 27 },
  { q: "In the fairy tale, a young woman trapped in a tall tower found a clever way to leave. The ______ used a long rope to escape.",
    options: ["princess","queen","host","guest"], answer: 0, vocabIndex: 28 },
  { q: "In the old castle, one loyal worker brought food to the king every single evening without fail. The quiet ______ never complained.",
    options: ["guest","guard","host","servant"], answer: 3, vocabIndex: 29 },
  { q: "The new student always said please and thank you, and held the door open for others. All the teachers liked how ______ he was.",
    options: ["clever","talkative","polite","shy"], answer: 2, vocabIndex: 30 },
  { q: "During a quiet family meal, talking loudly on the phone is generally seen as a bad habit. Many people consider this kind of behavior ______.",
    options: ["impolite","wise","smart","honest"], answer: 0, vocabIndex: 31 },
  { q: "Everyone in the restaurant was shocked by how the customer spoke to the waiter that evening. His tone was unusually sharp and ______.",
    options: ["shy","wise","silly","rude"], answer: 3, vocabIndex: 32 },
  { q: "Even as a young child, she showed unusual curiosity and asked thoughtful questions about everything. Her teachers always called her remarkably ______.",
    options: ["intelligent","talkative","shy","foolish"], answer: 0, vocabIndex: 33 },
  { q: "Trapped inside the cage, the small fox thought carefully and found an unexpected way out. Everyone agreed the fox had been very ______.",
    options: ["foolish","clever","rude","shy"], answer: 1, vocabIndex: 34 },
  { q: "My older sister always finishes her homework quickly and rarely makes careless mistakes. Her teachers often describe her as extremely ______.",
    options: ["smart","talkative","polite","shy"], answer: 0, vocabIndex: 35 },
  { q: "Whenever we felt confused about a problem, our old teacher gave thoughtful advice based on years of experience. Everyone agreed she was truly ______.",
    options: ["rude","silly","wise","talkative"], answer: 2, vocabIndex: 36 },
  { q: "He left his bicycle unlocked outside the crowded train station for several hours. Looking back, even he admitted that was a ______ decision.",
    options: ["foolish","wise","clever","polite"], answer: 0, vocabIndex: 37 },
  { q: "His joke about a talking banana made absolutely no sense, yet everyone laughed anyway. It was a completely ______ thing to say.",
    options: ["wise","rude","intelligent","silly"], answer: 3, vocabIndex: 38 },
  { q: "On the rainiest day of the entire year, he somehow forgot to bring his umbrella with him. He called it a truly ______ mistake.",
    options: ["clever","stupid","wise","polite"], answer: 1, vocabIndex: 39 },
  { q: "My little cousin gets nervous whenever asked to speak in front of the whole class. She is simply too ______ to raise her hand.",
    options: ["talkative","rude","shy","smart"], answer: 2, vocabIndex: 40 },
  { q: "During family dinners, my uncle never stops talking, even for a single quiet moment. Everyone agrees he is incredibly ______.",
    options: ["shy","talkative","polite","wise"], answer: 1, vocabIndex: 41 },
  { q: "The old man patiently stopped to help an injured stray dog on his way home. Everyone who saw it noticed his quiet ______.",
    options: ["goodness","honesty","humor","courage"], answer: 0, vocabIndex: 42 },
  { q: "My parents always remind me that telling the truth matters more than getting a perfect grade. They say ______ is the most important value.",
    options: ["goodness","humor","kindness","honesty"], answer: 3, vocabIndex: 43 },
  { q: "Even during the most stressful week of exams, my friend always found a way to make everyone smile. His ______ never seemed to fail.",
    options: ["humor","honesty","goodness","kindness"], answer: 0, vocabIndex: 44 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "actor": { pos: "n.", en_def: "a man who performs in movies, plays, or TV shows", cn_def: "男演員" },
  "advice": { pos: "n.", en_def: "a suggestion about what someone should do", cn_def: "建議" },
  "afraid": { pos: "adj.", en_def: "feeling fear about something", cn_def: "害怕的" },
  "alley": { pos: "n.", en_def: "a narrow street or passage between buildings", cn_def: "巷子" },
  "ancient": { pos: "adj.", en_def: "very old; from a long time ago", cn_def: "古代的" },
  "blanket": { pos: "n.", en_def: "a thick piece of cloth used for warmth, especially on a bed", cn_def: "毯子" },
  "brave": { pos: "adj.", en_def: "showing no fear when facing danger", cn_def: "勇敢的" },
  "bridge": { pos: "n.", en_def: "a structure built over a river or road so people can cross", cn_def: "橋" },
  "building": { pos: "n.", en_def: "a structure with walls and a roof", cn_def: "建築物" },
  "burning": { pos: "adj.", en_def: "on fire", cn_def: "燃燒的" },
  "castle": { pos: "n.", en_def: "a large old building, often with high walls, built for a king or noble", cn_def: "城堡" },
  "ceremony": { pos: "n.", en_def: "a formal event held for a special occasion", cn_def: "典禮" },
  "closet": { pos: "n.", en_def: "a small room or cabinet used for storing clothes or things", cn_def: "衣櫃；儲藏室" },
  "confused": { pos: "adj.", en_def: "unable to think clearly or understand something", cn_def: "困惑的" },
  "considered": { pos: "v.", en_def: "thought about something carefully, or regarded it in a certain way", cn_def: "認為（過去式）" },
  "controlled": { pos: "v.", en_def: "had power over something", cn_def: "控制（過去式）" },
  "courage": { pos: "n.", en_def: "the ability to face danger or fear without giving up", cn_def: "勇氣" },
  "crown": { pos: "n.", en_def: "a decorative headpiece worn by kings or queens", cn_def: "皇冠" },
  "curious": { pos: "adj.", en_def: "wanting to know or learn about something", cn_def: "好奇的" },
  "deer": { pos: "n.", en_def: "a graceful wild animal with antlers, found in forests", cn_def: "鹿" },
  "defeated": { pos: "v.", en_def: "won against someone in a fight or contest", cn_def: "打敗（過去式）" },
  "elementary": { pos: "adj.", en_def: "relating to the basic first stage of school", cn_def: "初級的；小學的" },
  "embarrassed": { pos: "adj.", en_def: "feeling shy or uncomfortable because of a mistake", cn_def: "尷尬的" },
  "entire": { pos: "adj.", en_def: "whole; complete", cn_def: "整個的" },
  "escape": { pos: "v.", en_def: "to get free from a place or danger", cn_def: "逃脫" },
  "escaped": { pos: "v.", en_def: "got free from a place or danger", cn_def: "逃脫（過去式）" },
  "exam": { pos: "n.", en_def: "a test of knowledge or skill", cn_def: "考試" },
  "expecting": { pos: "v.", en_def: "believing that something will happen or someone will arrive", cn_def: "期待；預期" },
  "experienced": { pos: "adj.", en_def: "having done something many times and gained skill", cn_def: "有經驗的" },
  "fairy tale": { pos: "n.", en_def: "a children's story with magic, often with kings, queens, and monsters", cn_def: "童話故事" },
  "fasten": { pos: "v.", en_def: "to close or attach something firmly", cn_def: "繫上" },
  "fierce": { pos: "adj.", en_def: "very aggressive or violent", cn_def: "兇猛的" },
  "firefighter": { pos: "n.", en_def: "a person whose job is to put out fires", cn_def: "消防員" },
  "floats": { pos: "v.", en_def: "stays in the air or on water without sinking", cn_def: "漂浮" },
  "forest": { pos: "n.", en_def: "a large area covered with trees", cn_def: "森林" },
  "forty": { pos: "n.", en_def: "the number 40", cn_def: "四十" },
  "fox": { pos: "n.", en_def: "a wild animal that looks like a dog with red fur and a pointed face", cn_def: "狐狸" },
  "goal": { pos: "n.", en_def: "a point scored in a game like soccer", cn_def: "球門；得分" },
  "golden": { pos: "adj.", en_def: "made of or colored like gold", cn_def: "金色的" },
  "grabbing": { pos: "v.", en_def: "taking hold of something quickly and roughly", cn_def: "抓取" },
  "greeted": { pos: "v.", en_def: "said hello to someone in a friendly way", cn_def: "問候（過去式）" },
  "guard": { pos: "n.", en_def: "a person whose job is to protect people or places", cn_def: "警衛" },
  "honest": { pos: "adj.", en_def: "telling the truth; not lying", cn_def: "誠實的" },
  "instantly": { pos: "adv.", en_def: "immediately; right away", cn_def: "立刻地" },
  "job": { pos: "n.", en_def: "the work a person does regularly to earn money", cn_def: "工作" },
  "joke": { pos: "n.", en_def: "something said to make people laugh", cn_def: "笑話" },
  "kindness": { pos: "n.", en_def: "the quality of being kind and caring", cn_def: "親切；善意" },
  "kingdom": { pos: "n.", en_def: "a country ruled by a king or queen", cn_def: "王國" },
  "knight": { pos: "n.", en_def: "a brave soldier from old times who often rode a horse", cn_def: "騎士" },
  "landing": { pos: "v.", en_def: "coming down to the ground, especially of a plane", cn_def: "降落" },
  "lead": { pos: "adj.", en_def: "the main or most important, as in a lead role", cn_def: "主要的" },
  "level": { pos: "n.", en_def: "a stage or part of a game", cn_def: "關卡" },
  "loyal": { pos: "adj.", en_def: "always faithful and supportive", cn_def: "忠誠的" },
  "match": { pos: "n.", en_def: "a sports game between two players or teams", cn_def: "比賽" },
  "model": { pos: "n.", en_def: "a small copy of something, often built for a project", cn_def: "模型" },
  "museum": { pos: "n.", en_def: "a building where interesting old or rare things are shown", cn_def: "博物館" },
  "narrow": { pos: "adj.", en_def: "not wide; having a small distance from side to side", cn_def: "狹窄的" },
  "organize": { pos: "v.", en_def: "to plan and arrange something", cn_def: "組織；籌辦" },
  "owner": { pos: "n.", en_def: "a person who owns something, like a shop", cn_def: "老闆；所有者" },
  "painting": { pos: "n.", en_def: "a picture made with paint", cn_def: "畫作" },
  "perfect": { pos: "adj.", en_def: "having no mistakes; completely correct", cn_def: "完美的" },
  "prize": { pos: "n.", en_def: "something given to a winner", cn_def: "獎品" },
  "problem": { pos: "n.", en_def: "a difficult question or situation to solve", cn_def: "問題" },
  "purse": { pos: "n.", en_def: "a small bag used to carry money and personal items", cn_def: "錢包；手提包" },
  "rescuing": { pos: "v.", en_def: "saving someone from danger", cn_def: "救援" },
  "rope": { pos: "n.", en_def: "a thick strong cord used for tying or climbing", cn_def: "繩子" },
  "ruled": { pos: "v.", en_def: "governed a country as a king, queen, or leader", cn_def: "統治（過去式）" },
  "saved": { pos: "v.", en_def: "rescued someone from danger", cn_def: "拯救（過去式）" },
  "score": { pos: "n.", en_def: "the number of points earned in a game or test", cn_def: "分數" },
  "scored": { pos: "v.", en_def: "got points in a game", cn_def: "得分（過去式）" },
  "seatbelt": { pos: "n.", en_def: "a strap used to keep a person safe in a vehicle or plane", cn_def: "安全帶" },
  "shocked": { pos: "adj.", en_def: "feeling very surprised, often unpleasantly", cn_def: "震驚的" },
  "silently": { pos: "adv.", en_def: "without making any sound", cn_def: "悄悄地；安靜地" },
  "solved": { pos: "v.", en_def: "found the answer to a problem", cn_def: "解決（過去式）" },
  "station": { pos: "n.", en_def: "a place where trains or buses stop", cn_def: "車站" },
  "stray": { pos: "adj.", en_def: "having no home, often used for lost animals", cn_def: "流浪的" },
  "stressful": { pos: "adj.", en_def: "causing worry and tension", cn_def: "壓力大的" },
  "tale": { pos: "n.", en_def: "a story, especially one that may not be completely true", cn_def: "故事" },
  "team": { pos: "n.", en_def: "a group of people playing or working together", cn_def: "隊伍；團隊" },
  "tenth": { pos: "adj.", en_def: "coming after the ninth; number 10 in order", cn_def: "第十的" },
  "thoughtful": { pos: "adj.", en_def: "showing careful thinking; considerate", cn_def: "體貼的；深思的" },
  "tower": { pos: "n.", en_def: "a tall narrow building or structure", cn_def: "塔" },
  "tracks": { pos: "n.", en_def: "marks left on the ground by an animal or person", cn_def: "足跡" },
  "trap": { pos: "n.", en_def: "a device or situation used to catch someone or something", cn_def: "陷阱" },
  "umbrella": { pos: "n.", en_def: "a folding device used to keep dry in the rain", cn_def: "雨傘" },
  "unlocked": { pos: "adj.", en_def: "not locked; open", cn_def: "沒鎖的" },
  "village": { pos: "n.", en_def: "a small group of houses, smaller than a town", cn_def: "村莊" },
  "volcano": { pos: "n.", en_def: "a mountain that can erupt with lava and ash", cn_def: "火山" },
  "waiter": { pos: "n.", en_def: "a person who serves food in a restaurant", cn_def: "服務生" },
  "winning": { pos: "adj.", en_def: "resulting in success or victory", cn_def: "獲勝的" },
  "wisely": { pos: "adv.", en_def: "in a way that shows good judgment", cn_def: "明智地" },
  "writer": { pos: "n.", en_def: "a person who writes books, articles, or stories as a job", cn_def: "作家" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});

// ---- Plural aliases so MCQ option lookups resolve correctly ----
const PLURAL_ALIASES = {
  "characters": "character", "roles": "role", "angels": "angel", "dragons": "dragon",
  "ghosts": "ghost", "gods": "god", "monsters": "monster", "customers": "customer",
  "guests": "guest", "passengers": "passenger", "enemies": "enemy", "neighbors": "neighbor",
  "friends": "friend", "partners": "partner", "strangers": "stranger", "visitors": "visitor",
  "fools": "fool", "geniuses": "genius", "giants": "giant", "heroes": "hero",
  "hunters": "hunter", "hosts": "host", "leaders": "leader", "players": "player",
  "thieves": "thief", "kings": "king", "queens": "queen", "princes": "prince",
  "princesses": "princess", "servants": "servant", "teams": "team", "jobs": "job",
  "writers": "writer", "actors": "actor", "guards": "guard"
};
Object.keys(PLURAL_ALIASES).forEach(plural => {
  const singular = PLURAL_ALIASES[plural];
  if (!LOOKUP[plural] && LOOKUP[singular]) {
    LOOKUP[plural] = LOOKUP[singular];
  }
});
