// ============================================================
// Group 36 Quiz Data: Actions, Part 5
// Full word set (36 words) — the fifth portion of the
// "actions" theme (252-word flat verb list). Continues from
// Group 35 (Actions, Part 4). Split into 7 groups of 36 words
// each (Groups 32-38) per the person's request.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 36 - Actions, Part 5 (動作 五)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (36 words) ----
const VOCAB = [
  { word: "inspire", pos: "v.", cn_def: "激勵", en_def: "to make someone feel excited and want to do something",
    sentence: "Her amazing story continued to {{BLANK}} students for many years afterward.",
    cn: "她驚人的故事多年來持續激勵著學生。" },
  { word: "introduce", pos: "v.", cn_def: "介紹", en_def: "to tell someone the name of another person when they meet",
    sentence: "Let me {{BLANK}} you to my new neighbor from across the street.",
    cn: "讓我把你介紹給我住在對街的新鄰居認識。" },
  { word: "invent", pos: "v.", cn_def: "發明", en_def: "to create something new that did not exist before",
    sentence: "Scientists are always trying to {{BLANK}} cleaner ways to produce electricity.",
    cn: "科學家總是試圖發明更乾淨的發電方式。" },
  { word: "invite", pos: "v.", cn_def: "邀請", en_def: "to ask someone to come to an event or place",
    sentence: "We decided to {{BLANK}} all our cousins to the summer barbecue.",
    cn: "我們決定邀請所有的表親來參加夏季烤肉聚會。" },
  { word: "join", pos: "v.", cn_def: "加入", en_def: "to become a member of a group or activity",
    sentence: "She finally worked up the courage to {{BLANK}} the school debate team.",
    cn: "她終於有勇氣加入學校的辯論隊。" },
  { word: "kick", pos: "v.", cn_def: "踢", en_def: "to hit something with your foot",
    sentence: "He used all his strength to {{BLANK}} the ball into the goal.",
    cn: "他用盡全力把球踢進球門。" },
  { word: "keep", pos: "v.", cn_def: "保持", en_def: "to continue having or doing something",
    sentence: "Please {{BLANK}} your voice down while your baby sister is napping.",
    cn: "你妹妹在睡覺時，請保持音量小聲一點。" },
  { word: "kill", pos: "v.", cn_def: "殺害", en_def: "to cause a person, animal, or plant to die",
    sentence: "A sudden frost overnight can quickly {{BLANK}} young plants in the garden.",
    cn: "一夜突來的霜凍可能很快就會殺死花園裡的幼苗。" },
  { word: "lack", pos: "n.", cn_def: "缺乏", en_def: "the state of not having enough of something",
    sentence: "The team's loss was mostly due to a {{BLANK}} of practice this season.",
    cn: "這支球隊的失敗主要是因為這個賽季缺乏練習。" },
  { word: "lay", pos: "v.", cn_def: "放置", en_def: "to put something down carefully in a particular place",
    sentence: "She gently began to {{BLANK}} the sleeping baby down in the crib.",
    cn: "她輕輕地把熟睡的寶寶放進嬰兒床裡。" },
  { word: "lead", pos: "v.", cn_def: "領導", en_def: "to guide or direct a group of people",
    sentence: "The captain agreed to {{BLANK}} the team through the final difficult match.",
    cn: "隊長同意在這場艱難的最後比賽中領導球隊。" },
  { word: "let", pos: "v.", cn_def: "讓", en_def: "to allow something to happen or someone to do something",
    sentence: "My parents finally decided to {{BLANK}} me stay up late on Friday.",
    cn: "我父母終於決定讓我星期五晚上可以晚點睡。" },
  { word: "lick", pos: "v.", cn_def: "舔", en_def: "to move your tongue across something",
    sentence: "The happy puppy began to {{BLANK}} the little boy's face affectionately.",
    cn: "這隻開心的小狗開始親切地舔小男孩的臉。" },
  { word: "lie", pos: "v.", cn_def: "說謊", en_def: "to say something that is not true",
    sentence: "He knew it was wrong to {{BLANK}} about breaking the window.",
    cn: "他知道為打破窗戶這件事說謊是不對的。" },
  { word: "lift", pos: "v.", cn_def: "舉起", en_def: "to raise something to a higher position",
    sentence: "It took two strong workers to {{BLANK}} the heavy wooden table.",
    cn: "需要兩位強壯的工人才能舉起這張沉重的木桌。" },
  { word: "limit", pos: "v.", cn_def: "限制", en_def: "to control or restrict the amount of something",
    sentence: "The doctor advised him to {{BLANK}} his screen time before bed.",
    cn: "醫生建議他在睡前限制使用螢幕的時間。" },
  { word: "lock", pos: "v.", cn_def: "鎖住", en_def: "to fasten something with a lock so it cannot open",
    sentence: "Remember to {{BLANK}} the front door before leaving for school today.",
    cn: "今天出門上學前，記得鎖上前門。" },
  { word: "make", pos: "v.", cn_def: "製做", en_def: "to create or produce something",
    sentence: "Every Sunday, my grandmother likes to {{BLANK}} fresh dumplings for the family.",
    cn: "每個星期天，我奶奶喜歡幫全家人做新鮮的水餃。" },
  { word: "marry", pos: "v.", cn_def: "結婚", en_def: "to become someone's husband or wife in a ceremony",
    sentence: "They plan to {{BLANK}} next spring in a small garden ceremony.",
    cn: "他們計畫明年春天在一個小花園裡舉行婚禮結婚。" },
  { word: "master", pos: "v.", cn_def: "精通", en_def: "to become completely skilled at something",
    sentence: "It took years of daily practice to {{BLANK}} the violin so well.",
    cn: "花了好幾年每天練習才如此精通小提琴。" },
  { word: "match", pos: "v.", cn_def: "相配", en_def: "to be similar to or go well with something else",
    sentence: "She chose a bright scarf that would {{BLANK}} her new winter coat.",
    cn: "她選了一條鮮豔的圍巾，要跟她的新冬季外套相配。" },
  { word: "mean", pos: "v.", cn_def: "表示…的意思", en_def: "to have a particular meaning",
    sentence: "A red traffic light always {{BLANK}} that drivers must come to a stop.",
    cn: "紅燈總是表示駕駛必須停下來。" },
  { word: "meet", pos: "v.", cn_def: "遇見", en_def: "to come together with someone, often for the first time",
    sentence: "We are planning to {{BLANK}} our pen pals from Japan this summer.",
    cn: "我們計畫今年夏天見到從日本來的筆友。" },
  { word: "mind", pos: "v.", cn_def: "留意", en_def: "to be bothered or annoyed by something",
    sentence: "Would you {{BLANK}} turning down the music a little bit, please?",
    cn: "你介意把音樂的音量調小一點嗎？" },
  { word: "miss", pos: "v.", cn_def: "錯過", en_def: "to fail to catch, see, or reach something",
    sentence: "If we don't leave now, we might {{BLANK}} the early morning bus.",
    cn: "如果我們現在不出發，可能會錯過早上的公車。" },
  { word: "mix", pos: "v.", cn_def: "混合", en_def: "to combine different things together",
    sentence: "Could you please {{BLANK}} the flour and sugar before adding the eggs?",
    cn: "你可以在加入蛋之前先把麵粉和糖混合嗎？" },
  { word: "move", pos: "v.", cn_def: "行動", en_def: "to change position or location",
    sentence: "The sleepy cat refused to {{BLANK}} from its warm spot by the window.",
    cn: "這隻愛睏的貓不肯離開牠在窗邊的溫暖位置。" },
  { word: "need", pos: "v.", cn_def: "需要", en_def: "to require something because it is necessary",
    sentence: "Plants {{BLANK}} sunlight and water in order to grow properly.",
    cn: "植物需要陽光和水才能正常生長。" },
  { word: "nod", pos: "v.", cn_def: "點頭", en_def: "to move your head up and down to show agreement",
    sentence: "She simply began to {{BLANK}} her head in agreement with the plan.",
    cn: "她只是點頭表示同意這個計畫。" },
  { word: "notice", pos: "v.", cn_def: "注意到", en_def: "to see or become aware of something",
    sentence: "Did you {{BLANK}} the new poster hanging outside the classroom door?",
    cn: "你注意到掛在教室門外的新海報了嗎？" },
  { word: "obey", pos: "v.", cn_def: "服從", en_def: "to do what someone tells you or follow a rule",
    sentence: "Well-trained dogs usually {{BLANK}} simple commands like sit and stay.",
    cn: "訓練良好的狗通常會服從像坐下和待命這樣的簡單指令。" },
  { word: "object", pos: "v.", cn_def: "反對", en_def: "to express disagreement or opposition to something",
    sentence: "Several parents began to {{BLANK}} to the new homework policy at school.",
    cn: "好幾位家長開始反對學校新的作業政策。" },
  { word: "omit", pos: "v.", cn_def: "省略", en_def: "to leave something out or not include it",
    sentence: "Please don't {{BLANK}} any important details from your science report.",
    cn: "請不要在你的科學報告中省略任何重要細節。" },
  { word: "own", pos: "v.", cn_def: "擁有", en_def: "to have something that belongs to you",
    sentence: "My cousin is lucky enough to {{BLANK}} a small farm in the countryside.",
    cn: "我表哥很幸運，在鄉間擁有一座小農場。" },
  { word: "pack", pos: "v.", cn_def: "打包", en_def: "to put things into a bag or container for traveling",
    sentence: "She started to {{BLANK}} her suitcase the night before the big trip.",
    cn: "她在這趟大旅行前一晚就開始打包行李箱。" },
  { word: "pause", pos: "v.", cn_def: "暫停", en_def: "to stop for a short time before continuing",
    sentence: "He decided to {{BLANK}} the movie so he could answer the phone.",
    cn: "他決定暫停電影，去接這通電話。" }
];

// ---- Part 2 data: 36 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~27-32 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// 4 options per question, answer letters balanced across A/B/C/D,
// no adjacent repeats. vocabIndex points to the exact VOCAB entry.
const MCQS = [
  { q: "Years after graduation, alumni still mention how one teacher's passion changed the course of their lives. Her amazing story continued to ______ students for many years afterward at the small school.",
    options: ["inspire", "introduce", "invent", "invite"], answer: 0, vocabIndex: 0 },
  { q: "Standing awkwardly on the porch with a plate of cookies, the friendly woman waited for her chance to speak. Let me ______ you to my new neighbor from across the street today.",
    options: ["join", "introduce", "kick", "keep"], answer: 1, vocabIndex: 1 },
  { q: "Working late in cluttered labs filled with wires and solar panels, researchers test idea after idea before any success. Scientists are always trying to ______ cleaner ways to produce electricity for homes.",
    options: ["inspire", "introduce", "invent", "lead"], answer: 2, vocabIndex: 2 },
  { q: "Setting up extra chairs and grilling enough burgers for a crowd, the family planned a lively gathering for the holiday. We decided to ______ all our cousins to the summer barbecue together.",
    options: ["lock", "limit", "lift", "invite"], answer: 3, vocabIndex: 3 },
  { q: "Watching older students argue passionately about current events every Thursday after school, she finally signed the sign-up sheet herself. She finally worked up the courage to ______ the school debate team.",
    options: ["join", "match", "mix", "meet"], answer: 0, vocabIndex: 4 },
  { q: "Sprinting toward the goal with the crowd roaring on both sides of the field, he lined up his shot carefully. He used all his strength to ______ the ball into the goal.",
    options: ["lift", "kick", "lock", "lay"], answer: 1, vocabIndex: 5 },
  { q: "Tiptoeing past the closed nursery door with the baby monitor turned low, the new parents whispered to each other constantly. Please ______ your voice down while your baby sister is napping nearby.",
    options: ["kill", "kick", "keep", "lead"], answer: 2, vocabIndex: 6 },
  { q: "Checking the weather report nervously the night before, the worried farmer covered the young seedlings with old blankets. A sudden frost overnight can quickly ______ young plants in the garden easily.",
    options: ["keep", "limit", "lock", "kill"], answer: 3, vocabIndex: 7 },
  { q: "Reviewing footage from the season's final game with disappointed faces, the coaching staff pointed to one obvious missing element. The team's loss was mostly due to a ______ of practice this season.",
    options: ["lack", "limit", "match", "mind"], answer: 0, vocabIndex: 8 },
  { q: "Tiptoeing across the dark nursery floor at midnight with the tiny bundle finally drifting off, the exhausted mother moved slowly. She gently began to ______ the sleeping baby down in the crib.",
    options: ["lift", "lay", "lock", "limit"], answer: 1, vocabIndex: 9 },
  { q: "Standing before the nervous players in the locker room before the championship game, the experienced senior felt the weight of responsibility. The captain agreed to ______ the team through the final difficult match.",
    options: ["lock", "lift", "lead", "limit"], answer: 2, vocabIndex: 10 },
  { q: "Begging quietly at the dinner table about the upcoming sleepover with friends down the street, the hopeful teenager waited anxiously. My parents finally decided to ______ me stay up late on Friday.",
    options: ["lock", "lift", "lead", "let"], answer: 3, vocabIndex: 11 },
  { q: "Bending down low after a long walk in the park, the small boy giggled as the friendly animal greeted him. The happy puppy began to ______ the little boy's face affectionately and happily.",
    options: ["lick", "lie", "lift", "limit"], answer: 0, vocabIndex: 12 },
  { q: "Standing nervously in front of his worried mother with a guilty look on his face, the boy avoided her eyes completely. He knew it was wrong to ______ about breaking the window earlier.",
    options: ["lay", "lie", "lick", "lead"], answer: 1, vocabIndex: 13 },
  { q: "Grunting together while bending their knees carefully near the delivery truck outside the new apartment building, the movers worked as a team. It took two strong workers to ______ the heavy wooden table.",
    options: ["lock", "lay", "lift", "limit"], answer: 2, vocabIndex: 14 },
  { q: "Concerned about late nights spent scrolling through videos instead of sleeping, the family doctor gave some firm advice during the checkup. The doctor advised him to ______ his screen time before bed.",
    options: ["match", "mix", "miss", "limit"], answer: 3, vocabIndex: 15 },
  { q: "Rushing out the door with backpacks and lunchboxes in hand every weekday morning, the busy family follows the same quick routine. Remember to ______ the front door before leaving for school today.",
    options: ["lock", "lift", "limit", "lay"], answer: 0, vocabIndex: 16 },
  { q: "Rolling out dough on the kitchen counter early every weekend morning, the elderly woman hums softly with flour on her hands. Every Sunday, my grandmother likes to ______ fresh dumplings for the family.",
    options: ["mix", "make", "match", "mean"], answer: 1, vocabIndex: 17 },
  { q: "Choosing flowers and a small guest list for a quiet outdoor ceremony surrounded by blooming trees, the couple felt nothing but joy. They plan to ______ next spring in a small garden ceremony.",
    options: ["meet", "master", "marry", "mind"], answer: 2, vocabIndex: 18 },
  { q: "Practicing scales every single evening for years under a patient teacher's guidance, the determined student slowly grew more confident with each note. It took years of daily practice to ______ the violin so well.",
    options: ["mix", "mean", "miss", "master"], answer: 3, vocabIndex: 19 },
  { q: "Standing in front of the mirror with several scarves draped over her shoulder, she compared colors against the new fabric carefully. She chose a bright scarf that would ______ her new winter coat.",
    options: ["match", "mind", "miss", "move"], answer: 0, vocabIndex: 20 },
  { q: "Watching cars stop obediently at every busy intersection downtown during rush hour, new drivers must memorize a few simple rules first. A red traffic light always ______ that drivers must come to a stop.",
    options: ["match", "mean", "mind", "move"], answer: 1, vocabIndex: 21 },
  { q: "Exchanging excited messages for weeks about flight schedules and sightseeing plans, two students separated by an ocean finally counted down the days. We are planning to ______ our pen pals from Japan this summer.",
    options: ["mind", "miss", "meet", "match"], answer: 2, vocabIndex: 22 },
  { q: "Sitting beside a roommate studying quietly with headphones nearby, she hesitated before speaking up about the loud volume. Would you ______ turning down the music a little bit, please tonight?",
    options: ["match", "mean", "move", "mind"], answer: 3, vocabIndex: 23 },
  { q: "Checking the clock anxiously while still searching for missing shoes near the front door, the family realized time was running short. If we don't leave now, we might ______ the early morning bus.",
    options: ["miss", "mean", "mind", "match"], answer: 0, vocabIndex: 24 },
  { q: "Standing at the counter with a large bowl and a wooden spoon in hand, she followed the recipe step by step carefully. Could you please ______ the flour and sugar before adding the eggs?",
    options: ["move", "mix", "mean", "miss"], answer: 1, vocabIndex: 25 },
  { q: "Curled up tightly in a warm patch of sunlight on the living room rug, the lazy feline barely opened one eye. The sleepy cat refused to ______ from its warm spot by the window.",
    options: ["mix", "mean", "move", "mind"], answer: 2, vocabIndex: 26 },
  { q: "Standing on the balcony each morning checking the small pots lined up along the railing, she watered every leafy stem carefully. Plants ______ sunlight and water in order to grow properly and stay healthy.",
    options: ["nod", "notice", "obey", "need"], answer: 3, vocabIndex: 27 },
  { q: "Listening carefully to the proposal during the quiet meeting without saying a single word, she simply gave a small, silent gesture. She simply began to ______ her head in agreement with the plan.",
    options: ["nod", "need", "notice", "object"], answer: 0, vocabIndex: 28 },
  { q: "Walking past the same hallway every day for a week without looking up from her phone, she finally glanced toward the bulletin board. Did you ______ the new poster hanging outside the classroom door?",
    options: ["object", "notice", "omit", "own"], answer: 1, vocabIndex: 29 },
  { q: "Sitting attentively during weekly training sessions at the park with treats ready in the trainer's pocket, the eager dogs responded quickly. Well-trained dogs usually ______ simple commands like sit and stay nicely.",
    options: ["object", "omit", "obey", "own"], answer: 2, vocabIndex: 30 },
  { q: "Filling the school auditorium for an evening meeting about extra assignments over the holiday break, several voices rose with concern. Several parents began to ______ to the new homework policy at school.",
    options: ["own", "obey", "omit", "object"], answer: 3, vocabIndex: 31 },
  { q: "Reviewing her rough draft line by line under bright desk lamp light the night before the deadline, she noticed something missing entirely. Please don't ______ any important details from your science report.",
    options: ["omit", "object", "obey", "own"], answer: 0, vocabIndex: 32 },
  { q: "Spending weekends riding through rolling green hills past rows of fruit trees inherited from his grandfather years ago, he felt proud. My cousin is lucky enough to ______ a small farm in the countryside.",
    options: ["pack", "own", "pause", "lack"], answer: 1, vocabIndex: 33 },
  { q: "Surrounded by piles of folded clothes and an open suitcase spread across her bed late one evening, she checked her list twice. She started to ______ her suitcase the night before the big trip.",
    options: ["own", "pause", "pack", "lack"], answer: 2, vocabIndex: 34 },
  { q: "Reaching quickly for the remote the moment his phone buzzed loudly from the counter during the final scene, he hesitated only briefly. He decided to ______ the movie so he could answer the phone.",
    options: ["pack", "own", "lack", "pause"], answer: 3, vocabIndex: 35 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "alumni": { pos: "n.", en_def: "former students of a school", cn_def: "畢業生（複數）" },
  "anxiously": { pos: "adv.", en_def: "in a worried or nervous way", cn_def: "焦慮地" },
  "attentively": { pos: "adv.", en_def: "in a way that pays close attention", cn_def: "專心地" },
  "auditorium": { pos: "n.", en_def: "a large room used for meetings or performances", cn_def: "禮堂" },
  "balcony": { pos: "n.", en_def: "a platform attached to the outside of a building", cn_def: "陽台" },
  "barbecue": { pos: "n.", en_def: "an outdoor meal where food is cooked over a fire", cn_def: "烤肉聚會" },
  "bulletin board": { pos: "n.", en_def: "a board for posting public notices", cn_def: "公告欄" },
  "bundle": { pos: "n.", en_def: "a small package, often referring to a wrapped baby", cn_def: "（嬰兒）包裹" },
  "checkup": { pos: "n.", en_def: "a routine medical examination", cn_def: "健康檢查" },
  "courage": { pos: "n.", en_def: "the ability to do something that frightens you", cn_def: "勇氣" },
  "deadline": { pos: "n.", en_def: "the latest time something must be finished", cn_def: "截止日期" },
  "draft": { pos: "n.", en_def: "an early, unfinished version of a piece of writing", cn_def: "草稿" },
  "dumplings": { pos: "n.", en_def: "small pieces of dough filled with meat or vegetables", cn_def: "水餃（複數）" },
  "elderly": { pos: "adj.", en_def: "old, especially referring to a person", cn_def: "年長的" },
  "feline": { pos: "n.", en_def: "a cat or animal related to cats", cn_def: "貓科動物" },
  "footage": { pos: "n.", en_def: "recorded video of an event", cn_def: "影像紀錄" },
  "frost": { pos: "n.", en_def: "a thin layer of ice that forms in cold weather", cn_def: "霜" },
  "gesture": { pos: "n.", en_def: "a movement of the body that expresses meaning", cn_def: "手勢；動作" },
  "graduation": { pos: "n.", en_def: "the act of completing a course of study", cn_def: "畢業" },
  "grunting": { pos: "v.", en_def: "making a short, low sound, often from effort", cn_def: "發出呼嚕聲（進行式）" },
  "guidance": { pos: "n.", en_def: "help or advice given by someone experienced", cn_def: "指導" },
  "headphones": { pos: "n.", en_def: "devices worn over the ears to listen privately", cn_def: "耳機" },
  "hesitated": { pos: "v.", en_def: "paused before doing or saying something", cn_def: "猶豫（過去式）" },
  "homework policy": { pos: "n.", en_def: "official rules about how much homework is assigned", cn_def: "作業政策" },
  "inherited": { pos: "v.", en_def: "received property or money from someone after they died", cn_def: "繼承（過去式）" },
  "intersection": { pos: "n.", en_def: "a place where two or more roads meet", cn_def: "十字路口" },
  "labs": { pos: "n.", en_def: "rooms used for scientific work, short for laboratories", cn_def: "實驗室（複數）" },
  "locker room": { pos: "n.", en_def: "a room with lockers used by athletes to change", cn_def: "更衣室" },
  "movers": { pos: "n.", en_def: "people whose job is to move furniture and belongings", cn_def: "搬運工人（複數）" },
  "nursery": { pos: "n.", en_def: "a room set up for a baby", cn_def: "嬰兒房" },
  "obediently": { pos: "adv.", en_def: "in a way that follows rules or instructions", cn_def: "順從地" },
  "passion": { pos: "n.", en_def: "a strong feeling of enthusiasm for something", cn_def: "熱情" },
  "pen pals": { pos: "n.", en_def: "friends you communicate with by letter or message, often abroad", cn_def: "筆友（複數）" },
  "porch": { pos: "n.", en_def: "a covered area at the entrance of a house", cn_def: "門廊" },
  "proposal": { pos: "n.", en_def: "a plan or suggestion put forward for consideration", cn_def: "提議" },
  "responsibility": { pos: "n.", en_def: "a duty to deal with or take care of something", cn_def: "責任" },
  "roommate": { pos: "n.", en_def: "a person who shares a room or home with you", cn_def: "室友" },
  "scales": { pos: "n.", en_def: "sets of musical notes played in order, used for practice", cn_def: "（音樂）音階" },
  "seedlings": { pos: "n.", en_def: "young plants grown from seeds", cn_def: "幼苗（複數）" },
  "senior": { pos: "n.", en_def: "an older or more experienced person, or a final-year student", cn_def: "畢業班學生；資深者" },
  "sightseeing": { pos: "n.", en_def: "the activity of visiting interesting places as a tourist", cn_def: "觀光" },
  "sleepover": { pos: "n.", en_def: "an occasion when someone stays overnight at a friend's house", cn_def: "過夜聚會" },
  "solar panels": { pos: "n.", en_def: "devices that convert sunlight into electricity", cn_def: "太陽能板" },
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
