// ============================================================
// Group 3 Quiz Data: Directions / Universe / Geography & Nature
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 3 - Directions / Universe / Geography & Nature (方向/宇宙/地理與大自然)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice ----
const VOCAB = [
  { word: "direction", pos: "n.", cn_def: "方向；說明", en_def: "the way something faces or moves toward",
    sentence: "I forgot which {{BLANK}} the library was in, so I had to ask a teacher for help finding my way.",
    cn: "我忘記圖書館在哪個方向，所以我必須請老師幫忙指路。" },
  { word: "east", pos: "n.", cn_def: "東方", en_def: "the direction where the sun rises",
    sentence: "The sun always rises in the {{BLANK}}, so our classroom gets very bright light every single morning.",
    cn: "太陽總是從東方升起，所以我們的教室每天早上都會有非常明亮的光線。" },
  { word: "north", pos: "n.", cn_def: "北方", en_def: "the direction to your left when facing the sunrise",
    sentence: "Snow falls almost every winter in the {{BLANK}} of Taiwan, especially on the tall mountains there.",
    cn: "台灣北方幾乎每個冬天都會下雪，尤其是在那裡的高山上。" },
  { word: "south", pos: "n.", cn_def: "南方", en_def: "the direction to your right when facing the sunrise",
    sentence: "My grandparents live in the {{BLANK}}, where the weather stays warm even during the coldest months.",
    cn: "我的祖父母住在南方，那裡即使在最冷的月份天氣也保持溫暖。" },
  { word: "south", pos: "adj.", cn_def: "南方的", en_def: "located in or facing the south",
    sentence: "We took a long train ride to visit a small {{BLANK}} village famous for its delicious seafood.",
    cn: "我們搭了很長的火車去拜訪一個以美味海鮮聞名的南方小村莊。" },
  { word: "west", pos: "n.", cn_def: "西方", en_def: "the direction where the sun sets",
    sentence: "The beautiful sunset always appears in the {{BLANK}}, painting the whole sky orange and pink.",
    cn: "美麗的夕陽總是出現在西方，把整個天空染成橘色和粉紅色。" },
  { word: "west", pos: "adj.", cn_def: "西邊的", en_def: "located in or facing the west",
    sentence: "Our school trip included a visit to a historic town located on the {{BLANK}} coast of the island.",
    cn: "我們的校外教學包括參觀一個位於島上西邊海岸的歷史古鎮。" },
  { word: "universe", pos: "n.", cn_def: "宇宙", en_def: "everything that exists, including all stars and space",
    sentence: "My science teacher explained that the {{BLANK}} contains billions of stars, planets, and galaxies.",
    cn: "我的科學老師解釋說，宇宙包含數十億顆星星、行星和星系。" },
  { word: "planet", pos: "n.", cn_def: "行星", en_def: "a large round object in space that orbits a star",
    sentence: "Mars is often called the red {{BLANK}} because its surface looks reddish from far away in space.",
    cn: "火星常被稱為紅色行星，因為它的表面從太空遠處看起來是紅色的。" },
  { word: "sun", pos: "n.", cn_def: "太陽", en_def: "the star that gives Earth light and heat",
    sentence: "We wore hats and sunglasses because the {{BLANK}} was extremely bright during our afternoon hike.",
    cn: "我們戴了帽子和太陽眼鏡，因為我們午後健行時太陽非常刺眼。" },
  { word: "moon", pos: "n.", cn_def: "月亮", en_def: "the round object that orbits the Earth and shines at night",
    sentence: "The {{BLANK}} looked huge and bright last night, so we sat outside and watched it for an hour.",
    cn: "昨晚月亮看起來又大又亮，所以我們坐在外面看了它一個小時。" },
  { word: "star", pos: "n.", cn_def: "星星", en_def: "a bright point of light seen in the night sky",
    sentence: "Far away from the city lights, every single {{BLANK}} in the night sky seemed clear and sparkling.",
    cn: "遠離城市的燈光，夜空中的每一顆星星看起來都清晰又閃亮。" },
  { word: "earth", pos: "n.", cn_def: "地球", en_def: "the planet we live on",
    sentence: "Our teacher showed us a photo of the {{BLANK}} taken from space, and it looked like a blue and white ball.",
    cn: "我們的老師給我們看了一張從太空拍攝的地球照片，它看起來像一個藍白色的球。" },
  { word: "world", pos: "n.", cn_def: "世界", en_def: "all the countries and people on Earth",
    sentence: "My older sister wants to travel around the {{BLANK}} and visit every single country before she turns thirty.",
    cn: "我姊姊想要環遊世界，在她三十歲之前拜訪每一個國家。" },
  { word: "island", pos: "n.", cn_def: "島嶼", en_def: "a piece of land surrounded completely by water",
    sentence: "Taiwan is a beautiful {{BLANK}} surrounded by ocean on every side, with mountains in the middle.",
    cn: "台灣是一個美麗的島嶼，四面環海，中間有山脈。" },
  { word: "land", pos: "n.", cn_def: "陸地", en_def: "the solid dry part of the Earth's surface",
    sentence: "After many days at sea, the sailors finally saw {{BLANK}} appear on the distant horizon.",
    cn: "在海上度過許多天之後，水手們終於看到陸地出現在遙遠的地平線上。" },
  { word: "coast", pos: "n.", cn_def: "海岸", en_def: "the land next to the sea",
    sentence: "My family enjoys driving along the {{BLANK}} on weekends because the ocean view is always so relaxing.",
    cn: "我家人喜歡週末沿著海岸開車，因為海景總是讓人很放鬆。" },
  { word: "ocean", pos: "n.", cn_def: "海洋", en_def: "a very large area of salt water",
    sentence: "The {{BLANK}} stretched out endlessly in front of us, with waves crashing gently against the sandy shore.",
    cn: "海洋在我們面前無盡地延伸，海浪輕輕拍打著沙岸。" },
  { word: "sea", pos: "n.", cn_def: "海", en_def: "a large area of salt water, smaller than an ocean",
    sentence: "We could smell the salty {{BLANK}} air long before we actually arrived at the beach that afternoon.",
    cn: "那天下午我們在真正抵達海灘之前，就已經能聞到鹹鹹的海風了。" },
  { word: "lake", pos: "n.", cn_def: "湖", en_def: "a large area of fresh water surrounded by land",
    sentence: "The water in the {{BLANK}} was so still and clear that it perfectly reflected the mountains around it.",
    cn: "湖裡的水非常平靜清澈，完美地映照出周圍的山。" },
  { word: "pond", pos: "n.", cn_def: "池塘", en_def: "a small area of still water, smaller than a lake",
    sentence: "There is a small {{BLANK}} behind our school where students like to feed the ducks after class.",
    cn: "我們學校後面有一個小池塘，學生們喜歡下課後在那裡餵鴨子。" },
  { word: "pool", pos: "n.", cn_def: "水池", en_def: "a small area of water, often man-made, for swimming",
    sentence: "My little cousin splashed happily in the shallow {{BLANK}} while the adults relaxed nearby in the shade.",
    cn: "我的小表弟在淺水池裡開心地玩水，大人們則在旁邊的陰影下休息。" },
  { word: "river", pos: "n.", cn_def: "河", en_def: "a large natural flow of fresh water",
    sentence: "The {{BLANK}} flows down from the mountains and passes right through the center of our busy little town.",
    cn: "這條河從山上流下來，正好穿過我們這個忙碌小鎮的中心。" },
  { word: "stream", pos: "n.", cn_def: "溪流", en_def: "a small narrow river",
    sentence: "We followed the narrow {{BLANK}} through the forest until it led us to a beautiful hidden waterfall.",
    cn: "我們沿著狹窄的溪流穿過森林，一直走到一個美麗的隱藏瀑布。" },
  { word: "waterfalls", pos: "n.", cn_def: "瀑布", en_def: "water falling from a high place, like off a cliff",
    sentence: "Tourists travel from all over the world just to see the famous {{BLANK}} crashing down the cliffs.",
    cn: "遊客們從世界各地前來，只為了看著名的瀑布從懸崖上傾瀉而下。" },
  { word: "desert", pos: "v.", cn_def: "遺棄", en_def: "to leave a person or place completely, abandoning it",
    sentence: "The soldiers had to {{BLANK}} their broken truck in the middle of the road and continue walking on foot.",
    cn: "士兵們必須遺棄他們在路中間故障的卡車，繼續徒步前進。" },
  { word: "desert", pos: "n.", cn_def: "沙漠", en_def: "a large area of land that is very dry with little rain",
    sentence: "It almost never rains in this {{BLANK}}, so very few plants are able to survive in the dry sand.",
    cn: "這個沙漠幾乎從不下雨，所以很少有植物能在乾燥的沙地中存活。" },
  { word: "rock", pos: "n.", cn_def: "岩石", en_def: "a hard solid piece of stone",
    sentence: "A large {{BLANK}} blocked the narrow hiking trail, so we had to climb carefully around it.",
    cn: "一塊大岩石擋住了狹窄的健行步道，所以我們必須小心地繞過它。" },
  { word: "stone", pos: "n.", cn_def: "石頭", en_def: "a small hard piece of rock",
    sentence: "The old bridge was built entirely out of gray {{BLANK}} more than a hundred years ago.",
    cn: "這座古老的橋完全是用灰色石頭建造的，已經超過一百年了。" },
  { word: "sand", pos: "n.", cn_def: "沙子", en_def: "tiny grains found on beaches and deserts",
    sentence: "The children spent the whole afternoon building a tall castle out of wet {{BLANK}} near the water.",
    cn: "孩子們整個下午都在水邊用濕沙子蓋一座高高的城堡。" },
  { word: "forest", pos: "n.", cn_def: "森林", en_def: "a large area covered with many trees",
    sentence: "Thick green trees covered the entire {{BLANK}}, making it almost impossible to see the sky above.",
    cn: "茂密的綠樹覆蓋了整片森林，讓人幾乎看不到上方的天空。" },
  { word: "valley", pos: "n.", cn_def: "山谷", en_def: "a low area of land between hills or mountains",
    sentence: "Our bus drove slowly through a quiet green {{BLANK}} surrounded by tall mountains on both sides.",
    cn: "我們的巴士緩慢地穿過一個被高山環繞的安靜綠色山谷。" },
  { word: "mountain", pos: "n.", cn_def: "山", en_def: "a very high area of land, higher than a hill",
    sentence: "Climbing to the top of the {{BLANK}} took us nearly six hours, but the view was absolutely worth it.",
    cn: "爬到山頂花了我們將近六個小時，但是那景色絕對值得。" },
  { word: "hill", pos: "n.", cn_def: "小山坡", en_def: "a small high area of land, smaller than a mountain",
    sentence: "We rolled an old tire down the grassy {{BLANK}} behind our house just for fun every weekend.",
    cn: "我們每個週末為了好玩，把一個舊輪胎從我們家後面長滿草的小山坡上滾下去。" },
  { word: "sky", pos: "n.", cn_def: "天空", en_def: "the space above the Earth where clouds and stars are seen",
    sentence: "Not a single cloud appeared in the bright blue {{BLANK}} during our entire outdoor field trip.",
    cn: "在我們整個戶外校外教學期間，明亮的藍天空中完全沒有出現一片雲。" },
  { word: "thunder", pos: "n.", cn_def: "雷", en_def: "the loud sound that follows lightning",
    sentence: "Loud {{BLANK}} shook the windows of our house right after the bright flash of lightning appeared.",
    cn: "在明亮的閃電出現之後，巨大的雷聲立刻震動了我們家的窗戶。" },
  { word: "fire", pos: "n.", cn_def: "火", en_def: "the hot bright flames produced by burning something",
    sentence: "We sat around the warm {{BLANK}} and told scary stories during our camping trip last summer.",
    cn: "去年夏天露營時，我們圍坐在溫暖的火堆旁講恐怖故事。" },
  { word: "ice", pos: "n.", cn_def: "冰", en_def: "water that has frozen solid",
    sentence: "The pond froze completely overnight, so thick {{BLANK}} now covers the entire surface of the water.",
    cn: "池塘整夜完全凍住了，所以現在厚厚的冰覆蓋了整個水面。" },
  { word: "nature", pos: "n.", cn_def: "大自然；性質", en_def: "everything in the world not made by people, like plants and animals",
    sentence: "Spending time in {{BLANK}} always makes me feel calmer, especially after a long and stressful week at school.",
    cn: "待在大自然中總是讓我感覺更平靜，尤其是在學校度過漫長又有壓力的一週之後。" },
  { word: "natural", pos: "adj.", cn_def: "自然的", en_def: "existing in nature, not made by people",
    sentence: "My grandmother prefers using {{BLANK}} ingredients like honey and lemon instead of medicine when she has a cold.",
    cn: "我奶奶感冒時比較喜歡使用天然的食材，像是蜂蜜和檸檬，而不是吃藥。" },
  { word: "shine", pos: "v.", cn_def: "發光；照耀", en_def: "to give off bright light",
    sentence: "The stars always seem to {{BLANK}} the brightest on clear nights far away from the bright city lights.",
    cn: "在遠離明亮城市燈光的晴朗夜晚，星星似乎總是發光得最明亮。" },
];

// ---- Part 2 data: 41 MCQs ----
// vocabIndex points to the exact VOCAB array entry being tested, which matters
// for words like south/west/desert that appear twice with different POS.
const MCQS = [
  { q: "I felt completely lost in the huge shopping mall and had no idea which way led back to the main entrance. I really needed someone to point me in the right ______.",
    options: ["east", "north", "world", "direction"], answer: 3, vocabIndex: 0 },
  { q: "Every single morning, bright golden light streams through my bedroom window because it faces the part of the sky where the sun first appears. My window faces ______.",
    options: ["east", "north", "south", "west"], answer: 0, vocabIndex: 1 },
  { q: "During winter break, my family always drives toward the colder, mountainous part of Taiwan where snow sometimes falls on the highest peaks. We usually travel to the ______.",
    options: ["east", "north", "south", "west"], answer: 1, vocabIndex: 2 },
  { q: "My uncle moved to the warmer part of the country last year because he was tired of the cold winters near Taipei. He now lives somewhere in the ______.",
    options: ["south", "east", "north", "west"], answer: 0, vocabIndex: 3 },
  { q: "The hotel room we booked has a beautiful balcony that faces the warmer side of the island, so we can watch the sunrise every morning. It has a lovely ______ view.",
    options: ["west", "natural", "local", "south"], answer: 3, vocabIndex: 4 },
  { q: "After a full day of hiking, we sat on a rock and watched the sun slowly sink down into the part of the sky where evening always begins. We were facing the ______.",
    options: ["east", "north", "west", "south"], answer: 2, vocabIndex: 5 },
  { q: "Our tour guide pointed out an old fishing village built along the side of the island that faces the setting sun every evening. It's known as the island's ______ coast.",
    options: ["west", "south", "natural", "local"], answer: 0, vocabIndex: 6 },
  { q: "My science textbook explained that there are billions and billions of stars and galaxies spread across everything that exists in space. Scientists call this enormous collection of everything the ______.",
    options: ["planet", "universe", "world", "earth"], answer: 1, vocabIndex: 7 },
  { q: "Astronomers recently discovered a new round object far out in space that orbits a distant sun, just like Earth orbits our own sun. They believe it could be a brand new ______.",
    options: ["planet", "star", "moon", "universe"], answer: 0, vocabIndex: 8 },
  { q: "On a clear summer afternoon, the bright object in the sky that gives us heat and light was so strong that everyone needed sunglasses. The ______ felt incredibly powerful that day.",
    options: ["moon", "star", "sun", "earth"], answer: 2, vocabIndex: 9 },
  { q: "Looking up at the night sky, we noticed that the large, glowing, round object was almost perfectly full and lit up the whole backyard. The ______ was unusually bright that night.",
    options: ["moon", "sun", "star", "planet"], answer: 0, vocabIndex: 10 },
  { q: "Far from the bright lights of the city, thousands of tiny twinkling points appeared scattered across the dark night sky above our campsite. Each one of those tiny points is called a ______.",
    options: ["moon", "star", "planet", "sun"], answer: 1, vocabIndex: 11 },
  { q: "Astronauts on the space station took an amazing photo showing our blue and green home planet floating peacefully in the darkness of space. From up there, the ______ looks incredibly small.",
    options: ["world", "universe", "planet", "earth"], answer: 3, vocabIndex: 12 },
  { q: "My older brother dreams of visiting every single country and culture that exists, from icy mountains to tropical beaches, before he turns forty. He wants to travel around the entire ______.",
    options: ["earth", "universe", "world", "planet"], answer: 2, vocabIndex: 13 },
  { q: "Taiwan is completely surrounded by ocean water on every single side, with a mountain range running right through the middle of it. Geographically speaking, Taiwan is considered an ______.",
    options: ["island", "land", "coast", "mountain"], answer: 0, vocabIndex: 14 },
  { q: "After three exhausting weeks sailing across the rough ocean, the tired sailors finally spotted solid ground appearing on the distant horizon. Everyone cheered loudly when they saw ______ ahead.",
    options: ["island", "coast", "land", "sea"], answer: 2, vocabIndex: 15 },
  { q: "My family loves taking a scenic drive along the road that runs right beside the ocean, stopping to admire the waves and cliffs. The view along the ______ is always breathtaking.",
    options: ["island", "river", "lake", "coast"], answer: 3, vocabIndex: 16 },
  { q: "Standing on the beach, we could see nothing but endless deep blue water stretching all the way to the horizon in every direction. The enormous body of salt water is called the ______.",
    options: ["lake", "river", "ocean", "pond"], answer: 2, vocabIndex: 17 },
  { q: "A gentle salty breeze blew across the boat deck as we sailed across the calm blue water between the two small islands. The smell of the ______ air was relaxing.",
    options: ["ocean", "sea", "lake", "pool"], answer: 1, vocabIndex: 18 },
  { q: "The water in front of our campsite was completely still and surrounded by tall trees, perfectly reflecting the mountains like a giant mirror. We decided to go fishing in the quiet ______.",
    options: ["river", "pond", "ocean", "lake"], answer: 3, vocabIndex: 19 },
  { q: "Behind our elementary school, there is a small area of still water where frogs sing loudly every evening and ducks swim peacefully during the day. Students often visit the little ______ during recess.",
    options: ["lake", "pond", "pool", "river"], answer: 1, vocabIndex: 20 },
  { q: "On hot summer afternoons, my younger cousins love jumping into the small, shallow area of water in our backyard to cool off and splash around. We built that little ______ ourselves last year.",
    options: ["pond", "lake", "ocean", "pool"], answer: 3, vocabIndex: 21 },
  { q: "A long, flowing body of fresh water winds its way down from the mountains and cuts straight through the middle of our busy city. Boats often travel along this important ______.",
    options: ["stream", "lake", "river", "sea"], answer: 2, vocabIndex: 22 },
  { q: "While hiking through the forest, we followed a thin, gently flowing line of clear water, smaller and narrower than a real river. The little ______ eventually led us to a hidden pool.",
    options: ["river", "waterfalls", "pond", "stream"], answer: 3, vocabIndex: 23 },
  { q: "Thousands of tourists travel every year just to witness water crashing dramatically down a tall cliff into the rocks below. The roar of the famous ______ could be heard from far away.",
    options: ["stream", "waterfalls", "river", "mountain"], answer: 1, vocabIndex: 24 },
  { q: "During the dangerous storm, the captain ordered the crew to leave the sinking ship behind completely and escape immediately in the small lifeboats. Nobody wanted to ______ their captain, but they had no other choice.",
    options: ["grow", "travel", "shine", "desert"], answer: 3, vocabIndex: 25 },
  { q: "For days, our jeep drove across an endless stretch of dry sand with almost no plants, water, or shade anywhere in sight. Surviving in this harsh ______ requires careful planning and plenty of water.",
    options: ["forest", "desert", "valley", "mountain"], answer: 1, vocabIndex: 26 },
  { q: "While climbing the steep trail, my foot suddenly slipped on a large gray object jutting out from the dirt path, and I almost fell over completely. That heavy ______ nearly caused a serious accident.",
    options: ["stone", "sand", "rock", "hill"], answer: 2, vocabIndex: 27 },
  { q: "The ancient castle walls were built centuries ago using thousands of carefully cut gray blocks stacked tightly on top of each other. Each heavy ______ had to be carried up the hill by hand.",
    options: ["stone", "rock", "sand", "ice"], answer: 0, vocabIndex: 28 },
  { q: "Walking barefoot along the beach, we could feel the warm, soft, tiny grains beneath our feet shifting gently with every single step we took. The golden ______ stretched for miles along the coast.",
    options: ["stone", "sand", "rock", "ice"], answer: 1, vocabIndex: 29 },
  { q: "Thick, tall trees grew so closely together in this part of the wilderness that almost no sunlight could reach the ground below. Hikers often get lost inside this dense, shadowy ______.",
    options: ["forest", "valley", "mountain", "desert"], answer: 0, vocabIndex: 30 },
  { q: "Our train passed slowly through a peaceful, low area of flat farmland that was completely surrounded by towering green mountains on both sides. Farmers have grown rice in this fertile ______ for generations.",
    options: ["forest", "valley", "mountain", "hill"], answer: 1, vocabIndex: 31 },
  { q: "It took our group almost eight hours of difficult climbing to finally reach the very top of the tallest peak in the entire national park. Standing on top of that enormous ______ felt incredibly rewarding.",
    options: ["hill", "valley", "mountain", "forest"], answer: 2, vocabIndex: 32 },
  { q: "Every weekend, neighborhood children gather to roll old tires down the small, grassy, gently sloping bump of land behind the community park. That little ______ has been a favorite playground for years.",
    options: ["mountain", "valley", "rock", "hill"], answer: 3, vocabIndex: 33 },
  { q: "Lying on our backs in the open field, we stared upward at the enormous blue space above us, completely empty except for a few drifting white clouds. The clear ______ made the afternoon feel peaceful.",
    options: ["world", "universe", "sky", "earth"], answer: 2, vocabIndex: 34 },
  { q: "Right after a sudden bright flash lit up the entire dark sky, an incredibly loud rumbling sound shook all the windows in our house. That frightening sound is called ______.",
    options: ["thunder", "fire", "ice", "sky"], answer: 0, vocabIndex: 35 },
  { q: "During our camping trip, we gathered dry wood and carefully built a small, warm, glowing flame to cook dinner and keep ourselves warm after dark. Everyone gathered closely around the crackling ______.",
    options: ["thunder", "ice", "fire", "sand"], answer: 2, vocabIndex: 36 },
  { q: "After leaving the bottles of water outside all night during the freezing winter storm, we found them completely frozen solid the next morning. A thick layer of ______ covered everything outside.",
    options: ["fire", "ice", "sand", "stone"], answer: 1, vocabIndex: 37 },
  { q: "After studying hard for exams all week, my favorite way to relax is hiking through forests and breathing fresh air away from the noisy city streets. Spending time in ______ always helps me feel calmer.",
    options: ["nature", "world", "universe", "sky"], answer: 0, vocabIndex: 38 },
  { q: "My grandmother always insists on using ingredients straight from plants and the earth, like honey and ginger, instead of taking medicine when she feels sick. She strongly believes in ______ remedies.",
    options: ["south", "west", "local", "natural"], answer: 3, vocabIndex: 39 },
  { q: "On clear nights far away from city lights, the stars always seem to glow with their brightest, most sparkling light, especially high up in the mountains. They really seem to ______ beautifully up there.",
    options: ["shine", "grow", "travel", "desert"], answer: 0, vocabIndex: 40 },
];

// ---- Word lookup definitions (for the lookup popup) ----
// Some words (south, west, desert) appear twice with different parts of speech.
// Merge those into one combined entry so lookup shows both senses instead
// of silently losing one to an object-key overwrite.
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});
// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "absolutely": { pos: "adv.", en_def: "completely; totally", cn_def: "絕對地；完全地" },
  "adults": { pos: "n.", en_def: "grown-up people", cn_def: "成人（複數）" },
  "afternoon": { pos: "n.", en_def: "the part of the day between noon and evening", cn_def: "下午" },
  "air": { pos: "n.", en_def: "the mixture of gases we breathe", cn_def: "空氣" },
  "appear": { pos: "v.", en_def: "to come into sight", cn_def: "出現" },
  "appeared": { pos: "v.", en_def: "came into sight (past tense of appear)", cn_def: "出現（appear的過去式）" },
  "appears": { pos: "v.", en_def: "comes into sight", cn_def: "出現" },
  "arrived": { pos: "v.", en_def: "got to a place (past tense of arrive)", cn_def: "抵達（arrive的過去式）" },
  "ask": { pos: "v.", en_def: "to put a question to someone", cn_def: "問" },
  "ball": { pos: "n.", en_def: "a round object used in games", cn_def: "球" },
  "beach": { pos: "n.", en_def: "an area of sand next to the sea", cn_def: "海灘" },
  "beautiful": { pos: "adj.", en_def: "very pretty or pleasing to look at", cn_def: "美麗的" },
  "behind": { pos: "prep.", en_def: "at the back of something", cn_def: "在...後面" },
  "billions": { pos: "n.", en_def: "very large numbers, a thousand million each", cn_def: "數十億" },
  "blocked": { pos: "v.", en_def: "stopped something from passing through", cn_def: "阻塞；擋住" },
  "blue": { pos: "adj.", en_def: "having the color of the sky on a clear day", cn_def: "藍色的" },
  "bridge": { pos: "n.", en_def: "a structure built over a river or road to cross it", cn_def: "橋" },
  "bright": { pos: "adj.", en_def: "giving out a lot of light", cn_def: "明亮的" },
  "brightest": { pos: "adj.", en_def: "giving out the most light", cn_def: "最明亮的" },
  "broken": { pos: "adj.", en_def: "damaged and no longer working", cn_def: "壞掉的" },
  "building": { pos: "v.", en_def: "making something by putting parts together", cn_def: "建造（進行式）" },
  "built": { pos: "v.", en_def: "made something (past tense of build)", cn_def: "建造（build的過去式）" },
  "bus": { pos: "n.", en_def: "a large vehicle that carries many passengers", cn_def: "公車" },
  "busy": { pos: "adj.", en_def: "having a lot to do; full of activity", cn_def: "忙碌的" },
  "called": { pos: "v.", en_def: "given a name; named", cn_def: "被稱為" },
  "calmer": { pos: "adj.", en_def: "more calm and peaceful", cn_def: "更平靜的" },
  "camping": { pos: "n.", en_def: "staying outdoors in a tent", cn_def: "露營" },
  "carefully": { pos: "adv.", en_def: "in a careful way, paying close attention", cn_def: "小心地" },
  "castle": { pos: "n.", en_def: "a large old building with thick walls, often for a king", cn_def: "城堡" },
  "center": { pos: "n.", en_def: "the middle part of something", cn_def: "中心" },
  "children": { pos: "n.", en_def: "young people; the plural of child", cn_def: "孩子們" },
  "city": { pos: "n.", en_def: "a large town", cn_def: "城市" },
  "class": { pos: "n.", en_def: "a group of students who study together", cn_def: "班級；課" },
  "classroom": { pos: "n.", en_def: "a room where students have lessons", cn_def: "教室" },
  "clear": { pos: "adj.", en_def: "easy to see through; with no clouds", cn_def: "晴朗的；清澈的" },
  "cliffs": { pos: "n.", en_def: "tall, steep rock faces, often by the sea", cn_def: "懸崖（複數）" },
  "climb": { pos: "v.", en_def: "to go up something using your hands and feet", cn_def: "攀爬" },
  "climbing": { pos: "v.", en_def: "going up something (the -ing form of climb)", cn_def: "攀爬（進行式）" },
  "cloud": { pos: "n.", en_def: "a white or gray shape floating in the sky", cn_def: "雲" },
  "cold": { pos: "adj.", en_def: "having a low temperature", cn_def: "冷的" },
  "coldest": { pos: "adj.", en_def: "having the lowest temperature", cn_def: "最冷的" },
  "completely": { pos: "adv.", en_def: "fully; entirely", cn_def: "完全地" },
  "contains": { pos: "v.", en_def: "has something inside", cn_def: "包含" },
  "continue": { pos: "v.", en_def: "to keep doing something without stopping", cn_def: "繼續" },
  "country": { pos: "n.", en_def: "a nation with its own government", cn_def: "國家" },
  "cousin": { pos: "n.", en_def: "the child of your aunt or uncle", cn_def: "表（堂）兄弟姊妹" },
  "covered": { pos: "v.", en_def: "put something over the top of another thing", cn_def: "覆蓋" },
  "covers": { pos: "v.", en_def: "puts something over the top of another thing", cn_def: "覆蓋" },
  "crashing": { pos: "v.", en_def: "hitting something violently with a loud noise", cn_def: "猛烈撞擊（進行式）" },
  "days": { pos: "n.", en_def: "more than one day", cn_def: "天（複數）" },
  "delicious": { pos: "adj.", en_def: "having a very good taste", cn_def: "美味的" },
  "distant": { pos: "adj.", en_def: "far away in space or time", cn_def: "遙遠的" },
  "down": { pos: "adv.", en_def: "toward a lower place", cn_def: "向下" },
  "driving": { pos: "v.", en_def: "controlling a car (the -ing form of drive)", cn_def: "駕駛（進行式）" },
  "drove": { pos: "v.", en_def: "controlled a vehicle (past tense of drive)", cn_def: "駕駛（drive的過去式）" },
  "dry": { pos: "adj.", en_def: "having no water or moisture", cn_def: "乾燥的" },
  "ducks": { pos: "n.", en_def: "water birds with webbed feet", cn_def: "鴨子（複數）" },
  "endlessly": { pos: "adv.", en_def: "without ending; continuously", cn_def: "無止盡地" },
  "enjoys": { pos: "v.", en_def: "gets pleasure from something", cn_def: "享受；喜歡" },
  "entire": { pos: "adj.", en_def: "whole; complete", cn_def: "整個的" },
  "entirely": { pos: "adv.", en_def: "completely; fully", cn_def: "完全地" },
  "especially": { pos: "adv.", en_def: "more than usual; particularly", cn_def: "尤其；特別" },
  "explained": { pos: "v.", en_def: "made something clear or easy to understand", cn_def: "解釋" },
  "extremely": { pos: "adv.", en_def: "to a very high degree", cn_def: "極度地" },
  "falls": { pos: "v.", en_def: "drops down (the present tense of fall)", cn_def: "落下" },
  "family": { pos: "n.", en_def: "a group of parents and children", cn_def: "家庭" },
  "famous": { pos: "adj.", en_def: "known by many people", cn_def: "著名的" },
  "feed": { pos: "v.", en_def: "to give food to a person or animal", cn_def: "餵食" },
  "feel": { pos: "v.", en_def: "to experience a feeling or sensation", cn_def: "感覺" },
  "field": { pos: "n.", en_def: "a large open area of land, often used for farming or sports", cn_def: "田野；場地" },
  "finally": { pos: "adv.", en_def: "after a long time; at last", cn_def: "終於" },
  "finding": { pos: "v.", en_def: "discovering something (the -ing form of find)", cn_def: "找到（進行式）" },
  "flash": { pos: "n.", en_def: "a sudden bright light", cn_def: "閃光" },
  "flows": { pos: "v.", en_def: "moves steadily like water", cn_def: "流動" },
  "followed": { pos: "v.", en_def: "went after or behind something", cn_def: "跟隨（過去式）" },
  "foot": { pos: "n.", en_def: "the part of the body at the end of the leg", cn_def: "腳" },
  "forgot": { pos: "v.", en_def: "did not remember (past tense of forget)", cn_def: "忘記（forget的過去式）" },
  "froze": { pos: "v.", en_def: "became solid ice (past tense of freeze)", cn_def: "結冰（freeze的過去式）" },
  "fun": { pos: "n.", en_def: "enjoyment; a good time", cn_def: "樂趣" },
  "galaxies": { pos: "n.", en_def: "huge groups of stars in space", cn_def: "星系（複數）" },
  "gently": { pos: "adv.", en_def: "in a soft, careful way", cn_def: "輕柔地" },
  "gets": { pos: "v.", en_def: "receives or becomes", cn_def: "得到；變得" },
  "grandmother": { pos: "n.", en_def: "the mother of your mother or father", cn_def: "祖母；奶奶" },
  "grandparents": { pos: "n.", en_def: "the parents of your mother or father", cn_def: "祖父母" },
  "grassy": { pos: "adj.", en_def: "covered with grass", cn_def: "長滿草的" },
  "gray": { pos: "adj.", en_def: "having the color between black and white", cn_def: "灰色的" },
  "green": { pos: "adj.", en_def: "having the color of grass or leaves", cn_def: "綠色的" },
  "happily": { pos: "adv.", en_def: "in a happy way", cn_def: "快樂地" },
  "hats": { pos: "n.", en_def: "coverings worn on the head", cn_def: "帽子（複數）" },
  "help": { pos: "v.", en_def: "to make something easier for someone", cn_def: "幫助" },
  "hidden": { pos: "adj.", en_def: "kept out of sight; not easy to find", cn_def: "隱藏的" },
  "hike": { pos: "n.", en_def: "a long walk, especially in nature", cn_def: "健行" },
  "hiking": { pos: "n.", en_def: "the activity of taking long walks in nature", cn_def: "健行（活動）" },
  "historic": { pos: "adj.", en_def: "important in history; old and famous", cn_def: "有歷史意義的" },
  "honey": { pos: "n.", en_def: "a sweet sticky food made by bees", cn_def: "蜂蜜" },
  "horizon": { pos: "n.", en_def: "the line where the sky meets the land or sea", cn_def: "地平線" },
  "hour": { pos: "n.", en_def: "a unit of time equal to 60 minutes", cn_def: "小時" },
  "hours": { pos: "n.", en_def: "more than one hour", cn_def: "小時（複數）" },
  "house": { pos: "n.", en_def: "a building where people live", cn_def: "房子" },
  "huge": { pos: "adj.", en_def: "extremely large in size", cn_def: "巨大的" },
  "hundred": { pos: "n.", en_def: "the number 100", cn_def: "一百" },
  "impossible": { pos: "adj.", en_def: "not able to happen or be done", cn_def: "不可能的" },
  "included": { pos: "v.", en_def: "had something as part of it", cn_def: "包含（過去式）" },
  "ingredients": { pos: "n.", en_def: "the foods or items used to make something", cn_def: "食材；原料" },
  "instead": { pos: "adv.", en_def: "in place of something else", cn_def: "取而代之" },
  "large": { pos: "adj.", en_def: "big in size or amount", cn_def: "大的" },
  "last": { pos: "adj.", en_def: "coming after all others; final", cn_def: "最後的；上一個" },
  "led": { pos: "v.", en_def: "guided someone to a place (past tense of lead)", cn_def: "帶領（lead的過去式）" },
  "lemon": { pos: "n.", en_def: "a sour yellow fruit", cn_def: "檸檬" },
  "library": { pos: "n.", en_def: "a building with books people can read or borrow", cn_def: "圖書館" },
  "light": { pos: "n.", en_def: "brightness that lets you see things", cn_def: "光" },
  "lightning": { pos: "n.", en_def: "a sudden bright flash of light in a storm", cn_def: "閃電" },
  "lights": { pos: "n.", en_def: "things that produce brightness", cn_def: "燈光（複數）" },
  "little": { pos: "adj.", en_def: "small in size", cn_def: "小的" },
  "live": { pos: "v.", en_def: "to have your home in a place", cn_def: "居住" },
  "located": { pos: "v.", en_def: "placed or found in a particular position", cn_def: "位於" },
  "long": { pos: "adj.", en_def: "having a great length or duration", cn_def: "長的" },
  "looked": { pos: "v.", en_def: "appeared a certain way; used your eyes", cn_def: "看起來；看（過去式）" },
  "looks": { pos: "v.", en_def: "appears a certain way", cn_def: "看起來" },
  "loud": { pos: "adj.", en_def: "making a lot of noise", cn_def: "大聲的" },
  "makes": { pos: "v.", en_def: "creates or causes", cn_def: "製作；使得" },
  "making": { pos: "v.", en_def: "creating something (the -ing form of make)", cn_def: "製作（進行式）" },
  "mars": { pos: "n.", en_def: "the fourth planet from the sun, known as the red planet", cn_def: "火星" },
  "medicine": { pos: "n.", en_def: "something taken to treat an illness", cn_def: "藥" },
  "middle": { pos: "n.", en_def: "the center part of something", cn_def: "中間" },
  "months": { pos: "n.", en_def: "periods of about 30 days; the plural of month", cn_def: "月份（複數）" },
  "morning": { pos: "n.", en_def: "the early part of the day", cn_def: "早上" },
  "mountains": { pos: "n.", en_def: "more than one mountain", cn_def: "山（複數）" },
  "narrow": { pos: "adj.", en_def: "not wide; having a small distance between sides", cn_def: "狹窄的" },
  "nearby": { pos: "adv.", en_def: "close to a place", cn_def: "在附近" },
  "nearly": { pos: "adv.", en_def: "almost", cn_def: "幾乎" },
  "night": { pos: "n.", en_def: "the dark part of the day", cn_def: "夜晚" },
  "nights": { pos: "n.", en_def: "more than one night", cn_def: "夜晚（複數）" },
  "old": { pos: "adj.", en_def: "having lived or existed for a long time", cn_def: "老的；舊的" },
  "older": { pos: "adj.", en_def: "more old; having lived longer", cn_def: "較年長的" },
  "orange": { pos: "adj.", en_def: "having a color between red and yellow", cn_def: "橘色的" },
  "outdoor": { pos: "adj.", en_def: "happening outside, not inside a building", cn_def: "戶外的" },
  "outside": { pos: "adv.", en_def: "not inside; in the open air", cn_def: "在外面" },
  "overnight": { pos: "adv.", en_def: "during the night", cn_def: "一整夜" },
  "painting": { pos: "v.", en_def: "making a picture or coating with paint", cn_def: "畫；上色（進行式）" },
  "passes": { pos: "v.", en_def: "moves past or through something", cn_def: "經過" },
  "perfectly": { pos: "adv.", en_def: "in a perfect way, without any flaws", cn_def: "完美地" },
  "photo": { pos: "n.", en_def: "a picture taken with a camera", cn_def: "照片" },
  "pink": { pos: "adj.", en_def: "having a pale red color", cn_def: "粉紅色的" },
  "planets": { pos: "n.", en_def: "more than one planet", cn_def: "行星（複數）" },
  "plants": { pos: "n.", en_def: "living things that grow in soil, like trees and flowers", cn_def: "植物（複數）" },
  "prefers": { pos: "v.", en_def: "likes one thing more than another", cn_def: "比較喜歡" },
  "quiet": { pos: "adj.", en_def: "making very little noise", cn_def: "安靜的" },
  "rains": { pos: "v.", en_def: "water falls from the sky", cn_def: "下雨" },
  "red": { pos: "adj.", en_def: "having the color of blood", cn_def: "紅色的" },
  "reddish": { pos: "adj.", en_def: "somewhat red in color", cn_def: "微紅的" },
  "reflected": { pos: "v.", en_def: "showed an image of something, like a mirror does", cn_def: "反射" },
  "relaxed": { pos: "v.", en_def: "became calm and free of stress", cn_def: "放鬆（過去式）" },
  "relaxing": { pos: "adj.", en_def: "making you feel calm; reducing stress", cn_def: "令人放鬆的" },
  "ride": { pos: "n.", en_def: "a trip in a vehicle", cn_def: "搭乘；乘坐" },
  "rises": { pos: "v.", en_def: "moves upward", cn_def: "上升" },
  "road": { pos: "n.", en_def: "a path made for vehicles to travel on", cn_def: "道路" },
  "rolled": { pos: "v.", en_def: "moved by turning over and over", cn_def: "滾動（過去式）" },
  "sailors": { pos: "n.", en_def: "people who work on a ship", cn_def: "水手（複數）" },
  "salty": { pos: "adj.", en_def: "tasting of or containing salt", cn_def: "鹹的" },
  "sandy": { pos: "adj.", en_def: "covered with sand", cn_def: "多沙的" },
  "sat": { pos: "v.", en_def: "rested on a seat (past tense of sit)", cn_def: "坐（sit的過去式）" },
  "saw": { pos: "v.", en_def: "noticed with the eyes (past tense of see)", cn_def: "看見（see的過去式）" },
  "scary": { pos: "adj.", en_def: "causing fear", cn_def: "可怕的" },
  "school": { pos: "n.", en_def: "a place where students go to learn", cn_def: "學校" },
  "science": { pos: "n.", en_def: "the study of the natural world", cn_def: "科學" },
  "seafood": { pos: "n.", en_def: "fish and other food from the sea", cn_def: "海鮮" },
  "see": { pos: "v.", en_def: "to notice something with your eyes", cn_def: "看見" },
  "seem": { pos: "v.", en_def: "to appear to be a certain way", cn_def: "似乎" },
  "seemed": { pos: "v.", en_def: "appeared to be a certain way (past tense)", cn_def: "似乎（過去式）" },
  "shade": { pos: "n.", en_def: "an area out of direct sunlight", cn_def: "陰影" },
  "shallow": { pos: "adj.", en_def: "not deep", cn_def: "淺的" },
  "shook": { pos: "v.", en_def: "moved back and forth quickly (past tense of shake)", cn_def: "搖動（shake的過去式）" },
  "shore": { pos: "n.", en_def: "the land along the edge of water", cn_def: "岸邊" },
  "showed": { pos: "v.", en_def: "let someone see something (past tense of show)", cn_def: "展示（show的過去式）" },
  "side": { pos: "n.", en_def: "one part of an object, away from the center", cn_def: "側邊；一邊" },
  "sides": { pos: "n.", en_def: "more than one side", cn_def: "側邊（複數）" },
  "single": { pos: "adj.", en_def: "only one", cn_def: "單一的" },
  "sister": { pos: "n.", en_def: "a girl or woman with the same parents as you", cn_def: "姊妹" },
  "six": { pos: "n.", en_def: "the number 6", cn_def: "六" },
  "slowly": { pos: "adv.", en_def: "not quickly; taking a long time", cn_def: "慢慢地" },
  "small": { pos: "adj.", en_def: "not large in size", cn_def: "小的" },
  "smell": { pos: "v.", en_def: "to notice an odor with the nose", cn_def: "聞" },
  "snow": { pos: "n.", en_def: "soft white frozen water that falls in winter", cn_def: "雪" },
  "soldiers": { pos: "n.", en_def: "people who serve in an army", cn_def: "士兵（複數）" },
  "space": { pos: "n.", en_def: "the area beyond Earth's atmosphere, where stars and planets are", cn_def: "太空" },
  "sparkling": { pos: "adj.", en_def: "shining with small flashes of light", cn_def: "閃爍的" },
  "spending": { pos: "v.", en_def: "using time or money on something (the -ing form of spend)", cn_def: "度過（進行式）" },
  "spent": { pos: "v.", en_def: "used time or money (past tense of spend)", cn_def: "度過（spend的過去式）" },
  "splashed": { pos: "v.", en_def: "made liquid scatter by hitting or moving in it", cn_def: "潑水（過去式）" },
  "stars": { pos: "n.", en_def: "more than one star", cn_def: "星星（複數）" },
  "stays": { pos: "v.", en_def: "remains in a place or condition", cn_def: "保持；停留" },
  "stories": { pos: "n.", en_def: "accounts of events, often imaginative", cn_def: "故事（複數）" },
  "stressful": { pos: "adj.", en_def: "causing worry or pressure", cn_def: "壓力大的" },
  "stretched": { pos: "v.", en_def: "extended over a distance", cn_def: "延伸（過去式）" },
  "students": { pos: "n.", en_def: "people who study at a school", cn_def: "學生（複數）" },
  "summer": { pos: "n.", en_def: "the warmest season of the year", cn_def: "夏天" },
  "sunglasses": { pos: "n.", en_def: "dark glasses worn to protect eyes from sunlight", cn_def: "太陽眼鏡" },
  "sunset": { pos: "n.", en_def: "the time when the sun goes down", cn_def: "日落" },
  "surface": { pos: "n.", en_def: "the outside or top layer of something", cn_def: "表面" },
  "surrounded": { pos: "v.", en_def: "was all around something", cn_def: "包圍" },
  "survive": { pos: "v.", en_def: "to continue to live, especially after a hard situation", cn_def: "存活" },
  "taiwan": { pos: "n.", en_def: "an island country in East Asia", cn_def: "台灣" },
  "taken": { pos: "v.", en_def: "captured or gotten (past participle of take)", cn_def: "拿取（take的過去分詞）" },
  "tall": { pos: "adj.", en_def: "having a great height", cn_def: "高的" },
  "teacher": { pos: "n.", en_def: "a person whose job is to teach", cn_def: "老師" },
  "thick": { pos: "adj.", en_def: "having a large distance between two sides", cn_def: "厚的；濃的" },
  "thirty": { pos: "n.", en_def: "the number 30", cn_def: "三十" },
  "time": { pos: "n.", en_def: "the thing measured by clocks and calendars", cn_def: "時間" },
  "tire": { pos: "n.", en_def: "the rubber ring around a wheel", cn_def: "輪胎" },
  "told": { pos: "v.", en_def: "said something to someone (past tense of tell)", cn_def: "告訴（tell的過去式）" },
  "took": { pos: "v.", en_def: "got hold of something (past tense of take)", cn_def: "拿（take的過去式）" },
  "top": { pos: "n.", en_def: "the highest part of something", cn_def: "頂部" },
  "tourists": { pos: "n.", en_def: "people who travel for pleasure", cn_def: "遊客（複數）" },
  "town": { pos: "n.", en_def: "a small city", cn_def: "城鎮" },
  "trail": { pos: "n.", en_def: "a path through nature", cn_def: "步道" },
  "train": { pos: "n.", en_def: "a vehicle that runs on tracks", cn_def: "火車" },
  "travel": { pos: "v.", en_def: "to go from one place to another", cn_def: "旅行" },
  "trees": { pos: "n.", en_def: "tall plants with a trunk and branches", cn_def: "樹（複數）" },
  "trip": { pos: "n.", en_def: "a journey to a place", cn_def: "旅行；行程" },
  "truck": { pos: "n.", en_def: "a large vehicle used to carry goods", cn_def: "卡車" },
  "turns": { pos: "v.", en_def: "becomes a certain age, or changes direction", cn_def: "變成（年齡）；轉向" },
  "using": { pos: "v.", en_def: "doing something with a tool or material (the -ing form of use)", cn_def: "使用（進行式）" },
  "view": { pos: "n.", en_def: "what you can see from a place", cn_def: "景色" },
  "village": { pos: "n.", en_def: "a small group of houses in the countryside", cn_def: "村莊" },
  "visit": { pos: "v.", en_def: "to go see a person or place", cn_def: "拜訪" },
  "walking": { pos: "v.", en_def: "moving on foot (the -ing form of walk)", cn_def: "走路（進行式）" },
  "wants": { pos: "v.", en_def: "desires something", cn_def: "想要" },
  "warm": { pos: "adj.", en_def: "having a comfortably high temperature", cn_def: "溫暖的" },
  "watched": { pos: "v.", en_def: "looked at something for a period of time", cn_def: "觀看（過去式）" },
  "water": { pos: "n.", en_def: "the clear liquid in rivers, lakes, and rain", cn_def: "水" },
  "waterfall": { pos: "n.", en_def: "water falling from a high place", cn_def: "瀑布" },
  "waves": { pos: "n.", en_def: "moving ridges of water on the sea's surface", cn_def: "波浪（複數）" },
  "way": { pos: "n.", en_def: "a path or route to somewhere", cn_def: "路；方式" },
  "weather": { pos: "n.", en_def: "the condition of the sky and temperature outside", cn_def: "天氣" },
  "week": { pos: "n.", en_def: "a period of seven days", cn_def: "星期；週" },
  "weekend": { pos: "n.", en_def: "Saturday and Sunday", cn_def: "週末" },
  "weekends": { pos: "n.", en_def: "more than one weekend", cn_def: "週末（複數）" },
  "wet": { pos: "adj.", en_def: "covered or soaked with water", cn_def: "濕的" },
  "white": { pos: "adj.", en_def: "having the color of snow or milk", cn_def: "白色的" },
  "whole": { pos: "adj.", en_def: "complete; all of something", cn_def: "整個的" },
  "windows": { pos: "n.", en_def: "openings in a wall covered with glass", cn_def: "窗戶（複數）" },
  "winter": { pos: "n.", en_def: "the coldest season of the year", cn_def: "冬天" },
  "wore": { pos: "v.", en_def: "had clothes on the body (past tense of wear)", cn_def: "穿著（wear的過去式）" },
  "worth": { pos: "adj.", en_def: "deserving of; having a value equal to", cn_def: "值得的" },
  "years": { pos: "n.", en_def: "periods of 12 months; the plural of year", cn_def: "年（複數）" },
};