// ============================================================
// Group 7 Quiz Data: Fruits / Vegetables / Drinks / Condiments
// Full word set (45 words) — completes the "food and drinks"
// theme started in Group 6 (meals & common foods).
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 7 - Fruits / Vegetables / Drinks / Condiments (水果/蔬菜/飲料/調味料)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (45 words) ----
const VOCAB = [
  { word: "fruit", pos: "n.", cn_def: "水果", en_def: "the sweet part of a plant that you can eat, like an apple or banana",
    sentence: "My mother always keeps a bowl of fresh {{BLANK}} on the kitchen table.",
    cn: "我媽媽總是在廚房餐桌上放一碗新鮮水果。" },
  { word: "apple", pos: "n.", cn_def: "蘋果", en_def: "a round fruit with red, yellow, or green skin",
    sentence: "Every day, my father packs a shiny red {{BLANK}} in my lunch box.",
    cn: "每天我爸爸都會在我的便當盒裡放一顆閃亮的紅蘋果。" },
  { word: "banana", pos: "n.", cn_def: "香蕉", en_def: "a long yellow fruit with soft sweet flesh",
    sentence: "Before her morning run, my sister always eats a {{BLANK}} for quick energy.",
    cn: "我姐姐在晨跑前總會吃一根香蕉來補充快速能量。" },
  { word: "grape", pos: "n.", cn_def: "葡萄", en_def: "a small round fruit that grows in bunches, used to make wine and juice",
    sentence: "At the night market, a vendor sold sweet purple {{BLANK}} by the bag.",
    cn: "在夜市裡，一位攤販以一袋一袋的方式賣著甜美的紫葡萄。" },
  { word: "guava", pos: "n.", cn_def: "芭樂", en_def: "a round green tropical fruit with crunchy white flesh",
    sentence: "My grandfather grows several {{BLANK}} trees in the small garden behind his house.",
    cn: "我爺爺在他家後面的小花園裡種了好幾棵芭樂樹。" },
  { word: "lemon", pos: "n.", cn_def: "檸檬", en_def: "a sour yellow fruit often used to flavor drinks and food",
    sentence: "On a hot afternoon, nothing tastes better than a cold glass of {{BLANK}} tea.",
    cn: "在炎熱的午後，沒有什麼比一杯冰涼的檸檬茶更好喝了。" },
  { word: "mango", pos: "n.", cn_def: "芒果", en_def: "a sweet orange tropical fruit with a large seed inside",
    sentence: "During the summer, my aunt makes a refreshing shaved ice topped with ripe {{BLANK}}.",
    cn: "在夏天，我阿姨會做一份清爽的剉冰，上面鋪滿成熟的芒果。" },
  { word: "orange", pos: "n.", cn_def: "柳橙", en_def: "a round citrus fruit with orange skin and juicy segments",
    sentence: "My mother squeezes a fresh {{BLANK}} every morning to make us juice.",
    cn: "我媽媽每天早上都會榨一顆新鮮柳橙幫我們做果汁。" },
  { word: "papaya", pos: "n.", cn_def: "木瓜", en_def: "a soft orange tropical fruit with small black seeds inside",
    sentence: "The fruit stand near my school always sells sliced {{BLANK}} in small plastic bags.",
    cn: "我學校附近的水果攤總是賣裝在小塑膠袋裡的木瓜切片。" },
  { word: "peach", pos: "n.", cn_def: "桃子", en_def: "a soft round fruit with fuzzy pink-orange skin",
    sentence: "My grandmother's garden produces the juiciest {{BLANK}} every summer without fail.",
    cn: "我奶奶的花園每年夏天都會結出最多汁的桃子。" },
  { word: "pear", pos: "n.", cn_def: "梨子", en_def: "a sweet fruit that is rounder at the bottom and narrow at the top",
    sentence: "For dessert, the restaurant served a small dish of sliced {{BLANK}} with honey.",
    cn: "餐廳上的甜點是一小盤淋上蜂蜜的梨子切片。" },
  { word: "pineapple", pos: "n.", cn_def: "鳳梨", en_def: "a tropical fruit with rough yellow-brown skin and a sweet juicy inside",
    sentence: "The chef placed a thin slice of {{BLANK}} on top of the grilled pork.",
    cn: "主廚在烤豬肉上放了一片薄薄的鳳梨切片。" },
  { word: "strawberry", pos: "n.", cn_def: "草莓", en_def: "a small red fruit with seeds on the outside",
    sentence: "Every spring, families visit the farm to pick fresh {{BLANK}} themselves.",
    cn: "每年春天，許多家庭都會到農場親自採摘新鮮的草莓。" },
  { word: "tangerine", pos: "n.", cn_def: "橘子", en_def: "a small sweet orange fruit that is easy to peel",
    sentence: "During Chinese New Year, my grandmother gives every child a small {{BLANK}} for good luck.",
    cn: "過年期間，我奶奶會給每個小孩一顆小橘子來祝福好運。" },
  { word: "watermelon", pos: "n.", cn_def: "西瓜", en_def: "a large round fruit with green skin and juicy red flesh",
    sentence: "On the hottest day of August, we cut open a giant {{BLANK}} to share.",
    cn: "在八月最熱的那一天，我們切開一顆巨大的西瓜來分享。" },
  { word: "vegetable", pos: "n.", cn_def: "蔬菜", en_def: "a plant or part of a plant that people eat, like carrots or lettuce",
    sentence: "The doctor told my brother to eat more {{BLANK}} and less fried food.",
    cn: "醫生告訴我哥哥要多吃蔬菜，少吃油炸食物。" },
  { word: "bean", pos: "n.", cn_def: "豆", en_def: "a small seed from certain plants, often cooked and eaten",
    sentence: "My grandmother boils a pot of sweet red {{BLANK}} soup every winter morning.",
    cn: "每年冬天的早晨，我奶奶都會煮一鍋甜甜的紅豆湯。" },
  { word: "cabbage", pos: "n.", cn_def: "高麗菜", en_def: "a round vegetable with thick green or purple leaves",
    sentence: "The chef chopped a fresh head of {{BLANK}} for the side salad.",
    cn: "主廚切了一顆新鮮的高麗菜來做配菜沙拉。" },
  { word: "carrot", pos: "n.", cn_def: "紅蘿蔔", en_def: "a long orange vegetable that grows underground",
    sentence: "My little sister only eats her vegetable soup if it has {{BLANK}} in it.",
    cn: "我妹妹只有在蔬菜湯裡有紅蘿蔔的時候才會喝。" },
  { word: "corn", pos: "n.", cn_def: "玉米", en_def: "a tall yellow vegetable with many small kernels on a cob",
    sentence: "At the summer festival, the smell of grilled {{BLANK}} filled the entire street.",
    cn: "在夏季慶典上，烤玉米的香味瀰漫了整條街。" },
  { word: "lettuce", pos: "n.", cn_def: "萵苣", en_def: "a green leafy vegetable often used in salads and sandwiches",
    sentence: "The waiter added a few crisp leaves of {{BLANK}} to the sandwich.",
    cn: "服務生在三明治裡加了幾片脆脆的萵苣葉。" },
  { word: "onion", pos: "n.", cn_def: "洋蔥", en_def: "a round vegetable with a strong smell and taste, often used in cooking",
    sentence: "Whenever my father chops an {{BLANK}}, the whole kitchen makes us cry a little.",
    cn: "每次我爸爸切洋蔥時，整個廚房都會讓我們流一點眼淚。" },
  { word: "potato", pos: "n.", cn_def: "馬鈴薯", en_def: "a round vegetable that grows underground and is often boiled or fried",
    sentence: "On Sunday nights, my mother bakes a large {{BLANK}} for each of us.",
    cn: "每個星期天晚上，我媽媽都會幫我們每個人烤一顆大馬鈴薯。" },
  { word: "pumpkin", pos: "n.", cn_def: "南瓜", en_def: "a large round orange vegetable, often used in autumn dishes",
    sentence: "Every October, my neighbor carves a giant {{BLANK}} and places it by the door.",
    cn: "每年十月，我的鄰居都會雕刻一顆巨大的南瓜放在門邊。" },
  { word: "tomato", pos: "n.", cn_def: "番茄", en_def: "a soft round red fruit usually eaten as a vegetable",
    sentence: "My father grows juicy red {{BLANK}} in pots on our small balcony.",
    cn: "我爸爸在我們家的小陽台用盆栽種了多汁的紅番茄。" },
  { word: "drink", pos: "n.", cn_def: "飲料", en_def: "any liquid that you swallow, such as water or juice",
    sentence: "The waiter asked what kind of {{BLANK}} we wanted with our meal.",
    cn: "服務生問我們用餐時想要喝什麼飲料。" },
  { word: "beer", pos: "n.", cn_def: "啤酒", en_def: "a yellow alcoholic drink made from grain",
    sentence: "At the summer festival, the food stalls sold cold {{BLANK}} alongside grilled meat.",
    cn: "在夏季慶典上，攤位除了賣烤肉，也賣冰涼的啤酒。" },
  { word: "coffee", pos: "n.", cn_def: "咖啡", en_def: "a dark hot drink made from roasted beans",
    sentence: "Every morning before work, my father stops at the same shop for a hot {{BLANK}}.",
    cn: "每天上班前，我爸爸都會在同一家店買一杯熱咖啡。" },
  { word: "cola", pos: "n.", cn_def: "可樂", en_def: "a sweet brown carbonated soft drink",
    sentence: "At the movie theater, my brother always orders a large {{BLANK}} with his popcorn.",
    cn: "在電影院裡，我哥哥總是會點一杯大杯可樂配他的爆米花。" },
  { word: "juice", pos: "n.", cn_def: "果汁", en_def: "a liquid drink made by pressing fruit or vegetables",
    sentence: "For breakfast, my mother gives me a small glass of fresh orange {{BLANK}}.",
    cn: "早餐時，我媽媽會給我一小杯新鮮的柳橙汁。" },
  { word: "milk", pos: "n.", cn_def: "牛奶", en_def: "a white drink that comes from cows and is good for your bones",
    sentence: "Before bed, my little brother always drinks a warm glass of {{BLANK}}.",
    cn: "睡前，我弟弟總是會喝一杯溫熱的牛奶。" },
  { word: "soda", pos: "n.", cn_def: "汽水", en_def: "a sweet bubbly soft drink",
    sentence: "The bubbles in the cold {{BLANK}} tickled my nose as I drank it quickly.",
    cn: "我快速喝汽水時，冰涼的氣泡讓我的鼻子覺得有點癢。" },
  { word: "soft drink", pos: "n.", cn_def: "汽水", en_def: "a sweet, non-alcoholic drink, often with bubbles",
    sentence: "The vending machine outside our classroom only sells water and one kind of {{BLANK}}.",
    cn: "我們教室外面的販賣機只賣水和一種汽水。" },
  { word: "tea", pos: "n.", cn_def: "茶", en_def: "a hot or cold drink made by soaking dried leaves in water",
    sentence: "My grandmother drinks a cup of warm {{BLANK}} every afternoon at exactly three o'clock.",
    cn: "我奶奶每天下午三點整都會喝一杯溫熱的茶。" },
  { word: "butter", pos: "n.", cn_def: "奶油", en_def: "a soft yellow food made from cream, spread on bread",
    sentence: "My mother melts a small piece of {{BLANK}} on top of the hot pancakes.",
    cn: "我媽媽會在熱熱的鬆餅上融化一小塊奶油。" },
  { word: "cream", pos: "n.", cn_def: "鮮奶油", en_def: "the thick rich part of milk, often used to top desserts",
    sentence: "The waiter added a swirl of whipped {{BLANK}} on top of my hot chocolate.",
    cn: "服務生在我的熱巧克力上加了一圈打發鮮奶油。" },
  { word: "flour", pos: "n.", cn_def: "麵粉", en_def: "a fine white powder made from grain, used to make bread and cakes",
    sentence: "Before baking, my mother sifted the {{BLANK}} carefully into a large mixing bowl.",
    cn: "烘焙前，我媽媽小心地把麵粉過篩到一個大攪拌碗裡。" },
  { word: "honey", pos: "n.", cn_def: "蜂蜜", en_def: "a sweet sticky golden liquid made by bees",
    sentence: "My grandmother always adds a spoonful of {{BLANK}} to her morning tea.",
    cn: "我奶奶每天早上喝茶時都會加一勺蜂蜜。" },
  { word: "ketchup", pos: "n.", cn_def: "番茄醬", en_def: "a thick red sauce made from tomatoes, often eaten with fries",
    sentence: "My little cousin pours far too much {{BLANK}} on his French fries every time.",
    cn: "我表弟每次吃薯條都會倒太多番茄醬。" },
  { word: "oil", pos: "n.", cn_def: "油", en_def: "a thick liquid used for cooking food",
    sentence: "The chef heated a small amount of {{BLANK}} in the pan before adding the vegetables.",
    cn: "主廚在加入蔬菜之前先在鍋裡熱了少量的油。" },
  { word: "pepper", pos: "n.", cn_def: "胡椒", en_def: "a spice with small black or white grains, used to add a sharp taste",
    sentence: "My father always shakes a little black {{BLANK}} onto his fried eggs.",
    cn: "我爸爸吃煎蛋時總會撒一點黑胡椒。" },
  { word: "salt", pos: "n.", cn_def: "鹽", en_def: "a white substance used to add flavor to food",
    sentence: "The soup tasted a little plain, so I added a small pinch of {{BLANK}}.",
    cn: "這碗湯味道有點淡，所以我加了一小撮鹽。" },
  { word: "soy-sauce", pos: "n.", cn_def: "醬油", en_def: "a dark salty sauce made from soybeans, common in Asian cooking",
    sentence: "My mother dips the dumplings into a small bowl of dark {{BLANK}} before eating.",
    cn: "我媽媽吃餃子前會先沾一小碗深色的醬油。" },
  { word: "sugar", pos: "n.", cn_def: "糖", en_def: "a sweet white substance used to make food and drinks taste sweet",
    sentence: "My brother always adds two spoonfuls of {{BLANK}} to his coffee every morning.",
    cn: "我哥哥每天早上喝咖啡時都會加兩勺糖。" },
  { word: "vinegar", pos: "n.", cn_def: "醋", en_def: "a sour liquid used to add flavor or to pickle food",
    sentence: "My grandmother mixes a splash of {{BLANK}} into the salad dressing for extra flavor.",
    cn: "我奶奶會在沙拉醬裡加一點醋來增添風味。" }
];

// ---- Part 2 data: 45 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (12/11/11/11), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "My mother always keeps something fresh on the kitchen table. The bowl of ______ is for anyone who feels hungry.",
    options: ["rice","soup","candy","fruit"], answer: 3, vocabIndex: 0 },
  { q: "Every day before school, my father packs my lunch box carefully. He always adds a shiny red ______ on top.",
    options: ["onion","apple","potato","pepper"], answer: 1, vocabIndex: 1 },
  { q: "Before her morning run, my sister needs quick energy. She always eats a ______ on her way out the door.",
    options: ["banana","pumpkin","carrot","cabbage"], answer: 0, vocabIndex: 2 },
  { q: "At the night market, a vendor sold something sweet by the bag. The purple ______ tasted juicy and cold.",
    options: ["tomato","lemon","grape","bean"], answer: 2, vocabIndex: 3 },
  { q: "My grandfather grows several fruit trees in his small garden. The green ______ trees give fruit every summer.",
    options: ["guava","mango","peach","pear"], answer: 0, vocabIndex: 4 },
  { q: "On a hot afternoon, nothing tastes better than something cold and sour. A glass of ______ tea always helps.",
    options: ["milk","coffee","lemon","soda"], answer: 2, vocabIndex: 5 },
  { q: "During the summer, my aunt makes a refreshing dessert for the whole family. The shaved ice is topped with ripe ______.",
    options: ["onion","pumpkin","corn","mango"], answer: 3, vocabIndex: 6 },
  { q: "My mother squeezes something fresh every single morning. She uses a fresh ______ to make us juice before school.",
    options: ["pear","orange","tomato","lettuce"], answer: 1, vocabIndex: 7 },
  { q: "The fruit stand near my school always has long lines. It sells sliced ______ in small plastic bags every day.",
    options: ["potato","carrot","papaya","cabbage"], answer: 2, vocabIndex: 8 },
  { q: "My grandmother's garden produces something delicious every summer without fail. The juiciest ______ always comes from her old tree.",
    options: ["lemon","guava","grape","peach"], answer: 3, vocabIndex: 9 },
  { q: "For dessert, the restaurant served something light and sweet with honey. A small dish of sliced ______ ended the meal nicely.",
    options: ["onion","potato","pear","corn"], answer: 2, vocabIndex: 10 },
  { q: "The chef wanted to add something tropical to the dish. He placed a thin slice of ______ on top of the grilled pork.",
    options: ["pumpkin","cabbage","lettuce","pineapple"], answer: 3, vocabIndex: 11 },
  { q: "Every spring, families visit the same farm together. They enjoy picking fresh ______ themselves under the warm sun.",
    options: ["tomato","bean","strawberry","onion"], answer: 2, vocabIndex: 12 },
  { q: "During Chinese New Year, my grandmother gives every child something small and sweet. The little ______ is meant for good luck.",
    options: ["potato","tangerine","carrot","pumpkin"], answer: 1, vocabIndex: 13 },
  { q: "On the hottest day of August, the whole family wanted something cool. We cut open a giant ______ to share together.",
    options: ["pumpkin","cabbage","potato","watermelon"], answer: 3, vocabIndex: 14 },
  { q: "The doctor gave my brother some advice during his last visit. He told him to eat more ______ and less fried food.",
    options: ["candy","cake","vegetable","cookie"], answer: 2, vocabIndex: 15 },
  { q: "Every winter morning, my grandmother makes something warm and sweet. She boils a pot of red ______ soup for breakfast.",
    options: ["corn","bean","lettuce","onion"], answer: 1, vocabIndex: 16 },
  { q: "The chef needed something fresh for the side salad. He chopped a whole head of ______ into thin pieces.",
    options: ["tomato","papaya","cabbage","guava"], answer: 2, vocabIndex: 17 },
  { q: "My little sister is very picky about her vegetable soup. She only drinks it if there is ______ inside.",
    options: ["lettuce","onion","cabbage","carrot"], answer: 3, vocabIndex: 18 },
  { q: "At the summer festival, a wonderful smell filled the whole street. The smell of grilled ______ made everyone hungry.",
    options: ["potato","pumpkin","corn","bean"], answer: 2, vocabIndex: 19 },
  { q: "The waiter wanted to make the sandwich a little fresher. He added a few crisp leaves of ______ on top.",
    options: ["onion","tomato","corn","lettuce"], answer: 3, vocabIndex: 20 },
  { q: "Whenever my father cooks in the kitchen, something always makes us cry a little. Chopping an ______ always has that effect.",
    options: ["potato","onion","carrot","pumpkin"], answer: 1, vocabIndex: 21 },
  { q: "On Sunday nights, my mother prepares something simple for everyone. She bakes a large ______ for each person at the table.",
    options: ["potato","tomato","corn","bean"], answer: 0, vocabIndex: 22 },
  { q: "Every October, my neighbor decorates the front door for autumn. He carves a giant ______ and places it outside.",
    options: ["watermelon","pumpkin","cabbage","papaya"], answer: 1, vocabIndex: 23 },
  { q: "My father enjoys gardening on our small balcony every weekend. He grows juicy red ______ in several large pots.",
    options: ["lettuce","onion","pumpkin","tomato"], answer: 3, vocabIndex: 24 },
  { q: "Before bringing our food, the waiter asked about something to go with the meal. He wanted to know what ______ we wanted.",
    options: ["dessert","drink","snack","soup"], answer: 1, vocabIndex: 25 },
  { q: "At the summer festival, the food stalls offered something cold for adults. Many people chose a cold ______ with their grilled meat.",
    options: ["beer","juice","milk","tea"], answer: 0, vocabIndex: 26 },
  { q: "Every morning before work, my father has the same routine. He stops at the same shop for a hot ______.",
    options: ["soda","coffee","juice","milk"], answer: 1, vocabIndex: 27 },
  { q: "At the movie theater, my brother always orders the same thing. He gets a large ______ to go with his popcorn.",
    options: ["cola","tea","milk","juice"], answer: 0, vocabIndex: 28 },
  { q: "For breakfast, my mother prepares something fresh and healthy every day. She gives me a small glass of orange ______.",
    options: ["soda","milk","tea","juice"], answer: 3, vocabIndex: 29 },
  { q: "Before bed every night, my little brother follows the same habit. He always drinks a warm glass of ______ first.",
    options: ["milk","juice","soda","coffee"], answer: 0, vocabIndex: 30 },
  { q: "The bubbles in something cold tickled my nose while I drank it quickly. The cold ______ fizzed all the way down.",
    options: ["milk","soda","tea","juice"], answer: 1, vocabIndex: 31 },
  { q: "The vending machine outside our classroom has very few choices. It only sells water and one kind of ______.",
    options: ["soft drink","coffee","milk","beer"], answer: 0, vocabIndex: 32 },
  { q: "My grandmother has a strict routine every single afternoon. She drinks a cup of warm ______ at exactly three o'clock.",
    options: ["soda","cola","tea","beer"], answer: 2, vocabIndex: 33 },
  { q: "My mother always wants the pancakes to taste extra rich. She melts a small piece of ______ on top of them.",
    options: ["butter","cheese","honey","sugar"], answer: 0, vocabIndex: 34 },
  { q: "The waiter wanted to make my drink look special. He added a swirl of whipped ______ on top of my hot chocolate.",
    options: ["sugar","cream","honey","butter"], answer: 1, vocabIndex: 35 },
  { q: "Before baking the cake, my mother followed every step carefully. She sifted the ______ into a large mixing bowl first.",
    options: ["flour","sugar","salt","pepper"], answer: 0, vocabIndex: 36 },
  { q: "My grandmother has a small sweet habit every morning. She always adds a spoonful of ______ to her tea.",
    options: ["sugar","salt","honey","vinegar"], answer: 2, vocabIndex: 37 },
  { q: "My little cousin always makes a mess at the dinner table. He pours far too much ______ on his French fries.",
    options: ["ketchup","honey","oil","vinegar"], answer: 0, vocabIndex: 38 },
  { q: "Before adding the vegetables, the chef prepared the hot pan carefully. He heated a small amount of ______ first.",
    options: ["water","milk","juice","oil"], answer: 3, vocabIndex: 39 },
  { q: "My father has a small habit with his breakfast every morning. He always shakes a little black ______ onto his fried eggs.",
    options: ["salt","pepper","sugar","honey"], answer: 1, vocabIndex: 40 },
  { q: "The soup tasted a little plain when I first tried it. I added a small pinch of ______ to fix the flavor.",
    options: ["salt","sugar","pepper","honey"], answer: 0, vocabIndex: 41 },
  { q: "My mother has a habit before eating dumplings at dinner. She dips them into a small bowl of dark ______ first.",
    options: ["vinegar","ketchup","soy-sauce","oil"], answer: 2, vocabIndex: 42 },
  { q: "My brother likes his coffee very sweet every single morning. He always adds two spoonfuls of ______ before drinking it.",
    options: ["sugar","salt","pepper","honey"], answer: 0, vocabIndex: 43 },
  { q: "My grandmother wants the salad dressing to taste a little brighter. She mixes in a splash of ______ for extra flavor.",
    options: ["soy-sauce","ketchup","oil","vinegar"], answer: 3, vocabIndex: 44 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "alongside": { pos: "prep.", en_def: "next to; together with", cn_def: "與……一起" },
  "amount": { pos: "n.", en_def: "a quantity of something", cn_def: "數量" },
  "aunt": { pos: "n.", en_def: "the sister of your father or mother", cn_def: "阿姨；伯母" },
  "bakes": { pos: "v.", en_def: "cooks food in an oven", cn_def: "烘烤" },
  "baking": { pos: "v.", en_def: "cooking food in an oven", cn_def: "烘焙中" },
  "balcony": { pos: "n.", en_def: "a platform outside an upper window of a building", cn_def: "陽台" },
  "boils": { pos: "v.", en_def: "heats a liquid until it bubbles", cn_def: "煮沸" },
  "bowl": { pos: "n.", en_def: "a round deep dish used for food", cn_def: "碗" },
  "breakfast": { pos: "n.", en_def: "the first meal of the day", cn_def: "早餐" },
  "bubbles": { pos: "n.", en_def: "small balls of air or gas in a liquid", cn_def: "氣泡" },
  "cake": { pos: "n.", en_def: "a sweet baked food, often eaten on birthdays", cn_def: "蛋糕" },
  "candy": { pos: "n.", en_def: "a small sweet food made mostly of sugar", cn_def: "糖果" },
  "carves": { pos: "v.", en_def: "cuts a shape into something", cn_def: "雕刻" },
  "cheese": { pos: "n.", en_def: "a solid food made from milk", cn_def: "乳酪" },
  "chef": { pos: "n.", en_def: "a professional cook, especially the head cook", cn_def: "主廚" },
  "chopped": { pos: "v.", en_def: "cut something into small pieces", cn_def: "切碎" },
  "chops": { pos: "v.", en_def: "cuts something into pieces", cn_def: "切" },
  "classroom": { pos: "n.", en_def: "a room where students have lessons", cn_def: "教室" },
  "cookie": { pos: "n.", en_def: "a small flat sweet baked food", cn_def: "餅乾" },
  "cousin": { pos: "n.", en_def: "the child of your aunt or uncle", cn_def: "表/堂兄弟姊妹" },
  "crisp": { pos: "adj.", en_def: "firm and fresh; easy to bite", cn_def: "脆的" },
  "dessert": { pos: "n.", en_def: "a sweet food eaten at the end of a meal", cn_def: "甜點" },
  "dips": { pos: "v.", en_def: "puts something briefly into a liquid", cn_def: "沾" },
  "dish": { pos: "n.", en_def: "a particular type of food served as part of a meal", cn_def: "菜；餐點" },
  "doctor": { pos: "n.", en_def: "a person trained to treat sick people", cn_def: "醫生" },
  "dressing": { pos: "n.", en_def: "a sauce added to salad", cn_def: "醬汁；調味料" },
  "dumplings": { pos: "n.", en_def: "small pieces of dough filled with meat or vegetables", cn_def: "餃子（複數）" },
  "eggs": { pos: "n.", en_def: "oval foods laid by hens", cn_def: "蛋（複數）" },
  "energy": { pos: "n.", en_def: "the power to be active without getting tired", cn_def: "能量" },
  "extra": { pos: "adj.", en_def: "more than the usual amount", cn_def: "額外的" },
  "families": { pos: "n.", en_def: "groups of people related to each other", cn_def: "家庭（複數）" },
  "farm": { pos: "n.", en_def: "land used for growing crops or raising animals", cn_def: "農場" },
  "festival": { pos: "n.", en_def: "a special day or time of celebration", cn_def: "節日" },
  "filled": { pos: "v.", en_def: "made something full", cn_def: "充滿" },
  "flavor": { pos: "n.", en_def: "the taste of food or drink", cn_def: "風味；味道" },
  "food": { pos: "n.", en_def: "anything that people or animals eat to stay alive", cn_def: "食物" },
  "french fries": { pos: "n.", en_def: "thin strips of fried potato", cn_def: "薯條" },
  "fresh": { pos: "adj.", en_def: "newly made or grown, not old", cn_def: "新鮮的" },
  "fried": { pos: "adj.", en_def: "cooked in hot oil", cn_def: "油炸的" },
  "garden": { pos: "n.", en_def: "an area of land where plants and flowers are grown", cn_def: "花園" },
  "giant": { pos: "adj.", en_def: "extremely large", cn_def: "巨大的" },
  "grandfather": { pos: "n.", en_def: "the father of your mother or father", cn_def: "爺爺/外公" },
  "grandmother": { pos: "n.", en_def: "the mother of your mother or father", cn_def: "奶奶/外婆" },
  "grilled": { pos: "adj.", en_def: "cooked over direct heat", cn_def: "烤的" },
  "grows": { pos: "v.", en_def: "plants and takes care of something living", cn_def: "種植" },
  "head": { pos: "n.", en_def: "a whole rounded vegetable, like a head of cabbage", cn_def: "（蔬菜的）顆" },
  "heated": { pos: "v.", en_def: "made something warm or hot", cn_def: "加熱（過去式）" },
  "hottest": { pos: "adj.", en_def: "the most hot", cn_def: "最熱的" },
  "ice": { pos: "n.", en_def: "water frozen solid", cn_def: "冰" },
  "juiciest": { pos: "adj.", en_def: "the most full of juice", cn_def: "最多汁的" },
  "juicy": { pos: "adj.", en_def: "full of liquid; not dry", cn_def: "多汁的" },
  "kitchen": { pos: "n.", en_def: "the room in a house where food is cooked", cn_def: "廚房" },
  "leaves": { pos: "n.", en_def: "the flat green parts of a plant", cn_def: "葉子（複數）" },
  "luck": { pos: "n.", en_def: "good or bad things that happen by chance", cn_def: "運氣" },
  "lunch": { pos: "n.", en_def: "a meal eaten in the middle of the day", cn_def: "午餐" },
  "machine": { pos: "n.", en_def: "a device that does work using power", cn_def: "機器" },
  "market": { pos: "n.", en_def: "a place where food and goods are sold", cn_def: "市場" },
  "meal": { pos: "n.", en_def: "the food eaten at one particular time", cn_def: "一餐" },
  "meat": { pos: "n.", en_def: "the flesh of an animal eaten as food", cn_def: "肉" },
  "melts": { pos: "v.", en_def: "changes from solid to liquid by heat", cn_def: "融化" },
  "mixes": { pos: "v.", en_def: "combines two or more things together", cn_def: "混合" },
  "mixing": { pos: "v.", en_def: "combining two or more things together", cn_def: "攪拌" },
  "neighbor": { pos: "n.", en_def: "a person who lives near you", cn_def: "鄰居" },
  "nose": { pos: "n.", en_def: "the part of the face used for smelling", cn_def: "鼻子" },
  "o'clock": { pos: "adv.", en_def: "used to say the exact hour", cn_def: "……點鐘" },
  "pan": { pos: "n.", en_def: "a flat metal container used for cooking", cn_def: "平底鍋" },
  "pancakes": { pos: "n.", en_def: "flat round cakes cooked in a pan", cn_def: "鬆餅（複數）" },
  "pinch": { pos: "n.", en_def: "a very small amount, held between two fingers", cn_def: "一小撮" },
  "placed": { pos: "v.", en_def: "put something somewhere carefully", cn_def: "放置（過去式）" },
  "places": { pos: "v.", en_def: "puts something somewhere carefully", cn_def: "放置" },
  "plain": { pos: "adj.", en_def: "simple, without much flavor or decoration", cn_def: "平淡的" },
  "plastic": { pos: "adj.", en_def: "made of a light man-made material", cn_def: "塑膠的" },
  "popcorn": { pos: "n.", en_def: "a snack made from corn that pops open when heated", cn_def: "爆米花" },
  "pork": { pos: "n.", en_def: "meat that comes from a pig", cn_def: "豬肉" },
  "pot": { pos: "n.", en_def: "a round deep container used for cooking", cn_def: "鍋子" },
  "pots": { pos: "n.", en_def: "containers used for cooking or planting", cn_def: "鍋子；盆栽（複數）" },
  "pours": { pos: "v.", en_def: "makes a liquid flow out of a container", cn_def: "倒；倒出" },
  "produces": { pos: "v.", en_def: "makes or grows something", cn_def: "生產；結（果）" },
  "purple": { pos: "adj.", en_def: "a color between red and blue", cn_def: "紫色的" },
  "refreshing": { pos: "adj.", en_def: "making you feel cool and less tired", cn_def: "提神的；清爽的" },
  "restaurant": { pos: "n.", en_def: "a place where people pay to eat meals", cn_def: "餐廳" },
  "rice": { pos: "n.", en_def: "small white grains that are cooked and eaten as a main food", cn_def: "飯（米）" },
  "ripe": { pos: "adj.", en_def: "ready to be eaten; fully grown", cn_def: "成熟的" },
  "salad": { pos: "n.", en_def: "a cold dish of mixed vegetables", cn_def: "沙拉" },
  "sandwich": { pos: "n.", en_def: "two slices of bread with food between them", cn_def: "三明治" },
  "shakes": { pos: "v.", en_def: "moves something quickly up and down or side to side", cn_def: "搖；撒" },
  "shaved": { pos: "adj.", en_def: "cut into very thin pieces", cn_def: "削成薄片的" },
  "shiny": { pos: "adj.", en_def: "bright and reflecting light", cn_def: "閃亮的" },
  "shop": { pos: "n.", en_def: "a small store that sells things", cn_def: "商店" },
  "sifted": { pos: "v.", en_def: "passed something through a fine screen to remove lumps", cn_def: "過篩（過去式）" },
  "slice": { pos: "n.", en_def: "a thin flat piece cut from something larger", cn_def: "一片" },
  "sliced": { pos: "adj.", en_def: "cut into thin flat pieces", cn_def: "切片的" },
  "smell": { pos: "n.", en_def: "something noticed with the nose", cn_def: "氣味" },
  "snack": { pos: "n.", en_def: "a small amount of food eaten between meals", cn_def: "點心" },
  "soup": { pos: "n.", en_def: "a liquid food often made by cooking meat or vegetables in water", cn_def: "湯" },
  "splash": { pos: "n.", en_def: "a small amount of liquid added quickly", cn_def: "一點點（液體）" },
  "spoonful": { pos: "n.", en_def: "the amount a spoon can hold", cn_def: "一勺" },
  "spoonfuls": { pos: "n.", en_def: "the amounts that several spoons can hold", cn_def: "幾勺" },
  "squeezes": { pos: "v.", en_def: "presses something firmly to get liquid out", cn_def: "榨；擠" },
  "stalls": { pos: "n.", en_def: "small open shops or tables, often outdoors", cn_def: "攤位（複數）" },
  "stand": { pos: "n.", en_def: "a small shop or table, usually outdoors", cn_def: "攤位" },
  "swirl": { pos: "n.", en_def: "a curling, twisting shape", cn_def: "一圈；旋渦狀" },
  "table": { pos: "n.", en_def: "a piece of furniture with a flat top", cn_def: "桌子" },
  "theater": { pos: "n.", en_def: "a building where movies or plays are shown", cn_def: "劇院；電影院" },
  "thin": { pos: "adj.", en_def: "not thick; narrow", cn_def: "薄的" },
  "tickled": { pos: "v.", en_def: "caused a light, ticklish feeling", cn_def: "使發癢（過去式）" },
  "topped": { pos: "v.", en_def: "covered something with a layer on top", cn_def: "鋪上（過去式）" },
  "trees": { pos: "n.", en_def: "tall plants with a trunk and branches", cn_def: "樹（複數）" },
  "vegetables": { pos: "n.", en_def: "plants eaten as food", cn_def: "蔬菜（複數）" },
  "vending": { pos: "adj.", en_def: "related to selling things through a machine", cn_def: "自動販售的" },
  "vendor": { pos: "n.", en_def: "a person who sells things, often outdoors", cn_def: "攤販" },
  "waiter": { pos: "n.", en_def: "a person who serves food in a restaurant", cn_def: "服務生" },
  "warm": { pos: "adj.", en_def: "having a comfortable level of heat", cn_def: "溫暖的" },
  "water": { pos: "n.", en_def: "the clear liquid that falls as rain and fills rivers", cn_def: "水" },
  "whipped": { pos: "adj.", en_def: "beaten until light and fluffy", cn_def: "打發的" },
  "winter": { pos: "n.", en_def: "the coldest season of the year", cn_def: "冬天" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});

// ---- Plural / variant aliases so MCQ option lookups resolve correctly ----
const PLURAL_ALIASES = {
  "soft drinks": "soft drink", "tangerines": "tangerine", "strawberries": "strawberry",
  "pineapples": "pineapple", "tomatoes": "tomato", "potatoes": "potato",
  "pumpkins": "pumpkin", "onions": "onion", "carrots": "carrot", "beans": "bean",
  "apples": "apple", "bananas": "banana", "grapes": "grape", "lemons": "lemon",
  "mangoes": "mango", "oranges": "orange", "peaches": "peach", "pears": "pear",
  "vegetables": "vegetable", "snacks": "snack", "soups": "soup", "candies": "candy"
};
Object.keys(PLURAL_ALIASES).forEach(plural => {
  const singular = PLURAL_ALIASES[plural];
  if (!LOOKUP[plural] && LOOKUP[singular]) {
    LOOKUP[plural] = LOOKUP[singular];
  }
});
