// ============================================================
// Group 19 Quiz Data: General Adjectives (Part 2)
// Word set (40 words, next-wild) — the second half of the
// "general adjectives" block from the "describing words" theme.
// This is the FINAL group completing the entire "describing
// words" theme, which began with Group 15 (Personality/Emotions).
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 19 - General Adjectives Part 2 (一般形容詞 二)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (40 words) ----
const VOCAB = [
  { word: "next", pos: "adj.", cn_def: "下一個的", en_def: "coming immediately after this one",
    sentence: "Please get off the bus at the {{BLANK}} stop near the library.",
    cn: "請在下一站靠近圖書館的地方下車。" },
  { word: "last", pos: "adj.", cn_def: "最後的", en_def: "coming after all others; final",
    sentence: "She was the {{BLANK}} student to leave the classroom after the bell rang.",
    cn: "鐘聲響起後，她是最後一個離開教室的學生。" },
  { word: "latest", pos: "adj.", cn_def: "最新的", en_def: "most recent; newest",
    sentence: "My brother waited in line for hours to buy the {{BLANK}} phone model.",
    cn: "我哥哥排隊等了好幾個小時才買到最新款的手機。" },
  { word: "latter", pos: "adj.", cn_def: "後者的", en_def: "referring to the second of two things mentioned",
    sentence: "Between pizza and noodles, we chose the {{BLANK}} option for dinner tonight.",
    cn: "在披薩和麵之間，我們今晚晚餐選擇了後者，也就是麵。" },
  { word: "long", pos: "adj.", cn_def: "長的", en_def: "having great length in distance or time",
    sentence: "We waited in a {{BLANK}} line for almost an hour to enter the museum.",
    cn: "我們排了將近一個小時的長隊才進入博物館。" },
  { word: "loud", pos: "adj.", cn_def: "大聲的", en_def: "making a lot of noise",
    sentence: "The music at the party was so {{BLANK}} that we could barely hear each other talk.",
    cn: "派對上的音樂太大聲了，我們幾乎聽不到彼此說話。" },
  { word: "lucky", pos: "adj.", cn_def: "幸運的", en_def: "having good things happen by chance",
    sentence: "He felt {{BLANK}} to find a parking spot right in front of the building.",
    cn: "他覺得自己很幸運能在大樓正前方找到停車位。" },
  { word: "magic", pos: "adj.", cn_def: "魔法的", en_def: "having special powers that seem impossible",
    sentence: "In the story, the old man owned a {{BLANK}} lamp that granted three wishes.",
    cn: "在這個故事裡，那位老人擁有一個能實現三個願望的魔法神燈。" },
  { word: "mass", pos: "adj.", cn_def: "大量的", en_def: "involving a large number of people or things",
    sentence: "The factory uses {{BLANK}} production to make thousands of toys every single day.",
    cn: "這家工廠採用大量生產的方式，每天製造數千個玩具。" },
  { word: "married", pos: "adj.", cn_def: "已婚的", en_def: "having a husband or wife",
    sentence: "My aunt has been {{BLANK}} to my uncle for almost twenty years now.",
    cn: "我阿姨已經和我叔叔結婚將近二十年了。" },
  { word: "not", pos: "adv.", cn_def: "不", en_def: "used to make a statement negative",
    sentence: "I am {{BLANK}} sure whether the store closes at nine or ten tonight.",
    cn: "我不確定這家店今晚是九點還是十點關門。" },
  { word: "off", pos: "adj.", cn_def: "關閉的", en_def: "not turned on or operating",
    sentence: "Before leaving the classroom, please make sure all the lights are turned {{BLANK}}.",
    cn: "離開教室前，請確保所有的燈都已經關閉。" },
  { word: "pale", pos: "adj.", cn_def: "蒼白的", en_def: "having less color than usual, especially in the face",
    sentence: "After being sick all week, she still looked quite {{BLANK}} at school today.",
    cn: "她整週生病後，今天在學校看起來仍然很蒼白。" },
  { word: "patient", pos: "adj.", cn_def: "有耐心的", en_def: "able to wait calmly without becoming upset",
    sentence: "The kindergarten teacher stayed {{BLANK}} even when the children would not stop talking.",
    cn: "即使孩子們一直講話不停，那位幼稚園老師依然保持耐心。" },
  { word: "personal", pos: "adj.", cn_def: "私人的", en_def: "belonging to or relating to a particular person",
    sentence: "She keeps her {{BLANK}} diary locked in a small box under her bed.",
    cn: "她把私人日記鎖在床下的一個小盒子裡。" },
  { word: "pleasant", pos: "adj.", cn_def: "愉悅的", en_def: "enjoyable or friendly; nice",
    sentence: "We had a {{BLANK}} afternoon walking through the park and feeding the ducks.",
    cn: "我們度過了一個愉快的午後，在公園裡散步並餵食鴨子。" },
  { word: "precious", pos: "adj.", cn_def: "珍貴的", en_def: "very valuable or important; treasured",
    sentence: "The necklace was a {{BLANK}} gift passed down from her great-grandmother.",
    cn: "這條項鍊是從她曾祖母那裡傳下來的珍貴禮物。" },
  { word: "ready", pos: "adj.", cn_def: "準備好的", en_def: "fully prepared for something",
    sentence: "Are you {{BLANK}} to leave for school, or do you need a few more minutes?",
    cn: "你準備好要去上學了嗎，還是還需要幾分鐘？" },
  { word: "scared", pos: "adj.", cn_def: "受驚嚇的", en_def: "feeling fear about something",
    sentence: "My little cousin was too {{BLANK}} to walk past the dark basement alone.",
    cn: "我的小表弟太害怕了，不敢獨自走過那個黑暗的地下室。" },
  { word: "serious", pos: "adj.", cn_def: "嚴重的；嚴肅的", en_def: "important and needing careful thought; not joking",
    sentence: "The doctor looked {{BLANK}} while explaining the results of the medical test.",
    cn: "醫生在解釋醫療檢查結果時表情嚴肅。" },
  { word: "sharp", pos: "adj.", cn_def: "鋒利的", en_def: "having a thin edge or point that can cut easily",
    sentence: "Be careful with that {{BLANK}} knife when you slice the vegetables.",
    cn: "切蔬菜時要小心那把鋒利的刀。" },
  { word: "skillful", pos: "adj.", cn_def: "有技術的", en_def: "having or showing great ability at something",
    sentence: "The {{BLANK}} carpenter built a beautiful wooden table in just two days.",
    cn: "那位有技術的木工師傅在短短兩天內就做出了一張漂亮的木桌。" },
  { word: "sneaky", pos: "adj.", cn_def: "鬼鬼祟祟的", en_def: "doing something secretly or dishonestly",
    sentence: "My cat is so {{BLANK}} that she always finds a way to steal food from the table.",
    cn: "我的貓非常鬼鬼祟祟，總是能找到方法從餐桌上偷食物。" },
  { word: "social", pos: "adj.", cn_def: "社會的；社交的", en_def: "relating to people spending time together; friendly",
    sentence: "My sister is very {{BLANK}} and makes new friends wherever she goes.",
    cn: "我姐姐非常善於社交，無論到哪裡都能交到新朋友。" },
  { word: "straight", pos: "adj.", cn_def: "直的", en_def: "without a curve or bend",
    sentence: "Draw a {{BLANK}} line from one corner of the paper to the other.",
    cn: "從紙的一個角畫一條直線到另一個角。" },
  { word: "strange", pos: "adj.", cn_def: "奇怪的", en_def: "unusual or unexpected; not familiar",
    sentence: "We heard a {{BLANK}} noise coming from the attic late last night.",
    cn: "我們昨晚很晚的時候聽到閣樓傳來一個奇怪的聲音。" },
  { word: "successful", pos: "adj.", cn_def: "成功的", en_def: "having achieved a desired goal or result",
    sentence: "After years of hard work, she finally became a {{BLANK}} writer with many fans.",
    cn: "經過多年的努力，她終於成為一位擁有許多粉絲的成功作家。" },
  { word: "such", pos: "adj.", cn_def: "如此的", en_def: "used to emphasize a quality or degree",
    sentence: "I have never seen {{BLANK}} a beautiful sunset over the ocean before.",
    cn: "我從來沒見過海上如此美麗的日落。" },
  { word: "sudden", pos: "adj.", cn_def: "突然的", en_def: "happening quickly and without warning",
    sentence: "A {{BLANK}} rainstorm forced everyone at the picnic to run for shelter.",
    cn: "一場突然的暴雨讓野餐的每個人都跑去躲雨。" },
  { word: "super", pos: "adj.", cn_def: "超級的", en_def: "extremely good or great",
    sentence: "The new roller coaster at the amusement park was absolutely {{BLANK}} exciting.",
    cn: "遊樂園裡的新雲霄飛車真是超級刺激。" },
  { word: "sure", pos: "adj.", cn_def: "有把握的", en_def: "having no doubt about something",
    sentence: "Are you {{BLANK}} that you locked the front door before we left the house?",
    cn: "你確定我們離開家之前鎖了前門嗎？" },
  { word: "thick", pos: "adj.", cn_def: "厚的", en_def: "having a large distance between opposite sides",
    sentence: "She wrapped herself in a {{BLANK}} blanket to stay warm during the cold night.",
    cn: "她裹著一條厚毯子，在寒冷的夜晚保暖。" },
  { word: "tidy", pos: "adj.", cn_def: "整齊的", en_def: "neat and well organized",
    sentence: "My roommate always keeps his side of the room {{BLANK}} and clean.",
    cn: "我的室友總是把房間自己那一邊保持整齊乾淨。" },
  { word: "tiny", pos: "adj.", cn_def: "微小的", en_def: "extremely small",
    sentence: "A {{BLANK}} kitten was hiding quietly underneath the porch steps.",
    cn: "一隻微小的小貓靜靜地躲在門廊階梯下面。" },
  { word: "touch", pos: "v.", cn_def: "觸摸", en_def: "to put your hand or fingers on something",
    sentence: "The museum guard reminded visitors not to {{BLANK}} any of the old paintings.",
    cn: "博物館的警衛提醒參觀者不要觸摸任何一幅老畫作。" },
  { word: "upper", pos: "adj.", cn_def: "較高的；上方的", en_def: "higher in position than something else",
    sentence: "Our classroom is located on the {{BLANK}} floor of the old school building.",
    cn: "我們的教室位於那座老校舍的較高樓層。" },
  { word: "valuable", pos: "adj.", cn_def: "有價值的", en_def: "worth a lot of money or very useful",
    sentence: "The old painting turned out to be far more {{BLANK}} than the family expected.",
    cn: "這幅老畫比這家人預期的還要珍貴許多。" },
  { word: "welcome", pos: "adj.", cn_def: "受歡迎的", en_def: "gladly received or accepted",
    sentence: "All new students are {{BLANK}} to join the after-school chess club anytime.",
    cn: "所有新生隨時都歡迎加入課後的棋藝社團。" },
  { word: "wet", pos: "adj.", cn_def: "潮濕的", en_def: "covered or soaked with water or another liquid",
    sentence: "His shoes were completely {{BLANK}} after walking through the puddles in the rain.",
    cn: "他在雨中走過水坑後，鞋子完全濕透了。" },
  { word: "wild", pos: "adj.", cn_def: "野生的", en_def: "living or growing in a natural state, not tamed or controlled",
    sentence: "A group of {{BLANK}} deer wandered through the campsite early in the morning.",
    cn: "一群野生的鹿在早晨時穿過了營地。" }
];

// ---- Part 2 data: 40 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (10 each), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "On the city bus, a recorded voice announces every upcoming stop along the route. The driver said the library is at the ______ stop.",
    options: ["last","next","latest","former"], answer: 1, vocabIndex: 0 },
  { q: "When the school bell finally rang at the end of the day, most students rushed straight out the door. She stayed behind and ended up being ______ to leave.",
    options: ["last","next","latest","sudden"], answer: 0, vocabIndex: 1 },
  { q: "Standing outside the store for hours before it even opened, my brother was determined to get something popular. He wanted the ______ phone model before it sold out.",
    options: ["last","former","latest","such"], answer: 2, vocabIndex: 2 },
  { q: "Deciding between pizza and noodles for dinner took longer than expected, but we finally agreed. Between the two choices, we picked the ______ option, which was the noodles.",
    options: ["former","next","last","latter"], answer: 3, vocabIndex: 3 },
  { q: "Outside the museum, dozens of visitors stood patiently waiting for the doors to open. We joined a ______ line that stretched almost around the block.",
    options: ["loud","thick","long","tidy"], answer: 2, vocabIndex: 4 },
  { q: "At the birthday party, the speakers were turned up so high that conversation became nearly impossible. The music was simply too ______ for anyone to talk normally.",
    options: ["long","loud","sharp","strange"], answer: 1, vocabIndex: 5 },
  { q: "Driving around the crowded parking lot, he was about to give up looking for a space. Right in front of the building, he felt ______ to find one open spot.",
    options: ["lucky","patient","scared","ready"], answer: 0, vocabIndex: 6 },
  { q: "In the old fairy tale, an elderly man carried a strange object that could grant wishes. His ______ lamp was said to hold three wishes inside.",
    options: ["mass","magic","super","sharp"], answer: 1, vocabIndex: 7 },
  { q: "Inside the busy factory, machines run around the clock to keep up with daily orders. Workers use ______ production methods to make thousands of toys every day.",
    options: ["mass","magic","social","such"], answer: 0, vocabIndex: 8 },
  { q: "For nearly two decades now, my aunt and uncle have shared birthdays, holidays, and everyday life together. They have been happily ______ since their wedding many years ago.",
    options: ["social","personal","married","ready"], answer: 2, vocabIndex: 9 },
  { q: "Checking the store hours online gave two different closing times depending on the website. I am ______ sure whether it closes at nine or ten tonight.",
    options: ["off","not","such","sure"], answer: 1, vocabIndex: 10 },
  { q: "Before locking up the classroom for the weekend, the teacher walked around checking every switch carefully. She made sure all the lights were completely turned ______.",
    options: ["not","wet","thick","off"], answer: 3, vocabIndex: 11 },
  { q: "After spending the entire week sick in bed with a fever, she still did not look like herself. Her face appeared unusually ______ even after returning to school.",
    options: ["pale","scared","tidy","wet"], answer: 0, vocabIndex: 12 },
  { q: "In the noisy kindergarten classroom, several children kept talking over each other no matter how many times she asked for quiet. The teacher somehow remained completely ______ throughout the chaos.",
    options: ["lucky","sneaky","patient","super"], answer: 2, vocabIndex: 13 },
  { q: "Every night before falling asleep, she writes down her private thoughts and secrets in a small locked notebook. That ______ diary stays hidden under her bed.",
    options: ["personal","social","successful","welcome"], answer: 0, vocabIndex: 14 },
  { q: "Strolling slowly through the park, we tossed bits of bread to the ducks gathered near the pond. It turned into a truly ______ afternoon for the whole family.",
    options: ["strange","sudden","scared","pleasant"], answer: 3, vocabIndex: 15 },
  { q: "Passed down through three generations of women in her family, the old necklace meant more than its price tag. To her, it was an incredibly ______ gift from her great-grandmother.",
    options: ["tiny","thick","precious","sharp"], answer: 2, vocabIndex: 16 },
  { q: "Standing by the door with her backpack on, she glanced at the clock one more time. \"Are you ______ to leave for school,\" her mother asked, \"or do you need more time?\"",
    options: ["sure","patient","social","ready"], answer: 3, vocabIndex: 17 },
  { q: "Every time the lights went out in the basement, my little cousin refused to go down there by himself. He always seemed far too ______ to walk past it alone.",
    options: ["pale","tidy","scared","sneaky"], answer: 2, vocabIndex: 18 },
  { q: "After running several tests in the office, the doctor's expression changed and her tone became much quieter. She looked unusually ______ while explaining the results to the family.",
    options: ["pleasant","welcome","lucky","serious"], answer: 3, vocabIndex: 19 },
  { q: "While slicing vegetables quickly for dinner, she nearly cut her finger on the kitchen tool she was using. Everyone in the house knew that particular knife was extremely ______.",
    options: ["sharp","thick","long","tidy"], answer: 0, vocabIndex: 20 },
  { q: "Working alone in his small workshop, the carpenter measured, cut, and sanded every piece of wood carefully. Everyone agreed his finished table proved how ______ he truly was.",
    options: ["sneaky","skillful","social","sudden"], answer: 1, vocabIndex: 21 },
  { q: "Every time the family sits down to eat, their cat waits quietly under the table for the perfect moment. She is incredibly ______ about grabbing food whenever no one is watching.",
    options: ["sneaky","skillful","patient","welcome"], answer: 0, vocabIndex: 22 },
  { q: "Wherever my sister goes on vacation, she comes home with new phone numbers and stories about people she met. Everyone describes her as remarkably ______ and easy to talk to.",
    options: ["personal","successful","sudden","social"], answer: 3, vocabIndex: 23 },
  { q: "Using a ruler to keep her hand steady, she carefully connected the two corners of the paper with her pencil. The result was a perfectly ______ line across the page.",
    options: ["straight","thick","sharp","long"], answer: 0, vocabIndex: 24 },
  { q: "Lying awake late at night, the whole family heard something unusual coming from above the bedroom ceiling. Nobody could explain the ______ noise echoing through the attic.",
    options: ["pleasant","tidy","strange","ready"], answer: 2, vocabIndex: 25 },
  { q: "After many years of writing stories that nobody wanted to publish, she finally found readers who loved her work. She eventually became a ______ author with fans all over the country.",
    options: ["scared","married","sneaky","successful"], answer: 3, vocabIndex: 26 },
  { q: "Standing on the cliff at sunset, the sky turned shades of orange and pink that nobody could look away from. None of us had ever witnessed ______ a breathtaking view before.",
    options: ["off","such","not","upper"], answer: 1, vocabIndex: 27 },
  { q: "Without any warning at all, dark clouds rolled in and rain began pouring down on the picnic blanket. That ______ storm sent everyone running for cover under the nearest tree.",
    options: ["patient","tidy","valuable","sudden"], answer: 3, vocabIndex: 28 },
  { q: "Climbing aboard the newest roller coaster at the amusement park, my cousins screamed with excitement the entire ride. Everyone agreed the experience felt absolutely ______ thrilling.",
    options: ["off","wet","super","thick"], answer: 2, vocabIndex: 29 },
  { q: "Right before leaving for vacation, my father suddenly stopped at the front door and looked back inside. \"Are you ______ that you locked it,\" my mother asked, \"before we leave?\"",
    options: ["ready","lucky","social","sure"], answer: 3, vocabIndex: 30 },
  { q: "On the coldest night of winter, she pulled an extra blanket from the closet and wrapped herself up completely. That ______ blanket kept her warm until morning.",
    options: ["sharp","straight","thick","off"], answer: 2, vocabIndex: 31 },
  { q: "Unlike most teenagers sharing a room, he always folds his clothes and makes his bed every single morning. His side of the room stays remarkably ______ no matter what.",
    options: ["wild","tidy","wet","loud"], answer: 1, vocabIndex: 32 },
  { q: "While cleaning under the porch steps, my neighbor discovered something small and soft curled up quietly in the shadows. A ______ kitten had been hiding there the whole time.",
    options: ["thick","such","loud","tiny"], answer: 3, vocabIndex: 33 },
  { q: "Walking slowly through the gallery, visitors admired the old paintings without getting too close to any of them. The museum guard reminded everyone politely not to ______ the artwork.",
    options: ["off","touch","such","ready"], answer: 1, vocabIndex: 34 },
  { q: "Climbing the stairs of the old school building, we passed several classrooms before reaching ours near the very top. Our classroom sits on the ______ floor of the building.",
    options: ["long","thick","upper","such"], answer: 2, vocabIndex: 35 },
  { q: "After an art expert examined the dusty old painting found in the attic, the family was stunned by the news. It turned out to be far more ______ than anyone had guessed.",
    options: ["valuable","tiny","wet","off"], answer: 0, vocabIndex: 36 },
  { q: "Posted on the door of the school's chess room, a colorful sign invites students of every skill level to stop by anytime. New members are always ______ to join the club.",
    options: ["married","welcome","scared","social"], answer: 1, vocabIndex: 37 },
  { q: "Walking home through the rain, he splashed straight through every puddle along the sidewalk without noticing. By the time he reached the door, his shoes were completely ______.",
    options: ["wet","thick","tidy","sharp"], answer: 0, vocabIndex: 38 },
  { q: "Just before sunrise near the campsite, several animals wandered quietly through the trees looking for food. A small group of ______ deer passed within a few feet of the tents.",
    options: ["tidy","wild","social","off"], answer: 1, vocabIndex: 39 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "absolutely": { pos: "adv.", en_def: "completely; totally", cn_def: "完全地；絕對地" },
  "amusement": { pos: "n.", en_def: "enjoyment or fun, as in an amusement park", cn_def: "娛樂" },
  "attic": { pos: "n.", en_def: "a space or room just below the roof of a house", cn_def: "閣樓" },
  "basement": { pos: "n.", en_def: "a room below the ground level of a building", cn_def: "地下室" },
  "blanket": { pos: "n.", en_def: "a thick piece of cloth used for warmth", cn_def: "毯子" },
  "campsite": { pos: "n.", en_def: "a place used for camping", cn_def: "營地" },
  "carpenter": { pos: "n.", en_def: "a person who builds and repairs wooden objects", cn_def: "木匠" },
  "chess": { pos: "n.", en_def: "a board game played with pieces like kings and queens", cn_def: "棋藝；西洋棋" },
  "coaster": { pos: "n.", en_def: "short for roller coaster, a fast amusement park ride", cn_def: "雲霄飛車" },
  "diary": { pos: "n.", en_def: "a book where someone writes about their daily life", cn_def: "日記" },
  "factory": { pos: "n.", en_def: "a building where goods are made in large numbers", cn_def: "工廠" },
  "former": { pos: "adj.", en_def: "having been something in the past, but not now; referring to the first of two things mentioned", cn_def: "前者的；前任的" },
  "granted": { pos: "v.", en_def: "gave someone what they wished for or asked for", cn_def: "准許；給予（過去式）" },
  "kindergarten": { pos: "n.", en_def: "a school or class for very young children", cn_def: "幼稚園" },
  "kitten": { pos: "n.", en_def: "a baby cat", cn_def: "小貓" },
  "lamp": { pos: "n.", en_def: "a device that produces light", cn_def: "燈" },
  "medical": { pos: "adj.", en_def: "relating to the treatment of illness or injury", cn_def: "醫療的" },
  "necklace": { pos: "n.", en_def: "a piece of jewelry worn around the neck", cn_def: "項鍊" },
  "porch": { pos: "n.", en_def: "a covered area at the entrance of a house", cn_def: "門廊" },
  "production": { pos: "n.", en_def: "the process of making goods or items", cn_def: "生產" },
  "puddles": { pos: "n.", en_def: "small pools of water on the ground", cn_def: "水坑（複數）" },
  "rainstorm": { pos: "n.", en_def: "a storm with heavy rain", cn_def: "暴雨" },
  "roommate": { pos: "n.", en_def: "a person who shares a room or home with you", cn_def: "室友" },
  "shelter": { pos: "n.", en_def: "a place that protects from weather or danger", cn_def: "避難處；遮蔽處" },
  "sunset": { pos: "n.", en_def: "the time when the sun goes down in the evening", cn_def: "日落" },
  "writer": { pos: "n.", en_def: "a person who writes books, articles, or stories as a job", cn_def: "作家" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
