// ============================================================
// Group 5 Quiz Data: Mammals / Reptiles / Sea Creatures / Insects
// Full word set (40 words) — every "animals" theme word not
// already covered in Group 4 (birds / farm & pet animals).
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 5 - Mammals / Reptiles / Sea Creatures / Insects (哺乳類/爬蟲類/海洋生物/昆蟲)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (40 words) ----
const VOCAB = [
  { word: "ant", pos: "n.", cn_def: "螞蟻", en_def: "a tiny insect that lives and works together in large groups",
    sentence: "A long line of tiny {{BLANK}} marched across the kitchen floor, carrying small pieces of bread.",
    cn: "一長排小小的螞蟻排隊走過廚房地板，搬著小小的麵包屑。" },
  { word: "bee", pos: "n.", cn_def: "蜜蜂", en_def: "a small flying insect that makes honey and can sting",
    sentence: "A busy {{BLANK}} flew from flower to flower in the garden, collecting sweet nectar on a sunny morning.",
    cn: "一隻忙碌的蜜蜂在晴朗的早晨於花園裡飛來飛去，採集甜美的花蜜。" },
  { word: "bug", pos: "n.", cn_def: "蟲子", en_def: "a small insect or creeping creature",
    sentence: "My little brother found a strange green {{BLANK}} crawling slowly along the edge of his bedroom window.",
    cn: "我弟弟發現一隻奇怪的綠色蟲子正沿著他臥室窗邊緩慢地爬行。" },
  { word: "butterfly", pos: "n.", cn_def: "蝴蝶", en_def: "a colorful insect with large wings that flies among flowers",
    sentence: "A beautiful orange {{BLANK}} landed gently on the flower right in front of the excited little girl.",
    cn: "一隻美麗的橘色蝴蝶輕輕地停在那位興奮小女孩面前的花朵上。" },
  { word: "cockroach", pos: "n.", cn_def: "蟑螂", en_def: "a brown insect that often hides in kitchens at night",
    sentence: "Everyone in the kitchen screamed when a large brown {{BLANK}} suddenly ran out from behind the refrigerator.",
    cn: "當一隻大蟑螂突然從冰箱後面跑出來時，廚房裡的每個人都驚叫了起來。" },
  { word: "crab", pos: "n.", cn_def: "螃蟹", en_def: "a sea animal with a hard shell and two big claws",
    sentence: "At low tide, my father and I found a small orange {{BLANK}} hiding under a wet rock.",
    cn: "退潮時，我和爸爸在一塊濕濕的石頭下發現了一隻橘色的小螃蟹。" },
  { word: "dinosaur", pos: "n.", cn_def: "恐龍", en_def: "a huge animal that lived millions of years ago and no longer exists",
    sentence: "At the museum, my son stood frozen in awe beneath the enormous skeleton of a real {{BLANK}}.",
    cn: "在博物館裡，我兒子站在一具真正的恐龍骨架下方，看得目瞪口呆。" },
  { word: "dog", pos: "n.", cn_def: "狗", en_def: "a common animal that people often keep as a pet",
    sentence: "Every afternoon after school, my little brother takes our {{BLANK}} for a walk around the park.",
    cn: "每天放學後，我弟弟都會帶我們的狗去公園散步。" },
  { word: "dolphin", pos: "n.", cn_def: "海豚", en_def: "a smart sea animal that swims fast and is known for being friendly",
    sentence: "During the boat tour, a group of gray {{BLANK}} jumped happily beside the boat for several minutes.",
    cn: "在乘船遊覽時，一群灰色的海豚開心地在船邊跳躍了好幾分鐘。" },
  { word: "donkey", pos: "n.", cn_def: "驢子", en_def: "an animal that looks like a small horse with long ears",
    sentence: "On the mountain trail, tourists rode a patient {{BLANK}} slowly up the steep and rocky path.",
    cn: "在山路上，遊客們騎著一隻耐心的驢子緩緩走上陡峭的石頭小路。" },
  { word: "elephant", pos: "n.", cn_def: "大象", en_def: "a very large gray animal with a long nose called a trunk",
    sentence: "At the zoo, the children were amazed at how gently the huge {{BLANK}} picked up the peanuts.",
    cn: "在動物園裡，孩子們對那隻巨大的大象輕輕拿起花生感到驚訝。" },
  { word: "fish", pos: "n.", cn_def: "魚", en_def: "an animal that lives in water and breathes through gills",
    sentence: "My grandfather wakes up early every Sunday to catch {{BLANK}} at the quiet river near his house.",
    cn: "我爺爺每個星期天都會早起去他家附近那條安靜的河邊釣魚。" },
  { word: "fox", pos: "n.", cn_def: "狐狸", en_def: "a wild animal that looks like a dog with red fur and a pointed face",
    sentence: "Late at night, a clever {{BLANK}} crept quietly across the farmer's field, looking for food.",
    cn: "深夜裡，一隻聰明的狐狸悄悄地穿過農夫的田地，想找東西吃。" },
  { word: "frog", pos: "n.", cn_def: "青蛙", en_def: "a small green animal that lives near water and can jump far",
    sentence: "After the heavy rain, a small green {{BLANK}} hopped across the wet path near our classroom window.",
    cn: "大雨過後，一隻綠色的小青蛙跳過我們教室窗外那條濕濕的小路。" },
  { word: "goat", pos: "n.", cn_def: "山羊", en_def: "a farm animal with horns that likes to eat grass and leaves",
    sentence: "Behind the old farmhouse, a curious white {{BLANK}} chewed quietly on the leaves of a low bush.",
    cn: "在那間老農舍後面，一隻好奇的白山羊正安靜地嚼著矮叢上的葉子。" },
  { word: "hippo", pos: "n.", cn_def: "河馬", en_def: "a huge gray animal that spends most of its time in rivers",
    sentence: "At the zoo, a massive gray {{BLANK}} floated lazily in the pool, showing only its eyes above the water.",
    cn: "在動物園裡，一隻巨大的灰色河馬懶洋洋地浮在水池裡，只露出眼睛在水面上。" },
  { word: "horse", pos: "n.", cn_def: "馬", en_def: "a large strong animal that people can ride",
    sentence: "My cousin learned to ride a {{BLANK}} last summer at her grandparents' farm in the countryside.",
    cn: "我表姐去年夏天在她祖父母的鄉間農場學會了騎馬。" },
  { word: "insect", pos: "n.", cn_def: "昆蟲", en_def: "a small animal with six legs, like an ant or a bee",
    sentence: "For her science project, my sister collected several kinds of {{BLANK}} in a small glass jar.",
    cn: "為了科學作業，我姐姐用一個小玻璃罐收集了好幾種昆蟲。" },
  { word: "kangaroo", pos: "n.", cn_def: "袋鼠", en_def: "an Australian animal that jumps on its strong back legs",
    sentence: "We watched in delight as a young {{BLANK}} hopped across the open field at the wildlife park.",
    cn: "我們開心地看著一隻小袋鼠在野生動物園的空地上跳來跳去。" },
  { word: "lamb", pos: "n.", cn_def: "小羊", en_def: "a baby sheep",
    sentence: "Every spring, a fluffy white {{BLANK}} follows its mother closely across the green hillside near the farm.",
    cn: "每年春天，一隻毛茸茸的白色小羊都會緊跟著媽媽走過農場旁的綠色山坡。" },
  { word: "lion", pos: "n.", cn_def: "獅子", en_def: "a large wild cat with a loud roar, often called the king of animals",
    sentence: "During the safari trip, our guide warned us never to get out of the car near a {{BLANK}}.",
    cn: "在野生動物之旅中，導遊警告我們絕對不要在獅子附近下車。" },
  { word: "monkey", pos: "n.", cn_def: "猴子", en_def: "an animal that can climb trees well and looks a little like a small person",
    sentence: "A playful {{BLANK}} jumped from branch to branch, trying to steal a banana from a tourist's bag.",
    cn: "一隻愛玩的猴子在樹枝間跳來跳去，想從遊客的包包裡偷香蕉。" },
  { word: "mosquito", pos: "n.", cn_def: "蚊子", en_def: "a tiny flying insect that bites people and can spread disease",
    sentence: "On the hot summer night, a single annoying {{BLANK}} kept buzzing loudly around my head while I tried to sleep.",
    cn: "在炎熱的夏夜，一隻討厭的蚊子在我頭邊嗡嗡作響，讓我難以入睡。" },
  { word: "mouse", pos: "n.", cn_def: "老鼠", en_def: "a very small animal with a long tail that likes cheese",
    sentence: "Late one night, my mother screamed when a tiny gray {{BLANK}} ran quickly across the kitchen floor.",
    cn: "某天深夜，當一隻灰色的小老鼠迅速跑過廚房地板時，我媽媽嚇得叫了起來。" },
  { word: "pig", pos: "n.", cn_def: "豬", en_def: "a farm animal with pink skin that people raise for meat",
    sentence: "Every morning, the farmer feeds his {{BLANK}} fresh vegetables before he goes to work in the fields.",
    cn: "每天早上，農夫會在去田裡工作前先餵豬吃新鮮的蔬菜。" },
  { word: "puppy", pos: "n.", cn_def: "小狗", en_def: "a baby dog",
    sentence: "For her birthday, my niece received an adorable little {{BLANK}} that she immediately named Cookie.",
    cn: "我姪女的生日禮物是一隻可愛的小狗，她馬上就把它取名叫Cookie。" },
  { word: "rabbit", pos: "n.", cn_def: "兔子", en_def: "a small soft animal with long ears that likes to eat carrots",
    sentence: "My sister keeps a white {{BLANK}} in a small cage on our balcony and feeds it carrots daily.",
    cn: "我姐姐在我們的陽台上養了一隻白兔，每天都餵它吃紅蘿蔔。" },
  { word: "rat", pos: "n.", cn_def: "老鼠", en_def: "a small animal with a long tail, larger than a mouse, often found in dirty places",
    sentence: "The restaurant was shut down for a week after an inspector found a {{BLANK}} hiding behind the stove.",
    cn: "餐廳因為稽查員在爐子後面發現一隻老鼠而被停業一週。" },
  { word: "shark", pos: "n.", cn_def: "鯊魚", en_def: "a large strong fish in the ocean with sharp teeth",
    sentence: "The lifeguard quickly told all the swimmers to leave the water after spotting a {{BLANK}} near the shore.",
    cn: "救生員發現岸邊有鯊魚出現後，立刻要所有泳客離開海水。" },
  { word: "sheep", pos: "n.", cn_def: "綿羊", en_def: "a farm animal with thick wool, often kept in large groups",
    sentence: "On the hillside farm, dozens of woolly white {{BLANK}} grazed quietly under the warm afternoon sun.",
    cn: "在山坡上的農場裡，數十隻毛茸茸的白色綿羊在溫暖的午後陽光下安靜地吃草。" },
  { word: "shrimp", pos: "n.", cn_def: "蝦子", en_def: "a small sea animal with a curved body, often eaten as food",
    sentence: "At the night market, my favorite stall sells grilled {{BLANK}} on a stick for only fifty dollars.",
    cn: "在夜市裡，我最喜歡的攤位只賣五十元一串的烤蝦。" },
  { word: "snail", pos: "n.", cn_def: "蝸牛", en_def: "a small slow animal with a round shell on its back",
    sentence: "After the rain, a tiny {{BLANK}} slowly left a shiny trail across the wet garden path.",
    cn: "下雨後，一隻小蝸牛緩緩地在濕濕的花園小路上留下一道閃亮的痕跡。" },
  { word: "snake", pos: "n.", cn_def: "蛇", en_def: "a long thin animal with no legs that moves by sliding on the ground",
    sentence: "Everyone screamed and ran away when a long {{BLANK}} suddenly appeared on the path during our hike.",
    cn: "在我們健行的路上，一條長長的蛇突然出現，大家都嚇得邊叫邊跑開。" },
  { word: "spider", pos: "n.", cn_def: "蜘蛛", en_def: "a small creature with eight legs that makes webs to catch insects",
    sentence: "When she opened the old box in the garage, a large {{BLANK}} quickly ran out and disappeared.",
    cn: "當她打開車庫裡那個舊箱子時，一隻大蜘蛛迅速跑出來消失了。" },
  { word: "tiger", pos: "n.", cn_def: "老虎", en_def: "a large wild cat with orange fur and black stripes",
    sentence: "The little boy was both scared and excited when he saw a real {{BLANK}} for the first time.",
    cn: "那個小男孩第一次看到真正的老虎時，又害怕又興奮。" },
  { word: "turtle", pos: "n.", cn_def: "烏龜", en_def: "an animal with a hard round shell that moves very slowly",
    sentence: "We watched a slow {{BLANK}} crawl across the sand and disappear quietly into the calm ocean water.",
    cn: "我們看著一隻緩慢的烏龜爬過沙地，靜靜地消失在平靜的海水中。" },
  { word: "whale", pos: "n.", cn_def: "鯨魚", en_def: "the largest animal that lives in the ocean",
    sentence: "Far out at sea, the passengers cheered as a giant {{BLANK}} rose slowly and sprayed water into the air.",
    cn: "在遠方的海面上，一隻巨大的鯨魚緩緩浮出水面並噴出水柱，乘客們都歡呼起來。" },
  { word: "wolf", pos: "n.", cn_def: "野狼", en_def: "a wild animal that looks like a large dog and often hunts in groups",
    sentence: "Deep in the snowy forest, a lone gray {{BLANK}} howled loudly under the bright full moon.",
    cn: "在雪林深處，一隻孤獨的灰狼在皎潔的滿月下大聲嚎叫。" },
  { word: "worm", pos: "n.", cn_def: "蠕蟲", en_def: "a small long soft animal with no legs that lives in soil",
    sentence: "After the rain stopped, my little cousin found a wet pink {{BLANK}} wriggling on the garden path.",
    cn: "雨停後，我的小表弟在花園小路上發現一隻濕濕的粉紅色蠕蟲在蠕動。" },
  { word: "zebra", pos: "n.", cn_def: "斑馬", en_def: "an African animal that looks like a horse with black and white stripes",
    sentence: "At the safari park, a herd of striped {{BLANK}} grazed peacefully beside a small group of giraffes.",
    cn: "在野生動物園裡，一群有條紋的斑馬正和一小群長頸鹿一起安靜地吃草。" }
];

// ---- Part 2 data: 40 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (10 each), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "A long line of tiny ______ walked across the kitchen floor. They were carrying small pieces of bread.",
    options: ["bees","snakes","crabs","ants"], answer: 3, vocabIndex: 0 },
  { q: "In the garden, a busy ______ flew from flower to flower. It was collecting sweet nectar in the sun.",
    options: ["bee","spider","tiger","turtle"], answer: 0, vocabIndex: 1 },
  { q: "A strange green ______ crawled slowly along the window. My little brother watched it for a long time.",
    options: ["horse","whale","bug","goat"], answer: 2, vocabIndex: 2 },
  { q: "A colorful ______ landed softly on a flower. The little girl watched it quietly without making a sound.",
    options: ["spider","butterfly","fox","shark"], answer: 1, vocabIndex: 3 },
  { q: "A large brown ______ ran out from behind the refrigerator. Everyone in the kitchen screamed and jumped back.",
    options: ["rabbit","lamb","cockroach","dolphin"], answer: 2, vocabIndex: 4 },
  { q: "Under a wet rock at the beach, my brother found a small orange ______. Its claws moved quickly.",
    options: ["fox","crab","wolf","lion"], answer: 1, vocabIndex: 5 },
  { q: "At the museum, my son stood frozen in awe. He stared up at the huge skeleton of a real ______.",
    options: ["sheep","shrimp","dinosaur","snail"], answer: 2, vocabIndex: 6 },
  { q: "My uncle has a small farm. Every morning, he feeds his ______ and walks it around the yard.",
    options: ["pig","rat","whale","dog"], answer: 3, vocabIndex: 7 },
  { q: "During the boat tour, a group of gray ______ jumped happily beside the boat. Everyone cheered and took pictures.",
    options: ["sharks","spiders","dolphins","ants"], answer: 2, vocabIndex: 8 },
  { q: "On the mountain trail, tourists rode a patient ______ up the steep path. It walked slowly but never stopped.",
    options: ["donkey","zebra","monkey","kangaroo"], answer: 0, vocabIndex: 9 },
  { q: "At the zoo, we saw a huge gray ______. It used its long nose to pick up food.",
    options: ["tiger","elephant","rabbit","shark"], answer: 1, vocabIndex: 10 },
  { q: "Every Sunday morning, my grandfather quietly goes to the river. He always brings home fresh ______ for dinner.",
    options: ["worms","rats","snails","fish"], answer: 3, vocabIndex: 11 },
  { q: "Late at night, a ______ ran across the field near the farmhouse. It was looking for chickens to eat.",
    options: ["turtle","fox","dolphin","ant"], answer: 1, vocabIndex: 12 },
  { q: "After the heavy rain, a small green ______ hopped across the path. It jumped quickly into the wet grass.",
    options: ["snake","bee","whale","frog"], answer: 3, vocabIndex: 13 },
  { q: "Behind the old farmhouse, a curious white ______ chewed quietly on the leaves. It seemed very happy there.",
    options: ["shrimp","goat","wolf","shark"], answer: 1, vocabIndex: 14 },
  { q: "At the zoo, a massive gray ______ floated lazily in the pool. Only its eyes showed above the water.",
    options: ["hippo","zebra","lamb","puppy"], answer: 0, vocabIndex: 15 },
  { q: "My cousin learned to ride a ______ last summer. She held on tightly and smiled the whole time.",
    options: ["snail","worm","crab","horse"], answer: 3, vocabIndex: 16 },
  { q: "For her science project, my sister collected several kinds of ______. She kept them in a small glass jar.",
    options: ["insects","wolves","whales","horses"], answer: 0, vocabIndex: 17 },
  { q: "We watched in delight as a young ______ hopped across the open field. It moved on its strong back legs.",
    options: ["donkey","mouse","rat","kangaroo"], answer: 3, vocabIndex: 18 },
  { q: "Every spring, a fluffy white ______ follows its mother closely. They walk slowly across the green hillside together.",
    options: ["tiger","lamb","shrimp","snake"], answer: 1, vocabIndex: 19 },
  { q: "During the safari trip, our guide warned us. He said to never get out of the car near a ______.",
    options: ["fish","frog","puppy","lion"], answer: 3, vocabIndex: 20 },
  { q: "A playful ______ jumped from branch to branch. It tried to steal a banana from a tourist's bag.",
    options: ["dog","monkey","zebra","ant"], answer: 1, vocabIndex: 21 },
  { q: "On the hot summer night, a single annoying ______ kept buzzing around my head. I could not fall asleep.",
    options: ["snail","sheep","mosquito","goat"], answer: 2, vocabIndex: 22 },
  { q: "Late one night, my mother screamed loudly. A tiny gray ______ had just run across the kitchen floor.",
    options: ["shark","mouse","wolf","horse"], answer: 1, vocabIndex: 23 },
  { q: "Every morning, the farmer feeds his ______ fresh vegetables. Then he goes to work in the fields nearby.",
    options: ["pig","bug","rabbit","dolphin"], answer: 0, vocabIndex: 24 },
  { q: "For her birthday, my niece received an adorable little ______. She immediately gave it the name Cookie.",
    options: ["elephant","crab","puppy","fox"], answer: 2, vocabIndex: 25 },
  { q: "My sister keeps a small white ______ inside a cage on the balcony. She feeds it carrots every day.",
    options: ["rabbit","lamb","worm","bee"], answer: 0, vocabIndex: 26 },
  { q: "The restaurant closed for a week after an inspection. A worker found a ______ hiding behind the old stove.",
    options: ["turtle","butterfly","goat","rat"], answer: 3, vocabIndex: 27 },
  { q: "The lifeguard saw something dangerous near the beach. He quickly told everyone to swim away from the gray ______.",
    options: ["shark","rabbit","spider","tiger"], answer: 0, vocabIndex: 28 },
  { q: "On the hillside farm, dozens of woolly white ______ grazed quietly. They stayed under the warm afternoon sun.",
    options: ["zebras","wolves","snails","sheep"], answer: 3, vocabIndex: 29 },
  { q: "At the night market, my favorite stall sells grilled ______ on a stick. Each one costs fifty dollars.",
    options: ["shrimp","lamb","insect","dinosaur"], answer: 0, vocabIndex: 30 },
  { q: "After the rain, a tiny ______ moved slowly along the garden path. It left a shiny trail behind it.",
    options: ["mouse","hippo","snail","fox"], answer: 2, vocabIndex: 31 },
  { q: "During our hike, a long ______ suddenly crossed the path. Everyone screamed and quickly ran the other way.",
    options: ["snake","kangaroo","puppy","rat"], answer: 0, vocabIndex: 32 },
  { q: "When she opened the old box in the garage, a big ______ ran out quickly. She jumped back in surprise.",
    options: ["mosquito","spider","ant","dolphin"], answer: 1, vocabIndex: 33 },
  { q: "The little boy felt both scared and excited. It was the first time he had ever seen a real ______.",
    options: ["tiger","bug","donkey","crab"], answer: 0, vocabIndex: 34 },
  { q: "On the beach, we watched a ______ move slowly across the sand. It finally reached the calm sea.",
    options: ["shark","wolf","turtle","bee"], answer: 2, vocabIndex: 35 },
  { q: "Far out at sea, the passengers cheered loudly. A giant ______ rose slowly and sprayed water into the air.",
    options: ["shrimp","rat","lion","whale"], answer: 3, vocabIndex: 36 },
  { q: "Deep in the snowy forest, a lone gray ______ howled loudly. The bright full moon lit up the sky.",
    options: ["fish","goat","wolf","monkey"], answer: 2, vocabIndex: 37 },
  { q: "After the rain stopped, my little cousin found something on the garden path. A wet pink ______ was wriggling slowly.",
    options: ["mouse","worm","frog","snail"], answer: 1, vocabIndex: 38 },
  { q: "At the safari park, a herd of striped ______ grazed peacefully nearby. A small group of giraffes stood close by.",
    options: ["horses","donkeys","zebras","kangaroos"], answer: 2, vocabIndex: 39 },
];


// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "adorable": { pos: "adj.", en_def: "very cute and easy to love", cn_def: "可愛的" },
  "afternoon": { pos: "n.", en_def: "the part of the day between noon and evening", cn_def: "下午" },
  "amazed": { pos: "adj.", en_def: "very surprised", cn_def: "感到驚訝的" },
  "annoying": { pos: "adj.", en_def: "making you feel a little angry or impatient", cn_def: "令人討厭的" },
  "appeared": { pos: "v.", en_def: "came into view suddenly", cn_def: "出現" },
  "awe": { pos: "n.", en_def: "a feeling of wonder and amazement", cn_def: "敬畏；驚嘆" },
  "balcony": { pos: "n.", en_def: "a platform outside an upper window of a building", cn_def: "陽台" },
  "banana": { pos: "n.", en_def: "a long yellow fruit", cn_def: "香蕉" },
  "bedroom": { pos: "n.", en_def: "a room used for sleeping", cn_def: "臥室" },
  "birthday": { pos: "n.", en_def: "the day of the year a person was born", cn_def: "生日" },
  "boat": { pos: "n.", en_def: "a small vehicle that travels on water", cn_def: "船" },
  "branch": { pos: "n.", en_def: "a part of a tree that grows out from the trunk", cn_def: "樹枝" },
  "bread": { pos: "n.", en_def: "a common food made from flour and baked", cn_def: "麵包" },
  "bush": { pos: "n.", en_def: "a low plant with many woody branches", cn_def: "灌木叢" },
  "buzzing": { pos: "v.", en_def: "making a low humming sound, like an insect", cn_def: "發出嗡嗡聲" },
  "cage": { pos: "n.", en_def: "a box with bars used to keep an animal inside", cn_def: "籠子" },
  "calm": { pos: "adj.", en_def: "quiet and peaceful, without much movement", cn_def: "平靜的" },
  "carrots": { pos: "n.", en_def: "long orange vegetables", cn_def: "紅蘿蔔（複數）" },
  "carrying": { pos: "v.", en_def: "holding and moving something from one place to another", cn_def: "搬運" },
  "cheered": { pos: "v.", en_def: "shouted happily to show excitement", cn_def: "歡呼" },
  "chewed": { pos: "v.", en_def: "bit and crushed food with the teeth", cn_def: "咀嚼" },
  "classroom": { pos: "n.", en_def: "a room where students have lessons", cn_def: "教室" },
  "clever": { pos: "adj.", en_def: "smart; able to think quickly", cn_def: "聰明的" },
  "collecting": { pos: "v.", en_def: "gathering things together", cn_def: "收集" },
  "countryside": { pos: "n.", en_def: "land outside of cities, with farms and fields", cn_def: "鄉村" },
  "cousin": { pos: "n.", en_def: "the child of your aunt or uncle", cn_def: "表/堂兄弟姊妹" },
  "crawl": { pos: "v.", en_def: "to move slowly close to the ground", cn_def: "爬行" },
  "crawling": { pos: "v.", en_def: "moving slowly close to the ground", cn_def: "爬行中" },
  "crept": { pos: "v.", en_def: "moved slowly and quietly (past tense of creep)", cn_def: "悄悄地移動（過去式）" },
  "curious": { pos: "adj.", en_def: "wanting to know or learn about something", cn_def: "好奇的" },
  "delight": { pos: "n.", en_def: "great pleasure or happiness", cn_def: "高興；愉悅" },
  "disappear": { pos: "v.", en_def: "to go out of sight", cn_def: "消失" },
  "disappeared": { pos: "v.", en_def: "went out of sight", cn_def: "消失（過去式）" },
  "dozens": { pos: "n.", en_def: "many groups of twelve; a large number", cn_def: "數十；許多" },
  "enormous": { pos: "adj.", en_def: "extremely large in size", cn_def: "巨大的" },
  "excited": { pos: "adj.", en_def: "feeling happy and full of energy about something", cn_def: "興奮的" },
  "farmer": { pos: "n.", en_def: "a person who grows crops or raises animals for a living", cn_def: "農夫" },
  "farmhouse": { pos: "n.", en_def: "a house on a farm", cn_def: "農舍" },
  "field": { pos: "n.", en_def: "a piece of open land, often used for farming", cn_def: "田地" },
  "fields": { pos: "n.", en_def: "pieces of open land used for farming", cn_def: "田地（複數）" },
  "flew": { pos: "v.", en_def: "moved through the air (past tense of fly)", cn_def: "飛（過去式）" },
  "floated": { pos: "v.", en_def: "stayed on top of water without sinking", cn_def: "漂浮" },
  "fluffy": { pos: "adj.", en_def: "soft and light, like fur or feathers", cn_def: "毛茸茸的" },
  "frozen": { pos: "adj.", en_def: "unable to move, often from surprise or fear", cn_def: "僵住的" },
  "garage": { pos: "n.", en_def: "a building where a car is kept", cn_def: "車庫" },
  "garden": { pos: "n.", en_def: "an area of land where plants and flowers are grown", cn_def: "花園" },
  "gently": { pos: "adv.", en_def: "in a soft, careful way", cn_def: "輕柔地" },
  "giraffes": { pos: "n.", en_def: "tall African animals with very long necks", cn_def: "長頸鹿（複數）" },
  "grandfather": { pos: "n.", en_def: "the father of your mother or father", cn_def: "爺爺/外公" },
  "grandparents": { pos: "n.", en_def: "the parents of your mother or father", cn_def: "祖父母" },
  "grazed": { pos: "v.", en_def: "ate grass in a field (used for farm animals)", cn_def: "吃草" },
  "grilled": { pos: "adj.", en_def: "cooked over direct heat", cn_def: "烤的" },
  "guide": { pos: "n.", en_def: "a person who shows tourists around a place", cn_def: "導遊" },
  "happily": { pos: "adv.", en_def: "in a happy way", cn_def: "開心地" },
  "heavy": { pos: "adj.", en_def: "having a lot of weight", cn_def: "重的" },
  "herd": { pos: "n.", en_def: "a large group of animals that live or move together", cn_def: "獸群" },
  "hiding": { pos: "v.", en_def: "staying out of sight", cn_def: "躲藏中" },
  "hike": { pos: "n.", en_def: "a long walk, usually in nature", cn_def: "健行" },
  "hillside": { pos: "n.", en_def: "the sloped side of a hill", cn_def: "山坡" },
  "hopped": { pos: "v.", en_def: "jumped lightly (past tense of hop)", cn_def: "跳躍（過去式）" },
  "howled": { pos: "v.", en_def: "made a long loud crying sound, like a wolf", cn_def: "嗥叫" },
  "inspector": { pos: "n.", en_def: "a person whose job is to check that things are safe or correct", cn_def: "檢查員" },
  "jar": { pos: "n.", en_def: "a glass or plastic container, usually round", cn_def: "罐子" },
  "kept": { pos: "v.", en_def: "continued doing something (past tense of keep)", cn_def: "持續（過去式）" },
  "kitchen": { pos: "n.", en_def: "the room in a house where food is cooked", cn_def: "廚房" },
  "landed": { pos: "v.", en_def: "came down and stopped on a surface", cn_def: "降落" },
  "late": { pos: "adv.", en_def: "near the end of a period of time", cn_def: "晚地；遲" },
  "lazily": { pos: "adv.", en_def: "in a slow, relaxed way without much effort", cn_def: "懶洋洋地" },
  "leaves": { pos: "n.", en_def: "the flat green parts of a plant", cn_def: "葉子（複數）" },
  "lifeguard": { pos: "n.", en_def: "a person who watches swimmers and keeps them safe", cn_def: "救生員" },
  "lone": { pos: "adj.", en_def: "by itself; alone", cn_def: "孤獨的；單獨的" },
  "loudly": { pos: "adv.", en_def: "in a loud way; not quietly", cn_def: "大聲地" },
  "marched": { pos: "v.", en_def: "walked together in a line", cn_def: "行進（過去式）" },
  "market": { pos: "n.", en_def: "a place where food and goods are sold", cn_def: "市場" },
  "massive": { pos: "adj.", en_def: "very large and heavy", cn_def: "巨大的" },
  "minutes": { pos: "n.", en_def: "units of time, sixty seconds each", cn_def: "分鐘（複數）" },
  "moon": { pos: "n.", en_def: "the round object that shines in the sky at night", cn_def: "月亮" },
  "morning": { pos: "n.", en_def: "the early part of the day", cn_def: "早上" },
  "mountain": { pos: "n.", en_def: "a very high area of land", cn_def: "山" },
  "museum": { pos: "n.", en_def: "a building where interesting old or rare things are shown", cn_def: "博物館" },
  "nectar": { pos: "n.", en_def: "the sweet liquid inside flowers", cn_def: "花蜜" },
  "niece": { pos: "n.", en_def: "the daughter of your brother or sister", cn_def: "姪女/外甥女" },
  "ocean": { pos: "n.", en_def: "a very large area of salt water", cn_def: "海洋" },
  "park": { pos: "n.", en_def: "a public area with grass and trees for people to enjoy", cn_def: "公園" },
  "passengers": { pos: "n.", en_def: "people traveling in a vehicle, boat, or plane", cn_def: "乘客（複數）" },
  "path": { pos: "n.", en_def: "a narrow way for walking", cn_def: "小路" },
  "patient": { pos: "adj.", en_def: "able to wait calmly without getting upset", cn_def: "有耐心的" },
  "peacefully": { pos: "adv.", en_def: "in a calm, quiet way", cn_def: "平靜地" },
  "peanuts": { pos: "n.", en_def: "small nuts often eaten as a snack", cn_def: "花生" },
  "picked": { pos: "v.", en_def: "chose or lifted something", cn_def: "挑選；拿起" },
  "pieces": { pos: "n.", en_def: "small parts of something larger", cn_def: "片；塊" },
  "playful": { pos: "adj.", en_def: "liking to play and have fun", cn_def: "愛玩的" },
  "pool": { pos: "n.", en_def: "a small area filled with water", cn_def: "水池" },
  "quickly": { pos: "adv.", en_def: "in a fast way", cn_def: "快速地" },
  "quietly": { pos: "adv.", en_def: "without making much noise", cn_def: "安靜地" },
  "received": { pos: "v.", en_def: "got something that was given", cn_def: "收到" },
  "refrigerator": { pos: "n.", en_def: "a machine that keeps food cold", cn_def: "冰箱" },
  "restaurant": { pos: "n.", en_def: "a place where people pay to eat meals", cn_def: "餐廳" },
  "river": { pos: "n.", en_def: "a long natural flow of water", cn_def: "河流" },
  "rocky": { pos: "adj.", en_def: "covered with or full of rocks", cn_def: "多石的" },
  "rode": { pos: "v.", en_def: "sat on and controlled an animal or vehicle (past tense of ride)", cn_def: "騎（過去式）" },
  "safari": { pos: "n.", en_def: "a trip to see wild animals, usually in Africa", cn_def: "狩獵旅行" },
  "scared": { pos: "adj.", en_def: "feeling afraid", cn_def: "害怕的" },
  "screamed": { pos: "v.", en_def: "made a loud sharp cry, often from fear", cn_def: "尖叫" },
  "shore": { pos: "n.", en_def: "the land along the edge of the ocean", cn_def: "岸邊" },
  "skeleton": { pos: "n.", en_def: "the frame of bones inside a body", cn_def: "骨骸" },
  "slowly": { pos: "adv.", en_def: "not quickly; taking a long time", cn_def: "緩慢地" },
  "spotting": { pos: "v.", en_def: "noticing or seeing something suddenly", cn_def: "發現" },
  "sprayed": { pos: "v.", en_def: "sent out liquid in small drops", cn_def: "噴灑" },
  "steal": { pos: "v.", en_def: "to take something that is not yours", cn_def: "偷竊" },
  "steep": { pos: "adj.", en_def: "rising or falling sharply", cn_def: "陡峭的" },
  "stove": { pos: "n.", en_def: "a machine used for cooking food", cn_def: "爐子" },
  "strange": { pos: "adj.", en_def: "unusual or surprising", cn_def: "奇怪的" },
  "striped": { pos: "adj.", en_def: "having lines of different colors", cn_def: "有條紋的" },
  "suddenly": { pos: "adv.", en_def: "happening quickly and without warning", cn_def: "突然地" },
  "swimmers": { pos: "n.", en_def: "people who are swimming", cn_def: "游泳的人" },
  "tide": { pos: "n.", en_def: "the regular rise and fall of the ocean", cn_def: "潮汐" },
  "tourists": { pos: "n.", en_def: "people who travel to visit a place for fun", cn_def: "遊客（複數）" },
  "tour": { pos: "n.", en_def: "a trip to see a place or several places", cn_def: "旅遊" },
  "trail": { pos: "n.", en_def: "a path through nature, or a mark left behind", cn_def: "小徑；痕跡" },
  "vegetables": { pos: "n.", en_def: "plants or parts of plants eaten as food", cn_def: "蔬菜" },
  "wakes": { pos: "v.", en_def: "stops sleeping", cn_def: "醒來" },
  "warned": { pos: "v.", en_def: "told someone about a possible danger", cn_def: "警告" },
  "wet": { pos: "adj.", en_def: "covered in water or another liquid", cn_def: "濕的" },
  "wildlife": { pos: "n.", en_def: "wild animals living in their natural environment", cn_def: "野生動物" },
  "window": { pos: "n.", en_def: "an opening in a wall, usually with glass", cn_def: "窗戶" },
  "woolly": { pos: "adj.", en_def: "covered in soft thick wool", cn_def: "毛茸茸的（羊毛）" },
  "wriggling": { pos: "v.", en_def: "twisting and turning the body", cn_def: "蠕動" },
  "zoo": { pos: "n.", en_def: "a park where many kinds of animals are kept for people to see", cn_def: "動物園" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});

// ---- Plural aliases so MCQ option lookups (e.g. "ants", "dolphins") resolve correctly ----
const PLURAL_ALIASES = {
  "ants": "ant", "bees": "bee", "bugs": "bug", "butterflies": "butterfly",
  "cockroaches": "cockroach", "crabs": "crab", "dinosaurs": "dinosaur", "dogs": "dog",
  "dolphins": "dolphin", "donkeys": "donkey", "elephants": "elephant", "foxes": "fox",
  "frogs": "frog", "goats": "goat", "hippos": "hippo", "horses": "horse",
  "insects": "insect", "kangaroos": "kangaroo", "lambs": "lamb", "lions": "lion",
  "monkeys": "monkey", "mosquitoes": "mosquito", "mice": "mouse", "pigs": "pig",
  "puppies": "puppy", "rabbits": "rabbit", "rats": "rat", "sharks": "shark",
  "shrimps": "shrimp", "snails": "snail", "snakes": "snake", "spiders": "spider",
  "tigers": "tiger", "turtles": "turtle", "whales": "whale", "wolves": "wolf",
  "worms": "worm", "zebras": "zebra"
};
Object.keys(PLURAL_ALIASES).forEach(plural => {
  const singular = PLURAL_ALIASES[plural];
  if (!LOOKUP[plural] && LOOKUP[singular]) {
    LOOKUP[plural] = LOOKUP[singular];
  }
});
