// ============================================================
// Group 9 Quiz Data: Jobs / Professions
// Full word set (34 words) — jobs and professions from the
// "people / family / jobs / personality" theme. Continues from
// Group 8 (Family / People / Age / Titles). Roles/Characters/
// Personality traits will follow as Group 10.
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 9 - Jobs / Professions (職業)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (34 words) ----
const VOCAB = [
  { word: "job", pos: "n.", cn_def: "職業", en_def: "the work a person does regularly to earn money",
    sentence: "My father has a new {{BLANK}} at a company close to our apartment.",
    cn: "我爸爸在離我們公寓很近的一家公司找到了一份新工作。" },
  { word: "actor", pos: "n.", cn_def: "男演員", en_def: "a man who performs in movies, plays, or TV shows",
    sentence: "The famous {{BLANK}} signed autographs for fans outside the theater after the show.",
    cn: "那位知名男演員在演出後在劇院外為粉絲簽名。" },
  { word: "actress", pos: "n.", cn_def: "女演員", en_def: "a woman who performs in movies, plays, or TV shows",
    sentence: "The young {{BLANK}} practiced her lines every night before the big audition.",
    cn: "那位年輕女演員在重要試鏡前每晚都會練習她的台詞。" },
  { word: "model", pos: "n.", cn_def: "模特兒", en_def: "a person who wears clothes for photos or shows to sell products",
    sentence: "The fashion {{BLANK}} walked confidently down the runway in a bright red dress.",
    cn: "那位時尚模特兒穿著一條鮮紅色洋裝，自信地走在天橋上。" },
  { word: "magician", pos: "n.", cn_def: "魔術師", en_def: "a person who performs tricks that seem like magic",
    sentence: "At the birthday party, a {{BLANK}} pulled a white rabbit out of his hat.",
    cn: "在生日派對上，一位魔術師從帽子裡拉出一隻白兔。" },
  { word: "artist", pos: "n.", cn_def: "藝術家", en_def: "a person who creates paintings, drawings, or other works of art",
    sentence: "The {{BLANK}} spent the whole afternoon painting a colorful mural on the school wall.",
    cn: "那位藝術家花了整個下午在學校牆上畫了一幅色彩鮮豔的壁畫。" },
  { word: "musician", pos: "n.", cn_def: "音樂家", en_def: "a person who plays a musical instrument professionally",
    sentence: "The street {{BLANK}} played his violin beautifully near the entrance of the park.",
    cn: "那位街頭音樂家在公園入口附近優美地演奏著小提琴。" },
  { word: "scientist", pos: "n.", cn_def: "科學家", en_def: "a person who studies and does research in science",
    sentence: "The {{BLANK}} carefully recorded every result during the long laboratory experiment.",
    cn: "那位科學家在這場漫長的實驗室實驗中仔細記錄了每一個結果。" },
  { word: "writer", pos: "n.", cn_def: "作家", en_def: "a person who writes books, articles, or stories as a job",
    sentence: "The famous {{BLANK}} spent three years working on her newest novel.",
    cn: "那位知名作家花了三年時間創作她最新的小說。" },
  { word: "president", pos: "n.", cn_def: "總統", en_def: "the leader of a country or organization",
    sentence: "The {{BLANK}} gave an important speech about education on national television.",
    cn: "總統在全國電視上發表了一場關於教育的重要演說。" },
  { word: "diplomat", pos: "n.", cn_def: "外交官", en_def: "a person who represents their country in talks with other countries",
    sentence: "The {{BLANK}} traveled to several countries to discuss the new trade agreement.",
    cn: "那位外交官前往多個國家討論新的貿易協定。" },
  { word: "officer", pos: "n.", cn_def: "軍官", en_def: "a person who holds a position of command, such as in the army or police",
    sentence: "A police {{BLANK}} helped the lost tourist find her way back to the hotel.",
    cn: "一位警官幫助那位迷路的遊客找到回飯店的路。" },
  { word: "guard", pos: "n.", cn_def: "警衛", en_def: "a person whose job is to protect people or places",
    sentence: "The {{BLANK}} checked every visitor's bag before allowing them into the museum.",
    cn: "那位警衛在讓每位訪客進入博物館之前都會檢查他們的包包。" },
  { word: "judge", pos: "n.", cn_def: "法官", en_def: "a person who decides cases in a court of law",
    sentence: "The {{BLANK}} listened carefully to both sides before making a final decision.",
    cn: "那位法官在做出最終判決之前仔細聽取了雙方的說法。" },
  { word: "lawyer", pos: "n.", cn_def: "律師", en_def: "a person trained to give advice about laws and represent people in court",
    sentence: "My cousin hired a {{BLANK}} to help her understand the rental contract.",
    cn: "我表姐請了一位律師幫她了解租屋合約的內容。" },
  { word: "doctor", pos: "n.", cn_def: "醫生", en_def: "a person trained to treat sick or injured people",
    sentence: "The {{BLANK}} carefully examined the little boy's broken arm before wrapping it.",
    cn: "那位醫生在包紮之前仔細檢查了那個小男孩骨折的手臂。" },
  { word: "dentist", pos: "n.", cn_def: "牙醫", en_def: "a person trained to treat teeth and gums",
    sentence: "My little sister was nervous before her first visit to the {{BLANK}}.",
    cn: "我妹妹第一次看牙醫前感到非常緊張。" },
  { word: "nurse", pos: "n.", cn_def: "護士", en_def: "a person trained to care for sick or injured people, often in a hospital",
    sentence: "The kind {{BLANK}} checked on every patient in the room every hour.",
    cn: "那位親切的護士每小時都會去查看病房裡的每位病人。" },
  { word: "journalist", pos: "n.", cn_def: "新聞記者", en_def: "a person who writes news stories for newspapers, magazines, or websites",
    sentence: "The {{BLANK}} interviewed several witnesses right after the accident happened.",
    cn: "那位新聞記者在事故發生後立刻採訪了幾位目擊者。" },
  { word: "reporter", pos: "n.", cn_def: "記者", en_def: "a person who collects and presents news, often on TV or radio",
    sentence: "A {{BLANK}} stood outside the building, waiting to ask the mayor a question.",
    cn: "一位記者站在大樓外面，等著向市長提問。" },
  { word: "principal", pos: "n.", cn_def: "校長", en_def: "the person in charge of a school",
    sentence: "Our {{BLANK}} welcomed all the new students during the morning assembly.",
    cn: "我們的校長在早會時歡迎所有新生。" },
  { word: "professor", pos: "n.", cn_def: "教授", en_def: "a senior teacher at a college or university",
    sentence: "The {{BLANK}} explained the difficult theory using a simple, clear example.",
    cn: "那位教授用一個簡單清楚的例子解釋了那個困難的理論。" },
  { word: "teacher", pos: "n.", cn_def: "老師", en_def: "a person whose job is to help students learn",
    sentence: "Our English {{BLANK}} always makes grammar lessons fun with games.",
    cn: "我們的英文老師總是用遊戲讓文法課變得很有趣。" },
  { word: "engineer", pos: "n.", cn_def: "工程師", en_def: "a person who designs or builds machines, structures, or systems",
    sentence: "The {{BLANK}} checked every part of the bridge before it opened to traffic.",
    cn: "那位工程師在橋樑開放通行前檢查了每一個部件。" },
  { word: "priest", pos: "n.", cn_def: "牧師", en_def: "a religious leader who performs ceremonies in a church",
    sentence: "The {{BLANK}} spoke gently to comfort the family during the quiet ceremony.",
    cn: "那位牧師在這場安靜的儀式中溫和地安慰著那個家庭。" },
  { word: "coach", pos: "n.", cn_def: "教練", en_def: "a person who trains an athlete or sports team",
    sentence: "Our basketball {{BLANK}} made the whole team practice for two extra hours.",
    cn: "我們的籃球教練讓全隊額外練習了兩個小時。" },
  { word: "sailor", pos: "n.", cn_def: "水手", en_def: "a person who works on a ship",
    sentence: "The old {{BLANK}} told us exciting stories about his years at sea.",
    cn: "那位老水手跟我們講述了他多年航海生活的精彩故事。" },
  { word: "singer", pos: "n.", cn_def: "歌手", en_def: "a person who sings, especially as a profession",
    sentence: "The young {{BLANK}} performed her first concert in front of thousands of fans.",
    cn: "那位年輕歌手在數千名粉絲面前舉辦了她的第一場演唱會。" },
  { word: "businessman", pos: "n.", cn_def: "商人", en_def: "a man who works in business, often running a company",
    sentence: "The successful {{BLANK}} started his first small shop when he was only twenty.",
    cn: "那位成功的商人在二十歲時就開了他第一間小店。" },
  { word: "boss", pos: "n.", cn_def: "老闆", en_def: "the person who is in charge at work",
    sentence: "My {{BLANK}} praised our whole team for finishing the project early.",
    cn: "我老闆稱讚我們整個團隊提早完成了這個專案。" },
  { word: "secretary", pos: "n.", cn_def: "秘書", en_def: "a person who organizes schedules, letters, and other office tasks",
    sentence: "The busy {{BLANK}} answered the phone and scheduled three meetings before lunch.",
    cn: "那位忙碌的秘書接了電話，並在午餐前安排了三場會議。" },
  { word: "manager", pos: "n.", cn_def: "經理", en_def: "a person who is in charge of a department, store, or team",
    sentence: "The store {{BLANK}} trained the new employees on their very first day.",
    cn: "那家店的經理在新員工的第一天就對他們進行了培訓。" },
  { word: "clerk", pos: "n.", cn_def: "職員", en_def: "a person who works in an office or store handling records or sales",
    sentence: "The {{BLANK}} at the front desk politely explained how to fill out the form.",
    cn: "前台的那位職員很有禮貌地解釋了如何填寫這份表格。" },
  { word: "assistant", pos: "n.", cn_def: "助理", en_def: "a person who helps someone else with their work",
    sentence: "The doctor's {{BLANK}} called to remind me about my appointment tomorrow.",
    cn: "那位醫生的助理打電話來提醒我明天的預約。" }
];

// ---- Part 2 data: 34 MCQs ----
// CEFR A2 / 國中會考 level: exactly 2 sentences, ~18-30 words total,
// rich concrete context clue, one blank, simple surrounding vocabulary.
// Answer letters balanced across A/B/C/D (9/9/8/8), no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "My father just started working at a company near our home. He is very excited about his new ______.",
    options: ["hobby","job","school","trip"], answer: 1, vocabIndex: 0 },
  { q: "After the movie ended, fans waited outside the theater for a long time. The famous ______ kindly signed their notebooks.",
    options: ["actor","writer","singer","coach"], answer: 0, vocabIndex: 1 },
  { q: "Before her big audition, someone practiced lines every night in her room. The young ______ wanted to do her best.",
    options: ["dentist","actress","nurse","manager"], answer: 1, vocabIndex: 2 },
  { q: "On the runway, someone wore a bright red dress and walked with great confidence. The fashion ______ smiled at the cameras.",
    options: ["artist","officer","judge","model"], answer: 3, vocabIndex: 3 },
  { q: "At the birthday party, something amazing happened with a hat and a rabbit. The ______ surprised everyone with the trick.",
    options: ["scientist","magician","engineer","principal"], answer: 1, vocabIndex: 4 },
  { q: "On the school wall, someone spent hours creating something colorful and beautiful. The ______ finished the mural just before sunset.",
    options: ["lawyer","secretary","clerk","artist"], answer: 3, vocabIndex: 5 },
  { q: "Near the park entrance, someone played a violin so beautifully that people stopped to listen. The street ______ smiled and kept playing.",
    options: ["musician","sailor","diplomat","assistant"], answer: 0, vocabIndex: 6 },
  { q: "In the laboratory, someone wrote down every detail of a long, careful experiment. The ______ checked the results twice.",
    options: ["teacher","scientist","boss","guard"], answer: 1, vocabIndex: 7 },
  { q: "For three years, someone worked quietly on a brand-new story for readers everywhere. The famous ______ finally finished her novel.",
    options: ["journalist","reporter","writer","professor"], answer: 2, vocabIndex: 8 },
  { q: "On national television, someone gave an important speech about schools and learning. The ______ spoke clearly to the whole country.",
    options: ["president","officer","principal","coach"], answer: 0, vocabIndex: 9 },
  { q: "After visiting several countries, someone returned home to discuss a new trade agreement. The ______ had worked very hard.",
    options: ["lawyer","diplomat","businessman","manager"], answer: 1, vocabIndex: 10 },
  { q: "A tourist near the station looked lost and confused about which way to go. A kind ______ helped her find the hotel.",
    options: ["officer","judge","doctor","sailor"], answer: 0, vocabIndex: 11 },
  { q: "At the museum entrance, someone checked every bag carefully before letting visitors inside. The ______ worked there every single day.",
    options: ["clerk","assistant","secretary","guard"], answer: 3, vocabIndex: 12 },
  { q: "In the quiet courtroom, someone listened to both sides before making a final decision. The ______ spoke slowly and clearly.",
    options: ["lawyer","officer","judge","principal"], answer: 2, vocabIndex: 13 },
  { q: "Before signing the rental contract, my cousin wanted to understand every part of it. She hired a ______ for advice.",
    options: ["doctor","lawyer","engineer","professor"], answer: 1, vocabIndex: 14 },
  { q: "After the little boy fell off his bike, his arm hurt badly near the wrist. The ______ checked it carefully before wrapping it.",
    options: ["nurse","dentist","doctor","coach"], answer: 2, vocabIndex: 15 },
  { q: "My little sister felt very nervous about her appointment that afternoon. It was her very first visit to the ______.",
    options: ["doctor","dentist","hospital","nurse"], answer: 1, vocabIndex: 16 },
  { q: "In the hospital room, someone checked on every patient once every hour, all through the night. The kind ______ never seemed tired.",
    options: ["nurse","doctor","dentist","guard"], answer: 0, vocabIndex: 17 },
  { q: "Right after the accident, someone rushed over and began asking witnesses careful questions. The ______ wrote everything down quickly.",
    options: ["officer","lawyer","journalist","judge"], answer: 2, vocabIndex: 18 },
  { q: "Outside the city building, someone waited patiently to ask the mayor an important question. The ______ held a small microphone.",
    options: ["reporter","writer","professor","secretary"], answer: 0, vocabIndex: 19 },
  { q: "During the morning assembly, someone welcomed all the new students with a warm smile. Our school ______ spoke for ten minutes.",
    options: ["teacher","coach","principal","manager"], answer: 2, vocabIndex: 20 },
  { q: "In the university lecture hall, someone explained a difficult theory using one simple, clear example. The ______ made it easy to understand.",
    options: ["teacher","principal","scientist","professor"], answer: 3, vocabIndex: 21 },
  { q: "During English class, grammar lessons somehow always felt fun because of clever games. Our ______ made learning enjoyable every day.",
    options: ["professor","principal","teacher","assistant"], answer: 2, vocabIndex: 22 },
  { q: "Before the new bridge opened to traffic, every single part needed to be checked carefully. The ______ worked there for weeks.",
    options: ["scientist","engineer","artist","officer"], answer: 1, vocabIndex: 23 },
  { q: "During the quiet ceremony, someone spoke gently to comfort the grieving family. The ______ chose his words with great care.",
    options: ["judge","manager","priest","boss"], answer: 2, vocabIndex: 24 },
  { q: "Before the big game, the whole basketball team practiced for two extra hours that evening. Our ______ pushed everyone to do better.",
    options: ["principal","teacher","manager","coach"], answer: 3, vocabIndex: 25 },
  { q: "Sitting by the fire, someone told us amazing stories about many years spent traveling at sea. The old ______ had seen the whole world.",
    options: ["sailor","officer","diplomat","guard"], answer: 0, vocabIndex: 26 },
  { q: "In front of thousands of cheering fans, someone performed her very first full concert. The young ______ felt both nervous and excited.",
    options: ["actress","musician","singer","model"], answer: 2, vocabIndex: 27 },
  { q: "At only twenty years old, someone opened a tiny shop that later became very successful. The young ______ worked incredibly hard.",
    options: ["manager","businessman","clerk","secretary"], answer: 1, vocabIndex: 28 },
  { q: "After finishing the project ahead of schedule, the whole team felt proud of their hard work. My ______ praised everyone warmly.",
    options: ["coach","professor","officer","boss"], answer: 3, vocabIndex: 29 },
  { q: "Before lunch, three meetings needed to be scheduled and several calls had to be answered. The busy ______ handled it all calmly.",
    options: ["secretary","manager","clerk","assistant"], answer: 0, vocabIndex: 30 },
  { q: "On their very first day at the store, several new employees needed careful training and guidance. The store ______ showed them everything.",
    options: ["boss","secretary","clerk","manager"], answer: 3, vocabIndex: 31 },
  { q: "At the front desk, a visitor needed help understanding how to fill out a long form. The ______ explained each step politely.",
    options: ["clerk","secretary","assistant","manager"], answer: 0, vocabIndex: 32 },
  { q: "The day before my appointment, someone from the clinic called to remind me about the time. The doctor's ______ sounded very friendly.",
    options: ["nurse","secretary","clerk","assistant"], answer: 3, vocabIndex: 33 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "accident": { pos: "n.", en_def: "an unexpected event that causes harm or damage", cn_def: "意外；事故" },
  "agreement": { pos: "n.", en_def: "a formal arrangement between people or groups", cn_def: "協議" },
  "allowing": { pos: "v.", en_def: "letting something happen or letting someone do something", cn_def: "允許" },
  "apartment": { pos: "n.", en_def: "a set of rooms for living in, usually in a larger building", cn_def: "公寓" },
  "appointment": { pos: "n.", en_def: "an arranged time to meet someone or visit somewhere", cn_def: "預約" },
  "assembly": { pos: "n.", en_def: "a meeting of a whole school or group", cn_def: "集會" },
  "audition": { pos: "n.", en_def: "a short performance to test if someone is good enough for a role", cn_def: "試鏡；試演" },
  "autographs": { pos: "n.", en_def: "signatures from famous people", cn_def: "簽名（複數）" },
  "basketball": { pos: "n.", en_def: "a sport played with a round ball and a high hoop", cn_def: "籃球" },
  "birthday": { pos: "n.", en_def: "the day of the year a person was born", cn_def: "生日" },
  "bridge": { pos: "n.", en_def: "a structure built over a river or road so people can cross", cn_def: "橋" },
  "broken": { pos: "adj.", en_def: "damaged or split into pieces; not working", cn_def: "破碎的；骨折的" },
  "building": { pos: "n.", en_def: "a structure with walls and a roof", cn_def: "建築物" },
  "ceremony": { pos: "n.", en_def: "a formal event held for a special occasion", cn_def: "儀式" },
  "checked": { pos: "v.", en_def: "looked at something carefully to make sure it was right", cn_def: "檢查（過去式）" },
  "comfort": { pos: "v.", en_def: "to make someone feel less worried or sad", cn_def: "安慰" },
  "company": { pos: "n.", en_def: "a business that makes or sells things", cn_def: "公司" },
  "concert": { pos: "n.", en_def: "a public music performance", cn_def: "演唱會；音樂會" },
  "confidently": { pos: "adv.", en_def: "in a way that shows belief in oneself", cn_def: "自信地" },
  "contract": { pos: "n.", en_def: "a written agreement between two or more people", cn_def: "合約" },
  "countries": { pos: "n.", en_def: "nations; areas of land with their own government", cn_def: "國家（複數）" },
  "cousin": { pos: "n.", en_def: "the child of your aunt or uncle", cn_def: "表/堂兄弟姊妹" },
  "decision": { pos: "n.", en_def: "a choice made after thinking about something", cn_def: "決定" },
  "desk": { pos: "n.", en_def: "a piece of furniture used for writing or working", cn_def: "辦公桌" },
  "discuss": { pos: "v.", en_def: "to talk about something with other people", cn_def: "討論" },
  "dress": { pos: "n.", en_def: "a piece of clothing worn by women or girls", cn_def: "洋裝" },
  "education": { pos: "n.", en_def: "the process of teaching and learning", cn_def: "教育" },
  "employees": { pos: "n.", en_def: "people who work for a company", cn_def: "員工（複數）" },
  "entrance": { pos: "n.", en_def: "the way into a place", cn_def: "入口" },
  "examined": { pos: "v.", en_def: "looked at something closely and carefully", cn_def: "檢查（過去式）" },
  "example": { pos: "n.", en_def: "something used to show or explain an idea", cn_def: "例子" },
  "experiment": { pos: "n.", en_def: "a scientific test to learn something", cn_def: "實驗" },
  "explained": { pos: "v.", en_def: "made something clear or easy to understand", cn_def: "解釋（過去式）" },
  "fans": { pos: "n.", en_def: "people who admire and support someone", cn_def: "粉絲（複數）" },
  "fashion": { pos: "n.", en_def: "a popular style of clothing", cn_def: "時尚" },
  "fill out": { pos: "phr.", en_def: "to complete a form by writing information in it", cn_def: "填寫" },
  "form": { pos: "n.", en_def: "a paper document with spaces to fill in information", cn_def: "表格" },
  "grammar": { pos: "n.", en_def: "the rules for how words are used in a language", cn_def: "文法" },
  "hired": { pos: "v.", en_def: "gave someone a paid job", cn_def: "聘請（過去式）" },
  "hobby": { pos: "n.", en_def: "an activity done for fun in free time", cn_def: "愛好" },
  "hospital": { pos: "n.", en_def: "a place where sick or injured people are treated", cn_def: "醫院" },
  "hotel": { pos: "n.", en_def: "a building where travelers pay to stay overnight", cn_def: "飯店" },
  "important": { pos: "adj.", en_def: "having great value or meaning", cn_def: "重要的" },
  "interviewed": { pos: "v.", en_def: "asked someone questions to get information or a story", cn_def: "採訪（過去式）" },
  "laboratory": { pos: "n.", en_def: "a room used for scientific experiments", cn_def: "實驗室" },
  "lessons": { pos: "n.", en_def: "periods of teaching on a particular subject", cn_def: "課程（複數）" },
  "lines": { pos: "n.", en_def: "the words an actor says in a play or movie", cn_def: "台詞" },
  "listened": { pos: "v.", en_def: "paid attention to sound or speech", cn_def: "聆聽（過去式）" },
  "lost": { pos: "adj.", en_def: "unable to find one's way", cn_def: "迷路的" },
  "mayor": { pos: "n.", en_def: "the leader of a city or town's government", cn_def: "市長" },
  "meetings": { pos: "n.", en_def: "gatherings of people to discuss something", cn_def: "會議（複數）" },
  "mural": { pos: "n.", en_def: "a large painting made directly on a wall", cn_def: "壁畫" },
  "museum": { pos: "n.", en_def: "a building where interesting old or rare things are shown", cn_def: "博物館" },
  "national": { pos: "adj.", en_def: "relating to a whole country", cn_def: "全國的" },
  "nervous": { pos: "adj.", en_def: "worried or afraid about what might happen", cn_def: "緊張的" },
  "novel": { pos: "n.", en_def: "a long written story, usually fiction", cn_def: "小說" },
  "painting": { pos: "v.", en_def: "creating a picture using paint", cn_def: "繪畫" },
  "party": { pos: "n.", en_def: "a social event for celebration or fun", cn_def: "派對" },
  "patient": { pos: "n.", en_def: "a person who is receiving medical treatment", cn_def: "病人" },
  "performed": { pos: "v.", en_def: "did something in front of an audience", cn_def: "表演（過去式）" },
  "police": { pos: "n.", en_def: "the official group of people who keep order and enforce laws", cn_def: "警察" },
  "politely": { pos: "adv.", en_def: "in a way that shows good manners", cn_def: "禮貌地" },
  "practice": { pos: "v.", en_def: "to do something repeatedly to improve a skill", cn_def: "練習" },
  "praised": { pos: "v.", en_def: "expressed approval or admiration for someone", cn_def: "稱讚（過去式）" },
  "project": { pos: "n.", en_def: "a planned piece of work", cn_def: "專案" },
  "question": { pos: "n.", en_def: "something asked in order to get information", cn_def: "問題" },
  "recorded": { pos: "v.", en_def: "wrote down or saved information", cn_def: "記錄（過去式）" },
  "remind": { pos: "v.", en_def: "to help someone remember something", cn_def: "提醒" },
  "rental": { pos: "adj.", en_def: "relating to paying to use something for a period of time", cn_def: "租賃的" },
  "result": { pos: "n.", en_def: "something that happens because of an action or event", cn_def: "結果" },
  "runway": { pos: "n.", en_def: "a long narrow platform used for fashion shows", cn_def: "（時裝秀的）走道" },
  "scheduled": { pos: "v.", en_def: "planned for a particular time", cn_def: "安排（過去式）" },
  "school": { pos: "n.", en_def: "a place where children go to learn", cn_def: "學校" },
  "shop": { pos: "n.", en_def: "a small store that sells things", cn_def: "商店" },
  "show": { pos: "n.", en_def: "a performance for an audience", cn_def: "表演；節目" },
  "signed": { pos: "v.", en_def: "wrote one's name on something", cn_def: "簽名（過去式）" },
  "speech": { pos: "n.", en_def: "a talk given to an audience", cn_def: "演說" },
  "stories": { pos: "n.", en_def: "accounts of events, true or imagined", cn_def: "故事（複數）" },
  "students": { pos: "n.", en_def: "people who are studying at a school", cn_def: "學生（複數）" },
  "successful": { pos: "adj.", en_def: "having achieved a goal or done well", cn_def: "成功的" },
  "team": { pos: "n.", en_def: "a group of people playing or working together", cn_def: "隊伍；團隊" },
  "television": { pos: "n.", en_def: "a device used to watch shows and news", cn_def: "電視" },
  "theater": { pos: "n.", en_def: "a building where plays or movies are shown", cn_def: "劇院" },
  "theory": { pos: "n.", en_def: "an idea used to explain something", cn_def: "理論" },
  "tourist": { pos: "n.", en_def: "a person who travels to visit a place for fun", cn_def: "遊客" },
  "trade": { pos: "n.", en_def: "the buying and selling of goods between countries", cn_def: "貿易" },
  "traffic": { pos: "n.", en_def: "vehicles moving along a road", cn_def: "交通" },
  "trained": { pos: "v.", en_def: "taught someone the skills needed for a job", cn_def: "訓練（過去式）" },
  "traveled": { pos: "v.", en_def: "went from one place to another", cn_def: "旅行；前往（過去式）" },
  "trip": { pos: "n.", en_def: "a journey to a place", cn_def: "旅行" },
  "understand": { pos: "v.", en_def: "to know the meaning of something", cn_def: "理解" },
  "violin": { pos: "n.", en_def: "a small wooden musical instrument played with a bow", cn_def: "小提琴" },
  "wall": { pos: "n.", en_def: "a solid upright structure that forms the side of a building or room", cn_def: "牆" },
  "welcomed": { pos: "v.", en_def: "greeted someone in a friendly way", cn_def: "歡迎（過去式）" },
  "witnesses": { pos: "n.", en_def: "people who see an event happen", cn_def: "目擊者（複數）" },
  "wrapping": { pos: "v.", en_def: "covering something by winding material around it", cn_def: "包紮" }
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});

// ---- Plural aliases so MCQ option lookups resolve correctly ----
const PLURAL_ALIASES = {
  "actors": "actor", "actresses": "actress", "models": "model", "magicians": "magician",
  "artists": "artist", "musicians": "musician", "scientists": "scientist", "writers": "writer",
  "officers": "officer", "guards": "guard", "judges": "judge", "lawyers": "lawyer",
  "doctors": "doctor", "dentists": "dentist", "nurses": "nurse", "journalists": "journalist",
  "reporters": "reporter", "professors": "professor", "teachers": "teacher", "engineers": "engineer",
  "priests": "priest", "coaches": "coach", "sailors": "sailor", "singers": "singer",
  "bosses": "boss", "secretaries": "secretary", "managers": "manager", "clerks": "clerk",
  "assistants": "assistant"
};
Object.keys(PLURAL_ALIASES).forEach(plural => {
  const singular = PLURAL_ALIASES[plural];
  if (!LOOKUP[plural] && LOOKUP[singular]) {
    LOOKUP[plural] = LOOKUP[singular];
  }
});
