// ============================================================
// Group 40 Quiz Data: Home / Household / Objects, Part 2
// Full word set (36 words) — desk/door furniture, bedroom
// appliances, bathroom items, and basic tableware from the
// "home / household / objects" theme. Continues from Group 39
// (Home & Household, Part 1). This is the second of 5 groups
// (39-43) covering this theme at ~36 words per group.
// Continues the simpler/shorter MCQ style introduced in
// Group 37 (~16-26 words, 2 sentences, one blank).
// ============================================================

const QUIZ_CONFIG = {
  groupName: "Group 40 - Home / Household, Part 2 (居家環境 二)",
  gasEndpoint: "https://script.google.com/macros/s/AKfycbzLUqP-nauSjmiHfPXiK3NAV65tYdjAlwqip38TcGdTKqeR_CijuzHYxZDC-sjtRVrr_w/exec"
};

// ---- Part 1 data: spelling practice (36 words) ----
const VOCAB = [
  { word: "desk", pos: "n.", cn_def: "桌子", en_def: "a piece of furniture used for writing or working",
    sentence: "She keeps her pencils neatly arranged on her {{BLANK}}.",
    cn: "她把鉛筆整齊地排放在書桌上。" },
  { word: "table", pos: "n.", cn_def: "桌子", en_def: "a piece of furniture with a flat top and legs",
    sentence: "We placed the birthday cake in the middle of the {{BLANK}}.",
    cn: "我們把生日蛋糕放在桌子中間。" },
  { word: "door", pos: "n.", cn_def: "門", en_def: "a barrier used to open or close an entrance",
    sentence: "He knocked twice on the {{BLANK}} before walking inside.",
    cn: "他在進去之前在門上敲了兩次。" },
  { word: "drawer", pos: "n.", cn_def: "抽屜", en_def: "a sliding storage box built into furniture",
    sentence: "She keeps her socks folded neatly in the top {{BLANK}}.",
    cn: "她把襪子整齊地折好放在最上層的抽屜裡。" },
  { word: "dresser", pos: "n.", cn_def: "梳妝台", en_def: "a piece of furniture with drawers for clothes",
    sentence: "He set his keys and wallet on the {{BLANK}} every night.",
    cn: "他每晚都把鑰匙和錢包放在梳妝台上。" },
  { word: "comb", pos: "n.", cn_def: "梳子", en_def: "a flat object with teeth used to arrange hair",
    sentence: "She always carries a small {{BLANK}} inside her school bag.",
    cn: "她的書包裡總是放著一把小梳子。" },
  { word: "conditioner", pos: "n.", cn_def: "冷氣機", en_def: "a machine that cools the air in a room",
    sentence: "We turned on the {{BLANK}} because the afternoon was so hot.",
    cn: "因為下午太熱了，我們打開了冷氣機。" },
  { word: "heater", pos: "n.", cn_def: "暖氣機", en_def: "a device that makes a room warmer",
    sentence: "She turned on the {{BLANK}} as soon as winter began.",
    cn: "冬天一開始她就打開了暖氣機。" },
  { word: "fan", pos: "n.", cn_def: "電扇", en_def: "a device that moves air to keep you cool",
    sentence: "He pointed the small {{BLANK}} toward his desk while studying.",
    cn: "他唸書時把小電扇對著書桌吹。" },
  { word: "alarm", pos: "n.", cn_def: "鬧鐘", en_def: "a device that makes a sound to wake you up",
    sentence: "She forgot to set her {{BLANK}} and woke up late.",
    cn: "她忘了設定鬧鐘，結果起床晚了。" },
  { word: "clock", pos: "n.", cn_def: "時鐘", en_def: "a device that shows the time",
    sentence: "The {{BLANK}} on the wall said it was almost midnight.",
    cn: "牆上的時鐘顯示快到午夜了。" },
  { word: "lamp", pos: "n.", cn_def: "檯燈", en_def: "a light that sits on a desk or table",
    sentence: "She turned on the {{BLANK}} to read her book in bed.",
    cn: "她打開檯燈在床上看書。" },
  { word: "mirror", pos: "n.", cn_def: "鏡子", en_def: "a glass surface that shows your reflection",
    sentence: "He checked his hair in the {{BLANK}} before leaving the house.",
    cn: "他出門前在鏡子前檢查了一下頭髮。" },
  { word: "pillow", pos: "n.", cn_def: "枕頭", en_def: "a soft cushion used to support your head while sleeping",
    sentence: "She hugged her favorite {{BLANK}} as she fell asleep.",
    cn: "她抱著最喜歡的枕頭就睡著了。" },
  { word: "radio", pos: "n.", cn_def: "收音機", en_def: "a device used to listen to broadcast sound",
    sentence: "My father likes to listen to the {{BLANK}} while driving.",
    cn: "我爸爸開車時喜歡聽收音機。" },
  { word: "telephone", pos: "n.", cn_def: "電話", en_def: "a device used to talk to someone far away",
    sentence: "The {{BLANK}} rang loudly just as we sat down for dinner.",
    cn: "我們剛坐下吃晚餐時電話就響了。" },
  { word: "TV", pos: "n.", cn_def: "電視", en_def: "a device used to watch shows and movies",
    sentence: "They gathered around the {{BLANK}} to watch the big game.",
    cn: "他們聚在電視機前看這場重要的比賽。" },
  { word: "decorate", pos: "v.", cn_def: "裝飾", en_def: "to make something look nicer by adding things",
    sentence: "We spent the afternoon helping {{BLANK}} the classroom for the party.",
    cn: "我們整個下午都在幫忙裝飾教室準備派對。" },
  { word: "design", pos: "v.", cn_def: "設計", en_def: "to plan how something will look or work",
    sentence: "She wants to {{BLANK}} her own clothes someday.",
    cn: "她希望有一天能設計自己的衣服。" },
  { word: "bath", pos: "n.", cn_def: "沐浴", en_def: "the act of washing your whole body in water",
    sentence: "She likes to take a warm {{BLANK}} before going to bed.",
    cn: "她喜歡睡前洗一個溫暖的澡。" },
  { word: "faucet", pos: "n.", cn_def: "水龍頭", en_def: "a device used to control water flow from a pipe",
    sentence: "He forgot to turn off the {{BLANK}} after washing his hands.",
    cn: "他洗完手後忘了關水龍頭。" },
  { word: "toilet", pos: "n.", cn_def: "馬桶", en_def: "a bathroom fixture used for waste removal",
    sentence: "Please remember to flush the {{BLANK}} after you use it.",
    cn: "使用馬桶後請記得沖水。" },
  { word: "tub", pos: "n.", cn_def: "浴缸", en_def: "a large container filled with water for bathing",
    sentence: "She filled the {{BLANK}} with warm water and bubbles.",
    cn: "她在浴缸裡裝滿溫水和泡泡。" },
  { word: "toothbrush", pos: "n.", cn_def: "牙刷", en_def: "a small brush used to clean teeth",
    sentence: "He keeps his {{BLANK}} in a cup by the sink.",
    cn: "他把牙刷放在水槽旁的杯子裡。" },
  { word: "towel", pos: "n.", cn_def: "毛巾", en_def: "a piece of cloth used to dry yourself",
    sentence: "She wrapped a soft {{BLANK}} around her wet hair.",
    cn: "她用一條柔軟的毛巾包住濕頭髮。" },
  { word: "soap", pos: "n.", cn_def: "肥皂", en_def: "a substance used with water to clean your skin",
    sentence: "Please wash your hands with {{BLANK}} before dinner tonight.",
    cn: "今晚晚餐前請用肥皂洗手。" },
  { word: "dryer", pos: "n.", cn_def: "烘乾機", en_def: "a machine that removes moisture from wet clothes",
    sentence: "She put the wet towels straight into the {{BLANK}}.",
    cn: "她把濕毛巾直接放進烘乾機裡。" },
  { word: "shower", pos: "n.", cn_def: "陣雨", en_def: "a device that sprays water for washing your body",
    sentence: "He takes a quick {{BLANK}} every morning before school.",
    cn: "他每天早上上學前都會快速沖個澡。" },
  { word: "bathe", pos: "v.", cn_def: "把…浸入", en_def: "to wash your whole body in water",
    sentence: "The mother carefully began to {{BLANK}} her tiny newborn baby.",
    cn: "媽媽小心地開始幫她剛出生的小寶寶洗澡。" },
  { word: "bottle", pos: "n.", cn_def: "瓶子", en_def: "a container used for holding liquids",
    sentence: "She carries a reusable water {{BLANK}} to school every day.",
    cn: "她每天都帶著一個可重複使用的水瓶去上學。" },
  { word: "lid", pos: "n.", cn_def: "蓋子", en_def: "a cover that fits over the top of a container",
    sentence: "He twisted the {{BLANK}} off the jar of jam.",
    cn: "他把果醬罐子的蓋子扭開了。" },
  { word: "bowl", pos: "n.", cn_def: "碗", en_def: "a round, deep dish used for food",
    sentence: "She poured cereal and milk into a clean {{BLANK}}.",
    cn: "她把麥片和牛奶倒進一個乾淨的碗裡。" },
  { word: "chopsticks", pos: "n.", cn_def: "筷子", en_def: "a pair of thin sticks used for eating food",
    sentence: "My grandfather taught me how to use {{BLANK}} when I was young.",
    cn: "我小時候，爺爺教我怎麼用筷子。" },
  { word: "cup", pos: "n.", cn_def: "杯子", en_def: "a small container used for drinking",
    sentence: "He poured hot tea into his favorite {{BLANK}}.",
    cn: "他把熱茶倒進他最喜歡的杯子裡。" },
  { word: "glass", pos: "n.", cn_def: "玻璃杯", en_def: "a drinking container made of clear material",
    sentence: "She filled a tall {{BLANK}} with cold lemonade.",
    cn: "她把一個高玻璃杯裝滿冰涼的檸檬水。" },
  { word: "dish", pos: "n.", cn_def: "盤子", en_def: "a shallow container used for serving food",
    sentence: "He carefully washed every {{BLANK}} after the big dinner.",
    cn: "他在這場盛大的晚餐後仔細洗了每一個盤子。" }
];

// ---- Part 2 data: 36 MCQs ----
// Continuing the simpler/shorter MCQ style from Group 37:
// ~16-26 words, exactly 2 sentences, one blank, 4 options.
// Answer letters balanced across A/B/C/D, no adjacent repeats.
// vocabIndex points to the exact VOCAB array entry being tested.
const MCQS = [
  { q: "She always likes to keep her study area organized. Her pencils are arranged neatly on her ______.",
    options: ["desk", "drawer", "dresser", "lamp"], answer: 0, vocabIndex: 0 },
  { q: "It was time to celebrate with the whole family. We placed the cake in the middle of the ______.",
    options: ["chair", "table", "dish", "bowl"], answer: 1, vocabIndex: 1 },
  { q: "He arrived at his friend's house a little nervous. He knocked twice on the ______ before walking inside.",
    options: ["window", "drawer", "door", "lid"], answer: 2, vocabIndex: 2 },
  { q: "She likes everything in her room to be tidy. Her socks are folded neatly in the top ______.",
    options: ["shelf", "closet", "lid", "drawer"], answer: 3, vocabIndex: 3 },
  { q: "He has a small routine before going to bed each night. He sets his keys and wallet on the ______.",
    options: ["dresser", "desk", "table", "shelf"], answer: 0, vocabIndex: 4 },
  { q: "Her hair gets messy during the school day sometimes. She always carries a small ______ in her bag.",
    options: ["mirror", "comb", "towel", "soap"], answer: 1, vocabIndex: 5 },
  { q: "The afternoon was unusually warm and humid this week. We turned on the ______ to cool the room down.",
    options: ["heater", "fan", "conditioner", "dryer"], answer: 2, vocabIndex: 6 },
  { q: "The first cold morning of the season had finally arrived. She turned on the ______ as winter began.",
    options: ["conditioner", "fan", "radio", "heater"], answer: 3, vocabIndex: 7 },
  { q: "It was hot in his room while he studied for the test. He pointed the small ______ toward his desk.",
    options: ["fan", "heater", "lamp", "clock"], answer: 0, vocabIndex: 8 },
  { q: "She had an important test early the next morning. She forgot to set her ______ and woke up late.",
    options: ["clock", "alarm", "radio", "lamp"], answer: 1, vocabIndex: 9 },
  { q: "It was very late, and everyone was finally getting tired. The ______ on the wall showed it was almost midnight.",
    options: ["mirror", "lamp", "clock", "alarm"], answer: 2, vocabIndex: 10 },
  { q: "She likes to read for a while before falling asleep. She turned on the ______ to read in bed.",
    options: ["fan", "heater", "radio", "lamp"], answer: 3, vocabIndex: 11 },
  { q: "He wanted his hair to look neat before school. He checked it in the ______ before leaving the house.",
    options: ["mirror", "window", "lamp", "clock"], answer: 0, vocabIndex: 12 },
  { q: "She has a favorite soft cushion she sleeps with every night. She hugged her favorite ______ as she fell asleep.",
    options: ["blanket", "pillow", "towel", "bowl"], answer: 1, vocabIndex: 13 },
  { q: "He enjoys listening to music and talk shows on the road. My father likes to listen to the ______ while driving.",
    options: ["telephone", "TV", "radio", "alarm"], answer: 2, vocabIndex: 14 },
  { q: "Dinner had just started when something unexpected happened. The ______ rang loudly just as we sat down to eat.",
    options: ["alarm", "clock", "radio", "telephone"], answer: 3, vocabIndex: 15 },
  { q: "There was an important sports event everyone wanted to see. They gathered around the ______ to watch the big game.",
    options: ["TV", "radio", "telephone", "clock"], answer: 0, vocabIndex: 16 },
  { q: "A class party was being planned for the following week. We spent the afternoon helping ______ the classroom.",
    options: ["design", "decorate", "bathe", "share"], answer: 1, vocabIndex: 17 },
  { q: "She dreams of becoming a fashion creator one day. She wants to ______ her own clothes someday.",
    options: ["decorate", "bathe", "design", "wash"], answer: 2, vocabIndex: 18 },
  { q: "Relaxing before bedtime is part of her nightly routine. She likes to take a warm ______ before going to bed.",
    options: ["shower", "swim", "soap", "bath"], answer: 3, vocabIndex: 19 },
  { q: "He was in a hurry and didn't notice the running water. He forgot to turn off the ______ after washing his hands.",
    options: ["faucet", "toilet", "shower", "tub"], answer: 0, vocabIndex: 20 },
  { q: "Good bathroom habits matter, especially in shared spaces. Please remember to flush the ______ after you use it.",
    options: ["sink", "toilet", "tub", "faucet"], answer: 1, vocabIndex: 21 },
  { q: "She wanted a relaxing soak after a long, tiring day. She filled the ______ with warm water and bubbles.",
    options: ["sink", "bowl", "tub", "cup"], answer: 2, vocabIndex: 22 },
  { q: "Good morning habits include taking care of your teeth. He keeps his ______ in a cup by the sink.",
    options: ["soap", "comb", "towel", "toothbrush"], answer: 3, vocabIndex: 23 },
  { q: "She just got out of the shower and her hair was dripping wet. She wrapped a soft ______ around it.",
    options: ["towel", "blanket", "pillow", "curtain"], answer: 0, vocabIndex: 24 },
  { q: "It's important to wash your hands properly before eating. Please wash your hands with ______ before dinner tonight.",
    options: ["water", "soap", "shampoo", "lotion"], answer: 1, vocabIndex: 25 },
  { q: "The laundry was finished, but the towels were still damp. She put the wet towels straight into the ______.",
    options: ["washer", "tub", "dryer", "sink"], answer: 2, vocabIndex: 26 },
  { q: "He doesn't have much time before school starts each day. He takes a quick ______ every morning before school.",
    options: ["bath", "nap", "rest", "shower"], answer: 3, vocabIndex: 27 },
  { q: "The new baby needed gentle care from her very first days. The mother carefully began to ______ her tiny newborn.",
    options: ["bathe", "wash", "dry", "clean"], answer: 0, vocabIndex: 28 },
  { q: "Staying hydrated is important, especially during the school day. She carries a reusable water ______ to school every day.",
    options: ["cup", "bottle", "glass", "bowl"], answer: 1, vocabIndex: 29 },
  { q: "He wanted some jam to spread on his toast this morning. He twisted the ______ off the jar of jam.",
    options: ["cup", "dish", "lid", "bowl"], answer: 2, vocabIndex: 30 },
  { q: "Breakfast was simple but satisfying that morning. She poured cereal and milk into a clean ______.",
    options: ["cup", "glass", "dish", "bowl"], answer: 3, vocabIndex: 31 },
  { q: "Learning to eat with traditional utensils takes some practice. My grandfather taught me how to use ______ when I was young.",
    options: ["chopsticks", "spoons", "forks", "knives"], answer: 0, vocabIndex: 32 },
  { q: "He wanted to enjoy a hot drink before starting his homework. He poured hot tea into his favorite ______.",
    options: ["bowl", "cup", "dish", "lid"], answer: 1, vocabIndex: 33 },
  { q: "It was a hot afternoon, and she needed something refreshing. She filled a tall ______ with cold lemonade.",
    options: ["bowl", "dish", "glass", "cup"], answer: 2, vocabIndex: 34 },
  { q: "After the big family dinner, there was plenty of cleaning to do. He carefully washed every ______ afterward.",
    options: ["cup", "glass", "lid", "dish"], answer: 3, vocabIndex: 35 },
];

// ---- LOOKUP table built from VOCAB ----
const LOOKUP = {};
VOCAB.forEach(v => {
  const key = v.word.toLowerCase();
  if (LOOKUP[key]) {
    LOOKUP[key].combined.push({ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def });
  } else {
    LOOKUP[key] = {
      pos: v.pos,
      en_def: v.en_def,
      cn_def: v.cn_def,
      combined: [{ pos: v.pos, en_def: v.en_def, cn_def: v.cn_def }]
    };
  }
});

// ---- Hand-checked Chinese glosses for supporting words used in this group's sentences ----
const EXTRA_GLOSSES = {
  "bubbles": { pos: "n.", en_def: "small balls of air or foam in liquid", cn_def: "泡泡（複數）" },
  "cereal": { pos: "n.", en_def: "a breakfast food made from grain", cn_def: "穀片" },
  "chair": { pos: "n.", en_def: "a piece of furniture for one person to sit on", cn_def: "椅子" },
  "clean": { pos: "v.", en_def: "to remove dirt from something", cn_def: "清潔" },
  "closet": { pos: "n.", en_def: "a small room or cabinet used for storage", cn_def: "衣櫥" },
  "curtain": { pos: "n.", en_def: "a piece of cloth hung over a window", cn_def: "窗簾" },
  "dry": { pos: "v.", en_def: "to remove water or moisture from something", cn_def: "使乾燥" },
  "fashion": { pos: "n.", en_def: "popular styles of clothing", cn_def: "時尚；流行" },
  "forks": { pos: "n.", en_def: "tools with prongs used for eating", cn_def: "叉子（複數）" },
  "humid": { pos: "adj.", en_def: "containing a lot of moisture in the air", cn_def: "潮濕的" },
  "jam": { pos: "n.", en_def: "a sweet spread made from fruit", cn_def: "果醬" },
  "jar": { pos: "n.", en_def: "a glass or plastic container with a wide opening", cn_def: "罐子" },
  "knives": { pos: "n.", en_def: "tools with a blade used for cutting", cn_def: "刀子（複數）" },
  "laundry": { pos: "n.", en_def: "clothes that need to be washed or have been washed", cn_def: "待洗（或洗好）的衣物" },
  "lemonade": { pos: "n.", en_def: "a sweet drink made from lemons", cn_def: "檸檬水" },
  "lotion": { pos: "n.", en_def: "a liquid used to soften or protect the skin", cn_def: "乳液" },
  "midnight": { pos: "n.", en_def: "twelve o'clock at night", cn_def: "午夜" },
  "nap": { pos: "n.", en_def: "a short sleep, usually during the day", cn_def: "小睡" },
  "newborn": { pos: "n.", en_def: "a baby that has just been born", cn_def: "新生兒" },
  "rest": { pos: "n.", en_def: "a period of relaxing or sleeping", cn_def: "休息" },
  "reusable": { pos: "adj.", en_def: "able to be used again", cn_def: "可重複使用的" },
  "routine": { pos: "n.", en_def: "a regular way of doing things", cn_def: "慣例；常規" },
  "shampoo": { pos: "n.", en_def: "a liquid soap used to wash hair", cn_def: "洗髮精" },
  "share": { pos: "v.", en_def: "to have or use something together with others", cn_def: "分擔；分享" },
  "shelf": { pos: "n.", en_def: "a flat surface used for holding objects", cn_def: "架子" },
  "sink": { pos: "n.", en_def: "a basin used for washing, usually with a faucet", cn_def: "洗手台；水槽" },
  "soak": { pos: "n.", en_def: "a period of sitting in water to relax", cn_def: "泡澡" },
  "spoons": { pos: "n.", en_def: "tools with a small bowl shape used for eating", cn_def: "湯匙（複數）" },
  "swim": { pos: "v.", en_def: "to move through water using the body", cn_def: "游泳" },
  "toast": { pos: "n.", en_def: "bread that has been browned by heat", cn_def: "吐司" },
  "utensils": { pos: "n.", en_def: "tools used for eating or cooking", cn_def: "餐具（複數）" },
  "blanket": { pos: "n.", en_def: "a covering used to keep warm in bed", cn_def: "毯子" },
  "washer": { pos: "n.", en_def: "a machine used to wash clothes", cn_def: "洗衣機" },
  "wash": { pos: "v.", en_def: "to clean something with water", cn_def: "洗" },
  "water": { pos: "n.", en_def: "a clear liquid needed for life", cn_def: "水" },
  "window": { pos: "n.", en_def: "an opening in a wall, usually covered with glass", cn_def: "窗戶" },
};
Object.keys(EXTRA_GLOSSES).forEach(key => {
  const g = EXTRA_GLOSSES[key];
  if (!LOOKUP[key]) {
    LOOKUP[key] = { pos: g.pos, en_def: g.en_def, cn_def: g.cn_def, combined: [g] };
  }
});
